import "server-only";
import { FX_COMMODITY_ARITHMETIC_MODE, FX_COMMODITY_FORMULA_VERSION, FX_COMMODITY_MODEL_ID, evaluateFxCommodity } from "./fx-commodity-core";
import { decimalToPresentationNumber, domainErrorMessage, isCanonicalDecimalSource, type Decimal, type DecimalSource } from "./pro-decimal-domain";
import type { ProFormulaResult } from "./pro-formula-contract"; import { PRO_SAMPLE_INPUTS } from "./pro-sample-inputs";
export const toolKey = "fx-commodity-pass-through-pricer"; export const formulaVersion = FX_COMMODITY_FORMULA_VERSION; export const arithmeticMode = FX_COMMODITY_ARITHMETIC_MODE; export const modelId = FX_COMMODITY_MODEL_ID; export const verificationEvidenceId = "tests/pro-calculation-correctness/fx-commodity.property.test.ts"; export const sampleInputs = PRO_SAMPLE_INPUTS[toolKey];
const REQUIRED = ["n_base_price", "n_fx_rate_spot", "n_fx_rate_budget", "n_commodity_index_current", "n_commodity_index_budget", "n_material_cost_pct", "n_fx_hedge_pct", "n_commodity_hedge_pct", "n_annual_volume", "n_source_confidence_ratio"] as const;
function blocked(warnings: string[]): ProFormulaResult { return { status: "BLOCKED", outputs: {}, decimalOutputs: {}, warnings, outputKeys: [], redaction_status: "PUBLIC_SAFE_REDACTED" }; }
export function calculate(inputs: Record<string, DecimalSource>): ProFormulaResult {
  const invalid = REQUIRED.filter((key) => !isCanonicalDecimalSource(inputs[key])); if (invalid.length) return blocked([`Missing or non-finite normalized inputs: ${invalid.join(", ")}.`]);
  const evaluated = evaluateFxCommodity({ basePrice: inputs.n_base_price, currentFxRate: inputs.n_fx_rate_spot, budgetFxRate: inputs.n_fx_rate_budget,
    currentCommodityIndex: inputs.n_commodity_index_current, budgetCommodityIndex: inputs.n_commodity_index_budget, materialCostShareRatio: inputs.n_material_cost_pct,
    fxHedgeRatio: inputs.n_fx_hedge_pct, commodityHedgeRatio: inputs.n_commodity_hedge_pct, annualVolume: inputs.n_annual_volume, sourceConfidenceRatio: inputs.n_source_confidence_ratio });
  if (!evaluated.ok) return blocked([domainErrorMessage(evaluated.error)]); const v = evaluated.value;
  const exact: Array<readonly [string, Decimal]> = [["out_fx_market_factor",v.fxMarketFactor],["out_commodity_market_factor",v.commodityMarketFactor],["out_hedge_adjusted_fx_factor",v.hedgeAdjustedFxFactor],["out_hedge_adjusted_commodity_factor",v.hedgeAdjustedCommodityFactor],["out_combined_material_factor",v.combinedMaterialFactor],["out_non_material_price_component",v.nonMaterialPriceComponent],["out_material_price_component",v.materialPriceComponent],["out_fx_price_impact",v.fxPriceImpact],["out_commodity_interaction_price_impact",v.commodityAndInteractionPriceImpact],["out_total_price_adjustment",v.totalPriceAdjustment],["out_pass_through_ratio",v.passThroughRatio],["out_adjusted_price",v.adjustedPrice],["out_annual_base_revenue",v.annualBaseRevenue],["out_annual_adjusted_revenue",v.annualAdjustedRevenue],["out_annual_price_adjustment",v.annualPriceAdjustment],["out_source_confidence_ratio",v.sourceConfidenceRatio],["out_price_adjustment_uncertainty",v.priceAdjustmentUncertainty],["out_adjusted_price_lower_bound",v.adjustedPriceLowerBound],["out_adjusted_price_upper_bound",v.adjustedPriceUpperBound],["out_annual_money_at_risk",v.annualMoneyAtRisk]];
  const outputs: Record<string, number> = {}; const decimalOutputs: Record<string, string> = {}; for (const [id,x] of exact) { const p=decimalToPresentationNumber(x,id); if(!p.ok)return blocked([domainErrorMessage(p.error)]); outputs[id]=p.value; decimalOutputs[id]=x.toString(); }
  outputs.out_primary_market_driver=v.primaryMarketDriver; outputs.out_adjustment_direction=v.adjustmentDirection; outputs.out_decision_state=v.decisionState;
  decimalOutputs.out_primary_market_driver=String(v.primaryMarketDriver); decimalOutputs.out_adjustment_direction=String(v.adjustmentDirection); decimalOutputs.out_decision_state=String(v.decisionState);
  const warnings=v.decisionState===1?["The evidence-adjusted price interval still crosses the base price; review market and hedge evidence before applying pass-through."]:[];
  return {status:warnings.length?"REVIEW":"OK",outputs,decimalOutputs,warnings,outputKeys:Object.keys(outputs),redaction_status:"PUBLIC_SAFE_REDACTED"};
}
