// SectorCalc PRO Engine Governance — AUTO-GENERATED REGISTRY
// Generated by scripts/generate-pro-formula-registry.mjs
// Do not edit manually. Re-generate by running: node scripts/generate-pro-formula-registry.mjs
//
// LIVE_TOOLS=20
// GENERATED_AT=2026-07-08T13:47:08.214Z

import type { ProFormulaModule } from "./resolve-formula-module";

import * as mod_0 from "./break-even-survival-cash-calculator.formula";
import * as mod_1 from "./machine-hourly-rate-proof-report.formula";
import * as mod_2 from "./loss-making-job-detector.formula";
import * as mod_3 from "./receivables-cost-payment-term-addendum.formula";
import * as mod_4 from "./setup-time-reduction-roi-smed.formula";
import * as mod_5 from "./product-sku-margin-ranker.formula";
import * as mod_6 from "./true-employee-cost-statement.formula";
import * as mod_7 from "./job-quote-builder-pro-pack.formula";
import * as mod_8 from "./machine-investment-feasibility-buy-lease-keep.formula";
import * as mod_9 from "./capital-equipment-investment-appraisal-npv-irr.formula";
import * as mod_10 from "./customer-sku-profitability-forensics.formula";
import * as mod_11 from "./downtime-scrap-loss-statement.formula";
import * as mod_12 from "./oee-loss-monetization-improvement-business-case.formula";
import * as mod_13 from "./scrap-rework-cost-tracker.formula";
import * as mod_14 from "./outsource-vs-in-house-analyzer.formula";
import * as mod_15 from "./plant-wide-shop-rate-cost-structure-audit.formula";
import * as mod_16 from "./fx-commodity-pass-through-pricer.formula";
import * as mod_17 from "./energy-efficiency-grant-incentive-feasibility-pack.formula";
import * as mod_18 from "./motor-compressor-replacement-roi.formula";
import * as mod_19 from "./weld-procedure-cost-consumable-estimation-suite.formula";

export const GENERATED_FORMULA_REGISTRY: Record<string, ProFormulaModule> = {
  "break-even-survival-cash-calculator": mod_0,
  "machine-hourly-rate-proof-report": mod_1,
  "loss-making-job-detector": mod_2,
  "receivables-cost-payment-term-addendum": mod_3,
  "setup-time-reduction-roi-smed": mod_4,
  "product-sku-margin-ranker": mod_5,
  "true-employee-cost-statement": mod_6,
  "job-quote-builder-pro-pack": mod_7,
  "machine-investment-feasibility-buy-lease-keep": mod_8,
  "capital-equipment-investment-appraisal-npv-irr": mod_9,
  "customer-sku-profitability-forensics": mod_10,
  "downtime-scrap-loss-statement": mod_11,
  "oee-loss-monetization-improvement-business-case": mod_12,
  "scrap-rework-cost-tracker": mod_13,
  "outsource-vs-in-house-analyzer": mod_14,
  "plant-wide-shop-rate-cost-structure-audit": mod_15,
  "fx-commodity-pass-through-pricer": mod_16,
  "energy-efficiency-grant-incentive-feasibility-pack": mod_17,
  "motor-compressor-replacement-roi": mod_18,
  "weld-procedure-cost-consumable-estimation-suite": mod_19,
};

export const REGISTERED_TOOL_KEYS: readonly string[] = [
  "break-even-survival-cash-calculator",
  "machine-hourly-rate-proof-report",
  "loss-making-job-detector",
  "receivables-cost-payment-term-addendum",
  "setup-time-reduction-roi-smed",
  "product-sku-margin-ranker",
  "true-employee-cost-statement",
  "job-quote-builder-pro-pack",
  "machine-investment-feasibility-buy-lease-keep",
  "capital-equipment-investment-appraisal-npv-irr",
  "customer-sku-profitability-forensics",
  "downtime-scrap-loss-statement",
  "oee-loss-monetization-improvement-business-case",
  "scrap-rework-cost-tracker",
  "outsource-vs-in-house-analyzer",
  "plant-wide-shop-rate-cost-structure-audit",
  "fx-commodity-pass-through-pricer",
  "energy-efficiency-grant-incentive-feasibility-pack",
  "motor-compressor-replacement-roi",
  "weld-procedure-cost-consumable-estimation-suite",
];

export function getGeneratedToolKeys(): string[] {
  return [...REGISTERED_TOOL_KEYS];
}

export function getGeneratedRegistrySize(): number {
  return Object.keys(GENERATED_FORMULA_REGISTRY).length;
}
