// SectorCalc PRO Engine Governance — Canonical Sample Inputs
// Each LIVE PRO tool has a deterministic sample input set used for:
//   - Golden test execution
//   - Build-time validation
//   - Health check endpoint
// Keys match the actual `get(inputs, "n_...")` calls in each .formula.ts module.
// Server-side only.

import "server-only";

export const PRO_SAMPLE_INPUTS: Record<string, Record<string, number>> = {
  "break-even-survival-cash-calculator": {
    n_annual_revenue: 1500000,
    n_variable_cost_percent: 45,
    n_annual_fixed_costs: 600000,
    n_available_cash_liquidity: 300000,
    n_unit_selling_price: 75,
    n_unit_variable_cost: 33.75,
  },
  "machine-hourly-rate-proof-report": {
    // Core required inputs
    n_planned_operating_hours: 2000,
    n_utilization_percent: 80,
    n_planned_downtime_percent: 5,
    n_purchase_price: 85000,
    n_residual_value: 5000,
    n_economic_life_years: 8,
    n_maintenance_cost: 6000,
    n_insurance_tax_cost: 2000,
    n_facility_allocation: 18000,
    n_machine_power_kw: 15,
    n_electricity_price: 0.12,
    n_consumables_cost_per_hour: 2.5,
    n_tooling_cost_per_hour: 3,
    n_operator_count: 1,
    n_labor_rate_per_hour: 45,
    n_current_shop_rate: 85,
    n_target_margin_percent: 25,
    // Optional core
    n_financing_cost_percent: 0,
    n_other_annual_fixed_cost: 0,
    // Optional scenario
    n_annual_production_volume: 100000,
    n_cycle_time_seconds: 720,
    n_setup_time_minutes: 8,
    n_average_batch_quantity: 500,
  },
  "loss-making-job-detector": {
    n_batch_quantity: 500,
    n_selling_price_per_unit: 95,
    n_material_cost_per_unit: 25,
    n_cycle_time_seconds_per_unit: 720,
    n_setup_time_minutes_per_batch: 8,
    n_machine_rate_per_hour: 85,
    n_operator_count: 1,
    n_labor_rate_per_hour: 45,
    n_external_processing_per_batch: 0,
    n_packaging_freight_per_batch: 50,
    n_other_job_cost_per_batch: 0,
    n_allocated_overhead: 350,
    n_scrap_rework_percent: 5,
    n_target_revenue_margin_percent: 30,
    n_annual_volume_units: 100000,
  },
  "receivables-cost-payment-term-addendum": {
    n_invoice_value: 100000,
    n_payment_days: 30,
    n_early_payment_discount_pct: 2,
    n_early_payment_days: 10,
    n_cost_of_capital_pct: 6,
    n_admin_collection_cost: 500,
    n_default_risk_allowance: 200,
  },
  "setup-time-reduction-roi-smed": {
    n_current_setup_time_minutes: 30,
    n_future_setup_time_minutes: 10,
    n_setups_per_year: 500,
    n_machine_hourly_rate: 85,
    n_labor_rate_per_hour: 45,
    n_implementation_cost: 35000,
    n_operator_count: 2,
  },
  "product-sku-margin-ranker": {
    n_unit_price: 100,
    n_material_cost_per_unit: 25,
    n_labor_cost_per_unit: 15,
    n_overhead_per_unit: 10,
    n_logistics_cost_per_unit: 5,
    n_annual_volume_units: 10000,
    n_target_margin_percent: 30,
    n_total_portfolio_revenue: 5000000,
    n_total_portfolio_profit: 1000000,
  },
  "true-employee-cost-statement": {
    n_annual_base_salary: 65000,
    n_payroll_tax_rate: 22.5,
    n_health_insurance_annual: 5000,
    n_pension_contribution_rate: 5,
    n_bonus_target_rate: 10,
    n_paid_leave_weeks: 4,
    n_training_budget_annual: 1300,
    n_equipment_it_annual: 3250,
    n_workspace_facility_annual: 5200,
    n_recruitment_allocation_rate: 3,
    n_other_benefits_annual: 1000,
    n_productive_hours_per_year: 1664,
  },
  "job-quote-builder-pro-pack": {
    n_batch_quantity: 500,
    n_material_cost_per_unit: 25,
    n_cycle_time_seconds_per_unit: 720,
    n_setup_time_minutes_per_batch: 8,
    n_machine_rate_per_hour: 85,
    n_labor_rate_per_hour: 45,
    n_operator_count: 1,
    n_annual_unallocated_overhead: 350000,
    n_annual_volume_units: 100000,
    n_scrap_rework_percent: 5,
    n_target_revenue_margin_percent: 30,
    n_tooling_consumables_cost_per_batch: 150,
    n_external_processing_cost_per_batch: 0,
    n_packaging_cost_per_batch: 50,
    n_freight_cost_per_batch: 0,
    n_other_job_cost_per_batch: 0,
    n_contingency_percent: 3,
    n_current_quote_per_unit: 0,
  },
  "machine-investment-feasibility-buy-lease-keep": {
    n_machine_purchase_price: 500000,
    n_down_payment_pct: 20,
    n_lease_annual_payment: 85000,
    n_lease_term_years: 5,
    n_loan_interest_rate_pct: 8,
    n_loan_term_years: 5,
    n_annual_maintenance_cost: 15000,
    n_annual_downtime_cost: 8000,
    n_residual_value: 120000,
    n_operating_savings_per_year: 180000,
    n_discount_rate: 10,
  },
  "capital-equipment-investment-appraisal-npv-irr": {
    n_initial_investment: 500000,
    n_working_capital: 50000,
    n_annual_cash_inflow_1: 150000,
    n_annual_cash_inflow_2: 165000,
    n_annual_cash_inflow_3: 180000,
    n_annual_cash_inflow_4: 195000,
    n_annual_cash_inflow_5: 210000,
    n_terminal_residual_value: 75000,
    n_discount_rate_percent: 10,
    n_scenario_downside_pct: -20,
    n_scenario_upside_pct: 20,
  },
  "customer-sku-profitability-forensics": {
    n_unit_price: 100,
    n_unit_variable_cost: 50,
    n_annual_volume: 10000,
    n_logistics_cost_pct: 5,
    n_service_cost_pct: 3,
    n_return_rate_pct: 2,
    n_target_margin: 25,
    n_financing_cost_pct: 2,
  },
  "downtime-scrap-loss-statement": {
    n_downtime_hours: 4,
    n_hourly_contribution_rate: 200,
    n_scrap_quantity: 150,
    n_material_cost_per_unit: 25,
    n_rework_hours: 8,
    n_rework_labor_rate: 55,
    n_disposal_inspection_cost: 500,
    n_annual_event_frequency: 12,
  },
  "oee-loss-monetization-improvement-business-case": {
    n_planned_production_time_seconds: 28800,
    n_operating_time_seconds: 25200,
    n_net_operating_time_seconds: 23000,
    n_ideal_cycle_time_per_part: 30,
    n_total_parts_produced: 900,
    n_good_parts: 855,
    n_hourly_contribution: 100,
    n_improvement_investment: 50000,
    n_operating_hours_per_year: 2000,
  },
  "scrap-rework-cost-tracker": {
    n_total_produced: 10000,
    n_scrap_quantity: 150,
    n_rework_quantity: 80,
    n_unit_material_cost: 25,
    n_unit_labor_cost: 15,
    n_rework_labor_rate: 45,
    n_rework_time_per_unit: 0.5,
    n_defect_rate_target_pct: 2.0,
    n_monthly_volume: 10000,
  },
  "outsource-vs-in-house-analyzer": {
    n_in_house_material_cost_per_unit: 30,
    n_in_house_labor_cost_per_unit: 25,
    n_in_house_overhead_per_unit: 20,
    n_in_house_setup_cost_per_batch: 500,
    n_outsource_unit_price: 95,
    n_outsource_logistics_per_unit: 8,
    n_quality_defect_allowance_pct: 3,
    n_inventory_lead_time_cost_pct: 2,
    n_capacity_opportunity_cost_pct: 5,
    n_annual_volume: 5000,
  },
  "plant-wide-shop-rate-cost-structure-audit": {
    n_total_annual_cost: 2000000,
    n_total_productive_hours: 40000,
    n_machine_group_cost: 500000,
    n_machine_group_hours: 15000,
    n_overhead_pool: 600000,
    n_overhead_allocation_base: 40000,
    n_current_shop_rate: 85,
    n_target_margin_pct: 25,
    n_utilization_pct: 80,
    n_labor_burden: 300000,
    n_facility_burden: 200000,
    n_maintenance_burden: 150000,
    n_energy_burden: 100000,
  },
  "fx-commodity-pass-through-pricer": {
    n_base_price: 100,
    n_fx_rate_spot: 1.10,
    n_fx_rate_budget: 1.05,
    n_commodity_index_current: 180,
    n_commodity_index_budget: 160,
    n_material_cost_pct: 40,
    n_fx_hedge_pct: 60,
    n_commodity_hedge_pct: 50,
    n_annual_volume: 10000,
    n_source_confidence_ratio: 0.9,
  },
  "energy-efficiency-grant-incentive-feasibility-pack": {
    n_baseline_energy_consumption_kwh: 500000,
    n_baseline_energy_price_per_kwh: 0.12,
    n_projected_saving_pct: 30,
    n_gross_project_cost: 120000,
    n_eligible_project_cost: 100000,
    n_grant_incentive_amount: 35000,
    n_annual_maintenance_cost: 5000,
    n_useful_life_years: 10,
    n_discount_rate: 8,
    n_energy_price_escalation_pct: 2,
  },
  "motor-compressor-replacement-roi": {
    n_current_power_kw: 75,
    n_proposed_power_kw: 60,
    n_annual_operating_hours: 6000,
    n_energy_price_per_kwh: 0.12,
    n_current_maintenance_cost: 5000,
    n_proposed_maintenance_cost: 3000,
    n_replacement_cost: 16000,
    n_useful_life_years: 10,
    n_discount_rate: 8,
  },
  "weld-procedure-cost-consumable-estimation-suite": {
    n_weld_length_m: 50,
    n_weld_throat_mm: 8,
    n_weld_density_g_per_cm3: 7.85,
    n_weld_time_min: 120,
    n_arc_time_min: 90,
    n_wire_cost_per_kg: 15,
    n_deposition_efficiency_pct: 85,
    n_gas_cost_per_min: 0.15,
    n_labor_rate: 55,
    n_overhead_rate: 350000,
    n_source_confidence_ratio: 0.9,
  },
};
