// SectorCalc PRO Engine Governance — Canonical Sample Inputs
// Each LIVE PRO tool has a deterministic sample input set used for:
//   - Golden test execution
//   - Build-time validation
//   - Health check endpoint
// Keys match the actual `get(inputs, "n_...")` calls in each .formula.ts module.
// Server-side only.

import "server-only";

export const PRO_SAMPLE_INPUTS: Record<string, Record<string, number>> = {
  "break-even-survival-cash-calculator": {
    n_initial_investment: 500000,
    n_annual_net_cash_flow: 250000,
    n_discount_rate: 0.4,
    n_analysis_years: 12,
    n_residual_value: 50000,
    n_stress_downside_factor: 0.8,
    n_labor_rate: 80000,
    n_overhead_rate: 30000,
    n_defect_or_loss_cost: 15000,
    n_source_confidence_ratio: 0.95,
    n_uncertainty_multiplier: 2,
  },
  "machine-hourly-rate-proof-report": {
    n_machine_rate: 85,
    n_cycle_time: 12,
    n_setup_time: 8,
    n_batch_quantity: 500,
    n_material_cost: 25,
    n_target_margin: 0.3,
    n_annual_volume: 100000,
    n_labor_rate: 45,
    n_overhead_rate: 35,
    n_source_confidence_ratio: 0.9,
  },
  "loss-making-job-detector": {
    n_machine_rate: 85,
    n_cycle_time: 12,
    n_setup_time: 1800,
    n_material_cost: 300,
    n_labor_rate: 55,
    n_overhead_rate: 350000,
    n_defect_or_loss_cost: 20,
    n_target_margin: 0.25,
    n_batch_quantity: 100,
    n_annual_volume: 5000,
    n_uncertainty_multiplier: 50000,
    n_source_confidence_ratio: 0.9,
  },
  "receivables-cost-payment-term-addendum": {
    n_material_cost: 10000,
    n_cycle_time: 30,
    n_setup_time: 90,
    n_target_margin: 0.12,
    n_defect_or_loss_cost: 0.005,
    n_machine_rate: 25,
    n_labor_rate: 300,
    n_annual_volume: 120,
    n_source_confidence_ratio: 0.9,
    n_uncertainty_multiplier: 2,
  },
  "setup-time-reduction-roi-smed": {
    n_machine_rate: 85,
    n_cycle_time: 12,
    n_setup_time: 1800,
    n_batch_quantity: 500,
    n_material_cost: 50000,
    n_labor_rate: 45,
    n_overhead_rate: 25,
    n_annual_volume: 100000,
    n_uncertainty_multiplier: 0.5,
    n_source_confidence_ratio: 0.9,
  },
  "product-sku-margin-ranker": {
    n_machine_rate: 85,
    n_cycle_time: 12,
    n_material_cost: 25,
    n_target_margin: 0.3,
    n_annual_volume: 100000,
    n_labor_rate: 45,
    n_overhead_rate: 350000,
    n_defect_or_loss_cost: 12000,
    n_uncertainty_multiplier: 100,
    n_source_confidence_ratio: 0.9,
  },
  "true-employee-cost-statement": {
    n_labor_rate: 45,
    n_annual_volume: 2080,
    n_target_margin: 0.8,
    n_uncertainty_multiplier: 0.225,
    n_material_cost: 9000,
    n_defect_or_loss_cost: 2000,
    n_machine_rate: 2500,
    n_overhead_rate: 6000,
    n_source_confidence_ratio: 0.9,
  },
  "job-quote-builder-pro-pack": {
    n_machine_rate: 85,
    n_cycle_time: 12,
    n_setup_time: 8,
    n_batch_quantity: 500,
    n_material_cost: 25,
    n_target_margin: 0.3,
    n_annual_volume: 100000,
    n_labor_rate: 45,
    n_overhead_rate: 350000,
    n_defect_or_loss_cost: 12000,
    n_source_confidence_ratio: 0.9,
    n_uncertainty_multiplier: 1.1,
  },
  "machine-investment-feasibility-buy-lease-keep": {
    n_initial_investment: 500000,
    n_annual_net_cash_flow: 50000,
    n_discount_rate: 0.10,
    n_analysis_years: 5,
    n_residual_value: 100000,
    n_stress_downside_factor: 0.2,
    n_annual_volume: 20000,
    n_labor_rate: 120000,
    n_overhead_rate: 80000,
    n_defect_or_loss_cost: 140000,
    n_source_confidence_ratio: 0.9,
    n_uncertainty_multiplier: 2,
  },
  "capital-equipment-investment-appraisal-npv-irr": {
    n_initial_investment: 500000,
    n_annual_net_cash_flow: 150000,
    n_discount_rate: 0.10,
    n_analysis_years: 5,
    n_residual_value: 50000,
    n_stress_downside_factor: 0.8,
    n_annual_volume: 10000,
    n_labor_rate: 80000,
    n_overhead_rate: 120000,
    n_defect_or_loss_cost: 15000,
    n_source_confidence_ratio: 0.95,
    n_uncertainty_multiplier: 1.2,
  },
  "customer-sku-profitability-forensics": {
    n_unit_price: 100,
    n_unit_variable_cost: 60,
    n_annual_volume: 10000,
    n_logistics_cost_pct: 0.05,
    n_service_cost_pct: 0.03,
    n_return_rate_pct: 0.02,
    n_target_margin: 0.25,
    n_labor_rate: 10000,
    n_overhead_rate: 5000,
    n_source_confidence_ratio: 0.9,
  },
  "downtime-scrap-loss-statement": {
    n_productive_hours: 7200000,
    n_actual_hours: 6336000,
    n_hourly_rate: 85,
    n_scrap_quantity: 150,
    n_unit_cost: 25,
    n_rework_hours: 432000,
    n_rework_rate: 55,
    n_material_cost: 50000,
    n_defect_rate_pct: 0.035,
    n_source_confidence_ratio: 0.9,
  },
  "oee-loss-monetization-improvement-business-case": {
    n_planned_production_time: 600,
    n_operating_time: 550,
    n_total_parts: 1000,
    n_good_parts: 950,
    n_ideal_cycle_time: 0.5,
    n_hourly_contribution: 100,
    n_improvement_cost: 50000,
    n_source_confidence_ratio: 0.9,
  },
  "scrap-rework-cost-tracker": {
    n_monthly_volume: 10000,
    n_scrap_quantity: 150,
    n_rework_quantity: 80,
    n_unit_material_cost: 25,
    n_unit_labor_cost: 15,
    n_rework_time_per_unit: 0.5,
    n_rework_labor_rate: 45,
    n_defect_rate_target_pct: 0.02,
    n_total_produced: 10000,
    n_source_confidence_ratio: 0.9,
  },
  "outsource-vs-in-house-analyzer": {
    n_in_house_labor_cost: 85,
    n_in_house_material_cost: 30,
    n_in_house_setup_cost: 500,
    n_in_house_overhead: 75,
    n_outsource_unit_price: 95,
    n_outsource_logistics_cost: 8,
    n_annual_volume: 5000,
    n_quality_risk_premium_pct: 0.05,
    n_source_confidence_ratio: 0.9,
  },
  "plant-wide-shop-rate-cost-structure-audit": {
    n_total_annual_cost: 2000000,
    n_total_productive_hours: 40000,
    n_machine_group_cost: 500000,
    n_machine_group_hours: 15000,
    n_overhead_pool: 600000,
    n_overhead_allocation_base: 40000,
    n_current_shop_rate: 85,
    n_target_margin_pct: 0.25,
    n_utilization_pct: 0.80,
    n_source_confidence_ratio: 0.9,
  },
  "fx-commodity-pass-through-pricer": {
    n_base_price: 100,
    n_fx_rate_spot: 1.10,
    n_fx_rate_budget: 1.05,
    n_commodity_index_current: 180,
    n_commodity_index_budget: 160,
    n_material_cost_pct: 0.4,
    n_fx_hedge_pct: 0.6,
    n_commodity_hedge_pct: 0.5,
    n_annual_volume: 10000,
    n_source_confidence_ratio: 0.9,
  },
  "energy-efficiency-grant-incentive-feasibility-pack": {
    n_current_kwh_per_year: 500000,
    n_target_kwh_per_year: 350000,
    n_avg_kwh_rate: 0.12,
    n_implementation_cost: 80000,
    n_grant_coverage_pct: 0.3,
    n_maintenance_cost_saving: 5000,
    n_emission_factor_kgco2_per_kwh: 0.45,
    n_equipment_life_years: 10,
    n_discount_rate: 0.08,
    n_source_confidence_ratio: 0.9,
  },
  "motor-compressor-replacement-roi": {
    n_motor_power_kw: 75,
    n_annual_operating_hours: 6000,
    n_current_efficiency_pct: 0.90,
    n_new_efficiency_pct: 0.95,
    n_avg_kwh_rate: 0.12,
    n_replacement_cost: 12000,
    n_installation_cost: 4000,
    n_maintenance_saving_per_year: 2000,
    n_equipment_life_years: 10,
    n_discount_rate: 0.08,
    n_source_confidence_ratio: 0.9,
  },
  "weld-procedure-cost-consumable-estimation-suite": {
    n_weld_length_m: 50,
    n_weld_throat_mm: 8,
    n_weld_density_g_per_cm3: 7.85,
    n_weld_time_min: 120,
    n_arc_time_min: 90,
    n_wire_cost_per_kg: 15,
    n_deposition_efficiency_pct: 0.85,
    n_gas_cost_per_min: 0.15,
    n_labor_rate: 55,
    n_overhead_rate: 350000,
    n_source_confidence_ratio: 0.9,
  },
};
