/**
 * Pure PDF line builder for SC-012. No DOM, no jsPDF — tested in node.
 */
export interface QuotePdfLine { text: string; style: 'title' | 'hero' | 'head' | 'row' | 'warn' | 'note'; }

export interface QuotePdfInput {
  toolCode: string;
  sellPrice: string;
  unitPrice: string;
  totalCost: string;
  profit: string;
  currency: string;
  breakdown: Array<{ item: string; amount: string; pct: string }>;
  warnings: Array<{ severity: string; message: string }>;
  steps: Array<{ step: number; description: string; result: string }>;
}

export function buildQuoteReportLines(input: QuotePdfInput): QuotePdfLine[] {
  const lines: QuotePdfLine[] = [];
  lines.push({ text: `SectorCalc — ${input.toolCode} Quote Pricing`, style: 'title' });
  lines.push({ text: `Sell price: ${input.sellPrice} ${input.currency}  (unit ${input.unitPrice})`, style: 'hero' });
  lines.push({ text: `Total cost ${input.totalCost} · profit ${input.profit} ${input.currency}`, style: 'note' });
  lines.push({ text: 'Cost breakdown', style: 'head' });
  for (const b of input.breakdown) {
    lines.push({ text: `${b.item}  ${b.amount}  (${b.pct}%)`, style: 'row' });
  }
  if (input.warnings.length > 0) {
    lines.push({ text: 'Heads up', style: 'head' });
    for (const w of input.warnings) {
      lines.push({ text: `[${w.severity}] ${w.message}`, style: 'warn' });
    }
  }
  lines.push({ text: 'Show me the math', style: 'head' });
  for (const s of input.steps) {
    lines.push({ text: `${s.step}. ${s.description} = ${s.result}`, style: 'row' });
  }
  lines.push({ text: 'Generated by SectorCalc — deterministic engine. Verify with local law.', style: 'note' });
  return lines;
}
