/**
 * Batch traffic catalog production vs oracle comparison.
 * GENERATED by scripts/generate-batch-traffic-catalog-governance.ts
 */

import type { FreeTrafficInputValues } from "@/lib/features/tools/free-traffic-calculators";
import {
  BATCH_TRAFFIC_CATALOG_ORACLE_SLUGS,
  calculateBatchTrafficCatalogOracle,
  getBatchTrafficCatalogOracleSpec,
  isBatchTrafficCatalogOracleSlug,
  type BatchTrafficCatalogOracleSlug,
} from "@/lib/features/formula-governance/oracle/batch-traffic-catalog-oracles";
import {
  adaptProductionBatchTrafficCatalogOutput,
  type NormalizedBatchTrafficCatalogProductionOutput,
} from "@/lib/features/formula-governance/oracle/production-adapters";
import { hasOracleForTool } from "@/lib/features/formula-governance/oracle/registry";
import type {
  FieldComparisonDiff,
  OracleComparisonAuditSummary,
  OracleComparisonResult,
  OracleComparisonStatus,
} from "@/lib/features/formula-governance/oracle/compare-production-oracle";

const NUMERIC_TOLERANCE = 0.05;
const CURRENCY_TOLERANCE = 0.02;
const PERCENT_TOLERANCE = 0.05;
const INTEGER_TOLERANCE = 0.5;

function toleranceForField(field: string, parseKind: string): number {
  if (parseKind === "currency") return CURRENCY_TOLERANCE;
  if (parseKind === "percent") return PERCENT_TOLERANCE;
  if (parseKind === "integer") return INTEGER_TOLERANCE;
  return NUMERIC_TOLERANCE;
}

function compareNumericFields(fields: readonly {
  readonly field: string;
  readonly production: number;
  readonly oracle: number;
  readonly tolerance: number;
}[]): { readonly passed: boolean; readonly diffs: readonly FieldComparisonDiff[] } {
  const diffs: FieldComparisonDiff[] = [];
  for (const entry of fields) {
    const delta = Math.abs(entry.production - entry.oracle);
    if (delta > entry.tolerance) {
      diffs.push({
        field: entry.field,
        production: entry.production,
        oracle: entry.oracle,
        delta,
        tolerance: entry.tolerance,
      });
    }
  }
  return { passed: diffs.length === 0, diffs };
}

export { BATCH_TRAFFIC_CATALOG_ORACLE_SLUGS };

export type BatchTrafficCatalogComparisonScenario = {
  readonly id: string;
  readonly kind: "normal" | "edge" | "absurd";
  readonly values: FreeTrafficInputValues;
  readonly expectPass?: boolean;
};

export function isBatchTrafficCatalogComparisonSlug(slug: string): slug is BatchTrafficCatalogOracleSlug {
  return isBatchTrafficCatalogOracleSlug(slug);
}

const SCENARIOS_BY_SLUG: Readonly<Record<BatchTrafficCatalogOracleSlug, readonly BatchTrafficCatalogComparisonScenario[]>> = {
  "age-calculator": [
    { id: "golden-valid", kind: "normal", values: {"birthYear":1990,"currentYear":2026} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"birthYear":-1,"currentYear":2026}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"birthYear":1990,"currentYear":2026} },
    { id: "rogue-key", kind: "absurd", values: { ...{"birthYear":1990,"currentYear":2026}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"birthYear":1990,"currentYear":2026} },
  ],
  "average-calculator": [
    { id: "golden-valid", kind: "normal", values: {"value1":10,"value2":20,"value3":30,"value4":40,"value5":50} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"value1":-1,"value2":20,"value3":30,"value4":40,"value5":50}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"value1":10,"value2":20,"value3":30,"value4":40,"value5":50} },
    { id: "rogue-key", kind: "absurd", values: { ...{"value1":10,"value2":20,"value3":30,"value4":40,"value5":50}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"value1":10,"value2":20,"value3":30,"value4":40,"value5":50} },
  ],
  "batch-yield-calculator": [
    { id: "golden-valid", kind: "normal", values: {"inputQty":1,"goodOutputQty":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"inputQty":-1,"goodOutputQty":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"inputQty":1,"goodOutputQty":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"inputQty":1,"goodOutputQty":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"inputQty":1,"goodOutputQty":1} },
  ],
  "boiler-efficiency-calculator": [
    { id: "golden-valid", kind: "normal", values: {"usefulOutputKwh":1,"fuelInputKwh":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"usefulOutputKwh":-1,"fuelInputKwh":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"usefulOutputKwh":1,"fuelInputKwh":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"usefulOutputKwh":1,"fuelInputKwh":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"usefulOutputKwh":1,"fuelInputKwh":1} },
  ],
  "brick-calculator": [
    { id: "golden-valid", kind: "normal", values: {"wallAreaM2":1,"bricksPerM2":1,"wastePercent":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"wallAreaM2":-1,"bricksPerM2":1,"wastePercent":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"wallAreaM2":1,"bricksPerM2":1,"wastePercent":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"wallAreaM2":1,"bricksPerM2":1,"wastePercent":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"wallAreaM2":1,"bricksPerM2":1,"wastePercent":1} },
  ],
  "carbon-footprint-quick": [
    { id: "golden-valid", kind: "normal", values: {"energyKwh":1,"emissionFactorKgPerKwh":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"energyKwh":-1,"emissionFactorKgPerKwh":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"energyKwh":1,"emissionFactorKgPerKwh":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"energyKwh":1,"emissionFactorKgPerKwh":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"energyKwh":1,"emissionFactorKgPerKwh":1} },
  ],
  "cbam-exposure-quick-check": [
    { id: "golden-valid", kind: "normal", values: {"emissionsTon":1,"carbonPrice":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"emissionsTon":-1,"carbonPrice":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"emissionsTon":1,"carbonPrice":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"emissionsTon":1,"carbonPrice":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"emissionsTon":1,"carbonPrice":1} },
  ],
  "cnc-cycle-time-calculator": [
    { id: "golden-valid", kind: "normal", values: {"machiningSeconds":1,"loadUnloadSeconds":1,"inspectionSeconds":1,"quantity":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"machiningSeconds":-1,"loadUnloadSeconds":1,"inspectionSeconds":1,"quantity":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"machiningSeconds":1,"loadUnloadSeconds":1,"inspectionSeconds":1,"quantity":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"machiningSeconds":1,"loadUnloadSeconds":1,"inspectionSeconds":1,"quantity":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"machiningSeconds":1,"loadUnloadSeconds":1,"inspectionSeconds":1,"quantity":1} },
  ],
  "compressor-energy-cost-calculator": [
    { id: "golden-valid", kind: "normal", values: {"powerKw":1,"operatingHours":1,"rate":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"powerKw":-1,"operatingHours":1,"rate":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"powerKw":1,"operatingHours":1,"rate":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"powerKw":1,"operatingHours":1,"rate":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"powerKw":1,"operatingHours":1,"rate":1} },
  ],
  "concrete-bag-calculator": [
    { id: "golden-valid", kind: "normal", values: {"volumeM3":1,"bagYieldM3":1,"wastePercent":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"volumeM3":-1,"bagYieldM3":1,"wastePercent":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"volumeM3":1,"bagYieldM3":1,"wastePercent":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"volumeM3":1,"bagYieldM3":1,"wastePercent":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"volumeM3":1,"bagYieldM3":1,"wastePercent":1} },
  ],
  "concrete-volume-calculator": [
    { id: "golden-valid", kind: "normal", values: {"length":1,"width":1,"depth":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"length":-1,"width":1,"depth":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"length":1,"width":1,"depth":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"length":1,"width":1,"depth":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"length":1,"width":1,"depth":1} },
  ],
  "crop-yield-calculator": [
    { id: "golden-valid", kind: "normal", values: {"areaHa":1,"yieldTonPerHa":1,"pricePerTon":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"areaHa":-1,"yieldTonPerHa":1,"pricePerTon":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"areaHa":1,"yieldTonPerHa":1,"pricePerTon":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"areaHa":1,"yieldTonPerHa":1,"pricePerTon":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"areaHa":1,"yieldTonPerHa":1,"pricePerTon":1} },
  ],
  "cutting-speed-calculator": [
    { id: "golden-valid", kind: "normal", values: {"diameterMm":1,"rpm":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"diameterMm":-1,"rpm":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"diameterMm":1,"rpm":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"diameterMm":1,"rpm":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"diameterMm":1,"rpm":1} },
  ],
  "date-difference-calculator": [
    { id: "golden-valid", kind: "normal", values: {"startDayNumber":1,"endDayNumber":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"startDayNumber":-1,"endDayNumber":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"startDayNumber":1,"endDayNumber":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"startDayNumber":1,"endDayNumber":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"startDayNumber":1,"endDayNumber":1} },
  ],
  "delivery-cost-calculator": [
    { id: "golden-valid", kind: "normal", values: {"distanceKm":1,"costPerKm":1,"stops":1,"costPerStop":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"distanceKm":-1,"costPerKm":1,"stops":1,"costPerStop":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"distanceKm":1,"costPerKm":1,"stops":1,"costPerStop":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"distanceKm":1,"costPerKm":1,"stops":1,"costPerStop":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"distanceKm":1,"costPerKm":1,"stops":1,"costPerStop":1} },
  ],
  "depreciation-calculator": [
    { id: "golden-valid", kind: "normal", values: {"assetCost":1,"salvageValue":1,"usefulLifeYears":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"assetCost":-1,"salvageValue":1,"usefulLifeYears":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"assetCost":1,"salvageValue":1,"usefulLifeYears":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"assetCost":1,"salvageValue":1,"usefulLifeYears":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"assetCost":1,"salvageValue":1,"usefulLifeYears":1} },
  ],
  "desi-calculator": [
    { id: "golden-valid", kind: "normal", values: {"lengthCm":1,"widthCm":1,"heightCm":1,"divisor":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"lengthCm":-1,"widthCm":1,"heightCm":1,"divisor":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"lengthCm":1,"widthCm":1,"heightCm":1,"divisor":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"lengthCm":1,"widthCm":1,"heightCm":1,"divisor":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"lengthCm":1,"widthCm":1,"heightCm":1,"divisor":1} },
  ],
  "discount-calculator": [
    { id: "golden-valid", kind: "normal", values: {"originalPrice":1,"discountPercent":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"originalPrice":-1,"discountPercent":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"originalPrice":1,"discountPercent":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"originalPrice":1,"discountPercent":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"originalPrice":1,"discountPercent":1} },
  ],
  "drywall-calculator": [
    { id: "golden-valid", kind: "normal", values: {"wallAreaM2":1,"sheetAreaM2":1,"wastePercent":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"wallAreaM2":-1,"sheetAreaM2":1,"wastePercent":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"wallAreaM2":1,"sheetAreaM2":1,"wastePercent":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"wallAreaM2":1,"sheetAreaM2":1,"wastePercent":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"wallAreaM2":1,"sheetAreaM2":1,"wastePercent":1} },
  ],
  "electricity-bill-calculator": [
    { id: "golden-valid", kind: "normal", values: {"kwh":1,"rate":1,"fixedCharge":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"kwh":-1,"rate":1,"fixedCharge":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"kwh":1,"rate":1,"fixedCharge":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"kwh":1,"rate":1,"fixedCharge":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"kwh":1,"rate":1,"fixedCharge":1} },
  ],
  "energy-consumption-check": [
    { id: "golden-valid", kind: "normal", values: {"powerKw":1,"hoursPerDay":1,"days":1,"rate":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"powerKw":-1,"hoursPerDay":1,"days":1,"rate":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"powerKw":1,"hoursPerDay":1,"days":1,"rate":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"powerKw":1,"hoursPerDay":1,"days":1,"rate":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"powerKw":1,"hoursPerDay":1,"days":1,"rate":1} },
  ],
  "excavation-volume-calculator": [
    { id: "golden-valid", kind: "normal", values: {"lengthM":1,"widthM":1,"depthM":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"lengthM":-1,"widthM":1,"depthM":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"lengthM":1,"widthM":1,"depthM":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"lengthM":1,"widthM":1,"depthM":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"lengthM":1,"widthM":1,"depthM":1} },
  ],
  "feed-cost-estimator": [
    { id: "golden-valid", kind: "normal", values: {"feedKg":1,"pricePerKg":1,"transportCost":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"feedKg":-1,"pricePerKg":1,"transportCost":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"feedKg":1,"pricePerKg":1,"transportCost":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"feedKg":1,"pricePerKg":1,"transportCost":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"feedKg":1,"pricePerKg":1,"transportCost":1} },
  ],
  "feed-rate-calculator": [
    { id: "golden-valid", kind: "normal", values: {"rpm":1,"teeth":1,"feedPerToothMm":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"rpm":-1,"teeth":1,"feedPerToothMm":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"rpm":1,"teeth":1,"feedPerToothMm":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"rpm":1,"teeth":1,"feedPerToothMm":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"rpm":1,"teeth":1,"feedPerToothMm":1} },
  ],
  "fertilizer-dosage-calculator": [
    { id: "golden-valid", kind: "normal", values: {"areaHa":1,"dosageKgPerHa":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"areaHa":-1,"dosageKgPerHa":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"areaHa":1,"dosageKgPerHa":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"areaHa":1,"dosageKgPerHa":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"areaHa":1,"dosageKgPerHa":1} },
  ],
  "flooring-calculator": [
    { id: "golden-valid", kind: "normal", values: {"roomLengthM":1,"roomWidthM":1,"wastePercent":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"roomLengthM":-1,"roomWidthM":1,"wastePercent":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"roomLengthM":1,"roomWidthM":1,"wastePercent":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"roomLengthM":1,"roomWidthM":1,"wastePercent":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"roomLengthM":1,"roomWidthM":1,"wastePercent":1} },
  ],
  "freight-cost-calculator": [
    { id: "golden-valid", kind: "normal", values: {"weightKg":1,"ratePerKg":1,"fixedFee":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"weightKg":-1,"ratePerKg":1,"fixedFee":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"weightKg":1,"ratePerKg":1,"fixedFee":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"weightKg":1,"ratePerKg":1,"fixedFee":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"weightKg":1,"ratePerKg":1,"fixedFee":1} },
  ],
  "fuel-consumption-calculator": [
    { id: "golden-valid", kind: "normal", values: {"distanceKm":1,"consumptionPer100Km":1,"fuelPrice":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"distanceKm":-1,"consumptionPer100Km":1,"fuelPrice":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"distanceKm":1,"consumptionPer100Km":1,"fuelPrice":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"distanceKm":1,"consumptionPer100Km":1,"fuelPrice":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"distanceKm":1,"consumptionPer100Km":1,"fuelPrice":1} },
  ],
  "fuel-cost-calculator": [
    { id: "golden-valid", kind: "normal", values: {"distanceKm":1,"consumptionPer100Km":1,"fuelPrice":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"distanceKm":-1,"consumptionPer100Km":1,"fuelPrice":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"distanceKm":1,"consumptionPer100Km":1,"fuelPrice":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"distanceKm":1,"consumptionPer100Km":1,"fuelPrice":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"distanceKm":1,"consumptionPer100Km":1,"fuelPrice":1} },
  ],
  "fuel-emission-calculator": [
    { id: "golden-valid", kind: "normal", values: {"litersFuel":1,"kgCo2PerLiter":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"litersFuel":-1,"kgCo2PerLiter":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"litersFuel":1,"kgCo2PerLiter":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"litersFuel":1,"kgCo2PerLiter":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"litersFuel":1,"kgCo2PerLiter":1} },
  ],
  "fuel-travel-calculator": [
    { id: "golden-valid", kind: "normal", values: {"distanceKm":1,"consumptionPer100Km":1,"fuelPrice":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"distanceKm":-1,"consumptionPer100Km":1,"fuelPrice":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"distanceKm":1,"consumptionPer100Km":1,"fuelPrice":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"distanceKm":1,"consumptionPer100Km":1,"fuelPrice":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"distanceKm":1,"consumptionPer100Km":1,"fuelPrice":1} },
  ],
  "heat-loss-calculator": [
    { id: "golden-valid", kind: "normal", values: {"uValue":1,"areaM2":1,"tempDifferenceC":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"uValue":-1,"areaM2":1,"tempDifferenceC":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"uValue":1,"areaM2":1,"tempDifferenceC":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"uValue":1,"areaM2":1,"tempDifferenceC":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"uValue":1,"areaM2":1,"tempDifferenceC":1} },
  ],
  "home-budget-calculator": [
    { id: "golden-valid", kind: "normal", values: {"income":5000,"rent":1200,"food":600,"transport":300,"utilities":200} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"income":-1,"rent":1200,"food":600,"transport":300,"utilities":200}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"income":5000,"rent":1200,"food":600,"transport":300,"utilities":200} },
    { id: "rogue-key", kind: "absurd", values: { ...{"income":5000,"rent":1200,"food":600,"transport":300,"utilities":200}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"income":5000,"rent":1200,"food":600,"transport":300,"utilities":200} },
  ],
  "home-renovation-m2-calculator": [
    { id: "golden-valid", kind: "normal", values: {"areaM2":1,"costPerM2":1,"contingencyPercent":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"areaM2":-1,"costPerM2":1,"contingencyPercent":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"areaM2":1,"costPerM2":1,"contingencyPercent":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"areaM2":1,"costPerM2":1,"contingencyPercent":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"areaM2":1,"costPerM2":1,"contingencyPercent":1} },
  ],
  "hourly-rate-calculator": [
    { id: "golden-valid", kind: "normal", values: {"monthlyIncome":1,"billableHours":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"monthlyIncome":-1,"billableHours":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"monthlyIncome":1,"billableHours":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"monthlyIncome":1,"billableHours":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"monthlyIncome":1,"billableHours":1} },
  ],
  "irrigation-cost-check": [
    { id: "golden-valid", kind: "normal", values: {"pumpKw":1,"hours":1,"energyRate":1,"waterCost":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"pumpKw":-1,"hours":1,"energyRate":1,"waterCost":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"pumpKw":1,"hours":1,"energyRate":1,"waterCost":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"pumpKw":1,"hours":1,"energyRate":1,"waterCost":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"pumpKw":1,"hours":1,"energyRate":1,"waterCost":1} },
  ],
  "kwh-cost-calculator": [
    { id: "golden-valid", kind: "normal", values: {"kwh":1,"rate":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"kwh":-1,"rate":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"kwh":1,"rate":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"kwh":1,"rate":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"kwh":1,"rate":1} },
  ],
  "linear-regression-calculator": [
    { id: "golden-valid", kind: "normal", values: {"x1":1,"y1":2,"x2":2,"y2":4,"x3":3,"y3":6} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"x1":-1,"y1":2,"x2":2,"y2":4,"x3":3,"y3":6}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"x1":1,"y1":2,"x2":2,"y2":4,"x3":3,"y3":6} },
    { id: "rogue-key", kind: "absurd", values: { ...{"x1":1,"y1":2,"x2":2,"y2":4,"x3":3,"y3":6}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"x1":1,"y1":2,"x2":2,"y2":4,"x3":3,"y3":6} },
  ],
  "machine-hour-rate-calculator": [
    { id: "golden-valid", kind: "normal", values: {"fixedMonthlyCost":1,"monthlyMachineHours":1,"variableCostPerHour":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"fixedMonthlyCost":-1,"monthlyMachineHours":1,"variableCostPerHour":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"fixedMonthlyCost":1,"monthlyMachineHours":1,"variableCostPerHour":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"fixedMonthlyCost":1,"monthlyMachineHours":1,"variableCostPerHour":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"fixedMonthlyCost":1,"monthlyMachineHours":1,"variableCostPerHour":1} },
  ],
  "material-waste-calculator": [
    { id: "golden-valid", kind: "normal", values: {"inputMaterialKg":1,"goodOutputKg":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"inputMaterialKg":-1,"goodOutputKg":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"inputMaterialKg":1,"goodOutputKg":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"inputMaterialKg":1,"goodOutputKg":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"inputMaterialKg":1,"goodOutputKg":1} },
  ],
  "median-calculator": [
    { id: "golden-valid", kind: "normal", values: {"value1":10,"value2":20,"value3":30,"value4":40,"value5":50} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"value1":-1,"value2":20,"value3":30,"value4":40,"value5":50}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"value1":10,"value2":20,"value3":30,"value4":40,"value5":50} },
    { id: "rogue-key", kind: "absurd", values: { ...{"value1":10,"value2":20,"value3":30,"value4":40,"value5":50}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"value1":10,"value2":20,"value3":30,"value4":40,"value5":50} },
  ],
  "milk-yield-check": [
    { id: "golden-valid", kind: "normal", values: {"cows":1,"litersPerCow":1,"milkPrice":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"cows":-1,"litersPerCow":1,"milkPrice":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"cows":1,"litersPerCow":1,"milkPrice":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"cows":1,"litersPerCow":1,"milkPrice":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"cows":1,"litersPerCow":1,"milkPrice":1} },
  ],
  "oee-calculator": [
    { id: "golden-valid", kind: "normal", values: {"availabilityPercent":1,"performancePercent":1,"qualityPercent":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"availabilityPercent":-1,"performancePercent":1,"qualityPercent":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"availabilityPercent":1,"performancePercent":1,"qualityPercent":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"availabilityPercent":1,"performancePercent":1,"qualityPercent":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"availabilityPercent":1,"performancePercent":1,"qualityPercent":1} },
  ],
  "paint-coverage-calculator": [
    { id: "golden-valid", kind: "normal", values: {"areaM2":1,"coveragePerLiter":1,"coats":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"areaM2":-1,"coveragePerLiter":1,"coats":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"areaM2":1,"coveragePerLiter":1,"coats":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"areaM2":1,"coveragePerLiter":1,"coats":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"areaM2":1,"coveragePerLiter":1,"coats":1} },
  ],
  "percentage-calculator": [
    { id: "golden-valid", kind: "normal", values: {"value":1,"percent":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"value":-1,"percent":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"value":1,"percent":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"value":1,"percent":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"value":1,"percent":1} },
  ],
  "percentage-increase-calculator": [
    { id: "golden-valid", kind: "normal", values: {"oldValue":1,"newValue":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"oldValue":-1,"newValue":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"oldValue":1,"newValue":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"oldValue":1,"newValue":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"oldValue":1,"newValue":1} },
  ],
  "plaster-calculator": [
    { id: "golden-valid", kind: "normal", values: {"areaM2":1,"thicknessMm":1,"densityKgM3":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"areaM2":-1,"thicknessMm":1,"densityKgM3":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"areaM2":1,"thicknessMm":1,"densityKgM3":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"areaM2":1,"thicknessMm":1,"densityKgM3":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"areaM2":1,"thicknessMm":1,"densityKgM3":1} },
  ],
  "portion-cost-calculator": [
    { id: "golden-valid", kind: "normal", values: {"totalBatchCost":1,"portions":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"totalBatchCost":-1,"portions":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"totalBatchCost":1,"portions":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"totalBatchCost":1,"portions":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"totalBatchCost":1,"portions":1} },
  ],
  "probability-calculator": [
    { id: "golden-valid", kind: "normal", values: {"favorableOutcomes":1,"totalOutcomes":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"favorableOutcomes":-1,"totalOutcomes":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"favorableOutcomes":1,"totalOutcomes":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"favorableOutcomes":1,"totalOutcomes":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"favorableOutcomes":1,"totalOutcomes":1} },
  ],
  "proportion-calculator": [
    { id: "golden-valid", kind: "normal", values: {"a":1,"b":1,"c":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"a":-1,"b":1,"c":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"a":1,"b":1,"c":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"a":1,"b":1,"c":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"a":1,"b":1,"c":1} },
  ],
  "rebar-weight-calculator": [
    { id: "golden-valid", kind: "normal", values: {"diameterMm":1,"lengthM":1,"quantity":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"diameterMm":-1,"lengthM":1,"quantity":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"diameterMm":1,"lengthM":1,"quantity":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"diameterMm":1,"lengthM":1,"quantity":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"diameterMm":1,"lengthM":1,"quantity":1} },
  ],
  "recipe-cost-check": [
    { id: "golden-valid", kind: "normal", values: {"ingredientCost":1,"portions":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"ingredientCost":-1,"portions":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"ingredientCost":1,"portions":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"ingredientCost":1,"portions":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"ingredientCost":1,"portions":1} },
  ],
  "roi-calculator": [
    { id: "golden-valid", kind: "normal", values: {"gain":1,"cost":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"gain":-1,"cost":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"gain":1,"cost":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"gain":1,"cost":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"gain":1,"cost":1} },
  ],
  "roofing-area-calculator": [
    { id: "golden-valid", kind: "normal", values: {"lengthM":1,"widthM":1,"pitchFactor":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"lengthM":-1,"widthM":1,"pitchFactor":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"lengthM":1,"widthM":1,"pitchFactor":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"lengthM":1,"widthM":1,"pitchFactor":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"lengthM":1,"widthM":1,"pitchFactor":1} },
  ],
  "route-cost-calculator": [
    { id: "golden-valid", kind: "normal", values: {"distanceKm":1,"fuelCostPerKm":1,"driverHours":1,"hourlyRate":1,"tolls":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"distanceKm":-1,"fuelCostPerKm":1,"driverHours":1,"hourlyRate":1,"tolls":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"distanceKm":1,"fuelCostPerKm":1,"driverHours":1,"hourlyRate":1,"tolls":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"distanceKm":1,"fuelCostPerKm":1,"driverHours":1,"hourlyRate":1,"tolls":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"distanceKm":1,"fuelCostPerKm":1,"driverHours":1,"hourlyRate":1,"tolls":1} },
  ],
  "savings-goal-calculator": [
    { id: "golden-valid", kind: "normal", values: {"targetAmount":1,"monthlySaving":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"targetAmount":-1,"monthlySaving":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"targetAmount":1,"monthlySaving":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"targetAmount":1,"monthlySaving":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"targetAmount":1,"monthlySaving":1} },
  ],
  "scrap-rate-calculator": [
    { id: "golden-valid", kind: "normal", values: {"scrapUnits":1,"totalUnits":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"scrapUnits":-1,"totalUnits":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"scrapUnits":1,"totalUnits":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"scrapUnits":1,"totalUnits":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"scrapUnits":1,"totalUnits":1} },
  ],
  "seed-rate-calculator": [
    { id: "golden-valid", kind: "normal", values: {"areaHa":1,"seedKgPerHa":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"areaHa":-1,"seedKgPerHa":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"areaHa":1,"seedKgPerHa":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"areaHa":1,"seedKgPerHa":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"areaHa":1,"seedKgPerHa":1} },
  ],
  "sheet-metal-weight-calculator": [
    { id: "golden-valid", kind: "normal", values: {"lengthM":1,"widthM":1,"thicknessMm":1,"densityKgM3":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"lengthM":-1,"widthM":1,"thicknessMm":1,"densityKgM3":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"lengthM":1,"widthM":1,"thicknessMm":1,"densityKgM3":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"lengthM":1,"widthM":1,"thicknessMm":1,"densityKgM3":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"lengthM":1,"widthM":1,"thicknessMm":1,"densityKgM3":1} },
  ],
  "shopping-budget-calculator": [
    { id: "golden-valid", kind: "normal", values: {"item1":1,"item2":1,"item3":1,"item4":1,"item5":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"item1":-1,"item2":1,"item3":1,"item4":1,"item5":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"item1":1,"item2":1,"item3":1,"item4":1,"item5":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"item1":1,"item2":1,"item3":1,"item4":1,"item5":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"item1":1,"item2":1,"item3":1,"item4":1,"item5":1} },
  ],
  "solar-panel-output-calculator": [
    { id: "golden-valid", kind: "normal", values: {"systemKw":1,"sunHoursPerDay":1,"days":1,"efficiencyPercent":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"systemKw":-1,"sunHoursPerDay":1,"days":1,"efficiencyPercent":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"systemKw":1,"sunHoursPerDay":1,"days":1,"efficiencyPercent":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"systemKw":1,"sunHoursPerDay":1,"days":1,"efficiencyPercent":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"systemKw":1,"sunHoursPerDay":1,"days":1,"efficiencyPercent":1} },
  ],
  "square-footage-calculator": [
    { id: "golden-valid", kind: "normal", values: {"length":1,"width":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"length":-1,"width":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"length":1,"width":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"length":1,"width":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"length":1,"width":1} },
  ],
  "square-meter-calculator": [
    { id: "golden-valid", kind: "normal", values: {"length":1,"width":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"length":-1,"width":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"length":1,"width":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"length":1,"width":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"length":1,"width":1} },
  ],
  "stair-calculator": [
    { id: "golden-valid", kind: "normal", values: {"totalRiseCm":1,"riserHeightCm":1,"treadDepthCm":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"totalRiseCm":-1,"riserHeightCm":1,"treadDepthCm":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"totalRiseCm":1,"riserHeightCm":1,"treadDepthCm":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"totalRiseCm":1,"riserHeightCm":1,"treadDepthCm":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"totalRiseCm":1,"riserHeightCm":1,"treadDepthCm":1} },
  ],
  "standard-deviation-calculator": [
    { id: "golden-valid", kind: "normal", values: {"value1":10,"value2":20,"value3":30,"value4":40,"value5":50} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"value1":-1,"value2":20,"value3":30,"value4":40,"value5":50}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"value1":10,"value2":20,"value3":30,"value4":40,"value5":50} },
    { id: "rogue-key", kind: "absurd", values: { ...{"value1":10,"value2":20,"value3":30,"value4":40,"value5":50}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"value1":10,"value2":20,"value3":30,"value4":40,"value5":50} },
  ],
  "tile-calculator": [
    { id: "golden-valid", kind: "normal", values: {"areaM2":1,"tileLengthCm":1,"tileWidthCm":1,"wastePercent":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"areaM2":-1,"tileLengthCm":1,"tileWidthCm":1,"wastePercent":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"areaM2":1,"tileLengthCm":1,"tileWidthCm":1,"wastePercent":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"areaM2":1,"tileLengthCm":1,"tileWidthCm":1,"wastePercent":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"areaM2":1,"tileLengthCm":1,"tileWidthCm":1,"wastePercent":1} },
  ],
  "time-duration-calculator": [
    { id: "golden-valid", kind: "normal", values: {"startHour":1,"startMinute":1,"endHour":1,"endMinute":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"startHour":-1,"startMinute":1,"endHour":1,"endMinute":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"startHour":1,"startMinute":1,"endHour":1,"endMinute":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"startHour":1,"startMinute":1,"endHour":1,"endMinute":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"startHour":1,"startMinute":1,"endHour":1,"endMinute":1} },
  ],
  "tip-calculator": [
    { id: "golden-valid", kind: "normal", values: {"billAmount":1,"tipPercent":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"billAmount":-1,"tipPercent":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"billAmount":1,"tipPercent":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"billAmount":1,"tipPercent":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"billAmount":1,"tipPercent":1} },
  ],
  "tolerance-drift-calculator": [
    { id: "golden-valid", kind: "normal", values: {"target":1,"actual":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"target":-1,"actual":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"target":1,"actual":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"target":1,"actual":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"target":1,"actual":1} },
  ],
  "tool-life-calculator": [
    { id: "golden-valid", kind: "normal", values: {"totalToolCost":1,"partsProduced":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"totalToolCost":-1,"partsProduced":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"totalToolCost":1,"partsProduced":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"totalToolCost":1,"partsProduced":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"totalToolCost":1,"partsProduced":1} },
  ],
  "trip-budget-calculator": [
    { id: "golden-valid", kind: "normal", values: {"fuelCost":1,"accommodationCost":1,"foodCost":1,"tolls":1,"otherCost":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"fuelCost":-1,"accommodationCost":1,"foodCost":1,"tolls":1,"otherCost":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"fuelCost":1,"accommodationCost":1,"foodCost":1,"tolls":1,"otherCost":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"fuelCost":1,"accommodationCost":1,"foodCost":1,"tolls":1,"otherCost":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"fuelCost":1,"accommodationCost":1,"foodCost":1,"tolls":1,"otherCost":1} },
  ],
  "unit-cost-calculator": [
    { id: "golden-valid", kind: "normal", values: {"totalCost":1,"quantity":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"totalCost":-1,"quantity":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"totalCost":1,"quantity":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"totalCost":1,"quantity":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"totalCost":1,"quantity":1} },
  ],
  "unit-price-calculator": [
    { id: "golden-valid", kind: "normal", values: {"totalPrice":1,"quantity":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"totalPrice":-1,"quantity":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"totalPrice":1,"quantity":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"totalPrice":1,"quantity":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"totalPrice":1,"quantity":1} },
  ],
  "vat-calculator": [
    { id: "golden-valid", kind: "normal", values: {"net":1,"vatRate":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"net":-1,"vatRate":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"net":1,"vatRate":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"net":1,"vatRate":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"net":1,"vatRate":1} },
  ],
  "vehicle-depreciation-calculator": [
    { id: "golden-valid", kind: "normal", values: {"purchasePrice":1,"resaleValue":1,"years":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"purchasePrice":-1,"resaleValue":1,"years":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"purchasePrice":1,"resaleValue":1,"years":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"purchasePrice":1,"resaleValue":1,"years":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"purchasePrice":1,"resaleValue":1,"years":1} },
  ],
  "volumetric-weight-calculator": [
    { id: "golden-valid", kind: "normal", values: {"lengthCm":1,"widthCm":1,"heightCm":1,"divisor":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"lengthCm":-1,"widthCm":1,"heightCm":1,"divisor":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"lengthCm":1,"widthCm":1,"heightCm":1,"divisor":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"lengthCm":1,"widthCm":1,"heightCm":1,"divisor":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"lengthCm":1,"widthCm":1,"heightCm":1,"divisor":1} },
  ],
  "warehouse-storage-cost-calculator": [
    { id: "golden-valid", kind: "normal", values: {"palletCount":1,"costPerPalletPerDay":1,"days":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"palletCount":-1,"costPerPalletPerDay":1,"days":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"palletCount":1,"costPerPalletPerDay":1,"days":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"palletCount":1,"costPerPalletPerDay":1,"days":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"palletCount":1,"costPerPalletPerDay":1,"days":1} },
  ],
  "water-usage-calculator": [
    { id: "golden-valid", kind: "normal", values: {"flowRateLiterMin":1,"minutes":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"flowRateLiterMin":-1,"minutes":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"flowRateLiterMin":1,"minutes":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"flowRateLiterMin":1,"minutes":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"flowRateLiterMin":1,"minutes":1} },
  ],
  "z-score-calculator": [
    { id: "golden-valid", kind: "normal", values: {"value":1,"mean":1,"standardDeviation":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"value":-1,"mean":1,"standardDeviation":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"value":1,"mean":1,"standardDeviation":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"value":1,"mean":1,"standardDeviation":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"value":1,"mean":1,"standardDeviation":1} },
  ],
};

function buildOracleOutput(
  slug: BatchTrafficCatalogOracleSlug,
  values: FreeTrafficInputValues,
): NormalizedBatchTrafficCatalogProductionOutput {
  const numeric: Record<string, number> = {};
  for (const [key, value] of Object.entries(values)) {
    if (typeof value === "number" && Number.isFinite(value)) {
      numeric[key] = value;
    }
  }
  return calculateBatchTrafficCatalogOracle(slug, numeric);
}

export function compareBatchTrafficCatalogProductionVsOracle(input: {
  readonly slug: BatchTrafficCatalogOracleSlug;
  readonly scenarioId: string;
  readonly values: FreeTrafficInputValues;
}): OracleComparisonResult {
  const toolId = `free-traffic.${input.slug}`;
  const spec = getBatchTrafficCatalogOracleSpec(input.slug);
  const production = adaptProductionBatchTrafficCatalogOutput(input.slug, input.values);
  if (production.status === "needs_adapter") {
    return {
      status: "NEEDS_ADAPTER",
      slug: input.slug,
      toolId,
      scenarioId: input.scenarioId,
      diffs: [],
      message: production.reason,
    };
  }
  if (production.status === "error") {
    return {
      status: "FAIL",
      slug: input.slug,
      toolId,
      scenarioId: input.scenarioId,
      diffs: [],
      message: production.reason,
    };
  }

  let oracle: NormalizedBatchTrafficCatalogProductionOutput;
  try {
    oracle = buildOracleOutput(input.slug, input.values);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return {
      status: "FAIL",
      slug: input.slug,
      toolId,
      scenarioId: input.scenarioId,
      diffs: [],
      message,
    };
  }

  const productionOutput = production.output as NormalizedBatchTrafficCatalogProductionOutput;
  const fields = Object.keys(oracle)
    .filter((key) => productionOutput[key] !== undefined)
    .map((key) => ({
      field: key,
      production: productionOutput[key],
      oracle: oracle[key],
      tolerance: toleranceForField(key, spec.parseKind),
    }));

  const comparison = compareNumericFields(fields);
  return {
    status: comparison.passed ? "PASS" : "FAIL",
    slug: input.slug,
    toolId,
    scenarioId: input.scenarioId,
    diffs: comparison.diffs,
  };
}

export function runBatchTrafficCatalogOracleComparisonAudit(
  slug: BatchTrafficCatalogOracleSlug,
): OracleComparisonAuditSummary {
  const toolId = `free-traffic.${slug}`;
  const scenarios = SCENARIOS_BY_SLUG[slug] ?? [];
  const comparableScenarios = scenarios.filter((scenario) => scenario.expectPass !== false);

  if (!hasOracleForTool(toolId)) {
    return {
      slug,
      toolId,
      status: "NOT_WIRED",
      passCount: 0,
      failCount: 0,
      needsAdapterCount: 0,
      notWiredCount: scenarios.length,
      results: scenarios.map((scenario) => ({
        slug,
        toolId,
        scenarioId: scenario.id,
        status: "NOT_WIRED" as const,
        diffs: [],
      })),
    };
  }

  const results = comparableScenarios.map((scenario) =>
    compareBatchTrafficCatalogProductionVsOracle({
      slug,
      scenarioId: scenario.id,
      values: scenario.values,
    }),
  );

  const passCount = results.filter((result) => result.status === "PASS").length;
  const failCount = results.filter((result) => result.status === "FAIL").length;
  const needsAdapterCount = results.filter((result) => result.status === "NEEDS_ADAPTER").length;

  let status: OracleComparisonStatus = "PASS";
  if (needsAdapterCount > 0) {
    status = "NEEDS_ADAPTER";
  } else if (failCount > 0) {
    status = "FAIL";
  } else if (passCount === 0) {
    status = "NOT_WIRED";
  }

  return {
    slug,
    toolId,
    status,
    passCount,
    failCount,
    needsAdapterCount,
    notWiredCount: 0,
    results,
  };
}

export function runAllBatchTrafficCatalogOracleComparisonAudits(): readonly OracleComparisonAuditSummary[] {
  return BATCH_TRAFFIC_CATALOG_ORACLE_SLUGS.map((slug) => runBatchTrafficCatalogOracleComparisonAudit(slug));
}
