/**
 * Engine module oracle registry - governance coverage for shared engines.
 * GENERATED by scripts/generate-formula-governance-gap-closure.ts - do not edit manually.
 */

export const ENGINE_MODULES_ORACLE_TOOL_IDS = {
  "revenue-free.fuel-consumption-check": "fuel-consumption-check",
  "engine.risk-engine": "margincore-risk-engine",
  "engine.sector-calculators": "sector-margin-calculators",
} as const;

export type EngineModulesOracleSlug =
  (typeof ENGINE_MODULES_ORACLE_TOOL_IDS)[keyof typeof ENGINE_MODULES_ORACLE_TOOL_IDS];

export function hasEngineModulesOracle(_slug: EngineModulesOracleSlug): boolean {
  return true;
}
