/* eslint-disable */
// @ts-nocheck

/**
 * Roadmap free batch oracle registry — mirror formulas via batch engine.
 * GENERATED by scripts/generate-roadmap-free-batch-governance.mjs — do not edit manually.
 */

import type { FreeTrafficInputValues } from "@/lib/features/tools/free-traffic-calculators";
import {
  calculateRoadmapFreeBatch1Tool,
  hasRoadmapFreeBatch1Calculator,
} from "@/lib/features/tools/roadmap-free-batch1-calculators";
import { calculateRoadmapFreeBatch2Tool } from "@/lib/features/tools/roadmap-free-batch2-calculators";

export const ROADMAP_FREE_BATCH_ORACLE_SLUGS = [
  "abonelik-yazilim-cloud-yillik-maliyet-calc",
  "agirlikli-ortalama-hesaplama",
  "akaryakit-fiyati-ile-yol-butcesi",
  "aku-kapasitesi-calisma-suresi-calc",
  "alti-sigma-dpmo-sigma-seviyesi-cevirici",
  "amper-kilowatt-kw-cevirici",
  "arac-amortisman-hesaplama",
  "arac-bakim-periyodu-takip-hesaplama",
  "arac-kira-satin-alma-karsilastirma",
  "asma-tavan-malzeme-calc",
  "aydinlatma-armatur-sayisi-hesaplama",
  "baca-havalandirma-kanali-cap-calc",
  "bar-psi-pascal-cevirici",
  "basincli-kap-cidar-kalinligi-calc",
  "beygir-gucu-kilowatt-cevirici",
  "boru-agirlik-hesaplama-celik-paslanmaz",
  "boru-capi-akis-hizi-hesaplama",
  "boya-kaplama-sarfiyati-m-basina-calc",
  "bulonlu-baglanti-kesme-ezilme-calc",
  "cay-kahve-su-tuketim-maliyeti",
  "cek-senet-vade-kirma-maliyeti-calc",
  "celik-cati-makas-yaklasik-agirligi",
  "celik-raf-depo-rafi-yuk-kapasitesi",
  "cevre-atik-beyani-maliyet-hesaplama",
  "cit-korkuluk-malzeme-calc",
  "civata-on-germe-kuvveti-calc",
  "civata-sikma-torku-hesaplama",
  "cop-atik-konteyner-hacim-calc",
  "daire-alani-cevresi-hesaplama",
  "depo-raf-palet-yerlesim-optimizasyonu",
  "disli-modul-cap-hesaplama",
  "dizel-benzin-maliyet-karsilastirma",
  "dogalgaz-tuketimi-hesaplama",
  "fx-position-exchange-rate-risk-calc",
  "duvar-kagidi-seramik-adet-hesaplama",
  "enflasyon-fiyat-eskalasyonu-hesaplama",
  "enjeksiyon-dokum-cekme-payi-calc",
  "fazla-mesai-ucreti-hesaplama",
  "forklift-transpalet-kullanim-maliyeti",
  "fotokopi-yazici-toner-sayfa-maliyeti",
  "gelir-vergisi-dilimleri-hesaplama",
  "geri-donusum-gelir-maliyet-calc",
  "gerilim-dusumu-hesaplama",
  "hidrolik-pompa-gucu-hesaplama",
  "hidrolik-silindir-itme-kuvveti-calc",
  "ic-verim-orani-irr-hesaplama",
  "internet-telefon-paketi-karsilastirma",
  "irsaliye-fatura-adedi-basina-sevkiyat-maliyeti",
  "is-elbisesi-kkd-kisisel-koruyucu-donanim-sarfiyati",
  "is-kazasi-maliyeti-gun-kaybi-hesaplama",
  "is-sagligi-ve-guvenligi-ceza-hesaplama",
  "ise-giris-cikis-bildirgesi-sureleri",
  "isi-degistirici-esanjor-kapasite-calc",
  "isitma-sogutma-yuku-kcal-kw-calc",
  "istatistiksel-proses-kontrol-spc-limit-calc",
  "istinat-duvari-yaklasik-beton-calc",
  "jenerator-kapasitesi-secim-hesaplama",
  "joule-kalori-watt-saat-cevirici",
  "kablo-kesiti-mm-secim-hesaplama",
  "kasko-sigorta-prim-karsilastirma",
  "kaynak-dikis-hacmi-maliyeti-calc",
  "kaynak-proseduru-wps-on-isitma-sicakligi-calc",
  "kaynakli-baglanti-kose-kut-mukavemet-calc",
  "kdv-tevkifati-hesaplama",
  "kesir-ondalik-cevirici",
  "kesme-bukme-abkant-tonaj-calc",
  "kiris-kolon-yaklasik-agirlik-calc",
  "klima-btu-secim-hesaplama",
  "kompresor-debisi-tank-hacmi-calc",
  "koni-hacmi-hesaplama",
  "konteyner-yukleme-kapasitesi-teu-calc",
  "kosebent-lama-agirlik-hesaplama",
  "kredi-erken-kapama-cezasi-hesaplama",
  "kumlama-raspa-kum-sarfiyati-calc",
  "kure-hacmi-hesaplama",
  "lastik-omru-degisim-km-hesaplama",
  "leasing-kiralama-maliyet-karsilastirma",
  "lpg-benzin-tasarruf-karsilastirma",
  "makine-ekonomik-omru-hurda-deger-calc",
  "matkap-kilavuz-delik-capi-tablosu",
  "merdiven-platform-yukseklik-erisim-calc",
  "mil-aks-capi-calc-egilme-burulma",
  "motor-gucu-kw-hp-cevirici",
  "mtv-motorlu-tasitlar-vergisi-hesaplama",
  "nakit-akisi-basit-gunluk-haftalik-panosu",
  "newton-kilogram-kuvvet-cevirici",
  "npu-npi-profil-agirlik-hesaplama",
  "ofis-kirtasiye-sarfiyat-calc",
  "paketleme-malzemesi-strec-koli-sarfiyati",
  "palet-ambalaj-kereste-calc",
  "paslanmaz-celik-aluminyum-ayirt-etme-hesaplayicisi-yogunluk-bazli",
  "personel-devamsizlik-maliyeti-hesaplama",
  "plastik-enjeksiyon-cevrim-suresi-tahmini",
  "pnomatik-silindir-kuvvet-calc",
  "pompa-gucu-basma-yuksekligi-calc",
  "prefabrik-konteyner-ofis-m-maliyeti",
  "prefabrik-konteyner-olcu-hesaplama",
  "radyator-petek-boyu-hesaplama",
  "rastgele-sayi-ureteci",
  "rulman-omur-calc-l10",
  "ruzgar-turbini-yaklasik-uretim-calc",
  "ses-yalitimi-desibel-azaltimi-calc",
  "sgk-prim-hesaplama-isci-plus-isveren",
  "silindir-hacmi-hesaplama",
  "sirket-telefon-faturasi-hesaplama",
  "sofor-operator-gunluk-yevmiye-maliyeti",
  "soguk-oda-sogutma-yuku-calc",
  "sogutma-sivisi-karisim-orani-antifriz-bor-yagi-hesaplama",
  "stopaj-hesaplama-kira-serbest-meslek",
  "su-debisi-litre-dakika-hesaplama",
  "su-deposu-hacmi-hesaplama",
  "su-isitma-kazan-boyler-kapasite-calc",
  "tahta-mdf-sunta-m-agirlik-calc",
  "tel-kablo-uzunlugu-agirlik-calc",
  "temizlik-malzemesi-sarfiyat-calc",
  "tir-kamyon-yuk-kapasitesi-hesaplama",
  "titresim-frekans-periyot-hesaplama",
  "toplanti-saati-maliyeti-hesaplama",
  "topraklama-direnci-hesaplama",
  "trafik-cezasi-gecikme-faizi-hesaplama",
  "ucgen-alani-cevresi-hesaplama",
  "ups-kesintisiz-guc-kaynagi-secimi",
  "vida-somun-adim-dis-ustu-cap-calc",
  "yalitim-malzemesi-m-hesaplama",
  "yamuk-alani-hesaplama",
  "yangin-merdiveni-kacis-yolu-genisligi-calc",
  "yangin-tupu-dolap-debisi-hesaplama",
  "yatak-rulman-omur-calc-l10",
  "yay-helisel-kuvvet-uzama-calc",
  "yemek-tabldot-maliyet-hesaplama",
] as const;

export type RoadmapFreeBatchOracleSlug = (typeof ROADMAP_FREE_BATCH_ORACLE_SLUGS)[number];

export type RoadmapFreeBatchParseKind = "plain" | "currency" | "percent" | "integer";

export const ROADMAP_FREE_BATCH_ORACLE_TOOL_IDS = Object.fromEntries(
  ROADMAP_FREE_BATCH_ORACLE_SLUGS.map((slug) => [`free-traffic.${slug}`, slug]),
) as Record<string, RoadmapFreeBatchOracleSlug>;

const PARSE_KIND_BY_SLUG: Readonly<Record<RoadmapFreeBatchOracleSlug, RoadmapFreeBatchParseKind>> = {
  "abonelik-yazilim-cloud-yillik-maliyet-calc": "currency",
  "agirlikli-ortalama-hesaplama": "plain",
  "akaryakit-fiyati-ile-yol-butcesi": "currency",
  "aku-kapasitesi-calisma-suresi-calc": "plain",
  "alti-sigma-dpmo-sigma-seviyesi-cevirici": "plain",
  "amper-kilowatt-kw-cevirici": "plain",
  "arac-amortisman-hesaplama": "currency",
  "arac-bakim-periyodu-takip-hesaplama": "plain",
  "arac-kira-satin-alma-karsilastirma": "currency",
  "asma-tavan-malzeme-calc": "plain",
  "aydinlatma-armatur-sayisi-hesaplama": "plain",
  "baca-havalandirma-kanali-cap-calc": "plain",
  "bar-psi-pascal-cevirici": "plain",
  "basincli-kap-cidar-kalinligi-calc": "plain",
  "beygir-gucu-kilowatt-cevirici": "plain",
  "boru-agirlik-hesaplama-celik-paslanmaz": "plain",
  "boru-capi-akis-hizi-hesaplama": "plain",
  "boya-kaplama-sarfiyati-m-basina-calc": "plain",
  "bulonlu-baglanti-kesme-ezilme-calc": "plain",
  "cay-kahve-su-tuketim-maliyeti": "currency",
  "cek-senet-vade-kirma-maliyeti-calc": "currency",
  "celik-cati-makas-yaklasik-agirligi": "plain",
  "celik-raf-depo-rafi-yuk-kapasitesi": "plain",
  "cevre-atik-beyani-maliyet-hesaplama": "currency",
  "cit-korkuluk-malzeme-calc": "plain",
  "civata-on-germe-kuvveti-calc": "plain",
  "civata-sikma-torku-hesaplama": "plain",
  "cop-atik-konteyner-hacim-calc": "plain",
  "daire-alani-cevresi-hesaplama": "plain",
  "depo-raf-palet-yerlesim-optimizasyonu": "plain",
  "disli-modul-cap-hesaplama": "plain",
  "dizel-benzin-maliyet-karsilastirma": "currency",
  "dogalgaz-tuketimi-hesaplama": "currency",
  "fx-position-exchange-rate-risk-calc": "currency",
  "duvar-kagidi-seramik-adet-hesaplama": "plain",
  "enflasyon-fiyat-eskalasyonu-hesaplama": "currency",
  "enjeksiyon-dokum-cekme-payi-calc": "plain",
  "fazla-mesai-ucreti-hesaplama": "currency",
  "forklift-transpalet-kullanim-maliyeti": "currency",
  "fotokopi-yazici-toner-sayfa-maliyeti": "currency",
  "gelir-vergisi-dilimleri-hesaplama": "currency",
  "geri-donusum-gelir-maliyet-calc": "currency",
  "gerilim-dusumu-hesaplama": "plain",
  "hidrolik-pompa-gucu-hesaplama": "plain",
  "hidrolik-silindir-itme-kuvveti-calc": "plain",
  "ic-verim-orani-irr-hesaplama": "plain",
  "internet-telefon-paketi-karsilastirma": "currency",
  "irsaliye-fatura-adedi-basina-sevkiyat-maliyeti": "currency",
  "is-elbisesi-kkd-kisisel-koruyucu-donanim-sarfiyati": "currency",
  "is-kazasi-maliyeti-gun-kaybi-hesaplama": "currency",
  "is-sagligi-ve-guvenligi-ceza-hesaplama": "currency",
  "ise-giris-cikis-bildirgesi-sureleri": "plain",
  "isi-degistirici-esanjor-kapasite-calc": "plain",
  "isitma-sogutma-yuku-kcal-kw-calc": "plain",
  "istatistiksel-proses-kontrol-spc-limit-calc": "plain",
  "istinat-duvari-yaklasik-beton-calc": "plain",
  "jenerator-kapasitesi-secim-hesaplama": "plain",
  "joule-kalori-watt-saat-cevirici": "plain",
  "kablo-kesiti-mm-secim-hesaplama": "plain",
  "kasko-sigorta-prim-karsilastirma": "currency",
  "kaynak-dikis-hacmi-maliyeti-calc": "plain",
  "kaynak-proseduru-wps-on-isitma-sicakligi-calc": "plain",
  "kaynakli-baglanti-kose-kut-mukavemet-calc": "plain",
  "kdv-tevkifati-hesaplama": "currency",
  "kesir-ondalik-cevirici": "plain",
  "kesme-bukme-abkant-tonaj-calc": "plain",
  "kiris-kolon-yaklasik-agirlik-calc": "plain",
  "klima-btu-secim-hesaplama": "plain",
  "kompresor-debisi-tank-hacmi-calc": "plain",
  "koni-hacmi-hesaplama": "plain",
  "konteyner-yukleme-kapasitesi-teu-calc": "plain",
  "kosebent-lama-agirlik-hesaplama": "plain",
  "kredi-erken-kapama-cezasi-hesaplama": "currency",
  "kumlama-raspa-kum-sarfiyati-calc": "plain",
  "kure-hacmi-hesaplama": "plain",
  "lastik-omru-degisim-km-hesaplama": "plain",
  "leasing-kiralama-maliyet-karsilastirma": "currency",
  "lpg-benzin-tasarruf-karsilastirma": "currency",
  "makine-ekonomik-omru-hurda-deger-calc": "currency",
  "matkap-kilavuz-delik-capi-tablosu": "plain",
  "merdiven-platform-yukseklik-erisim-calc": "plain",
  "mil-aks-capi-calc-egilme-burulma": "plain",
  "motor-gucu-kw-hp-cevirici": "plain",
  "mtv-motorlu-tasitlar-vergisi-hesaplama": "currency",
  "nakit-akisi-basit-gunluk-haftalik-panosu": "currency",
  "newton-kilogram-kuvvet-cevirici": "plain",
  "npu-npi-profil-agirlik-hesaplama": "plain",
  "ofis-kirtasiye-sarfiyat-calc": "currency",
  "paketleme-malzemesi-strec-koli-sarfiyati": "plain",
  "palet-ambalaj-kereste-calc": "plain",
  "paslanmaz-celik-aluminyum-ayirt-etme-hesaplayicisi-yogunluk-bazli": "plain",
  "personel-devamsizlik-maliyeti-hesaplama": "currency",
  "plastik-enjeksiyon-cevrim-suresi-tahmini": "plain",
  "pnomatik-silindir-kuvvet-calc": "plain",
  "pompa-gucu-basma-yuksekligi-calc": "plain",
  "prefabrik-konteyner-ofis-m-maliyeti": "currency",
  "prefabrik-konteyner-olcu-hesaplama": "plain",
  "radyator-petek-boyu-hesaplama": "plain",
  "rastgele-sayi-ureteci": "plain",
  "rulman-omur-calc-l10": "plain",
  "ruzgar-turbini-yaklasik-uretim-calc": "plain",
  "ses-yalitimi-desibel-azaltimi-calc": "currency",
  "sgk-prim-hesaplama-isci-plus-isveren": "currency",
  "silindir-hacmi-hesaplama": "plain",
  "sirket-telefon-faturasi-hesaplama": "currency",
  "sofor-operator-gunluk-yevmiye-maliyeti": "currency",
  "soguk-oda-sogutma-yuku-calc": "plain",
  "sogutma-sivisi-karisim-orani-antifriz-bor-yagi-hesaplama": "plain",
  "stopaj-hesaplama-kira-serbest-meslek": "currency",
  "su-debisi-litre-dakika-hesaplama": "plain",
  "su-deposu-hacmi-hesaplama": "plain",
  "su-isitma-kazan-boyler-kapasite-calc": "plain",
  "tahta-mdf-sunta-m-agirlik-calc": "plain",
  "tel-kablo-uzunlugu-agirlik-calc": "plain",
  "temizlik-malzemesi-sarfiyat-calc": "plain",
  "tir-kamyon-yuk-kapasitesi-hesaplama": "plain",
  "titresim-frekans-periyot-hesaplama": "plain",
  "toplanti-saati-maliyeti-hesaplama": "currency",
  "topraklama-direnci-hesaplama": "plain",
  "trafik-cezasi-gecikme-faizi-hesaplama": "currency",
  "ucgen-alani-cevresi-hesaplama": "plain",
  "ups-kesintisiz-guc-kaynagi-secimi": "plain",
  "vida-somun-adim-dis-ustu-cap-calc": "plain",
  "yalitim-malzemesi-m-hesaplama": "plain",
  "yamuk-alani-hesaplama": "plain",
  "yangin-merdiveni-kacis-yolu-genisligi-calc": "plain",
  "yangin-tupu-dolap-debisi-hesaplama": "plain",
  "yatak-rulman-omur-calc-l10": "plain",
  "yay-helisel-kuvvet-uzama-calc": "plain",
  "yemek-tabldot-maliyet-hesaplama": "currency",
};

export function isRoadmapFreeBatchOracleSlug(slug: string): slug is RoadmapFreeBatchOracleSlug {
  return (ROADMAP_FREE_BATCH_ORACLE_SLUGS as readonly string[]).includes(slug);
}

export function getRoadmapFreeBatchParseKind(slug: RoadmapFreeBatchOracleSlug): RoadmapFreeBatchParseKind {
  return PARSE_KIND_BY_SLUG[slug];
}

function parsePlainNumber(value: string): number | null {
  const cleaned = value.replace(/[^\d.-]/g, "");
  if (!cleaned) {
    return null;
  }
  const parsed = Number(cleaned);
  return Number.isFinite(parsed) ? parsed : null;
}

function parseCurrency(value: string): number | null {
  return parsePlainNumber(value);
}

function parsePercent(value: string): number | null {
  const parsed = parsePlainNumber(value);
  if (parsed === null) {
    return null;
  }
  return value.includes("%") ? parsed : parsed;
}

function parsePrimaryValue(value: string, parseKind: RoadmapFreeBatchParseKind): number | null {
  if (value === "—" || !value.trim()) {
    return null;
  }
  switch (parseKind) {
    case "currency":
      return parseCurrency(value);
    case "percent":
      return parsePercent(value);
    case "integer":
      return parsePlainNumber(value);
    case "plain":
    default:
      return parsePlainNumber(value);
  }
}

export type NormalizedRoadmapFreeBatchProductionOutput = Readonly<{
  readonly recommendedPrice: number;
}>;

export function calculateRoadmapFreeBatchOracle(
  slug: RoadmapFreeBatchOracleSlug,
  values: FreeTrafficInputValues,
): NormalizedRoadmapFreeBatchProductionOutput {
  const result = (hasRoadmapFreeBatch1Calculator(slug)
    ? calculateRoadmapFreeBatch1Tool(slug, values, "en")
    : calculateRoadmapFreeBatch2Tool(slug, values, "en")) as any;
  const recommendedPrice = parsePrimaryValue(result.primaryValue, getRoadmapFreeBatchParseKind(slug));
  if (recommendedPrice === null) {
    throw new Error(`Oracle could not parse primary output for "${slug}".`);
  }
  return { recommendedPrice };
}

export function extractRoadmapFreeBatchRecommendedPrice(
  slug: RoadmapFreeBatchOracleSlug,
  values: FreeTrafficInputValues,
): NormalizedRoadmapFreeBatchProductionOutput {
  return calculateRoadmapFreeBatchOracle(slug, values);
}
