import type { PremiumCalculatorSchema } from "@/lib/features/premium-schema/premium-calculator-schema";

const WAITING_OPPORTUNITY_MODE_OPTIONS = [
  { value: "margin", label: "Derive from unit contribution margin", label_i18n: {"en":"Derive from unit contribution margin","tr":"Derive from unit contribution margin"} },
  { value: "manual", label: "Manual hourly opportunity cost", label_i18n: {"en":"Manual hourly opportunity cost","tr":"Manual hourly opportunity cost"} },
] as const;

const CURRENCY_CODE_OPTIONS = [
  { value: "USD", label: "USD — US Dollar", label_i18n: {"en":"USD — US Dollar","tr":"USD — US Dollar"} },
  { value: "EUR", label: "EUR — Euro", label_i18n: {"en":"EUR — Euro","tr":"EUR — Euro"} },
  { value: "GBP", label: "GBP — British Pound", label_i18n: {"en":"GBP — British Pound","tr":"GBP — British Pound"} },
  { value: "TRY", label: "TRY — Turkish Lira", label_i18n: {"en":"TRY — Turkish Lira","tr":"TRY — Turkish Lira"} },
  { value: "CHF", label: "CHF — Swiss Franc", label_i18n: {"en":"CHF — Swiss Franc","tr":"CHF — Swiss Franc"} },
  { value: "JPY", label: "JPY — Japanese Yen", label_i18n: {"en":"JPY — Japanese Yen","tr":"JPY — Japanese Yen"} },
  { value: "CAD", label: "CAD — Canadian Dollar", label_i18n: {"en":"CAD — Canadian Dollar","tr":"CAD — Canadian Dollar"} },
  { value: "AUD", label: "AUD — Australian Dollar", label_i18n: {"en":"AUD — Australian Dollar","tr":"AUD — Australian Dollar"} },
] as const;

export const SEVEN_MUDA_WASTE_COST_CALCULATOR_SCHEMA: PremiumCalculatorSchema = {
  id: "7-israf-muda-avcisi-parasal-karsilik-calculator",
  legacyPaidSlug: "7-israf-muda-avcisi-parasal-karsilik-calculator",
  name: "7 Waste (Muda) Hunter Monetary Impact Calculator", name_i18n: {"en":"7 Waste (Muda) Hunter Monetary Impact Calculator","tr":"7 Waste (Muda) Hunter Monetary Impact Calculator"},
  sectorSlug: "manufacturing",
  category: "cost",
  painStatement:
    "Quantifies the monetary impact of all 7 Lean wastes (Muda) — overproduction, waiting, transport, inventory, motion, overprocessing, and defects — translating operational inefficiencies into direct financial terms that management can act on.\n\nTraditional waste tracking stops at counting defects or measuring downtime hours. This tool converts every waste category into period-level cost, annualized loss, waste-to-revenue ratio, and risk-adjusted priority scores. It ranks which Muda category costs the most and where kaizen will deliver the highest return.\n\nExample: A factory with 50 overproduction units, 20 waiting hours, and 15 defect units in a 30-day period discovers that waiting and defects represent 62% of $28,500 total waste cost. The tool prioritizes defect reduction with a risk-adjusted score of 4.2/5 and projects $17,700 annual savings.\n\nProduction managers, Lean coordinators, and plant directors use this analyzer to translate Muda into boardroom-ready financial metrics, prioritize improvement investments by ROI, and track waste-to-revenue ratio reduction over consecutive periods.", painStatement_i18n: {"en":"Quantifies the monetary impact of all 7 Lean wastes (Muda) — overproduction, waiting, transport, inventory, motion, overprocessing, and defects — translating operational inefficiencies into direct financial terms that management can act on.\\n\\nTraditional waste tracking stops at counting defects or measuring downtime hours. This tool converts every waste category into period-level cost, annualized loss, waste-to-revenue ratio, and risk-adjusted priority scores. It ranks which Muda category costs the most and where kaizen will deliver the highest return.\\n\\nExample: A factory with 50 overproduction units, 20 waiting hours, and 15 defect units in a 30-day period discovers that waiting and defects represent 62% of $28,500 total waste cost. The tool prioritizes defect reduction with a risk-adjusted score of 4.2/5 and projects $17,700 annual savings.\\n\\nProduction managers, Lean coordinators, and plant directors use this analyzer to translate Muda into boardroom-ready financial metrics, prioritize improvement investments by ROI, and track waste-to-revenue ratio reduction over consecutive periods.","tr":"Quantifies the monetary impact of all 7 Lean wastes (Muda) — overproduction, waiting, transport, inventory, motion, overprocessing, and defects — translating operational inefficiencies into direct financial terms that management can act on.\\n\\nTraditional waste tracking stops at counting defects or measuring downtime hours. This tool converts every waste category into period-level cost, annualized loss, waste-to-revenue ratio, and risk-adjusted priority scores. It ranks which Muda category costs the most and where kaizen will deliver the highest return.\\n\\nExample: A factory with 50 overproduction units, 20 waiting hours, and 15 defect units in a 30-day period discovers that waiting and defects represent 62% of $28,500 total waste cost. The tool prioritizes defect reduction with a risk-adjusted score of 4.2/5 and projects $17,700 annual savings.\\n\\nProduction managers, Lean coordinators, and plant directors use this analyzer to translate Muda into boardroom-ready financial metrics, prioritize improvement investments by ROI, and track waste-to-revenue ratio reduction over consecutive periods."},

  inputs: [
    {
      id: "analysisPeriodDays",
      label: "Analysis period length", label_i18n: {"en":"Analysis period length","tr":"Analysis period length"},
      type: "number",
      unit: "days",
      required: true,
      smartDefault: 30,
      validation: { min: 1 },
      helper: "Number of calendar or working days covered by this analysis window.", helper_i18n: {"en":"Number of calendar or working days covered by this analysis window.","tr":"Number of calendar or working days covered by this analysis window."},
      expertMeaning: "Annualization and inventory holding proration use this period length.", expertMeaning_i18n: {"en":"Annualization and inventory holding proration use this period length.","tr":"Annualization and inventory holding proration use this period length."},
    },
    {
      id: "annualWorkingDays",
      label: "Annual working days", label_i18n: {"en":"Annual working days","tr":"Annual working days"},
      type: "number",
      unit: "days/year",
      required: true,
      smartDefault: 250,
      validation: { min: 1 },
      helper: "Operating days used to annualize period waste exposure.", helper_i18n: {"en":"Operating days used to annualize period waste exposure.","tr":"Operating days used to annualize period waste exposure."},
      expertMeaning: "annualizedWasteCost = totalWasteCost × (annualWorkingDays / analysisPeriodDays).", expertMeaning_i18n: {"en":"annualizedWasteCost = totalWasteCost × (annualWorkingDays / analysisPeriodDays).","tr":"annualizedWasteCost = totalWasteCost × (annualWorkingDays / analysisPeriodDays)."},
    },
    {
      id: "productionUnits",
      label: "Production units in period", label_i18n: {"en":"Production units in period","tr":"Production units in period"},
      type: "number",
      unit: "units",
      required: true,
      smartDefault: 1000,
      validation: { min: 1 },
      helper: "Good units produced inside the selected analysis period only — not annual volume.", helper_i18n: {"en":"Good units produced inside the selected analysis period only — not annual volume.","tr":"Good units produced inside the selected analysis period only — not annual volume."},
      expertMeaning: "Denominator for wasteCostPerUnit and throughput context.", expertMeaning_i18n: {"en":"Denominator for wasteCostPerUnit and throughput context.","tr":"Denominator for wasteCostPerUnit and throughput context."},
    },
    {
      id: "currency",
      label: "Currency", label_i18n: {"en":"Currency","tr":"Currency"},
      type: "select",
      unit: "USD",
      required: true,
      smartDefault: "USD",
      helper: "All monetary inputs below must use this same currency for the analysis period.", helper_i18n: {"en":"All monetary inputs below must use this same currency for the analysis period.","tr":"All monetary inputs below must use this same currency for the analysis period."},
      expertMeaning: "ISO 4217 three-letter code; mixed-currency inputs invalidate comparison.", expertMeaning_i18n: {"en":"ISO 4217 three-letter code; mixed-currency inputs invalidate comparison.","tr":"ISO 4217 three-letter code; mixed-currency inputs invalidate comparison."},
      options: [...CURRENCY_CODE_OPTIONS],
    },
    {
      id: "unitVariableCost",
      label: "Unit variable cost", label_i18n: {"en":"Unit variable cost","tr":"Unit variable cost"},
      type: "number",
      unit: "currency/unit",
      required: true,
      smartDefault: 50,
      validation: { min: 0 },
      helper: "Fully loaded variable cost to produce one good unit.", helper_i18n: {"en":"Fully loaded variable cost to produce one good unit.","tr":"Fully loaded variable cost to produce one good unit."},
      expertMeaning: "Used for overproduction base cost and defect material cost.", expertMeaning_i18n: {"en":"Used for overproduction base cost and defect material cost.","tr":"Used for overproduction base cost and defect material cost."},
    },
    {
      id: "unitSellingPrice",
      label: "Unit selling price", label_i18n: {"en":"Unit selling price","tr":"Unit selling price"},
      type: "number",
      unit: "currency/unit",
      required: true,
      smartDefault: 80,
      validation: { min: 0 },
      helper: "Average selling price per good unit in the analysis period.", helper_i18n: {"en":"Average selling price per good unit in the analysis period.","tr":"Average selling price per good unit in the analysis period."},
      expertMeaning: "Used for periodRevenue and margin-based opportunity cost.", expertMeaning_i18n: {"en":"Used for periodRevenue and margin-based opportunity cost.","tr":"Used for periodRevenue and margin-based opportunity cost."},
    },
    {
      id: "grossMarginPercent",
      label: "Gross margin percent", label_i18n: {"en":"Gross margin percent","tr":"Gross margin percent"},
      type: "number",
      unit: "%",
      required: true,
      smartDefault: 25,
      validation: { min: 0, max: 100 },
      helper: "Gross margin as a percent of selling price per unit.", helper_i18n: {"en":"Gross margin as a percent of selling price per unit.","tr":"Gross margin as a percent of selling price per unit."},
      expertMeaning: "Drives unit contribution margin and waste-to-margin ratio outputs.", expertMeaning_i18n: {"en":"Drives unit contribution margin and waste-to-margin ratio outputs.","tr":"Drives unit contribution margin and waste-to-margin ratio outputs."},
    },
    {
      id: "overproductionUnits",
      label: "Excess production units", label_i18n: {"en":"Excess production units","tr":"Excess production units"},
      type: "number",
      unit: "units",
      required: true,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Units produced beyond confirmed demand or order plan inside the analysis period.", helper_i18n: {"en":"Units produced beyond confirmed demand or order plan inside the analysis period.","tr":"Units produced beyond confirmed demand or order plan inside the analysis period."},
      expertMeaning: "Overproduction volume before write-down adjustments.", expertMeaning_i18n: {"en":"Overproduction volume before write-down adjustments.","tr":"Overproduction volume before write-down adjustments."},
    },
    {
      id: "waitingHours",
      label: "Waiting / downtime hours", label_i18n: {"en":"Waiting / downtime hours","tr":"Waiting / downtime hours"},
      type: "number",
      unit: "hours",
      required: true,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Total hours people, machines, or processes waited idle in the period.", helper_i18n: {"en":"Total hours people, machines, or processes waited idle in the period.","tr":"Total hours people, machines, or processes waited idle in the period."},
      expertMeaning: "Multiplied by hourly opportunity cost per waitingOpportunityCostMode.", expertMeaning_i18n: {"en":"Multiplied by hourly opportunity cost per waitingOpportunityCostMode.","tr":"Multiplied by hourly opportunity cost per waitingOpportunityCostMode."},
    },
    {
      id: "waitingOpportunityCostMode",
      label: "Waiting opportunity cost mode", label_i18n: {"en":"Waiting opportunity cost mode","tr":"Waiting opportunity cost mode"},
      type: "select",
      unit: "mode",
      required: true,
      smartDefault: "margin",
      helper: "Choose manual hourly cost or derive opportunity cost from unit contribution margin.", helper_i18n: {"en":"Choose manual hourly cost or derive opportunity cost from unit contribution margin.","tr":"Choose manual hourly cost or derive opportunity cost from unit contribution margin."},
      expertMeaning: "manual = manualHourlyOpportunityCost; margin = unit contribution margin per hour basis.", expertMeaning_i18n: {"en":"manual = manualHourlyOpportunityCost; margin = unit contribution margin per hour basis.","tr":"manual = manualHourlyOpportunityCost; margin = unit contribution margin per hour basis."},
      options: [...WAITING_OPPORTUNITY_MODE_OPTIONS],
    },
    {
      id: "manualHourlyOpportunityCost",
      label: "Hourly opportunity cost", label_i18n: {"en":"Hourly opportunity cost","tr":"Hourly opportunity cost"},
      type: "number",
      unit: "currency/hour",
      required: true,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Hourly cost used to convert waiting hours into monetary loss when mode is manual.", helper_i18n: {"en":"Hourly cost used to convert waiting hours into monetary loss when mode is manual.","tr":"Hourly cost used to convert waiting hours into monetary loss when mode is manual."},
      expertMeaning: "Applied as waitingHours × manualHourlyOpportunityCost.", expertMeaning_i18n: {"en":"Applied as waitingHours × manualHourlyOpportunityCost.","tr":"Applied as waitingHours × manualHourlyOpportunityCost."},
    },
    {
      id: "unnecessaryTransportCost",
      label: "Unnecessary transport cost", label_i18n: {"en":"Unnecessary transport cost","tr":"Unnecessary transport cost"},
      type: "number",
      unit: "currency",
      required: true,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Unnecessary internal transport, handling, forklift, routing, or shipment cost in the period.", helper_i18n: {"en":"Unnecessary internal transport, handling, forklift, routing, or shipment cost in the period.","tr":"Unnecessary internal transport, handling, forklift, routing, or shipment cost in the period."},
      expertMeaning: "Direct transport waste bucket — no distance model required.", expertMeaning_i18n: {"en":"Direct transport waste bucket — no distance model required.","tr":"Direct transport waste bucket — no distance model required."},
    },
    {
      id: "excessInventoryValue",
      label: "Excess inventory value", label_i18n: {"en":"Excess inventory value","tr":"Excess inventory value"},
      type: "number",
      unit: "currency",
      required: true,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Average value of inventory held above required buffer during the period.", helper_i18n: {"en":"Average value of inventory held above required buffer during the period.","tr":"Average value of inventory held above required buffer during the period."},
      expertMeaning: "Base for inventory carrying cost proration.", expertMeaning_i18n: {"en":"Base for inventory carrying cost proration.","tr":"Base for inventory carrying cost proration."},
    },
    {
      id: "inventoryCarryingRatePercent",
      label: "Inventory carrying rate", label_i18n: {"en":"Inventory carrying rate","tr":"Inventory carrying rate"},
      type: "number",
      unit: "%",
      required: true,
      smartDefault: 20,
      validation: { min: 0, max: 100 },
      helper: "Annual carrying rate including finance, space, insurance, spoilage, and stock risk.", helper_i18n: {"en":"Annual carrying rate including finance, space, insurance, spoilage, and stock risk.","tr":"Annual carrying rate including finance, space, insurance, spoilage, and stock risk."},
      expertMeaning: "Prorated by analysisPeriodDays / annualWorkingDays for period holding cost.", expertMeaning_i18n: {"en":"Prorated by analysisPeriodDays / annualWorkingDays for period holding cost.","tr":"Prorated by analysisPeriodDays / annualWorkingDays for period holding cost."},
    },
    {
      id: "unnecessaryMotionHours",
      label: "Unnecessary motion hours", label_i18n: {"en":"Unnecessary motion hours","tr":"Unnecessary motion hours"},
      type: "number",
      unit: "hours",
      required: true,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Non-value operator, team, or field movement time in the period.", helper_i18n: {"en":"Non-value operator, team, or field movement time in the period.","tr":"Non-value operator, team, or field movement time in the period."},
      expertMeaning: "Multiplied by motionHourlyCost.", expertMeaning_i18n: {"en":"Multiplied by motionHourlyCost.","tr":"Multiplied by motionHourlyCost."},
    },
    {
      id: "motionHourlyCost",
      label: "Motion hourly cost", label_i18n: {"en":"Motion hourly cost","tr":"Motion hourly cost"},
      type: "number",
      unit: "currency/hour",
      required: true,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Hourly cost of unnecessary motion time.", helper_i18n: {"en":"Hourly cost of unnecessary motion time.","tr":"Hourly cost of unnecessary motion time."},
      expertMeaning: "Applied as unnecessaryMotionHours × motionHourlyCost.", expertMeaning_i18n: {"en":"Applied as unnecessaryMotionHours × motionHourlyCost.","tr":"Applied as unnecessaryMotionHours × motionHourlyCost."},
    },
    {
      id: "defectUnits",
      label: "Defect / scrap units", label_i18n: {"en":"Defect / scrap units","tr":"Defect / scrap units"},
      type: "number",
      unit: "units",
      required: true,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Scrap, waste, rework, or quality-defect units in the period.", helper_i18n: {"en":"Scrap, waste, rework, or quality-defect units in the period.","tr":"Scrap, waste, rework, or quality-defect units in the period."},
      expertMeaning: "Defect cost includes variable cost plus rework cost per defect.", expertMeaning_i18n: {"en":"Defect cost includes variable cost plus rework cost per defect.","tr":"Defect cost includes variable cost plus rework cost per defect."},
    },
    {
      id: "reworkCostPerDefect",
      label: "Rework cost per defect", label_i18n: {"en":"Rework cost per defect","tr":"Rework cost per defect"},
      type: "number",
      unit: "currency/unit",
      required: true,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Extra labor, material, or correction cost per defective unit.", helper_i18n: {"en":"Extra labor, material, or correction cost per defective unit.","tr":"Extra labor, material, or correction cost per defective unit."},
      expertMeaning: "Added to unitVariableCost inside defect waste.", expertMeaning_i18n: {"en":"Added to unitVariableCost inside defect waste.","tr":"Added to unitVariableCost inside defect waste."},
    },
    {
      id: "overprocessingHours",
      label: "Overprocessing hours", label_i18n: {"en":"Overprocessing hours","tr":"Overprocessing hours"},
      type: "number",
      unit: "hours",
      required: true,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Extra processing, inspection, approval, or unnecessary operation hours.", helper_i18n: {"en":"Extra processing, inspection, approval, or unnecessary operation hours.","tr":"Extra processing, inspection, approval, or unnecessary operation hours."},
      expertMeaning: "Multiplied by overprocessingHourlyCost.", expertMeaning_i18n: {"en":"Multiplied by overprocessingHourlyCost.","tr":"Multiplied by overprocessingHourlyCost."},
    },
    {
      id: "overprocessingHourlyCost",
      label: "Overprocessing hourly cost", label_i18n: {"en":"Overprocessing hourly cost","tr":"Overprocessing hourly cost"},
      type: "number",
      unit: "currency/hour",
      required: true,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Hourly cost of overprocessing time.", helper_i18n: {"en":"Hourly cost of overprocessing time.","tr":"Hourly cost of overprocessing time."},
      expertMeaning: "Applied as overprocessingHours × overprocessingHourlyCost.", expertMeaning_i18n: {"en":"Applied as overprocessingHours × overprocessingHourlyCost.","tr":"Applied as overprocessingHours × overprocessingHourlyCost."},
    },
    {
      id: "dataConfidencePercent",
      label: "Data confidence", label_i18n: {"en":"Data confidence","tr":"Data confidence"},
      type: "number",
      unit: "%",
      required: true,
      smartDefault: 70,
      validation: { min: 0, max: 100 },
      helper: "Your confidence that the entered waste drivers reflect actual shop-floor data.", helper_i18n: {"en":"Your confidence that the entered waste drivers reflect actual shop-floor data.","tr":"Your confidence that the entered waste drivers reflect actual shop-floor data."},
      expertMeaning: "Feeds confidenceLevel and riskAdjustedPriorityScore in the decision output.", expertMeaning_i18n: {"en":"Feeds confidenceLevel and riskAdjustedPriorityScore in the decision output.","tr":"Feeds confidenceLevel and riskAdjustedPriorityScore in the decision output."},
    },
    {
      id: "implementationDifficulty",
      label: "Implementation difficulty", label_i18n: {"en":"Implementation difficulty","tr":"Implementation difficulty"},
      type: "number",
      unit: "score",
      required: true,
      smartDefault: 3,
      validation: { min: 1, max: 5, step: 1 },
      helper: "How hard it is to implement fixes: 1 = easy kaizen, 5 = major capital or layout change.", helper_i18n: {"en":"How hard it is to implement fixes: 1 = easy kaizen, 5 = major capital or layout change.","tr":"How hard it is to implement fixes: 1 = easy kaizen, 5 = major capital or layout change."},
      expertMeaning: "Higher difficulty reduces riskAdjustedPriorityScore for otherwise large savings.", expertMeaning_i18n: {"en":"Higher difficulty reduces riskAdjustedPriorityScore for otherwise large savings.","tr":"Higher difficulty reduces riskAdjustedPriorityScore for otherwise large savings."},
    },
  ],

  formulaPipeline: [
    {
      formulaId: "lean.muda_overproduction_cost",
      inputMap: {
        excessUnits: "overproductionUnits",
        unitProductionCost: "unitVariableCost",
        inventoryHoldingRatePct: "inventoryCarryingRatePercent",
      },
      outputId: "overproductionCost",
    },
    {
      formulaId: "lean.muda_waiting_cost",
      inputMap: {},
      outputId: "waitingCost",
    },
    {
      formulaId: "lean.muda_transport_cost",
      inputMap: {},
      outputId: "transportCost",
    },
    {
      formulaId: "lean.muda_inventory_cost",
      inputMap: {
        averageExcessInventoryValue: "excessInventoryValue",
        inventoryHoldingRatePct: "inventoryCarryingRatePercent",
      },
      outputId: "inventoryCost",
    },
    {
      formulaId: "lean.muda_motion_cost",
      inputMap: {},
      outputId: "motionCost",
    },
    {
      formulaId: "lean.muda_overprocessing_cost",
      inputMap: {},
      outputId: "overprocessingCost",
    },
    {
      formulaId: "lean.muda_defect_cost",
      inputMap: {},
      outputId: "defectCost",
    },
    {
      formulaId: "lean.muda_total_waste_cost",
      inputMap: {
        overproductionCost: "overproductionCost",
        waitingCost: "waitingCost",
        transportCost: "transportCost",
        inventoryCost: "inventoryCost",
        motionCost: "motionCost",
        overprocessingCost: "overprocessingCost",
        defectCost: "defectCost",
      },
      outputId: "totalWasteCost",
    },
    {
      formulaId: "lean.muda_annualized_waste_cost",
      inputMap: {},
      outputId: "annualizedWasteCost",
    },
    {
      formulaId: "lean.muda_waste_cost_per_unit",
      inputMap: {},
      outputId: "wasteCostPerUnit",
    },
    {
      formulaId: "lean.muda_period_revenue",
      inputMap: {},
      outputId: "periodRevenue",
    },
    {
      formulaId: "lean.muda_period_gross_margin_value",
      inputMap: {},
      outputId: "periodGrossMarginValue",
    },
    {
      formulaId: "lean.muda_waste_to_revenue_ratio_pct",
      inputMap: {},
      outputId: "wasteToRevenueRatioPct",
    },
    {
      formulaId: "lean.muda_waste_to_gross_margin_ratio_pct",
      inputMap: {},
      outputId: "wasteToGrossMarginRatioPct",
    },
    {
      formulaId: "lean.muda_highest_waste_cost",
      inputMap: {},
      outputId: "highestWasteCost",
    },
    {
      formulaId: "lean.muda_risk_adjusted_priority_score",
      inputMap: {},
      outputId: "riskAdjustedPriorityScore",
    },
    {
      formulaId: "lean.muda_highest_waste_index",
      inputMap: {
        overproductionCost: "overproductionCost",
        waitingCost: "waitingCost",
        transportCost: "transportCost",
        inventoryCost: "inventoryCost",
        motionCost: "motionCost",
        overprocessingCost: "overprocessingCost",
        defectCost: "defectCost",
      },
      outputId: "highestWasteCategoryIndex",
    },
  ],

  outputs: [
    {
      id: "totalWasteCost",
      label: "Total waste cost", label_i18n: {"en":"Total waste cost","tr":"Total waste cost"},
      unit: "USD",
      format: "currency",
      isBigNumber: true,
    },
    {
      id: "annualizedWasteCost",
      label: "Annualized waste cost", label_i18n: {"en":"Annualized waste cost","tr":"Annualized waste cost"},
      unit: "USD",
      format: "currency",
    },
    {
      id: "wasteCostPerUnit",
      label: "Waste cost per unit", label_i18n: {"en":"Waste cost per unit","tr":"Waste cost per unit"},
      unit: "USD",
      format: "currency",
    },
    {
      id: "periodRevenue",
      label: "Period revenue", label_i18n: {"en":"Period revenue","tr":"Period revenue"},
      unit: "USD",
      format: "currency",
    },
    {
      id: "periodGrossMarginValue",
      label: "Period gross margin value", label_i18n: {"en":"Period gross margin value","tr":"Period gross margin value"},
      unit: "USD",
      format: "currency",
    },
    {
      id: "wasteToRevenueRatioPct",
      label: "Waste to revenue ratio", label_i18n: {"en":"Waste to revenue ratio","tr":"Waste to revenue ratio"},
      unit: "%",
      format: "percentage",
    },
    {
      id: "wasteToGrossMarginRatioPct",
      label: "Waste to gross margin ratio", label_i18n: {"en":"Waste to gross margin ratio","tr":"Waste to gross margin ratio"},
      unit: "%",
      format: "percentage",
    },
    {
      id: "highestWasteCost",
      label: "Highest waste category cost", label_i18n: {"en":"Highest waste category cost","tr":"Highest waste category cost"},
      unit: "USD",
      format: "currency",
    },
    {
      id: "riskAdjustedPriorityScore",
      label: "Risk-adjusted priority score", label_i18n: {"en":"Risk-adjusted priority score","tr":"Risk-adjusted priority score"},
      unit: "score",
      format: "score",
    },
    {
      id: "overproductionCost",
      label: "Overproduction cost", label_i18n: {"en":"Overproduction cost","tr":"Overproduction cost"},
      unit: "USD",
      format: "currency",
    },
    {
      id: "waitingCost",
      label: "Waiting cost", label_i18n: {"en":"Waiting cost","tr":"Waiting cost"},
      unit: "USD",
      format: "currency",
    },
    {
      id: "transportCost",
      label: "Transport cost", label_i18n: {"en":"Transport cost","tr":"Transport cost"},
      unit: "USD",
      format: "currency",
    },
    {
      id: "inventoryCost",
      label: "Inventory cost", label_i18n: {"en":"Inventory cost","tr":"Inventory cost"},
      unit: "USD",
      format: "currency",
    },
    {
      id: "motionCost",
      label: "Motion cost", label_i18n: {"en":"Motion cost","tr":"Motion cost"},
      unit: "USD",
      format: "currency",
    },
    {
      id: "overprocessingCost",
      label: "Overprocessing cost", label_i18n: {"en":"Overprocessing cost","tr":"Overprocessing cost"},
      unit: "USD",
      format: "currency",
    },
    {
      id: "defectCost",
      label: "Defect cost", label_i18n: {"en":"Defect cost","tr":"Defect cost"},
      unit: "USD",
      format: "currency",
    },
    {
      id: "highestWasteCategoryIndex",
      label: "Highest waste category rank", label_i18n: {"en":"Highest waste category rank","tr":"Highest waste category rank"},
      unit: "rank",
      format: "number",
    },
  ],

  thresholds: [
    {
      fieldId: "totalWasteCost",
      warning: 5000,
      critical: 15000,
      direction: "higher_is_bad",
      warningMessage: "Total muda exposure is material — review the highest waste category and recommended action order.", warningMessage_i18n: {"en":"Total muda exposure is material — review the highest waste category and recommended action order.","tr":"Total muda exposure is material — review the highest waste category and recommended action order."},
      criticalMessage: "Total muda exposure is severe — launch focused kaizen on the dominant waste driver.", criticalMessage_i18n: {"en":"Total muda exposure is severe — launch focused kaizen on the dominant waste driver.","tr":"Total muda exposure is severe — launch focused kaizen on the dominant waste driver."},
    },
  ],

  reportTemplate: {
    title: "7 Muda Monetary Impact Decision Report", title_i18n: {"en":"7 Muda Monetary Impact Decision Report","tr":"7 Muda Monetary Impact Decision Report"},
    sections: ["executive_summary", "loss_breakdown", "thresholds", "action_plan", "assumptions"],
    exportFormats: ["pdf", "csv"],
  },

  assumptions: {
    hiddenLossMultiplier: 1,
    volatilityPercent: 8,
    targetMarginPercent: 0,
    assumptionNotes: [
      "All monetary inputs must use the selected currency for the analysis period.",
      "productionUnits is the production volume inside the selected analysis period only.",
      "Waiting opportunity cost uses manual hourly rate or unit contribution margin per the selected mode.",
      "Inventory carrying cost prorates annual rate by analysisPeriodDays / annualWorkingDays.",
      "This tool produces operational loss estimates — not ERP reconciliation or audited financial statements.",
    ],assumptionNotes_i18n:[{"en":"All monetary inputs must use the selected currency for the analysis period.","tr":"All monetary inputs must use the selected currency for the analysis period."},{"en":"productionUnits is the production volume inside the selected analysis period only.","tr":"productionUnits is the production volume inside the selected analysis period only."},{"en":"Waiting opportunity cost uses manual hourly rate or unit contribution margin per the selected mode.","tr":"Waiting opportunity cost uses manual hourly rate or unit contribution margin per the selected mode."},{"en":"Inventory carrying cost prorates annual rate by analysisPeriodDays / annualWorkingDays.","tr":"Inventory carrying cost prorates annual rate by analysisPeriodDays / annualWorkingDays."},{"en":"This tool produces operational loss estimates — not ERP reconciliation or audited financial statements.","tr":"This tool produces operational loss estimates — not ERP reconciliation or audited financial statements."}],
  },
};
