import type { PremiumCalculatorSchema } from "@/lib/features/premium-schema/premium-calculator-schema";
export const CARBON_FOOTPRINT_CHECK_SCHEMA: PremiumCalculatorSchema = {
  id: "carbon-footprint-check-analyzer", legacyPaidSlug: "carbon-footprint-check-analyzer",
  name: "Carbon Footprint Check", name_i18n: {"en":"Carbon Footprint Check"}, sectorSlug: "energy-carbon", category: "measurement",
  painStatement: "Without calculating carbon footprint, exporters face financial risk from CBAM and carbon taxes.", painStatement_i18n: {"en":"Without calculating carbon footprint, exporters face financial risk from CBAM and carbon taxes."},
  inputs: [
    { id: "fuelConsumption", label: "Fuel Consumption (MWh)", label_i18n: {"en":"Fuel Consumption (MWh)"}, type: "number", unit: "MWh", required: false, smartDefault: 500, validation: { min: 0 }, helper: "", expertMeaning: "Total fuel energy consumption", expertMeaning_i18n: {"en":"Total fuel energy consumption"} },
    { id: "fuelEF", label: "Fuel Emission Factor", label_i18n: {"en":"Fuel Emission Factor"}, type: "number", unit: "tCO2e/MWh", required: false, smartDefault: 0.27, validation: { min: 0 }, helper: "", expertMeaning: "Emission factor per MWh", expertMeaning_i18n: {"en":"Emission factor per MWh"} },
    { id: "fugitive", label: "Fugitive Emissions", label_i18n: {"en":"Fugitive Emissions"}, type: "number", unit: "tCO2e", required: false, smartDefault: 0, validation: { min: 0 }, helper: "", expertMeaning: "Fugitive emissions", expertMeaning_i18n: {"en":"Fugitive emissions"} },
    { id: "electricity", label: "Elektrik Tüketimi", label_i18n: {"en":"Electricity Consumption"}, type: "number", unit: "MWh", required: true, smartDefault: 1000, validation: { min: 0 }, helper: "", expertMeaning: "Grid electricity consumption", expertMeaning_i18n: {"en":"Grid electricity consumption"} },
    { id: "gridEF", label: "Grid Emission Factor", label_i18n: {"en":"Grid Emission Factor"}, type: "number", unit: "tCO2e/MWh", required: true, smartDefault: 0.45, validation: { min: 0 }, helper: "", expertMeaning: "Grid emission factor", expertMeaning_i18n: {"en":"Grid emission factor"} },
    { id: "recFactor", label: "YEK Sertifika Faktörü", label_i18n: {"en":"REC Offset Factor"}, type: "number", unit: "tCO2e/MWh", required: false, smartDefault: 0, validation: { min: 0 }, helper: "", expertMeaning: "REC offset factor", expertMeaning_i18n: {"en":"REC offset factor"} },
    { id: "material", label: "Malzeme Tüketimi", label_i18n: {"en":"Material Consumption"}, type: "number", unit: "ton", required: false, smartDefault: 200, validation: { min: 0 }, helper: "", expertMeaning: "Raw material consumption", expertMeaning_i18n: {"en":"Raw material consumption"} },
    { id: "materialEF", label: "Malzeme Emisyon Faktörü", label_i18n: {"en":"Material Emission Factor"}, type: "number", unit: "tCO2e/ton", required: false, smartDefault: 1.5, validation: { min: 0 }, helper: "", expertMeaning: "Material emission factor", expertMeaning_i18n: {"en":"Material emission factor"} },
    { id: "logisticsEF", label: "Lojistik Emisyon", label_i18n: {"en":"Logistics Emissions"}, type: "number", unit: "tCO2e", required: false, smartDefault: 50, validation: { min: 0 }, helper: "", expertMeaning: "Logistics emissions total", expertMeaning_i18n: {"en":"Logistics emissions total"} },
    { id: "productionVolume", label: "Üretim Hacmi", label_i18n: {"en":"Production Volume"}, type: "number", unit: "ton", required: true, smartDefault: 5000, validation: { min: 1 }, helper: "", expertMeaning: "Total production volume", expertMeaning_i18n: {"en":"Total production volume"} },
    { id: "carbonPrice", label: "Forecast Carbon Price", label_i18n: {"en":"Forecast Carbon Price"}, type: "number", unit: "USD/ton", required: true, smartDefault: 80, validation: { min: 0 }, helper: "", expertMeaning: "Forecast carbon price", expertMeaning_i18n: {"en":"Forecast carbon price"} },
  ],
  outputs: [
    { id: "scope1", label: "Scope 1 Emisyon", label_i18n: {"en":"Scope 1 emission"}, unit: "tCO2e", format: "number" },
    { id: "scope2Market", label: "Scope 2 Piyasa Bazl", label_i18n: {"en":"Scope 2 Piyasa Bazl"}, unit: "tCO2e", format: "number" },
    { id: "scope3", label: "Scope 3 Yukar Aks", label_i18n: {"en":"Scope 3 Yukar Aks"}, unit: "tCO2e", format: "number" },
    { id: "totalCarbon", label: "Total Carbon Footprint", label_i18n: {"en":"Total Carbon Footprint"}, unit: "tCO2e", format: "number", isBigNumber: true },
    { id: "carbonIntensity", label: "Karbon Yogunlugu", label_i18n: {"en":"Carbon Yogunlugu"}, unit: "tCO2e/ton", format: "number" },
    { id: "financialRisk", label: "Finansal Risk (Karbon)", label_i18n: {"en":"Finansal Risk (Carbon)"}, unit: "USD", format: "currency" },
  ],
  thresholds: [{ fieldId: "carbonIntensity", warning: 1, critical: 2.5, direction: "higher_is_bad", warningMessage: "Carbon intensity > 1 — above industry average.", warningMessage_i18n: {"en":"Carbon intensity > 1 — above industry average."}, criticalMessage: "Carbon intensity > 2.5 — CBAM risk high.", criticalMessage_i18n: {"en":"Carbon intensity > 2.5 — CBAM risk high."} }],
  formulaPipeline: [
    { formulaId: "measurement.carbon_scope1", inputMap: { fuelConsumption: "fuelConsumption", fuelEF: "fuelEF", fugitive: "fugitive" }, outputId: "scope1" },
    { formulaId: "measurement.carbon_scope2_market", inputMap: { electricity: "electricity", gridEF: "gridEF", recFactor: "recFactor" }, outputId: "scope2Market" },
    { formulaId: "measurement.carbon_scope3_upstream", inputMap: { material: "material", materialEF: "materialEF", logisticsEF: "logisticsEF" }, outputId: "scope3" },
    { formulaId: "measurement.carbon_total", inputMap: { scope1: "scope1", scope2Market: "scope2Market", scope3: "scope3" }, outputId: "totalCarbon" },
    { formulaId: "measurement.carbon_intensity", inputMap: { totalCarbon: "totalCarbon", productionVolume: "productionVolume" }, outputId: "carbonIntensity" },
    { formulaId: "cost.carbon_financial_risk", inputMap: { totalCarbon: "totalCarbon", carbonPrice: "carbonPrice" }, outputId: "financialRisk" },
  ],
  reportTemplate: { title: "Carbon Footprint Report", title_i18n: {"en":"Carbon Footprint Report"}, sections: ["executive_summary", "loss_breakdown", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1, volatilityPercent: 15, targetMarginPercent: 20, assumptionNotes: ["Scope 2 market-based = electricity × (gridEF - REC).", "CBAM 2026 sonrası karbon fiyatı ~80 EUR/ton.", "Karbon yoğunluğu = toplam / üretim hacmi."],assumptionNotes_i18n:[{"en":"Scope 2 market-based = electricity × (gridEF - REC)."},{"en":"CBAM 2026 sonrası karbon fiyatı ~80 EUR/ton."},{"en":"Karbon yoğunluğu = toplam / üretim hacmi."}]},
};
