/**
 * Tool #20 — Cloud Waste Elimination Analyzer
 * ZombieResource + OversizingSavings + SpotSavings + ReservedSavings + IdleHoursCost
 */
import type { PremiumCalculatorSchema } from "@/lib/features/premium-schema/premium-calculator-schema";
export const CLOUD_WASTE_ELIMINATION_SCHEMA: PremiumCalculatorSchema = {
  id: "cloud-waste-elimination-analyzer", legacyPaidSlug: "cloud-waste-elimination-analyzer",
  name: "Cloud Waste Elimination Analyzer", name_i18n: {"en":"Cloud Waste Elimination Analyzer"}, sectorSlug: "it-cloud", category: "cost",
  painStatement: "30-45% of cloud spending consists of unnecessary resources: zombie resources, over-provisioning, and idle instances. This tool calculates total waste and shows savings potential.", painStatement_i18n: {"en":"30-45% of cloud spending consists of unnecessary resources: zombie resources, over-provisioning, and idle instances. This tool calculates total waste and shows savings potential."},
  inputs: [
    { id: "unattachedVolumes", label: "Unattached EBS volumes", label_i18n: {"en":"Unattached EBS volumes"}, type: "number", unit: "adet", required: true, smartDefault: 10, validation: { min: 0 }, helper: "", expertMeaning: "Unattached EBS volumes", expertMeaning_i18n: {"en":"Unattached EBS volumes"} },
    { id: "volumeRatePerMonth", label: "Disk Birim Fiyat", label_i18n: {"en":"Disk Unit Fiyat"}, type: "number", unit: "USD/ay", required: true, smartDefault: 10, validation: { min: 0 }, helper: "", expertMeaning: "Monthly cost per unattached volume", expertMeaning_i18n: {"en":"Monthly cost per unattached volume"} },
    { id: "orphanSnapshotGb", label: "Orphaned snapshots total GB", label_i18n: {"en":"Orphaned snapshots total GB"}, type: "number", unit: "GB", required: false, smartDefault: 500, validation: { min: 0 }, helper: "", expertMeaning: "Orphaned snapshots total GB", expertMeaning_i18n: {"en":"Orphaned snapshots total GB"} },
    { id: "snapshotStorageRate", label: "Snapshot Depolama Ucreti", label_i18n: {"en":"S3/EFS snapshot cost per GB"}, type: "number", unit: "USD/GB/ay", required: false, smartDefault: 0.05, validation: { min: 0 }, helper: "", expertMeaning: "S3/EFS snapshot cost per GB", expertMeaning_i18n: {"en":"S3/EFS snapshot cost per GB"} },
    { id: "currentInstanceCost", label: "Mevcut Instance Maliyeti", label_i18n: {"en":"Current Instance Cost"}, type: "number", unit: "USD/ay", required: true, smartDefault: 5000, validation: { min: 0 }, helper: "", expertMeaning: "Current monthly compute cost", expertMeaning_i18n: {"en":"Current monthly compute cost"} },
    { id: "rightSizedInstanceCost", label: "Right-Sized Instance Maliyeti", label_i18n: {"en":"Right-Sized Instance Cost"}, type: "number", unit: "USD/ay", required: true, smartDefault: 3500, validation: { min: 0 }, helper: "", expertMeaning: "Optimized monthly compute cost", expertMeaning_i18n: {"en":"Optimized monthly compute cost"} },
    { id: "spotUsageRatio", label: "Current spot adoption", label_i18n: {"en":"Current spot adoption"}, type: "number", unit: "%", required: false, smartDefault: 20, validation: { min: 0, max: 100 }, helper: "", expertMeaning: "Current spot adoption", expertMeaning_i18n: {"en":"Current spot adoption"} },
    { id: "targetSpotRatio", label: "Target spot adoption", label_i18n: {"en":"Target spot adoption"}, type: "number", unit: "%", required: false, smartDefault: 50, validation: { min: 0, max: 100 }, helper: "", expertMeaning: "Target spot adoption", expertMeaning_i18n: {"en":"Target spot adoption"} },
    { id: "onDemandCost", label: "On-demand spend eligible for RI", label_i18n: {"en":"On-demand spend eligible for RI"}, type: "number", unit: "USD", required: false, smartDefault: 3000, validation: { min: 0 }, helper: "", expertMeaning: "On-demand spend eligible for RI", expertMeaning_i18n: {"en":"On-demand spend eligible for RI"} },
    { id: "reservedCost", label: "Reserved instance cost", label_i18n: {"en":"Reserved instance cost"}, type: "number", unit: "USD", required: false, smartDefault: 2000, validation: { min: 0 }, helper: "", expertMeaning: "Reserved instance cost", expertMeaning_i18n: {"en":"Reserved instance cost"} },
    { id: "nonBizHoursInstances", label: "Instances running 24/7 unnecessarily", label_i18n: {"en":"Instances running 24/7 unnecessarily"}, type: "number", unit: "adet", required: false, smartDefault: 5, validation: { min: 0 }, helper: "", expertMeaning: "Instances running 24/7 unnecessarily", expertMeaning_i18n: {"en":"Instances running 24/7 unnecessarily"} },
    { id: "nonBizHoursPerMonth", label: "Non-business hours per month", label_i18n: {"en":"Non-business hours per month"}, type: "number", unit: "saat", required: false, smartDefault: 300, validation: { min: 0 }, helper: "", expertMeaning: "Non-business hours per month", expertMeaning_i18n: {"en":"Non-business hours per month"} },
    { id: "instanceHourlyRate", label: "Instance Saatlik Maliyet", label_i18n: {"en":"Instance Hourly Cost"}, type: "number", unit: "USD/saat", required: false, smartDefault: 0.50, validation: { min: 0 }, helper: "", expertMeaning: "Average hourly instance cost", expertMeaning_i18n: {"en":"Average hourly instance cost"} },
    { id: "zombieCostInput", label: "Zombie Kaynak Maliyeti (Tahmini)", label_i18n: {"en":"Zombie resource Cost (Estimated)"}, type: "number", unit: "USD/ay", required: false, smartDefault: 350, validation: { min: 0 }, helper: "Bagimsiz diskler + atil snapshotlar.", helper_i18n: {"en":"Orphaned disks + idle snapshots."}, expertMeaning: "Zombie resource cost per month", expertMeaning_i18n: {"en":"Zombie resource cost per month"} },
    { id: "oversizingSavingsInput", label: "Monthly oversizing waste", label_i18n: {"en":"Monthly oversizing waste"}, type: "number", unit: "USD/ay", required: false, smartDefault: 1500, validation: { min: 0 }, helper: "Mevcut - right-sized farki.", helper_i18n: {"en":"Current - right-sized difference."}, expertMeaning: "Monthly oversizing waste", expertMeaning_i18n: {"en":"Monthly oversizing waste"} },
    { id: "spotSavingsInput", label: "Spot Instance Tasarruf Potansiyeli", label_i18n: {"en":"Spot Instance Tasarruf Potansiyeli"}, type: "number", unit: "USD/ay", required: false, smartDefault: 450, validation: { min: 0 }, helper: "Spot kullanim artisindan tasarruf.", helper_i18n: {"en":"Savings from increased spot usage."}, expertMeaning: "Additional spot savings potential", expertMeaning_i18n: {"en":"Additional spot savings potential"} },
    { id: "reservedSavingsInput", label: "Reserved Instance Tasarrufu", label_i18n: {"en":"Reserved Instance Tasarrufu"}, type: "number", unit: "USD/ay", required: false, smartDefault: 600, validation: { min: 0 }, helper: "Reserved vs on-demand farki.", helper_i18n: {"en":"Reserved vs on-demand difference."}, expertMeaning: "RI savings per month", expertMeaning_i18n: {"en":"RI savings per month"} },
    { id: "idleHoursCostInput", label: "Non-business hours instance cost", label_i18n: {"en":"Non-business hours instance cost"}, type: "number", unit: "USD/ay", required: false, smartDefault: 750, validation: { min: 0 }, helper: "Mesai disi calisan instance'lar.", helper_i18n: {"en":"Instances running outside business hours."}, expertMeaning: "Non-business hours instance cost", expertMeaning_i18n: {"en":"Non-business hours instance cost"} },
  ],
  outputs: [
    { id: "zombieResourceCost", label: "Zombie Kaynak Maliyeti", label_i18n: {"en":"Zombie resource Cost"}, unit: "USD/ay", format: "currency" },
    { id: "oversizingSavings", label: "Asr Boyutlandrma Tasarrufu", label_i18n: {"en":"Asr Boyutlandrma Tasarrufu"}, unit: "USD/ay", format: "currency" },
    { id: "idleHoursCost", label: "Bosta Calsan Instance Maliyeti", label_i18n: {"en":"Bosta Employee Instance Cost"}, unit: "USD/ay", format: "currency" },
    { id: "totalWasteEliminated", label: "Toplam Israf (Aylk)", label_i18n: {"en":"Total Waste (Aylk)"}, unit: "USD/ay", format: "currency", isBigNumber: true },
  ],
  thresholds: [
    { fieldId: "totalWasteEliminated", warning: 2000, critical: 10000, direction: "higher_is_bad", warningMessage: "Aylik israf > $2K — bulut maliyet optimizasyonu plani baslatilmali.", warningMessage_i18n: {"en":"Monthly Waste > $2K — cloud Cost optimization plan should be initiated."}, criticalMessage: "Aylik israf > $10K — acil FinOps mudahalesi gerekiyor.", criticalMessage_i18n: {"en":"Monthly Waste > $10K — urgent FinOps intervention required."} },
  ],
  formulaPipeline: [
    { formulaId: "cost.cloud_waste_total", inputMap: { zombieCost: "zombieCostInput", oversizingSavings: "oversizingSavingsInput", spotSavings: "spotSavingsInput", reservedSavings: "reservedSavingsInput", idleHoursCost: "idleHoursCostInput" }, outputId: "totalWasteEliminated" },
  ],
  reportTemplate: { title: "Cloud Waste Elimination Report", title_i18n: {"en":"Cloud Waste Elimination Report"}, sections: ["executive_summary", "loss_breakdown", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.15, volatilityPercent: 15, targetMarginPercent: 20, assumptionNotes: ["Zombie cost = Unattached volumes × Rate + Orphan snapshots × Storage rate.", "Oversizing savings = (Current - RightSized) per month.", "Spot savings = (OnDemand - Spot) × fault-tolerant workload ratio.", "Reserved instance savings = (OnDemand - Reserved) × utilization.", "Idle hours cost = Non-business hours × Running instances × Hourly rate.", "Average waste: 30% overprovisioned, 20% idle, 15% zombie resources."],assumptionNotes_i18n:[{"en":"Zombie cost = Unattached volumes × Rate + Orphan snapshots × Storage rate."},{"en":"Oversizing savings = (Current - RightSized) per month."},{"en":"Spot savings = (OnDemand - Spot) × fault-tolerant workload ratio."},{"en":"Reserved instance savings = (OnDemand - Reserved) × utilization."},{"en":"Idle hours cost = Non-business hours × Running instances × Hourly rate."},{"en":"Average waste: 30% overprovisioned, 20% idle, 15% zombie resources."}] },
};
