/**
 * Tool #10 — Basınçlı Hava Sistemi Enerji Maliyeti
 * CompressorPower → AnnualEnergyCost → TotalAnnualCost
 */
import type { PremiumCalculatorSchema } from "@/lib/features/premium-schema/premium-calculator-schema";
export const COMPRESSED_AIR_SCHEMA: PremiumCalculatorSchema = {
  id: "compressed-air-energy-cost-analyzer", legacyPaidSlug: "compressed-air-energy-cost-analyzer",
  name: "Compressed Air System Energy Cost Analyzer", name_i18n: {"en":"Compressed Air System Energy Cost Analyzer"}, sectorSlug: "energy-consumption", category: "energy",
  painStatement: "Basınçlı hava sistemleri fabrika elektrik faturasının %30'una kadar çıkabilir. Kaçaklar ve düşük verim gizli maliyet oluşturur. Bu araç sistem enerji maliyetini ve ısı geri kazanım tasarrufunu hesaplar.", painStatement_i18n: {"en":"Compressed Air systems can account for up to 30% of a factory's electricity bill. Leaks and low Efficiency create latent Cost. This tool calculates System energy cost and heat Recovery savings."},
  inputs: [
    { id: "compressorPowerKw", label: "Kompresör Gücü", label_i18n: {"en":"Compressor Motor power"}, type: "number", unit: "kW", required: true, smartDefault: 75, validation: { min: 0 }, helper: "", expertMeaning: "Compressor motor power", expertMeaning_i18n: {"en":"Compressor Motor power"} },
    { id: "operatingHoursPerYear", label: "Annual operating hours", label_i18n: {"en":"Annual operating hours"}, type: "number", unit: "saat/yıl", required: true, smartDefault: 8000, validation: { min: 0 }, helper: "", expertMeaning: "Annual operating hours", expertMeaning_i18n: {"en":"Annual operating hours"} },
    { id: "loadFactor", label: "Compressor load factor", label_i18n: {"en":"Compressor load factor"}, type: "number", unit: "", required: true, smartDefault: 0.8, validation: { min: 0, max: 1 }, helper: "", expertMeaning: "Compressor load factor", expertMeaning_i18n: {"en":"Compressor load factor"} },
    { id: "efficiencyIsothermal", label: "Isothermal efficiency", label_i18n: {"en":"Isothermal efficiency"}, type: "number", unit: "%", required: true, smartDefault: 70, validation: { min: 1, max: 100 }, helper: "", expertMeaning: "Isothermal efficiency", expertMeaning_i18n: {"en":"Isothermal efficiency"} },
    { id: "efficiencyMotor", label: "Motor Verimi", label_i18n: {"en":"Motor Efficiency"}, type: "number", unit: "%", required: true, smartDefault: 90, validation: { min: 1, max: 100 }, helper: "", expertMeaning: "Electric motor efficiency", expertMeaning_i18n: {"en":"Electric Motor efficiency"} },
    { id: "efficiencyDrive", label: "Tahrik Verimi", label_i18n: {"en":"Tahrik Efficiency"}, type: "number", unit: "%", required: false, smartDefault: 95, validation: { min: 1, max: 100 }, helper: "", expertMeaning: "Drive/belt efficiency", expertMeaning_i18n: {"en":"Drive/belt efficiency"} },
    { id: "electricityRate", label: "Elektrik Tarifesi", label_i18n: {"en":"Elektrik Tarifesi"}, type: "number", unit: "USD/kWh", required: true, smartDefault: 0.12, validation: { min: 0 }, helper: "", expertMeaning: "Electricity unit cost", expertMeaning_i18n: {"en":"Electricity unit cost"} },
    { id: "excessPressureDropKpa", label: "Excess ΔP above design", label_i18n: {"en":"Excess ΔP above design"}, type: "number", unit: "kPa", required: false, smartDefault: 50, validation: { min: 0 }, helper: "", expertMeaning: "Excess ΔP above design", expertMeaning_i18n: {"en":"Excess ΔP above design"} },
    { id: "heatRecoveryEfficiency", label: "Heat recovery efficiency", label_i18n: {"en":"Heat recovery efficiency"}, type: "number", unit: "%", required: false, smartDefault: 50, validation: { min: 0, max: 100 }, helper: "", expertMeaning: "Heat recovery efficiency", expertMeaning_i18n: {"en":"Heat recovery efficiency"} },
    { id: "alternativeEnergyCost", label: "Alternatif Enerji Maliyeti", label_i18n: {"en":"Alternatif energy Cost"}, type: "number", unit: "USD/kWh", required: false, smartDefault: 0.10, validation: { min: 0 }, helper: "", expertMeaning: "Cost of alternative heating", expertMeaning_i18n: {"en":"Cost of alternative heating"} },
    { id: "gridEmissionFactor", label: "Grid carbon intensity", label_i18n: {"en":"Grid carbon intensity"}, type: "number", unit: "kgCO₂/kWh", required: false, smartDefault: 0.45, validation: { min: 0 }, helper: "", expertMeaning: "Grid carbon intensity", expertMeaning_i18n: {"en":"Grid carbon intensity"} },
    { id: "annualEnergyCostInput", label: "Annual electricity cost", label_i18n: {"en":"Annual electricity cost"}, type: "number", unit: "USD/yıl", required: false, smartDefault: 40000, validation: { min: 0 }, helper: "Kompresörün yıllık elektrik maliyeti.", helper_i18n: {"en":"Annual electricity cost of the compressor."}, expertMeaning: "Annual electricity cost", expertMeaning_i18n: {"en":"Annual electricity cost"} },
    { id: "leakageCostInput", label: "Annual leakage cost", label_i18n: {"en":"Annual leakage cost"}, type: "number", unit: "USD/yıl", required: false, smartDefault: 8000, validation: { min: 0 }, helper: "Basınçlı hava kaçaklarının yıllık maliyeti.", helper_i18n: {"en":"Annual cost of compressed air leaks."}, expertMeaning: "Annual leakage cost", expertMeaning_i18n: {"en":"Annual leakage cost"} },
    { id: "heatRecoverySavingsInput", label: "Annual heat recovery savings", label_i18n: {"en":"Annual heat recovery savings"}, type: "number", unit: "USD/yıl", required: false, smartDefault: 3000, validation: { min: 0 }, helper: "Atık ısının geri kazanımından sağlanan tasarruf.", helper_i18n: {"en":"Savings from waste heat recovery."}, expertMeaning: "Annual heat recovery savings", expertMeaning_i18n: {"en":"Annual heat recovery savings"} },
  ],
  outputs: [
    { id: "annualEnergyCost", label: "Annual Energy Cost", label_i18n: {"en":"Annual Energy Cost"}, unit: "USD/yıl", format: "currency" },
    { id: "heatRecoverySavings", label: "Is Geri Kazanm Tasarrufu", label_i18n: {"en":"Is Return Kazanm Tasarrufu"}, unit: "USD/yıl", format: "currency" },
    { id: "totalAnnualCost", label: "Toplam Yllk Maliyet", label_i18n: {"en":"Total Annual Cost"}, unit: "USD/yıl", format: "currency", isBigNumber: true },
    { id: "carbonFootprint", label: "Yllk Karbon Ayak Izi", label_i18n: {"en":"Annual Carbon Ayak Izi"}, unit: "kgCO₂/kWh", format: "number" },
  ],
  thresholds: [
    { fieldId: "totalAnnualCost", warning: 50000, critical: 150000, direction: "higher_is_bad", warningMessage: "Yıllık maliyet > $50K — kaçak taraması önerilir.", warningMessage_i18n: {"en":"Annual Cost > $50K — Leak survey recommended."}, criticalMessage: "Yıllık maliyet > $150K — kompresör yenileme fizibilitesi yapılmalı.", criticalMessage_i18n: {"en":"Annual Cost > $150K — compressor replacement feasibility study should be conducted."} },
  ],
  formulaPipeline: [
    { formulaId: "energy.compressed_air_annual_cost", inputMap: { annualEnergyCost: "annualEnergyCostInput", leakageCost: "leakageCostInput", pressureDropCost: "excessPressureDropKpa", heatRecoverySavings: "heatRecoverySavingsInput" }, outputId: "totalAnnualCost" },
  ],
  reportTemplate: { title: "Compressed Air Energy Cost Report", title_i18n: {"en":"Compressed Air Energy Cost Report"}, sections: ["executive_summary", "loss_breakdown", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.15, volatilityPercent: 15, targetMarginPercent: 20, assumptionNotes: ["Annual energy cost = Power × Hours × Rate × Load factor.", "Heat recovery savings = Power × RecoveryEff × Hours × AltEnergyCost.", "Leakage cost estimated at 20-30% of total energy cost for typical systems.", "Carbon footprint = (Total cost / Electricity rate) × Grid emission factor.", "1 kW saved = 8,760 kWh/year at continuous operation."],assumptionNotes_i18n:[{"en":"Annual energy cost = Power × Hours × Rate × Load factor."},{"en":"Heat recovery savings = Power × RecoveryEff × Hours × AltEnergyCost."},{"en":"Leakage cost estimated at 20-30% of total energy cost for typical systems."},{"en":"Carbon footprint = (Total cost / Electricity rate) × Grid emission factor."},{"en":"1 kW saved = 8,760 kWh/year at continuous operation."}] },
};
