/**
 * Tool #18 — Ciro Maliyeti (Employee Turnover Cost)
 * Separation → Vacancy → Replacement → Training → ProductivityLoss → Total
 */
import type { PremiumCalculatorSchema } from "@/lib/features/premium-schema/premium-calculator-schema";
export const TURNOVER_COST_SCHEMA: PremiumCalculatorSchema = {
  id: "employee-turnover-cost-analyzer", legacyPaidSlug: "employee-turnover-cost-analyzer",
  name: "calisan Ciro (Turnover) Maliyet Analizi", name_i18n: {"en":"calisan Ciro (Turnover) Cost Analizi"}, sectorSlug: "legal-tax", category: "cost",
  painStatement: "Personel ayrılma maliyeti sadece tazminat değil; işe alım, eğitim ve verimlilik kaybını da içerir. Bu araç ayrılan çalışan başına gerçek maliyeti hesaplar.", painStatement_i18n: {"en":"Personel ayrılma Cost sadece compensation değil; işe alım, training ve productivity kaybını da içerir. Bu araç ayrılan Employee Per Actual Cost hesaplar."},
  inputs: [
    { id: "exitsCount", label: "Number of employee exits", label_i18n: {"en":"Number of employee exits"}, type: "number", unit: "kişi", required: true, smartDefault: 10, validation: { min: 1 }, helper: "", expertMeaning: "Number of employee exits", expertMeaning_i18n: {"en":"Number of employee exits"} },
    { id: "severancePay", label: "Total severance compensation", label_i18n: {"en":"Total severance compensation"}, type: "number", unit: "USD", required: true, smartDefault: 25000, validation: { min: 0 }, helper: "", expertMeaning: "Total severance compensation", expertMeaning_i18n: {"en":"Total severance compensation"} },
    { id: "timeToFillDays", label: "Average days to fill position", label_i18n: {"en":"Average days to fill position"}, type: "number", unit: "gün", required: true, smartDefault: 45, validation: { min: 1 }, helper: "", expertMeaning: "Average days to fill position", expertMeaning_i18n: {"en":"Average days to fill position"} },
    { id: "dailyRevenuePerEmployee", label: "Revenue per employee per day", label_i18n: {"en":"Revenue per employee per day"}, type: "number", unit: "USD/gün", required: true, smartDefault: 400, validation: { min: 0 }, helper: "", expertMeaning: "Revenue per employee per day", expertMeaning_i18n: {"en":"Revenue per employee per day"} },
    { id: "advertisingAndAgencyFees", label: "Total recruitment advertising", label_i18n: {"en":"Total recruitment advertising"}, type: "number", unit: "USD", required: true, smartDefault: 3000, validation: { min: 0 }, helper: "", expertMeaning: "Total recruitment advertising", expertMeaning_i18n: {"en":"Total recruitment advertising"} },
    { id: "interviewHours", label: "Mülakat Süresi (Toplam)", label_i18n: {"en":"Manager interview hours per hire"}, type: "number", unit: "saat", required: false, smartDefault: 10, validation: { min: 0 }, helper: "", expertMeaning: "Manager interview hours per hire", expertMeaning_i18n: {"en":"Manager interview hours per hire"} },
    { id: "interviewerRate", label: "Manager hourly rate", label_i18n: {"en":"Manager hourly rate"}, type: "number", unit: "USD/saat", required: false, smartDefault: 60, validation: { min: 0 }, helper: "", expertMeaning: "Manager hourly rate", expertMeaning_i18n: {"en":"Manager hourly rate"} },
    { id: "trainingHours", label: "Total training hours per hire", label_i18n: {"en":"Total training hours per hire"}, type: "number", unit: "saat", required: false, smartDefault: 80, validation: { min: 0 }, helper: "", expertMeaning: "Total training hours per hire", expertMeaning_i18n: {"en":"Total training hours per hire"} },
    { id: "trainerRate", label: "Trainer hourly cost", label_i18n: {"en":"Trainer hourly cost"}, type: "number", unit: "USD/saat", required: false, smartDefault: 50, validation: { min: 0 }, helper: "", expertMeaning: "Trainer hourly cost", expertMeaning_i18n: {"en":"Trainer hourly cost"} },
    { id: "onboardingHours", label: "Oryantasyon Süresi", label_i18n: {"en":"Onboarding hours per hire"}, type: "number", unit: "saat", required: false, smartDefault: 40, validation: { min: 0 }, helper: "", expertMeaning: "Onboarding hours per hire", expertMeaning_i18n: {"en":"Onboarding hours per hire"} },
    { id: "newHireRate", label: "New hire hourly rate during training", label_i18n: {"en":"New hire hourly rate during training"}, type: "number", unit: "USD/saat", required: false, smartDefault: 20, validation: { min: 0 }, helper: "", expertMeaning: "New hire hourly rate during training", expertMeaning_i18n: {"en":"New hire hourly rate during training"} },
    { id: "timeToFullProductivityDays", label: "Days to reach full productivity", label_i18n: {"en":"Days to reach full productivity"}, type: "number", unit: "gün", required: false, smartDefault: 90, validation: { min: 0 }, helper: "", expertMeaning: "Days to reach full productivity", expertMeaning_i18n: {"en":"Days to reach full productivity"} },
    { id: "avgDailyOutput", label: "Average daily output per employee", label_i18n: {"en":"Average daily output per employee"}, type: "number", unit: "birim/gün", required: false, smartDefault: 50, validation: { min: 0 }, helper: "", expertMeaning: "Average daily output per employee", expertMeaning_i18n: {"en":"Average daily output per employee"} },
    { id: "unitMargin", label: "Profit margin per unit", label_i18n: {"en":"Profit margin per unit"}, type: "number", unit: "USD", required: false, smartDefault: 5, validation: { min: 0 }, helper: "", expertMeaning: "Profit margin per unit", expertMeaning_i18n: {"en":"Profit margin per unit"} },
    { id: "separationCostInput", label: "Separation cost per employee", label_i18n: {"en":"Separation cost per employee"}, type: "number", unit: "USD", required: false, smartDefault: 3000, validation: { min: 0 }, helper: "İşten çıkış maliyeti (tazminat + işlem).", helper_i18n: {"en":"İşten çıkış maliyeti (tazminat + işlem)."}, expertMeaning: "Separation cost per employee", expertMeaning_i18n: {"en":"Separation cost per employee"} },
    { id: "vacancyCostInput", label: "Vacancy cost per employee", label_i18n: {"en":"Vacancy cost per employee"}, type: "number", unit: "USD", required: false, smartDefault: 12000, validation: { min: 0 }, helper: "Boş pozisyonun günlük gelir kaybı.", helper_i18n: {"en":"Boş pozisyonun günlük gelir kaybı."}, expertMeaning: "Vacancy cost per employee", expertMeaning_i18n: {"en":"Vacancy cost per employee"} },
    { id: "replacementCostInput", label: "Yenileme Maliyeti", label_i18n: {"en":"replacement Cost"}, type: "number", unit: "USD", required: false, smartDefault: 5000, validation: { min: 0 }, helper: "İlan, mülakat, referans maliyeti.", helper_i18n: {"en":"İlan, mülakat, referans maliyeti."}, expertMeaning: "Replacement hiring cost", expertMeaning_i18n: {"en":"Replacement hiring cost"} },
    { id: "trainingCostInput", label: "Training cost per new hire", label_i18n: {"en":"Training cost per new hire"}, type: "number", unit: "USD", required: false, smartDefault: 4000, validation: { min: 0 }, helper: "Eğitim + oryantasyon maliyeti.", helper_i18n: {"en":"Eğitim + oryantasyon maliyeti."}, expertMeaning: "Training cost per new hire", expertMeaning_i18n: {"en":"Training cost per new hire"} },
    { id: "productivityLossInput", label: "Productivity loss per new hire", label_i18n: {"en":"Productivity loss per new hire"}, type: "number", unit: "USD", required: false, smartDefault: 8000, validation: { min: 0 }, helper: "Tam verime ulaşana kadar kayıp.", helper_i18n: {"en":"Tam verime ulaşana kadar kayıp."}, expertMeaning: "Productivity loss per new hire", expertMeaning_i18n: {"en":"Productivity loss per new hire"} },
  ],
  outputs: [
    { id: "separationCost", label: "Ayrlma Maliyeti", label_i18n: {"en":"Ayrlma Cost"}, unit: "USD", format: "currency" },
    { id: "vacancyCost", label: "Pozisyon Bosluk Maliyeti", label_i18n: {"en":"position Bosluk Cost"}, unit: "USD", format: "currency" },
    { id: "replacementCost", label: "Yenileme Maliyeti", label_i18n: {"en":"replacement Cost"}, unit: "USD", format: "currency" },
    { id: "trainingCost", label: "Egitim Maliyeti", label_i18n: {"en":"training Cost"}, unit: "USD", format: "currency" },
    { id: "productivityLoss", label: "Verimlilik Kayb", label_i18n: {"en":"productivity Loss"}, unit: "USD", format: "currency" },
    { id: "totalTurnoverCost", label: "Toplam Ciro Maliyeti", label_i18n: {"en":"Total Ciro Cost"}, unit: "USD", format: "currency", isBigNumber: true },
  ],
  thresholds: [
    { fieldId: "totalTurnoverCost", warning: 50000, critical: 150000, direction: "higher_is_bad", warningMessage: "Ciro maliyeti > $50K — çalışan bağlılığı programı değerlendirilmeli.", warningMessage_i18n: {"en":"Ciro Cost > $50K — Employee bağlılığı program değerlendirilmeli."}, criticalMessage: "Ciro maliyeti > $150K — acil elde tutma stratejisi gerekiyor.", criticalMessage_i18n: {"en":"Ciro Cost > $150K — urgent elde tutma stratejisi gerekiyor."} },
  ],
  formulaPipeline: [
    { formulaId: "cost.turnover_total", inputMap: { separationCost: "separationCostInput", vacancyCost: "vacancyCostInput", replacementCost: "replacementCostInput", trainingCost: "trainingCostInput", productivityLoss: "productivityLossInput" }, outputId: "totalTurnoverCost" },
  ],
  reportTemplate: { title: "Employee Turnover Cost Report", title_i18n: {"en":"Employee Turnover Cost Report"}, sections: ["executive_summary", "loss_breakdown", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.15, volatilityPercent: 15, targetMarginPercent: 20, assumptionNotes: ["Separation cost = Exit interview + Severance + Admin.", "Vacancy cost = Time to fill × Daily revenue + Temp agency.", "Replacement cost = Ads + Agency + Interview time × Manager rate.", "Training cost = Training hours × Trainer rate + Onboarding × New hire rate.", "Productivity loss = Time to full prod × (1 - Ramp-up curve) × Output × Margin."],assumptionNotes_i18n:[{"en":"Separation cost = Exit interview + Severance + Admin."},{"en":"Vacancy cost = Time to fill × Daily revenue + Temp agency."},{"en":"Replacement cost = Ads + Agency + Interview time × Manager rate."},{"en":"Training cost = Training hours × Trainer rate + Onboarding × New hire rate."},{"en":"Productivity loss = Time to full prod × (1 - Ramp-up curve) × Output × Margin."}] },
};
