/**
 * Tool #18 — Turnover Cost (Employee Turnover Cost)
 * Separation → Vacancy → Replacement → Training → ProductivityLoss → Total
 */
import type { PremiumCalculatorSchema } from "@/lib/features/premium-schema/premium-calculator-schema";
export const TURNOVER_COST_SCHEMA: PremiumCalculatorSchema = {
  id: "employee-turnover-cost-analyzer", legacyPaidSlug: "employee-turnover-cost-analyzer",
  name: "Employee Turnover Cost Analyzer", name_i18n: {"en":"Employee Turnover Cost Analyzer"}, sectorSlug: "legal-tax", category: "cost",
  painStatement: "Employee turnover cost includes not just severance but also recruitment, training, and productivity loss. This tool calculates the actual cost per departing employee.", painStatement_i18n: {"en":"Employee turnover cost includes not just severance but also recruitment, training, and productivity loss. This tool calculates the actual cost per departing employee."},
  inputs: [
    { id: "exitsCount", label: "Number of employee exits", label_i18n: {"en":"Number of employee exits"}, type: "number", unit: "people", required: true, smartDefault: 10, validation: { min: 1 }, helper: "", expertMeaning: "Number of employee exits", expertMeaning_i18n: {"en":"Number of employee exits"} },
    { id: "severancePay", label: "Total severance compensation", label_i18n: {"en":"Total severance compensation"}, type: "number", unit: "USD", required: true, smartDefault: 25000, validation: { min: 0 }, helper: "", expertMeaning: "Total severance compensation", expertMeaning_i18n: {"en":"Total severance compensation"} },
    { id: "timeToFillDays", label: "Average days to fill position", label_i18n: {"en":"Average days to fill position"}, type: "number", unit: "days", required: true, smartDefault: 45, validation: { min: 1 }, helper: "", expertMeaning: "Average days to fill position", expertMeaning_i18n: {"en":"Average days to fill position"} },
    { id: "dailyRevenuePerEmployee", label: "Revenue per employee per day", label_i18n: {"en":"Revenue per employee per day"}, type: "number", unit: "USD/day", required: true, smartDefault: 400, validation: { min: 0 }, helper: "", expertMeaning: "Revenue per employee per day", expertMeaning_i18n: {"en":"Revenue per employee per day"} },
    { id: "advertisingAndAgencyFees", label: "Total recruitment advertising", label_i18n: {"en":"Total recruitment advertising"}, type: "number", unit: "USD", required: true, smartDefault: 3000, validation: { min: 0 }, helper: "", expertMeaning: "Total recruitment advertising", expertMeaning_i18n: {"en":"Total recruitment advertising"} },
    { id: "interviewHours", label: "Manager interview hours per hire", label_i18n: {"en":"Manager interview hours per hire"}, type: "number", unit: "hours", required: false, smartDefault: 10, validation: { min: 0 }, helper: "", expertMeaning: "Manager interview hours per hire", expertMeaning_i18n: {"en":"Manager interview hours per hire"} },
    { id: "interviewerRate", label: "Manager hourly rate", label_i18n: {"en":"Manager hourly rate"}, type: "number", unit: "USD/hour", required: false, smartDefault: 60, validation: { min: 0 }, helper: "", expertMeaning: "Manager hourly rate", expertMeaning_i18n: {"en":"Manager hourly rate"} },
    { id: "trainingHours", label: "Total training hours per hire", label_i18n: {"en":"Total training hours per hire"}, type: "number", unit: "hours", required: false, smartDefault: 80, validation: { min: 0 }, helper: "", expertMeaning: "Total training hours per hire", expertMeaning_i18n: {"en":"Total training hours per hire"} },
    { id: "trainerRate", label: "Trainer hourly cost", label_i18n: {"en":"Trainer hourly cost"}, type: "number", unit: "USD/hour", required: false, smartDefault: 50, validation: { min: 0 }, helper: "", expertMeaning: "Trainer hourly cost", expertMeaning_i18n: {"en":"Trainer hourly cost"} },
    { id: "onboardingHours", label: "Onboarding hours per hire", label_i18n: {"en":"Onboarding hours per hire"}, type: "number", unit: "hours", required: false, smartDefault: 40, validation: { min: 0 }, helper: "", expertMeaning: "Onboarding hours per hire", expertMeaning_i18n: {"en":"Onboarding hours per hire"} },
    { id: "newHireRate", label: "New hire hourly rate during training", label_i18n: {"en":"New hire hourly rate during training"}, type: "number", unit: "USD/hour", required: false, smartDefault: 20, validation: { min: 0 }, helper: "", expertMeaning: "New hire hourly rate during training", expertMeaning_i18n: {"en":"New hire hourly rate during training"} },
    { id: "timeToFullProductivityDays", label: "Days to reach full productivity", label_i18n: {"en":"Days to reach full productivity"}, type: "number", unit: "days", required: false, smartDefault: 90, validation: { min: 0 }, helper: "", expertMeaning: "Days to reach full productivity", expertMeaning_i18n: {"en":"Days to reach full productivity"} },
    { id: "avgDailyOutput", label: "Average daily output per employee", label_i18n: {"en":"Average daily output per employee"}, type: "number", unit: "birim/gun", required: false, smartDefault: 50, validation: { min: 0 }, helper: "", expertMeaning: "Average daily output per employee", expertMeaning_i18n: {"en":"Average daily output per employee"} },
    { id: "unitMargin", label: "Profit margin per unit", label_i18n: {"en":"Profit margin per unit"}, type: "number", unit: "USD", required: false, smartDefault: 5, validation: { min: 0 }, helper: "", expertMeaning: "Profit margin per unit", expertMeaning_i18n: {"en":"Profit margin per unit"} },
    { id: "separationCostInput", label: "Separation cost per employee", label_i18n: {"en":"Separation cost per employee"}, type: "number", unit: "USD", required: false, smartDefault: 3000, validation: { min: 0 }, helper: "Exit cost (severance + processing).", helper_i18n: {"en":"Exit cost (severance + processing)."}, expertMeaning: "Separation cost per employee", expertMeaning_i18n: {"en":"Separation cost per employee"} },
    { id: "vacancyCostInput", label: "Vacancy cost per employee", label_i18n: {"en":"Vacancy cost per employee"}, type: "number", unit: "USD", required: false, smartDefault: 12000, validation: { min: 0 }, helper: "Daily revenue loss of vacant position.", helper_i18n: {"en":"Daily revenue loss of vacant position."}, expertMeaning: "Vacancy cost per employee", expertMeaning_i18n: {"en":"Vacancy cost per employee"} },
    { id: "replacementCostInput", label: "replacement Cost", label_i18n: {"en":"replacement Cost"}, type: "number", unit: "USD", required: false, smartDefault: 5000, validation: { min: 0 }, helper: "Job posting, interview, reference check cost.", helper_i18n: {"en":"Job posting, interview, reference check cost."}, expertMeaning: "Replacement hiring cost", expertMeaning_i18n: {"en":"Replacement hiring cost"} },
    { id: "trainingCostInput", label: "Training cost per new hire", label_i18n: {"en":"Training cost per new hire"}, type: "number", unit: "USD", required: false, smartDefault: 4000, validation: { min: 0 }, helper: "Training + orientation cost.", helper_i18n: {"en":"Training + orientation cost."}, expertMeaning: "Training cost per new hire", expertMeaning_i18n: {"en":"Training cost per new hire"} },
    { id: "productivityLossInput", label: "Productivity loss per new hire", label_i18n: {"en":"Productivity loss per new hire"}, type: "number", unit: "USD", required: false, smartDefault: 8000, validation: { min: 0 }, helper: "Loss until full productivity is reached.", helper_i18n: {"en":"Loss until full productivity is reached."}, expertMeaning: "Productivity loss per new hire", expertMeaning_i18n: {"en":"Productivity loss per new hire"} },
  ],
  outputs: [
    { id: "separationCost", label: "Ayrlma Cost", label_i18n: {"en":"Ayrlma Cost"}, unit: "USD", format: "currency" },
    { id: "vacancyCost", label: "position Bosluk Cost", label_i18n: {"en":"position Bosluk Cost"}, unit: "USD", format: "currency" },
    { id: "replacementCost", label: "replacement Cost", label_i18n: {"en":"replacement Cost"}, unit: "USD", format: "currency" },
    { id: "trainingCost", label: "training Cost", label_i18n: {"en":"training Cost"}, unit: "USD", format: "currency" },
    { id: "productivityLoss", label: "productivity Loss", label_i18n: {"en":"productivity Loss"}, unit: "USD", format: "currency" },
    { id: "totalTurnoverCost", label: "Total Ciro Cost", label_i18n: {"en":"Total Ciro Cost"}, unit: "USD", format: "currency", isBigNumber: true },
  ],
  thresholds: [
    { fieldId: "totalTurnoverCost", warning: 50000, critical: 150000, direction: "higher_is_bad", warningMessage: "Turnover Cost > $50K — employee engagement program should be evaluated.", warningMessage_i18n: {"en":"Turnover Cost > $50K — employee engagement program should be evaluated."}, criticalMessage: "Ciro Cost > $150K — urgent elde tutma stratejisi gerekiyor.", criticalMessage_i18n: {"en":"Ciro Cost > $150K — urgent elde tutma stratejisi gerekiyor."} },
  ],
  formulaPipeline: [
    { formulaId: "cost.turnover_total", inputMap: { separationCost: "separationCostInput", vacancyCost: "vacancyCostInput", replacementCost: "replacementCostInput", trainingCost: "trainingCostInput", productivityLoss: "productivityLossInput" }, outputId: "totalTurnoverCost" },
  ],
  reportTemplate: { title: "Employee Turnover Cost Report", title_i18n: {"en":"Employee Turnover Cost Report"}, sections: ["executive_summary", "loss_breakdown", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.15, volatilityPercent: 15, targetMarginPercent: 20, assumptionNotes: ["Separation cost = Exit interview + Severance + Admin.", "Vacancy cost = Time to fill × Daily revenue + Temp agency.", "Replacement cost = Ads + Agency + Interview time × Manager rate.", "Training cost = Training hours × Trainer rate + Onboarding × New hire rate.", "Productivity loss = Time to full prod × (1 - Ramp-up curve) × Output × Margin."],assumptionNotes_i18n:[{"en":"Separation cost = Exit interview + Severance + Admin."},{"en":"Vacancy cost = Time to fill × Daily revenue + Temp agency."},{"en":"Replacement cost = Ads + Agency + Interview time × Manager rate."},{"en":"Training cost = Training hours × Trainer rate + Onboarding × New hire rate."},{"en":"Productivity loss = Time to full prod × (1 - Ramp-up curve) × Output × Margin."}] },
};
