
import type { PremiumCalculatorSchema } from "@/lib/features/premium-schema/premium-calculator-schema";
export const NOISE_VIBRATION_COST_SCHEMA: PremiumCalculatorSchema = {
  id: "noise-vibration-cost-analyzer", legacyPaidSlug: "noise-vibration-cost-analyzer",
  name: "Noise & Vibration Cost Analyzer", name_i18n: {"en":"Noise & Vibration Cost Analyzer"}, sectorSlug: "quality", category: "cost",
  painStatement: "If the health, productivity, and quality costs of noise and vibration exposure are not calculated, feasibility for improvement investment cannot be established.", painStatement_i18n: {"en":"If the health, productivity, and quality costs of noise and vibration exposure are not calculated, feasibility for improvement investment cannot be established."},
  inputs: [
    { id: "noiseLevelDb", label: "Noise exposure level", label_i18n: {"en":"Noise exposure level"}, type: "number", unit: "dB(A)", required: true, smartDefault: 88, validation: { min: 30, max: 130 }, helper: "", expertMeaning: "Noise exposure level", expertMeaning_i18n: {"en":"Noise exposure level"} },
    { id: "exposureHours", label: "Daily exposure hours", label_i18n: {"en":"Daily exposure hours"}, type: "number", unit: "saat/gun", required: true, smartDefault: 8, validation: { min: 0.5, max: 16 }, helper: "", expertMeaning: "Daily exposure hours", expertMeaning_i18n: {"en":"Daily exposure hours"} },
    { id: "numWorkers", label: "Number of exposed workers", label_i18n: {"en":"Number of exposed workers"}, type: "number", unit: "people", required: true, smartDefault: 15, validation: { min: 1 }, helper: "", expertMeaning: "Number of exposed workers", expertMeaning_i18n: {"en":"Number of exposed workers"} },
    { id: "vibrationRms", label: "Vibration RMS level", label_i18n: {"en":"Vibration RMS level"}, type: "number", unit: "m/s²", required: true, smartDefault: 2.5, validation: { min: 0, max: 50 }, helper: "", expertMeaning: "Vibration RMS level", expertMeaning_i18n: {"en":"Vibration RMS level"} },
    { id: "vibrationDailyHours", label: "Daily vibration exposure hours", label_i18n: {"en":"Daily vibration exposure hours"}, type: "number", unit: "saat/gun", required: false, smartDefault: 4, validation: { min: 0.1, max: 16 }, helper: "", expertMeaning: "Daily vibration exposure hours", expertMeaning_i18n: {"en":"Daily vibration exposure hours"} },
    { id: "avgWorkerSalary", label: "Average annual salary", label_i18n: {"en":"Average annual salary"}, type: "number", unit: "USD/year", required: true, smartDefault: 35000, validation: { min: 1 }, helper: "", expertMeaning: "Average annual salary", expertMeaning_i18n: {"en":"Average annual salary"} },
    { id: "mitigationInvestment", label: "Noise/vibration mitigation cost", label_i18n: {"en":"Noise/vibration mitigation cost"}, type: "number", unit: "USD", required: false, smartDefault: 40000, validation: { min: 0 }, helper: "", expertMeaning: "Noise/vibration mitigation cost", expertMeaning_i18n: {"en":"Noise/vibration mitigation cost"} },
  ],
  outputs: [
    { id: "noiseExposure", label: "Gurultu exposure Skoru", label_i18n: {"en":"Gurultu exposure Skoru"}, unit: "dB(A)×saat", format: "number" },
    { id: "vibrationLevel", label: "Titresim level", label_i18n: {"en":"Titresim level"}, unit: "m/s²", format: "number" },
    { id: "healthCost", label: "Saglk Cost (Gurultu)", label_i18n: {"en":"Saglk Cost (Gurultu)"}, unit: "USD/year", format: "currency" },
    { id: "productivityLoss", label: "productivity Loss", label_i18n: {"en":"productivity Loss"}, unit: "USD/year", format: "currency" },
    { id: "reworkCost", label: "Hata/Revizyon Cost", label_i18n: {"en":"Hata/Revizyon Cost"}, unit: "USD/year", format: "currency" },
    { id: "mitigationRoi", label: "Azaltma ROI", label_i18n: {"en":"Azaltma ROI"}, unit: "%", format: "number", isBigNumber: true },
  ],
  thresholds: [{ fieldId: "mitigationRoi", warning: 50, critical: 20, direction: "lower_is_bad", warningMessage: "ROI < %50 — Investment fizibilitesi riskli.", warningMessage_i18n: {"en":"ROI < %50 — Investment fizibilitesi riskli."}, criticalMessage: "ROI < %20 — reduction investment is not recommended.", criticalMessage_i18n: {"en":"ROI < %20 — reduction investment is not recommended."} }],
  formulaPipeline: [
    { formulaId: "measurement.noise_exposure", inputMap: { noiseLevelDb: "noiseLevelDb", exposureHours: "exposureHours" ,
        noiseLevel: "noiseLevel",
        noiseLimit: "noiseLimit"}, outputId: "noiseExposure" },
    { formulaId: "measurement.vibration_rms", inputMap: { vibrationRms: "vibrationRms", vibrationDailyHours: "vibrationDailyHours" ,
        vibrationLevel: "vibrationLevel",
        exposureTime: "exposureTime"}, outputId: "vibrationLevel" },
    { formulaId: "cost.noise_health_cost", inputMap: { noiseExposure: "noiseExposure", numWorkers: "numWorkers", avgWorkerSalary: "avgWorkerSalary" ,
        affectedWorkers: "affectedWorkers",
        healthCostPerWorker: "healthCostPerWorker"}, outputId: "healthCost" },
    { formulaId: "cost.noise_productivity_loss", inputMap: { noiseLevelDb: "noiseLevelDb", numWorkers: "numWorkers", avgWorkerSalary: "avgWorkerSalary" ,
        noiseExposure: "noiseExposure",
        annualProdValue: "annualProdValue",
        productivityLossPct: "productivityLossPct"}, outputId: "productivityLoss" },
    { formulaId: "cost.noise_rework_cost", inputMap: { noiseLevelDb: "noiseLevelDb", vibrationLevel: "vibrationLevel", avgWorkerSalary: "avgWorkerSalary", numWorkers: "numWorkers" ,
        reworkHours: "reworkHours",
        reworkRate: "reworkRate"}, outputId: "reworkCost" },
    { formulaId: "cost.noise_mitigation_roi", inputMap: {
        healthCost: "healthCost",
        productivityLoss: "productivityLoss",
        reworkCost: "reworkCost",
        mitigationInvestment: "mitigationInvestment"
      ,
        mitigationCost: "mitigationCost"}, outputId: "mitigationRoi" },
  ],
  reportTemplate: { title: "Noise & Vibration Cost Report", title_i18n: {"en":"Noise & Vibration Cost Report"}, sections: ["executive_summary", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.1, volatilityPercent: 10, targetMarginPercent: 15, assumptionNotes: [],assumptionNotes_i18n:[{"en":"Noise above 85 dB(A) poses a health risk."},{"en":"Vibration RMS > 2.5 m/s² hand-arm vibration risk."},{"en":"Health cost = hearing loss + compensation risk."}] },
};
