/**
 * Tool #26 — Ofis Malzemeleri Maliyet
 */
import type { PremiumCalculatorSchema } from "@/lib/features/premium-schema/premium-calculator-schema";
export const OFFICE_SUPPLIES_COST_SCHEMA: PremiumCalculatorSchema = {
  id: "office-supplies-cost-analyzer", legacyPaidSlug: "office-supplies-cost-analyzer",
  name: "Office Supplies Cost Analyzer", name_i18n: {"en":"Office Supplies Cost Analyzer"}, sectorSlug: "financial-planning", category: "cost",
  painStatement: "Ofis malzemelerinde EOQ, taşıma maliyeti ve stok tükenme maliyeti hesaplanmazsa gereksiz stok ve fazla harcama oluşur.", painStatement_i18n: {"en":"Ofis malzemelerinde EOQ, taşıma maliyeti ve stok tükenme maliyeti hesaplanmazsa gereksiz stok ve fazla harcama oluşur."},
  inputs: [
    { id: "monthlyConsumption", label: "Aylık Tüketim Miktarı", label_i18n: {"en":"Monthly consumption quantity"}, type: "number", unit: "adet/ay", required: true, smartDefault: 500, validation: { min: 1 }, helper: "", expertMeaning: "Monthly consumption quantity", expertMeaning_i18n: {"en":"Monthly consumption quantity"} },
    { id: "unitPrice", label: "Birim Fiyat", label_i18n: {"en":"Birim Fiyat"}, type: "number", unit: "USD", required: true, smartDefault: 3.5, validation: { min: 0.01 }, helper: "", expertMeaning: "Unit price", expertMeaning_i18n: {"en":"Unit price"} },
    { id: "orderCost", label: "Sipariş Maliyeti", label_i18n: {"en":"Cost per order"}, type: "number", unit: "USD/sipariş", required: true, smartDefault: 15, validation: { min: 0.01 }, helper: "", expertMeaning: "Cost per order", expertMeaning_i18n: {"en":"Cost per order"} },
    { id: "holdingRate", label: "Taşıma Maliyeti Oranı", label_i18n: {"en":"Annual holding cost rate"}, type: "number", unit: "%/yıl", required: true, smartDefault: 20, validation: { min: 0, max: 100 }, helper: "", expertMeaning: "Annual holding cost rate", expertMeaning_i18n: {"en":"Annual holding cost rate"} },
    { id: "stockoutRate", label: "Stok Tükenme Riski", label_i18n: {"en":"Stockout probability"}, type: "number", unit: "%", required: false, smartDefault: 5, validation: { min: 0, max: 100 }, helper: "", expertMeaning: "Stockout probability", expertMeaning_i18n: {"en":"Stockout probability"} },
    { id: "stockoutCostPerUnit", label: "Stok Tükenme Birim Maliyeti", label_i18n: {"en":"Cost per stockout unit"}, type: "number", unit: "USD", required: false, smartDefault: 10, validation: { min: 0 }, helper: "", expertMeaning: "Cost per stockout unit", expertMeaning_i18n: {"en":"Cost per stockout unit"} },
    { id: "currentOrderQty", label: "Mevcut Sipariş Miktarı", label_i18n: {"en":"Current order quantity"}, type: "number", unit: "adet", required: false, smartDefault: 300, validation: { min: 1 }, helper: "", expertMeaning: "Current order quantity", expertMeaning_i18n: {"en":"Current order quantity"} },
  ],
  outputs: [
    { id: "consumptionRate", label: "Yıllık Tüketim Hızı", label_i18n: {"en":"Yllk Tuketim Hz"}, unit: "adet/yıl", format: "number" },
    { id: "annualCost", label: "Yıllık Ofis Malzeme Maliyeti", label_i18n: {"en":"Yllk Ofis Malzeme Maliyeti"}, unit: "USD/yıl", format: "currency" },
    { id: "carryingCost", label: "Taşıma Maliyeti", label_i18n: {"en":"Tasma Maliyeti"}, unit: "USD/yıl", format: "currency" },
    { id: "stockoutCost", label: "Stok Tükenme Maliyeti", label_i18n: {"en":"Stok Tukenme Maliyeti"}, unit: "USD/yıl", format: "currency" },
    { id: "optimalEoq", label: "Optimum Sipariş Miktarı (EOQ)", label_i18n: {"en":"Optimum Siparis Miktar (EOQ)"}, unit: "adet", format: "number" },
    { id: "wastePct", label: "İsraf Yüzdesi", label_i18n: {"en":"Israf Yuzdesi"}, unit: "%", format: "number" },
    { id: "optimizationSavings", label: "Optimizasyon Tasarrufu", label_i18n: {"en":"Optimizasyon Tasarrufu"}, unit: "USD/yıl", format: "currency" },
  ],
  thresholds: [{ fieldId: "optimizationSavings", warning: 500, critical: 100, direction: "lower_is_bad", warningMessage: "Tasarruf < $500 — mevcut sistem optimize.", warningMessage_i18n: {"en":"Tasarruf < $500 — mevcut sistem optimize."}, criticalMessage: "Tasarruf < $100 — küçük iyileştirme fırsatı.", criticalMessage_i18n: {"en":"Tasarruf < $100 — küçük iyileştirme fırsatı."} }],
  formulaPipeline: [
    { formulaId: "cost.office_consumption_rate", inputMap: { monthlyConsumption: "monthlyConsumption" ,
        annualUsage: "annualUsage"}, outputId: "consumptionRate" },
    { formulaId: "cost.office_annual_cost", inputMap: { consumptionRate: "consumptionRate", unitPrice: "unitPrice" ,
        annualDemand: "annualDemand",
        orderQty: "orderQty",
        orderCost: "orderCost"}, outputId: "annualCost" },
    { formulaId: "cost.office_carrying_cost", inputMap: { currentOrderQty: "currentOrderQty", unitPrice: "unitPrice", holdingRate: "holdingRate" ,
        orderQty: "orderQty",
        holdingCostPerUnit: "holdingCostPerUnit"}, outputId: "carryingCost" },
    { formulaId: "cost.office_stockout_cost", inputMap: { stockoutRate: "stockoutRate", stockoutCostPerUnit: "stockoutCostPerUnit", consumptionRate: "consumptionRate" ,
        stockoutUnits: "stockoutUnits",
        lostMarginPerUnit: "lostMarginPerUnit"}, outputId: "stockoutCost" },
    { formulaId: "cost.office_eoq", inputMap: { consumptionRate: "consumptionRate", orderCost: "orderCost", unitPrice: "unitPrice", holdingRate: "holdingRate" ,
        annualDemand: "annualDemand",
        holdingCostPerUnit: "holdingCostPerUnit"}, outputId: "optimalEoq" },
    { formulaId: "cost.office_waste_pct", inputMap: { currentOrderQty: "currentOrderQty", optimalEoq: "optimalEoq" ,
        wasteUnits: "wasteUnits",
        totalOrdered: "totalOrdered"}, outputId: "wastePct" },
    { formulaId: "cost.office_optimization_savings", inputMap: { currentOrderQty: "currentOrderQty", optimalEoq: "optimalEoq", orderCost: "orderCost", unitPrice: "unitPrice", holdingRate: "holdingRate" ,
        currentTotalCost: "currentTotalCost",
        optimalTotalCost: "optimalTotalCost"}, outputId: "optimizationSavings" },
  ],
  reportTemplate: { title: "Office Supplies Cost Report", title_i18n: {"en":"Office Supplies Cost Report"}, sections: ["executive_summary", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.1, volatilityPercent: 10, targetMarginPercent: 15, assumptionNotes: ["EOQ = √(2×yıllık talep×sipariş maliyeti / taşıma maliyeti).", "Taşıma maliyeti = stok değeri × taşıma oranı.", "Stok tükenme maliyeti = risk × birim maliyet × talep."],assumptionNotes_i18n:[{"en":"EOQ = √(2×yıllık talep×sipariş maliyeti / taşıma maliyeti)."},{"en":"Taşıma maliyeti = stok değeri × taşıma oranı."},{"en":"Stok tükenme maliyeti = risk × birim maliyet × talep."}] },
};
