import type { PremiumCalculatorSchema } from "@/lib/features/premium-schema/premium-calculator-schema";
export const QUALITY_COST_PAF_SCHEMA: PremiumCalculatorSchema = {
  id: "quality-cost-paf-analyzer", legacyPaidSlug: "quality-cost-paf-analyzer",
  name: "Kalite Maliyeti PAF Analizi", name_i18n: {"en":"Quality Cost PAF Analysis"}, sectorSlug: "quality", category: "cost",
  painStatement: "PAF modeli olmadan kalite maliyetleri görünmez; önleme, değerlendirme, iç ve dış başarısızlık maliyetleri kontrol edilemez.", painStatement_i18n: {"en":"Without the PAF model, quality costs remain invisible; prevention, appraisal, internal and external failure costs cannot be controlled."},
  inputs: [
    { id: "training", label: "Eğitim Bütçesi", label_i18n: {"en":"Training Budget"}, type: "number", unit: "USD", required: false, smartDefault: 10000, validation: { min: 0 }, helper: "", expertMeaning: "Quality training cost", expertMeaning_i18n: {"en":"Quality training cost"} },
    { id: "qualityPlanning", label: "Kalite Planlama", label_i18n: {"en":"Quality Planning"}, type: "number", unit: "USD", required: false, smartDefault: 15000, validation: { min: 0 }, helper: "", expertMeaning: "Quality planning cost", expertMeaning_i18n: {"en":"Quality planning cost"} },
    { id: "supplierScore", label: "Tedarikçi Değerlendirme", label_i18n: {"en":"Supplier Evaluation"}, type: "number", unit: "USD", required: false, smartDefault: 8000, validation: { min: 0 }, helper: "", expertMeaning: "Supplier evaluation cost", expertMeaning_i18n: {"en":"Supplier evaluation cost"} },
    { id: "designReview", label: "Tasarım Gözden Geçirme", label_i18n: {"en":"Design Review"}, type: "number", unit: "USD", required: false, smartDefault: 12000, validation: { min: 0 }, helper: "", expertMeaning: "Design review cost", expertMeaning_i18n: {"en":"Design review cost"} },
    { id: "inspection", label: "Muayene Maliyeti", label_i18n: {"en":"Inspection Cost"}, type: "number", unit: "USD", required: false, smartDefault: 20000, validation: { min: 0 }, helper: "", expertMeaning: "Inspection cost", expertMeaning_i18n: {"en":"Inspection cost"} },
    { id: "testing", label: "Test Maliyeti", label_i18n: {"en":"Testing Cost"}, type: "number", unit: "USD", required: false, smartDefault: 15000, validation: { min: 0 }, helper: "", expertMeaning: "Testing cost", expertMeaning_i18n: {"en":"Testing cost"} },
    { id: "calibration", label: "Kalibrasyon", label_i18n: {"en":"Calibration"}, type: "number", unit: "USD", required: false, smartDefault: 5000, validation: { min: 0 }, helper: "", expertMeaning: "Calibration cost", expertMeaning_i18n: {"en":"Calibration cost"} },
    { id: "audit", label: "Denetim", label_i18n: {"en":"Audit"}, type: "number", unit: "USD", required: false, smartDefault: 7000, validation: { min: 0 }, helper: "", expertMeaning: "Audit cost", expertMeaning_i18n: {"en":"Audit cost"} },
    { id: "scrap", label: "Hurda Maliyeti", label_i18n: {"en":"Scrap Cost"}, type: "number", unit: "USD", required: false, smartDefault: 30000, validation: { min: 0 }, helper: "", expertMeaning: "Scrap cost", expertMeaning_i18n: {"en":"Scrap cost"} },
    { id: "rework", label: "Yeniden İşleme", label_i18n: {"en":"Rework"}, type: "number", unit: "USD", required: false, smartDefault: 25000, validation: { min: 0 }, helper: "", expertMeaning: "Rework cost", expertMeaning_i18n: {"en":"Rework cost"} },
    { id: "reinspection", label: "Yeniden Muayene", label_i18n: {"en":"Reinspection"}, type: "number", unit: "USD", required: false, smartDefault: 8000, validation: { min: 0 }, helper: "", expertMeaning: "Reinspection cost", expertMeaning_i18n: {"en":"Reinspection cost"} },
    { id: "downtime", label: "Duruş Maliyeti", label_i18n: {"en":"Downtime Cost"}, type: "number", unit: "USD", required: false, smartDefault: 12000, validation: { min: 0 }, helper: "", expertMeaning: "Downtime cost from quality", expertMeaning_i18n: {"en":"Downtime cost from quality"} },
    { id: "warranty", label: "Garanti Maliyeti", label_i18n: {"en":"Warranty Cost"}, type: "number", unit: "USD", required: false, smartDefault: 40000, validation: { min: 0 }, helper: "", expertMeaning: "Warranty cost", expertMeaning_i18n: {"en":"Warranty cost"} },
    { id: "returns", label: "İade Maliyeti", label_i18n: {"en":"Returns Cost"}, type: "number", unit: "USD", required: false, smartDefault: 15000, validation: { min: 0 }, helper: "", expertMeaning: "Returns cost", expertMeaning_i18n: {"en":"Returns cost"} },
    { id: "recall", label: "Geri Çağırma", label_i18n: {"en":"Recall"}, type: "number", unit: "USD", required: false, smartDefault: 50000, validation: { min: 0 }, helper: "", expertMeaning: "Recall cost", expertMeaning_i18n: {"en":"Recall cost"} },
    { id: "liability", label: "Sorumluluk", label_i18n: {"en":"Liability"}, type: "number", unit: "USD", required: false, smartDefault: 20000, validation: { min: 0 }, helper: "", expertMeaning: "Liability cost", expertMeaning_i18n: {"en":"Liability cost"} },
    { id: "lostSales", label: "Kayıp Satış Tahmini", label_i18n: {"en":"Lost Sales Estimate"}, type: "number", unit: "USD", required: false, smartDefault: 60000, validation: { min: 0 }, helper: "", expertMeaning: "Lost sales estimate", expertMeaning_i18n: {"en":"Lost sales estimate"} },
    { id: "totalRevenue", label: "Toplam Gelir", label_i18n: {"en":"Total Revenue"}, type: "number", unit: "USD", required: true, smartDefault: 2000000, validation: { min: 1 }, helper: "", expertMeaning: "Total revenue for COQ ratio", expertMeaning_i18n: {"en":"Total revenue for COQ ratio"} },
  ],
  outputs: [
    { id: "prevention", label: "Önleme Maliyeti", label_i18n: {"en":"Onleme Maliyeti"}, unit: "USD", format: "currency" },
    { id: "appraisal", label: "Değerlendirme Maliyeti", label_i18n: {"en":"Degerlendirme Maliyeti"}, unit: "USD", format: "currency" },
    { id: "internalFailure", label: "İç Başarısızlık", label_i18n: {"en":"Ic Basarszlk"}, unit: "USD", format: "currency" },
    { id: "externalFailure", label: "Dış Başarısızlık", label_i18n: {"en":"Ds Basarszlk"}, unit: "USD", format: "currency" },
    { id: "totalCoq", label: "Toplam Kalite Maliyeti (COQ)", label_i18n: {"en":"Toplam Kalite Maliyeti (COQ)"}, unit: "USD", format: "currency", isBigNumber: true },
    { id: "coqRatio", label: "COQ / Gelir Oranı", label_i18n: {"en":"COQ / Gelir Oran"}, unit: "%", format: "percentage" },
    { id: "pafRatio", label: "Önleme / COQ Oranı", label_i18n: {"en":"Onleme / COQ Oran"}, unit: "%", format: "percentage" },
  ],
  thresholds: [{ fieldId: "coqRatio", warning: 0.05, critical: 0.15, direction: "higher_is_bad", warningMessage: "COQ > %5 — kalite yönetimi gözden geçirilmeli.", warningMessage_i18n: {"en":"COQ > 5% — quality management should be reviewed."}, criticalMessage: "COQ > %15 — acil kalite iyileştirme programı başlatılmalı.", criticalMessage_i18n: {"en":"COQ > 15% — initiate urgent quality improvement program."} }],
  formulaPipeline: [
    { formulaId: "cost.paf_prevention", inputMap: {
        training: "training",
        qualityPlanning: "qualityPlanning",
        designReview: "designReview",
        supplierScore: "supplierScore"
      }, outputId: "prevention" },
    { formulaId: "cost.paf_appraisal", inputMap: { inspection: "inspection", testing: "testing", calibration: "calibration", audit: "audit" }, outputId: "appraisal" },
    { formulaId: "cost.paf_internal_failure", inputMap: { scrap: "scrap", rework: "rework", reinspection: "reinspection", downtime: "downtime" }, outputId: "internalFailure" },
    { formulaId: "cost.paf_external_failure", inputMap: { warranty: "warranty", returns: "returns", recall: "recall", liability: "liability", lostSales: "lostSales" }, outputId: "externalFailure" },
    { formulaId: "cost.paf_total", inputMap: { prevention: "prevention", appraisal: "appraisal", internalFailure: "internalFailure", externalFailure: "externalFailure" }, outputId: "totalCoq" },
    { formulaId: "cost.paf_ratio", inputMap: { totalCoq: "totalCoq", totalRevenue: "totalRevenue" }, outputId: "coqRatio" },
    { formulaId: "cost.paf_p_ratio", inputMap: { prevention: "prevention", totalCoq: "totalCoq" }, outputId: "pafRatio" },
  ],
  reportTemplate: { title: "Kalite Maliyeti PAF Raporu", title_i18n: {"en":"Quality Cost PAF Report"}, sections: ["executive_summary", "loss_breakdown", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.15, volatilityPercent: 10, targetMarginPercent: 20, assumptionNotes: ["PAF = Prevention + Appraisal + Internal + External.", "COQ oranı > %15 kritik eşik.", "Önleme maliyeti arttıkça toplam COQ düşer (1:10 kuralı)."],assumptionNotes_i18n:[{"en":"PAF = Prevention + Appraisal + Internal + External."},{"en":"COQ ratio > 15% critical threshold."},{"en":"As prevention cost increases, total COQ decreases (1:10 rule)."}]},
};
