
import type { PremiumCalculatorSchema } from "@/lib/features/premium-schema/premium-calculator-schema";
export const RESTAURANT_MENU_MARGIN_LEAK_SCHEMA: PremiumCalculatorSchema = {
  id: "restaurant-menu-margin-leak-analyzer", legacyPaidSlug: "restaurant-menu-margin-leak-analyzer",
  name: "Restaurant Menu Margin Leak Analysis", name_i18n: {"en":"Restaurant Menu Margin Leak Analysis"}, sectorSlug: "food", category: "cost",
  painStatement: "If the gap between theoretical and actual margins is not tracked, waste, theft, and incorrect portioning silently destroy profit.", painStatement_i18n: {"en":"If the gap between theoretical and actual margins is not tracked, waste, theft, and incorrect portioning silently destroy profit."},
  inputs: [
    { id: "theoreticalFoodCost", label: "Teorik Yiyecek Cost", label_i18n: {"en":"Teorik Yiyecek Cost"}, type: "number", unit: "USD", required: true, smartDefault: 15000, validation: { min: 0 }, helper: "", expertMeaning: "Theoretical (ideal) food cost", expertMeaning_i18n: {"en":"Theoretical (ideal) food cost"} },
    { id: "actualFoodCost", label: "Actual food cost from P&L", label_i18n: {"en":"Actual food cost from P&L"}, type: "number", unit: "USD", required: true, smartDefault: 18500, validation: { min: 0 }, helper: "", expertMeaning: "Actual food cost from P&L", expertMeaning_i18n: {"en":"Actual food cost from P&L"} },
    { id: "revenue", label: "Revenue", label_i18n: {"en":"Revenue"}, type: "number", unit: "USD", required: true, smartDefault: 55000, validation: { min: 1 }, helper: "", expertMeaning: "Total food revenue", expertMeaning_i18n: {"en":"Total food revenue"} },
    { id: "wasteAmount", label: "Estimated Waste", label_i18n: {"en":"Estimated Waste"}, type: "number", unit: "USD", required: false, smartDefault: 1200, validation: { min: 0 }, helper: "", expertMeaning: "Estimated waste cost", expertMeaning_i18n: {"en":"Estimated waste cost"} },
    { id: "theftLoss", label: "Estimated theft or unauthorized use", label_i18n: {"en":"Estimated theft or unauthorized use"}, type: "number", unit: "USD", required: false, smartDefault: 800, validation: { min: 0 }, helper: "", expertMeaning: "Estimated theft or unauthorized use", expertMeaning_i18n: {"en":"Estimated theft or unauthorized use"} },
  ],
  outputs: [
    { id: "restaurantTheoreticalFood", label: "Teorik Yiyecek Cost", label_i18n: {"en":"Teorik Yiyecek Cost"}, unit: "USD", format: "currency" },
    { id: "restaurantActualFood", label: "Actual Yiyecek Cost", label_i18n: {"en":"Actual Yiyecek Cost"}, unit: "USD", format: "currency" },
    { id: "restaurantVariance", label: "Mutfak Sapmas", label_i18n: {"en":"Mutfak Sapmas"}, unit: "USD", format: "currency" },
    { id: "restaurantVariancePct", label: "Deviation Rate", label_i18n: {"en":"Deviation Rate"}, unit: "%", format: "number" },
    { id: "restaurantWasteCost", label: "Waste Cost", label_i18n: {"en":"Waste Cost"}, unit: "USD", format: "currency" },
    { id: "restaurantTheftLoss", label: "Shrinkage Cost", label_i18n: {"en":"Shrinkage Cost"}, unit: "USD", format: "currency" },
    { id: "restaurantIdealMargin", label: "Ideal Margin", label_i18n: {"en":"Ideal Margin"}, unit: "%", format: "number" },
    { id: "restaurantActualMargin", label: "Actual Margin", label_i18n: {"en":"Actual Margin"}, unit: "%", format: "number" },
  ],
  thresholds: [{ fieldId: "restaurantVariancePct", warning: 5, critical: 10, direction: "higher_is_bad", warningMessage: "Variance > 5% - increase portion and waste control.", warningMessage_i18n: {"en":"Variance > 5% - increase portion and waste control."}, criticalMessage: "Variance > 10% - kitchen operations must be urgently audited.", criticalMessage_i18n: {"en":"Variance > 10% - kitchen operations must be urgently audited."} }],
  formulaPipeline: [
    { formulaId: "cost.restaurant_theoretical_food", inputMap: { theoreticalFoodCost: "theoreticalFoodCost" ,
        totalSales: "totalSales",
        idealFoodCostPct: "idealFoodCostPct"}, outputId: "restaurantTheoreticalFood" },
    { formulaId: "cost.restaurant_actual_food", inputMap: { actualFoodCost: "actualFoodCost" ,
        beginningInv: "beginningInv",
        purchases: "purchases",
        endingInv: "endingInv"}, outputId: "restaurantActualFood" },
    { formulaId: "cost.restaurant_variance_cost", inputMap: { restaurantActualFood: "restaurantActualFood", theoreticalFoodCost: "theoreticalFoodCost" ,
        expectedFoodCost: "expectedFoodCost",
        actualFoodCost: "actualFoodCost",
        mealsServed: "mealsServed"}, outputId: "restaurantVariance" },
    { formulaId: "measurement.restaurant_variance_pct", inputMap: { restaurantVariance: "restaurantVariance", theoreticalFoodCost: "theoreticalFoodCost" ,
        varianceCost: "varianceCost",
        actualFoodCost: "actualFoodCost"}, outputId: "restaurantVariancePct" },
    { formulaId: "cost.restaurant_waste_cost", inputMap: { wasteAmount: "wasteAmount" ,
        wasteKg: "wasteKg",
        avgCostPerKg: "avgCostPerKg"}, outputId: "restaurantWasteCost" },
    { formulaId: "cost.restaurant_theft_loss", inputMap: { theftLoss: "theftLoss" ,
        theftQty: "theftQty",
        avgCostPerUnit: "avgCostPerUnit"}, outputId: "restaurantTheftLoss" },
    { formulaId: "measurement.restaurant_ideal_margin", inputMap: { revenue: "revenue", theoreticalFoodCost: "theoreticalFoodCost" ,
        idealFoodCostPct: "idealFoodCostPct"}, outputId: "restaurantIdealMargin" },
    { formulaId: "measurement.restaurant_actual_margin", inputMap: { revenue: "revenue", restaurantActualFood: "restaurantActualFood" ,
        actualFoodCost: "actualFoodCost",
        totalSales: "totalSales"}, outputId: "restaurantActualMargin" },
  ],
  reportTemplate: { title: "Restaurant Menu Margin Leak Report", title_i18n: {"en":"Restaurant Menu Margin Leak Report"}, sections: ["executive_summary", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.0, volatilityPercent: 10, targetMarginPercent: 20, assumptionNotes: ["Variance = actual − theoretical.", "Sapma % = sapma / teorik × 100.", "Ideal margin = (revenue − theoretical) / revenue × 100.", "Actual margin = (revenue − actual) / revenue × 100."],assumptionNotes_i18n:[{"en":"Variance = actual − theoretical."},{"en":"Variance % = variance / theoretical × 100."},{"en":"Ideal margin = (revenue − theoretical) / revenue × 100."},{"en":"Actual margin = (revenue − actual) / revenue × 100."}] },
};
