
import type { PremiumCalculatorSchema } from "@/lib/features/premium-schema/premium-calculator-schema";
export const ROBOT_VS_MANUAL_ANALYZER_SCHEMA: PremiumCalculatorSchema = {
  id: "robot-vs-manual-analyzer", legacyPaidSlug: "robot-vs-manual-analyzer",
  name: "Robot vs Manual Operation Cost", name_i18n: {"en":"Robot vs Manual Operation Cost"}, sectorSlug: "cnc-manufacturing", category: "cost",
  painStatement: "Without calculating the true cost advantage of automation over manual operation, a wrong decision can multiply production costs.", painStatement_i18n: {"en":"Without calculating the true cost advantage of automation over manual operation, a wrong decision can multiply production costs."},
  inputs: [
    { id: "manualLaborCost", label: "Annual Labor Cost", label_i18n: {"en":"Annual Labor Cost"}, type: "number", unit: "USD/year", required: true, smartDefault: 55000, validation: { min: 1 }, helper: "", expertMeaning: "Annual labor cost per worker", expertMeaning_i18n: {"en":"Annual labor cost per worker"} },
    { id: "numWorkers", label: "Worker Count", label_i18n: {"en":"Worker Count"}, type: "number", unit: "people", required: true, smartDefault: 3, validation: { min: 1 }, helper: "", expertMeaning: "Number of workers", expertMeaning_i18n: {"en":"Number of workers"} },
    { id: "robotInvestment", label: "Robot Investment", label_i18n: {"en":"Robot Investment"}, type: "number", unit: "USD", required: true, smartDefault: 120000, validation: { min: 1 }, helper: "", expertMeaning: "Total robot system investment", expertMeaning_i18n: {"en":"Total robot system investment"} },
    { id: "robotMaintenance", label: "Annual Maintenance Cost", label_i18n: {"en":"Annual Maintenance Cost"}, type: "number", unit: "USD/year", required: true, smartDefault: 8000, validation: { min: 0 }, helper: "", expertMeaning: "Annual robot maintenance cost", expertMeaning_i18n: {"en":"Annual robot maintenance cost"} },
    { id: "robotEnergy", label: "Annual Energy Cost", label_i18n: {"en":"Annual Energy Cost"}, type: "number", unit: "USD/year", required: true, smartDefault: 5000, validation: { min: 0 }, helper: "", expertMeaning: "Annual energy cost for robot", expertMeaning_i18n: {"en":"Annual energy cost for robot"} },
    { id: "robotLife", label: "Robot Life", label_i18n: {"en":"Robot Life"}, type: "number", unit: "years", required: true, smartDefault: 10, validation: { min: 1 }, helper: "", expertMeaning: "Expected robot useful life", expertMeaning_i18n: {"en":"Expected robot useful life"} },
    { id: "manualOutput", label: "Manual Output", label_i18n: {"en":"Manual Output"}, type: "number", unit: "units/year", required: true, smartDefault: 80000, validation: { min: 1 }, helper: "", expertMeaning: "Manual annual output per worker", expertMeaning_i18n: {"en":"Manual annual output per worker"} },
    { id: "robotOutput", label: "Robot Output", label_i18n: {"en":"Robot Output"}, type: "number", unit: "units/year", required: false, smartDefault: 120000, validation: { min: 1 }, helper: "", expertMeaning: "Robot annual output", expertMeaning_i18n: {"en":"Robot annual output"} },
  ],
  outputs: [
    { id: "manualCostAnnual", label: "Annual Manual Cost", label_i18n: {"en":"Annual Manual Cost"}, unit: "USD/year", format: "currency", isBigNumber: true },
    { id: "robotCostAnnual", label: "Annual Robot Cost", label_i18n: {"en":"Annual Robot Cost"}, unit: "USD/year", format: "currency", isBigNumber: true },
    { id: "robotOutput", label: "Robot Annual Output", label_i18n: {"en":"Robot Annual Output"}, unit: "units/year", format: "number", isBigNumber: true },
    { id: "manualOutput", label: "Manual Annual Output", label_i18n: {"en":"Manual Annual Output"}, unit: "units/year", format: "number", isBigNumber: true },
    { id: "costPerUnitManual", label: "Unit Cost — Manual", label_i18n: {"en":"Unit Cost — Manual"}, unit: "USD/unit", format: "currency" },
    { id: "costPerUnitRobot", label: "Unit Cost — Robot", label_i18n: {"en":"Unit Cost — Robot"}, unit: "USD/unit", format: "currency" },
    { id: "robotRoi", label: "Robot Investment Return", label_i18n: {"en":"Robot Investment Return"}, unit: "%", format: "number" },
    { id: "robotPayback", label: "Robot Payback Period", label_i18n: {"en":"Robot Payback Period"}, unit: "years", format: "number" },
  ],
  thresholds: [{ fieldId: "costPerUnitRobot", warning: 0.5, critical: 0.8, direction: "higher_is_bad", warningMessage: "Robot unit cost > $0.50 — evaluate efficiency.", warningMessage_i18n: {"en":"Robot unit cost > $0.50 — evaluate efficiency."}, criticalMessage: "Robot unit cost > $0.80 — question feasibility.", criticalMessage_i18n: {"en":"Robot unit cost > $0.80 — question feasibility."} }],
  formulaPipeline: [
    { formulaId: "cost.manual_cost_annual", inputMap: { manualLaborCost: "manualLaborCost", numWorkers: "numWorkers" }, outputId: "manualCostAnnual" },
    { formulaId: "cost.robot_cost_annual", inputMap: { robotInvestment: "robotInvestment", robotMaintenance: "robotMaintenance", robotEnergy: "robotEnergy", robotLife: "robotLife" }, outputId: "robotCostAnnual" },
    { formulaId: "measurement.robot_output", inputMap: { robotOutput: "robotOutput" }, outputId: "robotOutput" },
    { formulaId: "measurement.manual_output", inputMap: { manualOutput: "manualOutput", numWorkers: "numWorkers" }, outputId: "manualOutput" },
    { formulaId: "cost.cost_per_unit_manual", inputMap: { manualCostAnnual: "manualCostAnnual", manualOutput: "manualOutput" }, outputId: "costPerUnitManual" },
    { formulaId: "cost.cost_per_unit_robot", inputMap: { robotCostAnnual: "robotCostAnnual", robotOutput: "robotOutput" }, outputId: "costPerUnitRobot" },
    { formulaId: "cost.robot_roi", inputMap: { manualCostAnnual: "manualCostAnnual", robotCostAnnual: "robotCostAnnual", robotInvestment: "robotInvestment" }, outputId: "robotRoi" },
    { formulaId: "cost.robot_payback", inputMap: { robotInvestment: "robotInvestment", manualCostAnnual: "manualCostAnnual", robotCostAnnual: "robotCostAnnual" }, outputId: "robotPayback" },
  ],
  reportTemplate: { title: "Robot vs Manual Analysis Report", title_i18n: {"en":"Robot vs Manual Analysis Report"}, sections: ["executive_summary", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.0, volatilityPercent: 10, targetMarginPercent: 15, assumptionNotes: [],assumptionNotes_i18n:[{"en":"Manual cost = number of workers × annual cost."},{"en":"Robot cost = maintenance + energy + (investment / lifespan)."},{"en":"Unit cost = annual cost / annual output."},{"en":"ROI = (manual - robot) / investment × 100."}] },
};
