/**
 * Tool #41 — Rota Maliyet Analizi
 */
import type { PremiumCalculatorSchema } from "@/lib/features/premium-schema/premium-calculator-schema";
export const ROUTE_COST_ANALYZER_SCHEMA: PremiumCalculatorSchema = {
  id: "route-cost-analyzer", legacyPaidSlug: "route-cost-analyzer",
  name: "Rota Maliyet Analizi", name_i18n: {"en":"Route Cost Analysis","tr":"Rota Maliyet Analizi"}, sectorSlug: "logistics-transport", category: "route",
  painStatement: "Rota maliyeti km, zaman, geçiş ücreti ve genel gider bazında hesaplanmazsa nakliye fiyatlaması zarar edebilir.", painStatement_i18n: {"en":"If route cost is not calculated based on distance, time, tolls, and overhead, transportation pricing may result in losses.","tr":"Rota maliyeti km, zaman, geçiş ücreti ve genel gider bazında hesaplanmazsa nakliye fiyatlaması zarar edebilir."},
  inputs: [
    { id: "distance", label: "Mesafe", label_i18n: {"en":"Distance","tr":"Mesafe"}, type: "number", unit: "km", required: true, smartDefault: 350, validation: { min: 0.1 }, helper: "", expertMeaning: "Route distance in km", expertMeaning_i18n: {"en":"Route distance in km","tr":"Km cinsinden rota mesafesi"} },
    { id: "fuelCostPerKm", label: "Yakıt Maliyeti", label_i18n: {"en":"Fuel Cost","tr":"Yakıt Maliyeti"}, type: "number", unit: "USD/km", required: true, smartDefault: 0.35, validation: { min: 0.01 }, helper: "", expertMeaning: "Fuel cost per km", expertMeaning_i18n: {"en":"Fuel cost per km","tr":"Km başına yakıt maliyeti"} },
    { id: "driverWagePerHour", label: "Sürücü Saat Ücreti", label_i18n: {"en":"Driver Hourly Wage","tr":"Sürücü Saat Ücreti"}, type: "number", unit: "USD/saat", required: true, smartDefault: 18, validation: { min: 1 }, helper: "", expertMeaning: "Driver hourly wage", expertMeaning_i18n: {"en":"Driver hourly wage","tr":"Sürücü saatlik ücreti"} },
    { id: "avgSpeed", label: "Ortalama Hız", label_i18n: {"en":"Average Speed","tr":"Ortalama Hız"}, type: "number", unit: "km/saat", required: true, smartDefault: 70, validation: { min: 1 }, helper: "", expertMeaning: "Average travel speed", expertMeaning_i18n: {"en":"Average travel speed","tr":"Ortalama seyahat hızı"} },
    { id: "numberOfDrops", label: "Teslimat Sayısı", label_i18n: {"en":"Number of Deliveries","tr":"Teslimat Sayısı"}, type: "number", unit: "durak", required: true, smartDefault: 8, validation: { min: 1 }, helper: "", expertMeaning: "Number of drops per route", expertMeaning_i18n: {"en":"Number of drops per route","tr":"Rota başına teslimat sayısı"} },
    { id: "tollCost", label: "Köprü / Geçiş Ücreti", label_i18n: {"en":"Bridge / Toll Cost","tr":"Köprü / Geçiş Ücreti"}, type: "number", unit: "USD", required: false, smartDefault: 25, validation: { min: 0 }, helper: "", expertMeaning: "Toll and bridge costs", expertMeaning_i18n: {"en":"Toll and bridge costs","tr":"Köprü ve geçiş ücretleri"} },
    { id: "maintenancePerKm", label: "Bakım Maliyeti", label_i18n: {"en":"Maintenance Cost","tr":"Bakım Maliyeti"}, type: "number", unit: "USD/km", required: false, smartDefault: 0.12, validation: { min: 0 }, helper: "", expertMeaning: "Maintenance cost per km", expertMeaning_i18n: {"en":"Maintenance cost per km","tr":"Km başına bakım maliyeti"} },
    { id: "overheadPercent", label: "Genel Gider Oranı", label_i18n: {"en":"Overhead Rate","tr":"Genel Gider Oranı"}, type: "number", unit: "%", required: false, smartDefault: 15, validation: { min: 0, max: 50 }, helper: "", expertMeaning: "Overhead allocation percentage", expertMeaning_i18n: {"en":"Overhead allocation percentage","tr":"Genel gider dağıtım yüzdesi"} },
  ],
  outputs: [
    { id: "routeDistanceCost", label: "Mesafe Maliyeti", label_i18n: {"en":"Distance Cost","tr":"Mesafe Maliyeti"}, unit: "USD", format: "currency" },
    { id: "routeTimeCost", label: "Zaman Maliyeti", label_i18n: {"en":"Time Cost","tr":"Zaman Maliyeti"}, unit: "USD", format: "currency" },
    { id: "routeTollCost", label: "Geçiş Ücreti", label_i18n: {"en":"Toll Cost","tr":"Geçiş Ücreti"}, unit: "USD", format: "currency" },
    { id: "routeMaintenanceCost", label: "Bakım Maliyeti", label_i18n: {"en":"Maintenance Cost","tr":"Bakım Maliyeti"}, unit: "USD", format: "currency" },
    { id: "routeOverhead", label: "Genel Gider", label_i18n: {"en":"Overhead","tr":"Genel Gider"}, unit: "USD", format: "currency" },
    { id: "routeTotalCost", label: "Toplam Rota Maliyeti", label_i18n: {"en":"Total Route Cost","tr":"Toplam Rota Maliyeti"}, unit: "USD", format: "currency" },
    { id: "routeCostPerKm", label: "Km Başına Maliyet", label_i18n: {"en":"Cost per Km","tr":"Km Başına Maliyet"}, unit: "USD/km", format: "currency" },
    { id: "routeCostPerDrop", label: "Teslimat Başına Maliyet", label_i18n: {"en":"Cost per Delivery","tr":"Teslimat Başına Maliyet"}, unit: "USD/durak", format: "currency" },
  ],
  thresholds: [{ fieldId: "routeCostPerKm", warning: 1.5, critical: 2.0, direction: "higher_is_bad", warningMessage: "Km maliyet > $1.50 — rota optimizasyonu önerilir.", warningMessage_i18n: {"en":"Cost per km > $1.50 — route optimization recommended.","tr":"Km maliyet > $1.50 — rota optimizasyonu önerilir."}, criticalMessage: "Km maliyet > $2.00 — rota kârlılığı risk altında.", criticalMessage_i18n: {"en":"Cost per km > $2.00 — route profitability at risk.","tr":"Km maliyet > $2.00 — rota kârlılığı risk altında."} }],
  formulaPipeline: [
    { formulaId: "cost.route_distance_cost", inputMap: { distance: "distance", fuelCostPerKm: "fuelCostPerKm" ,
        distanceKm: "distanceKm",
        costPerKm: "costPerKm"}, outputId: "routeDistanceCost" },
    { formulaId: "cost.route_time_cost", inputMap: { distance: "distance", avgSpeed: "avgSpeed", driverWagePerHour: "driverWagePerHour" ,
        timeHours: "timeHours",
        costPerHour: "costPerHour"}, outputId: "routeTimeCost" },
    { formulaId: "cost.route_toll_cost", inputMap: { tollCost: "tollCost" ,
        tollAmount: "tollAmount",
        tollCount: "tollCount",
        tollPerPass: "tollPerPass"}, outputId: "routeTollCost" },
    { formulaId: "cost.route_maintenance_cost", inputMap: { distance: "distance", maintenancePerKm: "maintenancePerKm" ,
        distanceKm: "distanceKm",
        maintenanceRate: "maintenanceRate"}, outputId: "routeMaintenanceCost" },
    { formulaId: "cost.route_overhead", inputMap: { distance: "distance", fuelCostPerKm: "fuelCostPerKm", driverWagePerHour: "driverWagePerHour", avgSpeed: "avgSpeed", tollCost: "tollCost", maintenancePerKm: "maintenancePerKm", overheadPercent: "overheadPercent" ,
        routeDistance: "routeDistance",
        overheadPerKm: "overheadPerKm"}, outputId: "routeOverhead" },
    { formulaId: "cost.route_total_cost", inputMap: { routeDistanceCost: "routeDistanceCost", routeTimeCost: "routeTimeCost", routeTollCost: "routeTollCost", routeMaintenanceCost: "routeMaintenanceCost", routeOverhead: "routeOverhead" ,
        routeFuelCost: "routeFuelCost",
        routeLaborCost: "routeLaborCost"}, outputId: "routeTotalCost" },
    { formulaId: "measurement.route_cost_per_km", inputMap: { routeTotalCost: "routeTotalCost", distance: "distance" ,
        distanceKm: "distanceKm"}, outputId: "routeCostPerKm" },
    { formulaId: "measurement.route_cost_per_drop", inputMap: { routeTotalCost: "routeTotalCost", numberOfDrops: "numberOfDrops" ,
        totalDrops: "totalDrops"}, outputId: "routeCostPerDrop" },
  ],
  reportTemplate: { title: "Route Cost Analysis Report", title_i18n: {"en":"Route Cost Analysis Report","tr":"Rota Maliyet Analizi Raporu"}, sections: ["executive_summary", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.0, volatilityPercent: 10, targetMarginPercent: 15, assumptionNotes: ["Mesafe maliyeti = km × yakıt birim maliyet.", "Zaman maliyeti = (km/hız) × saat ücret.", "Genel gider = doğrudan maliyetler × oran.", "Km maliyet = toplam / km, drop maliyet = toplam / durak."],assumptionNotes_i18n:[{"en":"Distance cost = km × fuel unit cost.","tr":"Mesafe maliyeti = km × yakıt birim maliyet."},{"en":"Time cost = (km/speed) × hourly wage.","tr":"Zaman maliyeti = (km/hız) × saat ücret."},{"en":"Overhead = direct costs × rate.","tr":"Genel gider = doğrudan maliyetler × oran."},{"en":"Cost per km = total / km, cost per drop = total / stops.","tr":"Km maliyet = toplam / km, drop maliyet = toplam / durak."}] },
};
