/**
 * Tool #41 — Rota Maliyet Analizi
 */
import type { PremiumCalculatorSchema } from "@/lib/features/premium-schema/premium-calculator-schema";
export const ROUTE_COST_ANALYZER_SCHEMA: PremiumCalculatorSchema = {
  id: "route-cost-analyzer", legacyPaidSlug: "route-cost-analyzer",
  name: "Rota Maliyet Analizi", name_i18n: {"en":"Route Cost Analysis"}, sectorSlug: "logistics-transport", category: "route",
  painStatement: "If route cost is not calculated based on distance, time, tolls, and overhead, transportation pricing may result in losses.", painStatement_i18n: {"en":"If route cost is not calculated based pre distance, time, tolls, and overhead, transportation pricing may result in losses."},
  inputs: [
    { id: "distance", label: "Mesafe", label_i18n: {"en":"Distance"}, type: "number", unit: "km", required: true, smartDefault: 350, validation: { min: 0.1 }, helper: "", expertMeaning: "Route distance in km", expertMeaning_i18n: {"en":"Route distance in km"} },
    { id: "fuelCostPerKm", label: "Fuel Cost", label_i18n: {"en":"Fuel Cost"}, type: "number", unit: "USD/km", required: true, smartDefault: 0.35, validation: { min: 0.01 }, helper: "", expertMeaning: "Fuel cost per km", expertMeaning_i18n: {"en":"Fuel cost per km"} },
    { id: "driverWagePerHour", label: "Surucu Saat Ucreti", label_i18n: {"en":"Driver Hourly Wage"}, type: "number", unit: "USD/saat", required: true, smartDefault: 18, validation: { min: 1 }, helper: "", expertMeaning: "Driver hourly wage", expertMeaning_i18n: {"en":"Driver hourly wage"} },
    { id: "avgSpeed", label: "Average Speed", label_i18n: {"en":"Average Speed"}, type: "number", unit: "km/saat", required: true, smartDefault: 70, validation: { min: 1 }, helper: "", expertMeaning: "Average travel speed", expertMeaning_i18n: {"en":"Average travel speed"} },
    { id: "numberOfDrops", label: "Number of Deliveries", label_i18n: {"en":"Number of Deliveries"}, type: "number", unit: "durak", required: true, smartDefault: 8, validation: { min: 1 }, helper: "", expertMeaning: "Number of drops per route", expertMeaning_i18n: {"en":"Number of drops per route"} },
    { id: "tollCost", label: "Bridge / Toll Cost", label_i18n: {"en":"Bridge / Toll Cost"}, type: "number", unit: "USD", required: false, smartDefault: 25, validation: { min: 0 }, helper: "", expertMeaning: "Toll and bridge costs", expertMeaning_i18n: {"en":"Toll and bridge costs"} },
    { id: "maintenancePerKm", label: "Maintenance Cost", label_i18n: {"en":"Maintenance Cost"}, type: "number", unit: "USD/km", required: false, smartDefault: 0.12, validation: { min: 0 }, helper: "", expertMeaning: "Maintenance cost per km", expertMeaning_i18n: {"en":"Maintenance cost per km"} },
    { id: "overheadPercent", label: "Overhead Rate", label_i18n: {"en":"Overhead Rate"}, type: "number", unit: "%", required: false, smartDefault: 15, validation: { min: 0, max: 50 }, helper: "", expertMeaning: "Overhead allocation percentage", expertMeaning_i18n: {"en":"Overhead allocation percentage"} },
  ],
  outputs: [
    { id: "routeDistanceCost", label: "Mesafe Maliyeti", label_i18n: {"en":"Distance Cost"}, unit: "USD", format: "currency" },
    { id: "routeTimeCost", label: "Zaman Maliyeti", label_i18n: {"en":"Time Cost"}, unit: "USD", format: "currency" },
    { id: "routeTollCost", label: "Toll Cost", label_i18n: {"en":"Toll Cost"}, unit: "USD", format: "currency" },
    { id: "routeMaintenanceCost", label: "Maintenance Cost", label_i18n: {"en":"Maintenance Cost"}, unit: "USD", format: "currency" },
    { id: "routeOverhead", label: "Genel Gider", label_i18n: {"en":"Overhead"}, unit: "USD", format: "currency" },
    { id: "routeTotalCost", label: "Toplam Rota Maliyeti", label_i18n: {"en":"Total Route Cost"}, unit: "USD", format: "currency" },
    { id: "routeCostPerKm", label: "Cost per Km", label_i18n: {"en":"Cost per Km"}, unit: "USD/km", format: "currency" },
    { id: "routeCostPerDrop", label: "Cost per Delivery", label_i18n: {"en":"Cost per Delivery"}, unit: "USD/durak", format: "currency" },
  ],
  thresholds: [{ fieldId: "routeCostPerKm", warning: 1.5, critical: 2.0, direction: "higher_is_bad", warningMessage: "Km maliyet > $1.50 — rota optimizasyonu onerilir.", warningMessage_i18n: {"en":"Cost per km > $1.50 — route optimization recommended."}, criticalMessage: "Cost per km > $2.00 — route profitability at risk.", criticalMessage_i18n: {"en":"Cost per km > $2.00 — route profitability at risk."} }],
  formulaPipeline: [
    { formulaId: "cost.route_distance_cost", inputMap: { distance: "distance", fuelCostPerKm: "fuelCostPerKm" ,
        distanceKm: "distanceKm",
        costPerKm: "costPerKm"}, outputId: "routeDistanceCost" },
    { formulaId: "cost.route_time_cost", inputMap: { distance: "distance", avgSpeed: "avgSpeed", driverWagePerHour: "driverWagePerHour" ,
        timeHours: "timeHours",
        costPerHour: "costPerHour"}, outputId: "routeTimeCost" },
    { formulaId: "cost.route_toll_cost", inputMap: { tollCost: "tollCost" ,
        tollAmount: "tollAmount",
        tollCount: "tollCount",
        tollPerPass: "tollPerPass"}, outputId: "routeTollCost" },
    { formulaId: "cost.route_maintenance_cost", inputMap: { distance: "distance", maintenancePerKm: "maintenancePerKm" ,
        distanceKm: "distanceKm",
        maintenanceRate: "maintenanceRate"}, outputId: "routeMaintenanceCost" },
    { formulaId: "cost.route_overhead", inputMap: { distance: "distance", fuelCostPerKm: "fuelCostPerKm", driverWagePerHour: "driverWagePerHour", avgSpeed: "avgSpeed", tollCost: "tollCost", maintenancePerKm: "maintenancePerKm", overheadPercent: "overheadPercent" ,
        routeDistance: "routeDistance",
        overheadPerKm: "overheadPerKm"}, outputId: "routeOverhead" },
    { formulaId: "cost.route_total_cost", inputMap: { routeDistanceCost: "routeDistanceCost", routeTimeCost: "routeTimeCost", routeTollCost: "routeTollCost", routeMaintenanceCost: "routeMaintenanceCost", routeOverhead: "routeOverhead" ,
        routeFuelCost: "routeFuelCost",
        routeLaborCost: "routeLaborCost"}, outputId: "routeTotalCost" },
    { formulaId: "measurement.route_cost_per_km", inputMap: { routeTotalCost: "routeTotalCost", distance: "distance" ,
        distanceKm: "distanceKm"}, outputId: "routeCostPerKm" },
    { formulaId: "measurement.route_cost_per_drop", inputMap: { routeTotalCost: "routeTotalCost", numberOfDrops: "numberOfDrops" ,
        totalDrops: "totalDrops"}, outputId: "routeCostPerDrop" },
  ],
  reportTemplate: { title: "Route Cost Analysis Report", title_i18n: {"en":"Route Cost Analysis Report"}, sections: ["executive_summary", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.0, volatilityPercent: 10, targetMarginPercent: 15, assumptionNotes: ["Distance cost = km × fuel unit cost.", "Time cost = (km/speed) × hourly wage.", "Overhead = direct costs × rate.", "Km maliyet = toplam / km, drop maliyet = toplam / durak."],assumptionNotes_i18n:[{"en":"Distance cost = km × fuel unit cost."},{"en":"Time cost = (km/speed) × hourly wage."},{"en":"Overhead = direct costs × rate."},{"en":"Cost per km = total / km, cost per drop = total / stops."}] },
};
