import type { PremiumCalculatorSchema } from "@/lib/features/premium-schema/premium-calculator-schema";
export const SHOP_HOURLY_RATE_SCHEMA: PremiumCalculatorSchema = {
  id: "shop-hourly-rate-analyzer", legacyPaidSlug: "shop-hourly-rate-analyzer",
  name: "Shop Hourly Rate", name_i18n: {"en":"Shop Hourly Rate"}, sectorSlug: "financial-planning", category: "cost",
  painStatement: "If the shop hourly rate is not calculated correctly, billing losses and margin erosion occur.", painStatement_i18n: {"en":"If the shop hourly rate is not calculated correctly, billing losses and margin erosion occur."},
  inputs: [
    { id: "technicianWages", label: "Teknisyen Ücretleri", label_i18n: {"en":"Technician Wages"}, type: "number", unit: "USD/ay", required: true, smartDefault: 15000, validation: { min: 0 }, helper: "", expertMeaning: "Total technician wages", expertMeaning_i18n: {"en":"Total technician wages"} },
    { id: "managerWages", label: "Yönetici Ücretleri", label_i18n: {"en":"Manager Wages"}, type: "number", unit: "USD/ay", required: false, smartDefault: 8000, validation: { min: 0 }, helper: "", expertMeaning: "Manager wages", expertMeaning_i18n: {"en":"Manager wages"} },
    { id: "adminWages", label: "Admin Wages", label_i18n: {"en":"Admin Wages"}, type: "number", unit: "USD/ay", required: false, smartDefault: 5000, validation: { min: 0 }, helper: "", expertMeaning: "Admin wages", expertMeaning_i18n: {"en":"Admin wages"} },
    { id: "rent", label: "Kira", label_i18n: {"en":"Rent"}, type: "number", unit: "USD/ay", required: true, smartDefault: 5000, validation: { min: 0 }, helper: "", expertMeaning: "Monthly rent", expertMeaning_i18n: {"en":"Monthly rent"} },
    { id: "utilities", label: "Fatura", label_i18n: {"en":"Utilities"}, type: "number", unit: "USD/ay", required: false, smartDefault: 2000, validation: { min: 0 }, helper: "", expertMeaning: "Utilities", expertMeaning_i18n: {"en":"Utilities"} },
    { id: "insurance", label: "Sigorta", label_i18n: {"en":"Insurance"}, type: "number", unit: "USD/ay", required: false, smartDefault: 1000, validation: { min: 0 }, helper: "", expertMeaning: "Insurance", expertMeaning_i18n: {"en":"Insurance"} },
    { id: "tools", label: "Alet/Ekipman", label_i18n: {"en":"Tools/Equipment"}, type: "number", unit: "USD/ay", required: false, smartDefault: 1500, validation: { min: 0 }, helper: "", expertMeaning: "Tools & equipment", expertMeaning_i18n: {"en":"Tools & equipment"} },
    { id: "depreciation", label: "Amortisman", label_i18n: {"en":"Depreciation"}, type: "number", unit: "USD/ay", required: false, smartDefault: 2000, validation: { min: 0 }, helper: "", expertMeaning: "Monthly depreciation", expertMeaning_i18n: {"en":"Monthly depreciation"} },
    { id: "totalAvailableHours", label: "Toplam Faturalanabilir Saat", label_i18n: {"en":"Total Billable Hours"}, type: "number", unit: "saat/ay", required: true, smartDefault: 500, validation: { min: 1 }, helper: "", expertMeaning: "Total billable hours", expertMeaning_i18n: {"en":"Total billable hours"} },
    { id: "utilizationRate", label: "Utilization Rate", label_i18n: {"en":"Utilization Rate"}, type: "number", unit: "", required: false, smartDefault: 0.75, validation: { min: 0, max: 1 }, helper: "", expertMeaning: "Utilization rate", expertMeaning_i18n: {"en":"Utilization rate"} },
    { id: "targetMargin", label: "Target Profit Margin", label_i18n: {"en":"Target Profit Margin"}, type: "number", unit: "%", required: false, smartDefault: 30, validation: { min: 0, max: 100 }, helper: "", expertMeaning: "Target profit margin", expertMeaning_i18n: {"en":"Target profit margin"} },
    { id: "actualBillingRate", label: "Actual Billing Rate", label_i18n: {"en":"Actual Billing Rate"}, type: "number", unit: "USD/saat", required: true, smartDefault: 95, validation: { min: 0 }, helper: "", expertMeaning: "Actual billing rate", expertMeaning_i18n: {"en":"Actual billing rate"} },
  ],
  outputs: [
    { id: "directLabor", label: "Direct Labor", label_i18n: {"en":"Direct Labor"}, unit: "USD/ay", format: "currency" },
    { id: "indirectLabor", label: "Indirect Labor", label_i18n: {"en":"Indirect Labor"}, unit: "USD/ay", format: "currency" },
    { id: "overhead", label: "Genel Gider", label_i18n: {"en":"Overhead"}, unit: "USD/ay", format: "currency" },
    { id: "totalShopCost", label: "Toplam Atölye Maliyeti", label_i18n: {"en":"Total Shop Cost"}, unit: "USD/ay", format: "currency", isBigNumber: true },
    { id: "billableHours", label: "Faturalanabilir Saat", label_i18n: {"en":"Billable Hours"}, unit: "saat/ay", format: "number" },
    { id: "shopHourlyRate", label: "Atölye Saatlik Ücreti", label_i18n: {"en":"Shop Hourly Rate"}, unit: "USD/saat", format: "currency" },
    { id: "effectiveMargin", label: "Actual Margin", label_i18n: {"en":"Actual Margin"}, unit: "%", format: "percentage" },
  ],
  thresholds: [{ fieldId: "effectiveMargin", warning: 20, critical: 10, direction: "lower_is_bad", warningMessage: "Margin < 20% — review cost structure.", warningMessage_i18n: {"en":"Margin < 20% — review cost structure."}, criticalMessage: "Margin < 10% — urgent pricing revision.", criticalMessage_i18n: {"en":"Margin < 10% — urgent pricing revision."} }],
  formulaPipeline: [
    { formulaId: "cost.shop_direct_labor", inputMap: { technicianWages: "technicianWages" ,
        directHours: "directHours",
        directRate: "directRate"}, outputId: "directLabor" },
    { formulaId: "cost.shop_indirect_labor", inputMap: { managerWages: "managerWages", adminWages: "adminWages" ,
        indirectHours: "indirectHours",
        indirectRate: "indirectRate"}, outputId: "indirectLabor" },
    { formulaId: "cost.shop_overhead", inputMap: {
        depreciation: "depreciation",
        directLabor: "rent",
        indirectLabor: "utilities",
        insurance: "insurance",
        tools: "tools"
      ,
        overheadPct: "overheadPct"}, outputId: "overhead" },
    { formulaId: "cost.shop_total_cost", inputMap: { directLabor: "directLabor", indirectLabor: "indirectLabor", overhead: "overhead" ,
        shopOverhead: "shopOverhead"}, outputId: "totalShopCost" },
    { formulaId: "cost.shop_billable_hours", inputMap: { totalAvailableHours: "totalAvailableHours", utilizationRate: "utilizationRate" ,
        totalHours: "totalHours",
        chargeablePct: "chargeablePct"}, outputId: "billableHours" },
    { formulaId: "cost.shop_hourly_rate", inputMap: { totalShopCost: "totalShopCost", billableHours: "billableHours" ,
        fixedMonthlyCost: "fixedMonthlyCost",
        monthlyMachineHours: "monthlyMachineHours",
        variableCostPerHour: "variableCostPerHour"}, outputId: "shopHourlyRate" },
    { formulaId: "cost.shop_effective_margin", inputMap: {
        actualBillingRate: "actualBillingRate",
        shopHourlyRate: "shopHourlyRate"
      ,
        shopRevenue: "shopRevenue",
        shopTotalCost: "shopTotalCost"}, outputId: "effectiveMargin" },
  ],
  reportTemplate: { title: "Atölye Saatlik Ücret Raporu", title_i18n: {"en":"Shop Hourly Rate Report"}, sections: ["executive_summary", "loss_breakdown", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.1, volatilityPercent: 10, targetMarginPercent: 20, assumptionNotes: ["Saatlik ücret = Toplam maliyet / Faturalanabilir saat.", "Marj = (Faturalama - Maliyet) / Faturalama.", "Utilization rate reflects actual occupancy."],assumptionNotes_i18n:[{"en":"Hourly rate = Total cost / Billable hours."},{"en":"Margin = (Billing - Cost) / Billing."},{"en":"Utilization rate reflects actual occupancy."}] },
};
