
import type { PremiumCalculatorSchema } from "@/lib/features/premium-schema/premium-calculator-schema";
export const WAREHOUSE_LAYOUT_SCHEMA: PremiumCalculatorSchema = {
  id: "warehouse-layout-analyzer", legacyPaidSlug: "warehouse-layout-analyzer",
  name: "Warehouse Layout & Efficiency Analyzer", name_i18n: {"en":"Warehouse Layout & Efficiency Analyzer"}, sectorSlug: "logistics-transport", category: "measurement",
  painStatement: "If warehouse layout is not optimized, pallet position, throughput, and picking efficiency drops, operation Cost increases.", painStatement_i18n: {"en":"If warehouse layout is not optimized, pallet position, throughput, and picking efficiency drops, operation Cost increases."},
  inputs: [
    { id: "warehouseFootprint", label: "Warehouse footprint", label_i18n: {"en":"Warehouse footprint"}, type: "number", unit: "m²", required: true, smartDefault: 2000, validation: { min: 1 }, helper: "", expertMeaning: "Warehouse footprint", expertMeaning_i18n: {"en":"Warehouse footprint"} },
    { id: "utilRate", label: "Storage utilization rate", label_i18n: {"en":"Storage utilization rate"}, type: "number", unit: "%", required: true, smartDefault: 70, validation: { min: 1, max: 100 }, helper: "", expertMeaning: "Storage utilization rate", expertMeaning_i18n: {"en":"Storage utilization rate"} },
    { id: "palletFootprint", label: "Pallet footprint (L×W)", label_i18n: {"en":"Pallet footprint (L×W)"}, type: "number", unit: "m²", required: true, smartDefault: 1.0, validation: { min: 0.1 }, helper: "", expertMeaning: "Pallet footprint (L×W)", expertMeaning_i18n: {"en":"Pallet footprint (L×W)"} },
    { id: "aisleFactor", label: "Aisle space multiplier", label_i18n: {"en":"Aisle space multiplier"}, type: "number", unit: "scalar", required: true, smartDefault: 1.5, validation: { min: 1 }, helper: "", expertMeaning: "Aisle space multiplier", expertMeaning_i18n: {"en":"Aisle space multiplier"} },
    { id: "rackLevels", label: "Number of rack levels", label_i18n: {"en":"Number of rack levels"}, type: "number", unit: "scalar", required: true, smartDefault: 4, validation: { min: 1 }, helper: "", expertMeaning: "Number of rack levels", expertMeaning_i18n: {"en":"Number of rack levels"} },
    { id: "doorCount", label: "Number of loading doors", label_i18n: {"en":"Number of loading doors"}, type: "number", unit: "scalar", required: false, smartDefault: 4, validation: { min: 1 }, helper: "", expertMeaning: "Number of loading doors", expertMeaning_i18n: {"en":"Number of loading doors"} },
    { id: "turnaroundLoad", label: "Loading turnaround hours", label_i18n: {"en":"Loading turnaround hours"}, type: "number", unit: "hours", required: false, smartDefault: 0.5, validation: { min: 0 }, helper: "", expertMeaning: "Loading turnaround hours", expertMeaning_i18n: {"en":"Loading turnaround hours"} },
    { id: "turnaroundUnload", label: "Unloading turnaround hours", label_i18n: {"en":"Unloading turnaround hours"}, type: "number", unit: "hours", required: false, smartDefault: 0.5, validation: { min: 0 }, helper: "", expertMeaning: "Unloading turnaround hours", expertMeaning_i18n: {"en":"Unloading turnaround hours"} },
    { id: "pickLines", label: "Daily pick lines", label_i18n: {"en":"Daily pick lines"}, type: "number", unit: "units/day", required: false, smartDefault: 500, validation: { min: 0 }, helper: "", expertMeaning: "Daily pick lines", expertMeaning_i18n: {"en":"Daily pick lines"} },
    { id: "travelTime", label: "Daily travel time for picking", label_i18n: {"en":"Daily travel time for picking"}, type: "number", unit: "saat/gun", required: false, smartDefault: 40, validation: { min: 0 }, helper: "", expertMeaning: "Daily travel time for picking", expertMeaning_i18n: {"en":"Daily travel time for picking"} },
    { id: "facilityCost", label: "Total facility cost", label_i18n: {"en":"Total facility cost"}, type: "number", unit: "USD/year", required: false, smartDefault: 120000, validation: { min: 0 }, helper: "", expertMeaning: "Total facility cost", expertMeaning_i18n: {"en":"Total facility cost"} },
  ],
  outputs: [
    { id: "palletPositions", label: "Palet Pozisyonu (Tek Kat)", label_i18n: {"en":"Palet Pozisyonu (Tek Kat)"}, unit: "units", format: "number" },
    { id: "verticalCap", label: "Dikey Capacity", label_i18n: {"en":"Dikey Capacity"}, unit: "units", format: "number" },
    { id: "throughputCap", label: "Throughput Capacity", label_i18n: {"en":"Throughput Capacity"}, unit: "arac/gun", format: "number" },
    { id: "pickEfficiency", label: "Toplama Verimliligi", label_i18n: {"en":"Toplama Verimliligi"}, unit: "kalem/saat", format: "number" },
    { id: "costPerPosition", label: "position Per Cost", label_i18n: {"en":"position Per Cost"}, unit: "USD/year", format: "currency", isBigNumber: true },
  ],
  thresholds: [{ fieldId: "costPerPosition", warning: 150, critical: 250, direction: "higher_is_bad", warningMessage: "position Cost > $150 — Optimization opportunity exists.", warningMessage_i18n: {"en":"position Cost > $150 — Optimization opportunity exists."}, criticalMessage: "position Cost > $250 — Warehouse efficiency is low.", criticalMessage_i18n: {"en":"position Cost > $250 — Warehouse efficiency is low."} }],
  formulaPipeline: [
    { formulaId: "measurement.warehouse_pallet_positions", inputMap: { warehouseFootprint: "warehouseFootprint", utilRate: "utilRate", palletFootprint: "palletFootprint", aisleFactor: "aisleFactor" ,
        storageArea: "storageArea"}, outputId: "palletPositions" },
    { formulaId: "measurement.warehouse_vertical_cap", inputMap: { palletPositions: "palletPositions", rackLevels: "rackLevels" }, outputId: "verticalCap" },
    { formulaId: "measurement.warehouse_throughput_cap", inputMap: { doorCount: "doorCount", turnaroundLoad: "turnaroundLoad", turnaroundUnload: "turnaroundUnload" ,
        doors: "doors"}, outputId: "throughputCap" },
    { formulaId: "measurement.warehouse_pick_efficiency", inputMap: { pickLines: "pickLines", travelTime: "travelTime" ,
        lines: "lines"}, outputId: "pickEfficiency" },
    { formulaId: "cost.warehouse_cost_per_pos", inputMap: { facilityCost: "facilityCost", palletPositions: "palletPositions" }, outputId: "costPerPosition" },
  ],
  reportTemplate: { title: "Warehouse Layout Report", title_i18n: {"en":"Warehouse Layout Report"}, sections: ["executive_summary", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.1, volatilityPercent: 10, targetMarginPercent: 15, assumptionNotes: ["Positions = (Area×UtilRate)/(PalletFP×AisleFactor).", "Throughput = Doors/(TurnLoad+TurnUnload).", "PickEfficiency = Lines/TravelTime."],assumptionNotes_i18n:[{"en":"Positions = (Area×UtilRate)/(PalletFP×AisleFactor)."},{"en":"Throughput = Doors/(TurnLoad+TurnUnload)."},{"en":"PickEfficiency = Lines/TravelTime."}] },
};
