import type { PremiumCalculatorSchema } from "@/lib/features/premium-schema/premium-calculator-schema";
export const WELD_VOLUME_COST_SCHEMA: PremiumCalculatorSchema = {
  id: "weld-volume-cost-analyzer", legacyPaidSlug: "weld-volume-cost-analyzer",
  name: "Kaynak Hacmi ve Maliyeti", name_i18n: {"en":"Kaynak Hacmi ve Maliyeti","tr":"Kaynak Hacmi ve Maliyeti"}, sectorSlug: "cnc-manufacturing", category: "cost",
  painStatement: "Kaynak hacmi ve dolgu maliyeti hesaplanmazsa, tahminlerin üzerinde malzeme ve işçilik gideri oluşur.", painStatement_i18n: {"en":"Kaynak hacmi ve dolgu maliyeti hesaplanmazsa, tahminlerin üzerinde malzeme ve işçilik gideri oluşur.","tr":"Kaynak hacmi ve dolgu maliyeti hesaplanmazsa, tahminlerin üzerinde malzeme ve işçilik gideri oluşur."},
  inputs: [
    { id: "leg", label: "Kaynak Ağız Boyu (Leg)", label_i18n: {"en":"Fillet weld leg size","tr":"Kaynak Ağız Boyu (Leg)"}, type: "number", unit: "mm", required: true, smartDefault: 6, validation: { min: 1 }, helper: "", expertMeaning: "Fillet weld leg size", expertMeaning_i18n: {"en":"Fillet weld leg size","tr":"kaynak ağız boyu (leg)"} },
    { id: "weldLength", label: "Kaynak Uzunluğu", label_i18n: {"en":"Total weld length","tr":"Kaynak Uzunluğu"}, type: "number", unit: "m", required: true, smartDefault: 10, validation: { min: 0.1 }, helper: "", expertMeaning: "Total weld length", expertMeaning_i18n: {"en":"Total weld length","tr":"kaynak uzunluğu"} },
    { id: "density", label: "Malzeme Yoğunluğu", label_i18n: {"en":"Weld metal density","tr":"Malzeme Yoğunluğu"}, type: "number", unit: "kg/m³", required: false, smartDefault: 7850, validation: { min: 0 }, helper: "", expertMeaning: "Weld metal density", expertMeaning_i18n: {"en":"Weld metal density","tr":"malzeme yoğunluğu"} },
    { id: "depEff", label: "Biriktirme Verimi", label_i18n: {"en":"Biriktirme Verimi","tr":"Biriktirme Verimi"}, type: "number", unit: "", required: false, smartDefault: 0.8, validation: { min: 0, max: 1 }, helper: "", expertMeaning: "Deposition efficiency", expertMeaning_i18n: {"en":"Deposition efficiency","tr":"Deposition efficiency"} },
    { id: "pricePerKg", label: "Dolgu Teli Fiyatı", label_i18n: {"en":"Filler wire price","tr":"Dolgu Teli Fiyatı"}, type: "number", unit: "USD/kg", required: true, smartDefault: 5, validation: { min: 0 }, helper: "", expertMeaning: "Filler wire price", expertMeaning_i18n: {"en":"Filler wire price","tr":"dolgu teli fiyatı"} },
    { id: "gasFlowRate", label: "Gaz Debisi", label_i18n: {"en":"Gaz Debisi","tr":"Gaz Debisi"}, type: "number", unit: "L/dk", required: false, smartDefault: 15, validation: { min: 0 }, helper: "", expertMeaning: "Shielding gas flow rate", expertMeaning_i18n: {"en":"Shielding gas flow rate","tr":"Shielding gas flow rate"} },
    { id: "arcTime", label: "Ark Süresi", label_i18n: {"en":"Total arc-on time","tr":"Ark Süresi"}, type: "number", unit: "saat", required: true, smartDefault: 2, validation: { min: 0.1 }, helper: "", expertMeaning: "Total arc-on time", expertMeaning_i18n: {"en":"Total arc-on time","tr":"ark süresi"} },
    { id: "gasPrice", label: "Gaz Fiyatı", label_i18n: {"en":"Gas price per liter","tr":"Gaz Fiyatı"}, type: "number", unit: "USD/L", required: false, smartDefault: 0.05, validation: { min: 0 }, helper: "", expertMeaning: "Gas price per liter", expertMeaning_i18n: {"en":"Gas price per liter","tr":"gaz fiyatı"} },
    { id: "voltage", label: "Voltaj", label_i18n: {"en":"Voltaj","tr":"Voltaj"}, type: "number", unit: "V", required: false, smartDefault: 26, validation: { min: 0 }, helper: "", expertMeaning: "Welding voltage", expertMeaning_i18n: {"en":"Welding voltage","tr":"Welding voltage"} },
    { id: "current", label: "Akım", label_i18n: {"en":"Welding current","tr":"Akım"}, type: "number", unit: "A", required: false, smartDefault: 280, validation: { min: 0 }, helper: "", expertMeaning: "Welding current", expertMeaning_i18n: {"en":"Welding current","tr":"akım"} },
    { id: "machineEff", label: "Makine Verimi", label_i18n: {"en":"Makine Verimi","tr":"Makine Verimi"}, type: "number", unit: "", required: false, smartDefault: 0.85, validation: { min: 0, max: 1 }, helper: "", expertMeaning: "Machine efficiency", expertMeaning_i18n: {"en":"Machine efficiency","tr":"Machine efficiency"} },
    { id: "elecRate", label: "Elektrik Tarifesi", label_i18n: {"en":"Elektrik Tarifesi","tr":"Elektrik Tarifesi"}, type: "number", unit: "USD/kWh", required: false, smartDefault: 0.12, validation: { min: 0 }, helper: "", expertMeaning: "Electricity rate", expertMeaning_i18n: {"en":"Electricity rate","tr":"Electricity rate"} },
    { id: "depRate", label: "Biriktirme Hızı", label_i18n: {"en":"Deposition rate","tr":"Biriktirme Hızı"}, type: "number", unit: "kg/saat", required: false, smartDefault: 2.5, validation: { min: 0 }, helper: "", expertMeaning: "Deposition rate", expertMeaning_i18n: {"en":"Deposition rate","tr":"biriktirme hızı"} },
    { id: "laborRate", label: "İşçilik Saat Ücreti", label_i18n: {"en":"Labor cost per hour","tr":"İşçilik Saat Ücreti"}, type: "number", unit: "USD/saat", required: true, smartDefault: 35, validation: { min: 0 }, helper: "", expertMeaning: "Labor cost per hour", expertMeaning_i18n: {"en":"Labor cost per hour","tr":"i̇şçilik saat ücreti"} },
  ],
  outputs: [
    { id: "weldArea", label: "Kesit Alanı", label_i18n: {"en":"Kesit Alan","tr":"Kesit Alanı"}, unit: "mm²", format: "number" },
    { id: "weldVolume", label: "Kaynak Hacmi", label_i18n: {"en":"Kaynak Hacmi","tr":"Kaynak Hacmi"}, unit: "mm³", format: "number" },
    { id: "depositedWeight", label: "Biriktirilen Ağırlık", label_i18n: {"en":"Biriktirilen Agrlk","tr":"Biriktirilen Ağırlık"}, unit: "kg", format: "number" },
    { id: "electrodeWeight", label: "Elektrod Ağırlığı", label_i18n: {"en":"Elektrod Agrlg","tr":"Elektrod Ağırlığı"}, unit: "kg", format: "number" },
    { id: "fillerCost", label: "Dolgu Maliyeti", label_i18n: {"en":"Dolgu Maliyeti","tr":"Dolgu Maliyeti"}, unit: "USD", format: "currency" },
    { id: "gasCost", label: "Gaz Maliyeti", label_i18n: {"en":"Gaz Maliyeti","tr":"Gaz Maliyeti"}, unit: "USD", format: "currency" },
    { id: "powerCost", label: "Enerji Maliyeti", label_i18n: {"en":"Enerji Maliyeti","tr":"Enerji Maliyeti"}, unit: "USD", format: "currency" },
    { id: "totalWeldCost", label: "Toplam Kaynak Maliyeti", label_i18n: {"en":"Toplam Kaynak Maliyeti","tr":"Toplam Kaynak Maliyeti"}, unit: "USD", format: "currency", isBigNumber: true },
  ],
  thresholds: [{ fieldId: "totalWeldCost", warning: 5000, critical: 15000, direction: "higher_is_bad", warningMessage: "Kaynak maliyeti > $5K — proses optimizasyonu değerlendirilmeli.", warningMessage_i18n: {"en":"Kaynak maliyeti > $5K — proses optimizasyonu değerlendirilmeli.","tr":"Kaynak maliyeti > $5K — proses optimizasyonu değerlendirilmeli."}, criticalMessage: "Kaynak maliyeti > $15K — yöntem değişikliği gerekebilir.", criticalMessage_i18n: {"en":"Kaynak maliyeti > $15K — yöntem değişikliği gerekebilir.","tr":"Kaynak maliyeti > $15K — yöntem değişikliği gerekebilir."} }],
  formulaPipeline: [
    { formulaId: "measurement.weld_area", inputMap: { leg: "leg" }, outputId: "weldArea" },
    { formulaId: "measurement.weld_volume", inputMap: { weldArea: "weldArea", weldLength: "weldLength" }, outputId: "weldVolume" },
    { formulaId: "measurement.weld_deposited_weight", inputMap: { weldVolume: "weldVolume", density: "density" }, outputId: "depositedWeight" },
    { formulaId: "measurement.weld_electrode_weight", inputMap: { depositedWeight: "depositedWeight", depEff: "depEff" }, outputId: "electrodeWeight" },
    { formulaId: "cost.weld_filler_cost", inputMap: {
        weldWeight: "electrodeWeight",
        fillerPrice: "pricePerKg"
      ,
        electrodeWeight: "electrodeWeight",
        pricePerKg: "pricePerKg"}, outputId: "fillerCost" },
    { formulaId: "cost.weld_gas_cost", inputMap: { gasFlowRate: "gasFlowRate", arcTime: "arcTime", gasPrice: "gasPrice" }, outputId: "gasCost" },
    { formulaId: "cost.weld_power_cost", inputMap: { voltage: "voltage", current: "current", arcTime: "arcTime", machineEff: "machineEff", elecRate: "elecRate" }, outputId: "powerCost" },
    { formulaId: "cost.weld_total_cost", inputMap: { fillerCost: "fillerCost", gasCost: "gasCost", powerCost: "powerCost", arcTime: "arcTime", depRate: "depRate", laborRate: "laborRate" }, outputId: "totalWeldCost" },
  ],
  reportTemplate: { title: "Kaynak Hacim ve Maliyet Raporu", title_i18n: {"en":"Kaynak Hacim ve Maliyet Raporu","tr":"Kaynak Hacim ve Maliyet Raporu"}, sections: ["executive_summary", "loss_breakdown", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.1, volatilityPercent: 10, targetMarginPercent: 15, assumptionNotes: ["Kesit = Leg²/2. Hacim = Alan × Uzunluk.", "Biriktirme = Hacim × Yoğunluk.", "Enerji maliyeti = V×I×t / (1000×Verim) × Tarife."],assumptionNotes_i18n:[{"en":"Kesit = Leg²/2. Hacim = Alan × Uzunluk.","tr":"Kesit = Leg²/2. Hacim = Alan × Uzunluk."},{"en":"Biriktirme = Hacim × Yoğunluk.","tr":"Biriktirme = Hacim × Yoğunluk."},{"en":"Enerji maliyeti = V×I×t / (1000×Verim) × Tarife.","tr":"Enerji maliyeti = V×I×t / (1000×Verim) × Tarife."}] },
};
