import type { PremiumCalculatorSchema } from "@/lib/features/premium-schema/premium-calculator-schema";
export const WELD_VOLUME_COST_SCHEMA: PremiumCalculatorSchema = {
  id: "weld-volume-cost-analyzer", legacyPaidSlug: "weld-volume-cost-analyzer",
  name: "Weld Volume & Cost Analyzer", name_i18n: {"en":"Weld Volume & Cost Analyzer"}, sectorSlug: "cnc-manufacturing", category: "cost",
  painStatement: "If resource Volume and Filler Cost are not calculated, material and labor expenses exceed estimates.", painStatement_i18n: {"en":"If resource Volume and Filler Cost are not calculated, material and labor expenses exceed estimates."},
  inputs: [
    { id: "leg", label: "Fillet weld leg size", label_i18n: {"en":"Fillet weld leg size"}, type: "number", unit: "mm", required: true, smartDefault: 6, validation: { min: 1 }, helper: "", expertMeaning: "Fillet weld leg size", expertMeaning_i18n: {"en":"Fillet weld leg size"} },
    { id: "weldLength", label: "Total weld length", label_i18n: {"en":"Total weld length"}, type: "number", unit: "m", required: true, smartDefault: 10, validation: { min: 0.1 }, helper: "", expertMeaning: "Total weld length", expertMeaning_i18n: {"en":"Total weld length"} },
    { id: "density", label: "Weld metal density", label_i18n: {"en":"Weld metal density"}, type: "number", unit: "kg/m³", required: false, smartDefault: 7850, validation: { min: 0 }, helper: "", expertMeaning: "Weld metal density", expertMeaning_i18n: {"en":"Weld metal density"} },
    { id: "depEff", label: "Biriktirme Efficiency", label_i18n: {"en":"Biriktirme Efficiency"}, type: "number", unit: "", required: false, smartDefault: 0.8, validation: { min: 0, max: 1 }, helper: "", expertMeaning: "Deposition efficiency", expertMeaning_i18n: {"en":"Deposition efficiency"} },
    { id: "pricePerKg", label: "Filler wire price", label_i18n: {"en":"Filler wire price"}, type: "number", unit: "USD/kg", required: true, smartDefault: 5, validation: { min: 0 }, helper: "", expertMeaning: "Filler wire price", expertMeaning_i18n: {"en":"Filler wire price"} },
    { id: "gasFlowRate", label: "Gaz Debisi", label_i18n: {"en":"Gaz Debisi"}, type: "number", unit: "L/dk", required: false, smartDefault: 15, validation: { min: 0 }, helper: "", expertMeaning: "Shielding gas flow rate", expertMeaning_i18n: {"en":"Shielding gas flow rate"} },
    { id: "arcTime", label: "Total arc-on time", label_i18n: {"en":"Total arc-on time"}, type: "number", unit: "hours", required: true, smartDefault: 2, validation: { min: 0.1 }, helper: "", expertMeaning: "Total arc-on time", expertMeaning_i18n: {"en":"Total arc-on time"} },
    { id: "gasPrice", label: "Gas price per liter", label_i18n: {"en":"Gas price per liter"}, type: "number", unit: "USD/L", required: false, smartDefault: 0.05, validation: { min: 0 }, helper: "", expertMeaning: "Gas price per liter", expertMeaning_i18n: {"en":"Gas price per liter"} },
    { id: "voltage", label: "Voltaj", label_i18n: {"en":"Voltaj"}, type: "number", unit: "V", required: false, smartDefault: 26, validation: { min: 0 }, helper: "", expertMeaning: "Welding voltage", expertMeaning_i18n: {"en":"Welding voltage"} },
    { id: "current", label: "Welding current", label_i18n: {"en":"Welding current"}, type: "number", unit: "A", required: false, smartDefault: 280, validation: { min: 0 }, helper: "", expertMeaning: "Welding current", expertMeaning_i18n: {"en":"Welding current"} },
    { id: "machineEff", label: "Makine Efficiency", label_i18n: {"en":"Makine Efficiency"}, type: "number", unit: "", required: false, smartDefault: 0.85, validation: { min: 0, max: 1 }, helper: "", expertMeaning: "Machine efficiency", expertMeaning_i18n: {"en":"Machine efficiency"} },
    { id: "elecRate", label: "Elektrik Tarifesi", label_i18n: {"en":"Elektrik Tarifesi"}, type: "number", unit: "USD/kWh", required: false, smartDefault: 0.12, validation: { min: 0 }, helper: "", expertMeaning: "Electricity rate", expertMeaning_i18n: {"en":"Electricity rate"} },
    { id: "depRate", label: "Deposition rate", label_i18n: {"en":"Deposition rate"}, type: "number", unit: "kg/saat", required: false, smartDefault: 2.5, validation: { min: 0 }, helper: "", expertMeaning: "Deposition rate", expertMeaning_i18n: {"en":"Deposition rate"} },
    { id: "laborRate", label: "Labor cost per hour", label_i18n: {"en":"Labor cost per hour"}, type: "number", unit: "USD/hour", required: true, smartDefault: 35, validation: { min: 0 }, helper: "", expertMeaning: "Labor cost per hour", expertMeaning_i18n: {"en":"Labor cost per hour"} },
  ],
  outputs: [
    { id: "weldArea", label: "Kesit Alan", label_i18n: {"en":"Kesit Alan"}, unit: "mm²", format: "number" },
    { id: "weldVolume", label: "resource Volume", label_i18n: {"en":"resource Volume"}, unit: "mm³", format: "number" },
    { id: "depositedWeight", label: "Biriktirilen Weight", label_i18n: {"en":"Biriktirilen Weight"}, unit: "kg", format: "number" },
    { id: "electrodeWeight", label: "Elektrod Agrlg", label_i18n: {"en":"Elektrod Agrlg"}, unit: "kg", format: "number" },
    { id: "fillerCost", label: "Filler Cost", label_i18n: {"en":"Filler Cost"}, unit: "USD", format: "currency" },
    { id: "gasCost", label: "Gas Cost", label_i18n: {"en":"Gas Cost"}, unit: "USD", format: "currency" },
    { id: "powerCost", label: "Energy Cost", label_i18n: {"en":"Energy Cost"}, unit: "USD", format: "currency" },
    { id: "totalWeldCost", label: "Total resource Cost", label_i18n: {"en":"Total resource Cost"}, unit: "USD", format: "currency", isBigNumber: true },
  ],
  thresholds: [{ fieldId: "totalWeldCost", warning: 5000, critical: 15000, direction: "higher_is_bad", warningMessage: "resource Cost > $5K — Process optimization should be evaluated.", warningMessage_i18n: {"en":"resource Cost > $5K — Process optimization should be evaluated."}, criticalMessage: "resource Cost > $15K — method change gerekebilir.", criticalMessage_i18n: {"en":"resource Cost > $15K — method change gerekebilir."} }],
  formulaPipeline: [
    { formulaId: "measurement.weld_area", inputMap: { leg: "leg" }, outputId: "weldArea" },
    { formulaId: "measurement.weld_volume", inputMap: { weldArea: "weldArea", weldLength: "weldLength" }, outputId: "weldVolume" },
    { formulaId: "measurement.weld_deposited_weight", inputMap: { weldVolume: "weldVolume", density: "density" }, outputId: "depositedWeight" },
    { formulaId: "measurement.weld_electrode_weight", inputMap: { depositedWeight: "depositedWeight", depEff: "depEff" }, outputId: "electrodeWeight" },
    { formulaId: "cost.weld_filler_cost", inputMap: {
        weldWeight: "electrodeWeight",
        fillerPrice: "pricePerKg"
      ,
        electrodeWeight: "electrodeWeight",
        pricePerKg: "pricePerKg"}, outputId: "fillerCost" },
    { formulaId: "cost.weld_gas_cost", inputMap: { gasFlowRate: "gasFlowRate", arcTime: "arcTime", gasPrice: "gasPrice" }, outputId: "gasCost" },
    { formulaId: "cost.weld_power_cost", inputMap: { voltage: "voltage", current: "current", arcTime: "arcTime", machineEff: "machineEff", elecRate: "elecRate" }, outputId: "powerCost" },
    { formulaId: "cost.weld_total_cost", inputMap: { fillerCost: "fillerCost", gasCost: "gasCost", powerCost: "powerCost", arcTime: "arcTime", depRate: "depRate", laborRate: "laborRate" }, outputId: "totalWeldCost" },
  ],
  reportTemplate: { title: "resource Hacim ve Cost Raporu", title_i18n: {"en":"resource Hacim ve Cost Raporu"}, sections: ["executive_summary", "loss_breakdown", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.1, volatilityPercent: 10, targetMarginPercent: 15, assumptionNotes: [],assumptionNotes_i18n:[{"en":"Kesit = Leg²/2. Hacim = Alan × Uzunluk."},{"en":"Accumulation = Volume × Density."},{"en":"Energy cost = V×I×t / (1000×Verim) × Tarife."}] },
};
