import type { PremiumCalculatorSchema } from "@/lib/features/premium-schema/premium-calculator-schema";
export const WELD_COST_ANALYSIS_SCHEMA: PremiumCalculatorSchema = {
  id: "weld-cost-analysis-analyzer", legacyPaidSlug: "weld-cost-analysis-analyzer",
  name: "Weld Cost Detail Analyzer", name_i18n: {"en":"Weld Cost Detail Analyzer"}, sectorSlug: "cnc-manufacturing", category: "cost",
  painStatement: "Kaynak maliyetinin metraj bazlı analizi yapılmazsa, birim fiyat ve proses verimliliği izlenemez.", painStatement_i18n: {"en":"resource maliyetinin metraj bazlı analizi yapılmazsa, Unit fiyat ve proses verimliliği izlenemez."},
  inputs: [
    { id: "weldLength", label: "Total Weld Length", label_i18n: {"en":"Total Weld Length"}, type: "number", unit: "m", required: true, smartDefault: 100, validation: { min: 1 }, helper: "", expertMeaning: "Total weld meters", expertMeaning_i18n: {"en":"Total weld meters"} },
    { id: "totalShiftTime", label: "Vardiya Süresi", label_i18n: {"en":"Shift duration"}, type: "number", unit: "saat", required: false, smartDefault: 8, validation: { min: 1 }, helper: "", expertMeaning: "Shift duration", expertMeaning_i18n: {"en":"Shift duration"} },
    { id: "travelSpeed", label: "Travel speed", label_i18n: {"en":"Travel speed"}, type: "number", unit: "cm/dk", required: true, smartDefault: 30, validation: { min: 0.1 }, helper: "", expertMeaning: "Travel speed", expertMeaning_i18n: {"en":"Travel speed"} },
    { id: "arcTime", label: "Ark Süresi", label_i18n: {"en":"Arc-on time"}, type: "number", unit: "saat", required: true, smartDefault: 6, validation: { min: 0.1 }, helper: "", expertMeaning: "Arc-on time", expertMeaning_i18n: {"en":"Arc-on time"} },
    { id: "laborRate", label: "Labor rate", label_i18n: {"en":"Labor rate"}, type: "number", unit: "USD/saat", required: true, smartDefault: 35, validation: { min: 0 }, helper: "", expertMeaning: "Labor rate", expertMeaning_i18n: {"en":"Labor rate"} },
    { id: "overheadRate", label: "Genel Gider", label_i18n: {"en":"Genel Expense"}, type: "number", unit: "USD/saat", required: false, smartDefault: 15, validation: { min: 0 }, helper: "", expertMeaning: "Overhead rate", expertMeaning_i18n: {"en":"Overhead rate"} },
    { id: "fillerCost", label: "Filler Cost", label_i18n: {"en":"Filler Cost"}, type: "number", unit: "USD", required: true, smartDefault: 200, validation: { min: 0 }, helper: "", expertMeaning: "Total filler cost", expertMeaning_i18n: {"en":"Total filler cost"} },
    { id: "gasCost", label: "Gas Cost", label_i18n: {"en":"Gas Cost"}, type: "number", unit: "USD", required: false, smartDefault: 80, validation: { min: 0 }, helper: "", expertMeaning: "Gas cost", expertMeaning_i18n: {"en":"Gas cost"} },
    { id: "powerCost", label: "Energy Cost", label_i18n: {"en":"Energy Cost"}, type: "number", unit: "USD", required: false, smartDefault: 50, validation: { min: 0 }, helper: "", expertMeaning: "Power cost", expertMeaning_i18n: {"en":"Power cost"} },
    { id: "depositedWeight", label: "Deposited weld metal", label_i18n: {"en":"Deposited weld metal"}, type: "number", unit: "kg", required: false, smartDefault: 15, validation: { min: 0 }, helper: "", expertMeaning: "Deposited weld metal", expertMeaning_i18n: {"en":"Deposited weld metal"} },
  ],
  outputs: [
    { id: "opFactor", label: "Calsma Faktoru", label_i18n: {"en":"Calsma Faktoru"}, unit: "", format: "percentage" },
    { id: "depositionRate", label: "Biriktirme Hz", label_i18n: {"en":"Biriktirme Hz"}, unit: "kg/saat", format: "number" },
    { id: "jointCost", label: "Total Joint Cost", label_i18n: {"en":"Total Joint Cost"}, unit: "USD", format: "currency", isBigNumber: true },
    { id: "costPerMeter", label: "Cost Per Meter", label_i18n: {"en":"Cost Per Meter"}, unit: "USD/m", format: "currency" },
    { id: "consumablePct", label: "Consumable Ratio", label_i18n: {"en":"Consumable Ratio"}, unit: "%", format: "percentage" },
  ],
  thresholds: [{ fieldId: "costPerMeter", warning: 50, critical: 100, direction: "higher_is_bad", warningMessage: "m² maliyet > $50 — proses verimliliği düşük.", warningMessage_i18n: {"en":"m² Cost > $50 — proses verimliliği düşük."}, criticalMessage: "m² maliyet > $100 — kaynak yöntemi değişmeli.", criticalMessage_i18n: {"en":"m² Cost > $100 — resource yöntemi değişmeli."} }],
  formulaPipeline: [
    { formulaId: "measurement.weld_op_factor", inputMap: { arcTime: "arcTime", totalShiftTime: "totalShiftTime" }, outputId: "opFactor" },
    { formulaId: "measurement.weld_deposition_rate", inputMap: { depositedWeight: "depositedWeight", arcTime: "arcTime" }, outputId: "depositionRate" },
    { formulaId: "cost.weld_joint_cost", inputMap: { weldLength: "weldLength", travelSpeed: "travelSpeed", laborRate: "laborRate", overheadRate: "overheadRate", opFactor: "opFactor", fillerCost: "fillerCost", gasCost: "gasCost", powerCost: "powerCost" }, outputId: "jointCost" },
    { formulaId: "cost.weld_cost_per_meter", inputMap: { jointCost: "jointCost", weldLength: "weldLength" }, outputId: "costPerMeter" },
    { formulaId: "cost.weld_consumable_pct", inputMap: { fillerCost: "fillerCost", jointCost: "jointCost" }, outputId: "consumablePct" },
  ],
  reportTemplate: { title: "Kaynak Maliyet Analizi", title_i18n: {"en":"resource Cost Analizi"}, sections: ["executive_summary", "loss_breakdown", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.1, volatilityPercent: 10, targetMarginPercent: 15, assumptionNotes: ["Çalışma faktörü = Ark süresi / Vardiya süresi.", "Toplam maliyet = (Uzunluk/Hız)×(İşçilik+Overhead)/Faktör + Sarf.", "Sarf oranı = Dolgu / Toplam."],assumptionNotes_i18n:[{"en":"Çalışma faktörü = Ark süresi / Vardiya süresi."},{"en":"Toplam maliyet = (Uzunluk/Hız)×(İşçilik+Overhead)/Faktör + Sarf."},{"en":"Sarf oranı = Dolgu / Toplam."}] },
};
