import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        /* Anthropic Aesthetic */
        "industrial-matte": "#F0EEE6",
        "premium-velvet": "#1A1915",
        "body-charcoal": "rgba(26, 25, 21, 0.65)",
        "technical-gray": "rgba(26, 25, 21, 0.1)",
        "action-orange": "#BD5D3A",
        "sc-copper": "#BD5D3A",
        "sc-navy": "#1A1915",
        /* Status signals */
        "crit-red": "#991B1B",
        "warn-amber": "#D97706",
        "safe-green": "#166534",
        /* Legacy aliases → industrial mapping */
        "base-black": "#111111",
        "base-white": "#FFFFFF",
        "slate-gray": "#2B2B2B",
        "light-gray": "#F0EEE6",
        "deep-navy": { DEFAULT: "#1A1915", foreground: "#FAF9F5" },
        "dark-navy": "#1A1915",
        "bg-primary": "#F0EEE6",
        "bg-card": "#FAF9F5",
        "bg-subtle": "#F0EEE6",
        "text-primary": "#1A1915",
        "text-secondary": "#2B2B2B",
        "text-muted": "#2B2B2B",
        terminal: { DEFAULT: "#111111", surface: "#FAF7F2", border: "#D1D1D1" },
        amber: { DEFAULT: "#F59E0B", light: "#FBFBFA" },
        "accent-teal": "#111111",
        "accent-emerald": "#10B981",
        "accent-amber": "#F59E0B",
        emerald: "#10B981",
        "soft-red": "#DC2626",
        cyan: "#2B2B2B",
        slate: "#2B2B2B",
        "professional-blue": "#1A1915",
        "off-white": "#F0EEE6",
        "border-subtle": "rgba(26, 25, 21, 0.1)",
        "border-focus": "#1A1915",
        success: "#10B981",
        warning: "#F59E0B",
        error: "#DC2626",
        premium: { DEFAULT: "#111111", surface: "#FAF7F2", border: "#D1D1D1" },
      },
      fontFamily: {
        sans: [
          "var(--font-inter)",
          "-apple-system",
          "BlinkMacSystemFont",
          "Helvetica Neue",
          "Helvetica",
          "Arial",
          "sans-serif",
        ],
        display: [
          "var(--font-barlow)",
          "Barlow",
          "DIN Alternate",
          "Arial Narrow",
          "sans-serif",
        ],
        mono: [
          "var(--font-jetbrains)",
          "JetBrains Mono",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Consolas",
          "monospace",
        ],
      },
      boxShadow: {
        card: "none",
        "card-hover": "none",
        "card-premium": "none",
        "card-dark": "none",
        sm: "none",
      },
      borderRadius: {
        none: "0",
        sm: "0",
        DEFAULT: "0",
        md: "0",
        lg: "0",
        xl: "0",
        "2xl": "0",
        "3xl": "0",
        card: "0",
      },
    },
  },
  plugins: [],
};

export default config;
