import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        /* Industrial Ledger v1.1 */
        "industrial-matte": "#FAF7F2",
        "premium-velvet": "#1A1A1A",
        "body-charcoal": "#6B6B6B",
        "technical-gray": "#D1D1D1",
        "action-orange": "#C2410C",
        "sc-copper": "#C2410C",
        "sc-navy": "#1E40AF",
        /* Status signals */
        "crit-red": "#991B1B",
        "warn-amber": "#D97706",
        "safe-green": "#166534",
        /* Legacy aliases → industrial mapping */
        "base-black": "#111111",
        "base-white": "#FFFFFF",
        "slate-gray": "#2B2B2B",
        "light-gray": "#FBFBFA",
        "deep-navy": { DEFAULT: "#111111", foreground: "#FFFFFF" },
        "dark-navy": "#111111",
        "bg-primary": "#FBFBFA",
        "bg-card": "#FFFFFF",
        "bg-subtle": "#FBFBFA",
        "text-primary": "#111111",
        "text-secondary": "#2B2B2B",
        "text-muted": "#2B2B2B",
        terminal: { DEFAULT: "#111111", surface: "#FBFBFA", border: "#D1D1D1" },
        amber: { DEFAULT: "#F59E0B", light: "#FBFBFA" },
        "accent-teal": "#111111",
        "accent-emerald": "#10B981",
        "accent-amber": "#F59E0B",
        emerald: "#10B981",
        "soft-red": "#DC2626",
        cyan: "#2B2B2B",
        slate: "#2B2B2B",
        "professional-blue": "#111111",
        "off-white": "#FBFBFA",
        "border-subtle": "#D1D1D1",
        "border-focus": "#111111",
        success: "#10B981",
        warning: "#F59E0B",
        error: "#DC2626",
        premium: { DEFAULT: "#111111", surface: "#FBFBFA", border: "#D1D1D1" },
      },
      fontFamily: {
        sans: [
          "var(--font-inter)",
          "-apple-system",
          "BlinkMacSystemFont",
          "Helvetica Neue",
          "Helvetica",
          "Arial",
          "sans-serif",
        ],
        display: [
          "var(--font-barlow)",
          "Barlow",
          "DIN Alternate",
          "Arial Narrow",
          "sans-serif",
        ],
        mono: [
          "var(--font-jetbrains)",
          "JetBrains Mono",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Consolas",
          "monospace",
        ],
      },
      boxShadow: {
        card: "none",
        "card-hover": "none",
        "card-premium": "none",
        "card-dark": "none",
        sm: "none",
      },
      borderRadius: {
        none: "0",
        sm: "0",
        DEFAULT: "0",
        md: "0",
        lg: "0",
        xl: "0",
        "2xl": "0",
        "3xl": "0",
        card: "0",
      },
    },
  },
  plugins: [],
};

export default config;
