/** Slugs with generic guides explicitly blocked until approved spec exists (P3 repair). */

export const GENERIC_GUIDE_BLOCKED_SLUGS: readonly string[] = ["3d-print-job-margin-tool",
  "annual-leave-severance-notice-calculator",
  "auto-repair-comeback-cost",
  "auto-repair-parts-labor-quote-calculator",
  "belt-pulley-speed-length-calculator",
  "bolt-tightening-torque-calculator",
  "calibration-drift-risk",
  "carbon-footprint-compliance-risk",
  "cbam-exposure-quick-check",
  "cbam-unit-product-carbon-footprint-calculator",
  "cloud-api-cost-overrun",
  "cnc-oee-loss",
  "cnc-tool-wear-cost",
  "compressor-leak-cost-calculator",
  "construction-project-overrun",
  "construction-subcontractor-margin-leak",
  "dairy-feed-efficiency-loss",
  "doviz-pozisyonu-kur-farki-riski-hesabi",
  "downtime-minute-cost-calculator",
  "employee-total-cost-calculator",
  "energy-peak-cost",
  "energy-savings-package-calculator",
  "feed-efficiency-analyzer",
  "food-waste-margin-loss",
  "heat-loss-calculator",
  "hvac-callback-margin-risk",
  "hydraulic-pneumatic-cylinder-force-calculator",
  "inventory-carrying-cost-eoq-calculator",
  "investment-payback-npv-calculator",
  "logistics-fuel-route-drift",
  "material-waste-calculator",
  "oee-equipment-effectiveness-calculator",
  "painting-rework-coverage-risk",
  "plumbing-leak-callback-cost",
  "printing-reprint-margin-leak",
  "product-customer-profitability-calculator",
  "profit-margin-calculator",
  "quality-cost-paf-calculator",
  "quote-price-profit-margin-calculator",
  "restaurant-menu-margin-leak",
  "retail-inventory-turnover-risk",
  "roofing-weather-delay-risk",
  "scrap-rate-calculator",
  "sheet-metal-scrap-risk",
  "shop-rate-hourly-cost-calculator",
  "textile-fabric-waste-risk",
  "tolerance-stack-up-calculator",
  "value-stream-map-vsm-calculator",
  "warehouse-space-cost-leak",
];

export function isGuideExplicitlyBlocked(slug: string): boolean {
  const normalized = slug.trim();
  return GENERIC_GUIDE_BLOCKED_SLUGS.includes(normalized);
}
