import type { ProFieldGroup } from "../proFieldContract";

export const BREAK_EVEN_GROUPS: ProFieldGroup[] = [
  {
    title: "Revenue & Cost Structure",
    fields: [
      {
        id: "annual_revenue",
        label: "Annual Revenue",
        symbol: "R",
        type: "number",
        helpText: "Total annual revenue from the product or business unit",
        required: true,
        unitFamily: "currency",
        defaultUnit: "USD",
        allowedUnits: [{ unit: "USD", label: "USD" }, { unit: "EUR", label: "EUR" }, { unit: "GBP", label: "GBP" }],
        min: 0, max: 1e9,
      },
      {
        id: "variable_cost_percent",
        label: "Variable Cost (% of Revenue)",
        symbol: "VC%",
        type: "number",
        helpText: "Total variable costs as a percentage of revenue",
        required: true,
        unitFamily: "percentage",
        defaultUnit: "%",
        allowedUnits: [{ unit: "%", label: "%" }],
        min: 0, max: 99.9,
      },
      {
        id: "annual_fixed_costs",
        label: "Annual Fixed Operating Costs",
        symbol: "FC",
        type: "number",
        helpText: "Total annual fixed costs (rent, salaries, insurance, admin overhead)",
        required: true,
        unitFamily: "currency",
        defaultUnit: "USD",
        allowedUnits: [{ unit: "USD", label: "USD" }, { unit: "EUR", label: "EUR" }, { unit: "GBP", label: "GBP" }],
        min: 0, max: 1e9,
      },
    ],
  },
  {
    title: "Per-Unit Data (Optional)",
    fields: [
      {
        id: "unit_selling_price",
        label: "Selling Price per Unit",
        symbol: "P",
        type: "number",
        helpText: "Average selling price per unit — enables break-even unit calculation",
        required: false,
        unitFamily: "currency",
        defaultUnit: "USD",
        allowedUnits: [{ unit: "USD", label: "USD" }, { unit: "EUR", label: "EUR" }, { unit: "GBP", label: "GBP" }],
        min: 0, max: 1e6,
      },
      {
        id: "unit_variable_cost",
        label: "Variable Cost per Unit",
        symbol: "VCu",
        type: "number",
        helpText: "Variable cost incurred per unit sold",
        required: false,
        unitFamily: "currency",
        defaultUnit: "USD",
        allowedUnits: [{ unit: "USD", label: "USD" }, { unit: "EUR", label: "EUR" }, { unit: "GBP", label: "GBP" }],
        min: 0, max: 1e6,
      },
    ],
  },
  {
    title: "Cash & Liquidity",
    fields: [
      {
        id: "available_cash_liquidity",
        label: "Available Cash & Liquidity",
        symbol: "C",
        type: "number",
        helpText: "Current cash balance plus liquid assets available to cover short-term obligations",
        required: true,
        unitFamily: "currency",
        defaultUnit: "USD",
        allowedUnits: [{ unit: "USD", label: "USD" }, { unit: "EUR", label: "EUR" }, { unit: "GBP", label: "GBP" }],
        min: 0, max: 1e9,
      },
    ],
  },
];
