import type { ProFieldGroup } from "../proFieldContract";

export const CUSTOMER_SKU_FORENSICS_GROUPS: ProFieldGroup[] = [
  {
    title: "Pricing & Volume",
    fields: [
      {
        id: "unit_price",
        label: "Unit Selling Price",
        symbol: "P",
        type: "number",
        helpText: "Selling price per unit for the customer SKU",
        required: true,
        unitFamily: "currency",
        defaultUnit: "USD",
        allowedUnits: [{ unit: "USD", label: "USD" }, { unit: "EUR", label: "EUR" }, { unit: "GBP", label: "GBP" }],
        min: 0, max: 1e6,
      },
      {
        id: "unit_variable_cost",
        label: "Unit Variable Cost",
        symbol: "VCu",
        type: "number",
        helpText: "Direct variable cost per unit (materials, direct labor)",
        required: true,
        unitFamily: "currency",
        defaultUnit: "USD",
        allowedUnits: [{ unit: "USD", label: "USD" }, { unit: "EUR", label: "EUR" }, { unit: "GBP", label: "GBP" }],
        min: 0, max: 1e6,
      },
      {
        id: "annual_volume",
        label: "Annual Volume",
        symbol: "Q",
        type: "number",
        helpText: "Expected annual sales volume in units",
        required: true,
        unitFamily: "factor",
        defaultUnit: "units",
        allowedUnits: [{ unit: "units", label: "Units" }],
        min: 0, max: 1e9,
      },
    ],
  },
  {
    title: "Cost Factors",
    fields: [
      {
        id: "logistics_cost_pct",
        label: "Logistics Cost (% of Price)",
        symbol: "L%",
        type: "number",
        helpText: "Logistics and distribution costs as a percentage of unit selling price",
        required: true,
        unitFamily: "percentage",
        defaultUnit: "%",
        allowedUnits: [{ unit: "%", label: "%" }],
        min: 0, max: 99.9,
      },
      {
        id: "service_cost_pct",
        label: "Service Cost (% of Price)",
        symbol: "S%",
        type: "number",
        helpText: "Post-sales service and support costs as a percentage of unit selling price",
        required: true,
        unitFamily: "percentage",
        defaultUnit: "%",
        allowedUnits: [{ unit: "%", label: "%" }],
        min: 0, max: 99.9,
      },
      {
        id: "return_rate_pct",
        label: "Return Rate (% of Revenue)",
        symbol: "R%",
        type: "number",
        helpText: "Expected return/claims rate as a percentage of unit selling price",
        required: true,
        unitFamily: "percentage",
        defaultUnit: "%",
        allowedUnits: [{ unit: "%", label: "%" }],
        min: 0, max: 99.9,
      },
      {
        id: "financing_cost_pct",
        label: "Financing Cost (% of Price)",
        symbol: "F%",
        type: "number",
        helpText: "Customer financing, factoring, or payment term cost as a percentage of unit selling price",
        required: true,
        unitFamily: "percentage",
        defaultUnit: "%",
        allowedUnits: [{ unit: "%", label: "%" }],
        min: 0, max: 99.9,
      },
    ],
  },
  {
    title: "Target",
    fields: [
      {
        id: "target_margin",
        label: "Target Margin",
        symbol: "TM%",
        type: "number",
        helpText: "Minimum acceptable net margin percentage for this SKU",
        required: true,
        unitFamily: "percentage",
        defaultUnit: "%",
        allowedUnits: [{ unit: "%", label: "%" }],
        min: 0, max: 99.9,
      },
    ],
  },
];
