// SectorCalc PRO V2 — FX Commodity Pass-Through Pricer Field Contract
// Groups: Base Pricing, FX Rates, Commodity, Target

import type { ProFieldGroup } from "../proFieldContract";

export const FX_COMMODITY_PRICER_GROUPS: ProFieldGroup[] = [
  {
    title: "Base Pricing",
    fields: [
      {
        id: "base_price",
        label: "Base Price",
        symbol: "P0",
        type: "number",
        helpText: "Current base price per unit before any pass-through adjustment",
        required: true,
        unitFamily: "currency",
        defaultUnit: "USD",
        allowedUnits: [{ unit: "USD", label: "USD" }, { unit: "EUR", label: "EUR" }, { unit: "GBP", label: "GBP" }],
        min: 0.01, max: 1e9,
      },
      {
        id: "annual_volume",
        label: "Annual Volume",
        symbol: "V",
        type: "number",
        helpText: "Expected annual sales volume in units",
        required: true,
        unitFamily: "factor",
        defaultUnit: "units",
        allowedUnits: [{ unit: "units", label: "Units" }],
        min: 1, max: 1e9,
      },
    ],
  },
  {
    title: "FX Rates",
    fields: [
      {
        id: "fx_rate_spot",
        label: "Spot FX Rate",
        symbol: "FXs",
        type: "number",
        unitFamily: "factor",
        defaultUnit: "USD/EUR",
        allowedUnits: [{ unit: "USD/EUR", label: "USD/EUR" }, { unit: "USD/GBP", label: "USD/GBP" }, { unit: "EUR/USD", label: "EUR/USD" }, { unit: "GBP/USD", label: "GBP/USD" }, { unit: "TRY/USD", label: "TRY/USD" }],
        helpText: "Current spot exchange rate (local currency per foreign currency unit)",
        required: true,
        min: 0.0001, max: 1e6,
      },
      {
        id: "fx_rate_budget",
        label: "Budget FX Rate",
        symbol: "FXb",
        type: "number",
        unitFamily: "factor",
        defaultUnit: "USD/EUR",
        allowedUnits: [{ unit: "USD/EUR", label: "USD/EUR" }, { unit: "USD/GBP", label: "USD/GBP" }, { unit: "EUR/USD", label: "EUR/USD" }, { unit: "GBP/USD", label: "GBP/USD" }, { unit: "TRY/USD", label: "TRY/USD" }],
        helpText: "Budgeted or contracted exchange rate for comparison",
        required: true,
        min: 0.0001, max: 1e6,
      },
      {
        id: "fx_hedge_pct",
        label: "FX Hedge Coverage",
        symbol: "Hfx",
        type: "number",
        helpText: "Percentage of FX exposure covered by hedging instruments",
        required: true,
        unitFamily: "percentage",
        defaultUnit: "%",
        allowedUnits: [{ unit: "%", label: "%" }],
        min: 0, max: 100,
      },
    ],
  },
  {
    title: "Commodity",
    fields: [
      {
        id: "commodity_index_current",
        label: "Current Commodity Index",
        symbol: "CIc",
        type: "number",
        unitFamily: "factor",
        defaultUnit: "index",
        allowedUnits: [{ unit: "index", label: "index" }, { unit: "USD/tonne", label: "USD/t" }],
        helpText: "Current commodity index or raw material price level",
        required: true,
        min: 0.01, max: 1e9,
      },
      {
        id: "commodity_index_budget",
        label: "Budget Commodity Index",
        symbol: "CIb",
        type: "number",
        unitFamily: "factor",
        defaultUnit: "index",
        allowedUnits: [{ unit: "index", label: "index" }, { unit: "USD/tonne", label: "USD/t" }],
        helpText: "Budgeted commodity index level used in original pricing",
        required: true,
        min: 0.01, max: 1e9,
      },
      {
        id: "commodity_hedge_pct",
        label: "Commodity Hedge Coverage",
        symbol: "Hcm",
        type: "number",
        helpText: "Percentage of commodity exposure covered by hedging or fixed-price contracts",
        required: true,
        unitFamily: "percentage",
        defaultUnit: "%",
        allowedUnits: [{ unit: "%", label: "%" }],
        min: 0, max: 100,
      },
    ],
  },
  {
    title: "Target",
    fields: [
      {
        id: "material_cost_pct",
        label: "Material Cost (% of Price)",
        symbol: "M%",
        type: "number",
        helpText: "Material cost as a percentage of base price — determines commodity exposure weight",
        required: true,
        unitFamily: "percentage",
        defaultUnit: "%",
        allowedUnits: [{ unit: "%", label: "%" }],
        min: 0, max: 100,
      },
      {
        id: "target_margin_percent",
        label: "Target Margin (%)",
        symbol: "TM",
        type: "number",
        helpText: "Target profit margin percentage on the base price",
        required: true,
        unitFamily: "percentage",
        defaultUnit: "%",
        allowedUnits: [{ unit: "%", label: "%" }],
        min: 0, max: 100,
      },
    ],
  },
];
