// SectorCalc PRO V2 — Plant-Wide Shop Rate Cost Structure Audit Contract

import type { ProFieldGroup } from "../proFieldContract";

export const PLANT_WIDE_SHOP_RATE_GROUPS: ProFieldGroup[] = [
  {
    title: "Annual Cost & Hours",
    fields: [
      {
        id: "total_annual_cost",
        label: "Total Annual Cost",
        symbol: "TAC",
        type: "number",
        helpText: "Total annual manufacturing cost across all cost centers",
        required: true,
        unitFamily: "currency",
        defaultUnit: "USD",
        allowedUnits: [{ unit: "USD", label: "USD" }, { unit: "EUR", label: "EUR" }, { unit: "GBP", label: "GBP" }],
        min: 0.01, max: 1e9,
      },
      {
        id: "total_productive_hours",
        label: "Total Productive Hours",
        symbol: "H",
        type: "number",
        helpText: "Total annual productive machine/labor hours available",
        required: true,
        unitFamily: "time",
        defaultUnit: "h",
        allowedUnits: [{ unit: "h", label: "h" }, { unit: "day", label: "day" }],
        min: 1, max: 1e6,
      },
      {
        id: "machine_group_cost",
        label: "Machine Group Cost",
        symbol: "MGC",
        type: "number",
        helpText: "Cost allocated to specific machine group or work center",
        required: true,
        unitFamily: "currency",
        defaultUnit: "USD",
        allowedUnits: [{ unit: "USD", label: "USD" }, { unit: "EUR", label: "EUR" }, { unit: "GBP", label: "GBP" }],
        min: 0, max: 1e9,
      },
      {
        id: "machine_group_hours",
        label: "Machine Group Hours",
        symbol: "MGH",
        type: "number",
        helpText: "Hours attributed to the specific machine group",
        required: true,
        unitFamily: "time",
        defaultUnit: "h",
        allowedUnits: [{ unit: "h", label: "h" }, { unit: "day", label: "day" }],
        min: 0, max: 1e6,
      },
    ],
  },
  {
    title: "Overhead & Rate",
    fields: [
      {
        id: "overhead_pool",
        label: "Overhead Pool",
        symbol: "OHP",
        type: "number",
        helpText: "Total overhead cost pool to be allocated",
        required: true,
        unitFamily: "currency",
        defaultUnit: "USD",
        allowedUnits: [{ unit: "USD", label: "USD" }, { unit: "EUR", label: "EUR" }, { unit: "GBP", label: "GBP" }],
        min: 0, max: 1e9,
      },
      {
        id: "overhead_allocation_base",
        label: "Overhead Allocation Base",
        symbol: "OHB",
        type: "number",
        helpText: "Allocation base (e.g. direct labor hours) for overhead distribution",
        required: true,
        unitFamily: "time",
        defaultUnit: "h",
        allowedUnits: [{ unit: "h", label: "h" }, { unit: "day", label: "day" }],
        min: 0, max: 1e6,
      },
      {
        id: "current_shop_rate",
        label: "Current Shop Rate",
        symbol: "CSR",
        type: "number",
        helpText: "Currently billed shop rate charged to customers",
        required: true,
        unitFamily: "shop_rate",
        defaultUnit: "USD/hr",
        allowedUnits: [{ unit: "USD/hr", label: "USD/hr" }, { unit: "EUR/hr", label: "EUR/hr" }],
        min: 0, max: 1e6,
      },
      {
        id: "target_margin_pct",
        label: "Target Margin",
        symbol: "TM%",
        type: "number",
        helpText: "Target profit margin percentage above cost",
        required: true,
        unitFamily: "percentage",
        defaultUnit: "%",
        allowedUnits: [{ unit: "%", label: "%" }],
        min: 0, max: 99.9,
      },
      {
        id: "utilization_pct",
        label: "Utilization Rate",
        symbol: "U%",
        type: "number",
        helpText: "Actual capacity utilization percentage",
        required: true,
        unitFamily: "percentage",
        defaultUnit: "%",
        allowedUnits: [{ unit: "%", label: "%" }],
        min: 0, max: 100,
      },
    ],
  },
  {
    title: "Burden Breakdown",
    fields: [
      {
        id: "labor_burden",
        label: "Labor Burden",
        symbol: "LB",
        type: "number",
        helpText: "Total labor burden including fringe, payroll taxes, benefits",
        required: true,
        unitFamily: "currency",
        defaultUnit: "USD",
        allowedUnits: [{ unit: "USD", label: "USD" }, { unit: "EUR", label: "EUR" }, { unit: "GBP", label: "GBP" }],
        min: 0, max: 1e9,
      },
      {
        id: "facility_burden",
        label: "Facility Burden",
        symbol: "FB",
        type: "number",
        helpText: "Facility-related costs including rent, utilities, property tax",
        required: true,
        unitFamily: "currency",
        defaultUnit: "USD",
        allowedUnits: [{ unit: "USD", label: "USD" }, { unit: "EUR", label: "EUR" }, { unit: "GBP", label: "GBP" }],
        min: 0, max: 1e9,
      },
      {
        id: "maintenance_burden",
        label: "Maintenance Burden",
        symbol: "MB",
        type: "number",
        helpText: "Maintenance and repair costs for equipment and facility",
        required: true,
        unitFamily: "currency",
        defaultUnit: "USD",
        allowedUnits: [{ unit: "USD", label: "USD" }, { unit: "EUR", label: "EUR" }, { unit: "GBP", label: "GBP" }],
        min: 0, max: 1e9,
      },
      {
        id: "energy_burden",
        label: "Energy Burden",
        symbol: "EB",
        type: "number",
        helpText: "Energy costs including electricity, gas, compressed air",
        required: true,
        unitFamily: "currency",
        defaultUnit: "USD",
        allowedUnits: [{ unit: "USD", label: "USD" }, { unit: "EUR", label: "EUR" }, { unit: "GBP", label: "GBP" }],
        min: 0, max: 1e9,
      },
    ],
  },
];
