import type { ProFieldGroup } from "../proFieldContract";

export const SKU_MARGIN_RANKER_GROUPS: ProFieldGroup[] = [
  {
    title: "SKU Pricing & Cost",
    fields: [
      {
        id: "unit_price",
        label: "Unit Selling Price",
        symbol: "P",
        type: "number",
        helpText: "Selling price per unit",
        required: true,
        unitFamily: "currency",
        defaultUnit: "USD",
        allowedUnits: [{ unit: "USD", label: "USD" }],
        min: 0.01, max: 1e9,
      },
      {
        id: "material_cost_per_unit",
        label: "Material Cost per Unit",
        symbol: "M",
        type: "number",
        helpText: "Direct material cost per unit",
        required: true,
        unitFamily: "currency",
        defaultUnit: "USD",
        allowedUnits: [{ unit: "USD", label: "USD" }],
        min: 0, max: 1e9,
      },
      {
        id: "labor_cost_per_unit",
        label: "Labor Cost per Unit",
        symbol: "L",
        type: "number",
        helpText: "Direct labor cost per unit",
        required: true,
        unitFamily: "currency",
        defaultUnit: "USD",
        allowedUnits: [{ unit: "USD", label: "USD" }],
        min: 0, max: 1e9,
      },
      {
        id: "overhead_per_unit",
        label: "Overhead per Unit",
        symbol: "O",
        type: "number",
        helpText: "Allocated overhead per unit",
        required: true,
        unitFamily: "currency",
        defaultUnit: "USD",
        allowedUnits: [{ unit: "USD", label: "USD" }],
        min: 0, max: 1e9,
      },
      {
        id: "logistics_cost_per_unit",
        label: "Logistics Cost per Unit",
        symbol: "Log",
        type: "number",
        helpText: "Shipping, handling, warehousing per unit",
        required: true,
        unitFamily: "currency",
        defaultUnit: "USD",
        allowedUnits: [{ unit: "USD", label: "USD" }],
        min: 0, max: 1e9,
      },
    ],
  },
  {
    title: "Volume & Target",
    fields: [
      {
        id: "annual_volume_units",
        label: "Annual Volume (Units)",
        symbol: "V",
        type: "number",
        helpText: "Total units sold per year",
        required: true,
        unitFamily: "factor",
        defaultUnit: "units",
        allowedUnits: [{ unit: "units", label: "Units" }],
        min: 1, max: 1e9,
      },
      {
        id: "target_margin_percent",
        label: "Target Margin (%)",
        symbol: "TM",
        type: "number",
        helpText: "Target contribution margin percentage",
        required: true,
        unitFamily: "percentage",
        defaultUnit: "%",
        allowedUnits: [{ unit: "%", label: "%" }],
        min: 0, max: 100,
      },
    ],
  },
  {
    title: "Portfolio Context",
    fields: [
      {
        id: "total_portfolio_revenue",
        label: "Total Portfolio Revenue",
        symbol: "PR",
        type: "number",
        helpText: "Total revenue across all SKUs",
        required: true,
        unitFamily: "currency",
        defaultUnit: "USD",
        allowedUnits: [{ unit: "USD", label: "USD" }],
        min: 0, max: 1e12,
      },
      {
        id: "total_portfolio_profit",
        label: "Total Portfolio Profit",
        symbol: "PP",
        type: "number",
        helpText: "Total profit across all SKUs",
        required: true,
        unitFamily: "currency",
        defaultUnit: "USD",
        allowedUnits: [{ unit: "USD", label: "USD" }],
        min: 0, max: 1e12,
      },
    ],
  },
];
