import type { ProFieldGroup } from "../proFieldContract";

export const EMPLOYEE_COST_GROUPS: ProFieldGroup[] = [
  {
    title: "Base Compensation",
    fields: [
      {
        id: "annual_base_salary",
        label: "Annual Base Salary / Hourly Wage",
        symbol: "S",
        type: "number",
        helpText: "Annual gross salary. Enter hourly wage if below 1000 (e.g., 45 for $45/hr → auto-converted to annual)",
        required: true,
        unitFamily: "currency",
        defaultUnit: "USD",
        allowedUnits: [{ unit: "USD", label: "USD" }, { unit: "EUR", label: "EUR" }, { unit: "GBP", label: "GBP" }],
        min: 0, max: 1e7,
      },
      {
        id: "payroll_tax_rate",
        label: "Employer Payroll Tax Rate",
        symbol: "PTR",
        type: "number",
        helpText: "Employer portion of social security, medicare, unemployment taxes (default 22.5%)",
        required: false,
        unitFamily: "percentage",
        defaultUnit: "%",
        allowedUnits: [{ unit: "%", label: "%" }],
        min: 0, max: 60,
        defaultValue: 22.5,
      },
    ],
  },
  {
    title: "Benefits & Bonuses",
    fields: [
      {
        id: "health_insurance_annual",
        label: "Health Insurance (Annual)",
        symbol: "HI",
        type: "number",
        helpText: "Annual employer health insurance contribution per employee",
        required: false,
        unitFamily: "currency",
        defaultUnit: "USD",
        allowedUnits: [{ unit: "USD", label: "USD" }, { unit: "EUR", label: "EUR" }, { unit: "GBP", label: "GBP" }],
        min: 0, max: 1e6,
      },
      {
        id: "pension_contribution_rate",
        label: "Pension/401k Contribution Rate",
        symbol: "PCR",
        type: "number",
        helpText: "Employer pension or retirement contribution as % of salary",
        required: false,
        unitFamily: "percentage",
        defaultUnit: "%",
        allowedUnits: [{ unit: "%", label: "%" }],
        min: 0, max: 30,
      },
      {
        id: "bonus_target_rate",
        label: "Bonus Target Rate",
        symbol: "BTR",
        type: "number",
        helpText: "Target bonus as % of base salary",
        required: false,
        unitFamily: "percentage",
        defaultUnit: "%",
        allowedUnits: [{ unit: "%", label: "%" }],
        min: 0, max: 100,
      },
    ],
  },
  {
    title: "Leave, Training & Overhead",
    fields: [
      {
        id: "paid_leave_weeks",
        label: "Paid Leave (Weeks per Year)",
        symbol: "PLW",
        type: "number",
        helpText: "Number of paid vacation/sick leave weeks (default 4)",
        required: false,
        unitFamily: "factor",
        defaultUnit: "weeks",
        allowedUnits: [{ unit: "weeks", label: "weeks" }],
        min: 0, max: 12,
      },
      {
        id: "training_budget_annual",
        label: "Training Budget (Annual)",
        symbol: "TB",
        type: "number",
        helpText: "Annual training and development allocation per employee",
        required: false,
        unitFamily: "currency",
        defaultUnit: "USD",
        allowedUnits: [{ unit: "USD", label: "USD" }, { unit: "EUR", label: "EUR" }, { unit: "GBP", label: "GBP" }],
        min: 0, max: 1e6,
      },
      {
        id: "equipment_it_annual",
        label: "Equipment & IT (Annual)",
        symbol: "EIT",
        type: "number",
        helpText: "Annual laptop, software, phone, and IT support cost per employee",
        required: false,
        unitFamily: "currency",
        defaultUnit: "USD",
        allowedUnits: [{ unit: "USD", label: "USD" }, { unit: "EUR", label: "EUR" }, { unit: "GBP", label: "GBP" }],
        min: 0, max: 1e6,
      },
      {
        id: "workspace_facility_annual",
        label: "Workspace & Facility (Annual)",
        symbol: "WF",
        type: "number",
        helpText: "Annual office/workspace rent, utilities, and facility cost per employee",
        required: false,
        unitFamily: "currency",
        defaultUnit: "USD",
        allowedUnits: [{ unit: "USD", label: "USD" }, { unit: "EUR", label: "EUR" }, { unit: "GBP", label: "GBP" }],
        min: 0, max: 1e6,
      },
      {
        id: "recruitment_allocation_rate",
        label: "Recruitment & Retention Allocation",
        symbol: "RR",
        type: "number",
        helpText: "Annual recruitment and retention cost as % of salary",
        required: false,
        unitFamily: "percentage",
        defaultUnit: "%",
        allowedUnits: [{ unit: "%", label: "%" }],
        min: 0, max: 30,
      },
      {
        id: "other_benefits_annual",
        label: "Other Benefits (Annual)",
        symbol: "OB",
        type: "number",
        helpText: "Any other benefits not captured above (dental, vision, wellness, etc.)",
        required: false,
        unitFamily: "currency",
        defaultUnit: "USD",
        allowedUnits: [{ unit: "USD", label: "USD" }, { unit: "EUR", label: "EUR" }, { unit: "GBP", label: "GBP" }],
        min: 0, max: 1e6,
      },
      {
        id: "productive_hours_per_year",
        label: "Productive Hours per Year",
        symbol: "PH",
        type: "number",
        helpText: "Actual productive working hours per year (default 1664 = 2080 × 80%)",
        required: false,
        unitFamily: "time",
        defaultUnit: "hours",
        allowedUnits: [{ unit: "hours", label: "hours" }],
        min: 1, max: 8760,
      },
    ],
  },
];
