import { D, Decimal, CalcError } from '../core/engine.js';
import { ToolDefinition, CanonicalInput, numberValue as n, output as o, warning as w, decimalPi as PI } from './engine.js';

const positive = (x: Decimal, name: string): Decimal => { if (x.lte(0)) throw new CalcError('E_NON_POSITIVE', `${name} must be > 0`); return x; };
const nonNegative = (x: Decimal, name: string): Decimal => { if (x.lt(0)) throw new CalcError('E_NEGATIVE', `${name} must be >= 0`); return x; };

const SC033: ToolDefinition = {
  code:'SC-033', slug:'pressure-vessel-pro', name:'ASME VIII Cylindrical Shell — Internal Pressure', category:'Pressure Equipment & Piping', standard:'ASME Section VIII Div.1 UG-27 internal-pressure equations', engineVersion:'SC033-UEK-1.0.0',
  summary:'Sizes a cylindrical shell for internal pressure using circumferential and longitudinal UG-27 equations, corrosion allowance, mill tolerance and candidate-wall MAWP verification.', decision:'Select ordered wall thickness from a transparent code-equation path and reject candidates that fail after corrosion and negative mill tolerance.',
  fields:[
    {kind:'number',id:'pressure',label:'Design pressure',defaultValue:1.6,step:.1,family:'pressure',defaultUnit:'MPa',min:.001,max:100,reference:'Include required design margin and static head where applicable.'},
    {kind:'number',id:'id',label:'Inside diameter',defaultValue:1200,step:10,family:'length',defaultUnit:'mm',min:10,max:20000,reference:'Equation uses inside radius R = ID/2.'},
    {kind:'number',id:'allowable',label:'Allowable stress S',defaultValue:138,step:1,family:'pressure',defaultUnit:'MPa',min:1,max:1000,reference:'Use ASME allowable stress at design temperature for exact material/specification.'},
    {kind:'number',id:'jointEff',label:'Joint efficiency E',defaultValue:1,step:.05,family:'percent',defaultUnit:'ratio',min:.1,max:1,reference:'Per weld category / radiography requirements in the governing code edition.'},
    {kind:'number',id:'ca',label:'Corrosion allowance',defaultValue:3,step:.5,family:'length',defaultUnit:'mm',min:0,max:100,reference:'Owner/process corrosion allowance; separate from mill undertolerance.'},
    {kind:'number',id:'millTol',label:'Negative mill tolerance',defaultValue:12.5,step:.5,family:'percent',defaultUnit:'pct',min:0,max:.5,reference:'Typical plate/pipe procurement tolerance varies by product standard; enter actual requirement.'},
    {kind:'number',id:'candidate',label:'Candidate nominal wall',defaultValue:16,step:.5,family:'length',defaultUnit:'mm',min:.1,max:500,reference:'Nominal ordered thickness to verify after mill tolerance and corrosion.'},
    {kind:'number',id:'temp',label:'Design temperature',defaultValue:200,step:10,family:'temperature',defaultUnit:'C',min:-200,max:800,reference:'Used for audit context; allowable stress must already correspond to this temperature.'}
  ],
  formulas:['R = ID/2','t_hoop = P·R/(S·E − 0.6P)','t_long = P·R/(2S·E + 0.4P)','t_required = max(t_hoop,t_long)','t_ordered = (t_required + CA)/(1 − millTol)','candidate net t = candidate·(1−millTol) − CA','MAWP_hoop = S·E·t/(R+0.6t); MAWP_long = 2S·E·t/(R−0.4t)'],
  assumptions:['Internal pressure only; external pressure/vacuum buckling requires UG-28 chart-based evaluation and is intentionally not approximated.','Allowable stress S and weld efficiency E are user-supplied code values for the exact material, temperature, weld category and examination.','Nozzle openings, local loads, heads, fatigue, brittle fracture and test pressure are separate checks.'], sensitivity:{inputId:'pressure',outputId:'ordered',spanPct:20},
  calculate(input:CanonicalInput){
    const P=positive(n(input,'pressure'),'pressure'), ID=positive(n(input,'id'),'id'), S=positive(n(input,'allowable'),'allowable'), E=positive(n(input,'jointEff'),'jointEff'), ca=nonNegative(n(input,'ca'),'ca'), mt=n(input,'millTol'), cand=positive(n(input,'candidate'),'candidate'); if(mt.gte(1)) throw new CalcError('E_OUT_OF_RANGE','mill tolerance must be < 100%');
    const R=ID.div(2), denH=S.times(E).minus(P.times('.6')), denL=S.times(E).times(2).plus(P.times('.4')); if(denH.lte(0)||denL.lte(0)) throw new CalcError('E_DOMAIN','pressure exceeds valid denominator for UG-27 equation');
    const th=P.times(R).div(denH), tl=P.times(R).div(denL), req=Decimal.max(th,tl), ordered=req.plus(ca).div(D(1).minus(mt)); const net=cand.times(D(1).minus(mt)).minus(ca); const warns=[];
    if(net.lte(0)) warns.push(w('error','No remaining structural wall','Candidate wall is consumed by corrosion allowance / mill tolerance.'));
    const mawpH=net.gt(0)?S.times(E).times(net).div(R.plus(net.times('.6'))):D(0); const mawpL=net.gt(0)?S.times(E).times(2).times(net).div(R.minus(net.times('.4'))):D(0); const mawp=Decimal.min(mawpH,mawpL); const util=P.div(mawp.gt(0)?mawp:D('1e-30'));
    if(cand.lt(ordered)) warns.push(w('error','Candidate wall below required ordered thickness',`Candidate ${cand.toFixed(2)} mm < required ${ordered.toFixed(2)} mm.`)); else if(cand.lt(ordered.times(1.1))) warns.push(w('warning','Thickness reserve below 10%',`Candidate is only ${cand.div(ordered).minus(1).times(100).toFixed(1)}% above required nominal.`)); if(ID.div(cand).lt(10)) warns.push(w('warning','Thick-wall region','D/t < 10; verify whether UG-27 thin-shell equation applicability and geometry details remain appropriate.'));
    return {outputs:[o('ordered','Required nominal ordered wall',ordered,'mm',3,'Includes CA and negative mill tolerance',true,ordered.div(cand)),o('hoop','Pressure wall — hoop criterion',th,'mm',3),o('long','Pressure wall — longitudinal criterion',tl,'mm',3),o('netCandidate','Candidate net structural wall',net,'mm',3),o('mawp','Candidate MAWP',mawp,'MPa',3,true,util),o('util','Pressure / candidate MAWP',util.times(100),'%',1,true,util)],warnings:warns,formulas:this.formulas,assumptions:this.assumptions};
  }
};

const SC034: ToolDefinition = {
  code:'SC-034', slug:'pipe-wall-pro', name:'ASME B31.3 Pipe Wall Thickness / MAWP', category:'Pressure Equipment & Piping', standard:'ASME B31.3 straight-pipe internal-pressure equation', engineVersion:'SC034-UEK-1.0.0',
  summary:'Computes pressure design thickness, corrosion allowance, negative mill tolerance, required nominal wall and reverse MAWP for a candidate pipe wall.', decision:'Check whether a candidate schedule/wall survives pressure after code factors, corrosion and manufacturing undertolerance.',
  fields:[
    {kind:'number',id:'pressure',label:'Design pressure P',defaultValue:4,step:.1,family:'pressure',defaultUnit:'MPa',min:.001,max:200,reference:'Use design pressure including static head where required.'},
    {kind:'number',id:'od',label:'Pipe outside diameter D',defaultValue:168.3,step:.1,family:'length',defaultUnit:'mm',min:5,max:5000,reference:'Actual code outside diameter for the selected NPS/OD series.'},
    {kind:'number',id:'S',label:'Allowable stress S',defaultValue:120,step:1,family:'pressure',defaultUnit:'MPa',min:1,max:1000,reference:'Code allowable stress at design temperature.'},
    {kind:'number',id:'E',label:'Longitudinal weld factor E',defaultValue:1,step:.05,family:'percent',defaultUnit:'ratio',min:.1,max:1,reference:'Seam quality factor per material/product specification.'},
    {kind:'number',id:'W',label:'Weld strength reduction W',defaultValue:1,step:.05,family:'percent',defaultUnit:'ratio',min:.1,max:1,reference:'High-temperature weld strength reduction factor where applicable.'},
    {kind:'number',id:'Y',label:'Coefficient Y',defaultValue:.4,step:.05,family:'percent',defaultUnit:'ratio',min:0,max:1,reference:'Coefficient from B31.3 material/temperature table; commonly 0.4 for many steels in ordinary range.'},
    {kind:'number',id:'ca',label:'Corrosion / mechanical allowance',defaultValue:3,step:.5,family:'length',defaultUnit:'mm',min:0,max:100,reference:'Include corrosion, erosion, threading/grooving allowance as applicable.'},
    {kind:'number',id:'millTol',label:'Negative mill tolerance',defaultValue:12.5,step:.5,family:'percent',defaultUnit:'pct',min:0,max:.5,reference:'Enter product-standard undertolerance; 12.5% is common for some pipe products but not universal.'},
    {kind:'number',id:'candidate',label:'Candidate nominal wall',defaultValue:10.97,step:.1,family:'length',defaultUnit:'mm',min:.1,max:500,reference:'Actual nominal schedule wall to verify.'}
  ],
  formulas:['t = P·D/[2(S·E·W + P·Y)]','t_ordered = (t + CA)/(1−millTol)','t_net = candidate·(1−millTol) − CA','MAWP = 2S·E·W·t_net/(D − 2Y·t_net)'],
  assumptions:['Straight pipe under internal pressure; bends, branch reinforcement, external pressure, occasional loads and flexibility stresses are separate code checks.','Equation use is limited to the code applicability region; D/t and material-temperature limits must be checked against the governing edition.','S, E, W and Y are explicit user inputs to avoid hidden material assumptions.'], sensitivity:{inputId:'pressure',outputId:'ordered',spanPct:20},
  calculate(input){
    const P=positive(n(input,'pressure'),'pressure'), Dd=positive(n(input,'od'),'od'), S=positive(n(input,'S'),'S'), E=positive(n(input,'E'),'E'), W=positive(n(input,'W'),'W'), Y=nonNegative(n(input,'Y'),'Y'), ca=nonNegative(n(input,'ca'),'ca'), mt=n(input,'millTol'), cand=positive(n(input,'candidate'),'candidate'); if(mt.gte(1)) throw new CalcError('E_OUT_OF_RANGE','mill tolerance must be <1');
    const t=P.times(Dd).div(D(2).times(S.times(E).times(W).plus(P.times(Y)))); const ordered=t.plus(ca).div(D(1).minus(mt)); const net=cand.times(D(1).minus(mt)).minus(ca); const warns=[]; if(net.lte(0)) warns.push(w('error','Candidate net wall non-positive','Corrosion allowance and mill tolerance consume the candidate wall.'));
    const den=Dd.minus(Y.times(net).times(2)); const mawp=net.gt(0)&&den.gt(0)?S.times(E).times(W).times(net).times(2).div(den):D(0); const util=P.div(mawp.gt(0)?mawp:D('1e-30')); if(cand.lt(ordered)) warns.push(w('error','Candidate wall fails pressure design',`Candidate ${cand.toFixed(3)} mm < required nominal ${ordered.toFixed(3)} mm.`)); if(t.gt(Dd.div(6))) warns.push(w('error','Equation applicability exceeded','Pressure design thickness exceeds D/6; use the code thick-wall provisions rather than this equation.')); if(util.gt(.9)&&util.lte(1)) warns.push(w('warning','MAWP reserve below 10%',`Pressure utilization ${util.times(100).toFixed(1)}%.`));
    return {outputs:[o('ordered','Required nominal wall',ordered,'mm',3,true,ordered.div(cand)),o('pressureWall','Pressure design thickness t',t,'mm',3),o('netCandidate','Candidate net wall',net,'mm',3),o('mawp','Candidate MAWP',mawp,'MPa',3,true,util),o('util','Pressure utilization',util.times(100),'%',1,true,util),o('Dt','D / candidate t',Dd.div(cand),'—',2)],warnings:warns,formulas:this.formulas,assumptions:this.assumptions};
  }
};

const SC036: ToolDefinition = {
  code:'SC-036', slug:'bolted-joint-pro', name:'Bolted Joint Verification — Preload / Separation / Fatigue', category:'Fasteners & Bolted Joints', standard:'VDI 2230-style stiffness load sharing with proof and clamp-reserve checks', engineVersion:'SC036-UEK-1.0.0',
  summary:'Verifies bolt tensile area, assembly preload scatter, bolt/joint stiffness sharing, external-load amplification, clamp reserve, proof utilization and fatigue stress amplitude.', decision:'Detect joints that appear torque-tight but separate, overload the bolt at peak load or lack fatigue reserve.',
  fields:[
    {kind:'number',id:'d',label:'Nominal bolt diameter',defaultValue:12,step:.1,family:'length',defaultUnit:'mm',min:1,max:200,reference:'Metric thread nominal diameter.'},
    {kind:'number',id:'pitch',label:'Thread pitch',defaultValue:1.75,step:.05,family:'length',defaultUnit:'mm',min:.1,max:20,reference:'Metric coarse M12 pitch = 1.75 mm.'},
    {kind:'number',id:'proof',label:'Proof / allowable assembly stress',defaultValue:600,step:10,family:'pressure',defaultUnit:'MPa',min:50,max:2000,reference:'Use fastener property-class proof stress / approved assembly limit.'},
    {kind:'number',id:'preload',label:'Target assembly preload',defaultValue:45,step:1,family:'force',defaultUnit:'kN',min:.1,max:10000000,reference:'Target clamp load after tightening, before embedment loss.'},
    {kind:'number',id:'scatter',label:'Tightening scatter ±',defaultValue:15,step:1,family:'percent',defaultUnit:'pct',min:0,max:.8,reference:'Torque tightening often has wide scatter; controlled tensioning is lower.'},
    {kind:'number',id:'embedLoss',label:'Embedment / relaxation loss',defaultValue:4,step:.5,family:'force',defaultUnit:'kN',min:0,max:10000000,reference:'Expected preload loss from surface settlement, gasket relaxation, coating creep.'},
    {kind:'number',id:'external',label:'Maximum external axial joint load',defaultValue:30,step:1,family:'force',defaultUnit:'kN',min:0,max:10000000,reference:'Separating external load carried by the joint.'},
    {kind:'number',id:'loadRange',label:'External axial load range ΔF',defaultValue:20,step:1,family:'force',defaultUnit:'kN',min:0,max:10000000,reference:'Peak-to-peak cyclic external load range for fatigue screening.'},
    {kind:'number',id:'cb',label:'Bolt stiffness cb',defaultValue:250,step:10,family:'stiffness',defaultUnit:'Nmm',min:.1,max:1000000,reference:'Axial bolt stiffness from grip/thread geometry or FE model.'},
    {kind:'number',id:'cj',label:'Joint stiffness cj',defaultValue:800,step:10,family:'stiffness',defaultUnit:'Nmm',min:.1,max:1000000,reference:'Compressed member stiffness. Do not assume infinitely rigid joint.'},
    {kind:'number',id:'fatigueAllow',label:'Allowable alternating thread stress',defaultValue:50,step:5,family:'pressure',defaultUnit:'MPa',min:1,max:1000,reference:'Screening allowable; exact VDI fatigue verification depends on thread size, rolling, mean stress and surface treatment.'},
    {kind:'number',id:'nutFactor',label:'Nut factor K for torque estimate',defaultValue:.20,step:.01,family:'percent',defaultUnit:'ratio',min:.05,max:.5,reference:'Torque estimate T≈K·F·d is highly friction-sensitive; use measured torque-tension data where critical.'}
  ],
  formulas:['As ≈ π/4·(d−0.9382p)²','Φ = cb/(cb+cj)','Fpre,min = Fpre·(1−scatter) − embedLoss','Fpre,max = Fpre·(1+scatter)','Fbolt,max = Fpre,max + Φ·Fext','Fclamp,min = Fpre,min − (1−Φ)·Fext','σproof = Fbolt,max/As','σa = Φ·ΔF/(2As)','Tassembly ≈ K·Fpre·d'],
  assumptions:['Single-bolt axial joint with linear stiffness; eccentric loading, prying and transverse shear are separate checks.','Fatigue allowable is an explicit screening input, not a hidden VDI table lookup.','Torque estimate is informational because friction dominates torque-to-preload scatter.'], sensitivity:{inputId:'preload',outputId:'clampMin',spanPct:20},
  calculate(input){
    const d=positive(n(input,'d'),'d'), p=positive(n(input,'pitch'),'pitch'), proof=positive(n(input,'proof'),'proof'), preload=positive(n(input,'preload'),'preload'), scatter=n(input,'scatter'), loss=nonNegative(n(input,'embedLoss'),'embedLoss'), ext=nonNegative(n(input,'external'),'external'), range=nonNegative(n(input,'loadRange'),'loadRange'), cb=positive(n(input,'cb'),'cb'), cj=positive(n(input,'cj'),'cj'), fat=positive(n(input,'fatigueAllow'),'fatigueAllow'), K=positive(n(input,'nutFactor'),'nutFactor');
    const core=d.minus(p.times('.9382')); if(core.lte(0)) throw new CalcError('E_DOMAIN','thread tensile diameter is non-positive'); const As=PI().div(4).times(core.pow(2)), phi=cb.div(cb.plus(cj)), pmin=preload.times(D(1).minus(scatter)).minus(loss), pmax=preload.times(D(1).plus(scatter)), boltMax=pmax.plus(phi.times(ext)), clampMin=pmin.minus(D(1).minus(phi).times(ext)), proofStress=boltMax.div(As), proofUtil=proofStress.div(proof), altStress=phi.times(range).div(2).div(As), fatUtil=altStress.div(fat), torque=K.times(preload).times(d).div(1000); const warns=[];
    if(pmin.lte(0)) warns.push(w('error','Minimum preload collapses','Scatter and embedment loss can eliminate clamp load before service load is applied.')); if(clampMin.lte(0)) warns.push(w('error','Joint separation predicted',`Minimum clamp reserve ${clampMin.toFixed(1)} N ≤ 0.`)); else if(clampMin.lt(preload.times(.2))) warns.push(w('warning','Low clamp reserve','Remaining clamp force is below 20% of target preload.')); if(proofUtil.gt(1)) warns.push(w('error','Bolt proof stress exceeded',`Peak proof utilization ${proofUtil.times(100).toFixed(1)}%.`)); if(fatUtil.gt(1)) warns.push(w('error','Fatigue screening limit exceeded',`Alternating thread stress ${altStress.toFixed(1)} MPa > entered allowable ${fat.toFixed(1)} MPa.`)); else if(fatUtil.gt(.75)) warns.push(w('warning','Fatigue reserve below 25%',`Fatigue utilization ${fatUtil.times(100).toFixed(1)}%.`));
    return {outputs:[o('As','Thread tensile stress area',As,'mm²',2),o('phi','Bolt load fraction Φ',phi,'—',4),o('preMin','Minimum residual preload before service load',pmin,'N',1),o('boltMax','Maximum bolt load',boltMax,'N',1,true,proofUtil),o('clampMin','Minimum clamp reserve',clampMin,'N',1,true,clampMin.lte(0)?D(2):preload.times(.2).div(clampMin)),o('proofUtil','Proof utilization',proofUtil.times(100),'%',1,true,proofUtil),o('altStress','Alternating thread stress',altStress,'MPa',2,true,fatUtil),o('fatigueUtil','Fatigue utilization',fatUtil.times(100),'%',1,true,fatUtil),o('torque','Assembly torque estimate',torque,'N·m',1,'Friction-sensitive information only')],warnings:warns,formulas:this.formulas,assumptions:this.assumptions};
  }
};

const SC037: ToolDefinition = {
  code:'SC-037', slug:'oee-pro', name:'OEE / TEEP / Capacity Loss Decomposition', category:'Costing & Business', standard:'TPM OEE identity: Availability × Performance × Quality', engineVersion:'SC037-UEK-1.0.0',
  summary:'Calculates OEE, TEEP, effective output rate and separates downtime, speed and quality losses while guarding against impossible performance >100% caused by stale ideal-cycle assumptions.', decision:'Quantify which loss bucket is consuming productive capacity before buying more equipment or adding shifts.',
  fields:[
    {kind:'number',id:'calendar',label:'Calendar time in period',defaultValue:24,step:1,family:'time',defaultUnit:'h',min:1,max:31536000,reference:'Total elapsed period used for TEEP denominator.'},
    {kind:'number',id:'planned',label:'Planned production time',defaultValue:16,step:.5,family:'time',defaultUnit:'h',min:1,max:31536000,reference:'Scheduled production time excluding planned non-production.'},
    {kind:'number',id:'downtime',label:'Unplanned + counted downtime',defaultValue:2,step:.1,family:'time',defaultUnit:'h',min:0,max:31536000,reference:'Breakdowns, changeovers if counted as availability loss, waiting and stops per your OEE policy.'},
    {kind:'number',id:'idealCycle',label:'Ideal cycle time / part',defaultValue:30,step:1,family:'time',defaultUnit:'s',min:.001,max:86400,reference:'Best demonstrated sustainable cycle for one total part.'},
    {kind:'number',id:'totalCount',label:'Total count',defaultValue:1500,step:1,family:'count',defaultUnit:'count',min:1,max:1000000000,reference:'All produced units, good + reject.'},
    {kind:'number',id:'goodCount',label:'Good count',defaultValue:1450,step:1,family:'count',defaultUnit:'count',min:0,max:1000000000,reference:'Conforming output without unrecoverable rework.'},
    {kind:'number',id:'target',label:'OEE target',defaultValue:85,step:1,family:'percent',defaultUnit:'pct',min:.05,max:1,reference:'85% is a common benchmark, not a universal economic optimum.'}
  ],
  formulas:['Run time = planned − downtime','Availability = run/planned','Performance = idealCycle·totalCount/runTime','Quality = goodCount/totalCount','OEE = A·P·Q','Loading = planned/calendar','TEEP = Loading·OEE','Good theoretical capacity = runTime/idealCycle·Quality'],
  assumptions:['Ideal cycle is the best demonstrated sustainable rate and excludes planned losses.','Loss categorization must be consistent across periods; moving changeover between planned and downtime changes A without changing physical output.','OEE is a capacity diagnostic, not a profitability metric.'], sensitivity:{inputId:'downtime',outputId:'oee',spanPct:40},
  calculate(input){
    const cal=positive(n(input,'calendar'),'calendar'), planned=positive(n(input,'planned'),'planned'), down=nonNegative(n(input,'downtime'),'downtime'), ideal=positive(n(input,'idealCycle'),'idealCycle'), total=positive(n(input,'totalCount'),'totalCount'), good=nonNegative(n(input,'goodCount'),'goodCount'), target=positive(n(input,'target'),'target'); if(planned.gt(cal)) throw new CalcError('E_OUT_OF_RANGE','planned production time cannot exceed calendar time'); if(down.gte(planned)) throw new CalcError('E_OUT_OF_RANGE','downtime must be less than planned time'); if(good.gt(total)) throw new CalcError('E_CONSERVATION','good count cannot exceed total count');
    const run=planned.minus(down), A=run.div(planned), P=ideal.times(total).div(run), Q=good.div(total), oee=A.times(P).times(Q), loading=planned.div(cal), teep=loading.times(oee), warns=[]; if(P.gt(1.05)) warns.push(w('error','Performance above 105%','Ideal cycle time is stale/incorrect or count/time basis is inconsistent.')); else if(P.gt(1)) warns.push(w('warning','Performance above 100%','Review ideal cycle definition before using OEE for decisions.')); if(oee.lt(target)) warns.push(w('warning','OEE below target',`OEE ${oee.times(100).toFixed(1)}% < target ${target.times(100).toFixed(1)}%.`));
    const availabilityLoss=planned.times(D(1).minus(A)), speedLoss=run.times(D(1).minus(Decimal.min(P,D(1)))), qualityLoss=ideal.times(total.minus(good));
    return {outputs:[o('availability','Availability',A.times(100),'%',1,true,D(1).minus(A)),o('performance','Performance',P.times(100),'%',1,true,P.gt(1)?P.minus(1):D(1).minus(P)),o('quality','Quality',Q.times(100),'%',1,true,D(1).minus(Q)),o('oee','OEE',oee.times(100),'%',1,'A × P × Q',true,target.div(oee.gt(0)?oee:D('1e-30'))),o('teep','TEEP',teep.times(100),'%',1),o('availabilityLoss','Availability loss time',availabilityLoss,'s',1),o('speedLoss','Speed-loss equivalent time',speedLoss,'s',1),o('qualityLoss','Quality-loss ideal time',qualityLoss,'s',1)],warnings:warns,formulas:this.formulas,assumptions:this.assumptions};
  }
};

const SC038: ToolDefinition = {
  code:'SC-038', slug:'machine-hour-rate-pro', name:'True Machine Hour Rate / Capacity Economics', category:'Costing & Business', standard:'Full-cost capacity allocation with productive-hour denominator', engineVersion:'SC038-UEK-1.0.0',
  summary:'Builds a machine-hour cost from depreciation, capital charge, maintenance, insurance/floor, energy, labor, tooling and productive capacity after availability/performance losses.', decision:'Quote from the cost of a productive machine hour rather than scheduled hours, exposing the margin penalty of low utilization and downtime.',
  fields:[
    {kind:'number',id:'purchase',label:'Machine + installation cost',defaultValue:250000,step:1000,family:'currency',defaultUnit:'cur',min:0,max:1000000000,reference:'Installed acquisition cost including commissioning and required tooling base.'},
    {kind:'number',id:'salvage',label:'Residual / salvage value',defaultValue:25000,step:1000,family:'currency',defaultUnit:'cur',min:0,max:1000000000,reference:'Expected disposal value in same currency basis.'},
    {kind:'number',id:'lifeYears',label:'Economic life',defaultValue:10,step:.5,family:'count',defaultUnit:'count',min:.5,max:50,reference:'Economic cost life, not necessarily tax depreciation life.'},
    {kind:'number',id:'interest',label:'Annual cost of capital',defaultValue:10,step:.5,family:'percent',defaultUnit:'pct',min:0,max:1,reference:'Required annual financing/opportunity cost applied to average tied capital.'},
    {kind:'number',id:'maintenance',label:'Annual maintenance as % purchase',defaultValue:4,step:.5,family:'percent',defaultUnit:'pct',min:0,max:1,reference:'Preventive + corrective maintenance budget excluding operator labor if entered separately.'},
    {kind:'number',id:'insuranceFloor',label:'Annual insurance + floor + compliance',defaultValue:12000,step:500,family:'currency',defaultUnit:'cur',min:0,max:1000000000,reference:'Allocated annual fixed site cost attributable to the machine.'},
    {kind:'number',id:'power',label:'Rated spindle/process power',defaultValue:22,step:.5,family:'power',defaultUnit:'kW',min:0,max:10000,reference:'Electrical load basis; use measured whole-machine demand where available.'},
    {kind:'number',id:'loadFactor',label:'Average electrical load factor',defaultValue:60,step:5,family:'percent',defaultUnit:'pct',min:0,max:1,reference:'Average kW / rated kW during productive operation.'},
    {kind:'number',id:'energyRate',label:'Electricity rate',defaultValue:.18,step:.01,family:'currencyPerEnergy',defaultUnit:'curkwh',min:0,max:10000,reference:'Delivered energy tariff including demand/fees if allocated per kWh.'},
    {kind:'number',id:'operator',label:'Loaded operator cost',defaultValue:32,step:1,family:'currencyPerHour',defaultUnit:'curh',min:0,max:100000,reference:'True loaded labor rate, not wage.'},
    {kind:'number',id:'laborAttendance',label:'Operator attendance',defaultValue:70,step:5,family:'percent',defaultUnit:'pct',min:0,max:1,reference:'1.0 dedicated operator; lower for multi-machine tending.'},
    {kind:'number',id:'tooling',label:'Tooling + consumables / productive hour',defaultValue:12,step:1,family:'currencyPerHour',defaultUnit:'curh',min:0,max:100000,reference:'Expected inserts, cutters, coolant, filters and consumables.'},
    {kind:'number',id:'scheduledHours',label:'Scheduled machine hours / year',defaultValue:4000,step:100,family:'time',defaultUnit:'h',min:1,max:31536000,reference:'Planned annual machine availability before downtime/performance loss.'},
    {kind:'number',id:'availability',label:'Availability',defaultValue:85,step:1,family:'percent',defaultUnit:'pct',min:.05,max:1,reference:'Run time / scheduled production time.'},
    {kind:'number',id:'performance',label:'Performance',defaultValue:90,step:1,family:'percent',defaultUnit:'pct',min:.05,max:1.2,reference:'Effective productive speed vs ideal.'},
    {kind:'number',id:'targetMargin',label:'Target gross margin on machine time',defaultValue:25,step:1,family:'percent',defaultUnit:'pct',min:0,max:.95,reference:'Selling-rate margin, not markup: price = cost/(1−margin).'}
  ],
  formulas:['Annual depreciation = (purchase−salvage)/life','Capital charge = ((purchase+salvage)/2)·interest','Annual maintenance = purchase·maintenanceRate','Productive hours = scheduledHours·availability·performance','Fixed cost/hour = annual fixed cost/productive hours','Variable cost/hour = power·loadFactor·energyRate + operator·attendance + tooling','True machine hour = fixed/hour + variable/hour','Quote rate = trueRate/(1−targetMargin)'],
  assumptions:['Straight-line economic depreciation and average-capital interest model.','Availability/performance losses reduce the productive-hour denominator; hiding them in scheduled hours understates cost.','Taxes, financing structure, tooling amortization and site overhead can be added to the explicit fixed/variable inputs as appropriate.'], sensitivity:{inputId:'availability',outputId:'trueRate',spanPct:20},
  calculate(input){
    const purchase=nonNegative(n(input,'purchase'),'purchase'), salvage=nonNegative(n(input,'salvage'),'salvage'), life=positive(n(input,'lifeYears'),'lifeYears'), interest=nonNegative(n(input,'interest'),'interest'), maint=nonNegative(n(input,'maintenance'),'maintenance'), ins=nonNegative(n(input,'insuranceFloor'),'insuranceFloor'), power=nonNegative(n(input,'power'),'power'), load=nonNegative(n(input,'loadFactor'),'loadFactor'), er=nonNegative(n(input,'energyRate'),'energyRate'), op=nonNegative(n(input,'operator'),'operator'), attend=nonNegative(n(input,'laborAttendance'),'laborAttendance'), tooling=nonNegative(n(input,'tooling'),'tooling'), schedSec=positive(n(input,'scheduledHours'),'scheduledHours'), A=positive(n(input,'availability'),'availability'), P=positive(n(input,'performance'),'performance'), margin=n(input,'targetMargin'); if(salvage.gt(purchase)) throw new CalcError('E_CONSERVATION','salvage cannot exceed purchase cost'); if(margin.gte(1)) throw new CalcError('E_OUT_OF_RANGE','margin must be <1');
    const schedH=schedSec.div(3600), dep=purchase.minus(salvage).div(life), capital=purchase.plus(salvage).div(2).times(interest), maintenance=purchase.times(maint), annualFixed=dep.plus(capital).plus(maintenance).plus(ins), productiveH=schedH.times(A).times(P), fixedHr=annualFixed.div(productiveH), energyHr=power.times(load).times(er), laborHr=op.times(attend), variable=energyHr.plus(laborHr).plus(tooling), trueRate=fixedHr.plus(variable), quote=trueRate.div(D(1).minus(margin)), scheduledRate=annualFixed.div(schedH).plus(variable), hidden=trueRate.minus(scheduledRate); const warns=[];
    if(A.times(P).lt(.6)) warns.push(w('warning','Low productive utilization','Availability × performance below 60% makes fixed-cost absorption the dominant rate driver.')); if(P.gt(1.05)) warns.push(w('warning','Performance above 105%','Re-baseline ideal rate before using productive hours for costing.')); if(hidden.div(trueRate).gt(.2)) warns.push(w('warning','Scheduled-hour costing would understate >20%',`Ignoring capacity losses would understate machine rate by ${hidden.div(trueRate).times(100).toFixed(1)}%.`));
    return {outputs:[o('productiveHours','Productive machine hours / year',productiveH,'h/y',1),o('annualFixed','Annual fixed ownership cost',annualFixed,'currency/y',2),o('fixedHr','Fixed cost / productive hour',fixedHr,'currency/h',2),o('variableHr','Variable cost / productive hour',variable,'currency/h',2),o('trueRate','True machine-hour cost',trueRate,'currency/h',2,true),o('quoteRate','Recommended sell rate at target margin',quote,'currency/h',2,true),o('scheduledRate','Misleading scheduled-hour rate',scheduledRate,'currency/h',2),o('hiddenRate','Under-recovery if scheduled hours used',hidden,'currency/h',2,true,hidden.div(trueRate))],warnings:warns,formulas:this.formulas,assumptions:this.assumptions};
  }
};

export const PROCESS_TOOLS: readonly ToolDefinition[] = [SC033,SC034,SC036,SC037,SC038];
