// ⚡ AUTO-GENERATED — DO NOT EDIT
// Generated by: npx tsx scripts/generate-free-v531-static-registry.ts
// Imports a single bundled JSON to prevent webpack tree-shaking.
// Generated on: 2026-07-07

import type { SuperV4Schema } from "@/sectorcalc/pro-form/contract-types";
import ALL_SCHEMAS from "./bundled/all.json";

type SchemaType = SuperV4Schema;
type SchemaBundle = Record<string, SchemaType>;

const _BUNDLE = ALL_SCHEMAS as unknown as SchemaBundle;
const _L = Object.keys(_BUNDLE);

/** Sorted list of all Free V5.3.1 schema slugs. */
export const FREE_V531_SCHEMA_SLUGS: readonly string[] = ["beam-load-deflection-quick-check","bolt-preload-clamp-force","bolt-torque","break-even-point","carbon-price-exposure","cbam-cost-quick-estimator","cnc-shop-hourly-rate","compressed-air-leak-cost","concrete-volume-order-quantity","currency-adjusted-pricing","customer-profitability","cutting-speed-feed-rpm","diesel-fuel-co2-emissions","downtime-cost","electric-motor-running-cost","electricity-co2-emissions","energy-cost-per-part","eoq","fabric-consumption-gsm","fillet-weld-size-strength","freight-cost-per-km-trip","inventory-carrying-cost","iso-286-tolerance-fit","knurling-drill-point-depth","line-balancing-efficiency","machine-investment-payback","machining-cost-per-part","material-removal-rate","oee","pallet-container-load-cbm","payment-term-cost","product-carbon-footprint-basic","quote-margin-markup","rebar-weight-count","recipe-cost-menu-price","rework-vs-scrap-decision","safety-stock-reorder-point","scrap-cost","setup-time-cost","sheet-metal-bend-allowance","steel-weight","surface-roughness-converter","takt-time-cycle-time","tap-drill-size","thread-dimensions-reference","tool-life-tool-cost-per-part","true-employee-cost","weld-metal-weight-consumable","welding-cost-per-meter","welding-heat-input"] as const;

/** Resolve a Free V5.3.1 schema by slug. */
export function getFreeV531SchemaBySlug(slug: string): SchemaType | undefined {
  return _BUNDLE[slug];
}

/** Check if a Free V5.3.1 schema exists for the given slug. */
export function hasFreeV531Schema(slug: string): boolean {
  return slug in _BUNDLE;
}
