// SectorCalc PRO V2 — Job Quote Builder Presets

import type { ProPreset } from "../proToolRegistry";

export const QUOTE_BUILDER_PRESETS: ProPreset[] = [
  {
    label: "Small CNC Batch (500 units)",
    values: {
      batch_quantity: "500",
      cycle_time_seconds_per_unit: "720",
      setup_time_minutes_per_batch: "8",
      annual_volume_units: "100000",
      material_cost_per_unit: "25",
      machine_rate_per_hour: "85",
      labor_rate_per_hour: "45",
      operator_count: "1",
      annual_unallocated_overhead: "350000",
      scrap_rework_percent: "5",
      target_revenue_margin_percent: "30",
      tooling_consumables_cost_per_batch: "150",
      packaging_cost_per_batch: "50",
      contingency_percent: "3",
    },
    units: {
      batch_quantity: "units",
      cycle_time_seconds_per_unit: "sec",
      setup_time_minutes_per_batch: "min",
      annual_volume_units: "units",
      material_cost_per_unit: "USD",
      machine_rate_per_hour: "USD/h",
      labor_rate_per_hour: "USD/h",
      operator_count: "count",
      annual_unallocated_overhead: "USD",
      scrap_rework_percent: "%",
      target_revenue_margin_percent: "%",
      tooling_consumables_cost_per_batch: "USD",
      packaging_cost_per_batch: "USD",
      contingency_percent: "%",
    },
  },
  {
    label: "Medium Production Order (2000 units)",
    values: {
      batch_quantity: "2000",
      cycle_time_seconds_per_unit: "180",
      setup_time_minutes_per_batch: "15",
      annual_volume_units: "250000",
      material_cost_per_unit: "12",
      machine_rate_per_hour: "120",
      labor_rate_per_hour: "55",
      operator_count: "2",
      annual_unallocated_overhead: "800000",
      scrap_rework_percent: "3",
      target_revenue_margin_percent: "25",
      tooling_consumables_cost_per_batch: "400",
      packaging_cost_per_batch: "200",
      freight_cost_per_batch: "350",
      contingency_percent: "5",
    },
    units: {
      batch_quantity: "units",
      cycle_time_seconds_per_unit: "sec",
      setup_time_minutes_per_batch: "min",
      annual_volume_units: "units",
      material_cost_per_unit: "USD",
      machine_rate_per_hour: "USD/h",
      labor_rate_per_hour: "USD/h",
      operator_count: "count",
      annual_unallocated_overhead: "USD",
      scrap_rework_percent: "%",
      target_revenue_margin_percent: "%",
      tooling_consumables_cost_per_batch: "USD",
      packaging_cost_per_batch: "USD",
      freight_cost_per_batch: "USD",
      contingency_percent: "%",
    },
  },
  {
    label: "High-Complexity Precision Job (100 units)",
    values: {
      batch_quantity: "100",
      cycle_time_seconds_per_unit: "3600",
      setup_time_minutes_per_batch: "120",
      annual_volume_units: "50000",
      material_cost_per_unit: "350",
      machine_rate_per_hour: "200",
      labor_rate_per_hour: "85",
      operator_count: "1",
      annual_unallocated_overhead: "500000",
      scrap_rework_percent: "8",
      target_revenue_margin_percent: "35",
      tooling_consumables_cost_per_batch: "2500",
      external_processing_cost_per_batch: "1200",
      packaging_cost_per_batch: "300",
      freight_cost_per_batch: "1500",
      other_job_cost_per_batch: "800",
      contingency_percent: "8",
      current_quote_per_unit: "1250",
    },
    units: {
      batch_quantity: "units",
      cycle_time_seconds_per_unit: "sec",
      setup_time_minutes_per_batch: "min",
      annual_volume_units: "units",
      material_cost_per_unit: "USD",
      machine_rate_per_hour: "USD/h",
      labor_rate_per_hour: "USD/h",
      operator_count: "count",
      annual_unallocated_overhead: "USD",
      scrap_rework_percent: "%",
      target_revenue_margin_percent: "%",
      tooling_consumables_cost_per_batch: "USD",
      external_processing_cost_per_batch: "USD",
      packaging_cost_per_batch: "USD",
      freight_cost_per_batch: "USD",
      other_job_cost_per_batch: "USD",
      contingency_percent: "%",
      current_quote_per_unit: "USD",
    },
  },
];
