// SectorCalc PRO V2 — Loss Making Job Detector Presets

import type { ProPreset } from "../proToolRegistry";

export const LOSS_DETECTOR_PRESETS: ProPreset[] = [
  {
    label: "Profitable Repeat Job (500 units)",
    values: {
      batch_quantity: "500",
      selling_price_per_unit: "95",
      material_cost_per_unit: "25",
      cycle_time_seconds_per_unit: "720",
      setup_time_minutes_per_batch: "8",
      machine_rate_per_hour: "85",
      operator_count: "1",
      labor_rate_per_hour: "45",
      external_processing_per_batch: "0",
      packaging_freight_per_batch: "50",
      other_job_cost_per_batch: "0",
      allocated_overhead: "350",
      scrap_rework_percent: "5",
      target_revenue_margin_percent: "30",
      annual_volume_units: "100000",
    },
    units: {
      batch_quantity: "units",
      selling_price_per_unit: "USD",
      material_cost_per_unit: "USD",
      cycle_time_seconds_per_unit: "sec",
      setup_time_minutes_per_batch: "min",
      machine_rate_per_hour: "USD/h",
      operator_count: "count",
      labor_rate_per_hour: "USD/h",
      external_processing_per_batch: "USD",
      packaging_freight_per_batch: "USD",
      other_job_cost_per_batch: "USD",
      allocated_overhead: "USD",
      scrap_rework_percent: "%",
      target_revenue_margin_percent: "%",
      annual_volume_units: "units",
    },
  },
  {
    label: "Low-Margin Job (300 units)",
    values: {
      batch_quantity: "300",
      selling_price_per_unit: "50",
      material_cost_per_unit: "22",
      cycle_time_seconds_per_unit: "600",
      setup_time_minutes_per_batch: "10",
      machine_rate_per_hour: "75",
      operator_count: "1",
      labor_rate_per_hour: "40",
      external_processing_per_batch: "0",
      packaging_freight_per_batch: "30",
      other_job_cost_per_batch: "0",
      allocated_overhead: "400",
      scrap_rework_percent: "5",
      target_revenue_margin_percent: "25",
      annual_volume_units: "50000",
    },
    units: {
      batch_quantity: "units",
      selling_price_per_unit: "USD",
      material_cost_per_unit: "USD",
      cycle_time_seconds_per_unit: "sec",
      setup_time_minutes_per_batch: "min",
      machine_rate_per_hour: "USD/h",
      operator_count: "count",
      labor_rate_per_hour: "USD/h",
      external_processing_per_batch: "USD",
      packaging_freight_per_batch: "USD",
      other_job_cost_per_batch: "USD",
      allocated_overhead: "USD",
      scrap_rework_percent: "%",
      target_revenue_margin_percent: "%",
      annual_volume_units: "units",
    },
  },
  {
    label: "Loss-Making Job (200 units)",
    values: {
      batch_quantity: "200",
      selling_price_per_unit: "25",
      material_cost_per_unit: "12",
      cycle_time_seconds_per_unit: "1200",
      setup_time_minutes_per_batch: "15",
      machine_rate_per_hour: "80",
      operator_count: "1",
      labor_rate_per_hour: "42",
      external_processing_per_batch: "100",
      packaging_freight_per_batch: "40",
      other_job_cost_per_batch: "50",
      allocated_overhead: "200",
      scrap_rework_percent: "8",
      target_revenue_margin_percent: "20",
      annual_volume_units: "12000",
    },
    units: {
      batch_quantity: "units",
      selling_price_per_unit: "USD",
      material_cost_per_unit: "USD",
      cycle_time_seconds_per_unit: "sec",
      setup_time_minutes_per_batch: "min",
      machine_rate_per_hour: "USD/h",
      operator_count: "count",
      labor_rate_per_hour: "USD/h",
      external_processing_per_batch: "USD",
      packaging_freight_per_batch: "USD",
      other_job_cost_per_batch: "USD",
      allocated_overhead: "USD",
      scrap_rework_percent: "%",
      target_revenue_margin_percent: "%",
      annual_volume_units: "units",
    },
  },
];
