// SectorCalc PRO V2 — Machine Hourly Rate Proof Report Presets
// Three realistic presets matching the verified golden fixtures.
// Each preset populates all fields including optional scenario.

import type { ProPreset } from "../proToolRegistry";

export const MACHINE_RATE_PRESETS: ProPreset[] = [
  {
    label: "Small CNC Workshop",
    values: {
      planned_operating_hours: "2000",
      utilization_percent: "80",
      planned_downtime_percent: "5",
      purchase_price: "85000",
      residual_value: "5000",
      economic_life_years: "8",
      maintenance_cost: "6000",
      insurance_tax_cost: "2000",
      facility_allocation: "18000",
      machine_power_kw: "15",
      electricity_price: "0.12",
      consumables_cost_per_hour: "2.5",
      tooling_cost_per_hour: "3",
      operator_count: "1",
      labor_rate_per_hour: "45",
      current_shop_rate: "85",
      target_margin_percent: "25",
      financing_cost_percent: "0",
      other_annual_fixed_cost: "0",
      annual_production_volume: "100000",
      cycle_time_seconds: "720",
      setup_time_minutes: "8",
      average_batch_quantity: "500",
    },
    units: {
      planned_operating_hours: "h",
      utilization_percent: "%",
      planned_downtime_percent: "%",
      purchase_price: "USD",
      residual_value: "USD",
      economic_life_years: "year",
      maintenance_cost: "USD",
      insurance_tax_cost: "USD",
      facility_allocation: "USD",
      machine_power_kw: "kW",
      electricity_price: "USD/kWh",
      consumables_cost_per_hour: "USD/h",
      tooling_cost_per_hour: "USD/h",
      operator_count: "count",
      labor_rate_per_hour: "USD/h",
      current_shop_rate: "USD/h",
      target_margin_percent: "%",
      financing_cost_percent: "%/year",
      other_annual_fixed_cost: "USD",
      annual_production_volume: "units",
      cycle_time_seconds: "sec",
      setup_time_minutes: "min",
      average_batch_quantity: "units",
    },
  },
  {
    label: "Medium Production Machine",
    values: {
      planned_operating_hours: "3500",
      utilization_percent: "85",
      planned_downtime_percent: "3",
      purchase_price: "350000",
      residual_value: "35000",
      economic_life_years: "10",
      maintenance_cost: "18000",
      insurance_tax_cost: "5000",
      facility_allocation: "45000",
      machine_power_kw: "45",
      electricity_price: "0.10",
      consumables_cost_per_hour: "5",
      tooling_cost_per_hour: "8",
      operator_count: "2",
      labor_rate_per_hour: "65",
      current_shop_rate: "120",
      target_margin_percent: "20",
      financing_cost_percent: "5",
      other_annual_fixed_cost: "0",
      annual_production_volume: "500000",
      cycle_time_seconds: "300",
      setup_time_minutes: "15",
      average_batch_quantity: "2000",
    },
    units: {
      planned_operating_hours: "h",
      utilization_percent: "%",
      planned_downtime_percent: "%",
      purchase_price: "USD",
      residual_value: "USD",
      economic_life_years: "year",
      maintenance_cost: "USD",
      insurance_tax_cost: "USD",
      facility_allocation: "USD",
      machine_power_kw: "kW",
      electricity_price: "USD/kWh",
      consumables_cost_per_hour: "USD/h",
      tooling_cost_per_hour: "USD/h",
      operator_count: "count",
      labor_rate_per_hour: "USD/h",
      current_shop_rate: "USD/h",
      target_margin_percent: "%",
      financing_cost_percent: "%/year",
      other_annual_fixed_cost: "USD",
      annual_production_volume: "units",
      cycle_time_seconds: "sec",
      setup_time_minutes: "min",
      average_batch_quantity: "units",
    },
  },
  {
    label: "High-Overhead Precision Cell",
    values: {
      planned_operating_hours: "2000",
      utilization_percent: "70",
      planned_downtime_percent: "5",
      purchase_price: "750000",
      residual_value: "75000",
      economic_life_years: "12",
      maintenance_cost: "35000",
      insurance_tax_cost: "12000",
      facility_allocation: "95000",
      machine_power_kw: "30",
      electricity_price: "0.15",
      consumables_cost_per_hour: "15",
      tooling_cost_per_hour: "22",
      operator_count: "1",
      labor_rate_per_hour: "95",
      current_shop_rate: "250",
      target_margin_percent: "30",
      financing_cost_percent: "4",
      other_annual_fixed_cost: "10000",
      annual_production_volume: "15000",
      cycle_time_seconds: "1800",
      setup_time_minutes: "45",
      average_batch_quantity: "100",
    },
    units: {
      planned_operating_hours: "h",
      utilization_percent: "%",
      planned_downtime_percent: "%",
      purchase_price: "USD",
      residual_value: "USD",
      economic_life_years: "year",
      maintenance_cost: "USD",
      insurance_tax_cost: "USD",
      facility_allocation: "USD",
      machine_power_kw: "kW",
      electricity_price: "USD/kWh",
      consumables_cost_per_hour: "USD/h",
      tooling_cost_per_hour: "USD/h",
      operator_count: "count",
      labor_rate_per_hour: "USD/h",
      current_shop_rate: "USD/h",
      target_margin_percent: "%",
      financing_cost_percent: "%/year",
      other_annual_fixed_cost: "USD",
      annual_production_volume: "units",
      cycle_time_seconds: "sec",
      setup_time_minutes: "min",
      average_batch_quantity: "units",
    },
  },
];

export function getDefaultPreset(): ProPreset {
  return MACHINE_RATE_PRESETS[0];
}
