// SectorCalc PRO V2 — Plant-Wide Shop Rate Cost Structure Audit Presets

import type { ProPreset } from "../proToolRegistry";

export const PLANT_WIDE_SHOP_RATE_PRESETS: ProPreset[] = [
  {
    label: "Balanced Operations (GOOD)",
    values: {
      total_annual_cost: "2000000",
      total_productive_hours: "40000",
      machine_group_cost: "500000",
      machine_group_hours: "15000",
      overhead_pool: "600000",
      overhead_allocation_base: "40000",
      current_shop_rate: "85",
      target_margin_pct: "25",
      utilization_pct: "80",
      labor_burden: "300000",
      facility_burden: "200000",
      maintenance_burden: "150000",
      energy_burden: "100000",
    },
    units: {
      total_annual_cost: "USD",
      total_productive_hours: "hours",
      machine_group_cost: "USD",
      machine_group_hours: "hours",
      overhead_pool: "USD",
      overhead_allocation_base: "hours",
      current_shop_rate: "USD/hr",
      target_margin_pct: "%",
      utilization_pct: "%",
      labor_burden: "USD",
      facility_burden: "USD",
      maintenance_burden: "USD",
      energy_burden: "USD",
    },
  },
  {
    label: "Low Utilization (REVIEW)",
    values: {
      total_annual_cost: "1500000",
      total_productive_hours: "30000",
      machine_group_cost: "400000",
      machine_group_hours: "12000",
      overhead_pool: "500000",
      overhead_allocation_base: "30000",
      current_shop_rate: "55",
      target_margin_pct: "20",
      utilization_pct: "65",
      labor_burden: "250000",
      facility_burden: "180000",
      maintenance_burden: "120000",
      energy_burden: "80000",
    },
    units: {
      total_annual_cost: "USD",
      total_productive_hours: "hours",
      machine_group_cost: "USD",
      machine_group_hours: "hours",
      overhead_pool: "USD",
      overhead_allocation_base: "hours",
      current_shop_rate: "USD/hr",
      target_margin_pct: "%",
      utilization_pct: "%",
      labor_burden: "USD",
      facility_burden: "USD",
      maintenance_burden: "USD",
      energy_burden: "USD",
    },
  },
  {
    label: "Rate Below Cost (BLOCKED)",
    values: {
      total_annual_cost: "1800000",
      total_productive_hours: "25000",
      machine_group_cost: "450000",
      machine_group_hours: "10000",
      overhead_pool: "700000",
      overhead_allocation_base: "25000",
      current_shop_rate: "50",
      target_margin_pct: "15",
      utilization_pct: "75",
      labor_burden: "280000",
      facility_burden: "220000",
      maintenance_burden: "160000",
      energy_burden: "90000",
    },
    units: {
      total_annual_cost: "USD",
      total_productive_hours: "hours",
      machine_group_cost: "USD",
      machine_group_hours: "hours",
      overhead_pool: "USD",
      overhead_allocation_base: "hours",
      current_shop_rate: "USD/hr",
      target_margin_pct: "%",
      utilization_pct: "%",
      labor_burden: "USD",
      facility_burden: "USD",
      maintenance_burden: "USD",
      energy_burden: "USD",
    },
  },
];

export function getDefaultPreset(): ProPreset {
  return PLANT_WIDE_SHOP_RATE_PRESETS[0];
}
