import type { ProPreset } from "../proToolRegistry";

export const SKU_MARGIN_RANKER_PRESETS: ProPreset[] = [
  {
    label: "Profitable SKU (Good Margin)",
    values: {
      unit_price: "100",
      material_cost_per_unit: "25",
      labor_cost_per_unit: "15",
      overhead_per_unit: "10",
      logistics_cost_per_unit: "5",
      annual_volume_units: "10000",
      target_margin_percent: "30",
      total_portfolio_revenue: "5000000",
      total_portfolio_profit: "1000000",
    },
    units: {
      unit_price: "USD",
      material_cost_per_unit: "USD",
      labor_cost_per_unit: "USD",
      overhead_per_unit: "USD",
      logistics_cost_per_unit: "USD",
      annual_volume_units: "units",
      target_margin_percent: "%",
      total_portfolio_revenue: "USD",
      total_portfolio_profit: "USD",
    },
  },
  {
    label: "Weak Margin SKU (Review)",
    values: {
      unit_price: "80",
      material_cost_per_unit: "35",
      labor_cost_per_unit: "20",
      overhead_per_unit: "12",
      logistics_cost_per_unit: "8",
      annual_volume_units: "5000",
      target_margin_percent: "30",
      total_portfolio_revenue: "3000000",
      total_portfolio_profit: "400000",
    },
    units: {
      unit_price: "USD",
      material_cost_per_unit: "USD",
      labor_cost_per_unit: "USD",
      overhead_per_unit: "USD",
      logistics_cost_per_unit: "USD",
      annual_volume_units: "units",
      target_margin_percent: "%",
      total_portfolio_revenue: "USD",
      total_portfolio_profit: "USD",
    },
  },
  {
    label: "Loss-Making SKU (Blocked)",
    values: {
      unit_price: "50",
      material_cost_per_unit: "30",
      labor_cost_per_unit: "20",
      overhead_per_unit: "15",
      logistics_cost_per_unit: "10",
      annual_volume_units: "1000",
      target_margin_percent: "20",
      total_portfolio_revenue: "1000000",
      total_portfolio_profit: "100000",
    },
    units: {
      unit_price: "USD",
      material_cost_per_unit: "USD",
      labor_cost_per_unit: "USD",
      overhead_per_unit: "USD",
      logistics_cost_per_unit: "USD",
      annual_volume_units: "units",
      target_margin_percent: "%",
      total_portfolio_revenue: "USD",
      total_portfolio_profit: "USD",
    },
  },
];
