import type { ProPreset } from "../proToolRegistry";

export const EMPLOYEE_COST_PRESETS: ProPreset[] = [
  {
    label: "Standard Employee (Good — Controlled Cost)",
    values: {
      annual_base_salary: "50000",
      payroll_tax_rate: "12",
      health_insurance_annual: "4000",
      pension_contribution_rate: "4",
      bonus_target_rate: "5",
      paid_leave_weeks: "4",
      training_budget_annual: "1000",
      equipment_it_annual: "1500",
      workspace_facility_annual: "2500",
      recruitment_allocation_rate: "2",
      other_benefits_annual: "0",
      productive_hours_per_year: "1664",
    },
    units: {
      annual_base_salary: "USD",
      payroll_tax_rate: "%",
      health_insurance_annual: "USD",
      pension_contribution_rate: "%",
      bonus_target_rate: "%",
      paid_leave_weeks: "weeks",
      training_budget_annual: "USD",
      equipment_it_annual: "USD",
      workspace_facility_annual: "USD",
      recruitment_allocation_rate: "%",
      other_benefits_annual: "USD",
      productive_hours_per_year: "hours",
    },
  },
  {
    label: "Highly Compensated (Moderate — Elevated Burden)",
    values: {
      annual_base_salary: "150000",
      payroll_tax_rate: "25",
      health_insurance_annual: "12000",
      pension_contribution_rate: "8",
      bonus_target_rate: "20",
      paid_leave_weeks: "5",
      training_budget_annual: "5000",
      equipment_it_annual: "8000",
      workspace_facility_annual: "15000",
      recruitment_allocation_rate: "5",
      other_benefits_annual: "3000",
      productive_hours_per_year: "1600",
    },
    units: {
      annual_base_salary: "USD",
      payroll_tax_rate: "%",
      health_insurance_annual: "USD",
      pension_contribution_rate: "%",
      bonus_target_rate: "%",
      paid_leave_weeks: "weeks",
      training_budget_annual: "USD",
      equipment_it_annual: "USD",
      workspace_facility_annual: "USD",
      recruitment_allocation_rate: "%",
      other_benefits_annual: "USD",
      productive_hours_per_year: "hours",
    },
  },
  {
    label: "Executive Package (Critical — High Overhead)",
    values: {
      annual_base_salary: "300000",
      payroll_tax_rate: "28",
      health_insurance_annual: "30000",
      pension_contribution_rate: "15",
      bonus_target_rate: "50",
      paid_leave_weeks: "6",
      training_budget_annual: "15000",
      equipment_it_annual: "15000",
      workspace_facility_annual: "40000",
      recruitment_allocation_rate: "8",
      other_benefits_annual: "20000",
      productive_hours_per_year: "1500",
    },
    units: {
      annual_base_salary: "USD",
      payroll_tax_rate: "%",
      health_insurance_annual: "USD",
      pension_contribution_rate: "%",
      bonus_target_rate: "%",
      paid_leave_weeks: "weeks",
      training_budget_annual: "USD",
      equipment_it_annual: "USD",
      workspace_facility_annual: "USD",
      recruitment_allocation_rate: "%",
      other_benefits_annual: "USD",
      productive_hours_per_year: "hours",
    },
  },
];
