/**
 * S5/6 guide oracle UX scaffold specs — schema-derived input maps only.
 * GENERATED by scripts/tool-activation/apply-s5-guide-oracle-ux-scaffold.mjs
 * Do not edit manually; re-run apply:s5-guide-oracle-ux-scaffold to refresh.
 */
import type { ToolGuideSpec } from "@/lib/features/tool-guides/tool-guide-spec";

export const S5_GUIDE_ORACLE_UX_SCAFFOLD_SPECS: readonly ToolGuideSpec[] = [] as const;

export function getS5GuideOracleUxScaffoldSpec(slug: string): ToolGuideSpec | null {
  return S5_GUIDE_ORACLE_UX_SCAFFOLD_SPECS.find((spec) => spec.slug === slug) ?? null;
}
