// Auto-generated by scripts/deepseek/generate-calculator-registry.ts — do not edit manually.
import type { GeneratedCalculatorModule } from "@/lib/generated-tools/types";

type CalculatorLoader = () => Promise<GeneratedCalculatorModule>;

type RawGeneratedModule = Record<string, unknown>;

const TR_CHAR_MAP: Readonly<Record<string, string>> = {
  ğ: "g",
  Ğ: "G",
  ü: "u",
  Ü: "U",
  ş: "s",
  Ş: "S",
  ı: "i",
  İ: "I",
  ö: "o",
  Ö: "O",
  ç: "c",
  Ç: "C",
};

function normalizeAscii(str: string): string {
  return str.replace(/[ğĞüÜşŞıİöÖçÇ]/g, (char) => TR_CHAR_MAP[char] ?? char);
}

function toSafePascalCase(str: string): string {
  let name = normalizeAscii(str.trim())
    .replace(/[-_\s]+(.)?/g, (_, char?: string) => (char ? char.toUpperCase() : ""))
    .replace(/[^a-zA-Z0-9]/g, "");
  if (!name) {
    name = "Value";
  }
  if (/^\d/.test(name)) {
    name = `Tool${name}`;
  }
  return name.charAt(0).toUpperCase() + name.slice(1);
}

function wrapGeneratedModule(mod: RawGeneratedModule, slug: string): GeneratedCalculatorModule {
  const pascalName = toSafePascalCase(slug);
  const inputSchema = mod[`${pascalName}InputSchema`];
  const calculate = mod[`calculate${pascalName}`];
  if (!inputSchema || typeof calculate !== "function") {
    throw new Error(`Generated module for "${slug}" is missing exports.`);
  }
  return {
    inputSchema: inputSchema as GeneratedCalculatorModule["inputSchema"],
    calculate: calculate as GeneratedCalculatorModule["calculate"],
  };
}

function createLoader(slug: string): CalculatorLoader {
  return async () => {
    const mod = (await import(`@generated/${slug}`)) as RawGeneratedModule;
    return wrapGeneratedModule(mod, slug);
  };
}

const CALCULATOR_LOADERS: Readonly<Record<string, CalculatorLoader>> = {
  "3d-print-cost-check": createLoader("3d-print-cost-check"),
  "3d-print-job-margin-tool": createLoader("3d-print-job-margin-tool"),
  "7-israf-muda-avcisi-parasal-karsilik-calculator": createLoader("7-israf-muda-avcisi-parasal-karsilik-calculator"),
  "abonelik-yazilim-cloud-yillik-maliyet-hesabi": createLoader("abonelik-yazilim-cloud-yillik-maliyet-hesabi"),
  "agirlikli-ortalama-hesaplama": createLoader("agirlikli-ortalama-hesaplama"),
  "agriculture-irrigation-yield-loss": createLoader("agriculture-irrigation-yield-loss"),
  "agv-amr-otonom-tasima-geri-donus-calculator": createLoader("agv-amr-otonom-tasima-geri-donus-calculator"),
  "akaryakit-fiyati-ile-yol-butcesi": createLoader("akaryakit-fiyati-ile-yol-butcesi"),
  "aku-kapasitesi-calisma-suresi-hesabi": createLoader("aku-kapasitesi-calisma-suresi-hesabi"),
  "alti-sigma-dpmo-sigma-seviyesi-cevirici": createLoader("alti-sigma-dpmo-sigma-seviyesi-cevirici"),
  "ambalaj-malzemesi-degisimi-ve-maliyet-etki-calculator": createLoader("ambalaj-malzemesi-degisimi-ve-maliyet-etki-calculator"),
  "amper-kilowatt-kw-cevirici": createLoader("amper-kilowatt-kw-cevirici"),
  "andon-sistemi-durus-ve-tepki-suresi-maliyet-calculator": createLoader("andon-sistemi-durus-ve-tepki-suresi-maliyet-calculator"),
  "annual-leave-severance-notice-calculator": createLoader("annual-leave-severance-notice-calculator"),
  "aql-kabul-orneklemesi-risk-ve-maliyet-calculator": createLoader("aql-kabul-orneklemesi-risk-ve-maliyet-calculator"),
  "arac-amortisman-hesaplama": createLoader("arac-amortisman-hesaplama"),
  "arac-bakim-periyodu-takip-hesaplama": createLoader("arac-bakim-periyodu-takip-hesaplama"),
  "arac-kira-satin-alma-karsilastirma": createLoader("arac-kira-satin-alma-karsilastirma"),
  "area-converter": createLoader("area-converter"),
  "asgari-siparis-miktari-moq-ve-stok-tasima-maliyet-denge-calculator": createLoader("asgari-siparis-miktari-moq-ve-stok-tasima-maliyet-denge-calculator"),
  "asma-tavan-malzeme-hesabi": createLoader("asma-tavan-malzeme-hesabi"),
  "atik-yonetimi-ve-bertaraf-maliyet-optimizasyon-calculator": createLoader("atik-yonetimi-ve-bertaraf-maliyet-optimizasyon-calculator"),
  "auto-repair-comeback-cost": createLoader("auto-repair-comeback-cost"),
  "auto-repair-parts-labor-quote-calculator": createLoader("auto-repair-parts-labor-quote-calculator"),
  "auto-shop-margin-leak-detector": createLoader("auto-shop-margin-leak-detector"),
  "average-calculator": createLoader("average-calculator"),
  "aydinlatma-armatur-sayisi-hesaplama": createLoader("aydinlatma-armatur-sayisi-hesaplama"),
  "baca-havalandirma-kanali-cap-hesabi": createLoader("baca-havalandirma-kanali-cap-hesabi"),
  "bar-psi-pascal-cevirici": createLoader("bar-psi-pascal-cevirici"),
  "basincli-kap-cidar-kalinligi-hesabi": createLoader("basincli-kap-cidar-kalinligi-hesabi"),
  "batch-yield-calculator": createLoader("batch-yield-calculator"),
  "belt-pulley-speed-length-calculator": createLoader("belt-pulley-speed-length-calculator"),
  "beygir-gucu-kilowatt-cevirici": createLoader("beygir-gucu-kilowatt-cevirici"),
  "boiler-efficiency-calculator": createLoader("boiler-efficiency-calculator"),
  "bolt-tightening-torque-calculator": createLoader("bolt-tightening-torque-calculator"),
  "boru-agirlik-hesaplama-celik-paslanmaz": createLoader("boru-agirlik-hesaplama-celik-paslanmaz"),
  "boru-capi-akis-hizi-hesaplama": createLoader("boru-capi-akis-hizi-hesaplama"),
  "boru-hatti-surtunme-ve-pompa-enerji-kayip-calculator": createLoader("boru-hatti-surtunme-ve-pompa-enerji-kayip-calculator"),
  "boya-kaplama-sarfiyati-m-basina-hesabi": createLoader("boya-kaplama-sarfiyati-m-basina-hesabi"),
  "boya-ve-apre-recetesi-maliyet-optimizasyon-calculator": createLoader("boya-ve-apre-recetesi-maliyet-optimizasyon-calculator"),
  "break-even-calculator": createLoader("break-even-calculator"),
  "break-even-safety-margin-calculator": createLoader("break-even-safety-margin-calculator"),
  "brick-calculator": createLoader("brick-calculator"),
  "buhar-kapani-steam-trap-kacak-ve-enerji-kayip-calculator": createLoader("buhar-kapani-steam-trap-kacak-ve-enerji-kayip-calculator"),
  "bulonlu-baglanti-kesme-ezilme-hesabi": createLoader("bulonlu-baglanti-kesme-ezilme-hesabi"),
  "cabinet-cost-estimator": createLoader("cabinet-cost-estimator"),
  "calibration-drift-risk": createLoader("calibration-drift-risk"),
  "carbon-footprint-compliance-risk": createLoader("carbon-footprint-compliance-risk"),
  "carbon-footprint-quick": createLoader("carbon-footprint-quick"),
  "cash-flow-gap-calculator": createLoader("cash-flow-gap-calculator"),
  "cay-kahve-su-tuketim-maliyeti": createLoader("cay-kahve-su-tuketim-maliyeti"),
  "cbam-compliance-verdict": createLoader("cbam-compliance-verdict"),
  "cbam-exposure-quick-check": createLoader("cbam-exposure-quick-check"),
  "cbam-unit-product-carbon-footprint-calculator": createLoader("cbam-unit-product-carbon-footprint-calculator"),
  "cek-senet-vade-kirma-maliyeti-hesabi": createLoader("cek-senet-vade-kirma-maliyeti-hesabi"),
  "celik-cati-makas-yaklasik-agirligi": createLoader("celik-cati-makas-yaklasik-agirligi"),
  "celik-raf-depo-rafi-yuk-kapasitesi": createLoader("celik-raf-depo-rafi-yuk-kapasitesi"),
  "cevre-atik-beyani-maliyet-hesaplama": createLoader("cevre-atik-beyani-maliyet-hesaplama"),
  "change-order-impact-analyzer": createLoader("change-order-impact-analyzer"),
  "cit-korkuluk-malzeme-hesabi": createLoader("cit-korkuluk-malzeme-hesabi"),
  "civata-on-germe-kuvveti-hesabi": createLoader("civata-on-germe-kuvveti-hesabi"),
  "civata-sikma-torku-hesaplama": createLoader("civata-sikma-torku-hesaplama"),
  "cleaning-cost-calculator": createLoader("cleaning-cost-calculator"),
  "cloud-api-cost-overrun": createLoader("cloud-api-cost-overrun"),
  "cnc-cycle-time-calculator": createLoader("cnc-cycle-time-calculator"),
  "cnc-oee-loss": createLoader("cnc-oee-loss"),
  "cnc-quote-risk-analyzer": createLoader("cnc-quote-risk-analyzer"),
  "cnc-tool-wear-cost": createLoader("cnc-tool-wear-cost"),
  "cobot-vs-manuel-iscilik-karsilastirma-calculator": createLoader("cobot-vs-manuel-iscilik-karsilastirma-calculator"),
  "compressor-energy-cost-calculator": createLoader("compressor-energy-cost-calculator"),
  "compressor-leak-cost-calculator": createLoader("compressor-leak-cost-calculator"),
  "concrete-bag-calculator": createLoader("concrete-bag-calculator"),
  "concrete-volume-calculator": createLoader("concrete-volume-calculator"),
  "construction-project-overrun": createLoader("construction-project-overrun"),
  "construction-subcontractor-margin-leak": createLoader("construction-subcontractor-margin-leak"),
  "cop-atik-konteyner-hacim-hesabi": createLoader("cop-atik-konteyner-hacim-hesabi"),
  "cpk-ppk-hata-maliyeti-ppm-calculator": createLoader("cpk-ppk-hata-maliyeti-ppm-calculator"),
  "crop-yield-calculator": createLoader("crop-yield-calculator"),
  "crop-yield-loss-analyzer": createLoader("crop-yield-loss-analyzer"),
  "cutting-speed-calculator": createLoader("cutting-speed-calculator"),
  "daire-alani-cevresi-hesaplama": createLoader("daire-alani-cevresi-hesaplama"),
  "dairy-feed-efficiency-loss": createLoader("dairy-feed-efficiency-loss"),
  "dairy-profit-detector": createLoader("dairy-profit-detector"),
  "delivery-cost-calculator": createLoader("delivery-cost-calculator"),
  "depo-raf-palet-yerlesim-optimizasyonu": createLoader("depo-raf-palet-yerlesim-optimizasyonu"),
  "depo-yerlesimi-ve-toplama-rotasi-optimizasyon-calculator": createLoader("depo-yerlesimi-ve-toplama-rotasi-optimizasyon-calculator"),
  "depreciation-calculator": createLoader("depreciation-calculator"),
  "desi-calculator": createLoader("desi-calculator"),
  "discount-calculator": createLoader("discount-calculator"),
  "disli-modul-cap-hesaplama": createLoader("disli-modul-cap-hesaplama"),
  "dizel-benzin-maliyet-karsilastirma": createLoader("dizel-benzin-maliyet-karsilastirma"),
  "dogalgaz-tuketimi-hesaplama": createLoader("dogalgaz-tuketimi-hesaplama"),
  "dongusel-ekonomi-ve-urun-omru-uzatma-roi-calculator": createLoader("dongusel-ekonomi-ve-urun-omru-uzatma-roi-calculator"),
  "doviz-pozisyonu-kur-farki-riski-hesabi": createLoader("doviz-pozisyonu-kur-farki-riski-hesabi"),
  "dovme-ekstruzyon-proses-kuvvet-ve-pres-kapasite-calculator": createLoader("dovme-ekstruzyon-proses-kuvvet-ve-pres-kapasite-calculator"),
  "downtime-minute-cost-calculator": createLoader("downtime-minute-cost-calculator"),
  "drywall-calculator": createLoader("drywall-calculator"),
  "duvar-kagidi-seramik-adet-hesaplama": createLoader("duvar-kagidi-seramik-adet-hesaplama"),
  "egitim-yatirimi-ve-verimlilik-artisi-geri-donus-calculator": createLoader("egitim-yatirimi-ve-verimlilik-artisi-geri-donus-calculator"),
  "electrical-labor-estimator": createLoader("electrical-labor-estimator"),
  "electrical-panel-rework-cost": createLoader("electrical-panel-rework-cost"),
  "electricity-bill-calculator": createLoader("electricity-bill-calculator"),
  "employee-total-cost-calculator": createLoader("employee-total-cost-calculator"),
  "energy-compressor-leak-cost": createLoader("energy-compressor-leak-cost"),
  "energy-consumption-check": createLoader("energy-consumption-check"),
  "energy-efficiency-report": createLoader("energy-efficiency-report"),
  "energy-peak-cost": createLoader("energy-peak-cost"),
  "energy-savings-package-calculator": createLoader("energy-savings-package-calculator"),
  "enerji-izleme-sistemi-yatirim-ve-tasarruf-tahmin-calculator": createLoader("enerji-izleme-sistemi-yatirim-ve-tasarruf-tahmin-calculator"),
  "enflasyon-fiyat-eskalasyonu-hesaplama": createLoader("enflasyon-fiyat-eskalasyonu-hesaplama"),
  "enjeksiyon-dokum-cekme-payi-hesabi": createLoader("enjeksiyon-dokum-cekme-payi-hesabi"),
  "enjeksiyon-sogutma-suresi-ve-cevrim-optimizasyon-calculator": createLoader("enjeksiyon-sogutma-suresi-ve-cevrim-optimizasyon-calculator"),
  "esnek-uretim-hucresi-yatirim-ve-geri-donus-calculator": createLoader("esnek-uretim-hucresi-yatirim-ve-geri-donus-calculator"),
  "excavation-volume-calculator": createLoader("excavation-volume-calculator"),
  "fazla-mesai-ucreti-hesaplama": createLoader("fazla-mesai-ucreti-hesaplama"),
  "fazla-mesai-vs-yeni-ise-alim-basabas-calculator": createLoader("fazla-mesai-vs-yeni-ise-alim-basabas-calculator"),
  "feed-cost-estimator": createLoader("feed-cost-estimator"),
  "feed-efficiency-analyzer": createLoader("feed-efficiency-analyzer"),
  "feed-rate-calculator": createLoader("feed-rate-calculator"),
  "fertilizer-dosage-calculator": createLoader("fertilizer-dosage-calculator"),
  "filament-recine-toz-maliyet-ve-fire-karsilastirma-calculator": createLoader("filament-recine-toz-maliyet-ve-fire-karsilastirma-calculator"),
  "fire-system-flow-hydrant-calculator": createLoader("fire-system-flow-hydrant-calculator"),
  "fiyat-artisi-ve-talep-esnekligi-karlilik-simulasyon-calculator": createLoader("fiyat-artisi-ve-talep-esnekligi-karlilik-simulasyon-calculator"),
  "flooring-calculator": createLoader("flooring-calculator"),
  "food-cost-calculator": createLoader("food-cost-calculator"),
  "food-waste-margin-loss": createLoader("food-waste-margin-loss"),
  "forklift-transpalet-kullanim-maliyeti": createLoader("forklift-transpalet-kullanim-maliyeti"),
  "fotokopi-yazici-toner-sayfa-maliyeti": createLoader("fotokopi-yazici-toner-sayfa-maliyeti"),
  "freight-cost-calculator": createLoader("freight-cost-calculator"),
  "fuel-consumption-calculator": createLoader("fuel-consumption-calculator"),
  "fuel-consumption-check": createLoader("fuel-consumption-check"),
};

export const GENERATED_CALCULATOR_SLUGS = Object.freeze(
  Object.keys(CALCULATOR_LOADERS).sort((left, right) => left.localeCompare(right)),
) as readonly string[];

export async function loadGeneratedCalculator(
  slug: string,
): Promise<GeneratedCalculatorModule | null> {
  const loader = CALCULATOR_LOADERS[slug];
  if (!loader) {
    return null;
  }
  return loader();
}
