/**
 * Generated by scripts/tool-activation/generate-formula-source-audit-registry.mjs
 * Source: .sectorcalc/tool-quality/quality-scan-report.json (upgradeDecision === "PASS")
 * Do not edit manually — run: npm run audit:formula-registry
 */

export type FormulaSourceAuditStatus = {
  slug: string;
  status: "verified";
  auditGate: "Formula Source-of-Truth Audit Gate";
  auditVersion: "v1";
  verifiedAtSource: "quality-scan-report";
  standardReference: "7 Muda quality standard";
  checks: {
    upgradeDecisionPass: boolean;
    hasFormulaContract: boolean;
    hasValidation: boolean;
    hasTests: boolean;
    hasQuickResult: boolean;
    hasDeepReport: boolean;
    hasI18n: boolean;
  };
};

export const FORMULA_SOURCE_AUDIT_REGISTRY: Record<string, FormulaSourceAuditStatus> = {
  "3d-print-cost-check": {
    "slug": "3d-print-cost-check",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "3d-print-job-margin-tool": {
    "slug": "3d-print-job-margin-tool",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "7-israf-muda-avcisi-parasal-karsilik-calculator": {
    "slug": "7-israf-muda-avcisi-parasal-karsilik-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "abonelik-yazilim-cloud-yillik-maliyet-hesabi": {
    "slug": "abonelik-yazilim-cloud-yillik-maliyet-hesabi",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "agriculture-irrigation-yield-loss": {
    "slug": "agriculture-irrigation-yield-loss",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "aku-kapasitesi-calisma-suresi-hesabi": {
    "slug": "aku-kapasitesi-calisma-suresi-hesabi",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "alti-sigma-dpmo-sigma-seviyesi-cevirici": {
    "slug": "alti-sigma-dpmo-sigma-seviyesi-cevirici",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "arac-kira-satin-alma-karsilastirma": {
    "slug": "arac-kira-satin-alma-karsilastirma",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "auto-shop-margin-leak-detector": {
    "slug": "auto-shop-margin-leak-detector",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "basincli-kap-cidar-kalinligi-hesabi": {
    "slug": "basincli-kap-cidar-kalinligi-hesabi",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "belt-pulley-speed-length-calculator": {
    "slug": "belt-pulley-speed-length-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "boiler-efficiency-calculator": {
    "slug": "boiler-efficiency-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "break-even-calculator": {
    "slug": "break-even-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "bulonlu-baglanti-kesme-ezilme-hesabi": {
    "slug": "bulonlu-baglanti-kesme-ezilme-hesabi",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "calibration-drift-risk": {
    "slug": "calibration-drift-risk",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "carbon-footprint-quick": {
    "slug": "carbon-footprint-quick",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "cash-flow-gap-calculator": {
    "slug": "cash-flow-gap-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "cek-senet-vade-kirma-maliyeti-hesabi": {
    "slug": "cek-senet-vade-kirma-maliyeti-hesabi",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "celik-raf-depo-rafi-yuk-kapasitesi": {
    "slug": "celik-raf-depo-rafi-yuk-kapasitesi",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "cevre-atik-beyani-maliyet-hesaplama": {
    "slug": "cevre-atik-beyani-maliyet-hesaplama",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "change-order-impact-analyzer": {
    "slug": "change-order-impact-analyzer",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "civata-on-germe-kuvveti-hesabi": {
    "slug": "civata-on-germe-kuvveti-hesabi",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "civata-sikma-torku-hesaplama": {
    "slug": "civata-sikma-torku-hesaplama",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "cloud-api-cost-overrun": {
    "slug": "cloud-api-cost-overrun",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "cnc-cycle-time-calculator": {
    "slug": "cnc-cycle-time-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "cnc-oee-loss": {
    "slug": "cnc-oee-loss",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "cnc-quote-risk-analyzer": {
    "slug": "cnc-quote-risk-analyzer",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "cnc-tool-wear-cost": {
    "slug": "cnc-tool-wear-cost",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "compound-interest-calculator": {
    "slug": "compound-interest-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "compressor-energy-cost-calculator": {
    "slug": "compressor-energy-cost-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "compressor-leak-cost-calculator": {
    "slug": "compressor-leak-cost-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "concrete-bag-calculator": {
    "slug": "concrete-bag-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "construction-project-overrun": {
    "slug": "construction-project-overrun",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "construction-subcontractor-margin-leak": {
    "slug": "construction-subcontractor-margin-leak",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "crop-yield-calculator": {
    "slug": "crop-yield-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "crop-yield-loss-analyzer": {
    "slug": "crop-yield-loss-analyzer",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "dairy-feed-efficiency-loss": {
    "slug": "dairy-feed-efficiency-loss",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "dairy-profit-detector": {
    "slug": "dairy-profit-detector",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "depo-raf-palet-yerlesim-optimizasyonu": {
    "slug": "depo-raf-palet-yerlesim-optimizasyonu",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "doviz-pozisyonu-kur-farki-riski-hesabi": {
    "slug": "doviz-pozisyonu-kur-farki-riski-hesabi",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "downtime-minute-cost-calculator": {
    "slug": "downtime-minute-cost-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "electricity-bill-calculator": {
    "slug": "electricity-bill-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "employee-total-cost-calculator": {
    "slug": "employee-total-cost-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "energy-compressor-leak-cost": {
    "slug": "energy-compressor-leak-cost",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "energy-efficiency-report": {
    "slug": "energy-efficiency-report",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "energy-peak-cost": {
    "slug": "energy-peak-cost",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "energy-savings-package-calculator": {
    "slug": "energy-savings-package-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "enflasyon-fiyat-eskalasyonu-hesaplama": {
    "slug": "enflasyon-fiyat-eskalasyonu-hesaplama",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "enjeksiyon-dokum-cekme-payi-hesabi": {
    "slug": "enjeksiyon-dokum-cekme-payi-hesabi",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "fazla-mesai-ucreti-hesaplama": {
    "slug": "fazla-mesai-ucreti-hesaplama",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "feed-cost-estimator": {
    "slug": "feed-cost-estimator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "feed-efficiency-analyzer": {
    "slug": "feed-efficiency-analyzer",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "fertilizer-dosage-calculator": {
    "slug": "fertilizer-dosage-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "food-cost-calculator": {
    "slug": "food-cost-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "food-waste-margin-loss": {
    "slug": "food-waste-margin-loss",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "forklift-transpalet-kullanim-maliyeti": {
    "slug": "forklift-transpalet-kullanim-maliyeti",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "freight-cost-calculator": {
    "slug": "freight-cost-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "fuel-emission-calculator": {
    "slug": "fuel-emission-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "gelir-vergisi-dilimleri-hesaplama": {
    "slug": "gelir-vergisi-dilimleri-hesaplama",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "geri-donusum-gelir-maliyet-hesabi": {
    "slug": "geri-donusum-gelir-maliyet-hesabi",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "gerilim-dusumu-hesaplama": {
    "slug": "gerilim-dusumu-hesaplama",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "heat-loss-calculator": {
    "slug": "heat-loss-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "hidrolik-pompa-gucu-hesaplama": {
    "slug": "hidrolik-pompa-gucu-hesaplama",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "home-renovation-m2-calculator": {
    "slug": "home-renovation-m2-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "hourly-rate-calculator": {
    "slug": "hourly-rate-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "hvac-callback-margin-risk": {
    "slug": "hvac-callback-margin-risk",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "hvac-project-margin-guard": {
    "slug": "hvac-project-margin-guard",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "ic-verim-orani-irr-hesaplama": {
    "slug": "ic-verim-orani-irr-hesaplama",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "inventory-carrying-cost-eoq-calculator": {
    "slug": "inventory-carrying-cost-eoq-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "investment-payback-npv-calculator": {
    "slug": "investment-payback-npv-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "irrigation-cost-check": {
    "slug": "irrigation-cost-check",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "irsaliye-fatura-adedi-basina-sevkiyat-maliyeti": {
    "slug": "irsaliye-fatura-adedi-basina-sevkiyat-maliyeti",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "is-kazasi-maliyeti-gun-kaybi-hesaplama": {
    "slug": "is-kazasi-maliyeti-gun-kaybi-hesaplama",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "is-sagligi-ve-guvenligi-ceza-hesaplama": {
    "slug": "is-sagligi-ve-guvenligi-ceza-hesaplama",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "ise-giris-cikis-bildirgesi-sureleri": {
    "slug": "ise-giris-cikis-bildirgesi-sureleri",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "istatistiksel-proses-kontrol-spc-limit-hesabi": {
    "slug": "istatistiksel-proses-kontrol-spc-limit-hesabi",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "istinat-duvari-yaklasik-beton-hesabi": {
    "slug": "istinat-duvari-yaklasik-beton-hesabi",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "jenerator-kapasitesi-secim-hesaplama": {
    "slug": "jenerator-kapasitesi-secim-hesaplama",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "kablo-kesiti-mm-secim-hesaplama": {
    "slug": "kablo-kesiti-mm-secim-hesaplama",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "kasko-sigorta-prim-karsilastirma": {
    "slug": "kasko-sigorta-prim-karsilastirma",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "kaynak-dikis-hacmi-maliyeti-hesabi": {
    "slug": "kaynak-dikis-hacmi-maliyeti-hesabi",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "kaynak-proseduru-wps-on-isitma-sicakligi-hesabi": {
    "slug": "kaynak-proseduru-wps-on-isitma-sicakligi-hesabi",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "kaynakli-baglanti-kose-kut-mukavemet-hesabi": {
    "slug": "kaynakli-baglanti-kose-kut-mukavemet-hesabi",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "kdv-tevkifati-hesaplama": {
    "slug": "kdv-tevkifati-hesaplama",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "kesme-bukme-abkant-tonaj-hesabi": {
    "slug": "kesme-bukme-abkant-tonaj-hesabi",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "klima-btu-secim-hesaplama": {
    "slug": "klima-btu-secim-hesaplama",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "kompresor-debisi-tank-hacmi-hesabi": {
    "slug": "kompresor-debisi-tank-hacmi-hesabi",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "konteyner-yukleme-kapasitesi-teu-hesabi": {
    "slug": "konteyner-yukleme-kapasitesi-teu-hesabi",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "kredi-erken-kapama-cezasi-hesaplama": {
    "slug": "kredi-erken-kapama-cezasi-hesaplama",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "kwh-cost-calculator": {
    "slug": "kwh-cost-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "landscaping-contract-profit-tool": {
    "slug": "landscaping-contract-profit-tool",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "laser-cutting-time-check": {
    "slug": "laser-cutting-time-check",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "leasing-kiralama-maliyet-karsilastirma": {
    "slug": "leasing-kiralama-maliyet-karsilastirma",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "linear-regression-calculator": {
    "slug": "linear-regression-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "loan-payment-calculator": {
    "slug": "loan-payment-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "logistics-fuel-route-drift": {
    "slug": "logistics-fuel-route-drift",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "logistics-route-loss": {
    "slug": "logistics-route-loss",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "machine-hour-rate-calculator": {
    "slug": "machine-hour-rate-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "machine-time-calculator": {
    "slug": "machine-time-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "makine-ekonomik-omru-hurda-deger-hesabi": {
    "slug": "makine-ekonomik-omru-hurda-deger-hesabi",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "material-waste-calculator": {
    "slug": "material-waste-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "meal-planning-verdict": {
    "slug": "meal-planning-verdict",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "menu-profit-leak-detector": {
    "slug": "menu-profit-leak-detector",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "mil-aks-capi-hesabi-egilme-burulma": {
    "slug": "mil-aks-capi-hesabi-egilme-burulma",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "milk-yield-check": {
    "slug": "milk-yield-check",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "millwork-bid-risk-analyzer": {
    "slug": "millwork-bid-risk-analyzer",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "mortgage-calculator": {
    "slug": "mortgage-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "motor-gucu-kw-hp-cevirici": {
    "slug": "motor-gucu-kw-hp-cevirici",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "nakit-akisi-basit-gunluk-haftalik-panosu": {
    "slug": "nakit-akisi-basit-gunluk-haftalik-panosu",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "oee-calculator": {
    "slug": "oee-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "oee-equipment-effectiveness-calculator": {
    "slug": "oee-equipment-effectiveness-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "office-cleaning-bid-optimizer": {
    "slug": "office-cleaning-bid-optimizer",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "paint-coverage-calculator": {
    "slug": "paint-coverage-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "painting-job-profit-verdict": {
    "slug": "painting-job-profit-verdict",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "painting-rework-coverage-risk": {
    "slug": "painting-rework-coverage-risk",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "paketleme-malzemesi-strec-koli-sarfiyati": {
    "slug": "paketleme-malzemesi-strec-koli-sarfiyati",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "panel-shop-margin-verdict": {
    "slug": "panel-shop-margin-verdict",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "personel-devamsizlik-maliyeti-hesaplama": {
    "slug": "personel-devamsizlik-maliyeti-hesaplama",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "plastik-enjeksiyon-cevrim-suresi-tahmini": {
    "slug": "plastik-enjeksiyon-cevrim-suresi-tahmini",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "plumbing-job-margin-verdict": {
    "slug": "plumbing-job-margin-verdict",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "plumbing-leak-callback-cost": {
    "slug": "plumbing-leak-callback-cost",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "pnomatik-silindir-kuvvet-hesabi": {
    "slug": "pnomatik-silindir-kuvvet-hesabi",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "portion-cost-calculator": {
    "slug": "portion-cost-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "printing-reprint-margin-leak": {
    "slug": "printing-reprint-margin-leak",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "product-customer-profitability-calculator": {
    "slug": "product-customer-profitability-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "profit-margin-calculator": {
    "slug": "profit-margin-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "quality-cost-paf-calculator": {
    "slug": "quality-cost-paf-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "quote-price-profit-margin-calculator": {
    "slug": "quote-price-profit-margin-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "renovation-budget-optimizer": {
    "slug": "renovation-budget-optimizer",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "restaurant-menu-margin-leak": {
    "slug": "restaurant-menu-margin-leak",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "retail-inventory-turnover-risk": {
    "slug": "retail-inventory-turnover-risk",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "return-profit-erosion-tool": {
    "slug": "return-profit-erosion-tool",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "roi-calculator": {
    "slug": "roi-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "roofing-contract-margin-guard": {
    "slug": "roofing-contract-margin-guard",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "roofing-weather-delay-risk": {
    "slug": "roofing-weather-delay-risk",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "route-cost-calculator": {
    "slug": "route-cost-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "route-optimization-analyzer": {
    "slug": "route-optimization-analyzer",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "rulman-omur-hesabi-l10": {
    "slug": "rulman-omur-hesabi-l10",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "ruzgar-turbini-yaklasik-uretim-hesabi": {
    "slug": "ruzgar-turbini-yaklasik-uretim-hesabi",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "salary-cost-calculator": {
    "slug": "salary-cost-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "sample-size-calculator": {
    "slug": "sample-size-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "scrap-rate-calculator": {
    "slug": "scrap-rate-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "seed-rate-calculator": {
    "slug": "seed-rate-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "sgk-prim-hesaplama-isci-plus-isveren": {
    "slug": "sgk-prim-hesaplama-isci-plus-isveren",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "sheet-metal-quote-risk-tool": {
    "slug": "sheet-metal-quote-risk-tool",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "sheet-metal-scrap-risk": {
    "slug": "sheet-metal-scrap-risk",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "sheet-metal-weight-calculator": {
    "slug": "sheet-metal-weight-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "shop-rate-hourly-cost-calculator": {
    "slug": "shop-rate-hourly-cost-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "signage-bid-safe-price-tool": {
    "slug": "signage-bid-safe-price-tool",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "sirket-telefon-faturasi-hesaplama": {
    "slug": "sirket-telefon-faturasi-hesaplama",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "sofor-operator-gunluk-yevmiye-maliyeti": {
    "slug": "sofor-operator-gunluk-yevmiye-maliyeti",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "standard-deviation-calculator": {
    "slug": "standard-deviation-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "stopaj-hesaplama-kira-serbest-meslek": {
    "slug": "stopaj-hesaplama-kira-serbest-meslek",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "textile-fabric-waste-risk": {
    "slug": "textile-fabric-waste-risk",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "tir-kamyon-yuk-kapasitesi-hesaplama": {
    "slug": "tir-kamyon-yuk-kapasitesi-hesaplama",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "tolerance-stack-up-calculator": {
    "slug": "tolerance-stack-up-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "tool-life-calculator": {
    "slug": "tool-life-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "toplanti-saati-maliyeti-hesaplama": {
    "slug": "toplanti-saati-maliyeti-hesaplama",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "trafik-cezasi-gecikme-faizi-hesaplama": {
    "slug": "trafik-cezasi-gecikme-faizi-hesaplama",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "trip-budget-optimizer": {
    "slug": "trip-budget-optimizer",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "ups-kesintisiz-guc-kaynagi-secimi": {
    "slug": "ups-kesintisiz-guc-kaynagi-secimi",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "value-stream-map-vsm-calculator": {
    "slug": "value-stream-map-vsm-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "vehicle-depreciation-calculator": {
    "slug": "vehicle-depreciation-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "warehouse-space-cost-leak": {
    "slug": "warehouse-space-cost-leak",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "warehouse-storage-cost-calculator": {
    "slug": "warehouse-storage-cost-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "water-optimization-verdict": {
    "slug": "water-optimization-verdict",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "welding-bid-risk-analyzer": {
    "slug": "welding-bid-risk-analyzer",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": true,
      "hasDeepReport": true,
      "hasI18n": true
    }
  },
  "welding-cost-estimator": {
    "slug": "welding-cost-estimator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "yangin-merdiveni-kacis-yolu-genisligi-hesabi": {
    "slug": "yangin-merdiveni-kacis-yolu-genisligi-hesabi",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "yay-helisel-kuvvet-uzama-hesabi": {
    "slug": "yay-helisel-kuvvet-uzama-hesabi",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
  "z-score-calculator": {
    "slug": "z-score-calculator",
    "status": "verified",
    "auditGate": "Formula Source-of-Truth Audit Gate",
    "auditVersion": "v1",
    "verifiedAtSource": "quality-scan-report",
    "standardReference": "7 Muda quality standard",
    "checks": {
      "upgradeDecisionPass": true,
      "hasFormulaContract": true,
      "hasValidation": true,
      "hasTests": true,
      "hasQuickResult": false,
      "hasDeepReport": false,
      "hasI18n": false
    }
  },
};

export function getFormulaSourceAuditStatus(slug: string): FormulaSourceAuditStatus | null {
  return FORMULA_SOURCE_AUDIT_REGISTRY[slug] ?? null;
}

export function hasFormulaSourceAudit(slug: string): boolean {
  return Boolean(getFormulaSourceAuditStatus(slug));
}
