/* eslint-disable */
// @ts-nocheck

import type { CalculationReportCopy } from "@/lib/content/pdf/calculation-report-types";

const PDF_REPORT_COPY: Record<AppLocale, CalculationReportCopy> = {
  en: {
    subtitle: "SectorCalc · Academic-reviewed calculation report",
    inputsTitle: "Input parameters",
    resultsTitle: "Calculation results",
    primaryLabel: "Primary result",
    breakdownTitle: "Breakdown",
    footerLine1: "Generated by SectorCalc",
    footerLine2: "IIT Bombay · Prof. Dr. Neela Nataraj",
    footerLine3: "https://sectorcalc.com",
    disclaimer:
      "Technical simulation for decision support only. Not financial, legal or engineering advice.",
  },
  tr: {
    subtitle: "SectorCalc · Akademik metodoloji ile hesaplama raporu",
    inputsTitle: "Girdi parametreleri",
    resultsTitle: "Calculation sonuclari",
    primaryLabel: "Ana sonuc",
    breakdownTitle: "Dagilim",
    footerLine1: "Bu report SectorCalc tarafindan olusturulmustur",
    footerLine2: "IIT Bombay · Prof. Dr. Neela Nataraj",
    footerLine3: "https://sectorcalc.com",
    disclaimer:
      "Teknik simulasyon ve karar destegi icindir. Finansal, hukuki veya muhendislik tavsiyesi degildir.",
  },
  de: {
    subtitle: "SectorCalc · Akademisch geprufter Berechnungsbericht",
    inputsTitle: "Eingabeparameter",
    resultsTitle: "Berechnungsergebnisse",
    primaryLabel: "Hauptergebnis",
    breakdownTitle: "Aufschlusselung",
    footerLine1: "Erstellt von SectorCalc",
    footerLine2: "IIT Bombay · Prof. Dr. Neela Nataraj",
    footerLine3: "https://sectorcalc.com",
    disclaimer:
      "Technische Simulation zur Entscheidungsunterstutzung. Keine Finanz-, Rechts- oder Ingenieurberatung.",
  },
  fr: {
    subtitle: "SectorCalc · Rapport de calcul revu académiquement",
    inputsTitle: "Paramètres d'entrée",
    resultsTitle: "Résultats du calcul",
    primaryLabel: "Résultat principal",
    breakdownTitle: "Répartition",
    footerLine1: "Généré par SectorCalc",
    footerLine2: "IIT Bombay · Prof. Dr. Neela Nataraj",
    footerLine3: "https://sectorcalc.com",
    disclaimer:
      "Simulation technique d'aide à la décision. Pas un conseil financier, juridique ou d'ingénierie.",
  },
  es: {
    subtitle: "SectorCalc · Informe de cálculo con revisión académica",
    inputsTitle: "Parámetros de entrada",
    resultsTitle: "Resultados del cálculo",
    primaryLabel: "Resultado principal",
    breakdownTitle: "Desglose",
    footerLine1: "Generado por SectorCalc",
    footerLine2: "IIT Bombay · Prof. Dr. Neela Nataraj",
    footerLine3: "https://sectorcalc.com",
    disclaimer:
      "Simulación técnica de apoyo a decisiones. No es asesoramiento financiero, legal o de ingeniería.",
  },
  ar: {
    subtitle: "SectorCalc · تقرير حساب بمراجعة أكاديمية",
    inputsTitle: "مدخلات الحساب",
    resultsTitle: "نتائج الحساب",
    primaryLabel: "النتيجة الرئيسية",
    breakdownTitle: "التفصيل",
    footerLine1: "أنشأه SectorCalc",
    footerLine2: "IIT Bombay · Prof. Dr. Neela Nataraj",
    footerLine3: "https://sectorcalc.com",
    disclaimer: "محاكاة تقنية لدعم القرار. ليست مشورة مالية أو قانونية أو هندسية.",
  },
};

export function getCalculationReportCopy(locale: string): CalculationReportCopy {
  const key = locale as AppLocale;
  return PDF_REPORT_COPY[key] ?? PDF_REPORT_COPY.en;
}

export type CalculationReportEmailCopy = {
  readonly subject: string;
  readonly greeting: string;
  readonly body: string;
  readonly methodology: string;
  readonly upsellHtml: string;
  readonly signature: string;
  readonly attribution: string;
};

const EMAIL_COPY: Record<AppLocale, CalculationReportEmailCopy> = {
  en: {
    subject: "{toolName} calculation report",
    greeting: "Hello,",
    body: "Your <strong>{toolName}</strong> calculation report is attached.",
    methodology: "This report was generated using SectorCalc's transparent industrial methodology.",
    upsellHtml:
      'Explore <a href="https://sectorcalc.com/en/pricing" style="color:#1E3A5F;">Premium decision tools</a> for deeper loss analysis and export-ready reports.',
    signature: "SectorCalc Team",
    attribution: "IIT Bombay · Prof. Dr. Neela Nataraj",
  },
  tr: {
    subject: "{toolName} hesaplama raporunuz",
    greeting: "Merhaba,",
    body: "<strong>{toolName}</strong> hesaplama raporunuz ektedir.",
    methodology: "Bu report SectorCalc'in seffaf endustriyel metodolojisi ile olusturulmustur.",
    upsellHtml:
      'Daha detayli analizler icin <a href="https://sectorcalc.com/tr/pricing" style="color:#1E3A5F;">Premium araclarimizi</a> inceleyin.',
    signature: "SectorCalc Ekibi",
    attribution: "IIT Bombay · Prof. Dr. Neela Nataraj",
  },
  de: {
    subject: "{toolName} Berechnungsbericht",
    greeting: "Hallo,",
    body: "Ihr Berechnungsbericht fur <strong>{toolName}</strong> ist im Anhang.",
    methodology: "Dieser Bericht wurde mit der transparenten Industriemethodik von SectorCalc erstellt.",
    upsellHtml:
      'Entdecken Sie unsere <a href="https://sectorcalc.com/de/pricing" style="color:#1E3A5F;">Premium-Entscheidungstools</a> fur tiefere Verlustanalysen.',
    signature: "SectorCalc Team",
    attribution: "IIT Bombay · Prof. Dr. Neela Nataraj",
  },
  fr: {
    subject: "Rapport de calcul {toolName}",
    greeting: "Bonjour,",
    body: "Votre rapport de calcul <strong>{toolName}</strong> est en pièce jointe.",
    methodology: "Ce rapport a été généré avec la méthodologie industrielle transparente de SectorCalc.",
    upsellHtml:
      'Découvrez nos <a href="https://sectorcalc.com/fr/pricing" style="color:#1E3A5F;">outils Premium</a> pour une analyse plus approfondie.',
    signature: "Équipe SectorCalc",
    attribution: "IIT Bombay · Prof. Dr. Neela Nataraj",
  },
  es: {
    subject: "Informe de cálculo {toolName}",
    greeting: "Hola,",
    body: "Su informe de cálculo de <strong>{toolName}</strong> está adjunto.",
    methodology: "Este informe se generó con la metodología industrial transparente de SectorCalc.",
    upsellHtml:
      'Explore nuestras <a href="https://sectorcalc.com/es/pricing" style="color:#1E3A5F;">herramientas Premium</a> para un análisis más profundo.',
    signature: "Equipo SectorCalc",
    attribution: "IIT Bombay · Prof. Dr. Neela Nataraj",
  },
  ar: {
    subject: "تقرير حساب {toolName}",
    greeting: "مرحبًا،",
    body: "تقرير حساب <strong>{toolName}</strong> مرفق.",
    methodology: "تم إنشاء هذا التقرير باستخدام منهجية SectorCalc الصناعية الشفافة.",
    upsellHtml:
      'استكشف <a href="https://sectorcalc.com/ar/pricing" style="color:#1E3A5F;">أدوات Premium</a> لتحليل أعمq.',
    signature: "فريق SectorCalc",
    attribution: "IIT Bombay · Prof. Dr. Neela Nataraj",
  },
};

export function getCalculationReportEmailCopy(
  locale: string,
  toolName: string,
): CalculationReportEmailCopy {
  const key = locale as AppLocale;
  const base = EMAIL_COPY[key] ?? EMAIL_COPY.en;
  return {
    ...base,
    subject: base.subject.replace("{toolName}", toolName),
    body: base.body.replace("{toolName}", toolName),
  };
}

export function buildCalculationReportEmailHtml(
  locale: string,
  toolName: string,
): string {
  const copy = getCalculationReportEmailCopy(locale, toolName);
  return `
    <div style="font-family:Arial,sans-serif;color:#0F172A;line-height:1.6;">
      <p>${copy.greeting}</p>
      <p>${copy.body}</p>
      <p>${copy.methodology}</p>
      <p>${copy.upsellHtml}</p>
      <p>${copy.signature}</p>
      <p style="font-size:12px;color:#94A3B8;">${copy.attribution}</p>
    </div>
  `.trim();
}
