/**
 * Tool #14 — CBAM Maruziyeti Check
 * EmbeddedEmissions → CBAMCertificateCost → ComplianceScore
 */
import type { PremiumCalculatorSchema } from "@/lib/premium-schema/premium-calculator-schema";

const EU_ETS_DEFAULT_PRICE = 90;

export const CBAM_EXPOSURE_SCHEMA: PremiumCalculatorSchema = {
  id: "cbam-exposure-analyzer", legacyPaidSlug: "cbam-exposure-analyzer",
  name: "CBAM Maruziyeti Analizi", name_i18n: {"en":"CBAM Exposure Analysis","tr":"CBAM Maruziyeti Analizi"}, sectorSlug: "energy-carbon", category: "carbon",
  painStatement: "AB Sınırda Karbon Düzenlemesi (CBAM) kapsamında ürünlerin gömülü emisyonlarını raporlamayan ihracatçılar ciddi mali cezalarla karşılaşır. Bu araç CBAM mali yükümlülüğünü hesaplar ve uyum puanı verir.", painStatement_i18n: {"en":"Exporters who do not report embedded emissions of products under the EU CBAM face serious financial penalties. This tool calculates CBAM financial liability and provides a compliance score.","tr":"AB Sınırda Karbon Düzenlemesi (CBAM) kapsamında ürünlerin gömülü emisyonlarını raporlamayan ihracatçılar ciddi mali cezalarla karşılaşır. Bu araç CBAM mali yükümlülüğünü hesaplar ve uyum puanı verir."},
  inputs: [
    { id: "productionVolumeTons", label: "Üretim Hacmi", label_i18n: {"en":"Production Volume","tr":"Üretim Hacmi"}, type: "number", unit: "ton", required: true, smartDefault: 1000, validation: { min: 0 }, helper: "", expertMeaning: "Total production in metric tons", expertMeaning_i18n: {"en":"Total production in metric tons","tr":"Metrik ton cinsinden toplam üretim"} },
    { id: "naturalGasM3", label: "Doğal Gaz Tüketimi", label_i18n: {"en":"Natural Gas Consumption","tr":"Doğal Gaz Tüketimi"}, type: "number", unit: "m³", required: true, smartDefault: 500000, validation: { min: 0 }, helper: "", expertMeaning: "Natural gas consumption", expertMeaning_i18n: {"en":"Natural gas consumption","tr":"Doğal gaz tüketimi"} },
    { id: "coalTons", label: "Kömür Tüketimi", label_i18n: {"en":"Coal Consumption","tr":"Kömür Tüketimi"}, type: "number", unit: "ton", required: false, smartDefault: 0, validation: { min: 0 }, helper: "", expertMeaning: "Coal consumption", expertMeaning_i18n: {"en":"Coal consumption","tr":"Kömür tüketimi"} },
    { id: "electricityMwh", label: "Elektrik Tüketimi", label_i18n: {"en":"Electricity Consumption","tr":"Elektrik Tüketimi"}, type: "number", unit: "MWh", required: true, smartDefault: 5000, validation: { min: 0 }, helper: "", expertMeaning: "Electricity consumption", expertMeaning_i18n: {"en":"Electricity consumption","tr":"Elektrik tüketimi"} },
    { id: "processEmissions", label: "Proses Emisyonu", label_i18n: {"en":"Process Emissions","tr":"Proses Emisyonu"}, type: "number", unit: "tCO₂e", required: false, smartDefault: 200, validation: { min: 0 }, helper: "", expertMeaning: "Process CO₂ equivalent", expertMeaning_i18n: {"en":"Process CO₂ equivalent","tr":"Proses CO₂ eşdeğeri"} },
    { id: "renewableRatio", label: "Yenilenebilir Enerji Oranı", label_i18n: {"en":"Renewable Energy Share","tr":"Yenilenebilir Enerji Oranı"}, type: "number", unit: "%", required: false, smartDefault: 10, validation: { min: 0, max: 100 }, helper: "", expertMeaning: "Renewable energy share", expertMeaning_i18n: {"en":"Renewable energy share","tr":"Yenilenebilir enerji payı"} },
    { id: "exportVolumeTons", label: "AB'ye İhracat Hacmi", label_i18n: {"en":"Export Volume to EU","tr":"AB'ye İhracat Hacmi"}, type: "number", unit: "ton", required: true, smartDefault: 500, validation: { min: 0 }, helper: "", expertMeaning: "Export volume to EU", expertMeaning_i18n: {"en":"Export volume to EU","tr":"AB'ye ihracat hacmi"} },
    { id: "euEtsPrice", label: "EU ETS Fiyatı", label_i18n: {"en":"EU ETS Price","tr":"EU ETS Fiyatı"}, type: "number", unit: "USD/tCO₂e", required: false, smartDefault: EU_ETS_DEFAULT_PRICE, validation: { min: 0 }, helper: "", expertMeaning: "EU ETS carbon price", expertMeaning_i18n: {"en":"EU ETS carbon price","tr":"EU ETS karbon fiyatı"} },
    { id: "carbonLeakageFactor", label: "Karbon Kaçağı Faktörü", label_i18n: {"en":"Carbon Leakage Factor","tr":"Karbon Kaçağı Faktörü"}, type: "number", unit: "", required: false, smartDefault: 0.8, validation: { min: 0, max: 1 }, helper: "", expertMeaning: "Carbon leakage exposure factor", expertMeaning_i18n: {"en":"Carbon leakage exposure factor","tr":"Karbon kaçağı maruziyet faktörü"} },
    { id: "dataCompleteness", label: "Veri Tamamlık (%)", label_i18n: {"en":"Data Completeness (%)","tr":"Veri Tamamlık (%)"}, type: "number", unit: "%", required: false, smartDefault: 60, validation: { min: 0, max: 100 }, helper: "", expertMeaning: "Emissions data completeness", expertMeaning_i18n: {"en":"Emissions data completeness","tr":"Emisyon veri tamamlığı"} },
    { id: "verificationStatus", label: "Doğrulama Durumu (%)", label_i18n: {"en":"Verification Status (%)","tr":"Doğrulama Durumu (%)"}, type: "number", unit: "%", required: false, smartDefault: 40, validation: { min: 0, max: 100 }, helper: "", expertMeaning: "Third-party verification completeness", expertMeaning_i18n: {"en":"Third-party verification completeness","tr":"Üçüncü taraf doğrulama tamamlığı"} },
    { id: "reductionProgress", label: "Azaltım İlerlemesi (%)", label_i18n: {"en":"Reduction Progress (%)","tr":"Azaltım İlerlemesi (%)"}, type: "number", unit: "%", required: false, smartDefault: 25, validation: { min: 0, max: 100 }, helper: "", expertMeaning: "Emission reduction progress", expertMeaning_i18n: {"en":"Emission reduction progress","tr":"Emisyon azaltım ilerlemesi"} },
    { id: "directEmissionsInput", label: "Kapsam 1 Emisyon (Hesaplanmış)", label_i18n: {"en":"Scope 1 Emissions (Calculated)","tr":"Kapsam 1 Emisyon (Hesaplanmış)"}, type: "number", unit: "tCO₂e", required: true, smartDefault: 700, validation: { min: 0 }, helper: "Direkt emisyonlar (doğalgaz/kömür/proses).", helper_i18n: {"en":"Direkt emisyonlar (doğalgaz/kömür/proses).","tr":"Direkt emisyonlar (doğalgaz/kömür/proses)."}, expertMeaning: "Scope 1 direct emissions", expertMeaning_i18n: {"en":"Scope 1 direct emissions","tr":"Kapsam 1 direkt emisyonlar"} },
    { id: "indirectEmissionsInput", label: "Kapsam 2 Emisyon (Hesaplanmış)", label_i18n: {"en":"Scope 2 Emissions (Calculated)","tr":"Kapsam 2 Emisyon (Hesaplanmış)"}, type: "number", unit: "tCO₂e", required: true, smartDefault: 500, validation: { min: 0 }, helper: "Elektrik tüketimi kaynaklı emisyonlar.", helper_i18n: {"en":"Elektrik tüketimi kaynaklı emisyonlar.","tr":"Elektrik tüketimi kaynaklı emisyonlar."}, expertMeaning: "Scope 2 indirect emissions", expertMeaning_i18n: {"en":"Scope 2 indirect emissions","tr":"Kapsam 2 endirekt emisyonlar"} },
    { id: "totalEmbeddedInput", label: "Toplam Gömülü Emisyon", label_i18n: {"en":"Total Embedded Emissions","tr":"Toplam Gömülü Emisyon"}, type: "number", unit: "tCO₂e", required: true, smartDefault: 1200, validation: { min: 0 }, helper: "Kapsam 1 + Kapsam 2 toplamı.", helper_i18n: {"en":"Kapsam 1 + Kapsam 2 toplamı.","tr":"Kapsam 1 + Kapsam 2 toplamı."}, expertMeaning: "Total embedded emissions", expertMeaning_i18n: {"en":"Total embedded emissions","tr":"Toplam gömülü emisyon"} },
  ],
  outputs: [
    { id: "totalEmbedded", label: "Toplam Gömülü Emisyon", label_i18n: {"en":"Total Embedded Emissions","tr":"Toplam Gömülü Emisyon"}, unit: "tCO₂e", format: "number" },
    { id: "carbonIntensity", label: "Karbon Yoğunluğu", label_i18n: {"en":"Karbon Yogunlugu","tr":"Karbon Yoğunluğu"}, unit: "tCO₂e/ton", format: "number" },
    { id: "cbamCertificateCost", label: "CBAM Sertifika Maliyeti", label_i18n: {"en":"CBAM Sertifika Maliyeti","tr":"CBAM Sertifika Maliyeti"}, unit: "USD", format: "currency" },
    { id: "complianceScore", label: "Uyum Puanı (0-100)", label_i18n: {"en":"Uyum Puan (0-100)","tr":"Uyum Puanı (0-100)"}, unit: "", format: "score", isBigNumber: true },
  ],
  thresholds: [
    { fieldId: "cbamCertificateCost", warning: 10000, critical: 50000, direction: "higher_is_bad", warningMessage: "CBAM maliyeti > $10K — emisyon azaltım stratejisi geliştirilmeli.", warningMessage_i18n: {"en":"CBAM cost > $10K — develop emission reduction strategy.","tr":"CBAM maliyeti > $10K — emisyon azaltım stratejisi geliştirilmeli."}, criticalMessage: "CBAM maliyeti > $50K — acil uyum eylem planı gerekiyor.", criticalMessage_i18n: {"en":"CBAM cost > $50K — urgent compliance action plan required.","tr":"CBAM maliyeti > $50K — acil uyum eylem planı gerekiyor."} },
    { fieldId: "complianceScore", warning: 50, critical: 30, direction: "lower_is_bad", warningMessage: "Uyum puanı < 50 — veri ve doğrulama eksik.", warningMessage_i18n: {"en":"Uyum puanı < 50 — veri ve doğrulama eksik.","tr":"Uyum puanı < 50 — veri ve doğrulama eksik."}, criticalMessage: "Uyum puanı < 30 — CBAM raporlaması için yetersiz.", criticalMessage_i18n: {"en":"Uyum puanı < 30 — CBAM raporlaması için yetersiz.","tr":"Uyum puanı < 30 — CBAM raporlaması için yetersiz."} },
  ],
  formulaPipeline: [
    { formulaId: "carbon.embedded_emissions", inputMap: { directEmissions: "directEmissionsInput", indirectEmissions: "indirectEmissionsInput" }, outputId: "totalEmbedded" },
    { formulaId: "carbon.cbam_certificate_cost", inputMap: { embeddedEmissions: "totalEmbeddedInput", freeAllowance: "exportVolumeTons", euEtsPrice: "euEtsPrice" }, outputId: "cbamCertificateCost" },
    { formulaId: "carbon.compliance_score", inputMap: { dataCompleteness: "dataCompleteness", verificationStatus: "verificationStatus", reductionProgress: "reductionProgress" }, outputId: "complianceScore" },
  ],
  reportTemplate: { title: "CBAM Exposure Report", title_i18n: {"en":"CBAM Exposure Report","tr":"CBAM Exposure Report"}, sections: ["executive_summary", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.2, volatilityPercent: 20, targetMarginPercent: 25, assumptionNotes: ["Direct = NaturalGas×2.204 + Coal×2.86 (tCO₂e).", "Indirect = ElectricityMWh × GridFactor (0.447 for Turkey).", "CBAM cost = (Embedded - FreeAllowance) × EU_ETS_Price.", "Free allowance = Benchmark × Production × LeakageFactor.", "Compliance score = Data(0.3) + Verification(0.3) + Reduction(0.4).", "EU ETS assumed at $90/tCO₂e (2026 estimated)."],assumptionNotes_i18n:[{"en":"Direct = NaturalGas×2.204 + Coal×2.86 (tCO₂e).","tr":"Direct = NaturalGas×2.204 + Coal×2.86 (tCO₂e)."},{"en":"Indirect = ElectricityMWh × GridFactor (0.447 for Turkey).","tr":"Indirect = ElectricityMWh × GridFactor (0.447 for Turkey)."},{"en":"CBAM cost = (Embedded - FreeAllowance) × EU_ETS_Price.","tr":"CBAM cost = (Embedded - FreeAllowance) × EU_ETS_Price."},{"en":"Free allowance = Benchmark × Production × LeakageFactor.","tr":"Free allowance = Benchmark × Production × LeakageFactor."},{"en":"Compliance score = Data(0.3) + Verification(0.3) + Reduction(0.4).","tr":"Compliance score = Data(0.3) + Verification(0.3) + Reduction(0.4)."},{"en":"EU ETS assumed at $90/tCO₂e (2026 estimated).","tr":"EU ETS assumed at $90/tCO₂e (2026 estimated)."}]},
};
