/**
 * Tool — Supplier TCO
 */
import type { PremiumCalculatorSchema } from "@/lib/premium-schema/premium-calculator-schema";
export const SUPPLIER_PERFORMANCE_TCO_ANALYZER: PremiumCalculatorSchema = {
  id: "supplier-performance-tco-analyzer", legacyPaidSlug: "supplier-performance-tco-analyzer",
  name: "Tedarikçi TCO Performans Analizi", name_i18n: {"en":"Supplier TCO Performance Analysis","tr":"Tedarikçi TCO Performans Analizi"}, sectorSlug: "quality", category: "cost",
  painStatement: "Tedarikçi seçiminde sadece birim fiyata bakılır; kalite, lojistik, stok ve hurda maliyetleri hesaba katılmazsa gerçek toplam sahip olma maliyeti gizli kalır.", painStatement_i18n: {"en":"Supplier selection often focuses only on unit price; when quality, logistics, inventory, and scrap costs are ignored, the true total cost of ownership remains hidden.","tr":"Tedarikçi seçiminde sadece birim fiyata bakılır; kalite, lojistik, stok ve hurda maliyetleri hesaba katılmazsa gerçek toplam sahip olma maliyeti gizli kalır."},
  inputs: [
    { id: "unitPrice", label: "Birim Fiyat", label_i18n: {"en":"Unit Price","tr":"Birim Fiyat"}, type: "number", unit: "USD/adet", required: true, smartDefault: 5, validation: { min: 0.01 }, helper: "", expertMeaning: "Price per unit", expertMeaning_i18n: {"en":"Price per unit","tr":"Birim fiyat"} },
    { id: "annualVolume", label: "Yıllık Hacim", label_i18n: {"en":"Annual Volume","tr":"Yıllık Hacim"}, type: "number", unit: "adet", required: true, smartDefault: 50000, validation: { min: 1 }, helper: "", expertMeaning: "Annual purchase volume", expertMeaning_i18n: {"en":"Annual purchase volume","tr":"Yıllık satın alma hacmi"} },
    { id: "defectRate", label: "Hata Oranı", label_i18n: {"en":"Defect Rate","tr":"Hata Oranı"}, type: "number", unit: "%", required: true, smartDefault: 2, validation: { min: 0, max: 100 }, helper: "", expertMeaning: "Defect rate percentage", expertMeaning_i18n: {"en":"Defect rate percentage","tr":"Hata oranı yüzdesi"} },
    { id: "costPerDefect", label: "Hata Başına Maliyet", label_i18n: {"en":"Cost per Defect","tr":"Hata Başına Maliyet"}, type: "number", unit: "USD", required: true, smartDefault: 10, validation: { min: 0.01 }, helper: "", expertMeaning: "Cost per defective unit", expertMeaning_i18n: {"en":"Cost per defective unit","tr":"Hatalı birim başına maliyet"} },
    { id: "freightCostPerUnit", label: "Nakliye Birim Maliyeti", label_i18n: {"en":"Freight Cost per Unit","tr":"Nakliye Birim Maliyeti"}, type: "number", unit: "USD/adet", required: false, smartDefault: 0.5, validation: { min: 0 }, helper: "", expertMeaning: "Freight cost per unit", expertMeaning_i18n: {"en":"Freight cost per unit","tr":"Birim başına nakliye maliyeti"} },
    { id: "leadTimeDays", label: "Teslim Süresi", label_i18n: {"en":"Delivery Lead Time","tr":"Teslim Süresi"}, type: "number", unit: "gün", required: false, smartDefault: 14, validation: { min: 1 }, helper: "", expertMeaning: "Delivery lead time in days", expertMeaning_i18n: {"en":"Delivery lead time in days","tr":"Gün cinsinden teslim süresi"} },
    { id: "holdingCostPct", label: "Stok Taşıma Maliyeti Oranı", label_i18n: {"en":"Inventory Holding Cost Rate","tr":"Stok Taşıma Maliyeti Oranı"}, type: "number", unit: "%/yıl", required: false, smartDefault: 20, validation: { min: 0, max: 100 }, helper: "", expertMeaning: "Annual holding cost as % of unit price", expertMeaning_i18n: {"en":"Annual holding cost as % of unit price","tr":"Birim fiyatın yüzdesi olarak yıllık stok taşıma maliyeti"} },
    { id: "inspectionCostPerUnit", label: "Muayene Birim Maliyeti", label_i18n: {"en":"Inspection Cost per Unit","tr":"Muayene Birim Maliyeti"}, type: "number", unit: "USD/adet", required: false, smartDefault: 0.1, validation: { min: 0 }, helper: "", expertMeaning: "Inspection cost per unit", expertMeaning_i18n: {"en":"Inspection cost per unit","tr":"Birim başına muayene maliyeti"} },
  ],
  outputs: [
    { id: "supplierTco", label: "Toplam Sahip Olma Maliyeti (TCO)", label_i18n: {"en":"Total Cost of Ownership (TCO)","tr":"Toplam Sahip Olma Maliyeti (TCO)"}, unit: "USD/adet", format: "currency", isBigNumber: true },
  ],
  thresholds: [{ fieldId: "supplierTco", warning: 6, critical: 8, direction: "higher_is_bad", warningMessage: "TCO >$6/adet — tedarikçi performansı sorgulanmalı.", warningMessage_i18n: {"en":"TCO >$6/unit — question supplier performance.","tr":"TCO >$6/adet — tedarikçi performansı sorgulanmalı."}, criticalMessage: "TCO >$8/adet — alternatif tedarikçi değerlendirmesi gerekli.", criticalMessage_i18n: {"en":"TCO >$8/unit — evaluate alternative suppliers.","tr":"TCO >$8/adet — alternatif tedarikçi değerlendirmesi gerekli."} }],
  formulaPipeline: [
    { formulaId: "cost.supplier_tco", inputMap: { unitPrice: "unitPrice", annualVolume: "annualVolume", defectRate: "defectRate", costPerDefect: "costPerDefect", freightCostPerUnit: "freightCostPerUnit", leadTimeDays: "leadTimeDays", holdingCostPct: "holdingCostPct", inspectionCostPerUnit: "inspectionCostPerUnit" }, outputId: "supplierTco" },
  ],
  reportTemplate: { title: "Tedarikçi TCO Raporu", title_i18n: {"en":"Supplier TCO Report","tr":"Tedarikçi TCO Raporu"}, sections: ["executive_summary", "loss_breakdown", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.1, volatilityPercent: 10, targetMarginPercent: 15, assumptionNotes: ["TCO = birim fiyat + hata maliyeti + nakliye + muayene + stok taşıma.", "Hata maliyeti = hata oranı × hacim × birim hata maliyeti / hacim.", "Stok taşıma = teslim süresi × günlük talep × taşıma oranı × birim fiyat / hacim.", "Kalite maliyetleri TCO'nun ortalama %15-30'unu oluşturur."],assumptionNotes_i18n:[{"en":"TCO = unit price + defect cost + freight + inspection + inventory holding.","tr":"TCO = birim fiyat + hata maliyeti + nakliye + muayene + stok taşıma."},{"en":"Defect cost = defect rate × volume × cost per defect / volume.","tr":"Hata maliyeti = hata oranı × hacim × birim hata maliyeti / hacim."},{"en":"Inventory holding = lead time × daily demand × holding rate × unit price / volume.","tr":"Stok taşıma = teslim süresi × günlük talep × taşıma oranı × birim fiyat / hacim."},{"en":"Quality costs account for 15-30% of TCO on average.","tr":"Kalite maliyetleri TCO'nun ortalama %15-30'unu oluşturur."}] },
};
