/**
 * Tool #34 — VSM Finansal Dönüştürücü
 */
import type { PremiumCalculatorSchema } from "@/lib/premium-schema/premium-calculator-schema";
export const VSM_FINANCIAL_SCHEMA: PremiumCalculatorSchema = {
  id: "vsm-financial-converter-analyzer", legacyPaidSlug: "vsm-financial-converter-analyzer",
  name: "VSM Finansal Dönüştürücü", name_i18n: {"en":"VSM Financial Converter","tr":"VSM Finansal Dönüştürücü"}, sectorSlug: "quality", category: "cost",
  painStatement: "Value Stream Mapping (VSM) çalışmaları operasyonel süreçleri gösterir ancak finansal etkiyi ölçmez. Katma değersiz adımların parasal karşılığı bilinmezse iyileştirme önceliklendirilemez.", painStatement_i18n: {"en":"Value Stream Mapping (VSM) studies show operational processes but do not measure financial impact. If the monetary equivalent of non-value-added steps is unknown, improvements cannot be prioritized.","tr":"Value Stream Mapping (VSM) çalışmaları operasyonel süreçleri gösterir ancak finansal etkiyi ölçmez. Katma değersiz adımların parasal karşılığı bilinmezse iyileştirme önceliklendirilemez."},
  inputs: [
    { id: "totalLeadTime", label: "Toplam Teslim Süresi", label_i18n: {"en":"Total Lead Time","tr":"Toplam Teslim Süresi"}, type: "number", unit: "dk", required: true, smartDefault: 480, validation: { min: 1 }, helper: "", expertMeaning: "Total lead time from order to delivery", expertMeaning_i18n: {"en":"Total lead time from order to delivery","tr":"Siparişten teslimata toplam teslim süresi"} },
    { id: "valueAddedTime", label: "Katma Değerli Süre", label_i18n: {"en":"Value-Added Time","tr":"Katma Değerli Süre"}, type: "number", unit: "dk", required: true, smartDefault: 120, validation: { min: 1 }, helper: "", expertMeaning: "Value-added processing time", expertMeaning_i18n: {"en":"Value-added processing time","tr":"Katma değerli işlem süresi"} },
    { id: "dailyProduction", label: "Günlük Üretim Miktarı", label_i18n: {"en":"Daily Production Quantity","tr":"Günlük Üretim Miktarı"}, type: "number", unit: "adet/gün", required: true, smartDefault: 500, validation: { min: 1 }, helper: "", expertMeaning: "Daily production volume", expertMeaning_i18n: {"en":"Daily production volume","tr":"Günlük üretim hacmi"} },
    { id: "costPerMinute", label: "Dakika Başına Maliyet", label_i18n: {"en":"Cost Per Minute","tr":"Dakika Başına Maliyet"}, type: "number", unit: "USD/dk", required: true, smartDefault: 1.5, validation: { min: 0.01 }, helper: "", expertMeaning: "Operating cost per minute", expertMeaning_i18n: {"en":"Operating cost per minute","tr":"Dakika başına işletme maliyeti"} },
    { id: "operatingDays", label: "Çalışma Günü / Yıl", label_i18n: {"en":"Operating Days / Year","tr":"Çalışma Günü / Yıl"}, type: "number", unit: "gün", required: false, smartDefault: 240, validation: { min: 1 }, helper: "", expertMeaning: "Annual operating days", expertMeaning_i18n: {"en":"Annual operating days","tr":"Yıllık çalışma günü"} },
    { id: "reworkPercent", label: "Yeniden İşlem Oranı", label_i18n: {"en":"Rework Rate","tr":"Yeniden İşlem Oranı"}, type: "number", unit: "%", required: false, smartDefault: 5, validation: { min: 0, max: 100 }, helper: "", expertMeaning: "Rework percentage", expertMeaning_i18n: {"en":"Rework percentage","tr":"Yeniden işlem yüzdesi"} },
  ],
  outputs: [
    { id: "vsmLeadtimeCost", label: "Teslim Süresi Maliyeti", label_i18n: {"en":"Lead Time Cost","tr":"Teslim Süresi Maliyeti"}, unit: "USD/gün", format: "currency" },
    { id: "vsmValueAddedRatio", label: "Katma Değer Oranı", label_i18n: {"en":"Value-Added Ratio","tr":"Katma Değer Oranı"}, unit: "%", format: "percentage" },
    { id: "vsmNonValueAddedCost", label: "Katma Değersiz Maliyet", label_i18n: {"en":"Non-Value-Added Cost","tr":"Katma Değersiz Maliyet"}, unit: "USD/yıl", format: "currency", isBigNumber: true },
    { id: "vsmTotalFinancialImpact", label: "Toplam Finansal Etki", label_i18n: {"en":"Total Financial Impact","tr":"Toplam Finansal Etki"}, unit: "USD/yıl", format: "currency", isBigNumber: true },
  ],
  thresholds: [
    { fieldId: "vsmValueAddedRatio", warning: 30, critical: 15, direction: "lower_is_bad", warningMessage: "KD oranı < %30 — süreçte önemli katma değersiz adımlar var.", warningMessage_i18n: {"en":"VA ratio < 30% — there are significant non-value-added steps in the process.","tr":"KD oranı < %30 — süreçte önemli katma değersiz adımlar var."}, criticalMessage: "KD oranı < %15 — süreç köklü yeniden yapılandırılmalı.", criticalMessage_i18n: {"en":"VA ratio < 15% — process needs fundamental restructuring.","tr":"KD oranı < %15 — süreç köklü yeniden yapılandırılmalı."} },
    { fieldId: "vsmNonValueAddedCost", warning: 50000, critical: 150000, direction: "higher_is_bad", warningMessage: "KD maliyet > $50K — yalın dönüşüm önceliklendirilmeli.", warningMessage_i18n: {"en":"NVA cost > $50K — lean transformation should be prioritized.","tr":"KD maliyet > $50K — yalın dönüşüm önceliklendirilmeli."}, criticalMessage: "KD maliyet > $150K — acil VSM atölyesi planlanmalı.", criticalMessage_i18n: {"en":"NVA cost > $150K — urgent VSM workshop should be planned.","tr":"KD maliyet > $150K — acil VSM atölyesi planlanmalı."} },
  ],
  formulaPipeline: [
    { formulaId: "cost.vsm_leadtime_cost", inputMap: { totalLeadTime: "totalLeadTime", costPerMinute: "costPerMinute", dailyProduction: "dailyProduction" }, outputId: "vsmLeadtimeCost" },
    { formulaId: "measurement.vsm_value_added_ratio", inputMap: { valueAddedTime: "valueAddedTime", totalLeadTime: "totalLeadTime" }, outputId: "vsmValueAddedRatio" },
    { formulaId: "cost.vsm_non_value_added_cost", inputMap: { totalLeadTime: "totalLeadTime", valueAddedTime: "valueAddedTime", costPerMinute: "costPerMinute", dailyProduction: "dailyProduction", operatingDays: "operatingDays" }, outputId: "vsmNonValueAddedCost" },
    { formulaId: "cost.vsm_total_financial_impact", inputMap: { vsmNonValueAddedCost: "vsmNonValueAddedCost", vsmLeadtimeCost: "vsmLeadtimeCost", reworkPercent: "reworkPercent", dailyProduction: "dailyProduction", operatingDays: "operatingDays" }, outputId: "vsmTotalFinancialImpact" },
  ],
  reportTemplate: { title: "VSM Finansal Dönüştürücü Raporu", title_i18n: {"en":"VSM Financial Converter Report","tr":"VSM Finansal Dönüştürücü Raporu"}, sections: ["executive_summary", "loss_breakdown", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.2, volatilityPercent: 10, targetMarginPercent: 10, assumptionNotes: ["Katma değer oranı = KD süre / toplam teslim süresi.", "KD olmayan maliyet = (toplam - KD süre) × birim maliyet × üretim.", "Fire ve yeniden işlem maliyeti KD olmayan maliyete dahildir."],assumptionNotes_i18n:[{"en":"Value-added ratio = VA time / total lead time.","tr":"Katma değer oranı = KD süre / toplam teslim süresi."},{"en":"Non-value-added cost = (total - VA time) × unit cost × production.","tr":"KD olmayan maliyet = (toplam - KD süre) × birim maliyet × üretim."},{"en":"Scrap and rework costs are included in non-value-added cost.","tr":"Fire ve yeniden işlem maliyeti KD olmayan maliyete dahildir."}] },
};
