// SectorCalc Free V5.3.1 Public-Safe Tool Manifest
// This file is fs-free and contains NO formulas, NO private registry,
// NO schema contract body, NO internal trace.
// Only public-safe route metadata for sitemap, catalog, and routing use.
// AUTO-GENERATED — do not edit manually. Run scripts/generate-free-manifest.mjs

export interface FreeToolManifestEntry {
  slug: string;
  toolKey: string;
  toolName: string;
  route: string;
  accessTier: "FREE";
}

const FREE_TOOLS: FreeToolManifestEntry[] = [
  { slug: "2d_inverse_kinematics_calculator", toolKey: "2d_inverse_kinematics_calculator", toolName: "2d Inverse Kinematics Calculator", route: "/tools/free/2d_inverse_kinematics_calculator", accessTier: "FREE" },
  { slug: "abc_classification_calculator", toolKey: "abc_classification_calculator", toolName: "Abc Classification Calculator", route: "/tools/free/abc_classification_calculator", accessTier: "FREE" },
  { slug: "accounts_payable_turnover_calculator", toolKey: "accounts_payable_turnover_calculator", toolName: "Accounts Payable Turnover Calculator", route: "/tools/free/accounts_payable_turnover_calculator", accessTier: "FREE" },
  { slug: "accounts_receivable_turnover_calculator", toolKey: "accounts_receivable_turnover_calculator", toolName: "Accounts Receivable Turnover Calculator", route: "/tools/free/accounts_receivable_turnover_calculator", accessTier: "FREE" },
  { slug: "adc_resolution_calculator", toolKey: "adc_resolution_calculator", toolName: "Adc Resolution Calculator", route: "/tools/free/adc_resolution_calculator", accessTier: "FREE" },
  { slug: "adhesive_quantity_calculator", toolKey: "adhesive_quantity_calculator", toolName: "Adhesive Quantity Calculator", route: "/tools/free/adhesive_quantity_calculator", accessTier: "FREE" },
  { slug: "ai_token_cost_analyzer", toolKey: "ai_token_cost_analyzer", toolName: "AI Token Cost Analyzer", route: "/tools/free/ai_token_cost_analyzer", accessTier: "FREE" },
  { slug: "anchor_chain_length_calculator", toolKey: "anchor_chain_length_calculator", toolName: "Anchor Chain Length Calculator", route: "/tools/free/anchor_chain_length_calculator", accessTier: "FREE" },
  { slug: "angle_of_twist_calculator", toolKey: "angle_of_twist_calculator", toolName: "Angle Of Twist Calculator", route: "/tools/free/angle_of_twist_calculator", accessTier: "FREE" },
  { slug: "annualized_return_calculator", toolKey: "annualized_return_calculator", toolName: "Annualized Return Calculator", route: "/tools/free/annualized_return_calculator", accessTier: "FREE" },
  { slug: "annuity_income_calculator", toolKey: "annuity_income_calculator", toolName: "Annuity Income Calculator", route: "/tools/free/annuity_income_calculator", accessTier: "FREE" },
  { slug: "antenna_length_calculator", toolKey: "antenna_length_calculator", toolName: "Antenna Length Calculator", route: "/tools/free/antenna_length_calculator", accessTier: "FREE" },
  { slug: "api_latency_sla_calculator", toolKey: "api_latency_sla_calculator", toolName: "Api Latency Sla Calculator", route: "/tools/free/api_latency_sla_calculator", accessTier: "FREE" },
  { slug: "apr_calculator", toolKey: "apr_calculator", toolName: "Apr Calculator", route: "/tools/free/apr_calculator", accessTier: "FREE" },
  { slug: "asme_shaft_diameter_bending_torsion_calculator", toolKey: "asme_shaft_diameter_bending_torsion_calculator", toolName: "Asme Shaft Diameter Bending Torsion Calculator", route: "/tools/free/asme_shaft_diameter_bending_torsion_calculator", accessTier: "FREE" },
  { slug: "asset_allocation_calculator", toolKey: "asset_allocation_calculator", toolName: "Asset Allocation Calculator", route: "/tools/free/asset_allocation_calculator", accessTier: "FREE" },
  { slug: "audit_risk_calculator", toolKey: "audit_risk_calculator", toolName: "Audit Risk Calculator", route: "/tools/free/audit_risk_calculator", accessTier: "FREE" },
  { slug: "barn_ventilation_calculator", toolKey: "barn_ventilation_calculator", toolName: "Barn Ventilation Calculator", route: "/tools/free/barn_ventilation_calculator", accessTier: "FREE" },
  { slug: "baseboard_length_calculator", toolKey: "baseboard_length_calculator", toolName: "Baseboard Length Calculator", route: "/tools/free/baseboard_length_calculator", accessTier: "FREE" },
  { slug: "battery_backup_time_calculator", toolKey: "battery_backup_time_calculator", toolName: "Battery Backup Time Calculator", route: "/tools/free/battery_backup_time_calculator", accessTier: "FREE" },
  { slug: "beam_deflection_calculator", toolKey: "beam_deflection_calculator", toolName: "Beam Deflection Calculator", route: "/tools/free/beam_deflection_calculator", accessTier: "FREE" },
  { slug: "beam_reaction_calculator", toolKey: "beam_reaction_calculator", toolName: "Beam Reaction Calculator", route: "/tools/free/beam_reaction_calculator", accessTier: "FREE" },
  { slug: "bearing_wall_stress_calculator", toolKey: "bearing_wall_stress_calculator", toolName: "Bearing Wall Stress Calculator", route: "/tools/free/bearing_wall_stress_calculator", accessTier: "FREE" },
  { slug: "bernoulli_pressure_calculator", toolKey: "bernoulli_pressure_calculator", toolName: "Bernoulli Pressure Calculator", route: "/tools/free/bernoulli_pressure_calculator", accessTier: "FREE" },
  { slug: "bilge_discharge_time_calculator", toolKey: "bilge_discharge_time_calculator", toolName: "Bilge Discharge Time Calculator", route: "/tools/free/bilge_discharge_time_calculator", accessTier: "FREE" },
  { slug: "black_scholes_calculator", toolKey: "black_scholes_calculator", toolName: "Black Scholes Calculator", route: "/tools/free/black_scholes_calculator", accessTier: "FREE" },
  { slug: "bobbin_yarn_length_calculator", toolKey: "bobbin_yarn_length_calculator", toolName: "Bobbin Yarn Length Calculator", route: "/tools/free/bobbin_yarn_length_calculator", accessTier: "FREE" },
  { slug: "bond_price_calculator", toolKey: "bond_price_calculator", toolName: "Bond Price Calculator", route: "/tools/free/bond_price_calculator", accessTier: "FREE" },
  { slug: "bottleneck_analysis_calculator", toolKey: "bottleneck_analysis_calculator", toolName: "Bottleneck Analysis Calculator", route: "/tools/free/bottleneck_analysis_calculator", accessTier: "FREE" },
  { slug: "break-even-and-margin-of-safety-analysis", toolKey: "break-even-and-margin-of-safety-analysis", toolName: "Break-Even & Margin of Safety Analysis", route: "/tools/free/break-even-and-margin-of-safety-analysis", accessTier: "FREE" },
  { slug: "breeam_leed_score_calculator", toolKey: "breeam_leed_score_calculator", toolName: "Breeam Leed Score Calculator", route: "/tools/free/breeam_leed_score_calculator", accessTier: "FREE" },
  { slug: "building_load_factor_calculator", toolKey: "building_load_factor_calculator", toolName: "Building Load Factor Calculator", route: "/tools/free/building_load_factor_calculator", accessTier: "FREE" },
  { slug: "building_shadow_duration_calculator", toolKey: "building_shadow_duration_calculator", toolName: "Building Shadow Duration Calculator", route: "/tools/free/building_shadow_duration_calculator", accessTier: "FREE" },
  { slug: "buoyant_force_calculator", toolKey: "buoyant_force_calculator", toolName: "Buoyant Force Calculator", route: "/tools/free/buoyant_force_calculator", accessTier: "FREE" },
  { slug: "burn_rate_calculator", toolKey: "burn_rate_calculator", toolName: "Burn Rate Calculator", route: "/tools/free/burn_rate_calculator", accessTier: "FREE" },
  { slug: "business_valuation_multiple_calculator", toolKey: "business_valuation_multiple_calculator", toolName: "Business Valuation Multiple Calculator", route: "/tools/free/business_valuation_multiple_calculator", accessTier: "FREE" },
  { slug: "cac_to_clv_ratio_calculator", toolKey: "cac_to_clv_ratio_calculator", toolName: "Cac To Clv Ratio Calculator", route: "/tools/free/cac_to_clv_ratio_calculator", accessTier: "FREE" },
  { slug: "cagr_calculator", toolKey: "cagr_calculator", toolName: "Cagr Calculator", route: "/tools/free/cagr_calculator", accessTier: "FREE" },
  { slug: "calibration_drift_calculator", toolKey: "calibration_drift_calculator", toolName: "Calibration Drift Calculator", route: "/tools/free/calibration_drift_calculator", accessTier: "FREE" },
  { slug: "cap_rate_calculator", toolKey: "cap_rate_calculator", toolName: "Cap Rate Calculator", route: "/tools/free/cap_rate_calculator", accessTier: "FREE" },
  { slug: "cap_table_calculator", toolKey: "cap_table_calculator", toolName: "Cap Table Calculator", route: "/tools/free/cap_table_calculator", accessTier: "FREE" },
  { slug: "capacitive_reactance_calculator", toolKey: "capacitive_reactance_calculator", toolName: "Capacitive Reactance Calculator", route: "/tools/free/capacitive_reactance_calculator", accessTier: "FREE" },
  { slug: "capital_gains_tax_calculator", toolKey: "capital_gains_tax_calculator", toolName: "Capital Gains Tax Calculator", route: "/tools/free/capital_gains_tax_calculator", accessTier: "FREE" },
  { slug: "capm_cost_of_equity_calculator", toolKey: "capm_cost_of_equity_calculator", toolName: "Capm Cost Of Equity Calculator", route: "/tools/free/capm_cost_of_equity_calculator", accessTier: "FREE" },
  { slug: "carbon_footprint_calculator", toolKey: "carbon_footprint_calculator", toolName: "Carbon Footprint Calculator", route: "/tools/free/carbon_footprint_calculator", accessTier: "FREE" },
  { slug: "carbon_offset_trees_calculator", toolKey: "carbon_offset_trees_calculator", toolName: "Carbon Offset Trees Calculator", route: "/tools/free/carbon_offset_trees_calculator", accessTier: "FREE" },
  { slug: "carnot_efficiency_calculator", toolKey: "carnot_efficiency_calculator", toolName: "Carnot Efficiency Calculator", route: "/tools/free/carnot_efficiency_calculator", accessTier: "FREE" },
  { slug: "cash_conversion_cycle_calculator", toolKey: "cash_conversion_cycle_calculator", toolName: "Cash Conversion Cycle Calculator", route: "/tools/free/cash_conversion_cycle_calculator", accessTier: "FREE" },
  { slug: "cash_flow_gap_analysis", toolKey: "cash_flow_gap_analysis", toolName: "Cash Flow Gap Analysis", route: "/tools/free/cash_flow_gap_analysis", accessTier: "FREE" },
  { slug: "cash_on_cash_return_calculator", toolKey: "cash_on_cash_return_calculator", toolName: "Cash On Cash Return Calculator", route: "/tools/free/cash_on_cash_return_calculator", accessTier: "FREE" },
  { slug: "cash_out_refinance_calculator", toolKey: "cash_out_refinance_calculator", toolName: "Cash Out Refinance Calculator", route: "/tools/free/cash_out_refinance_calculator", accessTier: "FREE" },
  { slug: "chain_drive_calculator", toolKey: "chain_drive_calculator", toolName: "Chain Drive Calculator", route: "/tools/free/chain_drive_calculator", accessTier: "FREE" },
  { slug: "chair_rail_calculator", toolKey: "chair_rail_calculator", toolName: "Chair Rail Calculator", route: "/tools/free/chair_rail_calculator", accessTier: "FREE" },
  { slug: "circular_economy_ratio_calculator", toolKey: "circular_economy_ratio_calculator", toolName: "Circular Economy Ratio Calculator", route: "/tools/free/circular_economy_ratio_calculator", accessTier: "FREE" },
  { slug: "clamping_force_calculator", toolKey: "clamping_force_calculator", toolName: "Clamping Force Calculator", route: "/tools/free/clamping_force_calculator", accessTier: "FREE" },
  { slug: "cleaning_bid_optimizer", toolKey: "cleaning_bid_optimizer", toolName: "Cleaning Bid Optimizer", route: "/tools/free/cleaning_bid_optimizer", accessTier: "FREE" },
  { slug: "clearance_interference_calculator", toolKey: "clearance_interference_calculator", toolName: "Clearance Interference Calculator", route: "/tools/free/clearance_interference_calculator", accessTier: "FREE" },
  { slug: "click_through_rate_calculator", toolKey: "click_through_rate_calculator", toolName: "Click Through Rate Calculator", route: "/tools/free/click_through_rate_calculator", accessTier: "FREE" },
  { slug: "closing_costs_calculator", toolKey: "closing_costs_calculator", toolName: "Closing Costs Calculator", route: "/tools/free/closing_costs_calculator", accessTier: "FREE" },
  { slug: "cold_storage_heat_gain_calculator", toolKey: "cold_storage_heat_gain_calculator", toolName: "Cold Storage Heat Gain Calculator", route: "/tools/free/cold_storage_heat_gain_calculator", accessTier: "FREE" },
  { slug: "compound_interest_calculator", toolKey: "compound_interest_calculator", toolName: "Compound Interest Calculator", route: "/tools/free/compound_interest_calculator", accessTier: "FREE" },
  { slug: "compound_late_interest_calculator", toolKey: "compound_late_interest_calculator", toolName: "Compound Late Interest Calculator", route: "/tools/free/compound_late_interest_calculator", accessTier: "FREE" },
  { slug: "constrained_pipe_axial_thermal_stress_calculator", toolKey: "constrained_pipe_axial_thermal_stress_calculator", toolName: "Constrained Pipe Axial Thermal Stress Calculator", route: "/tools/free/constrained_pipe_axial_thermal_stress_calculator", accessTier: "FREE" },
  { slug: "consulting_hourly_rate_calculator", toolKey: "consulting_hourly_rate_calculator", toolName: "Consulting Hourly Rate Calculator", route: "/tools/free/consulting_hourly_rate_calculator", accessTier: "FREE" },
  { slug: "container_loading_calculator", toolKey: "container_loading_calculator", toolName: "Container Loading Calculator", route: "/tools/free/container_loading_calculator", accessTier: "FREE" },
  { slug: "continuous_compounding_calculator", toolKey: "continuous_compounding_calculator", toolName: "Continuous Compounding Calculator", route: "/tools/free/continuous_compounding_calculator", accessTier: "FREE" },
  { slug: "contract_incentive_analysis", toolKey: "contract_incentive_analysis", toolName: "Contract Incentive Analysis", route: "/tools/free/contract_incentive_analysis", accessTier: "FREE" },
  { slug: "contribution_margin_calculator", toolKey: "contribution_margin_calculator", toolName: "Contribution Margin Calculator", route: "/tools/free/contribution_margin_calculator", accessTier: "FREE" },
  { slug: "conversion_rate_calculator", toolKey: "conversion_rate_calculator", toolName: "Conversion Rate Calculator", route: "/tools/free/conversion_rate_calculator", accessTier: "FREE" },
  { slug: "convertible_note_calculator", toolKey: "convertible_note_calculator", toolName: "Convertible Note Calculator", route: "/tools/free/convertible_note_calculator", accessTier: "FREE" },
  { slug: "correlation_regression_calculator", toolKey: "correlation_regression_calculator", toolName: "Correlation Regression Calculator", route: "/tools/free/correlation_regression_calculator", accessTier: "FREE" },
  { slug: "cost_per_click_calculator", toolKey: "cost_per_click_calculator", toolName: "Cost Per Click Calculator", route: "/tools/free/cost_per_click_calculator", accessTier: "FREE" },
  { slug: "cost_per_mille_calculator", toolKey: "cost_per_mille_calculator", toolName: "Cost Per Mille Calculator", route: "/tools/free/cost_per_mille_calculator", accessTier: "FREE" },
  { slug: "credit_card_processing_fee_calculator", toolKey: "credit_card_processing_fee_calculator", toolName: "Credit Card Processing Fee Calculator", route: "/tools/free/credit_card_processing_fee_calculator", accessTier: "FREE" },
  { slug: "crop_yield_loss_analyzer", toolKey: "crop_yield_loss_analyzer", toolName: "Crop Yield Loss Analyzer", route: "/tools/free/crop_yield_loss_analyzer", accessTier: "FREE" },
  { slug: "customer_acquisition_cost_calculator", toolKey: "customer_acquisition_cost_calculator", toolName: "Customer Acquisition Cost Calculator", route: "/tools/free/customer_acquisition_cost_calculator", accessTier: "FREE" },
  { slug: "customer_churn_rate_calculator", toolKey: "customer_churn_rate_calculator", toolName: "Customer Churn Rate Calculator", route: "/tools/free/customer_churn_rate_calculator", accessTier: "FREE" },
  { slug: "customer_lifetime_value_calculator", toolKey: "customer_lifetime_value_calculator", toolName: "Customer Lifetime Value Calculator", route: "/tools/free/customer_lifetime_value_calculator", accessTier: "FREE" },
  { slug: "customs_duty_calculator", toolKey: "customs_duty_calculator", toolName: "Customs Duty Calculator", route: "/tools/free/customs_duty_calculator", accessTier: "FREE" },
  { slug: "daily_compound_interest_calculator", toolKey: "daily_compound_interest_calculator", toolName: "Daily Compound Interest Calculator", route: "/tools/free/daily_compound_interest_calculator", accessTier: "FREE" },
  { slug: "dairy_profit_detector", toolKey: "dairy_profit_detector", toolName: "Dairy Profit Detector", route: "/tools/free/dairy_profit_detector", accessTier: "FREE" },
  { slug: "data_backup_time_calculator", toolKey: "data_backup_time_calculator", toolName: "Data Backup Time Calculator", route: "/tools/free/data_backup_time_calculator", accessTier: "FREE" },
  { slug: "dcf_valuation_calculator", toolKey: "dcf_valuation_calculator", toolName: "Dcf Valuation Calculator", route: "/tools/free/dcf_valuation_calculator", accessTier: "FREE" },
  { slug: "debt_service_coverage_ratio_calculator", toolKey: "debt_service_coverage_ratio_calculator", toolName: "Debt Service Coverage Ratio Calculator", route: "/tools/free/debt_service_coverage_ratio_calculator", accessTier: "FREE" },
  { slug: "deck_board_calculator", toolKey: "deck_board_calculator", toolName: "Deck Board Calculator", route: "/tools/free/deck_board_calculator", accessTier: "FREE" },
  { slug: "demand_forecast_stock_cost_analyzer", toolKey: "demand_forecast_stock_cost_analyzer", toolName: "Demand Forecast Stock Cost Analyzer", route: "/tools/free/demand_forecast_stock_cost_analyzer", accessTier: "FREE" },
  { slug: "density_converter", toolKey: "density_converter", toolName: "Density Converter", route: "/tools/free/density_converter", accessTier: "FREE" },
  { slug: "depreciation_calculator", toolKey: "depreciation_calculator", toolName: "Depreciation Calculator", route: "/tools/free/depreciation_calculator", accessTier: "FREE" },
  { slug: "discounted_payback_calculator", toolKey: "discounted_payback_calculator", toolName: "Discounted Payback Calculator", route: "/tools/free/discounted_payback_calculator", accessTier: "FREE" },
  { slug: "dividend_reinvestment_calculator", toolKey: "dividend_reinvestment_calculator", toolName: "Dividend Reinvestment Calculator", route: "/tools/free/dividend_reinvestment_calculator", accessTier: "FREE" },
  { slug: "dividend_tax_calculator", toolKey: "dividend_tax_calculator", toolName: "Dividend Tax Calculator", route: "/tools/free/dividend_tax_calculator", accessTier: "FREE" },
  { slug: "draft_angle_calculator", toolKey: "draft_angle_calculator", toolName: "Draft Angle Calculator", route: "/tools/free/draft_angle_calculator", accessTier: "FREE" },
  { slug: "drill_string_torque_calculator", toolKey: "drill_string_torque_calculator", toolName: "Drill String Torque Calculator", route: "/tools/free/drill_string_torque_calculator", accessTier: "FREE" },
  { slug: "drip_irrigation_pipe_calculator", toolKey: "drip_irrigation_pipe_calculator", toolName: "Drip Irrigation Pipe Calculator", route: "/tools/free/drip_irrigation_pipe_calculator", accessTier: "FREE" },
  { slug: "drying_time_calculator", toolKey: "drying_time_calculator", toolName: "Drying Time Calculator", route: "/tools/free/drying_time_calculator", accessTier: "FREE" },
  { slug: "drywall_sheet_calculator", toolKey: "drywall_sheet_calculator", toolName: "Drywall Sheet Calculator", route: "/tools/free/drywall_sheet_calculator", accessTier: "FREE" },
  { slug: "dupont_roi_calculator", toolKey: "dupont_roi_calculator", toolName: "Dupont Roi Calculator", route: "/tools/free/dupont_roi_calculator", accessTier: "FREE" },
  { slug: "earthquake_pga_calculator", toolKey: "earthquake_pga_calculator", toolName: "Earthquake Pga Calculator", route: "/tools/free/earthquake_pga_calculator", accessTier: "FREE" },
  { slug: "ebitda_calculator", toolKey: "ebitda_calculator", toolName: "Ebitda Calculator", route: "/tools/free/ebitda_calculator", accessTier: "FREE" },
  { slug: "ecommerce_profit_calculator", toolKey: "ecommerce_profit_calculator", toolName: "Ecommerce Profit Calculator", route: "/tools/free/ecommerce_profit_calculator", accessTier: "FREE" },
  { slug: "economic_order_quantity_calculator", toolKey: "economic_order_quantity_calculator", toolName: "Economic Order Quantity Calculator", route: "/tools/free/economic_order_quantity_calculator", accessTier: "FREE" },
  { slug: "effective_annual_rate_calculator", toolKey: "effective_annual_rate_calculator", toolName: "Effective Annual Rate Calculator", route: "/tools/free/effective_annual_rate_calculator", accessTier: "FREE" },
  { slug: "effective_radiation_dose_calculator", toolKey: "effective_radiation_dose_calculator", toolName: "Effective Radiation Dose Calculator", route: "/tools/free/effective_radiation_dose_calculator", accessTier: "FREE" },
  { slug: "employee_turnover_cost_analyzer", toolKey: "employee_turnover_cost_analyzer", toolName: "Employee Turnover Cost Analyzer", route: "/tools/free/employee_turnover_cost_analyzer", accessTier: "FREE" },
  { slug: "energy_density_calculator", toolKey: "energy_density_calculator", toolName: "Energy Density Calculator", route: "/tools/free/energy_density_calculator", accessTier: "FREE" },
  { slug: "engine_torque_calculator", toolKey: "engine_torque_calculator", toolName: "Engine Torque Calculator", route: "/tools/free/engine_torque_calculator", accessTier: "FREE" },
  { slug: "engineering_strain_calculator", toolKey: "engineering_strain_calculator", toolName: "Engineering Strain Calculator", route: "/tools/free/engineering_strain_calculator", accessTier: "FREE" },
  { slug: "equity_dilution_calculator", toolKey: "equity_dilution_calculator", toolName: "Equity Dilution Calculator", route: "/tools/free/equity_dilution_calculator", accessTier: "FREE" },
  { slug: "esg_score_calculator", toolKey: "esg_score_calculator", toolName: "Esg Score Calculator", route: "/tools/free/esg_score_calculator", accessTier: "FREE" },
  { slug: "espp_calculator", toolKey: "espp_calculator", toolName: "Espp Calculator", route: "/tools/free/espp_calculator", accessTier: "FREE" },
  { slug: "etf_return_calculator", toolKey: "etf_return_calculator", toolName: "Etf Return Calculator", route: "/tools/free/etf_return_calculator", accessTier: "FREE" },
  { slug: "eu_import_vat_calculator", toolKey: "eu_import_vat_calculator", toolName: "Eu Import Vat Calculator", route: "/tools/free/eu_import_vat_calculator", accessTier: "FREE" },
  { slug: "ev_charging_time_calculator", toolKey: "ev_charging_time_calculator", toolName: "Ev Charging Time Calculator", route: "/tools/free/ev_charging_time_calculator", accessTier: "FREE" },
  { slug: "ev_range_calculator", toolKey: "ev_range_calculator", toolName: "Ev Range Calculator", route: "/tools/free/ev_range_calculator", accessTier: "FREE" },
  { slug: "eva_calculator", toolKey: "eva_calculator", toolName: "Eva Calculator", route: "/tools/free/eva_calculator", accessTier: "FREE" },
  { slug: "extruder_output_calculator", toolKey: "extruder_output_calculator", toolName: "Extruder Output Calculator", route: "/tools/free/extruder_output_calculator", accessTier: "FREE" },
  { slug: "fabric_cutting_optimizer", toolKey: "fabric_cutting_optimizer", toolName: "Fabric Cutting Optimizer", route: "/tools/free/fabric_cutting_optimizer", accessTier: "FREE" },
  { slug: "fabric_shrinkage_calculator", toolKey: "fabric_shrinkage_calculator", toolName: "Fabric Shrinkage Calculator", route: "/tools/free/fabric_shrinkage_calculator", accessTier: "FREE" },
  { slug: "fabric_weight_calculator", toolKey: "fabric_weight_calculator", toolName: "Fabric Weight Calculator", route: "/tools/free/fabric_weight_calculator", accessTier: "FREE" },
  { slug: "faraday_electrolysis_calculator", toolKey: "faraday_electrolysis_calculator", toolName: "Faraday Electrolysis Calculator", route: "/tools/free/faraday_electrolysis_calculator", accessTier: "FREE" },
  { slug: "fcff_fcfe_calculator", toolKey: "fcff_fcfe_calculator", toolName: "Fcff Fcfe Calculator", route: "/tools/free/fcff_fcfe_calculator", accessTier: "FREE" },
  { slug: "fiber_optic_loss_calculator", toolKey: "fiber_optic_loss_calculator", toolName: "Fiber Optic Loss Calculator", route: "/tools/free/fiber_optic_loss_calculator", accessTier: "FREE" },
  { slug: "fire_load_calculator", toolKey: "fire_load_calculator", toolName: "Fire Load Calculator", route: "/tools/free/fire_load_calculator", accessTier: "FREE" },
  { slug: "fire_pump_power_calculator", toolKey: "fire_pump_power_calculator", toolName: "Fire Pump Power Calculator", route: "/tools/free/fire_pump_power_calculator", accessTier: "FREE" },
  { slug: "flight_cost_calculator", toolKey: "flight_cost_calculator", toolName: "Flight Cost Calculator", route: "/tools/free/flight_cost_calculator", accessTier: "FREE" },
  { slug: "forex_profit_calculator", toolKey: "forex_profit_calculator", toolName: "Forex Profit Calculator", route: "/tools/free/forex_profit_calculator", accessTier: "FREE" },
  { slug: "freelancer_hourly_rate_calculator", toolKey: "freelancer_hourly_rate_calculator", toolName: "Freelancer Hourly Rate Calculator", route: "/tools/free/freelancer_hourly_rate_calculator", accessTier: "FREE" },
  { slug: "freight_cost_calculator", toolKey: "freight_cost_calculator", toolName: "Freight Cost Calculator", route: "/tools/free/freight_cost_calculator", accessTier: "FREE" },
  { slug: "fuel_cost_calculator", toolKey: "fuel_cost_calculator", toolName: "Fuel Cost Calculator", route: "/tools/free/fuel_cost_calculator", accessTier: "FREE" },
  { slug: "fund_return_calculator", toolKey: "fund_return_calculator", toolName: "Fund Return Calculator", route: "/tools/free/fund_return_calculator", accessTier: "FREE" },
  { slug: "futures_profit_calculator", toolKey: "futures_profit_calculator", toolName: "Futures Profit Calculator", route: "/tools/free/futures_profit_calculator", accessTier: "FREE" },
  { slug: "gage_r_and_r_calculator", toolKey: "gage_r_and_r_calculator", toolName: "Gage R And R Calculator", route: "/tools/free/gage_r_and_r_calculator", accessTier: "FREE" },
  { slug: "gear_root_bending_stress_lewis_calculator", toolKey: "gear_root_bending_stress_lewis_calculator", toolName: "Gear Root Bending Stress Lewis Calculator", route: "/tools/free/gear_root_bending_stress_lewis_calculator", accessTier: "FREE" },
  { slug: "gravel_weight_calculator", toolKey: "gravel_weight_calculator", toolName: "Gravel Weight Calculator", route: "/tools/free/gravel_weight_calculator", accessTier: "FREE" },
  { slug: "greywater_savings_calculator", toolKey: "greywater_savings_calculator", toolName: "Greywater Savings Calculator", route: "/tools/free/greywater_savings_calculator", accessTier: "FREE" },
  { slug: "gross_net_profit_calculator", toolKey: "gross_net_profit_calculator", toolName: "Gross Net Profit Calculator", route: "/tools/free/gross_net_profit_calculator", accessTier: "FREE" },
  { slug: "hardness_conversion_calculator", toolKey: "hardness_conversion_calculator", toolName: "Hardness Conversion Calculator", route: "/tools/free/hardness_conversion_calculator", accessTier: "FREE" },
  { slug: "heat_transfer_rate_calculator", toolKey: "heat_transfer_rate_calculator", toolName: "Heat Transfer Rate Calculator", route: "/tools/free/heat_transfer_rate_calculator", accessTier: "FREE" },
  { slug: "hookes_law_normal_stress_calculator", toolKey: "hookes_law_normal_stress_calculator", toolName: "Hookes Law Normal Stress Calculator", route: "/tools/free/hookes_law_normal_stress_calculator", accessTier: "FREE" },
  { slug: "horsepower_converter", toolKey: "horsepower_converter", toolName: "Horsepower Converter", route: "/tools/free/horsepower_converter", accessTier: "FREE" },
  { slug: "hydroelectric_power_calculator", toolKey: "hydroelectric_power_calculator", toolName: "Hydroelectric Power Calculator", route: "/tools/free/hydroelectric_power_calculator", accessTier: "FREE" },
  { slug: "hydrostatic_pressure_fluid_column_calculator", toolKey: "hydrostatic_pressure_fluid_column_calculator", toolName: "Hydrostatic Pressure Fluid Column Calculator", route: "/tools/free/hydrostatic_pressure_fluid_column_calculator", accessTier: "FREE" },
  { slug: "indicated_horsepower_calculator", toolKey: "indicated_horsepower_calculator", toolName: "Indicated Horsepower Calculator", route: "/tools/free/indicated_horsepower_calculator", accessTier: "FREE" },
  { slug: "inductive_reactance_calculator", toolKey: "inductive_reactance_calculator", toolName: "Inductive Reactance Calculator", route: "/tools/free/inductive_reactance_calculator", accessTier: "FREE" },
  { slug: "inflation_adjustment_calculator", toolKey: "inflation_adjustment_calculator", toolName: "Inflation Adjustment Calculator", route: "/tools/free/inflation_adjustment_calculator", accessTier: "FREE" },
  { slug: "interference_fit_contact_pressure_calculator", toolKey: "interference_fit_contact_pressure_calculator", toolName: "Interference Fit Contact Pressure Calculator", route: "/tools/free/interference_fit_contact_pressure_calculator", accessTier: "FREE" },
  { slug: "inventory_turnover_calculator", toolKey: "inventory_turnover_calculator", toolName: "Inventory Turnover Calculator", route: "/tools/free/inventory_turnover_calculator", accessTier: "FREE" },
  { slug: "inventory_turnover_rate_calculator", toolKey: "inventory_turnover_rate_calculator", toolName: "Inventory Turnover Rate Calculator", route: "/tools/free/inventory_turnover_rate_calculator", accessTier: "FREE" },
  { slug: "inventory_turnover_risk_analyzer", toolKey: "inventory_turnover_risk_analyzer", toolName: "Inventory Turnover Risk Analyzer", route: "/tools/free/inventory_turnover_risk_analyzer", accessTier: "FREE" },
  { slug: "irr_calculator", toolKey: "irr_calculator", toolName: "Irr Calculator", route: "/tools/free/irr_calculator", accessTier: "FREE" },
  { slug: "irrigation_cost_check_analyzer", toolKey: "irrigation_cost_check_analyzer", toolName: "Irrigation Cost Check Analyzer", route: "/tools/free/irrigation_cost_check_analyzer", accessTier: "FREE" },
  { slug: "joint_compound_calculator", toolKey: "joint_compound_calculator", toolName: "Joint Compound Calculator", route: "/tools/free/joint_compound_calculator", accessTier: "FREE" },
  { slug: "joint_torque_calculator", toolKey: "joint_torque_calculator", toolName: "Joint Torque Calculator", route: "/tools/free/joint_torque_calculator", accessTier: "FREE" },
  { slug: "kalman_filter_prediction_calculator", toolKey: "kalman_filter_prediction_calculator", toolName: "Kalman Filter Prediction Calculator", route: "/tools/free/kalman_filter_prediction_calculator", accessTier: "FREE" },
  { slug: "landfill_area_calculator", toolKey: "landfill_area_calculator", toolName: "Landfill Area Calculator", route: "/tools/free/landfill_area_calculator", accessTier: "FREE" },
  { slug: "laser_processing_energy_density_calculator", toolKey: "laser_processing_energy_density_calculator", toolName: "Laser Processing Energy Density Calculator", route: "/tools/free/laser_processing_energy_density_calculator", accessTier: "FREE" },
  { slug: "learning_curve_calculator", toolKey: "learning_curve_calculator", toolName: "Learning Curve Calculator", route: "/tools/free/learning_curve_calculator", accessTier: "FREE" },
  { slug: "lens_power_calculator", toolKey: "lens_power_calculator", toolName: "Lens Power Calculator", route: "/tools/free/lens_power_calculator", accessTier: "FREE" },
  { slug: "levelized_cost_of_energy_calculator", toolKey: "levelized_cost_of_energy_calculator", toolName: "Levelized Cost Of Energy Calculator", route: "/tools/free/levelized_cost_of_energy_calculator", accessTier: "FREE" },
  { slug: "lever_rule_calculator", toolKey: "lever_rule_calculator", toolName: "Lever Rule Calculator", route: "/tools/free/lever_rule_calculator", accessTier: "FREE" },
  { slug: "line_balancing_calculator", toolKey: "line_balancing_calculator", toolName: "Line Balancing Calculator", route: "/tools/free/line_balancing_calculator", accessTier: "FREE" },
  { slug: "linoleum_length_calculator", toolKey: "linoleum_length_calculator", toolName: "Linoleum Length Calculator", route: "/tools/free/linoleum_length_calculator", accessTier: "FREE" },
  { slug: "lintel_beam_bending_stress_calculator", toolKey: "lintel_beam_bending_stress_calculator", toolName: "Lintel Beam Bending Stress Calculator", route: "/tools/free/lintel_beam_bending_stress_calculator", accessTier: "FREE" },
  { slug: "load_factor_calculator", toolKey: "load_factor_calculator", toolName: "Load Factor Calculator", route: "/tools/free/load_factor_calculator", accessTier: "FREE" },
  { slug: "loom_production_calculator", toolKey: "loom_production_calculator", toolName: "Loom Production Calculator", route: "/tools/free/loom_production_calculator", accessTier: "FREE" },
  { slug: "lvl_beam_capacity_calculator", toolKey: "lvl_beam_capacity_calculator", toolName: "Lvl Beam Capacity Calculator", route: "/tools/free/lvl_beam_capacity_calculator", accessTier: "FREE" },
  { slug: "machine_depreciation_calculator", toolKey: "machine_depreciation_calculator", toolName: "Machine Depreciation Calculator", route: "/tools/free/machine_depreciation_calculator", accessTier: "FREE" },
  { slug: "magnetic_field_wire_calculator", toolKey: "magnetic_field_wire_calculator", toolName: "Magnetic Field Wire Calculator", route: "/tools/free/magnetic_field_wire_calculator", accessTier: "FREE" },
  { slug: "marketing_roi_calculator", toolKey: "marketing_roi_calculator", toolName: "Marketing Roi Calculator", route: "/tools/free/marketing_roi_calculator", accessTier: "FREE" },
  { slug: "maximum_drawdown_calculator", toolKey: "maximum_drawdown_calculator", toolName: "Maximum Drawdown Calculator", route: "/tools/free/maximum_drawdown_calculator", accessTier: "FREE" },
  { slug: "maximum_torsional_shear_stress_circular_calculator", toolKey: "maximum_torsional_shear_stress_circular_calculator", toolName: "Maximum Torsional Shear Stress Circular Calculator", route: "/tools/free/maximum_torsional_shear_stress_circular_calculator", accessTier: "FREE" },
  { slug: "metacentric_height_calculator", toolKey: "metacentric_height_calculator", toolName: "Metacentric Height Calculator", route: "/tools/free/metacentric_height_calculator", accessTier: "FREE" },
  { slug: "minimum_belt_tension_slack_side_calculator", toolKey: "minimum_belt_tension_slack_side_calculator", toolName: "Minimum Belt Tension Slack Side Calculator", route: "/tools/free/minimum_belt_tension_slack_side_calculator", accessTier: "FREE" },
  { slug: "minimum_sample_size_calculator", toolKey: "minimum_sample_size_calculator", toolName: "Minimum Sample Size Calculator", route: "/tools/free/minimum_sample_size_calculator", accessTier: "FREE" },
  { slug: "minimum_weld_throat_thickness_calculator", toolKey: "minimum_weld_throat_thickness_calculator", toolName: "Minimum Weld Throat Thickness Calculator", route: "/tools/free/minimum_weld_throat_thickness_calculator", accessTier: "FREE" },
  { slug: "mohrs_circle_principal_stress_calculator", toolKey: "mohrs_circle_principal_stress_calculator", toolName: "Mohrs Circle Principal Stress Calculator", route: "/tools/free/mohrs_circle_principal_stress_calculator", accessTier: "FREE" },
  { slug: "mooring_line_load_calculator", toolKey: "mooring_line_load_calculator", toolName: "Mooring Line Load Calculator", route: "/tools/free/mooring_line_load_calculator", accessTier: "FREE" },
  { slug: "motor_efficiency_calculator", toolKey: "motor_efficiency_calculator", toolName: "Motor Efficiency Calculator", route: "/tools/free/motor_efficiency_calculator", accessTier: "FREE" },
  { slug: "mud_annular_velocity_calculator", toolKey: "mud_annular_velocity_calculator", toolName: "Mud Annular Velocity Calculator", route: "/tools/free/mud_annular_velocity_calculator", accessTier: "FREE" },
  { slug: "net_positive_suction_head_available_calculator", toolKey: "net_positive_suction_head_available_calculator", toolName: "Net Positive Suction Head Available Calculator", route: "/tools/free/net_positive_suction_head_available_calculator", accessTier: "FREE" },
  { slug: "noise_propagation_calculator", toolKey: "noise_propagation_calculator", toolName: "Noise Propagation Calculator", route: "/tools/free/noise_propagation_calculator", accessTier: "FREE" },
  { slug: "normal_stress_force_area_calculator", toolKey: "normal_stress_force_area_calculator", toolName: "Normal Stress Force Area Calculator", route: "/tools/free/normal_stress_force_area_calculator", accessTier: "FREE" },
  { slug: "npv_calculator", toolKey: "npv_calculator", toolName: "Npv Calculator", route: "/tools/free/npv_calculator", accessTier: "FREE" },
  { slug: "office_supplies_cost_analyzer", toolKey: "office_supplies_cost_analyzer", toolName: "Office Supplies Cost Analyzer", route: "/tools/free/office_supplies_cost_analyzer", accessTier: "FREE" },
  { slug: "operating_margin_calculator", toolKey: "operating_margin_calculator", toolName: "Operating Margin Calculator", route: "/tools/free/operating_margin_calculator", accessTier: "FREE" },
  { slug: "opportunity_cost_calculator", toolKey: "opportunity_cost_calculator", toolName: "Opportunity Cost Calculator", route: "/tools/free/opportunity_cost_calculator", accessTier: "FREE" },
  { slug: "ore_reserve_volume_calculator", toolKey: "ore_reserve_volume_calculator", toolName: "Ore Reserve Volume Calculator", route: "/tools/free/ore_reserve_volume_calculator", accessTier: "FREE" },
  { slug: "oven_capacity_calculator", toolKey: "oven_capacity_calculator", toolName: "Oven Capacity Calculator", route: "/tools/free/oven_capacity_calculator", accessTier: "FREE" },
  { slug: "overall_equipment_effectiveness_calculator", toolKey: "overall_equipment_effectiveness_calculator", toolName: "Overall Equipment Effectiveness Calculator", route: "/tools/free/overall_equipment_effectiveness_calculator", accessTier: "FREE" },
  { slug: "overtime_vs_hiring_breakeven", toolKey: "overtime_vs_hiring_breakeven", toolName: "Overtime vs Hiring Breakeven", route: "/tools/free/overtime_vs_hiring_breakeven", accessTier: "FREE" },
  { slug: "pallet_rack_capacity_optimizer", toolKey: "pallet_rack_capacity_optimizer", toolName: "Pallet Rack Capacity Optimizer", route: "/tools/free/pallet_rack_capacity_optimizer", accessTier: "FREE" },
  { slug: "pasteurization_time_calculator", toolKey: "pasteurization_time_calculator", toolName: "Pasteurization Time Calculator", route: "/tools/free/pasteurization_time_calculator", accessTier: "FREE" },
  { slug: "paving_stone_calculator", toolKey: "paving_stone_calculator", toolName: "Paving Stone Calculator", route: "/tools/free/paving_stone_calculator", accessTier: "FREE" },
  { slug: "payment_processor_fee_calculator", toolKey: "payment_processor_fee_calculator", toolName: "Payment Processor Fee Calculator", route: "/tools/free/payment_processor_fee_calculator", accessTier: "FREE" },
  { slug: "payment_terms_optimizer", toolKey: "payment_terms_optimizer", toolName: "Payment Terms Optimizer", route: "/tools/free/payment_terms_optimizer", accessTier: "FREE" },
  { slug: "pb_ratio_calculator", toolKey: "pb_ratio_calculator", toolName: "Pb Ratio Calculator", route: "/tools/free/pb_ratio_calculator", accessTier: "FREE" },
  { slug: "pe_ratio_calculator", toolKey: "pe_ratio_calculator", toolName: "Pe Ratio Calculator", route: "/tools/free/pe_ratio_calculator", accessTier: "FREE" },
  { slug: "pid_controller_ziegler_calculator", toolKey: "pid_controller_ziegler_calculator", toolName: "Pid Controller Ziegler Calculator", route: "/tools/free/pid_controller_ziegler_calculator", accessTier: "FREE" },
  { slug: "pile_bearing_capacity_calculator", toolKey: "pile_bearing_capacity_calculator", toolName: "Pile Bearing Capacity Calculator", route: "/tools/free/pile_bearing_capacity_calculator", accessTier: "FREE" },
  { slug: "plaster_weight_calculator", toolKey: "plaster_weight_calculator", toolName: "Plaster Weight Calculator", route: "/tools/free/plaster_weight_calculator", accessTier: "FREE" },
  { slug: "plastic_cooling_time_calculator", toolKey: "plastic_cooling_time_calculator", toolName: "Plastic Cooling Time Calculator", route: "/tools/free/plastic_cooling_time_calculator", accessTier: "FREE" },
  { slug: "plastic_drying_time_calculator", toolKey: "plastic_drying_time_calculator", toolName: "Plastic Drying Time Calculator", route: "/tools/free/plastic_drying_time_calculator", accessTier: "FREE" },
  { slug: "porosity_calculator", toolKey: "porosity_calculator", toolName: "Porosity Calculator", route: "/tools/free/porosity_calculator", accessTier: "FREE" },
  { slug: "portfolio_optimization_calculator", toolKey: "portfolio_optimization_calculator", toolName: "Portfolio Optimization Calculator", route: "/tools/free/portfolio_optimization_calculator", accessTier: "FREE" },
  { slug: "profitability_index_calculator", toolKey: "profitability_index_calculator", toolName: "Profitability Index Calculator", route: "/tools/free/profitability_index_calculator", accessTier: "FREE" },
  { slug: "propagation_constant_calculator", toolKey: "propagation_constant_calculator", toolName: "Propagation Constant Calculator", route: "/tools/free/propagation_constant_calculator", accessTier: "FREE" },
  { slug: "ps_ratio_calculator", toolKey: "ps_ratio_calculator", toolName: "Ps Ratio Calculator", route: "/tools/free/ps_ratio_calculator", accessTier: "FREE" },
  { slug: "pump_power_calculator", toolKey: "pump_power_calculator", toolName: "Pump Power Calculator", route: "/tools/free/pump_power_calculator", accessTier: "FREE" },
  { slug: "quality_factor_calculator", toolKey: "quality_factor_calculator", toolName: "Quality Factor Calculator", route: "/tools/free/quality_factor_calculator", accessTier: "FREE" },
  { slug: "rainwater_harvest_calculator", toolKey: "rainwater_harvest_calculator", toolName: "Rainwater Harvest Calculator", route: "/tools/free/rainwater_harvest_calculator", accessTier: "FREE" },
  { slug: "rc_time_constant_calculator", toolKey: "rc_time_constant_calculator", toolName: "Rc Time Constant Calculator", route: "/tools/free/rc_time_constant_calculator", accessTier: "FREE" },
  { slug: "real_return_calculator", toolKey: "real_return_calculator", toolName: "Real Return Calculator", route: "/tools/free/real_return_calculator", accessTier: "FREE" },
  { slug: "recipe_cost_check", toolKey: "recipe_cost_check", toolName: "Recipe Cost Check", route: "/tools/free/recipe_cost_check", accessTier: "FREE" },
  { slug: "rectangular_section_moment_of_inertia_calculator", toolKey: "rectangular_section_moment_of_inertia_calculator", toolName: "Rectangular Section Moment Of Inertia Calculator", route: "/tools/free/rectangular_section_moment_of_inertia_calculator", accessTier: "FREE" },
  { slug: "recycling_rate_calculator", toolKey: "recycling_rate_calculator", toolName: "Recycling Rate Calculator", route: "/tools/free/recycling_rate_calculator", accessTier: "FREE" },
  { slug: "rent_to_value_ratio_calculator", toolKey: "rent_to_value_ratio_calculator", toolName: "Rent To Value Ratio Calculator", route: "/tools/free/rent_to_value_ratio_calculator", accessTier: "FREE" },
  { slug: "rent_vs_buy_calculator", toolKey: "rent_vs_buy_calculator", toolName: "Rent Vs Buy Calculator", route: "/tools/free/rent_vs_buy_calculator", accessTier: "FREE" },
  { slug: "rental_property_cash_flow_calculator", toolKey: "rental_property_cash_flow_calculator", toolName: "Rental Property Cash Flow Calculator", route: "/tools/free/rental_property_cash_flow_calculator", accessTier: "FREE" },
  { slug: "reorder_point_calculator", toolKey: "reorder_point_calculator", toolName: "Reorder Point Calculator", route: "/tools/free/reorder_point_calculator", accessTier: "FREE" },
  { slug: "restaurant_menu_margin_leak_analysis", toolKey: "restaurant_menu_margin_leak_analysis", toolName: "Restaurant Menu Margin Leak Analysis", route: "/tools/free/restaurant_menu_margin_leak_analysis", accessTier: "FREE" },
  { slug: "ridge_beam_calculator", toolKey: "ridge_beam_calculator", toolName: "Ridge Beam Calculator", route: "/tools/free/ridge_beam_calculator", accessTier: "FREE" },
  { slug: "rlc_resonant_frequency_calculator", toolKey: "rlc_resonant_frequency_calculator", toolName: "Rlc Resonant Frequency Calculator", route: "/tools/free/rlc_resonant_frequency_calculator", accessTier: "FREE" },
  { slug: "roi_calculator", toolKey: "roi_calculator", toolName: "Roi Calculator", route: "/tools/free/roi_calculator", accessTier: "FREE" },
  { slug: "roic_calculator", toolKey: "roic_calculator", toolName: "Roic Calculator", route: "/tools/free/roic_calculator", accessTier: "FREE" },
  { slug: "rsu_calculator", toolKey: "rsu_calculator", toolName: "Rsu Calculator", route: "/tools/free/rsu_calculator", accessTier: "FREE" },
  { slug: "runway_length_calculator", toolKey: "runway_length_calculator", toolName: "Runway Length Calculator", route: "/tools/free/runway_length_calculator", accessTier: "FREE" },
  { slug: "saas_shelfware_analysis", toolKey: "saas_shelfware_analysis", toolName: "SaaS Shelfware Analysis", route: "/tools/free/saas_shelfware_analysis", accessTier: "FREE" },
  { slug: "safe_agreement_calculator", toolKey: "safe_agreement_calculator", toolName: "Safe Agreement Calculator", route: "/tools/free/safe_agreement_calculator", accessTier: "FREE" },
  { slug: "sampling_weight_calculator", toolKey: "sampling_weight_calculator", toolName: "Sampling Weight Calculator", route: "/tools/free/sampling_weight_calculator", accessTier: "FREE" },
  { slug: "scrap_rate_optimization_calculator", toolKey: "scrap_rate_optimization_calculator", toolName: "Scrap Rate Optimization Calculator", route: "/tools/free/scrap_rate_optimization_calculator", accessTier: "FREE" },
  { slug: "seed_rate_and_cost_analysis", toolKey: "seed_rate_and_cost_analysis", toolName: "Seed Rate and Cost Analysis", route: "/tools/free/seed_rate_and_cost_analysis", accessTier: "FREE" },
  { slug: "seed_rate_calculator", toolKey: "seed_rate_calculator", toolName: "Seed Rate Calculator", route: "/tools/free/seed_rate_calculator", accessTier: "FREE" },
  { slug: "sewing_cycle_time_calculator", toolKey: "sewing_cycle_time_calculator", toolName: "Sewing Cycle Time Calculator", route: "/tools/free/sewing_cycle_time_calculator", accessTier: "FREE" },
  { slug: "sewing_line_balancing_calculator", toolKey: "sewing_line_balancing_calculator", toolName: "Sewing Line Balancing Calculator", route: "/tools/free/sewing_line_balancing_calculator", accessTier: "FREE" },
  { slug: "sharpe_ratio_calculator", toolKey: "sharpe_ratio_calculator", toolName: "Sharpe Ratio Calculator", route: "/tools/free/sharpe_ratio_calculator", accessTier: "FREE" },
  { slug: "shear_force_diagram_calculator", toolKey: "shear_force_diagram_calculator", toolName: "Shear Force Diagram Calculator", route: "/tools/free/shear_force_diagram_calculator", accessTier: "FREE" },
  { slug: "ship_draft_calculator", toolKey: "ship_draft_calculator", toolName: "Ship Draft Calculator", route: "/tools/free/ship_draft_calculator", accessTier: "FREE" },
  { slug: "shipping_cost_calculator", toolKey: "shipping_cost_calculator", toolName: "Shipping Cost Calculator", route: "/tools/free/shipping_cost_calculator", accessTier: "FREE" },
  { slug: "siding_panel_calculator", toolKey: "siding_panel_calculator", toolName: "Siding Panel Calculator", route: "/tools/free/siding_panel_calculator", accessTier: "FREE" },
  { slug: "signal_to_noise_ratio_calculator", toolKey: "signal_to_noise_ratio_calculator", toolName: "Signal To Noise Ratio Calculator", route: "/tools/free/signal_to_noise_ratio_calculator", accessTier: "FREE" },
  { slug: "silage_weight_calculator", toolKey: "silage_weight_calculator", toolName: "Silage Weight Calculator", route: "/tools/free/silage_weight_calculator", accessTier: "FREE" },
  { slug: "simple_interest_calculator", toolKey: "simple_interest_calculator", toolName: "Simple Interest Calculator", route: "/tools/free/simple_interest_calculator", accessTier: "FREE" },
  { slug: "simply_supported_beam_deflection_calculator", toolKey: "simply_supported_beam_deflection_calculator", toolName: "Simply Supported Beam Deflection Calculator", route: "/tools/free/simply_supported_beam_deflection_calculator", accessTier: "FREE" },
  { slug: "slope_stability_factor_calculator", toolKey: "slope_stability_factor_calculator", toolName: "Slope Stability Factor Calculator", route: "/tools/free/slope_stability_factor_calculator", accessTier: "FREE" },
  { slug: "smed_setup_time_calculator", toolKey: "smed_setup_time_calculator", toolName: "Smed Setup Time Calculator", route: "/tools/free/smed_setup_time_calculator", accessTier: "FREE" },
  { slug: "soffit_area_calculator", toolKey: "soffit_area_calculator", toolName: "Soffit Area Calculator", route: "/tools/free/soffit_area_calculator", accessTier: "FREE" },
  { slug: "soil_bearing_capacity_calculator", toolKey: "soil_bearing_capacity_calculator", toolName: "Soil Bearing Capacity Calculator", route: "/tools/free/soil_bearing_capacity_calculator", accessTier: "FREE" },
  { slug: "sortino_ratio_calculator", toolKey: "sortino_ratio_calculator", toolName: "Sortino Ratio Calculator", route: "/tools/free/sortino_ratio_calculator", accessTier: "FREE" },
  { slug: "spray_paint_calculator", toolKey: "spray_paint_calculator", toolName: "Spray Paint Calculator", route: "/tools/free/spray_paint_calculator", accessTier: "FREE" },
  { slug: "spring_force_hookes_law_calculator", toolKey: "spring_force_hookes_law_calculator", toolName: "Spring Force Hookes Law Calculator", route: "/tools/free/spring_force_hookes_law_calculator", accessTier: "FREE" },
  { slug: "sprinkler_flow_rate_calculator", toolKey: "sprinkler_flow_rate_calculator", toolName: "Sprinkler Flow Rate Calculator", route: "/tools/free/sprinkler_flow_rate_calculator", accessTier: "FREE" },
  { slug: "sqnr_calculator", toolKey: "sqnr_calculator", toolName: "Sqnr Calculator", route: "/tools/free/sqnr_calculator", accessTier: "FREE" },
  { slug: "standard_deviation_variance_calculator", toolKey: "standard_deviation_variance_calculator", toolName: "Standard Deviation Variance Calculator", route: "/tools/free/standard_deviation_variance_calculator", accessTier: "FREE" },
  { slug: "standard_time_calculator", toolKey: "standard_time_calculator", toolName: "Standard Time Calculator", route: "/tools/free/standard_time_calculator", accessTier: "FREE" },
  { slug: "startup_valuation_calculator", toolKey: "startup_valuation_calculator", toolName: "Startup Valuation Calculator", route: "/tools/free/startup_valuation_calculator", accessTier: "FREE" },
  { slug: "steel_beam_maximum_bending_stress_calculator", toolKey: "steel_beam_maximum_bending_stress_calculator", toolName: "Steel Beam Maximum Bending Stress Calculator", route: "/tools/free/steel_beam_maximum_bending_stress_calculator", accessTier: "FREE" },
  { slug: "stock_return_calculator", toolKey: "stock_return_calculator", toolName: "Stock Return Calculator", route: "/tools/free/stock_return_calculator", accessTier: "FREE" },
  { slug: "supply_chain_disruption_risk_analysis", toolKey: "supply_chain_disruption_risk_analysis", toolName: "Supply Chain Disruption Risk Analysis", route: "/tools/free/supply_chain_disruption_risk_analysis", accessTier: "FREE" },
  { slug: "surface_roughness_calculator", toolKey: "surface_roughness_calculator", toolName: "Surface Roughness Calculator", route: "/tools/free/surface_roughness_calculator", accessTier: "FREE" },
  { slug: "taguchi_quality_loss_analysis", toolKey: "taguchi_quality_loss_analysis", toolName: "Taguchi Quality Loss Analysis", route: "/tools/free/taguchi_quality_loss_analysis", accessTier: "FREE" },
  { slug: "tariff_extra_duty_calculator", toolKey: "tariff_extra_duty_calculator", toolName: "Tariff Extra Duty Calculator", route: "/tools/free/tariff_extra_duty_calculator", accessTier: "FREE" },
  { slug: "textile_waste_risk_analyzer", toolKey: "textile_waste_risk_analyzer", toolName: "Textile Waste Risk Analyzer", route: "/tools/free/textile_waste_risk_analyzer", accessTier: "FREE" },
  { slug: "thermal_conductivity_converter", toolKey: "thermal_conductivity_converter", toolName: "Thermal Conductivity Converter", route: "/tools/free/thermal_conductivity_converter", accessTier: "FREE" },
  { slug: "thin_walled_pressure_vessel_hoop_stress_calculator", toolKey: "thin_walled_pressure_vessel_hoop_stress_calculator", toolName: "Thin Walled Pressure Vessel Hoop Stress Calculator", route: "/tools/free/thin_walled_pressure_vessel_hoop_stress_calculator", accessTier: "FREE" },
  { slug: "tile_waste_calculator", toolKey: "tile_waste_calculator", toolName: "Tile Waste Calculator", route: "/tools/free/tile_waste_calculator", accessTier: "FREE" },
  { slug: "timber_beam_shear_calculator", toolKey: "timber_beam_shear_calculator", toolName: "Timber Beam Shear Calculator", route: "/tools/free/timber_beam_shear_calculator", accessTier: "FREE" },
  { slug: "torque_converter", toolKey: "torque_converter", toolName: "Torque Converter", route: "/tools/free/torque_converter", accessTier: "FREE" },
  { slug: "torsion_spring_calculator", toolKey: "torsion_spring_calculator", toolName: "Torsion Spring Calculator", route: "/tools/free/torsion_spring_calculator", accessTier: "FREE" },
  { slug: "total_employee_cost_analyzer", toolKey: "total_employee_cost_analyzer", toolName: "Total Employee Cost Analyzer", route: "/tools/free/total_employee_cost_analyzer", accessTier: "FREE" },
  { slug: "traffic_signal_delay_calculator", toolKey: "traffic_signal_delay_calculator", toolName: "Traffic Signal Delay Calculator", route: "/tools/free/traffic_signal_delay_calculator", accessTier: "FREE" },
  { slug: "transfer_pricing_optimizer", toolKey: "transfer_pricing_optimizer", toolName: "Transfer Pricing Optimizer", route: "/tools/free/transfer_pricing_optimizer", accessTier: "FREE" },
  { slug: "treynor_ratio_calculator", toolKey: "treynor_ratio_calculator", toolName: "Treynor Ratio Calculator", route: "/tools/free/treynor_ratio_calculator", accessTier: "FREE" },
  { slug: "usd_loan_cost_calculator", toolKey: "usd_loan_cost_calculator", toolName: "Usd Loan Cost Calculator", route: "/tools/free/usd_loan_cost_calculator", accessTier: "FREE" },
  { slug: "vacuum_pump_time_calculator", toolKey: "vacuum_pump_time_calculator", toolName: "Vacuum Pump Time Calculator", route: "/tools/free/vacuum_pump_time_calculator", accessTier: "FREE" },
  { slug: "vehicle_top_speed_calculator", toolKey: "vehicle_top_speed_calculator", toolName: "Vehicle Top Speed Calculator", route: "/tools/free/vehicle_top_speed_calculator", accessTier: "FREE" },
  { slug: "viscous_pump_power_calculator", toolKey: "viscous_pump_power_calculator", toolName: "Viscous Pump Power Calculator", route: "/tools/free/viscous_pump_power_calculator", accessTier: "FREE" },
  { slug: "volumetric_weight_calculator", toolKey: "volumetric_weight_calculator", toolName: "Volumetric Weight Calculator", route: "/tools/free/volumetric_weight_calculator", accessTier: "FREE" },
  { slug: "von_mises_stress_calculator", toolKey: "von_mises_stress_calculator", toolName: "Von Mises Stress Calculator", route: "/tools/free/von_mises_stress_calculator", accessTier: "FREE" },
  { slug: "vswr_calculator", toolKey: "vswr_calculator", toolName: "Vswr Calculator", route: "/tools/free/vswr_calculator", accessTier: "FREE" },
  { slug: "wacc_calculator", toolKey: "wacc_calculator", toolName: "Wacc Calculator", route: "/tools/free/wacc_calculator", accessTier: "FREE" },
  { slug: "wallpaper_roll_calculator", toolKey: "wallpaper_roll_calculator", toolName: "Wallpaper Roll Calculator", route: "/tools/free/wallpaper_roll_calculator", accessTier: "FREE" },
  { slug: "warehouse_capacity_calculator", toolKey: "warehouse_capacity_calculator", toolName: "Warehouse Capacity Calculator", route: "/tools/free/warehouse_capacity_calculator", accessTier: "FREE" },
  { slug: "water_footprint_calculator", toolKey: "water_footprint_calculator", toolName: "Water Footprint Calculator", route: "/tools/free/water_footprint_calculator", accessTier: "FREE" },
  { slug: "water_usage_optimization_analyzer", toolKey: "water_usage_optimization_analyzer", toolName: "Water Usage Optimization Analyzer", route: "/tools/free/water_usage_optimization_analyzer", accessTier: "FREE" },
  { slug: "watershed_runoff_calculator", toolKey: "watershed_runoff_calculator", toolName: "Watershed Runoff Calculator", route: "/tools/free/watershed_runoff_calculator", accessTier: "FREE" },
  { slug: "wavelength_calculator", toolKey: "wavelength_calculator", toolName: "Wavelength Calculator", route: "/tools/free/wavelength_calculator", accessTier: "FREE" },
  { slug: "weld_heat_input_calculator", toolKey: "weld_heat_input_calculator", toolName: "Weld Heat Input Calculator", route: "/tools/free/weld_heat_input_calculator", accessTier: "FREE" },
  { slug: "well_bottom_pressure_calculator", toolKey: "well_bottom_pressure_calculator", toolName: "Well Bottom Pressure Calculator", route: "/tools/free/well_bottom_pressure_calculator", accessTier: "FREE" },
  { slug: "wellbore_pressure_calculator", toolKey: "wellbore_pressure_calculator", toolName: "Wellbore Pressure Calculator", route: "/tools/free/wellbore_pressure_calculator", accessTier: "FREE" },
  { slug: "wind_turbine_power_calculator", toolKey: "wind_turbine_power_calculator", toolName: "Wind Turbine Power Calculator", route: "/tools/free/wind_turbine_power_calculator", accessTier: "FREE" },
  { slug: "wood_siding_calculator", toolKey: "wood_siding_calculator", toolName: "Wood Siding Calculator", route: "/tools/free/wood_siding_calculator", accessTier: "FREE" },
  { slug: "wood_stain_calculator", toolKey: "wood_stain_calculator", toolName: "Wood Stain Calculator", route: "/tools/free/wood_stain_calculator", accessTier: "FREE" },
  { slug: "working_capital_calculator", toolKey: "working_capital_calculator", toolName: "Working Capital Calculator", route: "/tools/free/working_capital_calculator", accessTier: "FREE" },
  { slug: "worm_gear_efficiency_calculator", toolKey: "worm_gear_efficiency_calculator", toolName: "Worm Gear Efficiency Calculator", route: "/tools/free/worm_gear_efficiency_calculator", accessTier: "FREE" },
];

const freeToolSlugs: string[] = FREE_TOOLS.map((t) => t.slug).sort();
const freeToolBySlug = new Map<string, FreeToolManifestEntry>(FREE_TOOLS.map((t) => [t.slug, t]));

export function listFreeToolSlugs(): string[] {
  return [...freeToolSlugs];
}

export function listFreeToolManifestEntries(): FreeToolManifestEntry[] {
  return FREE_TOOLS.map((t) => ({ ...t }));
}

export function getFreeToolManifestEntry(slug: string): FreeToolManifestEntry | undefined {
  return freeToolBySlug.get(slug);
}

export function getFreeToolSitemapItems(): { slug: string; route: string; toolName: string }[] {
  return FREE_TOOLS.map((t) => ({ slug: t.slug, route: t.route, toolName: t.toolName }));
}
