/**
 * Roadmap free batch production vs oracle comparison.
 * GENERATED by scripts/generate-roadmap-free-batch-governance.mjs — do not edit manually.
 */

import type { FreeTrafficInputValues } from "@/lib/tools/free-traffic-calculators";
import {
  ROADMAP_FREE_BATCH_ORACLE_SLUGS,
  calculateRoadmapFreeBatchOracle,
  extractRoadmapFreeBatchRecommendedPrice,
  getRoadmapFreeBatchParseKind,
  isRoadmapFreeBatchOracleSlug,
  type RoadmapFreeBatchOracleSlug,
} from "@/lib/formula-governance/oracle/roadmap-free-batch-oracles";
import { getRoadmapFreeBatchProductionFormulaLocator } from "@/lib/formula-governance/oracle/roadmap-free-batch-production-locators";
import { hasOracleForTool } from "@/lib/formula-governance/oracle/registry";
import type {
  FieldComparisonDiff,
  OracleComparisonAuditSummary,
  OracleComparisonResult,
  OracleComparisonStatus,
} from "@/lib/formula-governance/oracle/compare-production-oracle";
import { compareNumericFields } from "@/lib/formula-governance/oracle/compare-production-oracle";

const NUMERIC_TOLERANCE = 0.05;
const CURRENCY_TOLERANCE = 0.02;
const PERCENT_TOLERANCE = 0.05;
const INTEGER_TOLERANCE = 0.5;

function toleranceForParseKind(parseKind: ReturnType<typeof getRoadmapFreeBatchParseKind>): number {
  if (parseKind === "currency") return CURRENCY_TOLERANCE;
  if (parseKind === "percent") return PERCENT_TOLERANCE;
  if (parseKind === "integer") return INTEGER_TOLERANCE;
  return NUMERIC_TOLERANCE;
}

export { ROADMAP_FREE_BATCH_ORACLE_SLUGS };

export type RoadmapFreeBatchComparisonScenario = {
  readonly id: string;
  readonly kind: "normal" | "edge" | "absurd";
  readonly values: FreeTrafficInputValues;
  readonly expectPass?: boolean;
};

export function isRoadmapFreeBatchComparisonSlug(slug: string): slug is RoadmapFreeBatchOracleSlug {
  return isRoadmapFreeBatchOracleSlug(slug);
}

const NON_DETERMINISTIC_SLUGS = new Set<RoadmapFreeBatchOracleSlug>([
  "rastgele-sayi-ureteci",
]);

const SCENARIOS_BY_SLUG: Readonly<Record<RoadmapFreeBatchOracleSlug, readonly RoadmapFreeBatchComparisonScenario[]>> = {
  "abonelik-yazilim-cloud-yillik-maliyet-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"monthlyFee":0.01,"months":12} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"monthlyFee":-1,"months":12}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"monthlyFee":0.01,"months":12} },
    { id: "rogue-key", kind: "absurd", values: { ...{"monthlyFee":0.01,"months":12}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"monthlyFee":0.01,"months":12} },
  ],
  "agirlikli-ortalama-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"value1":0.01,"weight1":1,"value2":0.01,"weight2":1,"value3":0.01,"weight3":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"value1":-1,"weight1":1,"value2":0.01,"weight2":1,"value3":0.01,"weight3":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"value1":0.01,"weight1":1,"value2":0.01,"weight2":1,"value3":0.01,"weight3":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"value1":0.01,"weight1":1,"value2":0.01,"weight2":1,"value3":0.01,"weight3":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"value1":0.01,"weight1":1,"value2":0.01,"weight2":1,"value3":0.01,"weight3":1} },
  ],
  "akaryakit-fiyati-ile-yol-butcesi": [
    { id: "golden-valid", kind: "normal", values: {"distanceKm":0.01,"costPerKm":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"distanceKm":-1,"costPerKm":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"distanceKm":0.01,"costPerKm":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"distanceKm":0.01,"costPerKm":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"distanceKm":0.01,"costPerKm":0.01} },
  ],
  "aku-kapasitesi-calisma-suresi-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"batteryAh":0.01,"loadAmps":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"batteryAh":-1,"loadAmps":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"batteryAh":0.01,"loadAmps":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"batteryAh":0.01,"loadAmps":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"batteryAh":0.01,"loadAmps":0.01} },
  ],
  "alti-sigma-dpmo-sigma-seviyesi-cevirici": [
    { id: "golden-valid", kind: "normal", values: {"dpmo":0.01,"million":1000000} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"dpmo":-1,"million":1000000}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"dpmo":0.01,"million":1000000} },
    { id: "rogue-key", kind: "absurd", values: { ...{"dpmo":0.01,"million":1000000}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"dpmo":0.01,"million":1000000} },
  ],
  "amper-kilowatt-kw-cevirici": [
    { id: "golden-valid", kind: "normal", values: {"amps":0.01,"volts":0.01,"powerFactor":0.9} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"amps":-1,"volts":0.01,"powerFactor":0.9}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"amps":0.01,"volts":0.01,"powerFactor":0.9} },
    { id: "rogue-key", kind: "absurd", values: { ...{"amps":0.01,"volts":0.01,"powerFactor":0.9}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"amps":0.01,"volts":0.01,"powerFactor":0.9} },
  ],
  "arac-amortisman-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"vehicleCost":0.01,"salvageValue":0.01,"usefulLifeYears":5} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"vehicleCost":-1,"salvageValue":0.01,"usefulLifeYears":5}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"vehicleCost":0.01,"salvageValue":0.01,"usefulLifeYears":5} },
    { id: "rogue-key", kind: "absurd", values: { ...{"vehicleCost":0.01,"salvageValue":0.01,"usefulLifeYears":5}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"vehicleCost":0.01,"salvageValue":0.01,"usefulLifeYears":5} },
  ],
  "arac-bakim-periyodu-takip-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"remainingKm":0.01,"dailyKm":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"remainingKm":-1,"dailyKm":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"remainingKm":0.01,"dailyKm":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"remainingKm":0.01,"dailyKm":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"remainingKm":0.01,"dailyKm":0.01} },
  ],
  "arac-kira-satin-alma-karsilastirma": [
    { id: "golden-valid", kind: "normal", values: {"purchaseCost":0.01,"leaseCost":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"purchaseCost":-1,"leaseCost":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"purchaseCost":0.01,"leaseCost":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"purchaseCost":0.01,"leaseCost":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"purchaseCost":0.01,"leaseCost":0.01} },
  ],
  "asma-tavan-malzeme-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"ceilingAreaM2":0.01,"materialPerM2":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"ceilingAreaM2":-1,"materialPerM2":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"ceilingAreaM2":0.01,"materialPerM2":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"ceilingAreaM2":0.01,"materialPerM2":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"ceilingAreaM2":0.01,"materialPerM2":0.01} },
  ],
  "aydinlatma-armatur-sayisi-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"totalLumensNeeded":0.01,"lumensPerFixture":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"totalLumensNeeded":-1,"lumensPerFixture":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"totalLumensNeeded":0.01,"lumensPerFixture":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"totalLumensNeeded":0.01,"lumensPerFixture":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"totalLumensNeeded":0.01,"lumensPerFixture":0.01} },
  ],
  "baca-havalandirma-kanali-cap-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"airflowM3h":0.01,"velocityMps":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"airflowM3h":-1,"velocityMps":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"airflowM3h":0.01,"velocityMps":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"airflowM3h":0.01,"velocityMps":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"airflowM3h":0.01,"velocityMps":0.01} },
  ],
  "bar-psi-pascal-cevirici": [
    { id: "golden-valid", kind: "normal", values: {"value":0,"fromUnit":"pa"} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"value":-1,"fromUnit":"pa"}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"value":0,"fromUnit":"pa"} },
    { id: "rogue-key", kind: "absurd", values: { ...{"value":0,"fromUnit":"pa"}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"value":0,"fromUnit":"pa"} },
  ],
  "basincli-kap-cidar-kalinligi-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"designPressureBar":0.01,"allowableStressBar":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"designPressureBar":-1,"allowableStressBar":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"designPressureBar":0.01,"allowableStressBar":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"designPressureBar":0.01,"allowableStressBar":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"designPressureBar":0.01,"allowableStressBar":0.01} },
  ],
  "beygir-gucu-kilowatt-cevirici": [
    { id: "golden-valid", kind: "normal", values: {"value":0,"fromUnit":"w"} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"value":-1,"fromUnit":"w"}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"value":0,"fromUnit":"w"} },
    { id: "rogue-key", kind: "absurd", values: { ...{"value":0,"fromUnit":"w"}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"value":0,"fromUnit":"w"} },
  ],
  "boru-agirlik-hesaplama-celik-paslanmaz": [
    { id: "golden-valid", kind: "normal", values: {"length":0.01,"kgPerMeter":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"length":-1,"kgPerMeter":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"length":0.01,"kgPerMeter":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"length":0.01,"kgPerMeter":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"length":0.01,"kgPerMeter":0.01} },
  ],
  "boru-capi-akis-hizi-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"flowLpm":0.01,"velocityMps":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"flowLpm":-1,"velocityMps":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"flowLpm":0.01,"velocityMps":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"flowLpm":0.01,"velocityMps":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"flowLpm":0.01,"velocityMps":0.01} },
  ],
  "boya-kaplama-sarfiyati-m-basina-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"areaM2":0.01,"coveragePerLiter":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"areaM2":-1,"coveragePerLiter":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"areaM2":0.01,"coveragePerLiter":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"areaM2":0.01,"coveragePerLiter":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"areaM2":0.01,"coveragePerLiter":0.01} },
  ],
  "bulonlu-baglanti-kesme-ezilme-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"boltCount":0.01,"shearCapacityKn":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"boltCount":-1,"shearCapacityKn":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"boltCount":0.01,"shearCapacityKn":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"boltCount":0.01,"shearCapacityKn":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"boltCount":0.01,"shearCapacityKn":0.01} },
  ],
  "cay-kahve-su-tuketim-maliyeti": [
    { id: "golden-valid", kind: "normal", values: {"unitCost":0.01,"dailyUnits":50} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"unitCost":-1,"dailyUnits":50}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"unitCost":0.01,"dailyUnits":50} },
    { id: "rogue-key", kind: "absurd", values: { ...{"unitCost":0.01,"dailyUnits":50}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"unitCost":0.01,"dailyUnits":50} },
  ],
  "cek-senet-vade-kirma-maliyeti-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"faceValue":0.01,"discountRate":3} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"faceValue":-1,"discountRate":3}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"faceValue":0.01,"discountRate":3} },
    { id: "rogue-key", kind: "absurd", values: { ...{"faceValue":0.01,"discountRate":3}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"faceValue":0.01,"discountRate":3} },
  ],
  "celik-cati-makas-yaklasik-agirligi": [
    { id: "golden-valid", kind: "normal", values: {"span":0.01,"weightPerMeter":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"span":-1,"weightPerMeter":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"span":0.01,"weightPerMeter":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"span":0.01,"weightPerMeter":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"span":0.01,"weightPerMeter":0.01} },
  ],
  "celik-raf-depo-rafi-yuk-kapasitesi": [
    { id: "golden-valid", kind: "normal", values: {"beamCapacityKg":0.01,"shelfCount":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"beamCapacityKg":-1,"shelfCount":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"beamCapacityKg":0.01,"shelfCount":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"beamCapacityKg":0.01,"shelfCount":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"beamCapacityKg":0.01,"shelfCount":0.01} },
  ],
  "cevre-atik-beyani-maliyet-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"wasteTonnes":0.01,"feePerTonne":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"wasteTonnes":-1,"feePerTonne":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"wasteTonnes":0.01,"feePerTonne":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"wasteTonnes":0.01,"feePerTonne":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"wasteTonnes":0.01,"feePerTonne":0.01} },
  ],
  "cit-korkuluk-malzeme-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"length":0.01,"postSpacing":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"length":-1,"postSpacing":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"length":0.01,"postSpacing":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"length":0.01,"postSpacing":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"length":0.01,"postSpacing":0.01} },
  ],
  "civata-on-germe-kuvveti-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"boltDiameterMm":0.01,"preloadKn":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"boltDiameterMm":-1,"preloadKn":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"boltDiameterMm":0.01,"preloadKn":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"boltDiameterMm":0.01,"preloadKn":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"boltDiameterMm":0.01,"preloadKn":0.01} },
  ],
  "civata-sikma-torku-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"clampForce":0.01,"boltDiameterMm":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"clampForce":-1,"boltDiameterMm":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"clampForce":0.01,"boltDiameterMm":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"clampForce":0.01,"boltDiameterMm":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"clampForce":0.01,"boltDiameterMm":0.01} },
  ],
  "cop-atik-konteyner-hacim-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"containerLengthM":0.01,"containerWidthM":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"containerLengthM":-1,"containerWidthM":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"containerLengthM":0.01,"containerWidthM":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"containerLengthM":0.01,"containerWidthM":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"containerLengthM":0.01,"containerWidthM":0.01} },
  ],
  "daire-alani-cevresi-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"radius":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"radius":-1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"radius":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"radius":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"radius":0.01} },
  ],
  "depo-raf-palet-yerlesim-optimizasyonu": [
    { id: "golden-valid", kind: "normal", values: {"palletWidthM":0.01,"palletDepthM":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"palletWidthM":-1,"palletDepthM":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"palletWidthM":0.01,"palletDepthM":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"palletWidthM":0.01,"palletDepthM":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"palletWidthM":0.01,"palletDepthM":0.01} },
  ],
  "disli-modul-cap-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"module":0.01,"teeth":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"module":-1,"teeth":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"module":0.01,"teeth":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"module":0.01,"teeth":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"module":0.01,"teeth":0.01} },
  ],
  "dizel-benzin-maliyet-karsilastirma": [
    { id: "golden-valid", kind: "normal", values: {"dieselCost":0.01,"gasolineCost":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"dieselCost":-1,"gasolineCost":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"dieselCost":0.01,"gasolineCost":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"dieselCost":0.01,"gasolineCost":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"dieselCost":0.01,"gasolineCost":0.01} },
  ],
  "dogalgaz-tuketimi-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"consumptionSm3":0.01,"unitPrice":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"consumptionSm3":-1,"unitPrice":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"consumptionSm3":0.01,"unitPrice":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"consumptionSm3":0.01,"unitPrice":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"consumptionSm3":0.01,"unitPrice":0.01} },
  ],
  "doviz-pozisyonu-kur-farki-riski-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"foreignExposure":0.01,"fxMovePercent":5} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"foreignExposure":-1,"fxMovePercent":5}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"foreignExposure":0.01,"fxMovePercent":5} },
    { id: "rogue-key", kind: "absurd", values: { ...{"foreignExposure":0.01,"fxMovePercent":5}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"foreignExposure":0.01,"fxMovePercent":5} },
  ],
  "duvar-kagidi-seramik-adet-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"wallAreaM2":0.01,"tileAreaM2":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"wallAreaM2":-1,"tileAreaM2":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"wallAreaM2":0.01,"tileAreaM2":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"wallAreaM2":0.01,"tileAreaM2":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"wallAreaM2":0.01,"tileAreaM2":0.01} },
  ],
  "enflasyon-fiyat-eskalasyonu-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"baseAmount":0.01,"inflationPercent":8} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"baseAmount":-1,"inflationPercent":8}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"baseAmount":0.01,"inflationPercent":8} },
    { id: "rogue-key", kind: "absurd", values: { ...{"baseAmount":0.01,"inflationPercent":8}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"baseAmount":0.01,"inflationPercent":8} },
  ],
  "enjeksiyon-dokum-cekme-payi-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"partLengthMm":0.01,"shrinkPercent":2} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"partLengthMm":-1,"shrinkPercent":2}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"partLengthMm":0.01,"shrinkPercent":2} },
    { id: "rogue-key", kind: "absurd", values: { ...{"partLengthMm":0.01,"shrinkPercent":2}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"partLengthMm":0.01,"shrinkPercent":2} },
  ],
  "fazla-mesai-ucreti-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"overtimeHours":0.01,"hourlyRate":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"overtimeHours":-1,"hourlyRate":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"overtimeHours":0.01,"hourlyRate":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"overtimeHours":0.01,"hourlyRate":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"overtimeHours":0.01,"hourlyRate":0.01} },
  ],
  "forklift-transpalet-kullanim-maliyeti": [
    { id: "golden-valid", kind: "normal", values: {"hourlyRate":0.01,"hours":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"hourlyRate":-1,"hours":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"hourlyRate":0.01,"hours":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"hourlyRate":0.01,"hours":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"hourlyRate":0.01,"hours":0.01} },
  ],
  "fotokopi-yazici-toner-sayfa-maliyeti": [
    { id: "golden-valid", kind: "normal", values: {"tonerCost":0.01,"pageYield":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"tonerCost":-1,"pageYield":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"tonerCost":0.01,"pageYield":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"tonerCost":0.01,"pageYield":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"tonerCost":0.01,"pageYield":0.01} },
  ],
  "gelir-vergisi-dilimleri-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"taxableIncome":0.01,"effectiveRate":15} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"taxableIncome":-1,"effectiveRate":15}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"taxableIncome":0.01,"effectiveRate":15} },
    { id: "rogue-key", kind: "absurd", values: { ...{"taxableIncome":0.01,"effectiveRate":15}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"taxableIncome":0.01,"effectiveRate":15} },
  ],
  "geri-donusum-gelir-maliyet-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"recyclingRevenue":0.01,"processingCost":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"recyclingRevenue":-1,"processingCost":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"recyclingRevenue":0.01,"processingCost":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"recyclingRevenue":0.01,"processingCost":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"recyclingRevenue":0.01,"processingCost":0.01} },
  ],
  "gerilim-dusumu-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"current":0.01,"lineLengthM":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"current":-1,"lineLengthM":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"current":0.01,"lineLengthM":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"current":0.01,"lineLengthM":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"current":0.01,"lineLengthM":0.01} },
  ],
  "hidrolik-pompa-gucu-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"flowLpm":0.01,"pressureBar":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"flowLpm":-1,"pressureBar":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"flowLpm":0.01,"pressureBar":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"flowLpm":0.01,"pressureBar":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"flowLpm":0.01,"pressureBar":0.01} },
  ],
  "hidrolik-silindir-itme-kuvveti-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"pressureBar":0.01,"boreMm":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"pressureBar":-1,"boreMm":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"pressureBar":0.01,"boreMm":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"pressureBar":0.01,"boreMm":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"pressureBar":0.01,"boreMm":0.01} },
  ],
  "ic-verim-orani-irr-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"initialInvestment":0.01,"returnMultiple":1.2} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"initialInvestment":-1,"returnMultiple":1.2}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"initialInvestment":0.01,"returnMultiple":1.2} },
    { id: "rogue-key", kind: "absurd", values: { ...{"initialInvestment":0.01,"returnMultiple":1.2}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"initialInvestment":0.01,"returnMultiple":1.2} },
  ],
  "internet-telefon-paketi-karsilastirma": [
    { id: "golden-valid", kind: "normal", values: {"packageA":0.01,"packageB":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"packageA":-1,"packageB":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"packageA":0.01,"packageB":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"packageA":0.01,"packageB":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"packageA":0.01,"packageB":0.01} },
  ],
  "irsaliye-fatura-adedi-basina-sevkiyat-maliyeti": [
    { id: "golden-valid", kind: "normal", values: {"totalShippingCost":0.01,"documentCount":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"totalShippingCost":-1,"documentCount":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"totalShippingCost":0.01,"documentCount":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"totalShippingCost":0.01,"documentCount":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"totalShippingCost":0.01,"documentCount":0.01} },
  ],
  "is-elbisesi-kkd-kisisel-koruyucu-donanim-sarfiyati": [
    { id: "golden-valid", kind: "normal", values: {"unitCost":0.01,"employeeCount":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"unitCost":-1,"employeeCount":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"unitCost":0.01,"employeeCount":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"unitCost":0.01,"employeeCount":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"unitCost":0.01,"employeeCount":0.01} },
  ],
  "is-kazasi-maliyeti-gun-kaybi-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"dailyOutputValue":0.01,"lostDays":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"dailyOutputValue":-1,"lostDays":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"dailyOutputValue":0.01,"lostDays":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"dailyOutputValue":0.01,"lostDays":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"dailyOutputValue":0.01,"lostDays":0.01} },
  ],
  "is-sagligi-ve-guvenligi-ceza-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"baseFine":0.01,"severityFactor":1.5} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"baseFine":-1,"severityFactor":1.5}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"baseFine":0.01,"severityFactor":1.5} },
    { id: "rogue-key", kind: "absurd", values: { ...{"baseFine":0.01,"severityFactor":1.5}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"baseFine":0.01,"severityFactor":1.5} },
  ],
  "ise-giris-cikis-bildirgesi-sureleri": [
    { id: "golden-valid", kind: "normal", values: {"noticeDays":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"noticeDays":-1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"noticeDays":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"noticeDays":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"noticeDays":0.01} },
  ],
  "isi-degistirici-esanjor-kapasite-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"flowRateM3h":0.01,"deltaTempC":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"flowRateM3h":-1,"deltaTempC":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"flowRateM3h":0.01,"deltaTempC":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"flowRateM3h":0.01,"deltaTempC":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"flowRateM3h":0.01,"deltaTempC":0.01} },
  ],
  "isitma-sogutma-yuku-kcal-kw-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"areaM2":0.01,"loadKcal":100} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"areaM2":-1,"loadKcal":100}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"areaM2":0.01,"loadKcal":100} },
    { id: "rogue-key", kind: "absurd", values: { ...{"areaM2":0.01,"loadKcal":100}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"areaM2":0.01,"loadKcal":100} },
  ],
  "istatistiksel-proses-kontrol-spc-limit-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"processMean":0.01,"controlFactor":3} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"processMean":-1,"controlFactor":3}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"processMean":0.01,"controlFactor":3} },
    { id: "rogue-key", kind: "absurd", values: { ...{"processMean":0.01,"controlFactor":3}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"processMean":0.01,"controlFactor":3} },
  ],
  "istinat-duvari-yaklasik-beton-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"wallLengthM":0.01,"wallHeightM":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"wallLengthM":-1,"wallHeightM":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"wallLengthM":0.01,"wallHeightM":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"wallLengthM":0.01,"wallHeightM":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"wallLengthM":0.01,"wallHeightM":0.01} },
  ],
  "jenerator-kapasitesi-secim-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"peakLoadKw":0.01,"safetyFactor":1.25} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"peakLoadKw":-1,"safetyFactor":1.25}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"peakLoadKw":0.01,"safetyFactor":1.25} },
    { id: "rogue-key", kind: "absurd", values: { ...{"peakLoadKw":0.01,"safetyFactor":1.25}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"peakLoadKw":0.01,"safetyFactor":1.25} },
  ],
  "joule-kalori-watt-saat-cevirici": [
    { id: "golden-valid", kind: "normal", values: {"value":0,"fromUnit":"j"} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"value":-1,"fromUnit":"j"}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"value":0,"fromUnit":"j"} },
    { id: "rogue-key", kind: "absurd", values: { ...{"value":0,"fromUnit":"j"}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"value":0,"fromUnit":"j"} },
  ],
  "kablo-kesiti-mm-secim-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"loadAmps":0.01,"ampacityPerMm2":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"loadAmps":-1,"ampacityPerMm2":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"loadAmps":0.01,"ampacityPerMm2":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"loadAmps":0.01,"ampacityPerMm2":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"loadAmps":0.01,"ampacityPerMm2":0.01} },
  ],
  "kasko-sigorta-prim-karsilastirma": [
    { id: "golden-valid", kind: "normal", values: {"quoteA":0.01,"quoteB":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"quoteA":-1,"quoteB":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"quoteA":0.01,"quoteB":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"quoteA":0.01,"quoteB":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"quoteA":0.01,"quoteB":0.01} },
  ],
  "kaynak-dikis-hacmi-maliyeti-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"throatMm":0.01,"weldLengthM":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"throatMm":-1,"weldLengthM":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"throatMm":0.01,"weldLengthM":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"throatMm":0.01,"weldLengthM":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"throatMm":0.01,"weldLengthM":0.01} },
  ],
  "kaynak-proseduru-wps-on-isitma-sicakligi-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"preheatTempC":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"preheatTempC":-1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"preheatTempC":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"preheatTempC":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"preheatTempC":0.01} },
  ],
  "kaynakli-baglanti-kose-kut-mukavemet-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"throatMm":0.01,"legLengthMm":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"throatMm":-1,"legLengthMm":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"throatMm":0.01,"legLengthMm":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"throatMm":0.01,"legLengthMm":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"throatMm":0.01,"legLengthMm":0.01} },
  ],
  "kdv-tevkifati-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"netAmount":0.01,"withholdingRate":20} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"netAmount":-1,"withholdingRate":20}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"netAmount":0.01,"withholdingRate":20} },
    { id: "rogue-key", kind: "absurd", values: { ...{"netAmount":0.01,"withholdingRate":20}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"netAmount":0.01,"withholdingRate":20} },
  ],
  "kesir-ondalik-cevirici": [
    { id: "golden-valid", kind: "normal", values: {"numerator":0.01,"denominator":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"numerator":-1,"denominator":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"numerator":0.01,"denominator":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"numerator":0.01,"denominator":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"numerator":0.01,"denominator":0.01} },
  ],
  "kesme-bukme-abkant-tonaj-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"sheetLengthMm":0.01,"sheetThicknessMm":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"sheetLengthMm":-1,"sheetThicknessMm":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"sheetLengthMm":0.01,"sheetThicknessMm":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"sheetLengthMm":0.01,"sheetThicknessMm":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"sheetLengthMm":0.01,"sheetThicknessMm":0.01} },
  ],
  "kiris-kolon-yaklasik-agirlik-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"lengthM":0.01,"kgPerMeter":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"lengthM":-1,"kgPerMeter":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"lengthM":0.01,"kgPerMeter":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"lengthM":0.01,"kgPerMeter":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"lengthM":0.01,"kgPerMeter":0.01} },
  ],
  "klima-btu-secim-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"areaM2":0.01,"ceilingM":2.7,"loadFactor":600} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"areaM2":-1,"ceilingM":2.7,"loadFactor":600}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"areaM2":0.01,"ceilingM":2.7,"loadFactor":600} },
    { id: "rogue-key", kind: "absurd", values: { ...{"areaM2":0.01,"ceilingM":2.7,"loadFactor":600}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"areaM2":0.01,"ceilingM":2.7,"loadFactor":600} },
  ],
  "kompresor-debisi-tank-hacmi-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"flowCfm":0.01,"fillMinutes":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"flowCfm":-1,"fillMinutes":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"flowCfm":0.01,"fillMinutes":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"flowCfm":0.01,"fillMinutes":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"flowCfm":0.01,"fillMinutes":0.01} },
  ],
  "koni-hacmi-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"radius":0.01,"height":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"radius":-1,"height":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"radius":0.01,"height":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"radius":0.01,"height":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"radius":0.01,"height":0.01} },
  ],
  "konteyner-yukleme-kapasitesi-teu-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"totalWeightKg":0.01,"unitWeightKg":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"totalWeightKg":-1,"unitWeightKg":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"totalWeightKg":0.01,"unitWeightKg":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"totalWeightKg":0.01,"unitWeightKg":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"totalWeightKg":0.01,"unitWeightKg":0.01} },
  ],
  "kosebent-lama-agirlik-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"length":0.01,"kgPerMeter":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"length":-1,"kgPerMeter":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"length":0.01,"kgPerMeter":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"length":0.01,"kgPerMeter":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"length":0.01,"kgPerMeter":0.01} },
  ],
  "kredi-erken-kapama-cezasi-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"remainingBalance":0.01,"penaltyRate":2} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"remainingBalance":-1,"penaltyRate":2}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"remainingBalance":0.01,"penaltyRate":2} },
    { id: "rogue-key", kind: "absurd", values: { ...{"remainingBalance":0.01,"penaltyRate":2}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"remainingBalance":0.01,"penaltyRate":2} },
  ],
  "kumlama-raspa-kum-sarfiyati-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"surfaceAreaM2":0.01,"abrasiveKgPerM2":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"surfaceAreaM2":-1,"abrasiveKgPerM2":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"surfaceAreaM2":0.01,"abrasiveKgPerM2":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"surfaceAreaM2":0.01,"abrasiveKgPerM2":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"surfaceAreaM2":0.01,"abrasiveKgPerM2":0.01} },
  ],
  "kure-hacmi-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"radius":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"radius":-1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"radius":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"radius":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"radius":0.01} },
  ],
  "lastik-omru-degisim-km-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"remainingTreadKm":0.01,"monthlyKm":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"remainingTreadKm":-1,"monthlyKm":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"remainingTreadKm":0.01,"monthlyKm":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"remainingTreadKm":0.01,"monthlyKm":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"remainingTreadKm":0.01,"monthlyKm":0.01} },
  ],
  "leasing-kiralama-maliyet-karsilastirma": [
    { id: "golden-valid", kind: "normal", values: {"leaseCost":0.01,"rentalCost":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"leaseCost":-1,"rentalCost":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"leaseCost":0.01,"rentalCost":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"leaseCost":0.01,"rentalCost":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"leaseCost":0.01,"rentalCost":0.01} },
  ],
  "lpg-benzin-tasarruf-karsilastirma": [
    { id: "golden-valid", kind: "normal", values: {"lpgCost":0.01,"gasolineCost":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"lpgCost":-1,"gasolineCost":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"lpgCost":0.01,"gasolineCost":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"lpgCost":0.01,"gasolineCost":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"lpgCost":0.01,"gasolineCost":0.01} },
  ],
  "makine-ekonomik-omru-hurda-deger-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"machineCost":0.01,"salvageValue":0.01,"usefulLifeYears":10} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"machineCost":-1,"salvageValue":0.01,"usefulLifeYears":10}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"machineCost":0.01,"salvageValue":0.01,"usefulLifeYears":10} },
    { id: "rogue-key", kind: "absurd", values: { ...{"machineCost":0.01,"salvageValue":0.01,"usefulLifeYears":10}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"machineCost":0.01,"salvageValue":0.01,"usefulLifeYears":10} },
  ],
  "matkap-kilavuz-delik-capi-tablosu": [
    { id: "golden-valid", kind: "normal", values: {"screwDiameterMm":0.01,"drillFactor":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"screwDiameterMm":-1,"drillFactor":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"screwDiameterMm":0.01,"drillFactor":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"screwDiameterMm":0.01,"drillFactor":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"screwDiameterMm":0.01,"drillFactor":0.01} },
  ],
  "merdiven-platform-yukseklik-erisim-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"platformHeightM":0.01,"accessFactor":1.2} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"platformHeightM":-1,"accessFactor":1.2}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"platformHeightM":0.01,"accessFactor":1.2} },
    { id: "rogue-key", kind: "absurd", values: { ...{"platformHeightM":0.01,"accessFactor":1.2}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"platformHeightM":0.01,"accessFactor":1.2} },
  ],
  "mil-aks-capi-hesabi-egilme-burulma": [
    { id: "golden-valid", kind: "normal", values: {"bendingMoment":0.01,"torque":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"bendingMoment":-1,"torque":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"bendingMoment":0.01,"torque":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"bendingMoment":0.01,"torque":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"bendingMoment":0.01,"torque":0.01} },
  ],
  "motor-gucu-kw-hp-cevirici": [
    { id: "golden-valid", kind: "normal", values: {"value":0,"fromUnit":"w"} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"value":-1,"fromUnit":"w"}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"value":0,"fromUnit":"w"} },
    { id: "rogue-key", kind: "absurd", values: { ...{"value":0,"fromUnit":"w"}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"value":0,"fromUnit":"w"} },
  ],
  "mtv-motorlu-tasitlar-vergisi-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"engineCc":0.01,"ageFactor":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"engineCc":-1,"ageFactor":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"engineCc":0.01,"ageFactor":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"engineCc":0.01,"ageFactor":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"engineCc":0.01,"ageFactor":1} },
  ],
  "nakit-akisi-basit-gunluk-haftalik-panosu": [
    { id: "golden-valid", kind: "normal", values: {"dailyInflow":0.01,"days":7} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"dailyInflow":-1,"days":7}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"dailyInflow":0.01,"days":7} },
    { id: "rogue-key", kind: "absurd", values: { ...{"dailyInflow":0.01,"days":7}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"dailyInflow":0.01,"days":7} },
  ],
  "newton-kilogram-kuvvet-cevirici": [
    { id: "golden-valid", kind: "normal", values: {"value":0,"fromUnit":"n"} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"value":-1,"fromUnit":"n"}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"value":0,"fromUnit":"n"} },
    { id: "rogue-key", kind: "absurd", values: { ...{"value":0,"fromUnit":"n"}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"value":0,"fromUnit":"n"} },
  ],
  "npu-npi-profil-agirlik-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"length":0.01,"kgPerMeter":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"length":-1,"kgPerMeter":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"length":0.01,"kgPerMeter":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"length":0.01,"kgPerMeter":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"length":0.01,"kgPerMeter":0.01} },
  ],
  "ofis-kirtasiye-sarfiyat-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"employeeCount":0.01,"monthlySpendPerHead":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"employeeCount":-1,"monthlySpendPerHead":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"employeeCount":0.01,"monthlySpendPerHead":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"employeeCount":0.01,"monthlySpendPerHead":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"employeeCount":0.01,"monthlySpendPerHead":0.01} },
  ],
  "paketleme-malzemesi-strec-koli-sarfiyati": [
    { id: "golden-valid", kind: "normal", values: {"shipmentCount":0.01,"materialPerShipment":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"shipmentCount":-1,"materialPerShipment":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"shipmentCount":0.01,"materialPerShipment":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"shipmentCount":0.01,"materialPerShipment":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"shipmentCount":0.01,"materialPerShipment":0.01} },
  ],
  "palet-ambalaj-kereste-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"palletCount":0.01,"boardLengthM":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"palletCount":-1,"boardLengthM":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"palletCount":0.01,"boardLengthM":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"palletCount":0.01,"boardLengthM":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"palletCount":0.01,"boardLengthM":0.01} },
  ],
  "paslanmaz-celik-aluminyum-ayirt-etme-hesaplayicisi-yogunluk-bazli": [
    { id: "golden-valid", kind: "normal", values: {"densityKgM3":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"densityKgM3":-1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"densityKgM3":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"densityKgM3":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"densityKgM3":0.01} },
  ],
  "personel-devamsizlik-maliyeti-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"dailyWage":0.01,"absentDays":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"dailyWage":-1,"absentDays":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"dailyWage":0.01,"absentDays":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"dailyWage":0.01,"absentDays":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"dailyWage":0.01,"absentDays":0.01} },
  ],
  "plastik-enjeksiyon-cevrim-suresi-tahmini": [
    { id: "golden-valid", kind: "normal", values: {"shotWeightG":0.01,"injectionRateGps":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"shotWeightG":-1,"injectionRateGps":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"shotWeightG":0.01,"injectionRateGps":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"shotWeightG":0.01,"injectionRateGps":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"shotWeightG":0.01,"injectionRateGps":0.01} },
  ],
  "pnomatik-silindir-kuvvet-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"pressureBar":0.01,"boreMm":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"pressureBar":-1,"boreMm":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"pressureBar":0.01,"boreMm":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"pressureBar":0.01,"boreMm":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"pressureBar":0.01,"boreMm":0.01} },
  ],
  "pompa-gucu-basma-yuksekligi-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"flowM3h":0.01,"headM":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"flowM3h":-1,"headM":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"flowM3h":0.01,"headM":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"flowM3h":0.01,"headM":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"flowM3h":0.01,"headM":0.01} },
  ],
  "prefabrik-konteyner-ofis-m-maliyeti": [
    { id: "golden-valid", kind: "normal", values: {"areaM2":0.01,"costPerM2":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"areaM2":-1,"costPerM2":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"areaM2":0.01,"costPerM2":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"areaM2":0.01,"costPerM2":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"areaM2":0.01,"costPerM2":0.01} },
  ],
  "prefabrik-konteyner-olcu-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"length":0.01,"width":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"length":-1,"width":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"length":0.01,"width":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"length":0.01,"width":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"length":0.01,"width":0.01} },
  ],
  "radyator-petek-boyu-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"heatLoadKcal":0.01,"panelOutputKcal":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"heatLoadKcal":-1,"panelOutputKcal":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"heatLoadKcal":0.01,"panelOutputKcal":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"heatLoadKcal":0.01,"panelOutputKcal":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"heatLoadKcal":0.01,"panelOutputKcal":0.01} },
  ],
  "rastgele-sayi-ureteci": [
    { id: "golden-valid", kind: "normal", values: {"minValue":1,"maxValue":100} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"minValue":1,"maxValue":100}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"minValue":1,"maxValue":100} },
    { id: "rogue-key", kind: "absurd", values: { ...{"minValue":1,"maxValue":100}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"minValue":1,"maxValue":100} },
  ],
  "rulman-omur-hesabi-l10": [
    { id: "golden-valid", kind: "normal", values: {"dynamicLoadKn":0.01,"basicLoadKn":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"dynamicLoadKn":-1,"basicLoadKn":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"dynamicLoadKn":0.01,"basicLoadKn":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"dynamicLoadKn":0.01,"basicLoadKn":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"dynamicLoadKn":0.01,"basicLoadKn":0.01} },
  ],
  "ruzgar-turbini-yaklasik-uretim-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"ratedKw":0.01,"capacityFactor":0.25} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"ratedKw":-1,"capacityFactor":0.25}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"ratedKw":0.01,"capacityFactor":0.25} },
    { id: "rogue-key", kind: "absurd", values: { ...{"ratedKw":0.01,"capacityFactor":0.25}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"ratedKw":0.01,"capacityFactor":0.25} },
  ],
  "ses-yalitimi-desibel-azaltimi-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"sourceDb":0.01,"attenuationDb":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"sourceDb":-1,"attenuationDb":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"sourceDb":0.01,"attenuationDb":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"sourceDb":0.01,"attenuationDb":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"sourceDb":0.01,"attenuationDb":0.01} },
  ],
  "sgk-prim-hesaplama-isci-plus-isveren": [
    { id: "golden-valid", kind: "normal", values: {"grossWage":0.01,"combinedRate":34.5} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"grossWage":-1,"combinedRate":34.5}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"grossWage":0.01,"combinedRate":34.5} },
    { id: "rogue-key", kind: "absurd", values: { ...{"grossWage":0.01,"combinedRate":34.5}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"grossWage":0.01,"combinedRate":34.5} },
  ],
  "silindir-hacmi-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"radius":0.01,"height":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"radius":-1,"height":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"radius":0.01,"height":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"radius":0.01,"height":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"radius":0.01,"height":0.01} },
  ],
  "sirket-telefon-faturasi-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"lineCount":0.01,"monthlyLineCost":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"lineCount":-1,"monthlyLineCost":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"lineCount":0.01,"monthlyLineCost":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"lineCount":0.01,"monthlyLineCost":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"lineCount":0.01,"monthlyLineCost":0.01} },
  ],
  "sofor-operator-gunluk-yevmiye-maliyeti": [
    { id: "golden-valid", kind: "normal", values: {"dailyRate":0.01,"days":22} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"dailyRate":-1,"days":22}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"dailyRate":0.01,"days":22} },
    { id: "rogue-key", kind: "absurd", values: { ...{"dailyRate":0.01,"days":22}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"dailyRate":0.01,"days":22} },
  ],
  "soguk-oda-sogutma-yuku-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"roomVolumeM3":0.01,"loadFactor":40} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"roomVolumeM3":-1,"loadFactor":40}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"roomVolumeM3":0.01,"loadFactor":40} },
    { id: "rogue-key", kind: "absurd", values: { ...{"roomVolumeM3":0.01,"loadFactor":40}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"roomVolumeM3":0.01,"loadFactor":40} },
  ],
  "sogutma-sivisi-karisim-orani-antifriz-bor-yagi-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"antifreezeLiters":0.01,"totalLiters":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"antifreezeLiters":-1,"totalLiters":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"antifreezeLiters":0.01,"totalLiters":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"antifreezeLiters":0.01,"totalLiters":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"antifreezeLiters":0.01,"totalLiters":0.01} },
  ],
  "stopaj-hesaplama-kira-serbest-meslek": [
    { id: "golden-valid", kind: "normal", values: {"grossAmount":0.01,"withholdingRate":20} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"grossAmount":-1,"withholdingRate":20}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"grossAmount":0.01,"withholdingRate":20} },
    { id: "rogue-key", kind: "absurd", values: { ...{"grossAmount":0.01,"withholdingRate":20}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"grossAmount":0.01,"withholdingRate":20} },
  ],
  "su-debisi-litre-dakika-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"volumeLiters":0.01,"minutes":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"volumeLiters":-1,"minutes":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"volumeLiters":0.01,"minutes":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"volumeLiters":0.01,"minutes":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"volumeLiters":0.01,"minutes":0.01} },
  ],
  "su-deposu-hacmi-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"radius":1.2,"height":2.5} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"radius":-1,"height":2.5}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"radius":1.2,"height":2.5} },
    { id: "rogue-key", kind: "absurd", values: { ...{"radius":1.2,"height":2.5}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"radius":1.2,"height":2.5} },
  ],
  "su-isitma-kazan-boyler-kapasite-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"volumeLiters":0.01,"deltaTempC":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"volumeLiters":-1,"deltaTempC":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"volumeLiters":0.01,"deltaTempC":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"volumeLiters":0.01,"deltaTempC":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"volumeLiters":0.01,"deltaTempC":0.01} },
  ],
  "tahta-mdf-sunta-m-agirlik-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"areaM2":0.01,"kgPerM2":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"areaM2":-1,"kgPerM2":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"areaM2":0.01,"kgPerM2":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"areaM2":0.01,"kgPerM2":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"areaM2":0.01,"kgPerM2":0.01} },
  ],
  "tel-kablo-uzunlugu-agirlik-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"lengthM":0.01,"kgPerMeter":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"lengthM":-1,"kgPerMeter":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"lengthM":0.01,"kgPerMeter":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"lengthM":0.01,"kgPerMeter":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"lengthM":0.01,"kgPerMeter":0.01} },
  ],
  "temizlik-malzemesi-sarfiyat-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"areaM2":0.01,"consumptionPerM2":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"areaM2":-1,"consumptionPerM2":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"areaM2":0.01,"consumptionPerM2":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"areaM2":0.01,"consumptionPerM2":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"areaM2":0.01,"consumptionPerM2":0.01} },
  ],
  "tir-kamyon-yuk-kapasitesi-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"payloadTon":0.01,"loadFactor":0.85} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"payloadTon":-1,"loadFactor":0.85}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"payloadTon":0.01,"loadFactor":0.85} },
    { id: "rogue-key", kind: "absurd", values: { ...{"payloadTon":0.01,"loadFactor":0.85}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"payloadTon":0.01,"loadFactor":0.85} },
  ],
  "titresim-frekans-periyot-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"frequencyHz":0.01,"unitConstant":1} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"frequencyHz":-1,"unitConstant":1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"frequencyHz":0.01,"unitConstant":1} },
    { id: "rogue-key", kind: "absurd", values: { ...{"frequencyHz":0.01,"unitConstant":1}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"frequencyHz":0.01,"unitConstant":1} },
  ],
  "toplanti-saati-maliyeti-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"attendeeRate":0.01,"attendeeHours":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"attendeeRate":-1,"attendeeHours":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"attendeeRate":0.01,"attendeeHours":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"attendeeRate":0.01,"attendeeHours":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"attendeeRate":0.01,"attendeeHours":0.01} },
  ],
  "topraklama-direnci-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"measuredOhms":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"measuredOhms":-1}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"measuredOhms":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"measuredOhms":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"measuredOhms":0.01} },
  ],
  "trafik-cezasi-gecikme-faizi-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"fineAmount":0.01,"lateRate":5} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"fineAmount":-1,"lateRate":5}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"fineAmount":0.01,"lateRate":5} },
    { id: "rogue-key", kind: "absurd", values: { ...{"fineAmount":0.01,"lateRate":5}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"fineAmount":0.01,"lateRate":5} },
  ],
  "ucgen-alani-cevresi-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"base":0.01,"height":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"base":-1,"height":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"base":0.01,"height":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"base":0.01,"height":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"base":0.01,"height":0.01} },
  ],
  "ups-kesintisiz-guc-kaynagi-secimi": [
    { id: "golden-valid", kind: "normal", values: {"loadWatts":0.01,"runtimeMinutes":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"loadWatts":-1,"runtimeMinutes":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"loadWatts":0.01,"runtimeMinutes":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"loadWatts":0.01,"runtimeMinutes":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"loadWatts":0.01,"runtimeMinutes":0.01} },
  ],
  "vida-somun-adim-dis-ustu-cap-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"pitchMm":0.01,"threadCount":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"pitchMm":-1,"threadCount":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"pitchMm":0.01,"threadCount":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"pitchMm":0.01,"threadCount":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"pitchMm":0.01,"threadCount":0.01} },
  ],
  "yalitim-malzemesi-m-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"areaM2":0.01,"layers":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"areaM2":-1,"layers":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"areaM2":0.01,"layers":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"areaM2":0.01,"layers":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"areaM2":0.01,"layers":0.01} },
  ],
  "yamuk-alani-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"baseA":0.01,"baseB":0.01,"height":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"baseA":-1,"baseB":0.01,"height":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"baseA":0.01,"baseB":0.01,"height":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"baseA":0.01,"baseB":0.01,"height":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"baseA":0.01,"baseB":0.01,"height":0.01} },
  ],
  "yangin-merdiveni-kacis-yolu-genisligi-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"occupantLoad":0.01,"flowPerMeter":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"occupantLoad":-1,"flowPerMeter":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"occupantLoad":0.01,"flowPerMeter":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"occupantLoad":0.01,"flowPerMeter":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"occupantLoad":0.01,"flowPerMeter":0.01} },
  ],
  "yangin-tupu-dolap-debisi-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"areaM2":0.01,"flowFactor":0.5} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"areaM2":-1,"flowFactor":0.5}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"areaM2":0.01,"flowFactor":0.5} },
    { id: "rogue-key", kind: "absurd", values: { ...{"areaM2":0.01,"flowFactor":0.5}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"areaM2":0.01,"flowFactor":0.5} },
  ],
  "yatak-rulman-omur-hesabi-l10": [
    { id: "golden-valid", kind: "normal", values: {"dynamicLoadKn":0.01,"basicLoadKn":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"dynamicLoadKn":-1,"basicLoadKn":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"dynamicLoadKn":0.01,"basicLoadKn":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"dynamicLoadKn":0.01,"basicLoadKn":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"dynamicLoadKn":0.01,"basicLoadKn":0.01} },
  ],
  "yay-helisel-kuvvet-uzama-hesabi": [
    { id: "golden-valid", kind: "normal", values: {"springRate":0.01,"deflectionMm":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"springRate":-1,"deflectionMm":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"springRate":0.01,"deflectionMm":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"springRate":0.01,"deflectionMm":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"springRate":0.01,"deflectionMm":0.01} },
  ],
  "yemek-tabldot-maliyet-hesaplama": [
    { id: "golden-valid", kind: "normal", values: {"mealCost":0.01,"headcount":0.01} },
    { id: "missing-input", kind: "edge", values: {}, expectPass: false },
    { id: "invalid-negative", kind: "edge", values: {"mealCost":-1,"headcount":0.01}, expectPass: false },
    { id: "boundary-min", kind: "edge", values: {"mealCost":0.01,"headcount":0.01} },
    { id: "rogue-key", kind: "absurd", values: { ...{"mealCost":0.01,"headcount":0.01}, rogueKey: 999 } },
    { id: "valid-success", kind: "normal", values: {"mealCost":0.01,"headcount":0.01} },
  ],
};

export function compareRoadmapFreeBatchProductionVsOracle(input: {
  readonly slug: RoadmapFreeBatchOracleSlug;
  readonly scenarioId: string;
  readonly values: FreeTrafficInputValues;
}): OracleComparisonResult {
  const toolId = `free-traffic.${input.slug}`;
  const parseKind = getRoadmapFreeBatchParseKind(input.slug);
  const tolerance = toleranceForParseKind(parseKind);

  if (NON_DETERMINISTIC_SLUGS.has(input.slug)) {
    try {
      const output = extractRoadmapFreeBatchRecommendedPrice(input.slug, input.values);
      return {
        status: Number.isFinite(output.recommendedPrice) ? "PASS" : "FAIL",
        slug: input.slug,
        toolId,
        scenarioId: input.scenarioId,
        diffs: [],
      };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      return {
        status: "FAIL",
        slug: input.slug,
        toolId,
        scenarioId: input.scenarioId,
        diffs: [],
        message,
      };
    }
  }

  let production;
  try {
    production = extractRoadmapFreeBatchRecommendedPrice(input.slug, input.values);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return {
      status: "FAIL",
      slug: input.slug,
      toolId,
      scenarioId: input.scenarioId,
      diffs: [],
      message,
    };
  }

  let oracle;
  try {
    oracle = calculateRoadmapFreeBatchOracle(input.slug, input.values);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return {
      status: "FAIL",
      slug: input.slug,
      toolId,
      scenarioId: input.scenarioId,
      diffs: [],
      message,
    };
  }

  const comparison = compareNumericFields([
    {
      field: "recommendedPrice",
      production: production.recommendedPrice,
      oracle: oracle.recommendedPrice,
      tolerance,
    },
  ]);

  return {
    status: comparison.passed ? "PASS" : "FAIL",
    slug: input.slug,
    toolId,
    scenarioId: input.scenarioId,
    diffs: comparison.diffs,
  };
}

export function runRoadmapFreeBatchOracleComparisonAudit(
  slug: RoadmapFreeBatchOracleSlug,
): OracleComparisonAuditSummary {
  const toolId = `free-traffic.${slug}`;
  const locator = getRoadmapFreeBatchProductionFormulaLocator(slug);
  const scenarios = SCENARIOS_BY_SLUG[slug] ?? [];
  const comparableScenarios = scenarios.filter((scenario) => scenario.expectPass !== false);

  if (!locator?.comparisonWired || !hasOracleForTool(toolId)) {
    return {
      slug,
      toolId,
      status: "NOT_WIRED",
      passCount: 0,
      failCount: 0,
      needsAdapterCount: 0,
      notWiredCount: comparableScenarios.length,
      results: comparableScenarios.map((scenario) => ({
        slug,
        toolId,
        scenarioId: scenario.id,
        status: "NOT_WIRED" as const,
        diffs: [],
      })),
    };
  }

  const results = comparableScenarios.map((scenario) =>
    compareRoadmapFreeBatchProductionVsOracle({
      slug,
      scenarioId: scenario.id,
      values: scenario.values,
    }),
  );

  const passCount = results.filter((result) => result.status === "PASS").length;
  const failCount = results.filter((result) => result.status === "FAIL").length;
  const needsAdapterCount = results.filter((result) => result.status === "NEEDS_ADAPTER").length;

  let status: OracleComparisonStatus = "PASS";
  if (failCount > 0) {
    status = "FAIL";
  } else if (needsAdapterCount > 0) {
    status = "NEEDS_ADAPTER";
  } else if (passCount === 0) {
    status = "NOT_WIRED";
  }

  return {
    slug,
    toolId,
    status,
    passCount,
    failCount,
    needsAdapterCount,
    notWiredCount: 0,
    results,
  };
}

export function runAllRoadmapFreeBatchOracleComparisonAudits(): readonly OracleComparisonAuditSummary[] {
  return ROADMAP_FREE_BATCH_ORACLE_SLUGS.map((slug) => runRoadmapFreeBatchOracleComparisonAudit(slug));
}
