/**
 * Engine module production formula locators.
 * GENERATED by scripts/generate-formula-governance-gap-closure.ts — do not edit manually.
 */

import type { ProductionFormulaLocator } from "@/lib/formula-governance/oracle/production-formula-locator";

export const ENGINE_MODULES_PRODUCTION_FORMULA_LOCATORS: readonly ProductionFormulaLocator[] = [
  {
    slug: "fuel-consumption-check",
    toolId: "revenue-free.fuel-consumption-check",
    productionFilePath: "src/lib/tools/sectors/sector-calculators.ts",
    productionFunctionName: "calculateSectorTool",
    productionEntry: "fuel-consumption-check sector route → fuel cost",
    oracleFunctionName: "hasEngineModulesOracle",
    inputShape: ["distanceKm", "consumptionPer100Km", "fuelPricePerLiter"],
    productionOutputShape: ["recommendedPrice", "fuelCost"],
    oracleOutputShape: ["recommendedPrice"],
    comparisonWired: false,
  },
  {
    slug: "margincore-risk-engine",
    toolId: "engine.risk-engine",
    productionFilePath: "src/lib/tools/risk-engine.ts",
    productionFunctionName: "calculateRiskEngine",
    productionEntry: "MarginCore risk engine → safePrice",
    oracleFunctionName: "hasEngineModulesOracle",
    inputShape: ["expectedCost", "variance", "emissionFactor", "carbonPrice"],
    productionOutputShape: ["safePrice", "recommendedPrice", "verdict"],
    oracleOutputShape: ["safePrice"],
    comparisonWired: false,
  },
  {
    slug: "sector-margin-calculators",
    toolId: "engine.sector-calculators",
    productionFilePath: "src/lib/tools/sectors/sector-calculators.ts",
    productionFunctionName: "calculateSectorTool",
    productionEntry: "sector margin calculators → naiveCost",
    oracleFunctionName: "hasEngineModulesOracle",
    inputShape: ["naiveCost", "marginLeak", "verdict"],
    productionOutputShape: ["naiveCost", "recommendedPrice"],
    oracleOutputShape: ["recommendedPrice"],
    comparisonWired: false,
  },
];

export function getEngineModulesProductionFormulaLocator(
  slug: string,
): ProductionFormulaLocator | undefined {
  return ENGINE_MODULES_PRODUCTION_FORMULA_LOCATORS.find((entry) => entry.slug === slug);
}

export function isEngineModulesProductionSlug(slug: string): boolean {
  return ENGINE_MODULES_PRODUCTION_FORMULA_LOCATORS.some((entry) => entry.slug === slug);
}
