/**
 * Premium schema extended oracle registry — mirror via runPremiumSchemaEngine.
 * GENERATED by scripts/generate-formula-governance-gap-closure.ts — do not edit manually.
 */

import { getPremiumCalculatorSchema } from "@/lib/premium-schema/schema-registry";
import type { SchemaInputValues } from "@/lib/premium-schema/premium-calculator-schema";
import { runPremiumSchemaEngine } from "@/lib/premium-schema/premium-schema-engine";

export const PREMIUM_SCHEMA_EXTENDED_ORACLE_SCHEMA_IDS = [
  "7-israf-muda-avcisi-parasal-karsilik-calculator",
  "annual-leave-severance-notice-calculator",
  "auto-repair-parts-labor-quote-calculator",
  "belt-pulley-speed-length-calculator",
  "bolt-tightening-torque-calculator",
  "break-even-safety-margin-calculator",
  "cbam-unit-product-carbon-footprint-calculator",
  "compressor-leak-cost-calculator",
  "downtime-minute-cost-calculator",
  "employee-total-cost-calculator",
  "energy-savings-package-calculator",
  "fire-system-flow-hydrant-calculator",
  "hydraulic-pneumatic-cylinder-force-calculator",
  "inventory-carrying-cost-eoq-calculator",
  "investment-payback-npv-calculator",
  "oee-equipment-effectiveness-calculator",
  "pressure-vessel-wall-thickness-calculator",
  "product-customer-profitability-calculator",
  "quality-cost-paf-calculator",
  "quote-price-profit-margin-calculator",
  "shop-rate-hourly-cost-calculator",
  "six-sigma-project-prioritizer",
  "tolerance-stack-up-calculator",
  "value-stream-map-vsm-calculator",
  "welded-bolted-connection-calculator",
] as const;

export type PremiumSchemaExtendedOracleSchemaId =
  (typeof PREMIUM_SCHEMA_EXTENDED_ORACLE_SCHEMA_IDS)[number];

export const PREMIUM_SCHEMA_EXTENDED_ORACLE_TOOL_IDS = Object.fromEntries(
  PREMIUM_SCHEMA_EXTENDED_ORACLE_SCHEMA_IDS.map((schemaId) => [
    `premium-schema.${schemaId}`,
    schemaId,
  ]),
) as Record<string, PremiumSchemaExtendedOracleSchemaId>;

export type NormalizedPremiumSchemaExtendedOutput = Readonly<{
  readonly minimumSafePrice: number;
  readonly p90Cost: number;
  readonly recommendedPrice: number;
}>;

export function isPremiumSchemaExtendedOracleSchemaId(
  schemaId: string,
): schemaId is PremiumSchemaExtendedOracleSchemaId {
  return (PREMIUM_SCHEMA_EXTENDED_ORACLE_SCHEMA_IDS as readonly string[]).includes(schemaId);
}

export function calculatePremiumSchemaExtendedOracle(
  schemaId: PremiumSchemaExtendedOracleSchemaId,
  values: SchemaInputValues,
): NormalizedPremiumSchemaExtendedOutput {
  const schema = getPremiumCalculatorSchema(schemaId);
  if (!schema) {
    throw new Error(`Unknown premium schema id: ${schemaId}`);
  }
  const result = runPremiumSchemaEngine(schema, values, "en");
  if (!Number.isFinite(result.minimumSafePrice)) {
    throw new Error(`Oracle could not produce finite minimumSafePrice for "${schemaId}".`);
  }
  return {
    minimumSafePrice: result.minimumSafePrice,
    p90Cost: result.p90Exposure,
    recommendedPrice: result.minimumSafePrice,
  };
}

export function extractPremiumSchemaExtendedOutput(
  schemaId: PremiumSchemaExtendedOracleSchemaId,
  values: SchemaInputValues,
): NormalizedPremiumSchemaExtendedOutput {
  return calculatePremiumSchemaExtendedOracle(schemaId, values);
}
