// SectorCalc PRO V5.3.1 — Baris Product Registry
// 45 sellable products: 20 INSTANT_PRO_CALCULATOR + 25 ASSISTED_PRO_DOSSIER
// Server-side only. Never imported by client modules.
// Paddle price IDs resolved via env keys, not hardcoded. Payment provider: PADDLE.
import "server-only";

export type ProductMode = "INSTANT_PRO_CALCULATOR" | "ASSISTED_PRO_DOSSIER";
export type ExecutionMode = "LIVE_ENGINE_READY" | "DISABLED_UNTIL_FORMULA_READY";
export type PaymentProductType = "PRO_INSTANT_CALCULATOR" | "PRO_DOSSIER_REQUEST";

export interface BarisProProduct {
  toolKey: string;
  toolName: string;
  priceUsd: number;
  visible: true;
  sellable: true;
  productMode: ProductMode;
  executionMode: ExecutionMode;
  paymentProductType: PaymentProductType;
  paymentProvider: "PADDLE";
  stripePriceEnvKey: string;
  paddlePriceEnvKey: string;
  entitlementRequired: true;
  routeEnabled: true;
  instantResultAvailable: boolean;
  ctaLabel: string;
  publicBadge: string;
  publicNotice: string;
}

export const BARIS_PRO_PRODUCTS: BarisProProduct[] = [
  // ── BATCH 1: 10 INSTANT PRO CALCULATORS ──────────────────────────────────
  {
    toolKey: "break-even-survival-cash-calculator",
    toolName: "Break-Even & Survival Cash Calculator",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_BREAK_EVEN_SURVIVAL_CASH_CALCULATOR",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_BREAK_EVEN_SURVIVAL_CASH_CALCULATOR",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "machine-hourly-rate-proof-report",
    toolName: "Machine Hourly Rate Proof Report",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_MACHINE_HOURLY_RATE_PROOF_REPORT",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_MACHINE_HOURLY_RATE_PROOF_REPORT",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "loss-making-job-detector",
    toolName: "Loss Making Job Detector",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_LOSS_MAKING_JOB_DETECTOR",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_LOSS_MAKING_JOB_DETECTOR",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "receivables-cost-payment-term-addendum",
    toolName: "Receivables Cost & Payment Term Addendum",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_RECEIVABLES_COST_PAYMENT_TERM_ADDENDUM",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_RECEIVABLES_COST_PAYMENT_TERM_ADDENDUM",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "setup-time-reduction-roi-smed",
    toolName: "Setup Time Reduction ROI (SMED)",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_SETUP_TIME_REDUCTION_ROI_SMED",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_SETUP_TIME_REDUCTION_ROI_SMED",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "product-sku-margin-ranker",
    toolName: "Product SKU Margin Ranker",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_PRODUCT_SKU_MARGIN_RANKER",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_PRODUCT_SKU_MARGIN_RANKER",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "true-employee-cost-statement",
    toolName: "True Employee Cost Statement",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_TRUE_EMPLOYEE_COST_STATEMENT",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_TRUE_EMPLOYEE_COST_STATEMENT",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "job-quote-builder-pro-pack",
    toolName: "Job Quote Builder Pro Pack",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_JOB_QUOTE_BUILDER_PRO_PACK",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_JOB_QUOTE_BUILDER_PRO_PACK",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "machine-investment-feasibility-buy-lease-keep",
    toolName: "Machine Investment Feasibility (Buy / Lease / Keep)",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_MACHINE_INVESTMENT_FEASIBILITY_BUY_LEASE_KEEP",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_MACHINE_INVESTMENT_FEASIBILITY_BUY_LEASE_KEEP",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "capital-equipment-investment-appraisal-npv-irr",
    toolName: "Capital Equipment Investment Appraisal (NPV / IRR)",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_CAPITAL_EQUIPMENT_INVESTMENT_APPRAISAL_NPV_IRR",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_CAPITAL_EQUIPMENT_INVESTMENT_APPRAISAL_NPV_IRR",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },

  // ── BATCH 2: 10 INSTANT PRO CALCULATORS ──────────────────────────────────
  {
    toolKey: "customer-sku-profitability-forensics",
    toolName: "Customer SKU Profitability Forensics",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_CUSTOMER_SKU_PROFITABILITY_FORENSICS",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_CUSTOMER_SKU_PROFITABILITY_FORENSICS",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "downtime-scrap-loss-statement",
    toolName: "Downtime & Scrap Loss Statement",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_DOWNTIME_SCRAP_LOSS_STATEMENT",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_DOWNTIME_SCRAP_LOSS_STATEMENT",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "oee-loss-monetization-improvement-business-case",
    toolName: "OEE Loss Monetization & Improvement Business Case",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_OEE_LOSS_MONETIZATION_IMPROVEMENT_BUSINESS_CASE",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_OEE_LOSS_MONETIZATION_IMPROVEMENT_BUSINESS_CASE",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "scrap-rework-cost-tracker",
    toolName: "Scrap & Rework Cost Tracker",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_SCRAP_REWORK_COST_TRACKER",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_SCRAP_REWORK_COST_TRACKER",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "outsource-vs-in-house-analyzer",
    toolName: "Outsource vs. In-House Analyzer",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_OUTSOURCE_VS_IN_HOUSE_ANALYZER",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_OUTSOURCE_VS_IN_HOUSE_ANALYZER",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "plant-wide-shop-rate-cost-structure-audit",
    toolName: "Plant-Wide Shop Rate Cost Structure Audit",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_PLANT_WIDE_SHOP_RATE_COST_STRUCTURE_AUDIT",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_PLANT_WIDE_SHOP_RATE_COST_STRUCTURE_AUDIT",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "fx-commodity-pass-through-pricer",
    toolName: "FX & Commodity Pass-Through Pricer",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_FX_COMMODITY_PASS_THROUGH_PRICER",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_FX_COMMODITY_PASS_THROUGH_PRICER",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "energy-efficiency-grant-incentive-feasibility-pack",
    toolName: "Energy Efficiency Grant & Incentive Feasibility Pack",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_ENERGY_EFFICIENCY_GRANT_INCENTIVE_FEASIBILITY_PACK",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_ENERGY_EFFICIENCY_GRANT_INCENTIVE_FEASIBILITY_PACK",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "motor-compressor-replacement-roi",
    toolName: "Motor & Compressor Replacement ROI",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_MOTOR_COMPRESSOR_REPLACEMENT_ROI",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_MOTOR_COMPRESSOR_REPLACEMENT_ROI",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "weld-procedure-cost-consumable-estimation-suite",
    toolName: "Weld Procedure Cost & Consumable Estimation Suite",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_WELD_PROCEDURE_COST_CONSUMABLE_ESTIMATION_SUITE",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_WELD_PROCEDURE_COST_CONSUMABLE_ESTIMATION_SUITE",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },

  // ── BLOCKED SOURCE REQUIRED: 15 ASSISTED DOSSIER PRODUCTS ─────────────────
  {
    toolKey: "pressure-vessel-wall-thickness-mawp-hydrotest-package",
    toolName: "Pressure Vessel Wall Thickness MAWP & Hydrotest Package",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_PRESSURE_VESSEL_WALL_THICKNESS_MAWP_HYDROTEST_PACKAGE",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_PRESSURE_VESSEL_WALL_THICKNESS_MAWP_HYDROTEST_PACKAGE",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "pressure-relief-valve-sizing-sheet-api-520",
    toolName: "Pressure Relief Valve Sizing Sheet (API 520)",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_PRESSURE_RELIEF_VALVE_SIZING_SHEET_API_520",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_PRESSURE_RELIEF_VALVE_SIZING_SHEET_API_520",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "fillet-weld-sizing-verification-sheet-ec3-aws-d11",
    toolName: "Fillet Weld Sizing Verification Sheet (EC3 / AWS D1.1)",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_FILLET_WELD_SIZING_VERIFICATION_SHEET_EC3_AWS_D11",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_FILLET_WELD_SIZING_VERIFICATION_SHEET_EC3_AWS_D11",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "structural-connection-verification-dossier-ec3-aisc",
    toolName: "Structural Connection Verification Dossier (EC3 / AISC)",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_STRUCTURAL_CONNECTION_VERIFICATION_DOSSIER_EC3_AISC",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_STRUCTURAL_CONNECTION_VERIFICATION_DOSSIER_EC3_AISC",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "bolted-connection-verifier",
    toolName: "Bolted Connection Verifier",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_BOLTED_CONNECTION_VERIFIER",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_BOLTED_CONNECTION_VERIFIER",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "bolt-torque-preload-spec-card-vdi-2230",
    toolName: "Bolt Torque Preload Spec Card (VDI 2230)",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_BOLT_TORQUE_PRELOAD_SPEC_CARD_VDI_2230",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_BOLT_TORQUE_PRELOAD_SPEC_CARD_VDI_2230",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "lifting-rigging-crane-plan-suite",
    toolName: "Lifting, Rigging & Crane Plan Suite",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_LIFTING_RIGGING_CRANE_PLAN_SUITE",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_LIFTING_RIGGING_CRANE_PLAN_SUITE",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "gdt-fit-clearance-calculator-iso-286",
    toolName: "GDT Fit Clearance Calculator (ISO 286)",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_GDT_FIT_CLEARANCE_CALCULATOR_ISO_286",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_GDT_FIT_CLEARANCE_CALCULATOR_ISO_286",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "tolerance-stack-up-root-cause-report-wc-rss",
    toolName: "Tolerance Stack-Up Root Cause Report (WC / RSS)",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_TOLERANCE_STACK_UP_ROOT_CAUSE_REPORT_WC_RSS",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_TOLERANCE_STACK_UP_ROOT_CAUSE_REPORT_WC_RSS",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "measurement-uncertainty-budget-gum-iso-17025",
    toolName: "Measurement Uncertainty Budget (GUM / ISO 17025)",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_MEASUREMENT_UNCERTAINTY_BUDGET_GUM_ISO_17025",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_MEASUREMENT_UNCERTAINTY_BUDGET_GUM_ISO_17025",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "first-article-inspection-report-builder-as9102-lite",
    toolName: "First Article Inspection Report Builder (AS9102 Lite)",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_FIRST_ARTICLE_INSPECTION_REPORT_BUILDER_AS9102_LITE",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_FIRST_ARTICLE_INSPECTION_REPORT_BUILDER_AS9102_LITE",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "compressed-air-leak-energy-audit-report-iso-11011",
    toolName: "Compressed Air Leak Energy Audit Report (ISO 11011)",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_COMPRESSED_AIR_LEAK_ENERGY_AUDIT_REPORT_ISO_11011",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_COMPRESSED_AIR_LEAK_ENERGY_AUDIT_REPORT_ISO_11011",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "cbam-definitive-period-compliance-package",
    toolName: "CBAM Definitive Period Compliance Package",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_CBAM_DEFINITIVE_PERIOD_COMPLIANCE_PACKAGE",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_CBAM_DEFINITIVE_PERIOD_COMPLIANCE_PACKAGE",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "cbam-cost-exposure-hedging-forecaster",
    toolName: "CBAM Cost Exposure & Hedging Forecaster",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_CBAM_COST_EXPOSURE_HEDGING_FORECASTER",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_CBAM_COST_EXPOSURE_HEDGING_FORECASTER",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "cbam-supplier-emissions-data-sheet",
    toolName: "CBAM Supplier Emissions Data Sheet",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_CBAM_SUPPLIER_EMISSIONS_DATA_SHEET",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_CBAM_SUPPLIER_EMISSIONS_DATA_SHEET",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },

  // ── RUNTIME CONTRACT BLOCKED: 10 ASSISTED DOSSIER PRODUCTS ───────────────
  {
    toolKey: "machining-cycle-time-part-cost-sheet",
    toolName: "Machining Cycle Time & Part Cost Sheet",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_MACHINING_CYCLE_TIME_PART_COST_SHEET",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_MACHINING_CYCLE_TIME_PART_COST_SHEET",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "sealed-job-quote-certificate-fire-setup-vade",
    toolName: "Sealed Job Quote Certificate (Fire Setup / Vade)",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_SEALED_JOB_QUOTE_CERTIFICATE_FIRE_SETUP_VADE",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_SEALED_JOB_QUOTE_CERTIFICATE_FIRE_SETUP_VADE",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "steel-structure-weight-cost-takeoff",
    toolName: "Steel Structure Weight & Cost Takeoff",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_STEEL_STRUCTURE_WEIGHT_COST_TAKEOFF",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_STEEL_STRUCTURE_WEIGHT_COST_TAKEOFF",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "compressed-air-pipe-sizing-pressure-drop",
    toolName: "Compressed Air Pipe Sizing & Pressure Drop",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_COMPRESSED_AIR_PIPE_SIZING_PRESSURE_DROP",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_COMPRESSED_AIR_PIPE_SIZING_PRESSURE_DROP",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "hydraulic-cylinder-pump-sizing",
    toolName: "Hydraulic Cylinder & Pump Sizing",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_HYDRAULIC_CYLINDER_PUMP_SIZING",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_HYDRAULIC_CYLINDER_PUMP_SIZING",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "pump-system-curve-npsh-verifier",
    toolName: "Pump System Curve & NPSH Verifier",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_PUMP_SYSTEM_CURVE_NPSH_VERIFIER",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_PUMP_SYSTEM_CURVE_NPSH_VERIFIER",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "shaft-deflection-critical-speed-check",
    toolName: "Shaft Deflection & Critical Speed Check",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_SHAFT_DEFLECTION_CRITICAL_SPEED_CHECK",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_SHAFT_DEFLECTION_CRITICAL_SPEED_CHECK",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "scope-1-2-3-splitter-for-smes",
    toolName: "Scope 1-2-3 Splitter for SMEs",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_SCOPE_1_2_3_SPLITTER_FOR_SMES",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_SCOPE_1_2_3_SPLITTER_FOR_SMES",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "bank-grade-financial-projection-covenant-model",
    toolName: "Bank-Grade Financial Projection & Covenant Model",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_BANK_GRADE_FINANCIAL_PROJECTION_COVENANT_MODEL",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_BANK_GRADE_FINANCIAL_PROJECTION_COVENANT_MODEL",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "ppap-gauge-rr-cpk-ppk-quality-submission-bundle",
    toolName: "PPAP Gauge R&R CPK PPK Quality Submission Bundle",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    stripePriceEnvKey: "STRIPE_PRICE_BARIS_PPAP_GAUGE_RR_CPK_PPK_QUALITY_SUBMISSION_BUNDLE",
    paymentProvider: "PADDLE",
    paddlePriceEnvKey: "PADDLE_PRICE_BARIS_PPAP_GAUGE_RR_CPK_PPK_QUALITY_SUBMISSION_BUNDLE",
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
];

// ── Lookup helpers ───────────────────────────────────────────────────────────

export function getBarisProduct(toolKey: string): BarisProProduct | undefined {
  return BARIS_PRO_PRODUCTS.find(p => p.toolKey === toolKey);
}

export function isBarisProduct(toolKey: string): boolean {
  return BARIS_PRO_PRODUCTS.some(p => p.toolKey === toolKey);
}

export function getInstantCalculatorProducts(): BarisProProduct[] {
  return BARIS_PRO_PRODUCTS.filter(p => p.productMode === "INSTANT_PRO_CALCULATOR");
}

export function getAssistedDossierProducts(): BarisProProduct[] {
  return BARIS_PRO_PRODUCTS.filter(p => p.productMode === "ASSISTED_PRO_DOSSIER");
}

export function getBarisProductSummary(): {
  total: number;
  visible: number;
  sellable: number;
  instantCalculators: number;
  assistedDossiers: number;
} {
  return {
    total: BARIS_PRO_PRODUCTS.length,
    visible: BARIS_PRO_PRODUCTS.filter(p => p.visible).length,
    sellable: BARIS_PRO_PRODUCTS.filter(p => p.sellable).length,
    instantCalculators: getInstantCalculatorProducts().length,
    assistedDossiers: getAssistedDossierProducts().length,
  };
}
