// SectorCalc PRO V5.3.1 — Baris Product Registry
// 45 sellable products: 20 INSTANT_PRO_CALCULATOR + 25 ASSISTED_PRO_DOSSIER
// Server-side only. Never imported by client modules.
// Key-pool model: users purchase key packs via Paddle (single env var). Payment provider: KEY_POOL.
import "server-only";

export type ProductMode = "INSTANT_PRO_CALCULATOR" | "ASSISTED_PRO_DOSSIER";
export type ExecutionMode = "LIVE_ENGINE_READY" | "DISABLED_UNTIL_FORMULA_READY";
export type PaymentProductType = "PRO_INSTANT_CALCULATOR" | "PRO_DOSSIER_REQUEST";

export interface BarisProProduct {
  toolKey: string;
  toolName: string;
  priceUsd: number;
  visible: true;
  sellable: true;
  productMode: ProductMode;
  executionMode: ExecutionMode;
  paymentProductType: PaymentProductType;
  paymentProvider: "KEY_POOL";
  keyCost: number;
  entitlementRequired: true;
  routeEnabled: true;
  instantResultAvailable: boolean;
  ctaLabel: string;
  publicBadge: string;
  publicNotice: string;
}

export const BARIS_PRO_PRODUCTS: BarisProProduct[] = [
  // ── BATCH 1: 10 INSTANT PRO CALCULATORS ──────────────────────────────────
  {
    toolKey: "break-even-survival-cash-calculator",
    toolName: "Break-Even & Survival Cash Calculator",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "machine-hourly-rate-proof-report",
    toolName: "Machine Hourly Rate Proof Report",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "loss-making-job-detector",
    toolName: "Loss Making Job Detector",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "receivables-cost-payment-term-addendum",
    toolName: "Receivables Cost & Payment Term Addendum",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "setup-time-reduction-roi-smed",
    toolName: "Setup Time Reduction ROI (SMED)",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "product-sku-margin-ranker",
    toolName: "Product SKU Margin Ranker",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "true-employee-cost-statement",
    toolName: "True Employee Cost Statement",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "job-quote-builder-pro-pack",
    toolName: "Job Quote Builder Pro Pack",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "machine-investment-feasibility-buy-lease-keep",
    toolName: "Machine Investment Feasibility (Buy / Lease / Keep)",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "capital-equipment-investment-appraisal-npv-irr",
    toolName: "Capital Equipment Investment Appraisal (NPV / IRR)",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },

  // ── BATCH 2: 10 INSTANT PRO CALCULATORS ──────────────────────────────────
  {
    toolKey: "customer-sku-profitability-forensics",
    toolName: "Customer SKU Profitability Forensics",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "downtime-scrap-loss-statement",
    toolName: "Downtime & Scrap Loss Statement",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "oee-loss-monetization-improvement-business-case",
    toolName: "OEE Loss Monetization & Improvement Business Case",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "scrap-rework-cost-tracker",
    toolName: "Scrap & Rework Cost Tracker",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "outsource-vs-in-house-analyzer",
    toolName: "Outsource vs. In-House Analyzer",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "plant-wide-shop-rate-cost-structure-audit",
    toolName: "Plant-Wide Shop Rate Cost Structure Audit",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "fx-commodity-pass-through-pricer",
    toolName: "FX & Commodity Pass-Through Pricer",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "energy-efficiency-grant-incentive-feasibility-pack",
    toolName: "Energy Efficiency Grant & Incentive Feasibility Pack",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "motor-compressor-replacement-roi",
    toolName: "Motor & Compressor Replacement ROI",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },
  {
    toolKey: "weld-procedure-cost-consumable-estimation-suite",
    toolName: "Weld Procedure Cost & Consumable Estimation Suite",
    priceUsd: 49,
    visible: true, sellable: true,
    productMode: "INSTANT_PRO_CALCULATOR",
    executionMode: "LIVE_ENGINE_READY",
    paymentProductType: "PRO_INSTANT_CALCULATOR",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: true,
    ctaLabel: "Start PRO Calculation",
    publicBadge: "PRO Calculator",
    publicNotice: "Requires paid PRO entitlement before execution.",
  },

  // ── BLOCKED SOURCE REQUIRED: 15 ASSISTED DOSSIER PRODUCTS ─────────────────
  {
    toolKey: "pressure-vessel-wall-thickness-mawp-hydrotest-package",
    toolName: "Pressure Vessel Wall Thickness MAWP & Hydrotest Package",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "pressure-relief-valve-sizing-sheet-api-520",
    toolName: "Pressure Relief Valve Sizing Sheet (API 520)",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "fillet-weld-sizing-verification-sheet-ec3-aws-d11",
    toolName: "Fillet Weld Sizing Verification Sheet (EC3 / AWS D1.1)",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "structural-connection-verification-dossier-ec3-aisc",
    toolName: "Structural Connection Verification Dossier (EC3 / AISC)",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "bolted-connection-verifier",
    toolName: "Bolted Connection Verifier",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "bolt-torque-preload-spec-card-vdi-2230",
    toolName: "Bolt Torque Preload Spec Card (VDI 2230)",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "lifting-rigging-crane-plan-suite",
    toolName: "Lifting, Rigging & Crane Plan Suite",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "gdt-fit-clearance-calculator-iso-286",
    toolName: "GDT Fit Clearance Calculator (ISO 286)",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "tolerance-stack-up-root-cause-report-wc-rss",
    toolName: "Tolerance Stack-Up Root Cause Report (WC / RSS)",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "measurement-uncertainty-budget-gum-iso-17025",
    toolName: "Measurement Uncertainty Budget (GUM / ISO 17025)",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "first-article-inspection-report-builder-as9102-lite",
    toolName: "First Article Inspection Report Builder (AS9102 Lite)",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "compressed-air-leak-energy-audit-report-iso-11011",
    toolName: "Compressed Air Leak Energy Audit Report (ISO 11011)",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "cbam-definitive-period-compliance-package",
    toolName: "CBAM Definitive Period Compliance Package",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "cbam-cost-exposure-hedging-forecaster",
    toolName: "CBAM Cost Exposure & Hedging Forecaster",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "cbam-supplier-emissions-data-sheet",
    toolName: "CBAM Supplier Emissions Data Sheet",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },

  // ── RUNTIME CONTRACT BLOCKED: 10 ASSISTED DOSSIER PRODUCTS ───────────────
  {
    toolKey: "machining-cycle-time-part-cost-sheet",
    toolName: "Machining Cycle Time & Part Cost Sheet",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "sealed-job-quote-certificate-fire-setup-vade",
    toolName: "Sealed Job Quote Certificate (Fire Setup / Vade)",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "steel-structure-weight-cost-takeoff",
    toolName: "Steel Structure Weight & Cost Takeoff",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "compressed-air-pipe-sizing-pressure-drop",
    toolName: "Compressed Air Pipe Sizing & Pressure Drop",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "hydraulic-cylinder-pump-sizing",
    toolName: "Hydraulic Cylinder & Pump Sizing",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "pump-system-curve-npsh-verifier",
    toolName: "Pump System Curve & NPSH Verifier",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "shaft-deflection-critical-speed-check",
    toolName: "Shaft Deflection & Critical Speed Check",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "scope-1-2-3-splitter-for-smes",
    toolName: "Scope 1-2-3 Splitter for SMEs",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "bank-grade-financial-projection-covenant-model",
    toolName: "Bank-Grade Financial Projection & Covenant Model",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
  {
    toolKey: "ppap-gauge-rr-cpk-ppk-quality-submission-bundle",
    toolName: "PPAP Gauge R&R CPK PPK Quality Submission Bundle",
    priceUsd: 99,
    visible: true, sellable: true,
    productMode: "ASSISTED_PRO_DOSSIER",
    executionMode: "DISABLED_UNTIL_FORMULA_READY",
    paymentProductType: "PRO_DOSSIER_REQUEST",
    paymentProvider: "KEY_POOL",
    keyCost: 1,
    entitlementRequired: true, routeEnabled: true,
    instantResultAvailable: false,
    ctaLabel: "Start PRO Dossier Request",
    publicBadge: "PRO Dossier",
    publicNotice: "Source verification is required before calculation output.",
  },
];

// ── Lookup helpers ───────────────────────────────────────────────────────────

export function getBarisProduct(toolKey: string): BarisProProduct | undefined {
  return BARIS_PRO_PRODUCTS.find(p => p.toolKey === toolKey);
}

export function isBarisProduct(toolKey: string): boolean {
  return BARIS_PRO_PRODUCTS.some(p => p.toolKey === toolKey);
}

export function getInstantCalculatorProducts(): BarisProProduct[] {
  return BARIS_PRO_PRODUCTS.filter(p => p.productMode === "INSTANT_PRO_CALCULATOR");
}

export function getAssistedDossierProducts(): BarisProProduct[] {
  return BARIS_PRO_PRODUCTS.filter(p => p.productMode === "ASSISTED_PRO_DOSSIER");
}

export function getBarisProductSummary(): {
  total: number;
  visible: number;
  sellable: number;
  instantCalculators: number;
  assistedDossiers: number;
} {
  return {
    total: BARIS_PRO_PRODUCTS.length,
    visible: BARIS_PRO_PRODUCTS.filter(p => p.visible).length,
    sellable: BARIS_PRO_PRODUCTS.filter(p => p.sellable).length,
    instantCalculators: getInstantCalculatorProducts().length,
    assistedDossiers: getAssistedDossierProducts().length,
  };
}
