import type { GlobalToolCategorySlug } from "@/lib/catalog/global-tool-category-taxonomy";

export type CategoryTaxonomyEntry = {
  readonly slug: string;
  readonly trTitle: string;
  readonly enTitle: string;
  readonly sector: string;
  readonly sectorKey: string;
  readonly globalCategorySlug: GlobalToolCategorySlug;
  readonly keywords: readonly string[];
};

/** 21 professional tool categories — profession, sector, and expertise oriented. */
export const CATEGORY_TAXONOMY: Readonly<Record<string, CategoryTaxonomyEntry>> = {
  "Makine & Tasarım": {
    slug: "makine-tasarim",
    trTitle: "Makine & Tasarım",
    enTitle: "Mechanical Design",
    sector: "Teknik & Mühendislik",
    sectorKey: "teknik-muhendislik",
    globalCategorySlug: "cnc-additive-manufacturing",
    keywords: [
      "beam",
      "deflection",
      "torque",
      "bolt",
      "weld",
      "stress",
      "strain",
      "bearing",
      "gear",
      "spring",
      "shaft",
      "moment",
      "shear",
      "torsion",
      "fatigue",
      "buckling",
      "pulley",
      "lever",
      "mechanical",
      "static",
      "dynamic",
    ],
  },
  "İmalat & Üretim": {
    slug: "imalat-uretim",
    trTitle: "İmalat & Üretim",
    enTitle: "Manufacturing & Production",
    sector: "Üretim & İmalat",
    sectorKey: "uretim-imalat",
    globalCategorySlug: "cnc-additive-manufacturing",
    keywords: [
      "cnc",
      "machining",
      "cutting",
      "oee",
      "cycle time",
      "tool life",
      "machining cost",
      "spindle",
      "feed rate",
      "setup",
      "scrap",
      "nesting",
      "production",
      "manufacturing",
      "workshop",
      "lathe",
      "milling",
    ],
  },
  "Malzeme & Metalurji": {
    slug: "malzeme-metalurji",
    trTitle: "Malzeme & Metalurji",
    enTitle: "Materials & Metallurgy",
    sector: "Teknik & Mühendislik",
    sectorKey: "teknik-muhendislik",
    globalCategorySlug: "metal-plastics-forming",
    keywords: [
      "hardness",
      "thermal",
      "conductivity",
      "alloy",
      "heat treatment",
      "material",
      "metal",
      "plastic",
      "density",
      "melting",
      "yield strength",
      "tensile",
      "metallurgy",
      "composite",
    ],
  },
  "Akışkanlar & Termodinamik": {
    slug: "akiskanlar-termodinamik",
    trTitle: "Akışkanlar & Termodinamik",
    enTitle: "Fluids & Thermodynamics",
    sector: "Teknik & Mühendislik",
    sectorKey: "teknik-muhendislik",
    globalCategorySlug: "process-chemical",
    keywords: [
      "reynolds",
      "heat",
      "thermo",
      "compressor",
      "flow",
      "hydraulic",
      "pneumatic",
      "pump",
      "pipe",
      "fluid",
      "viscosity",
      "pressure drop",
      "enthalpy",
      "exchanger",
      "boiler",
      "steam",
    ],
  },
  "Elektrik & Otomasyon": {
    slug: "elektrik-otomasyon",
    trTitle: "Elektrik & Otomasyon",
    enTitle: "Electrical & Automation",
    sector: "Teknik & Mühendislik",
    sectorKey: "teknik-muhendislik",
    globalCategorySlug: "electrical-power-systems",
    keywords: [
      "voltage",
      "motor",
      "power",
      "automation",
      "plc",
      "drive",
      "electrical",
      "current",
      "resistance",
      "capacitor",
      "inductor",
      "transformer",
      "watt",
      "ampere",
      "ohm",
      "circuit",
      "inverter",
    ],
  },
  "İnşaat & Yapı": {
    slug: "insaat-yapi",
    trTitle: "İnşaat & Yapı",
    enTitle: "Construction & Structures",
    sector: "İnşaat & Saha",
    sectorKey: "insaat-saha",
    globalCategorySlug: "project-construction-management",
    keywords: [
      "concrete",
      "foundation",
      "wind load",
      "seismic",
      "column",
      "roof",
      "rebar",
      "mortar",
      "brick",
      "excavation",
      "footing",
      "slab",
      "truss",
      "construction",
      "building",
      "structural",
    ],
  },
  "Yalın Üretim": {
    slug: "yalin-uretim",
    trTitle: "Yalın Üretim",
    enTitle: "Lean Production",
    sector: "Üretim & İmalat",
    sectorKey: "uretim-imalat",
    globalCategorySlug: "lean-production",
    keywords: [
      "smed",
      "5s",
      "kaizen",
      "muda",
      "lean",
      "changeover",
      "kanban",
      "vsm",
      "takt",
      "andon",
      "heijunka",
      "poka",
      "value stream",
    ],
  },
  "Kalite & Süreç Kontrol": {
    slug: "kalite-surec-kontrol",
    trTitle: "Kalite & Süreç Kontrol",
    enTitle: "Quality & Process Control",
    sector: "Üretim & İmalat",
    sectorKey: "uretim-imalat",
    globalCategorySlug: "quality-six-sigma",
    keywords: [
      "spc",
      "six sigma",
      "cpk",
      "ppm",
      "quality cost",
      "paf",
      "gage",
      "fmea",
      "sigma",
      "aql",
      "defect",
      "yield",
      "process capability",
    ],
  },
  "Bakım & Güvenilirlik": {
    slug: "bakim-guvenilirlik",
    trTitle: "Bakım & Güvenilirlik",
    enTitle: "Maintenance & Reliability",
    sector: "Üretim & İmalat",
    sectorKey: "uretim-imalat",
    globalCategorySlug: "maintenance-reliability",
    keywords: [
      "mtbf",
      "mttr",
      "maintenance",
      "reliability",
      "downtime",
      "failure",
      "repair",
      "spare part",
      "preventive",
      "rca",
      "uptime",
    ],
  },
  "Lojistik & Tedarik Zinciri": {
    slug: "lojistik-tedarik-zinciri",
    trTitle: "Lojistik & Tedarik Zinciri",
    enTitle: "Logistics & Supply Chain",
    sector: "Lojistik & Sevkiyat",
    sectorKey: "lojistik-sevkiyat",
    globalCategorySlug: "procurement-supply-chain",
    keywords: [
      "eoq",
      "inventory",
      "route",
      "warehouse",
      "logistics",
      "supply chain",
      "shipping",
      "freight",
      "procurement",
      "moq",
      "lead time",
      "transport",
      "delivery",
    ],
  },
  "Enerji & Sürdürülebilirlik": {
    slug: "enerji-surdurulebilirlik",
    trTitle: "Enerji & Sürdürülebilirlik",
    enTitle: "Energy & Sustainability",
    sector: "Enerji & Karbon",
    sectorKey: "enerji-karbon",
    globalCategorySlug: "sustainability-resource-esg",
    keywords: [
      "kwh",
      "carbon",
      "compressor leak",
      "led",
      "energy",
      "sustainability",
      "green",
      "solar",
      "emission",
      "scope",
      "cbam",
      "esg",
      "footprint",
      "efficiency",
    ],
  },
  "Maliyet & Bütçeleme": {
    slug: "maliyet-butceleme",
    trTitle: "Maliyet & Bütçeleme",
    enTitle: "Cost & Budgeting",
    sector: "Finans & İK",
    sectorKey: "finans-ik",
    globalCategorySlug: "finance-sales-working-capital",
    keywords: [
      "cost",
      "budget",
      "break even",
      "margin",
      "markup",
      "profit",
      "pricing",
      "quote",
      "expense",
      "overhead",
      "unit cost",
      "breakeven",
    ],
  },
  "İK & Personel": {
    slug: "ik-personel",
    trTitle: "İK & Personel",
    enTitle: "HR & Personnel",
    sector: "Finans & İK",
    sectorKey: "finans-ik",
    globalCategorySlug: "workforce-hr",
    keywords: [
      "employee",
      "salary",
      "overtime",
      "payroll",
      "hr",
      "personnel",
      "workforce",
      "turnover",
      "hiring",
      "labor",
      "wage",
      "shift",
      "headcount",
    ],
  },
  "Proje & Yatırım": {
    slug: "proje-yatirim",
    trTitle: "Proje & Yatırım",
    enTitle: "Project & Investment",
    sector: "Finans & İK",
    sectorKey: "finans-ik",
    globalCategorySlug: "finance-sales-working-capital",
    keywords: [
      "npv",
      "irr",
      "payback",
      "investment",
      "roi",
      "project",
      "evm",
      "cpm",
      "capital",
      "discount rate",
      "present value",
      "annuity",
    ],
  },
  "Vergi & Finansal Raporlama": {
    slug: "vergi-finansal-raporlama",
    trTitle: "Vergi & Finansal Raporlama",
    enTitle: "Tax & Financial Reporting",
    sector: "Finans & İK",
    sectorKey: "finans-ik",
    globalCategorySlug: "finance-sales-working-capital",
    keywords: [
      "tax",
      "depreciation",
      "vat",
      "financial",
      "reporting",
      "amortization",
      "mortgage",
      "loan",
      "interest",
      "income tax",
      "sales tax",
      "1031",
      "capital gains",
    ],
  },
  "İSG & Risk Yönetimi": {
    slug: "isg-risk-yonetimi",
    trTitle: "İSG & Risk Yönetimi",
    enTitle: "HSE & Risk Management",
    sector: "İSG & Risk",
    sectorKey: "isg-risk",
    globalCategorySlug: "hse-ergonomics",
    keywords: [
      "risk",
      "ergonomics",
      "noise",
      "safety",
      "hazard",
      "ppe",
      "accident",
      "injury",
      "osha",
      "hse",
      "workplace safety",
    ],
  },
  "Çevre & Emisyon": {
    slug: "cevre-emisyon",
    trTitle: "Çevre & Emisyon",
    enTitle: "Environment & Emissions",
    sector: "Sürdürülebilirlik",
    sectorKey: "surdurulebilirlik",
    globalCategorySlug: "sustainability-resource-esg",
    keywords: [
      "water",
      "waste",
      "emission",
      "recycle",
      "environment",
      "pollution",
      "wastewater",
      "landfill",
      "ecology",
      "biodiversity",
    ],
  },
  "Kalite & Laboratuvar": {
    slug: "kalite-laboratuvar",
    trTitle: "Kalite & Laboratuvar",
    enTitle: "Quality & Laboratory",
    sector: "Kalite, SPC & Altı Sigma",
    sectorKey: "kalite-spc-alti-sigma",
    globalCategorySlug: "quality-six-sigma",
    keywords: [
      "sample size",
      "test",
      "measurement",
      "calibration",
      "lab",
      "converter",
      "conversion",
      "unit",
      "percent",
      "fraction",
      "ratio",
      "standard deviation",
      "statistics",
      "probability",
      "gauge",
    ],
  },
  "Gıda & Tarım": {
    slug: "gida-tarim",
    trTitle: "Gıda & Tarım",
    enTitle: "Food & Agriculture",
    sector: "Perakende & Gıda",
    sectorKey: "perakende-gida",
    globalCategorySlug: "food-cold-chain-hygiene",
    keywords: [
      "recipe",
      "yield",
      "fertilizer",
      "crop",
      "food",
      "feed",
      "agriculture",
      "farm",
      "harvest",
      "livestock",
      "menu",
      "baking",
      "nutrition",
    ],
  },
  "Tekstil & Moda": {
    slug: "tekstil-moda",
    trTitle: "Tekstil & Moda",
    enTitle: "Textile & Fashion",
    sector: "Perakende & Gıda",
    sectorKey: "perakende-gida",
    globalCategorySlug: "textile-print-lab",
    keywords: [
      "fabric",
      "textile",
      "dye",
      "sewing",
      "yarn",
      "weaving",
      "garment",
      "print",
      "pattern",
    ],
  },
  Otomotiv: {
    slug: "otomotiv",
    trTitle: "Otomotiv",
    enTitle: "Automotive",
    sector: "Üretim & İmalat",
    sectorKey: "uretim-imalat",
    globalCategorySlug: "maintenance-reliability",
    keywords: [
      "auto",
      "repair",
      "vehicle",
      "fuel",
      "car",
      "automotive",
      "tire",
      "mpg",
      "mileage",
      "engine",
      "brake",
      "transmission",
    ],
  },
};

export const TAXONOMY_CATEGORY_NAMES = Object.keys(CATEGORY_TAXONOMY) as Array<
  keyof typeof CATEGORY_TAXONOMY
>;

export function listTaxonomyCategorySlugs(): readonly string[] {
  return TAXONOMY_CATEGORY_NAMES.map((name) => CATEGORY_TAXONOMY[name].slug);
}

export function getTaxonomyEntryBySlug(slug: string): CategoryTaxonomyEntry | undefined {
  return TAXONOMY_CATEGORY_NAMES.map((name) => CATEGORY_TAXONOMY[name]).find(
    (entry) => entry.slug === slug,
  );
}

export function getTaxonomyEntryByTitle(title: string): CategoryTaxonomyEntry | undefined {
  return CATEGORY_TAXONOMY[title];
}
