/**
 * SectorCalc - Sektor, Meslek Dali ve Category Taksonomisi
 * Endustriyel disiplin + yasam alani hibrit siniflandirma (Tekla / Ansys / Omni tarzi).
 */

export interface Sector {
  id: string;
  label: string;
  labelEn: string;
  professions: string[];
  keywords: string[];
  /** Lucide icon key - UI resolves via taxonomy-sector-icon-map. */
  icon: string;
}

export interface Category {
  id: string;
  label: string;
  labelEn: string;
  keywords: string[];
}

/** High-confidence slug-token → sector hints (data-driven from catalog frequency). */
export const SLUG_TOKEN_SECTOR_HINTS: Readonly<Record<string, string>> = {
  converter: "birim-donusum",
  calorie: "saglik",
  area: "matematik",
  weight: "saglik",
  equation: "matematik",
  probability: "istatistik",
  integral: "matematik",
  matrix: "matematik",
  vector: "matematik",
  fraction: "matematik",
  fractions: "matematik",
  decimal: "matematik",
  percent: "matematik",
  percentage: "matematik",
  theorem: "matematik",
  solver: "matematik",
  polynomial: "matematik",
  regression: "istatistik",
  anova: "istatistik",
  percentile: "istatistik",
  swimming: "fitness-spor",
  running: "fitness-spor",
  cycling: "fitness-spor",
  pace: "fitness-spor",
  marathon: "fitness-spor",
  training: "fitness-spor",
  muscle: "fitness-spor",
  vo2: "fitness-spor",
  diet: "gida",
  baby: "saglik",
  heart: "saglik",
  blood: "saglik",
  sleep: "saglik",
  fasting: "saglik",
  breathing: "saglik",
  ovulation: "saglik",
  pregnancy: "saglik",
  workout: "fitness-spor",
  yoga: "fitness-spor",
  zumba: "fitness-spor",
  metabolic: "saglik",
  cholesterol: "saglik",
  body: "saglik",
  age: "ev-yasam",
  date: "ev-yasam",
  calendar: "ev-yasam",
  grade: "egitim",
  college: "egitim",
  mortgage: "emlak",
  rent: "emlak",
  pipe: "hidrolik-pnomatik",
  pressure: "fizik",
  force: "fizik",
  velocity: "fizik",
  flow: "fizik",
  load: "yapisal-muhendislik",
  beam: "yapisal-muhendislik",
  concrete: "insaat",
  rebar: "insaat",
  welding: "metal",
  weld: "metal",
  solar: "yenilenebilir",
  wind: "yenilenebilir",
  turbine: "havacilik",
  aircraft: "havacilik",
  ship: "denizcilik",
  vessel: "denizcilik",
  truck: "otomotiv",
  tire: "otomotiv",
  brake: "otomotiv",
  engine: "otomotiv",
  cnc: "makine",
  lathe: "makine",
  injection: "plastik",
  mold: "plastik",
  recipe: "gida",
  baking: "gida",
  abv: "gida",
  beer: "gida",
  crop: "tarim",
  harvest: "tarim",
  irrigation: "tarim",
  fertilizer: "tarim",
  mine: "madencilik",
  ore: "madencilik",
  network: "telekom",
  fiber: "telekom",
  router: "telekom",
  loan: "finans",
  interest: "finans",
  tax: "finans",
  payroll: "finans",
  inventory: "lojistik",
  warehouse: "lojistik",
  shipping: "lojistik",
  cargo: "kargo",
  freight: "kargo",
  hotel: "turizm",
  travel: "turizm",
  pool: "su-yonetimi",
  aquarium: "su-yonetimi",
  wastewater: "su-yonetimi",
  carbon: "cevre",
  emission: "cevre",
  recycle: "cevre",
  circuit: "elektronik",
  resistor: "elektronik",
  capacitor: "elektronik",
  adc: "elektronik",
  packaging: "ambalaj-baski",
  print: "ambalaj-baski",
  lumber: "mobilya-ahsap",
  wood: "mobilya-ahsap",
  furniture: "mobilya-ahsap",
  petroleum: "petrokimya",
  refinery: "petrokimya",
  cattle: "tarim",
  livestock: "tarim",
  veterinary: "tarim",
  hydraulic: "hidrolik-pnomatik",
  pneumatic: "hidrolik-pnomatik",
  rail: "demiryolu",
  train: "demiryolu",
  ceramic: "cam-seramik",
  glass: "cam-seramik",
  ergonomics: "isg-risk",
  hazard: "isg-risk",
  noise: "optik-akustik",
  acoustic: "optik-akustik",
  pixel: "gorsel-medya",
  color: "gorsel-medya",
  image: "gorsel-medya",
  software: "bilisim",
  cloud: "bilisim",
  database: "bilisim",
  textile: "tekstil",
  fabric: "tekstil",
  cleaning: "temizlik",
  hygiene: "temizlik",
  pharma: "kimya",
  chemical: "kimya",
  reaction: "kimya",
  molar: "kimya",
  titration: "kimya",
  abc: "lojistik",
  ach: "finans",
  thermogenesis: "saglik",
  amazon: "perakende",
  fba: "perakende",
  ari: "makine",
  ascii: "bilisim",
  checksum: "bilisim",
  atom: "kimya",
  atomik: "kimya",
  atomic: "kimya",
  kutle: "fizik",
  ekonomisi: "finans",
  attribution: "perakende",
  baldness: "saglik",
  balloon: "finans",
  kredi: "finans",
  bevel: "makine",
  braces: "saglik",
  bread: "gida",
  brining: "gida",
  burn: "finans",
  c1v1: "kimya",
  c2v2: "kimya",
  chess: "egitim",
  churn: "perakende",
  clv: "perakende",
  cobra: "finans",
  coefficient: "istatistik",
  commission: "finans",
  conic: "matematik",
  cosmological: "fizik",
  cpa: "perakende",
  critical: "insaat",
  customs: "lojistik",
  cashback: "perakende",
  clustering: "istatistik",
  coin: "finans",
  consolidation: "finans",
  cut: "makine",
  clearance: "makine",
  stair: "insaat",
  gear: "makine",
  baccarat: "finans",
  card: "finans",
  rating: "egitim",
  auc: "istatistik",
  roc: "istatistik",
  curve: "matematik",
  function: "matematik",
  fee: "finans",
  cash: "finans",
  return: "finans",
  rule: "matematik",
  level: "ev-yasam",
  minutes: "ev-yasam",
  seconds: "ev-yasam",
  distance: "matematik",
  path: "lojistik",
  analysis: "istatistik",
  fit: "makine",
  value: "finans",
  text: "bilisim",
  citation: "egitim",
  poker: "finans",
  gambling: "finans",
  slot: "finans",
  roulette: "finans",
  blackjack: "finans",
  lottery: "finans",
  odds: "istatistik",
  ev: "otomotiv",
  startup: "finans",
  runway: "finans",
  valuation: "finans",
  dilution: "finans",
  equity: "finans",
  option: "finans",
  futures: "finans",
  hedge: "finans",
  swap: "finans",
  forex: "finans",
  crypto: "finans",
  bitcoin: "finans",
  ethereum: "finans",
  mining: "madencilik",
  nft: "bilisim",
  token: "bilisim",
  hash: "bilisim",
  encryption: "bilisim",
  password: "bilisim",
  subnet: "telekom",
  ip: "telekom",
  dns: "telekom",
  vpn: "telekom",
  ssl: "bilisim",
  tls: "bilisim",
  jwt: "bilisim",
  oauth: "bilisim",
  regex: "bilisim",
  json: "bilisim",
  xml: "bilisim",
  yaml: "bilisim",
  markdown: "bilisim",
  base64: "bilisim",
  unicode: "bilisim",
  utf: "bilisim",
  morse: "bilisim",
  barcode: "ambalaj-baski",
  qrcode: "ambalaj-baski",
  stamp: "ambalaj-baski",
  postage: "kargo",
  tariff: "lojistik",
  duty: "lojistik",
  import: "lojistik",
  export: "lojistik",
  incoterm: "lojistik",
  fob: "lojistik",
  cif: "lojistik",
  demurrage: "denizcilik",
  bunker: "denizcilik",
  draft: "denizcilik",
  anchorage: "denizcilik",
  mooring: "denizcilik",
  ballast: "denizcilik",
  trim: "denizcilik",
  heel: "denizcilik",
  metacentric: "denizcilik",
  stability: "denizcilik",
  scantling: "denizcilik",
  fillet: "metal",
  groove: "metal",
  penetration: "metal",
  distortion: "metal",
  shrinkage: "metal",
  preheat: "metal",
  interpass: "metal",
  hardness: "metal",
  hrc: "metal",
  hb: "metal",
  hv: "metal",
  roughness: "makine",
  tolerance: "makine",
  interference: "makine",
  gd: "makine",
  datum: "makine",
  cmm: "makine",
  probe: "makine",
  stylus: "makine",
  thread: "makine",
  pitch: "makine",
  lead: "makine",
  tap: "makine",
  die: "makine",
  chamfer: "makine",
  deburr: "makine",
  honing: "makine",
  lapping: "makine",
  broaching: "makine",
  hobbing: "makine",
  shaping: "makine",
  planing: "makine",
  boring: "makine",
  reaming: "makine",
  tapping: "makine",
  knurling: "makine",
  parting: "makine",
  facing: "makine",
  turning: "makine",
  milling: "makine",
  drilling: "makine",
  grinding: "makine",
  edm: "makine",
  laser: "makine",
  plasma: "makine",
  waterjet: "makine",
  abrasive: "makine",
  coolant: "makine",
  chip: "makine",
  swarf: "makine",
  insert: "makine",
  carbide: "makine",
  hss: "makine",
  coating: "makine",
  tin: "makine",
  ticn: "makine",
  alcrn: "makine",
  drywall: "insaat",
  stucco: "insaat",
  roofing: "insaat",
  gambrel: "insaat",
  rigging: "makine",
  flange: "makine",
  nozzle: "makine",
  duathlon: "fitness-spor",
  equestrian: "fitness-spor",
  hiking: "fitness-spor",
  met: "fitness-spor",
  sinclair: "fitness-spor",
  skateboard: "fitness-spor",
  tempo: "fitness-spor",
  reps: "fitness-spor",
  jump: "fitness-spor",
  rope: "fitness-spor",
  dijkstra: "matematik",
  divergence: "matematik",
  gradient: "matematik",
  gcf: "matematik",
  iqr: "istatistik",
  kendall: "istatistik",
  dbscan: "istatistik",
  decomposition: "matematik",
  quaternion: "matematik",
  radical: "matematik",
  recurrence: "matematik",
  partition: "matematik",
  predicate: "matematik",
  logic: "matematik",
  roman: "matematik",
  stirling: "matematik",
  ncr: "matematik",
  hanoi: "matematik",
  karnaugh: "elektronik",
  polar: "matematik",
  koordinat: "matematik",
  donuturucu: "birim-donusum",
  decades: "birim-donusum",
  centuries: "birim-donusum",
  stone: "birim-donusum",
  octal: "bilisim",
  kb: "bilisim",
  tree: "bilisim",
  disk: "matematik",
  dice: "istatistik",
  roller: "istatistik",
  dollar: "finans",
  averaging: "finans",
  dps: "finans",
  etf: "finans",
  franchise: "finans",
  leverage: "finans",
  vat: "finans",
  pip: "finans",
  roa: "finans",
  roic: "finans",
  ira: "finans",
  sep: "finans",
  toll: "turizm",
  true: "finans",
  birikim: "egitim",
  transcript: "egitim",
  plagiarism: "egitim",
  deadline: "ev-yasam",
  moon: "ev-yasam",
  pond: "ev-yasam",
  liner: "ev-yasam",
  espresso: "gida",
  kombucha: "gida",
  paleo: "gida",
  pizza: "gida",
  sourdough: "gida",
  yogurt: "gida",
  sugar: "gida",
  stages: "gida",
  electronegativity: "kimya",
  hess: "kimya",
  yasasi: "kimya",
  kc: "kimya",
  npk: "tarim",
  ntu: "su-yonetimi",
  ecog: "saglik",
  mindfulness: "saglik",
  whitening: "saglik",
  smoking: "saglik",
  teeth: "saglik",
  wim: "saglik",
  hof: "saglik",
  noom: "saglik",
  kalori: "saglik",
  lose: "saglik",
  mrs: "saglik",
  reverb: "optik-akustik",
  smog: "cevre",
  yagi: "telekom",
  parabolic: "telekom",
  dish: "telekom",
  paper: "ambalaj-baski",
  page: "ambalaj-baski",
  transform: "istatistik",
  inverse: "istatistik",
  wells: "finans",
  social: "finans",
  security: "finans",
  survivor: "finans",
  benefits: "finans",
  gacha: "finans",
  experience: "finans",
  operating: "finans",
  oss: "finans",
  pathfinder: "egitim",
  grafik: "istatistik",
  yaprak: "istatistik",
  kok: "istatistik",
};

/** Expert-reviewed slug → sector overrides for edge cases (post frequency analysis). */
export const SECTOR_SLUG_OVERRIDES: Readonly<Record<string, string>> = {
  "dbscan-calculator": "istatistik",
  "decades-to-centuries-calculator": "birim-donusum",
  "dice-roller-calculator": "istatistik",
  "dijkstra-calculator": "matematik",
  "disk-method-calculator": "matematik",
  "divergence-calculator": "matematik",
  "dollar-cost-averaging-calculator": "finans",
  "dps-calculator": "finans",
  "drywall-calculator": "insaat",
  "duathlon-calculator": "fitness-spor",
  "ecog-performance-status-calculator": "saglik",
  "egitim-birikim-hesaplayici": "egitim",
  "electronegativity-calculator": "kimya",
  "equestrian-calculator": "fitness-spor",
  "espresso-calculator": "gida",
  "etf-calculator": "finans",
  "experience-calculator": "finans",
  "flange-calculator": "makine",
  "franchise-calculator": "finans",
  "gacha-calculator": "finans",
  "gambrel-roof-calculator": "insaat",
  "gcf-calculator": "matematik",
  "gradient-calculator": "matematik",
  "hess-yasasi-hesaplayici-calculator": "kimya",
  "hiking-calculator": "fitness-spor",
  "inverse-z-transform-calculator": "istatistik",
  "iqr-calculator": "istatistik",
  "jump-rope-calculator": "fitness-spor",
  "karnaugh-map-calculator": "elektronik",
  "kb-calculator": "birim-donusum",
  "kc-calculator": "kimya",
  "kendall-tau-calculator": "istatistik",
  "kok-yaprak-grafik-calculator": "istatistik",
  "kombucha-calculator": "gida",
  "lose-it-app-calculator": "saglik",
  "lu-decomposition-calculator": "matematik",
  "met-calculator": "fitness-spor",
  "middle-calculator": "matematik",
  "mindfulness-calculator": "saglik",
  "moon-phase-calculator": "ev-yasam",
  "mrs-calculator": "saglik",
  "ncr-calculator": "matematik",
  "noom-kalori-hesaplayici": "saglik",
  "nozzle-calculator": "makine",
  "npk-calculator": "tarim",
  "ntu-calculator": "su-yonetimi",
  "octal-calculator": "bilisim",
  "operating-leverage-calculator": "finans",
  "oss-vat-calculator": "finans",
  "page-count-calculator": "ambalaj-baski",
  "paleo-calculator": "gida",
  "paper-size-calculator": "ambalaj-baski",
  "parabolic-dish-calculator": "telekom",
  "partition-number-calculator": "matematik",
  "pathfinder-calculator": "egitim",
  "permanent-teeth-calculator": "saglik",
  "pip-calculator": "finans",
  "pizza-calculator": "gida",
  "plagiarism-calculator": "egitim",
  "polar-koordinat-donusturucu-calculator": "matematik",
  "pond-liner-calculator": "su-yonetimi",
  "predicate-logic-calculator": "matematik",
  "project-deadline-calculator": "ev-yasam",
  "quaternion-calculator": "matematik",
  "radical-calculator": "matematik",
  "recurrence-relation-calculator": "matematik",
  "reps-in-reserve-calculator": "fitness-spor",
  "reverb-calculator": "optik-akustik",
  "rigging-calculator": "makine",
  "roa-calculator": "finans",
  "roic-calculator": "finans",
  "roman-numeral-calculator": "matematik",
  "roofing-calculator": "insaat",
  "sep-ira-calculator": "finans",
  "set-theory-calculator": "matematik",
  "sinclair-calculator": "fitness-spor",
  "skateboard-impact-calculator": "fitness-spor",
  "smog-index-calculator": "cevre",
  "smoking-calculator": "saglik",
  "social-security-survivor-benefits-calculator": "finans",
  "sourdough-calculator": "gida",
  "stirling-number-calculator": "matematik",
  "stone-calculator": "birim-donusum",
  "stucco-calculator": "insaat",
  "sugar-stages-calculator": "gida",
  "tempo-calculator": "fitness-spor",
  "toll-calculator": "turizm",
  "tower-of-hanoi-calculator": "matematik",
  "transcript-calculator": "egitim",
  "tree-calculator": "bilisim",
  "true-cost-calculator": "finans",
  "wells-pe-calculator": "finans",
  "whitening-calculator": "saglik",
  "wim-hof-calculator": "saglik",
  "yagi-calculator": "telekom",
  "yogurt-calculator": "gida",
};


export const SECTORS: Sector[] = [
  {
    id: "otomotiv",
    label: "Automotive & Vehicles",
    labelEn: "Automotive & Vehicle",
    icon: "CarFront",
    professions: ["Production Engineer", "Quality Engineer", "Supply Chain Specialist", "R&D Engineer", "Maintenance Technician"],
    keywords: ["automotive", "vehicle", "car", "auto", "motor", "engine", "tire", "tyre", "brake", "transmission", "chassis", "ev", "battery", "hybrid", "truck", "bus", "trailer", "fleet", "oem", "aftermarket", "drivetrain", "suspension", "exhaust", "fuel", "mpg", "odometer", "vin"],
  },
  {
    id: "havacilik",
    label: "Aerospace",
    labelEn: "Aerospace & Space",
    icon: "Plane",
    professions: ["Design Engineer", "Maintenance Specialist", "Quality Engineer", "Systems Engineer", "R&D Specialist"],
    keywords: ["aerospace", "aircraft", "aviation", "airplane", "plane", "jet", "turbine", "wing", "fuselage", "aerodynamic", "lift", "drag", "altitude", "runway", "pilot", "flight", "rocket", "orbital", "satellite", "spacecraft", "propulsion", "nacelle"],
  },
  {
    id: "makine",
    label: "Machinery & Manufacturing",
    labelEn: "Machinery & Manufacturing",
    icon: "Cog",
    professions: ["CNC Operator", "Design Engineer", "Process Engineer", "Maintenance Specialist", "Draftsman"],
    keywords: ["machining", "cnc", "lathe", "mill", "milling", "drill", "grinder", "machine", "equipment", "tooling", "fixture", "spindle", "feed", "rpm", "tolerance", "manufacturing", "production", "assembly", "factory", "plant", "oee", "cycle", "takt", "lean"],
  },
  {
    id: "metal",
    label: "Metal & Kaynak",
    labelEn: "Metal & Welding",
    icon: "Anvil",
    professions: ["Sheet Metal Technician", "Welding Specialist", "Metallurgical Engineer", "Mold Specialist", "Surface Treatment Specialist"],
    keywords: ["metal", "steel", "aluminum", "aluminium", "sheet", "welding", "weld", "solder", "brazing", "casting", "forging", "stamping", "rolling", "extrusion", "alloy", "iron", "copper", "brass", "titanium", "hardness", "annealing", "tempering", "metallurgy"],
  },
  {
    id: "plastik",
    label: "Plastics & Polymers",
    labelEn: "Plastics & Polymers",
    icon: "Cylinder",
    professions: ["Process Engineer", "Mold Specialist", "Production Engineer", "Materials Specialist", "Quality Engineer"],
    keywords: ["plastic", "polymer", "injection", "molding", "mould", "mold", "extrusion", "blow", "thermoform", "resin", "polyethylene", "polypropylene", "pvc", "abs", "composite", "fibre", "fiber", "additive"],
  },
  {
    id: "gida",
    label: "Food & Nutrition",
    labelEn: "Food & Nutrition",
    icon: "Salad",
    professions: ["Food Engineer", "Production Engineer", "Quality Specialist", "R&D Specialist", "Dietitian"],
    keywords: ["food", "beverage", "nutrition", "recipe", "baking", "cooking", "diet", "meal", "calorie", "protein", "carb", "fat", "vitamin", "mineral", "dairy", "meat", "bakery", "brewery", "abv", "alcohol", "beer", "wine", "serving", "portion", "haccp", "shelf"],
  },
  {
    id: "kimya",
    label: "Chemical & Process",
    labelEn: "Chemistry & Process",
    icon: "FlaskConical",
    professions: ["Chemist", "Process Engineer", "R&D Specialist", "Quality Specialist", "Lab Technician"],
    keywords: ["chemical", "chemistry", "reaction", "synthesis", "catalyst", "molar", "mol", "stoichiometry", "titration", "ph", "acid", "base", "concentration", "solution", "solvent", "distillation", "chromatography", "pharma", "pharmaceutical", "drug", "compound", "molecule", "ion", "electrolyte"],
  },
  {
    id: "enerji",
    label: "Energy & Electrical",
    labelEn: "Energy & Electrical Power",
    icon: "Zap",
    professions: ["Energy Engineer", "Electrical Engineer", "Grid Specialist", "Energy Manager", "Maintenance Technician"],
    keywords: ["energy", "electric", "electricity", "power", "kwh", "kw", "voltage", "current", "ampere", "watt", "transformer", "generator", "motor", "grid", "substation", "powerfactor", "reactive", "demand", "tariff", "utility", "consumption", "loadfactor"],
  },
  {
    id: "insaat",
    label: "Construction & Building",
    labelEn: "Construction & Building",
    icon: "HardHat",
    professions: ["Civil Engineer", "Project Manager", "Site Chief", "Quality Specialist", "Architectural Technician"],
    keywords: ["construction", "building", "concrete", "cement", "rebar", "foundation", "excavation", "scaffold", "formwork", "masonry", "brick", "block", "mortar", "site", "contractor", "bid", "santiye", "structural", "footing", "slab", "column", "shoring"],
  },
  {
    id: "lojistik",
    label: "Logistics & Supply Chain",
    labelEn: "Logistics & Supply Chain",
    icon: "Warehouse",
    professions: ["Logistics Specialist", "Warehouse Manager", "Supply Chain Manager", "Planning Specialist", "Import/Export Specialist"],
    keywords: ["logistics", "warehouse", "inventory", "stock", "supply", "procurement", "sourcing", "eoq", "reorder", "leadtime", "backorder", "fulfillment", "picking", "packing", "pallet", "sku", "demand", "forecast", "safety", "stockout"],
  },
  {
    id: "perakende",
    label: "Perakende & Ticaret",
    labelEn: "Retail & Commerce",
    icon: "Store",
    professions: ["Sales Manager", "Category Manager", "Store Manager", "Finance Specialist", "Customer Experience Specialist"],
    keywords: ["retail", "store", "shop", "margin", "markup", "pricing", "discount", "promotion", "basket", "checkout", "pos", "merchandise", "sku", "sales", "revenue", "turnover", "shrinkage", "footfall", "conversion", "customer"],
  },
  {
    id: "tekstil",
    label: "Textile & Apparel",
    labelEn: "Textile & Apparel",
    icon: "Shirt",
    professions: ["Textile Engineer", "Production Engineer", "Quality Specialist", "Fashion Designer", "Apparel Specialist"],
    keywords: ["textile", "fabric", "cloth", "apparel", "garment", "sewing", "knitting", "weaving", "dye", "yarn", "thread", "fiber", "denim", "cotton", "wool", "pattern", "stitch"],
  },
  {
    id: "bilisim",
    label: "IT & Software",
    labelEn: "IT & Software",
    icon: "Monitor",
    professions: ["Software Developer", "Systems Engineer", "Data Specialist", "Cloud Specialist", "Cybersecurity Specialist"],
    keywords: ["software", "code", "programming", "algorithm", "database", "cloud", "server", "api", "data", "binary", "hex", "encryption", "hash", "bandwidth", "latency", "storage", "memory", "cpu", "gpu", "devops", "saas"],
  },
  {
    id: "finans",
    label: "Finans & Muhasebe",
    labelEn: "Finance & Accounting",
    icon: "Landmark",
    professions: ["Finance Manager", "Accountant", "Risk Specialist", "Investment Specialist", "Actuary"],
    keywords: ["finance", "financial", "loan", "credit", "interest", "mortgage", "investment", "roi", "npv", "irr", "payback", "depreciation", "amortization", "tax", "salary", "payroll", "dividend", "bond", "stock", "portfolio", "budget", "cashflow", "working", "capital", "profit", "revenue", "expense", "accounting", "ledger"],
  },
  {
    id: "saglik",
    label: "Healthcare & Medical",
    labelEn: "Health & Medicine",
    icon: "Stethoscope",
    professions: ["Biomedical Engineer", "Nurse", "Lab Technician", "Clinical Specialist", "Medical Device Specialist"],
    keywords: ["health", "medical", "clinical", "patient", "hospital", "diagnosis", "treatment", "therapy", "dose", "dosage", "medication", "drug", "bmi", "body", "weight", "obesity", "heart", "cardiac", "blood", "glucose", "diabetes", "cholesterol", "pregnancy", "pediatric", "renal", "kidney", "liver", "cancer", "tumor", "frailty", "tinnitus", "thyroid", "hormone", "insulin", "metabolic", "calorie", "sleep", "breathing", "baby", "infant", "vital", "symptom"],
  },
  {
    id: "tarim",
    label: "Agriculture & Livestock",
    labelEn: "Agriculture & Livestock",
    icon: "Wheat",
    professions: ["Agricultural Engineer", "Food Specialist", "Agriculture Technician", "Irrigation Specialist", "Plant Protection Specialist"],
    keywords: ["agriculture", "farming", "crop", "harvest", "irrigation", "fertilizer", "soil", "plant", "seed", "yield", "field", "tractor", "pesticide", "herbicide", "greenhouse", "livestock", "cattle", "dairy", "milk", "feed", "grain", "wheat", "corn", "rice", "veterinary", "veterinarian", "animal", "poultry", "swine", "equine", "pet", "herd", "flock", "breeding", "vaccination"],
  },
  {
    id: "denizcilik",
    label: "Maritime & Shipping",
    labelEn: "Maritime & Shipbuilding",
    icon: "Ship",
    professions: ["Marine Engineer", "Maritime Transport Specialist", "Shipyard Technician", "Logistics Specialist", "Maritime Safety Specialist"],
    keywords: ["maritime", "marine", "ship", "vessel", "boat", "naval", "port", "harbor", "harbour", "cargo", "container", "draft", "displacement", "buoyancy", "anchor", "hull", "propeller", "nautical", "seafaring"],
  },
  {
    id: "madencilik",
    label: "Madencilik & Jeoloji",
    labelEn: "Mining & Geology",
    icon: "Pickaxe",
    professions: ["Mining Engineer", "Geologist", "Field Specialist", "Environmental Specialist", "Occupational Health Specialist"],
    keywords: ["mining", "mine", "ore", "mineral", "coal", "gold", "silver", "copper", "drill", "excavation", "geology", "geological", "seismic", "reservoir", "sediment", "rock", "stratum", "blast", "quarry"],
  },
  {
    id: "telekom",
    label: "Telekomunikasyon",
    labelEn: "Telecommunications",
    icon: "Antenna",
    professions: ["Ag Muhendisi", "RF Uzmani", "Systems Engineer", "Saha Teknisyeni", "Data Specialist"],
    keywords: ["telecom", "telecommunication", "network", "radio", "frequency", "rf", "fiber", "cable", "5g", "4g", "lte", "wireless", "router", "antenna", "signal", "bandwidth", "latency", "throughput", "modem", "voip"],
  },
  {
    id: "yenilenebilir",
    label: "Yenilenebilir Enerji",
    labelEn: "Renewable Energy",
    icon: "SunMedium",
    professions: ["Energy Engineer", "Gunes Enerjisi Uzmani", "Ruzgar Enerjisi Uzmani", "Surdurulebilirlik Uzmani", "Energy Manager"],
    keywords: ["solar", "photovoltaic", "pv", "wind", "renewable", "green", "sustainable", "turbine", "biomass", "geothermal", "hydroelectric", "battery", "inverter", "panel", "array", "carbon", "netzero", "feedin"],
  },
  {
    id: "temizlik",
    label: "Tesis & Hijyen",
    labelEn: "Facilities & Hygiene",
    icon: "Sparkles",
    professions: ["Hijyen Uzmani", "Tesis Yoneticisi", "Quality Specialist", "Saha Sorumlusu", "Temizlik Operatoru"],
    keywords: ["cleaning", "hygiene", "sanitize", "sanitation", "janitor", "facility", "disinfect", "detergent", "custodial", "maintenance"],
  },
  {
    id: "kargo",
    label: "Kargo & Nakliye",
    labelEn: "Freight & Haulage",
    icon: "Truck",
    professions: ["Logistics Specialist", "Filo Yoneticisi", "Rota Planlayicisi", "Guvenlik Uzmani", "Operasyon Muduru"],
    keywords: ["freight", "cargo", "haulage", "courier", "delivery", "dispatch", "trucking", "carrier", "waybill", "consignment", "tonnage", "payload", "deadhead"],
  },
  {
    id: "matematik",
    label: "Matematik & Geometri",
    labelEn: "Mathematics & Geometry",
    icon: "Sigma",
    professions: ["Matematikci", "Muhendis", "Arastirmaci", "Ogretmen", "Veri Analisti"],
    keywords: ["math", "mathematics", "algebra", "geometry", "trigonometry", "calculus", "equation", "formula", "fraction", "decimal", "matrix", "vector", "integral", "derivative", "polynomial", "logarithm", "exponential", "prime", "factorial", "theorem", "pythagorean", "quadratic", "linear", "solver", "root", "modulo", "gcd", "lcm", "series", "sequence", "fibonacci", "permutation", "combination", "factor", "divisor", "multiple", "ratio", "proportion", "area", "volume", "surface", "angle", "triangle", "circle", "square", "rectangle", "polygon", "coordinate", "graph", "slope", "intercept", "absolute", "complex", "imaginary", "binary", "hexadecimal", "scientific", "notation"],
  },
  {
    id: "istatistik",
    label: "Istatistik & Olasilik",
    labelEn: "Statistics & Probability",
    icon: "ChartColumn",
    professions: ["Istatistikci", "Veri Bilimci", "Quality Engineer", "Arastirmaci", "Actuary"],
    keywords: ["statistics", "statistical", "probability", "percentile", "sample", "population", "mean", "median", "mode", "variance", "deviation", "standard", "confidence", "interval", "regression", "correlation", "anova", "hypothesis", "chi", "zscore", "ttest", "distribution", "normal", "binomial", "poisson", "bayes", "likelihood", "odds", "predictor", "forecast", "trend", "rank", "quartile", "outlier"],
  },
  {
    id: "fizik",
    label: "Fizik & Mekanik",
    labelEn: "Physics & Mechanics",
    icon: "Magnet",
    professions: ["Fizik Muhendisi", "Mekanik Muhendisi", "R&D Specialist", "Test Engineer", "Akademisyen"],
    keywords: ["physics", "mechanics", "force", "momentum", "velocity", "acceleration", "kinematics", "dynamics", "gravity", "friction", "torque", "stress", "strain", "elasticity", "modulus", "beam", "bending", "shear", "torsion", "pressure", "density", "buoyancy", "fluid", "flow", "reynolds", "bernoulli", "thermodynamic", "entropy", "enthalpy", "heat", "thermal", "conduction", "convection", "radiation", "optics", "wavelength", "frequency", "wave", "resonance", "magnetic", "electric", "capacitance", "inductance", "joule", "newton", "pascal", "hertz"],
  },
  {
    id: "birim-donusum",
    label: "Birim & Donusum",
    labelEn: "Units & Conversion",
    icon: "ArrowLeftRight",
    professions: ["Muhendis", "Teknisyen", "Lab Technician", "Quality Specialist", "Operator"],
    keywords: ["converter", "conversion", "convert", "unit", "metric", "imperial", "meters", "metres", "feet", "foot", "inches", "inch", "yards", "yard", "miles", "mile", "kilometer", "kilometre", "centimeter", "millimeter", "micrometer", "nanometer", "liters", "litres", "gallons", "gallon", "quarts", "pints", "cups", "fluid", "ounces", "pounds", "kilograms", "grams", "tons", "tonnes", "celsius", "fahrenheit", "kelvin", "rankine", "acres", "hectares", "hectare", "sqm", "square", "cubic", "psi", "bar", "atm", "pascal", "mph", "kmh", "knot", "degrees", "radians", "arcminute", "arcsecond", "horsepower", "btu", "joule", "calorie", "watt", "ampere", "volt"],
  },
  {
    id: "fitness-spor",
    label: "Fitness & Spor",
    labelEn: "Fitness & Sports",
    icon: "Dumbbell",
    professions: ["Antrenor", "Spor Bilimci", "Fizyoterapist", "Dietitian", "Performans Analisti"],
    keywords: ["fitness", "sport", "sports", "exercise", "workout", "training", "running", "marathon", "5k", "10k", "cycling", "swimming", "pace", "vo2", "cardio", "aerobic", "anaerobic", "muscle", "strength", "hypertrophy", "1rm", "rep", "bench", "squat", "deadlift", "athletic", "endurance", "overtraining", "recovery", "stretch", "flexibility", "agility", "sprint", "triathlon"],
  },
  {
    id: "ev-yasam",
    label: "Gunluk Yasam & Ev",
    labelEn: "Everyday Life & Home",
    icon: "Home",
    professions: ["Ev Yoneticisi", "Ic Mimar", "Tesisatci", "Bahcivan", "Tuketici Danismani"],
    keywords: ["everyday", "daily", "home", "household", "life", "age", "date", "calendar", "birthday", "anniversary", "time", "duration", "day", "week", "month", "year", "clock", "timer", "schedule", "reminder", "pregnancy", "due", "gestation", "renovation", "remodel", "paint", "tile", "flooring", "garden", "lawn", "landscaping", "fuel", "commute", "parking", "tip", "gratuity", "split", "bill"],
  },
  {
    id: "egitim",
    label: "Egitim & Akademik",
    labelEn: "Education & Academic",
    icon: "GraduationCap",
    professions: ["Ogretmen", "Akademisyen", "Rehber Ogretmen", "Egitim Koordinatoru", "Arastirmaci"],
    keywords: ["education", "academic", "school", "student", "grade", "gpa", "exam", "test", "score", "act", "sat", "iq", "college", "university", "degree", "credit", "semester", "tuition", "scholarship", "classroom", "curriculum", "learning", "study"],
  },
  {
    id: "emlak",
    label: "Emlak & Gayrimenkul",
    labelEn: "Real Estate & Property",
    icon: "KeyRound",
    professions: ["Emlak Danismani", "Degerleme Uzmani", "Yatirim Danismani", "Proje Gelistirici", "Portfoy Yoneticisi"],
    keywords: ["real", "estate", "property", "mortgage", "rent", "rental", "lease", "landlord", "tenant", "housing", "appraisal", "valuation", "downpayment", "closing", "hoa", "caprate", "cashflow", "flip", "refinance"],
  },
  {
    id: "turizm",
    label: "Turizm & Konaklama",
    labelEn: "Tourism & Hospitality",
    icon: "Luggage",
    professions: ["Otel Muduru", "Rezervasyon Uzmani", "Seyahat Danismani", "Etkinlik Planlayicisi", "Restoran Muduru"],
    keywords: ["tourism", "travel", "hotel", "hospitality", "resort", "booking", "reservation", "flight", "itinerary", "vacation", "tourist", "occupancy", "revpar", "adr", "catering", "banquet", "restaurant", "menu", "foodcost"],
  },
  {
    id: "cevre",
    label: "Cevre & Surdurulebilirlik",
    labelEn: "Environment & Sustainability",
    icon: "Leaf",
    professions: ["Cevre Muhendisi", "Surdurulebilirlik Uzmani", "EHS Uzmani", "Atik Yoneticisi", "Karbon Denetcisi"],
    keywords: ["environment", "environmental", "sustainability", "sustainable", "carbon", "emission", "co2", "greenhouse", "footprint", "recycle", "recycling", "waste", "landfill", "compost", "pollution", "airquality", "waterquality", "biodiversity", "ecology", "lifecycle", "circular"],
  },
  {
    id: "elektronik",
    label: "Elektronik & Devre",
    labelEn: "Electronics & Circuits",
    icon: "CircuitBoard",
    professions: ["Elektronik Muhendisi", "PCB Tasarimcisi", "Test Engineer", "Maintenance Technician", "R&D Specialist"],
    keywords: ["electronic", "electronics", "circuit", "resistor", "capacitor", "inductor", "transistor", "diode", "led", "pcb", "voltage", "current", "ohm", "impedance", "adc", "dac", "amplifier", "filter", "microcontroller", "sensor", "semiconductor", "ic", "opamp"],
  },
  {
    id: "ambalaj-baski",
    label: "Ambalaj & Printing",
    labelEn: "Packaging & Printing",
    icon: "Printer",
    professions: ["Ambalaj Muhendisi", "Baski Operatoru", "Grafik Tasarimcisi", "Quality Specialist", "Uretim Planlayicisi"],
    keywords: ["packaging", "package", "label", "printing", "print", "box", "carton", "pallet", "shrink", "laminate", "flexo", "offset", "diecut", "corrugated", "barcode"],
  },
  {
    id: "mobilya-ahsap",
    label: "Mobilya & Ahsap",
    labelEn: "Furniture & Woodworking",
    icon: "Armchair",
    professions: ["Marangoz", "Mobilya Tasarimcisi", "Uretim Ustasi", "CNC Operator", "Kalite Kontroloru"],
    keywords: ["furniture", "wood", "woodworking", "lumber", "timber", "carpentry", "cabinet", "joinery", "veneer", "plywood", "hardwood", "softwood", "sawmill", "millwork"],
  },
  {
    id: "petrokimya",
    label: "Petrokimya & Rafineri",
    labelEn: "Petrochemical & Refining",
    icon: "Fuel",
    professions: ["Process Engineer", "Rafineri Operatoru", "R&D Specialist", "Guvenlik Muhendisi", "Quality Specialist"],
    keywords: ["petroleum", "petrochemical", "refinery", "oil", "gas", "crude", "distillation", "pipeline", "lng", "hydrocarbon", "octane", "diesel", "gasoline", "lubricant", "asphalt"],
  },
  {
    id: "hidrolik-pnomatik",
    label: "Hidrolik & Pnomatik",
    labelEn: "Hydraulics & Pneumatics",
    icon: "Gauge",
    professions: ["Hidrolik Muhendisi", "Maintenance Technician", "Proje Muhendisi", "Sistem Entegratoru", "Satis Muhendisi"],
    keywords: ["hydraulic", "hydraulics", "pneumatic", "pneumatics", "cylinder", "pump", "valve", "actuator", "compressor", "pipe", "piping", "fitting", "hose", "manifold", "flowrate"],
  },
  {
    id: "yapisal-muhendislik",
    label: "Yapisal Engineerlik",
    labelEn: "Structural Engineering",
    icon: "Columns3",
    professions: ["Yapisal Muhendis", "Statik Muhendis", "Proje Muhendisi", "Santiye Muhendisi", "Denetim Muhendisi"],
    keywords: ["structural", "static", "load", "deadload", "liveload", "deflection", "buckling", "moment", "shear", "reinforcement", "truss", "frame", "cantilever", "eurocode", "aisc", "concrete", "steel", "timber"],
  },
  {
    id: "su-yonetimi",
    label: "Su & Atiksu",
    labelEn: "Water & Wastewater",
    icon: "Droplets",
    professions: ["Su Muhendisi", "Cevre Muhendisi", "Tesis Operatoru", "Hidrolog", "Process Engineer"],
    keywords: ["water", "wastewater", "sewage", "treatment", "filtration", "chlorination", "desalination", "aquifer", "hydrology", "rainfall", "runoff", "drainage", "pump", "reservoir", "pool", "swimming", "aquarium", "irrigation"],
  },
  {
    id: "optik-akustik",
    label: "Optik & Akustik",
    labelEn: "Optics & Acoustics",
    icon: "AudioLines",
    professions: ["Akustik Muhendisi", "Optik Muhendisi", "R&D Specialist", "Test Engineer", "Design Engineer"],
    keywords: ["acoustic", "acoustics", "sound", "noise", "decibel", "reverberation", "absorption", "optics", "optical", "lens", "mirror", "refraction", "diffraction", "magnification", "luminance", "illuminance", "photometry"],
  },
  {
    id: "gorsel-medya",
    label: "Gorsel & Medya",
    labelEn: "Visual & Media",
    icon: "Camera",
    professions: ["Grafik Tasarimci", "Fotografci", "Video Editoru", "UI Tasarimcisi", "Medya Planlayicisi"],
    keywords: ["image", "video", "pixel", "resolution", "dpi", "aspect", "ratio", "color", "colour", "rgb", "cmyk", "hex", "font", "typography", "media", "display", "screen", "bitrate", "compression"],
  },
  {
    id: "demiryolu",
    label: "Demiryolu & Rayli",
    labelEn: "Rail & Transit",
    icon: "TrainFront",
    professions: ["Demiryolu Muhendisi", "Sinyalizasyon Uzmani", "Maintenance Technician", "Operasyon Muduru", "Proje Muhendisi"],
    keywords: ["rail", "railway", "railroad", "train", "locomotive", "wagon", "track", "gauge", "metro", "subway", "tram", "transit", "signaling", "siding"],
  },
  {
    id: "cam-seramik",
    label: "Cam & Seramik",
    labelEn: "Glass & Ceramics",
    icon: "Circle",
    professions: ["Ceramic Engineer", "Glass Master", "Quality Specialist", "Furnace Operator", "Designer"],
    keywords: ["glass", "ceramic", "ceramics", "porcelain", "tile", "glaze", "kiln", "firing", "refractory", "silica", "enamel"],
  },
  {
    id: "savunma",
    label: "Savunma & Askeri",
    labelEn: "Defense & Military",
    icon: "Shield",
    professions: ["Defense Engineer", "Systems Engineer", "Project Manager", "Test Engineer", "Logistics Specialist"],
    keywords: ["defense", "defence", "military", "army", "navy", "airforce", "weapon", "munition", "radar", "sonar", "surveillance", "cyber", "soldier", "tank", "missile", "drone", "uav", "helicopter", "warship", "submarine", "armored", "ballistic", "camouflage"],
  },
  {
    id: "veteriner",
    label: "Veterinary & Animal Health",
    labelEn: "Veterinary & Animal Health",
    icon: "PawPrint",
    professions: ["Veterinarian", "Animal Health Specialist", "Lab Technician", "Farm Consultant", "Food Safety Specialist"],
    keywords: ["veterinary", "veterinarian", "vet", "animal", "pet", "dog", "cat", "livestock", "cattle", "horse", "equine", "vaccination", "deworming", "surgery", "clinic", "farm", "dairy", "poultry", "swine", "zoonosis", "rabies", "parasite", "nutrition", "feed", "diagnosis"],
  },
];

/** Catch-all sector for tools that do not map to a primary taxonomy sector. */
export const OTHER_SECTOR: Sector = {
  id: "diger",
  label: "Other",
  labelEn: "Other",
  icon: "FolderOpen",
  professions: [],
  keywords: [],
};

/** First taxonomy grid tile - shows every tool in the catalog. */
export const ALL_TOOLS_SECTOR: Sector = {
  id: "all",
  label: "Tumu",
  labelEn: "All",
  icon: "LayoutGrid",
  professions: [],
  keywords: [],
};

// ============================================================
// 2. KATEGORILER (Calculation Turu)
// ============================================================

/** Default calculation-type category when a sector is known but keyword score is zero. */
export const SECTOR_TO_CATEGORY: Readonly<Record<string, string>> = {
  otomotiv: "engineering",
  havacilik: "engineering",
  makine: "engineering",
  metal: "engineering",
  plastik: "engineering",
  kimya: "engineering",
  elektronik: "engineering",
  "hidrolik-pnomatik": "engineering",
  "yapisal-muhendislik": "engineering",
  denizcilik: "engineering",
  petrokimya: "engineering",
  madencilik: "engineering",
  "cam-seramik": "engineering",
  "optik-akustik": "engineering",
  telekom: "engineering",
  insaat: "engineering",
  fizik: "engineering",
  enerji: "energy",
  yenilenebilir: "energy",
  cevre: "sustainability",
  "su-yonetimi": "sustainability",
  tarim: "sustainability",
  veteriner: "safety",
  finans: "finance",
  emlak: "finance",
  perakende: "cost",
  tekstil: "cost",
  "ambalaj-baski": "cost",
  "mobilya-ahsap": "cost",
  temizlik: "cost",
  gida: "conversion",
  lojistik: "logistics",
  kargo: "logistics",
  turizm: "logistics",
  demiryolu: "logistics",
  saglik: "safety",
  savunma: "engineering",
  "fitness-spor": "safety",
  "isg-risk": "safety",
  matematik: "math",
  istatistik: "math",
  bilisim: "math",
  egitim: "math",
  "birim-donusum": "conversion",
  "ev-yasam": "conversion",
  "gorsel-medya": "conversion",
  diger: "math",
};

export const CATEGORIES: Category[] = [
  {
    id: "cost",
    label: "Maliyet & Butceleme",
    labelEn: "Cost & Budgeting",
    keywords: [
      "cost",
      "budget",
      "price",
      "expense",
      "profit",
      "margin",
      "markup",
      "breakeven",
      "bom",
      "quote",
      "estimate",
      "bid",
      "retail",
      "wholesale",
      "packaging",
      "printing",
      "furniture",
      "cleaning",
      "textile",
      "clv",
      "churn",
      "commission",
      "cashback",
      "amazon",
      "fba",
      "attribution",
      "cpa",
    ],
  },
  {
    id: "efficiency",
    label: "Verimlilik & OEE",
    labelEn: "Efficiency & OEE",
    keywords: [
      "oee",
      "smed",
      "5s",
      "productivity",
      "efficiency",
      "utilization",
      "downtime",
      "cycletime",
      "takt",
      "throughput",
      "uptime",
      "lean",
      "kaizen",
      "kanban",
      "changeover",
      "capacity",
    ],
  },
  {
    id: "quality",
    label: "Kalite & Surec Kontrol",
    labelEn: "Quality & Process Control",
    keywords: [
      "quality",
      "spc",
      "sixsigma",
      "cpk",
      "cp",
      "ppm",
      "control",
      "gauge",
      "gauge rr",
      "measurement",
      "audit",
      "defect",
      "yield",
      "fmea",
      "aql",
      "sigma",
      "abc analysis",
      "abc-analysis",
    ],
  },
  {
    id: "energy",
    label: "Enerji & Karbon",
    labelEn: "Energy & Carbon",
    keywords: [
      "energy",
      "power",
      "kwh",
      "carbon",
      "emission",
      "fuel",
      "electricity",
      "gas",
      "heat",
      "solar",
      "wind",
      "co2",
      "compressor",
      "turbine",
      "battery",
      "ev",
      "photovoltaic",
    ],
  },
  {
    id: "logistics",
    label: "Lojistik & Rota",
    labelEn: "Logistics & Route",
    keywords: [
      "logistics",
      "warehouse",
      "route",
      "delivery",
      "transport",
      "inventory",
      "eoq",
      "shipment",
      "cargo",
      "routing",
      "freight",
      "shipping",
      "customs",
      "toll",
      "travel",
      "hotel",
      "rail",
      "train",
      "abc",
    ],
  },
  {
    id: "finance",
    label: "Finans & Yatirim",
    labelEn: "Finance & Investment",
    keywords: [
      "npv",
      "irr",
      "payback",
      "investment",
      "loan",
      "credit",
      "tax",
      "depreciation",
      "amortization",
      "roi",
      "dividend",
      "mortgage",
      "interest",
      "stock",
      "bond",
      "crypto",
      "bitcoin",
      "forex",
      "option",
      "equity",
      "valuation",
      "fee",
      "ach",
      "accrual",
      "cash",
      "poker",
      "gambling",
      "lottery",
      "startup",
      "runway",
      "etf",
      "ira",
      "pip",
      "roa",
      "roic",
      "leverage",
      "wells",
      "social security",
      "benefits",
      "gacha",
      "experience",
      "operating",
      "vat",
      "dps",
      "coin",
      "consolidation",
      "burn",
      "balloon",
      "kredi",
      "card",
      "baccarat",
      "blackjack",
      "roulette",
      "slot",
    ],
  },
  {
    id: "hr",
    label: "HR & Personnel",
    labelEn: "HR & Personnel",
    keywords: [
      "employee",
      "salary",
      "payroll",
      "overtime",
      "benefit",
      "labor",
      "labour",
      "workforce",
      "turnover",
      "competence",
      "absenteeism",
      "shift",
      "headcount",
      "hiring",
      "wage",
    ],
  },
  {
    id: "engineering",
    label: "Teknik & Engineerlik",
    labelEn: "Technical & Engineering",
    keywords: [
      "torque",
      "stress",
      "strain",
      "flow",
      "heat",
      "thermo",
      "hydraulic",
      "pneumatic",
      "mechanical",
      "electrical",
      "structural",
      "beam",
      "bolt",
      "weld",
      "bearing",
      "gear",
      "motor",
      "circuit",
      "voltage",
      "acceleration",
      "velocity",
      "force",
      "pressure",
      "pipe",
      "pump",
      "adc",
      "resistor",
      "capacitor",
      "aircraft",
      "ship",
      "vessel",
      "engine",
      "brake",
      "tire",
      "vehicle",
      "automotive",
      "concrete",
      "rebar",
      "roof",
      "flange",
      "nozzle",
      "rigging",
      "absorption",
      "reverb",
      "acoustic",
      "optics",
      "yagi",
      "parabolic",
      "network",
      "fiber",
      "router",
      "petroleum",
      "refinery",
      "mining",
      "ore",
      "ceramic",
      "glass",
      "injection",
      "mold",
      "plastic",
      "metal",
      "cnc",
      "lathe",
      "milling",
      "drilling",
    ],
  },
  {
    id: "safety",
    label: "OHS & Risk",
    labelEn: "Safety & Risk",
    keywords: [
      "risk",
      "safety",
      "hazard",
      "ergonomics",
      "noise",
      "ppe",
      "accident",
      "security",
      "compliance",
      "exposure",
      "health",
      "bmi",
      "bmr",
      "calorie",
      "body",
      "heart",
      "blood",
      "sleep",
      "pregnancy",
      "baby",
      "fasting",
      "breathing",
      "metabolic",
      "fitness",
      "workout",
      "diet",
      "wellness",
      "exercise",
      "running",
      "hiking",
      "swimming",
      "cycling",
      "marathon",
      "pace",
      "training",
      "muscle",
      "vo2",
      "1rm",
      "mindfulness",
      "smoking",
      "teeth",
      "whitening",
      "ecog",
      "noom",
      "wim",
      "hof",
      "ovulation",
      "cholesterol",
    ],
  },
  {
    id: "sustainability",
    label: "Surdurulebilirlik",
    labelEn: "Sustainability",
    keywords: [
      "sustainability",
      "recycle",
      "waste",
      "water",
      "green",
      "circular",
      "reuse",
      "emission",
      "footprint",
      "crop",
      "farm",
      "harvest",
      "fertilizer",
      "irrigation",
      "livestock",
      "cattle",
      "veterinary",
      "npk",
      "pond",
      "wastewater",
      "smog",
      "ecology",
      "ntu",
    ],
  },
  {
    id: "conversion",
    label: "Donusum & Measurement",
    labelEn: "Conversion & Measurement",
    keywords: [
      "conversion",
      "convert",
      "measure",
      "unit",
      "scale",
      "metric",
      "imperial",
      "size",
      "weight",
      "volume",
      "speed",
      "temperature",
      "converter",
      "area",
      "length",
      "height",
      "recipe",
      "food",
      "baking",
      "abv",
      "beer",
      "wine",
      "coffee",
      "pizza",
      "yogurt",
      "sourdough",
      "kombucha",
      "espresso",
      "paleo",
      "age",
      "date",
      "calendar",
      "birthday",
      "deadline",
      "moon",
      "stone",
      "decades",
      "centuries",
      "kb",
      "octal",
      "ascii",
      "base64",
      "pixel",
      "color",
      "image",
      "paper",
      "page",
      "barcode",
      "qrcode",
    ],
  },
  {
    id: "math",
    label: "Matematik & Analiz",
    labelEn: "Mathematics & Analysis",
    keywords: [
      "math",
      "algebra",
      "geometry",
      "equation",
      "matrix",
      "statistics",
      "probability",
      "calculus",
      "formula",
      "solver",
      "vector",
      "fraction",
      "decimal",
      "percent",
      "percentage",
      "angle",
      "logarithm",
      "polynomial",
      "integral",
      "derivative",
      "absolute",
      "magnitude",
      "coordinate",
      "radical",
      "quaternion",
      "regression",
      "anova",
      "percentile",
      "correlation",
      "sample",
      "confidence",
      "hypothesis",
      "gcd",
      "gcf",
      "lcm",
      "prime",
      "factorial",
      "combinatorics",
      "graph",
      "topology",
      "dijkstra",
      "gradient",
      "divergence",
      "partition",
      "predicate",
      "logic",
      "roman",
      "stirling",
      "ncr",
      "hanoi",
      "iqr",
      "kendall",
      "dbscan",
      "clustering",
      "coefficient",
      "curve",
      "function",
      "conic",
      "disk",
      "dice",
      "transform",
      "inverse",
      "middle",
      "decomposition",
      "set theory",
      "pathfinder",
      "rating",
      "grade",
      "college",
      "transcript",
      "plagiarism",
      "chess",
      "tree",
      "software",
      "cloud",
      "database",
      "regex",
      "json",
      "encryption",
      "password",
      "hash",
      "unicode",
      "checksum",
      "a-b-test",
      "auc",
      "roc",
    ],
  },
];

/** Slug token → calculation category (derived from sector hints + direct overrides). */
export const SLUG_TOKEN_CATEGORY_HINTS: Readonly<Record<string, string>> = {
  ...Object.fromEntries(
    Object.entries(SLUG_TOKEN_SECTOR_HINTS).map(([token, sectorId]) => [
      token,
      SECTOR_TO_CATEGORY[sectorId] ?? "math",
    ]),
  ),
  ratio: "finance",
  fee: "finance",
};

// ============================================================
// 3. YARDIMCI FONKSIYONLAR
// ============================================================

export function getSectorById(id: string): Sector | undefined {
  return SECTORS.find((s) => s.id === id);
}

export function getSectorByKeyword(keyword: string): Sector | undefined {
  const lower = keyword.toLowerCase();
  return SECTORS.find((s) => s.keywords.some((k) => lower.includes(k)));
}

export function getCategoryById(id: string): Category | undefined {
  return CATEGORIES.find((c) => c.id === id);
}

export function getCategoryByKeyword(keyword: string): Category | undefined {
  const lower = keyword.toLowerCase();
  return CATEGORIES.find((c) => c.keywords.some((k) => lower.includes(k)));
}

export function getAllSectorLabels(): string[] {
  return SECTORS.map((s) => s.label);
}

export function getAllCategoryLabels(): string[] {
  return CATEGORIES.map((c) => c.label);
}

export function assertUniqueSectorIcons(): void {
  const seen = new Map<string, string>();
  const allSectors = [...SECTORS, OTHER_SECTOR, ALL_TOOLS_SECTOR];
  for (const sector of allSectors) {
    const previous = seen.get(sector.icon);
    if (previous) {
      throw new Error(`Duplicate sector icon key ${sector.icon} on ${sector.id} and ${previous}`);
    }
    seen.set(sector.icon, sector.id);
  }
  if (SECTORS.length < 30) {
    throw new Error(`Expected at least 30 sectors, found ${SECTORS.length}`);
  }
}
