import * as fs from "node:fs";
import * as path from "node:path";
import { PROJECT_ROOT } from "./load-env";
import {
  generatedCalculateExport,
  generatedInputSchemaExport,
} from "@/lib/generated-tools/export-names";

const GENERATED_DIR = path.join(PROJECT_ROOT, "generated");
const OUTPUT_FILE = path.join(
  PROJECT_ROOT,
  "src",
  "lib",
  "generated-tools",
  "calculator-registry.ts",
);

function main(): void {
  const toolFiles = fs
    .readdirSync(GENERATED_DIR)
    .filter((name) => name.endsWith(".ts") && name !== "index.ts")
    .map((name) => name.replace(/\.ts$/, ""))
    .sort((left, right) => left.localeCompare(right));

  const loaderEntries = toolFiles
    .map((slug) => `  ${JSON.stringify(slug)}: createLoader(${JSON.stringify(slug)}),`)
    .join("\n");

  const output = `// Auto-generated by scripts/deepseek/generate-calculator-registry.ts — do not edit manually.
import type { GeneratedCalculatorModule } from "@/lib/generated-tools/types";
import {
  generatedCalculateExport,
  generatedInputSchemaExport,
} from "@/lib/generated-tools/export-names";

type CalculatorLoader = () => Promise<GeneratedCalculatorModule>;

type RawGeneratedModule = Record<string, unknown>;

function wrapGeneratedModule(mod: RawGeneratedModule, slug: string): GeneratedCalculatorModule {
  const inputSchemaKey = generatedInputSchemaExport(slug);
  const calculateKey = generatedCalculateExport(slug);
  const inputSchema = mod[inputSchemaKey];
  const calculate = mod[calculateKey];
  if (!inputSchema || typeof calculate !== "function") {
    throw new Error(\`Generated module for "\${slug}" is missing exports (\${inputSchemaKey}, \${calculateKey}).\`);
  }
  return {
    inputSchema: inputSchema as GeneratedCalculatorModule["inputSchema"],
    calculate: calculate as GeneratedCalculatorModule["calculate"],
  };
}

function createLoader(slug: string): CalculatorLoader {
  return async () => {
    const mod = (await import(
      /* webpackInclude: /\\.ts$/ */
      \`@generated/\${slug}\`
    )) as RawGeneratedModule;
    return wrapGeneratedModule(mod, slug);
  };
}

const CALCULATOR_LOADERS: Readonly<Record<string, CalculatorLoader>> = {
${loaderEntries}
};

export const GENERATED_CALCULATOR_SLUGS = Object.freeze(
  Object.keys(CALCULATOR_LOADERS).sort((left, right) => left.localeCompare(right)),
) as readonly string[];

export async function loadGeneratedCalculator(
  slug: string,
): Promise<GeneratedCalculatorModule | null> {
  const loader = CALCULATOR_LOADERS[slug];
  if (!loader) {
    return null;
  }
  return loader();
}
`;

  fs.writeFileSync(OUTPUT_FILE, output);
  console.log(`Generated ${OUTPUT_FILE} (${toolFiles.length} tools)`);
}

main();
