import fs from "node:fs";
import path from "node:path";
import type {
  DeepSeekScannedFormulaEntry,
  ToolScanRecord,
  ToolsSchemaDocument,
} from "./types";
import { PROJECT_ROOT } from "./load-env";

const GENERATED_DIR = path.join(PROJECT_ROOT, "generated");

export function writeScanOutputs(records: readonly ToolScanRecord[]): {
  readonly toolsSchemaPath: string;
  readonly formulaRegistryPath: string;
} {
  fs.mkdirSync(GENERATED_DIR, { recursive: true });

  const succeeded = records.filter((record) => record.ok);
  const failed = records.filter((record) => !record.ok);

  const document: ToolsSchemaDocument = {
    generatedAt: new Date().toISOString(),
    generator: "scripts/deepseek/scan-tools.ts",
    summary: {
      discovered: records.length,
      scanned: records.length,
      succeeded: succeeded.length,
      failed: failed.length,
    },
    tools: records,
  };

  const toolsSchemaPath = path.join(GENERATED_DIR, "tools-schema.json");
  fs.writeFileSync(toolsSchemaPath, `${JSON.stringify(document, null, 2)}\n`, "utf8");

  const registryEntries: Record<string, DeepSeekScannedFormulaEntry> = {};
  for (const record of succeeded) {
    if (!record.payload) {
      continue;
    }
    registryEntries[record.slug] = {
      slug: record.slug,
      formulaSummary: record.payload.schema.formulaSummary,
      riskLevel: record.payload.audit.riskLevel,
      safeForCalculation: record.payload.audit.safeForCalculation,
      formulaConsistent: record.payload.audit.formulaConsistent,
      inputCount: record.payload.schema.inputs.length,
      outputCount: record.payload.schema.outputs.length,
      scannedAt: record.scannedAt,
    };
  }

  const formulaRegistryPath = path.join(GENERATED_DIR, "formula-registry.ts");
  fs.writeFileSync(
    formulaRegistryPath,
    buildFormulaRegistrySource(registryEntries),
    "utf8",
  );

  return { toolsSchemaPath, formulaRegistryPath };
}

function buildFormulaRegistrySource(
  entries: Record<string, DeepSeekScannedFormulaEntry>,
): string {
  const serializedEntries = Object.entries(entries)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([slug, entry]) => `  ${JSON.stringify(slug)}: ${JSON.stringify(entry, null, 2).replace(/\n/g, "\n  ")},`)
    .join("\n");

  return [
    "/**",
    " * Auto-generated by npm run scan:tools",
    " * Source: scripts/deepseek/scan-tools.ts",
    " * Do not edit manually.",
    " */",
    "",
    'export type DeepSeekScannedFormulaEntry = {',
    "  readonly slug: string;",
    "  readonly formulaSummary: string;",
    '  readonly riskLevel: "low" | "medium" | "high" | "critical";',
    "  readonly safeForCalculation: boolean;",
    "  readonly formulaConsistent: boolean;",
    "  readonly inputCount: number;",
    "  readonly outputCount: number;",
    "  readonly scannedAt: string;",
    "};",
    "",
    "export const DEEPSEEK_SCANNED_FORMULA_REGISTRY: Record<string, DeepSeekScannedFormulaEntry> = {",
    serializedEntries,
    "};",
    "",
  ].join("\n");
}
