// SectorCalc V5.4 — Free Tools Source-of-Truth Manifest
// Every active free tool must be registered here with its metadata.
// This is the single authoritative list. Catalog, sitemap, guards, and
// route resolution all derive from this manifest.

export interface FreeToolManifestEntry {
  slug: string;
  title: string;
  category: string;
  schemaPath: string;
  formulaPath: string;
  route: `/tools/free/${string}`;
  status: "LIVE_FREE";
  hasGolden: boolean;
  hasSampleInput: boolean;
  publicCopyClean: boolean;
}

const MANIFEST: FreeToolManifestEntry[] = [
  { slug: "machining-cost-per-part", title: "Machining Cost Per Part", category: "Machining & CNC", schemaPath: "src/sectorcalc/schemas/free-v531/machining-cost-per-part.json", formulaPath: "src/sectorcalc/formulas/free-v531/machining-cost-per-part.formula.ts", route: "/tools/free/machining-cost-per-part", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "cnc-shop-hourly-rate", title: "CNC Shop Hourly Rate", category: "Machining & CNC", schemaPath: "src/sectorcalc/schemas/free-v531/cnc-shop-hourly-rate.json", formulaPath: "src/sectorcalc/formulas/free-v531/cnc-shop-hourly-rate.formula.ts", route: "/tools/free/cnc-shop-hourly-rate", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "cutting-speed-feed-rpm", title: "Cutting Speed & Feed RPM", category: "Machining & CNC", schemaPath: "src/sectorcalc/schemas/free-v531/cutting-speed-feed-rpm.json", formulaPath: "src/sectorcalc/formulas/free-v531/cutting-speed-feed-rpm.formula.ts", route: "/tools/free/cutting-speed-feed-rpm", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "tap-drill-size", title: "Tap Drill Size", category: "Machining & CNC", schemaPath: "src/sectorcalc/schemas/free-v531/298-tap-drill-size.json", formulaPath: "src/sectorcalc/formulas/free-v531/tap-drill-size.formula.ts", route: "/tools/free/tap-drill-size", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "iso-286-tolerance-fit", title: "ISO 286 Tolerance Fit", category: "Machining & CNC", schemaPath: "src/sectorcalc/schemas/free-v531/iso-286-tolerance-fit.json", formulaPath: "src/sectorcalc/formulas/free-v531/iso-286-tolerance-fit.formula.ts", route: "/tools/free/iso-286-tolerance-fit", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "surface-roughness-converter", title: "Surface Roughness Converter", category: "Machining & CNC", schemaPath: "src/sectorcalc/schemas/free-v531/surface-roughness-converter.json", formulaPath: "src/sectorcalc/formulas/free-v531/surface-roughness-converter.formula.ts", route: "/tools/free/surface-roughness-converter", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "material-removal-rate", title: "Material Removal Rate", category: "Machining & CNC", schemaPath: "src/sectorcalc/schemas/free-v531/material-removal-rate.json", formulaPath: "src/sectorcalc/formulas/free-v531/material-removal-rate.formula.ts", route: "/tools/free/material-removal-rate", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "tool-life-tool-cost-per-part", title: "Tool Life & Cost Per Part", category: "Machining & CNC", schemaPath: "src/sectorcalc/schemas/free-v531/tool-life-tool-cost-per-part.json", formulaPath: "src/sectorcalc/formulas/free-v531/tool-life-tool-cost-per-part.formula.ts", route: "/tools/free/tool-life-tool-cost-per-part", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "scrap-cost", title: "Scrap Cost", category: "Quality & Scrap", schemaPath: "src/sectorcalc/schemas/free-v531/scrap-cost.json", formulaPath: "src/sectorcalc/formulas/free-v531/scrap-cost.formula.ts", route: "/tools/free/scrap-cost", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "rework-vs-scrap-decision", title: "Rework vs Scrap Decision", category: "Quality & Scrap", schemaPath: "src/sectorcalc/schemas/free-v531/rework-vs-scrap-decision.json", formulaPath: "src/sectorcalc/formulas/free-v531/rework-vs-scrap-decision.formula.ts", route: "/tools/free/rework-vs-scrap-decision", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "thread-dimensions-reference", title: "Thread Dimensions Reference", category: "Machining & CNC", schemaPath: "src/sectorcalc/schemas/free-v531/thread-dimensions-reference.json", formulaPath: "src/sectorcalc/formulas/free-v531/thread-dimensions-reference.formula.ts", route: "/tools/free/thread-dimensions-reference", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "knurling-drill-point-depth", title: "Knurling & Drill Point Depth", category: "Machining & CNC", schemaPath: "src/sectorcalc/schemas/free-v531/knurling-drill-point-depth.json", formulaPath: "src/sectorcalc/formulas/free-v531/knurling-drill-point-depth.formula.ts", route: "/tools/free/knurling-drill-point-depth", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "weld-metal-weight-consumable", title: "Weld Metal Weight & Consumable", category: "Welding & Fabrication", schemaPath: "src/sectorcalc/schemas/free-v531/weld-metal-weight-consumable.json", formulaPath: "src/sectorcalc/formulas/free-v531/weld-metal-weight-consumable.formula.ts", route: "/tools/free/weld-metal-weight-consumable", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "fillet-weld-size-strength", title: "Fillet Weld Size & Strength", category: "Welding & Fabrication", schemaPath: "src/sectorcalc/schemas/free-v531/fillet-weld-size-strength.json", formulaPath: "src/sectorcalc/formulas/free-v531/fillet-weld-size-strength.formula.ts", route: "/tools/free/fillet-weld-size-strength", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "welding-cost-per-meter", title: "Welding Cost Per Meter", category: "Welding & Fabrication", schemaPath: "src/sectorcalc/schemas/free-v531/welding-cost-per-meter.json", formulaPath: "src/sectorcalc/formulas/free-v531/welding-cost-per-meter.formula.ts", route: "/tools/free/welding-cost-per-meter", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "welding-heat-input", title: "Welding Heat Input", category: "Welding & Fabrication", schemaPath: "src/sectorcalc/schemas/free-v531/welding-heat-input.json", formulaPath: "src/sectorcalc/formulas/free-v531/welding-heat-input.formula.ts", route: "/tools/free/welding-heat-input", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "bolt-torque", title: "Bolt Torque", category: "Fasteners & Joints", schemaPath: "src/sectorcalc/schemas/free-v531/bolt-torque.json", formulaPath: "src/sectorcalc/formulas/free-v531/bolt-torque.formula.ts", route: "/tools/free/bolt-torque", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "bolt-preload-clamp-force", title: "Bolt Preload & Clamp Force", category: "Fasteners & Joints", schemaPath: "src/sectorcalc/schemas/free-v531/bolt-preload-clamp-force.json", formulaPath: "src/sectorcalc/formulas/free-v531/bolt-preload-clamp-force.formula.ts", route: "/tools/free/bolt-preload-clamp-force", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "steel-weight", title: "Steel Weight", category: "Materials & Weight", schemaPath: "src/sectorcalc/schemas/free-v531/steel-weight.json", formulaPath: "src/sectorcalc/formulas/free-v531/steel-weight.formula.ts", route: "/tools/free/steel-weight", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "beam-load-deflection-quick-check", title: "Beam Load & Deflection Quick Check", category: "Structural", schemaPath: "src/sectorcalc/schemas/free-v531/beam-load-deflection-quick-check.json", formulaPath: "src/sectorcalc/formulas/free-v531/beam-load-deflection-quick-check.formula.ts", route: "/tools/free/beam-load-deflection-quick-check", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "sheet-metal-bend-allowance", title: "Sheet Metal Bend Allowance", category: "Fabrication", schemaPath: "src/sectorcalc/schemas/free-v531/sheet-metal-bend-allowance.json", formulaPath: "src/sectorcalc/formulas/free-v531/sheet-metal-bend-allowance.formula.ts", route: "/tools/free/sheet-metal-bend-allowance", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "oee", title: "OEE", category: "Manufacturing & Productivity", schemaPath: "src/sectorcalc/schemas/free-v531/oee.json", formulaPath: "src/sectorcalc/formulas/free-v531/oee.formula.ts", route: "/tools/free/oee", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "downtime-cost", title: "Downtime Cost", category: "Manufacturing & Productivity", schemaPath: "src/sectorcalc/schemas/free-v531/downtime-cost.json", formulaPath: "src/sectorcalc/formulas/free-v531/downtime-cost.formula.ts", route: "/tools/free/downtime-cost", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "takt-time-cycle-time", title: "Takt Time & Cycle Time", category: "Manufacturing & Productivity", schemaPath: "src/sectorcalc/schemas/free-v531/takt-time-cycle-time.json", formulaPath: "src/sectorcalc/formulas/free-v531/takt-time-cycle-time.formula.ts", route: "/tools/free/takt-time-cycle-time", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "setup-time-cost", title: "Setup Time Cost", category: "Manufacturing & Productivity", schemaPath: "src/sectorcalc/schemas/free-v531/setup-time-cost.json", formulaPath: "src/sectorcalc/formulas/free-v531/setup-time-cost.formula.ts", route: "/tools/free/setup-time-cost", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "line-balancing-efficiency", title: "Line Balancing Efficiency", category: "Manufacturing & Productivity", schemaPath: "src/sectorcalc/schemas/free-v531/line-balancing-efficiency.json", formulaPath: "src/sectorcalc/formulas/free-v531/line-balancing-efficiency.formula.ts", route: "/tools/free/line-balancing-efficiency", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "compressed-air-leak-cost", title: "Compressed Air Leak Cost", category: "Energy & Utilities", schemaPath: "src/sectorcalc/schemas/free-v531/compressed-air-leak-cost.json", formulaPath: "src/sectorcalc/formulas/free-v531/compressed-air-leak-cost.formula.ts", route: "/tools/free/compressed-air-leak-cost", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "electric-motor-running-cost", title: "Electric Motor Running Cost", category: "Energy & Utilities", schemaPath: "src/sectorcalc/schemas/free-v531/electric-motor-running-cost.json", formulaPath: "src/sectorcalc/formulas/free-v531/electric-motor-running-cost.formula.ts", route: "/tools/free/electric-motor-running-cost", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "energy-cost-per-part", title: "Energy Cost Per Part", category: "Energy & Utilities", schemaPath: "src/sectorcalc/schemas/free-v531/energy-cost-per-part.json", formulaPath: "src/sectorcalc/formulas/free-v531/energy-cost-per-part.formula.ts", route: "/tools/free/energy-cost-per-part", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "cbam-cost-quick-estimator", title: "CBAM Cost Quick Estimator", category: "Energy & Utilities", schemaPath: "src/sectorcalc/schemas/free-v531/cbam-cost-quick-estimator.json", formulaPath: "src/sectorcalc/formulas/free-v531/cbam-cost-quick-estimator.formula.ts", route: "/tools/free/cbam-cost-quick-estimator", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "electricity-co2-emissions", title: "Electricity CO2 Emissions", category: "Energy & Utilities", schemaPath: "src/sectorcalc/schemas/free-v531/electricity-co2-emissions.json", formulaPath: "src/sectorcalc/formulas/free-v531/electricity-co2-emissions.formula.ts", route: "/tools/free/electricity-co2-emissions", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "diesel-fuel-co2-emissions", title: "Diesel Fuel CO2 Emissions", category: "Energy & Utilities", schemaPath: "src/sectorcalc/schemas/free-v531/diesel-fuel-co2-emissions.json", formulaPath: "src/sectorcalc/formulas/free-v531/diesel-fuel-co2-emissions.formula.ts", route: "/tools/free/diesel-fuel-co2-emissions", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "product-carbon-footprint-basic", title: "Product Carbon Footprint Basic", category: "Energy & Utilities", schemaPath: "src/sectorcalc/schemas/free-v531/product-carbon-footprint-basic.json", formulaPath: "src/sectorcalc/formulas/free-v531/product-carbon-footprint-basic.formula.ts", route: "/tools/free/product-carbon-footprint-basic", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "carbon-price-exposure", title: "Carbon Price Exposure", category: "Energy & Utilities", schemaPath: "src/sectorcalc/schemas/free-v531/carbon-price-exposure.json", formulaPath: "src/sectorcalc/formulas/free-v531/carbon-price-exposure.formula.ts", route: "/tools/free/carbon-price-exposure", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "true-employee-cost", title: "True Employee Cost", category: "Cost & Finance", schemaPath: "src/sectorcalc/schemas/free-v531/true-employee-cost.json", formulaPath: "src/sectorcalc/formulas/free-v531/true-employee-cost.formula.ts", route: "/tools/free/true-employee-cost", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "quote-margin-markup", title: "Quote Margin & Markup", category: "Cost & Finance", schemaPath: "src/sectorcalc/schemas/free-v531/quote-margin-markup.json", formulaPath: "src/sectorcalc/formulas/free-v531/quote-margin-markup.formula.ts", route: "/tools/free/quote-margin-markup", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "break-even-point", title: "Break-Even Point", category: "Cost & Finance", schemaPath: "src/sectorcalc/schemas/free-v531/break-even-point.json", formulaPath: "src/sectorcalc/formulas/free-v531/break-even-point.formula.ts", route: "/tools/free/break-even-point", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "break-even-and-margin-of-safety-analysis", title: "Break-Even & Margin of Safety Analysis", category: "Cost & Finance", schemaPath: "src/sectorcalc/schemas/free-v531/030-break-even-and-margin-of-safety-analysis.json", formulaPath: "src/sectorcalc/formulas/free-v531/break-even-and-margin-of-safety-analysis.formula.ts", route: "/tools/free/break-even-and-margin-of-safety-analysis", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "payment-term-cost", title: "Payment Term Cost", category: "Cost & Finance", schemaPath: "src/sectorcalc/schemas/free-v531/payment-term-cost.json", formulaPath: "src/sectorcalc/formulas/free-v531/payment-term-cost.formula.ts", route: "/tools/free/payment-term-cost", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "machine-investment-payback", title: "Machine Investment Payback", category: "Cost & Finance", schemaPath: "src/sectorcalc/schemas/free-v531/machine-investment-payback.json", formulaPath: "src/sectorcalc/formulas/free-v531/machine-investment-payback.formula.ts", route: "/tools/free/machine-investment-payback", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "customer-profitability", title: "Customer Profitability", category: "Cost & Finance", schemaPath: "src/sectorcalc/schemas/free-v531/customer-profitability.json", formulaPath: "src/sectorcalc/formulas/free-v531/customer-profitability.formula.ts", route: "/tools/free/customer-profitability", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "currency-adjusted-pricing", title: "Currency Adjusted Pricing", category: "Cost & Finance", schemaPath: "src/sectorcalc/schemas/free-v531/currency-adjusted-pricing.json", formulaPath: "src/sectorcalc/formulas/free-v531/currency-adjusted-pricing.formula.ts", route: "/tools/free/currency-adjusted-pricing", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "eoq", title: "EOQ", category: "Inventory & Logistics", schemaPath: "src/sectorcalc/schemas/free-v531/eoq.json", formulaPath: "src/sectorcalc/formulas/free-v531/eoq.formula.ts", route: "/tools/free/eoq", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "safety-stock-reorder-point", title: "Safety Stock & Reorder Point", category: "Inventory & Logistics", schemaPath: "src/sectorcalc/schemas/free-v531/safety-stock-reorder-point.json", formulaPath: "src/sectorcalc/formulas/free-v531/safety-stock-reorder-point.formula.ts", route: "/tools/free/safety-stock-reorder-point", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "inventory-carrying-cost", title: "Inventory Carrying Cost", category: "Inventory & Logistics", schemaPath: "src/sectorcalc/schemas/free-v531/inventory-carrying-cost.json", formulaPath: "src/sectorcalc/formulas/free-v531/inventory-carrying-cost.formula.ts", route: "/tools/free/inventory-carrying-cost", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "pallet-container-load-cbm", title: "Pallet & Container Load CBM", category: "Inventory & Logistics", schemaPath: "src/sectorcalc/schemas/free-v531/pallet-container-load-cbm.json", formulaPath: "src/sectorcalc/formulas/free-v531/pallet-container-load-cbm.formula.ts", route: "/tools/free/pallet-container-load-cbm", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "freight-cost-per-km-trip", title: "Freight Cost Per KM Trip", category: "Inventory & Logistics", schemaPath: "src/sectorcalc/schemas/free-v531/freight-cost-per-km-trip.json", formulaPath: "src/sectorcalc/formulas/free-v531/freight-cost-per-km-trip.formula.ts", route: "/tools/free/freight-cost-per-km-trip", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "concrete-volume-order-quantity", title: "Concrete Volume Order Quantity", category: "Construction", schemaPath: "src/sectorcalc/schemas/free-v531/concrete-volume-order-quantity.json", formulaPath: "src/sectorcalc/formulas/free-v531/concrete-volume-order-quantity.formula.ts", route: "/tools/free/concrete-volume-order-quantity", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "rebar-weight-count", title: "Rebar Weight & Count", category: "Construction", schemaPath: "src/sectorcalc/schemas/free-v531/rebar-weight-count.json", formulaPath: "src/sectorcalc/formulas/free-v531/rebar-weight-count.formula.ts", route: "/tools/free/rebar-weight-count", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "recipe-cost-menu-price", title: "Recipe Cost & Menu Price", category: "Food & Beverage", schemaPath: "src/sectorcalc/schemas/free-v531/recipe-cost-menu-price.json", formulaPath: "src/sectorcalc/formulas/free-v531/recipe-cost-menu-price.formula.ts", route: "/tools/free/recipe-cost-menu-price", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "fabric-consumption-gsm", title: "Fabric Consumption GSM", category: "Textile & Apparel", schemaPath: "src/sectorcalc/schemas/free-v531/fabric-consumption-gsm.json", formulaPath: "src/sectorcalc/formulas/free-v531/fabric-consumption-gsm.formula.ts", route: "/tools/free/fabric-consumption-gsm", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "von-mises-stress-calculator", title: "Von Mises Stress Calculator", category: "Structural", schemaPath: "src/sectorcalc/schemas/free-v531/278-von-mises-stress-calculator.json", formulaPath: "src/sectorcalc/formulas/free-v531/von-mises-stress-calculator.formula.ts", route: "/tools/free/von-mises-stress-calculator", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "net-present-value-calculator", title: "Net Present Value Calculator", category: "Finance", schemaPath: "src/sectorcalc/schemas/free-v531/400-net-present-value-calculator.json", formulaPath: "src/sectorcalc/formulas/free-v531/net-present-value-calculator.formula.ts", route: "/tools/free/net-present-value-calculator", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
  { slug: "return-on-investment-calculator", title: "Return on Investment Calculator", category: "Finance", schemaPath: "src/sectorcalc/schemas/free-v531/401-return-on-investment-calculator.json", formulaPath: "src/sectorcalc/formulas/free-v531/return-on-investment-calculator.formula.ts", route: "/tools/free/return-on-investment-calculator", status: "LIVE_FREE", hasGolden: true, hasSampleInput: false, publicCopyClean: true },
];

export function getFreeToolManifest(): FreeToolManifestEntry[] {
  return MANIFEST;
}

export function getFreeToolManifestEntry(slug: string): FreeToolManifestEntry | undefined {
  return MANIFEST.find((e) => e.slug === slug);
}

export function getActiveFreeToolSlugs(): string[] {
  return MANIFEST.map((e) => e.slug);
}

export const FREE_TOOL_MANIFEST_COUNT = MANIFEST.length;

export function verifyManifestConsistency(): { pass: boolean; errors: string[] } {
  const errors: string[] = [];
  const slugs = new Set<string>();
  for (const entry of MANIFEST) {
    if (slugs.has(entry.slug)) errors.push(`Duplicate slug: ${entry.slug}`);
    slugs.add(entry.slug);
    if (entry.status !== "LIVE_FREE") errors.push(`Non-LIVE status: ${entry.slug}`);
  }
  return { pass: errors.length === 0, errors };
}
