/** Generated by scripts/generate-roadmap-free-batch2.mjs — do not edit manually. */
import type { FreeTrafficInputValues } from "@/lib/tools/free-traffic-calculators";
import { runBatch1Formula, setBatch1FormatLocale, type Batch1CalcPartial } from "@/lib/tools/roadmap-free-batch1/engine";
import { ROADMAP_FREE_BATCH2_SPECS } from "@/lib/tools/roadmap-free-batch2-specs.generated";

export const ROADMAP_FREE_BATCH2_SLUGS = Object.freeze(Object.keys(ROADMAP_FREE_BATCH2_SPECS));

export function calculateRoadmapFreeBatch2Tool(
  slug: string,
  values: FreeTrafficInputValues,
  locale = "en",
): Batch1CalcPartial {
  const spec = ROADMAP_FREE_BATCH2_SPECS[slug];
  if (!spec) {
    throw new Error(`Unknown roadmap batch-2 calculator slug: ${slug}`);
  }
  setBatch1FormatLocale(locale);

  if (slug === "kdv-tevkifati-hesaplama" || slug === "stopaj-hesaplama-kira-serbest-meslek" || slug === "sgk-prim-hesaplama-isci-plus-isveren") {
    const amount = Number(values[slug === "sgk-prim-hesaplama-isci-plus-isveren" ? "grossWage" : slug === "kdv-tevkifati-hesaplama" ? "netAmount" : "grossAmount"] ?? 0);
    const rate = Number(values.withholdingRate ?? values.combinedRate ?? 0);
    const rateKey = slug === "sgk-prim-hesaplama-isci-plus-isveren" ? "combinedRate" : "withholdingRate";
    return runBatch1Formula(
      spec,
      { ...values, [slug === "sgk-prim-hesaplama-isci-plus-isveren" ? "grossWage" : slug === "kdv-tevkifati-hesaplama" ? "netAmount" : "grossAmount"]: amount * (rate / 100), [rateKey]: 1 },
    );
  }
  if (slug === "gelir-vergisi-dilimleri-hesaplama") {
    const income = Number(values.taxableIncome ?? 0);
    const rate = Number(values.effectiveRate ?? 0);
    return runBatch1Formula(spec, { taxableIncome: income * (rate / 100), effectiveRate: 1 });
  }
  if (slug === "makine-ekonomik-omru-hurda-deger-hesabi") {
    const cost = Number(values.machineCost ?? 0);
    const salvage = Number(values.salvageValue ?? 0);
    const years = Math.max(Number(values.usefulLifeYears ?? 1), 0.01);
    return runBatch1Formula(
      { kind: "divide", headline: "Machine depreciation", primaryLabel: "Annual depreciation", numerator: "depreciableBase", denominator: "usefulLifeYears", format: "currency", explanation: spec.explanation },
      { ...values, depreciableBase: Math.max(cost - salvage, 0), usefulLifeYears: years },
    );
  }
  if (slug === "kredi-erken-kapama-cezasi-hesaplama" || slug === "doviz-pozisyonu-kur-farki-riski-hesabi" || slug === "cek-senet-vade-kirma-maliyeti-hesabi" || slug === "trafik-cezasi-gecikme-faizi-hesaplama") {
    const baseKey = slug === "kredi-erken-kapama-cezasi-hesaplama" ? "remainingBalance" : slug === "doviz-pozisyonu-kur-farki-riski-hesabi" ? "foreignExposure" : slug === "cek-senet-vade-kirma-maliyeti-hesabi" ? "faceValue" : "fineAmount";
    const rateKey = slug === "doviz-pozisyonu-kur-farki-riski-hesabi" ? "fxMovePercent" : slug === "cek-senet-vade-kirma-maliyeti-hesabi" ? "discountRate" : slug === "trafik-cezasi-gecikme-faizi-hesaplama" ? "lateRate" : "penaltyRate";
    const base = Number(values[baseKey] ?? 0);
    const rate = Number(values[rateKey] ?? 0);
    return runBatch1Formula(spec, { ...values, [baseKey]: base * (rate / 100), [rateKey]: 1 });
  }
  if (slug === "enjeksiyon-dokum-cekme-payi-hesabi") {
    const length = Number(values.partLengthMm ?? 0);
    const shrink = Number(values.shrinkPercent ?? 0);
    return runBatch1Formula(spec, { partLengthMm: length * (shrink / 100), shrinkPercent: 1 });
  }

  return runBatch1Formula(spec, values);
}

export function hasRoadmapFreeBatch2Calculator(slug: string): boolean {
  return slug in ROADMAP_FREE_BATCH2_SPECS;
}
