/** Generated by scripts/generate-roadmap-free-batch1.mjs — do not edit manually. */
import type { FreeTrafficInputValues } from "@/lib/tools/free-traffic-calculators";
import { runBatch1Formula, setBatch1FormatLocale, type Batch1CalcPartial } from "@/lib/tools/roadmap-free-batch1/engine";
import { ROADMAP_FREE_BATCH1_SPECS } from "@/lib/tools/roadmap-free-batch1-specs.generated";

export const ROADMAP_FREE_BATCH1_SLUGS = Object.freeze(Object.keys(ROADMAP_FREE_BATCH1_SPECS));

export function calculateRoadmapFreeBatch1Tool(
  slug: string,
  values: FreeTrafficInputValues,
  locale = "en",
): Batch1CalcPartial {
  const spec = ROADMAP_FREE_BATCH1_SPECS[slug];
  if (!spec) {
    throw new Error(`Unknown roadmap batch-1 calculator slug: ${slug}`);
  }
  setBatch1FormatLocale(locale);
  if (slug === "enflasyon-fiyat-eskalasyonu-hesaplama") {
    const base = Number(values.baseAmount ?? 0);
    const rate = Number(values.inflationPercent ?? 0);
    return runBatch1Formula(
      {
        kind: "multiply",
        headline: "Inflation-adjusted amount",
        primaryLabel: "Escalated amount",
        keys: ["baseAmount", "inflationPercent"],
        format: "currency",
        explanation: "Single-period escalation ≈ base × (1 + rate/100) — informational only.",
      },
      { baseAmount: base * (1 + rate / 100), inflationPercent: 1 },
    );
  }
  if (slug === "arac-amortisman-hesaplama") {
    const cost = Number(values.vehicleCost ?? 0);
    const salvage = Number(values.salvageValue ?? 0);
    const years = Math.max(Number(values.usefulLifeYears ?? 1), 0.01);
    return runBatch1Formula(
      {
        kind: "divide",
        headline: "Vehicle depreciation",
        primaryLabel: "Annual depreciation",
        numerator: "depreciableBase",
        denominator: "usefulLifeYears",
        format: "currency",
        explanation: "Straight-line annual depreciation ≈ (cost − salvage) ÷ years (informational).",
      },
      { ...values, depreciableBase: Math.max(cost - salvage, 0), usefulLifeYears: years },
    );
  }
  return runBatch1Formula(spec, values);
}

export function hasRoadmapFreeBatch1Calculator(slug: string): boolean {
  return slug in ROADMAP_FREE_BATCH1_SPECS;
}
