/**
 * P6B formula factory guide specs — schema-derived input maps.
 * GENERATED by scripts/tool-activation/p6b-apply-safe-formula-batch.mjs
 */
import {
  TOOL_GUIDE_QUALITY_DEFAULT,
  type ToolGuideSpec,
} from "@/lib/tool-guides/tool-guide-spec";

export const P6B_FORMULA_FACTORY_GUIDE_SPECS: readonly ToolGuideSpec[] = [
  {
    slug: "yatak-rulman-omur-hesabi-l10",
    guideType: "cost_breakdown",
    titleKey: "inputGuide.p6bFormulaFactory.tools.yatakRulmanOmurHesabiL10.title",
    descriptionKey: "inputGuide.costBreakdown.description",
    inputMap: [
      { inputKey: "dynamicLoadRatingC", visualRole: "primary", nodeId: "dynamicloadratingc" },
      { inputKey: "equivalentDynamicLoadP", visualRole: "driver", nodeId: "equivalentdynamicloadp" },
      { inputKey: "rotationalSpeedN", visualRole: "driver", nodeId: "rotationalspeedn" },
      { inputKey: "reliabilityFactorA1", visualRole: "secondary", nodeId: "reliabilityfactora1" },
      { inputKey: "materialFactorA2", visualRole: "output", nodeId: "materialfactora2" },
    ],
    quality: TOOL_GUIDE_QUALITY_DEFAULT,
  }
];
