/**
 * P6B formula factory guide specs — schema-derived input maps.
 * GENERATED by scripts/tool-activation/p6b-apply-safe-formula-batch.mjs
 */
import {
  TOOL_GUIDE_QUALITY_DEFAULT,
  type ToolGuideSpec,
} from "@/lib/tool-guides/tool-guide-spec";

export const P6B_FORMULA_FACTORY_GUIDE_SPECS: readonly ToolGuideSpec[] = [
  {
    slug: "3d-print-job-margin-tool",
    guideType: "cost_breakdown",
    titleKey: "inputGuide.p6bFormulaFactory.tools.threeDPrintJobMarginTool.title",
    descriptionKey: "inputGuide.costBreakdown.description",
    inputMap: [
      { inputKey: "materialCost", visualRole: "primary", nodeId: "materialcost" },
      { inputKey: "machineTimeHours", visualRole: "driver", nodeId: "machinetimehours" },
      { inputKey: "machineHourlyRate", visualRole: "driver", nodeId: "machinehourlyrate" },
      { inputKey: "laborHours", visualRole: "secondary", nodeId: "laborhours" },
      { inputKey: "laborHourlyRate", visualRole: "secondary", nodeId: "laborhourlyrate" },
      { inputKey: "electricityCost", visualRole: "secondary", nodeId: "electricitycost" },
      { inputKey: "postProcessingCost", visualRole: "driver", nodeId: "postprocessingcost" },
      { inputKey: "failureScrapRatePercent", visualRole: "driver", nodeId: "failurescrapratepercent" },
      { inputKey: "overheadPercent", visualRole: "secondary", nodeId: "overheadpercent" },
      { inputKey: "targetMarginPercent", visualRole: "output", nodeId: "targetmarginpercent" },
    ],
    quality: TOOL_GUIDE_QUALITY_DEFAULT,
  },
  {
    slug: "welding-bid-risk-analyzer",
    guideType: "cost_breakdown",
    titleKey: "inputGuide.p6bFormulaFactory.tools.weldingBidRiskAnalyzer.title",
    descriptionKey: "inputGuide.costBreakdown.description",
    inputMap: [
      { inputKey: "monthlyToolCost", visualRole: "primary", nodeId: "monthlytoolcost" },
      { inputKey: "partsProduced", visualRole: "driver", nodeId: "partsproduced" },
      { inputKey: "toolChangeMinutes", visualRole: "driver", nodeId: "toolchangeminutes" },
      { inputKey: "changesPerMonth", visualRole: "secondary", nodeId: "changespermonth" },
      { inputKey: "hourlyCost", visualRole: "secondary", nodeId: "hourlycost" },
      { inputKey: "coolantCost", visualRole: "output", nodeId: "coolantcost" },
    ],
    quality: TOOL_GUIDE_QUALITY_DEFAULT,
  }
];
