"use client";

// SectorCalc PRO — Capital Equipment Investment Appraisal: NPV/IRR
// Dedicated page implementing the x1 reference design (see buy-lease-keep
// for the sibling pattern this was built from). Live preview via the pure
// formula engine (no credit cost); sealed report via
// /api/pro-calculator/execute (1 credit).
//
// Input keys sent to the server are the EXACT schema.inputs[].id values
// (snake_case: capex, discount_rate, ...) with raw DISPLAY values and a
// matching selected_units entry — never pre-converted canonical values —
// so the server's unit-normalizer converts exactly once.

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  executeFormula,
  schedule,
  npvAt,
  irr as computeIrr,
  IRR_UNDEFINED,
  NO_PAYBACK_YEARS,
  declaredOutputKeys as SEALED_OUTPUT_KEYS,
  type CapitalAppraisalInputs,
  type CapitalAppraisalOutputs,
} from "@/sectorcalc/formulas/pro-v531/capital-equipment-investment-appraisal-npv-irr.formula";
import { useUserSubscription } from "@/lib/features/billing/use-user-subscription";
import { isProBypassEmail } from "@/lib/features/billing/subscription";
import { PremiumReportFeedback } from "@/components/reports/PremiumReportFeedback";
import "@/styles/capital-equipment-npv-irr-tool.css";

const TOOL_KEY = "capital-equipment-investment-appraisal-npv-irr";
const BYPASS_SESSION_ID = "bypass-unlimited";

// ── Currency registry ────────────────────────────────────────────
const CURRENCIES: Array<{ code: string; sym: string }> = [
  { code: "EUR", sym: "€" }, { code: "USD", sym: "$" }, { code: "GBP", sym: "£" },
  { code: "TRY", sym: "₺" }, { code: "JPY", sym: "¥JP" }, { code: "CNY", sym: "¥CN" },
  { code: "CHF", sym: "CHF" }, { code: "SEK", sym: "kr" }, { code: "AUD", sym: "A$" },
  { code: "CAD", sym: "C$" }, { code: "INR", sym: "₹" }, { code: "AED", sym: "AED" },
];

// ── Field schema — id MUST equal schema.inputs[].id exactly ────────
type Dom = "cur" | "pct" | "num";
interface UnitOption { k: string; f: number; l: string }
interface FieldDef {
  ev: keyof CapitalAppraisalInputs;
  dom: Dom;
  label: string;
  def: number;
  hard: [number, number];
  ref: [number, number];
  refUnit: string;
  hint: string;
  src: string;
  grp: number;
  units?: UnitOption[];
}
const FIELDS: Record<string, FieldDef> = {
  capex:                  { ev: "capex",                dom: "cur", label: "CAPEX — initial investment",         def: 200000, hard: [1, 5e7],   ref: [15000, 5000000],  refUnit: "", hint: "Total installed cost of the equipment being appraised.", src: "vendor quote or capex budget", grp: 1 },
  discount_rate:          { ev: "discountRate",          dom: "pct", label: "Discount rate / hurdle rate",        def: 10,     hard: [0, 40],    ref: [6, 15],           refUnit: "%", hint: "Corporate cost of capital or minimum acceptable return.", src: "finance policy", grp: 1 },
  study_years:            { ev: "studyYears",            dom: "num", label: "Analysis period",                    def: 8,      hard: [1, 40],    ref: [5, 15],           refUnit: "yr", hint: "Investment appraisal horizon.", src: "engineering assumption register", grp: 1,
                            units: [{ k: "yr", f: 1, l: "years" }, { k: "mo", f: 1 / 12, l: "months" }] },
  annual_cash_flow:       { ev: "annualCashFlow",        dom: "cur", label: "Annual net cash flow (Year 1)",      def: 50000,  hard: [-5e7, 5e7],ref: [10000, 1000000],  refUnit: "/yr", hint: "Year-1 net operating cash flow generated by the investment.", src: "finance projection", grp: 2 },
  cash_flow_growth_rate:  { ev: "cashFlowGrowthRate",    dom: "pct", label: "Cash flow growth rate",              def: 3,      hard: [-30, 30],  ref: [-5, 8],           refUnit: "%/yr", hint: "Annual growth (or decline) in net cash flow after year 1.", src: "finance projection", grp: 2 },
  residual_value:         { ev: "residualValue",         dom: "cur", label: "Residual / salvage value",           def: 20000,  hard: [0, 5e7],   ref: [0, 1000000],      refUnit: "", hint: "Equipment resale/salvage value at the end of the analysis period.", src: "appraisal or resale comp", grp: 3 },
  working_capital:        { ev: "workingCapital",        dom: "cur", label: "Incremental working capital",        def: 10000,  hard: [0, 5e7],   ref: [0, 500000],       refUnit: "", hint: "Additional working capital tied up at t=0 and recovered at the end.", src: "finance projection", grp: 3 },
};
const GROUPS: Record<number, { n: string; t: string; d: string }> = {
  1: { n: "01", t: "Global assumptions", d: "What the equipment costs new, the cost of capital, and how long you are analysing." },
  2: { n: "02", t: "Operating cash flow", d: "The net cash the investment generates each year, and how that changes over time." },
  3: { n: "03", t: "Terminal position", d: "What comes back at the end of the study period — resale value and recovered working capital." },
};

interface FieldState { value: string; unit: string; error: string | null; warn: boolean; canon: number | null; }

function unitFactor(f: FieldDef, unitKey: string): number {
  if (!f.units) return 1;
  return (f.units.find((u) => u.k === unitKey) ?? f.units[0]).f;
}
function toCanon(f: FieldDef, raw: number, unitKey: string): number {
  const v = f.dom === "pct" ? raw / 100 : raw;
  return v * unitFactor(f, unitKey);
}
function fromCanon(f: FieldDef, canon: number, unitKey: string): number {
  const v = canon / unitFactor(f, unitKey);
  return f.dom === "pct" ? v * 100 : v;
}
function boundValue(f: FieldDef, raw: number, canon: number): number { return f.dom === "pct" ? raw : canon; }
function refCheck(f: FieldDef, canon: number): boolean {
  const lo = f.dom === "pct" ? f.ref[0] / 100 : f.ref[0];
  const hi = f.dom === "pct" ? f.ref[1] / 100 : f.ref[1];
  return canon < lo || canon > hi;
}
function fmtRef(f: FieldDef, curSym: string): string {
  if (f.dom === "pct") return `Ref: ${f.ref[0]}–${f.ref[1]}%`;
  if (f.dom === "cur") return `Ref: ${curSym}${f.ref[0].toLocaleString()}–${curSym}${f.ref[1].toLocaleString()}`;
  return `Ref: ${f.ref[0].toLocaleString()}–${f.ref[1].toLocaleString()} ${f.refUnit}`;
}
function fmt(x: number | null | undefined): string {
  if (x == null || Number.isNaN(x)) return "—";
  if (!Number.isFinite(x)) return "∞";
  const a = Math.abs(x);
  return x.toLocaleString("en-US", { maximumFractionDigits: a >= 100 ? 0 : a >= 1 ? 2 : 4 });
}

// ── SVG chart builders (verified engine, reused as string generators) ──
const CCOL = { pos: "#2E6B4E", neg: "#9C3520", ink: "#181713", faint: "#8C887E", line: "#E4E0D6", accent: "#C15F3C" };
function svgOpen(w: number, h: number) { return `<svg class="nir-chart" viewBox="0 0 ${w} ${h}" preserveAspectRatio="xMidYMid meet" xmlns="http://www.w3.org/2000/svg">`; }

/** NPV vs discount rate — the single clearest visual proof that IRR is a
 *  genuine root of NPV(rate)=0, not an assumed number. Sweeps a rate range
 *  spanning 0 to ~1.5x the higher of (hurdle rate, IRR) so the crossing is
 *  always visible on-chart. */
function chartNpvVsRate(x: CapitalAppraisalInputs, r: CapitalAppraisalOutputs, curSym: string): string {
  const w = 680, h = 260, padL = 74, padR = 20, padT = 16, padB = 34;
  const irrValid = r.out_irr > IRR_UNDEFINED + 1e-9;
  const maxRate = Math.max(x.discountRate, irrValid ? r.out_irr : x.discountRate) * 1.6 + 0.02;
  const N = 40;
  const pts: Array<{ rate: number; npv: number }> = [];
  for (let i = 0; i <= N; i++) {
    const rate = (maxRate * i) / N;
    pts.push({ rate, npv: npvAt(x, rate) });
  }
  const maxNpv = Math.max(...pts.map((p) => p.npv), 0);
  const minNpv = Math.min(...pts.map((p) => p.npv), 0);
  const span = maxNpv - minNpv || 1;
  const X = (rate: number) => padL + (w - padL - padR) * (rate / maxRate);
  const Y = (npv: number) => padT + (h - padT - padB) * (1 - (npv - minNpv) / span);
  let s = svgOpen(w, h);
  const zeroY = Y(0);
  s += `<line x1="${padL}" y1="${zeroY}" x2="${w - padR}" y2="${zeroY}" stroke="${CCOL.faint}" stroke-width="1"/>`;
  for (let g = 0; g <= 4; g++) {
    const rv = (maxRate * g) / 4;
    s += `<text x="${X(rv)}" y="${h - padB + 18}" text-anchor="middle" fill="${CCOL.faint}" font-size="10">${(rv * 100).toFixed(0)}%</text>`;
  }
  const path = pts.map((p, i) => `${i === 0 ? "M" : "L"}${X(p.rate).toFixed(1)},${Y(p.npv).toFixed(1)}`).join(" ");
  s += `<path d="${path}" fill="none" stroke="${CCOL.accent}" stroke-width="2.4"/>`;
  s += `<line x1="${X(x.discountRate)}" y1="${padT}" x2="${X(x.discountRate)}" y2="${h - padB}" stroke="${CCOL.ink}" stroke-width="1" stroke-dasharray="3 3"/>`;
  s += `<text x="${X(x.discountRate)}" y="${padT + 12}" text-anchor="middle" fill="${CCOL.ink}" font-size="10">hurdle ${(x.discountRate * 100).toFixed(1)}%</text>`;
  if (irrValid) {
    const ix = X(r.out_irr);
    s += `<circle cx="${ix}" cy="${zeroY}" r="4.5" fill="${CCOL.pos}"/>`;
    s += `<text x="${ix}" y="${zeroY - 8}" text-anchor="middle" fill="${CCOL.pos}" font-size="11">IRR ${(r.out_irr * 100).toFixed(1)}%</text>`;
  }
  s += `<text x="${padL - 8}" y="${zeroY + 4}" text-anchor="end" fill="${CCOL.faint}" font-size="10">${curSym}0</text>`;
  s += `<text x="${padL - 8}" y="${Y(maxNpv) + 4}" text-anchor="end" fill="${CCOL.faint}" font-size="10">${curSym}${fmt(maxNpv)}</text>`;
  return s + "</svg>";
}

/** Cumulative discounted cash flow — visualizes both simple and discounted
 *  payback as the crossing points against the zero line. */
function chartPayback(x: CapitalAppraisalInputs, curSym: string): string {
  const w = 680, h = 260, padL = 74, padR = 20, padT = 16, padB = 34;
  const sch = schedule(x);
  const outlay = x.capex + x.workingCapital;
  let cumNom = -outlay, cumDisc = -outlay;
  const pts: Array<{ t: number; nom: number; disc: number }> = [{ t: 0, nom: cumNom, disc: cumDisc }];
  for (const row of sch.rows) {
    cumNom += row.total;
    cumDisc += row.total / Math.pow(1 + x.discountRate, row.year);
    pts.push({ t: row.year, nom: cumNom, disc: cumDisc });
  }
  const maxV = Math.max(...pts.map((p) => Math.max(p.nom, p.disc)), 0);
  const minV = Math.min(...pts.map((p) => Math.min(p.nom, p.disc)), 0);
  const span = maxV - minV || 1;
  const X = (t: number) => padL + (w - padL - padR) * (t / sch.years);
  const Y = (v: number) => padT + (h - padT - padB) * (1 - (v - minV) / span);
  let s = svgOpen(w, h);
  const zeroY = Y(0);
  s += `<line x1="${padL}" y1="${zeroY}" x2="${w - padR}" y2="${zeroY}" stroke="${CCOL.faint}" stroke-width="1"/>`;
  for (let t = 0; t <= sch.years; t++) s += `<text x="${X(t)}" y="${h - padB + 18}" text-anchor="middle" fill="${CCOL.faint}" font-size="10">${t}</text>`;
  const line = (key: "nom" | "disc", col: string) => `<polyline points="${pts.map((p) => `${X(p.t)},${Y(p[key])}`).join(" ")}" fill="none" stroke="${col}" stroke-width="2.2"/>`;
  s += line("nom", CCOL.faint) + line("disc", CCOL.accent);
  const lg: Array<[string, string]> = [["Simple (undiscounted)", CCOL.faint], ["Discounted", CCOL.accent]];
  lg.forEach(([l, c], k) => {
    const lx = padL + k * 170;
    s += `<rect x="${lx}" y="4" width="12" height="12" fill="${c}"/><text x="${lx + 18}" y="14" fill="${CCOL.ink}" font-size="11">${l}</text>`;
  });
  s += `<text x="${padL - 8}" y="${zeroY + 4}" text-anchor="end" fill="${CCOL.faint}" font-size="10">${curSym}0</text>`;
  return s + "</svg>";
}

function chartTornado(x: CapitalAppraisalInputs, curSym: string): string {
  const drivers: Array<{ key: keyof CapitalAppraisalInputs; label: string }> = [
    { key: "annualCashFlow", label: "Annual cash flow ±15%" },
    { key: "capex", label: "CAPEX ±15%" },
    { key: "discountRate", label: "Discount rate ±15%" },
    { key: "cashFlowGrowthRate", label: "Cash flow growth ±15%" },
    { key: "residualValue", label: "Residual value ±15%" },
  ];
  const bars = drivers.map((d) => {
    const up = { ...x, [d.key]: x[d.key] * 1.15 } as CapitalAppraisalInputs;
    const dn = { ...x, [d.key]: x[d.key] * 0.85 } as CapitalAppraisalInputs;
    const npvUp = npvAt(up, up.discountRate);
    const npvDn = npvAt(dn, dn.discountRate);
    return { label: d.label, span: Math.abs(npvUp - npvDn) };
  }).sort((a, b) => b.span - a.span);
  const w = 680, padL = 190, padR = 90, h = 40 + bars.length * 30;
  const maxSpan = Math.max(...bars.map((b) => b.span), 1);
  let s = svgOpen(w, h);
  bars.forEach((b, k) => {
    const y = 18 + k * 30;
    const bw = ((w - padL - padR) * b.span) / maxSpan;
    s += `<text x="${padL - 12}" y="${y + 15}" text-anchor="end" fill="${CCOL.ink}" font-size="11">${b.label}</text>`;
    s += `<rect x="${padL}" y="${y}" width="${bw.toFixed(1)}" height="20" fill="${CCOL.accent}" opacity="0.8"/>`;
    s += `<text x="${padL + bw + 8}" y="${y + 15}" fill="${CCOL.faint}" font-size="10">${curSym}${fmt(b.span)}</text>`;
  });
  return s + "</svg>";
}

interface Insight { sev: "opp" | "info" | "crit"; t: string; msg: string }

function buildInsights(x: CapitalAppraisalInputs, r: CapitalAppraisalOutputs, curSym: string): Insight[] {
  const out: Insight[] = [];
  const fmtMoney = (v: number) => curSym + fmt(v);
  const irrValid = r.out_irr > IRR_UNDEFINED + 1e-9;

  if (r.out_decision === 1) {
    out.push({ sev: "opp", t: "recommendation",
      msg: `<strong>ACCEPT.</strong> NPV is positive (${fmtMoney(r.out_npv)}) and IRR (${irrValid ? (r.out_irr * 100).toFixed(1) + "%" : "undefined"}) clears the ${(x.discountRate * 100).toFixed(1)}% hurdle rate by ${irrValid ? (r.out_irr_minus_hurdle * 100).toFixed(1) + " points" : "n/a"}. This investment creates value at the assumptions entered.` });
  } else {
    out.push({ sev: "crit", t: "recommendation",
      msg: `<strong>REJECT.</strong> ${r.out_npv <= 0 ? `NPV is ${fmtMoney(r.out_npv)} at the ${(x.discountRate * 100).toFixed(1)}% hurdle rate.` : "IRR does not clear the hurdle rate."} This investment destroys value at the current assumptions — do not commit capital without revising the case.` });
  }

  out.push({ sev: "info", t: "profitability index",
    msg: `Profitability Index is <strong>${r.out_profitability_index.toFixed(2)}</strong> — every ${curSym}1 committed returns ${curSym}${r.out_profitability_index.toFixed(2)} in present value. ${r.out_profitability_index > 1 ? "Above 1.00 confirms value creation, consistent with the NPV sign." : "Below 1.00 confirms value destruction, consistent with the NPV sign."}`});

  out.push({ sev: "info", t: "payback",
    msg: `Simple payback in <strong>${r.out_payback_years < NO_PAYBACK_YEARS ? r.out_payback_years.toFixed(1) + " years" : "never (within the study period)"}</strong>; discounted payback (the more honest number — it accounts for the time value of money) in <strong>${r.out_discounted_payback_years < NO_PAYBACK_YEARS ? r.out_discounted_payback_years.toFixed(1) + " years" : "never"}</strong>.` });

  const terminalShare = r.out_npv !== 0 ? Math.abs(r.out_terminal_pv / (r.out_npv + x.capex + x.workingCapital)) : 0;
  if (terminalShare > 0.15)
    out.push({ sev: "info", t: "terminal-value dependency",
      msg: `The present value of the residual/working-capital recovery (${fmtMoney(r.out_terminal_pv)}) makes up a meaningful share of total inflows. If the equipment's actual resale value at year ${x.studyYears} is uncertain, stress-test the case without it.` });

  const upCapex = npvAt({ ...x, capex: x.capex * 1.15 }, x.discountRate);
  const dnCapex = npvAt({ ...x, capex: x.capex * 0.85 }, x.discountRate);
  const upCF = npvAt({ ...x, annualCashFlow: x.annualCashFlow * 1.15 }, x.discountRate);
  const dnCF = npvAt({ ...x, annualCashFlow: x.annualCashFlow * 0.85 }, x.discountRate);
  const mostSensitive = Math.abs(upCF - dnCF) >= Math.abs(upCapex - dnCapex) ? "annual cash flow" : "CAPEX";
  out.push({ sev: "info", t: "critical variable",
    msg: `The verdict is most sensitive to <strong>${mostSensitive}</strong>. Get this number from a signed quote or a finance-approved projection, not a rough estimate, before committing.` });

  out.push({ sev: "info", t: "scope limitation — tax shield not modeled",
    msg: `This engine prices pre-tax cash flow only. Depreciation tax shield is not modeled — get your tax basis from finance if the accept/reject call is close.` });

  return out;
}

interface ServerSeal { output_hash?: string; input_hash?: string; schema_hash?: string; hash_algorithm?: string; executed_at?: string }
interface ServerResultState { outputs: Record<string, number>; seal: ServerSeal; inputs: CapitalAppraisalInputs; currency: string }

export default function CapitalEquipmentNpvIrrToolPage() {
  const [curSym, setCurSym] = useState("€");
  const reportRef = useRef<HTMLDivElement>(null);

  const { user } = useUserSubscription();
  const [usageSessionId, setUsageSessionId] = useState<string | null>(null);
  const [remainingRuns, setRemainingRuns] = useState<number | null>(null);
  const [sessionLoading, setSessionLoading] = useState(false);
  const [sessionError, setSessionError] = useState<string | null>(null);
  const [authToken, setAuthToken] = useState<string | null>(null);
  const lastUid = useRef<string | null | undefined>(undefined);

  const [isExecuting, setIsExecuting] = useState(false);
  const [serverResult, setServerResult] = useState<ServerResultState | null>(null);
  const [executeError, setExecuteError] = useState<string | null>(null);

  useEffect(() => {
    const uid = user?.uid ?? null;
    if (lastUid.current === uid) return;
    lastUid.current = uid;
    setAuthToken(null);
    setUsageSessionId(null);
    setRemainingRuns(null);
    setSessionError(null);
    setExecuteError(null);
    setServerResult(null);
    if (user) {
      user.getIdToken(false).then(setAuthToken).catch(() => setSessionError("Could not verify your session — please refresh."));
    }
  }, [user]);

  useEffect(() => {
    if (user?.email && isProBypassEmail(user.email)) {
      setUsageSessionId(BYPASS_SESSION_ID);
      setRemainingRuns(999);
    }
  }, [user?.email]);

  const requestSession = useCallback(async () => {
    if (user?.email && isProBypassEmail(user.email)) return;
    setSessionLoading(true);
    setSessionError(null);
    try {
      if (!user) { window.location.href = `/login?next=${encodeURIComponent(window.location.pathname)}`; return; }
      const idToken = await user.getIdToken(false);
      const res = await fetch("/api/pro-tool-session/create", {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${idToken}` },
        body: JSON.stringify({ toolKey: TOOL_KEY }),
      });
      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        if (data.error === "INSUFFICIENT_CREDITS") { window.location.href = "/pricing"; return; }
        throw new Error(data.error || "Session failed");
      }
      const session = await res.json();
      setUsageSessionId(session.usageSessionId);
      setRemainingRuns(session.remainingRuns);
    } catch (err) {
      setSessionError(err instanceof Error ? err.message : "Could not start a session — please try again.");
    } finally { setSessionLoading(false); }
  }, [user]);

  const [fieldStates, setFieldStates] = useState<Record<string, FieldState>>(() => {
    const s: Record<string, FieldState> = {};
    for (const id of Object.keys(FIELDS)) {
      const f = FIELDS[id];
      const unit = f.units ? f.units[0].k : "";
      const canon = toCanon(f, f.def, unit);
      s[id] = { value: String(f.def), unit, error: null, warn: refCheck(f, canon), canon };
    }
    return s;
  });

  const updateField = useCallback((id: string, newValue: string) => {
    setFieldStates((prev) => {
      const f = FIELDS[id];
      const st = prev[id];
      const raw = parseFloat(newValue);
      let error: string | null = null;
      let warn = false;
      let canon: number | null = null;
      if (newValue.trim() === "" || Number.isNaN(raw)) {
        error = "Enter a number.";
      } else {
        canon = toCanon(f, raw, st.unit);
        const bv = boundValue(f, raw, canon);
        if (bv < f.hard[0] || bv > f.hard[1]) {
          error = `Outside valid range (${f.hard[0]}–${f.hard[1]}${f.dom === "pct" ? "%" : ""}).`;
          canon = null;
        } else {
          warn = refCheck(f, canon);
        }
      }
      return { ...prev, [id]: { ...st, value: newValue, error, warn, canon } };
    });
  }, []);

  const updateFieldUnit = useCallback((id: string, newUnit: string) => {
    setFieldStates((prev) => {
      const f = FIELDS[id];
      const st = prev[id];
      if (st.canon == null) return { ...prev, [id]: { ...st, unit: newUnit } };
      const raw = fromCanon(f, st.canon, newUnit);
      const rounded = Math.round(raw * 1000) / 1000;
      return { ...prev, [id]: { ...st, unit: newUnit, value: String(rounded) } };
    });
  }, []);

  const collectedInputs = useMemo((): CapitalAppraisalInputs | null => {
    const o: Partial<CapitalAppraisalInputs> = {};
    for (const [id, st] of Object.entries(fieldStates)) {
      if (st.error || st.canon == null) return null;
      (o as Record<string, number>)[FIELDS[id].ev] = st.canon;
    }
    return o as CapitalAppraisalInputs;
  }, [fieldStates]);

  const engineResult = useMemo((): CapitalAppraisalOutputs | null => {
    if (!collectedInputs) return null;
    try { return executeFormula(collectedInputs); } catch { return null; }
  }, [collectedInputs]);

  const errorCount = useMemo(() => Object.values(fieldStates).filter((s) => s.error).length, [fieldStates]);

  const handleGenerate = useCallback(async () => {
    if (!collectedInputs || isExecuting || !usageSessionId) return;
    setIsExecuting(true);
    setExecuteError(null);
    const snapshotInputs = collectedInputs;
    const snapshotCurrency = curSym;
    try {
      const rawInputs: Record<string, number> = {};
      const selectedUnits: Record<string, string> = {};
      for (const [id, st] of Object.entries(fieldStates)) {
        const f = FIELDS[id];
        if (f.units) {
          rawInputs[id] = st.canon ?? parseFloat(st.value);
        } else {
          rawInputs[id] = parseFloat(st.value);
          if (f.dom === "pct") selectedUnits[id] = "percent";
        }
      }
      const res = await fetch("/api/pro-calculator/execute", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          ...(authToken ? { Authorization: `Bearer ${authToken}` } : {}),
        },
        body: JSON.stringify({
          tool_key: TOOL_KEY,
          raw_inputs: rawInputs,
          selected_units: selectedUnits,
          usage_session_id: usageSessionId,
        }),
      });
      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        throw new Error(data.error || `Server error ${res.status}`);
      }
      const data = await res.json();
      const outputsMap: Record<string, number> = {};
      if (Array.isArray(data.outputs)) {
        for (const o of data.outputs) if (typeof o.value === "number") outputsMap[o.id] = o.value;
      } else if (data.outputs && typeof data.outputs === "object") {
        Object.assign(outputsMap, data.outputs);
      }

      const missingOrNonFinite = SEALED_OUTPUT_KEYS.filter(
        (k) => typeof outputsMap[k] !== "number" || !Number.isFinite(outputsMap[k]),
      );
      const decisionOk = [0, 1].includes(outputsMap.out_decision);
      const seal = data.audit_seal as Record<string, unknown> | undefined;
      const sealOk = !!seal && seal.seal_status === "SEALED" && typeof seal.output_hash === "string" && seal.output_hash.length > 0
        && typeof seal.hash_algorithm === "string";
      if (missingOrNonFinite.length > 0 || !decisionOk || !sealOk) {
        throw new Error(
          `Sealed response incomplete (${[
            missingOrNonFinite.length ? `missing/non-finite: ${missingOrNonFinite.join(", ")}` : null,
            decisionOk ? null : "invalid decision flag",
            sealOk ? null : "missing or unsealed audit seal",
          ].filter(Boolean).join("; ")}) — report withheld.`,
        );
      }

      setServerResult({
        outputs: outputsMap,
        seal: {
          output_hash: seal!.output_hash as string,
          input_hash: seal!.input_hash as string | undefined,
          schema_hash: seal!.schema_hash as string | undefined,
          hash_algorithm: seal!.hash_algorithm as string,
          executed_at: seal!.executed_at as string | undefined,
        },
        inputs: snapshotInputs,
        currency: snapshotCurrency,
      });
      setTimeout(() => reportRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }), 100);
    } catch (err) {
      setExecuteError(err instanceof Error ? err.message : "Execution failed");
    } finally {
      setIsExecuting(false);
    }
  }, [collectedInputs, isExecuting, usageSessionId, authToken, fieldStates, curSym]);

  const r = engineResult;
  const x = collectedInputs;
  const canGenerate = !!x && !isExecuting;
  const irrValidLive = r ? r.out_irr > IRR_UNDEFINED + 1e-9 : false;

  const renderField = (id: string) => {
    const f = FIELDS[id];
    const st = fieldStates[id];
    const cls = st.error ? "nir-bad" : st.warn ? "nir-warn" : "";
    const msg = st.error ? st.error : st.warn ? `Outside typical industry range (${fmtRef(f, curSym)}). Value accepted — flagged for review.` : "";
    const msgCls = st.error ? "nir-err" : st.warn ? "nir-warn" : "";
    const msgId = `ms_${id}`;
    const canonUnitLabel = f.units ? ` ${f.units[0].l}` : "";
    const canonTxt = st.error ? "" : `= ${f.dom === "cur" ? curSym : ""}${fmt(f.dom === "pct" ? (st.canon ?? 0) * 100 : st.canon)}${canonUnitLabel}`;
    return (
      <div className="nir-f" key={id}>
        <div className="nir-f-top">
          <label htmlFor={`in_${id}`}>{f.label}</label>
          <span className="nir-unitline">{canonTxt}</span>
        </div>
        <div className={`nir-control ${cls}`}>
          <input
            id={`in_${id}`}
            type="number"
            step="any"
            inputMode="decimal"
            value={st.value}
            onChange={(e) => updateField(id, e.target.value)}
            aria-invalid={!!st.error}
            aria-describedby={msg ? msgId : undefined}
          />
          {f.dom === "cur" && <span className="nir-prefix">{curSym}</span>}
          {f.dom === "pct" && <span className="nir-prefix" style={{ borderLeft: "1px solid var(--nir-line)", borderRight: "none" }}>%</span>}
          {f.units && (
            <select
              aria-label={`Unit for ${f.label}`}
              value={st.unit}
              onChange={(e) => updateFieldUnit(id, e.target.value)}
              style={{ borderLeft: "1px solid var(--nir-line)", background: "var(--nir-panel)", fontFamily: "var(--nir-mono)", fontSize: "14px", padding: "8px", minHeight: "48px", color: "var(--nir-ink)" }}
            >
              {f.units.map((u) => <option key={u.k} value={u.k}>{u.l}</option>)}
            </select>
          )}
        </div>
        <div className="nir-f-foot">
          <span className="nir-hint">{f.hint} <em style={{ fontStyle: "normal", color: "var(--nir-faint)" }}>· {f.src}</em></span>
          <span className="nir-bench-ref">{fmtRef(f, curSym)}</span>
        </div>
        {msg && <div id={msgId} className={`nir-msg ${msgCls}`} role={st.error ? "alert" : "status"}>{msg}</div>}
      </div>
    );
  };

  const renderReport = () => {
    if (!serverResult) return null;
    const s = serverResult.outputs;
    // Every key here is guaranteed present and finite — validated fail-closed
    // in handleGenerate before serverResult was ever set. No local fallback.
    const sealed: CapitalAppraisalOutputs = {
      out_npv: s.out_npv,
      out_irr: s.out_irr,
      out_payback_years: s.out_payback_years,
      out_discounted_payback_years: s.out_discounted_payback_years,
      out_profitability_index: s.out_profitability_index,
      out_decision: s.out_decision,
      out_irr_minus_hurdle: s.out_irr_minus_hurdle,
      out_terminal_pv: s.out_terminal_pv,
      out_evidence_completeness: s.out_evidence_completeness,
    };
    const rx = serverResult.inputs;
    const repCur = serverResult.currency;
    const sch = schedule(rx);
    const ins = buildInsights(rx, sealed, repCur);
    const seal = serverResult.seal.output_hash;
    const fmtMoney = (v: number) => repCur + fmt(v);
    const irrValid = sealed.out_irr > IRR_UNDEFINED + 1e-9;

    let cumDisc = -(rx.capex + rx.workingCapital);

    return (
      <div className="nir-report" ref={reportRef}>
        <div className="nir-rep-mast">
          <h2>Capital Equipment Investment Appraisal — proof report</h2>
          <div className="nir-rid">
            SC-PRO-NIR · {new Date().toISOString().slice(0, 10)}<br />
            engine v5.3.2-domain · discounted NPV + Newton-Raphson IRR<br />
            currency {repCur} · standard capital budgeting
          </div>
        </div>
        <div className="nir-rep-body">
          <div className="nir-sec">
            <div className={`nir-verdict-box ${sealed.out_decision === 1 ? "nir-verdict-accept" : "nir-verdict-reject"}`}>
              <div className="nir-head">{sealed.out_decision === 1 ? "Recommendation: Accept." : "Recommendation: Reject."}</div>
              <p>Over a {sch.years}-year horizon at a {(100 * rx.discountRate).toFixed(1)}% discount rate, this investment has an NPV of <strong>{fmtMoney(sealed.out_npv)}</strong> and an IRR of <strong>{irrValid ? (100 * sealed.out_irr).toFixed(1) + "%" : "undefined"}</strong>.</p>
              <p>Profitability Index <strong>{sealed.out_profitability_index.toFixed(2)}</strong> · Simple payback <strong>{sealed.out_payback_years < NO_PAYBACK_YEARS ? sealed.out_payback_years.toFixed(1) + " yr" : "never"}</strong> · Discounted payback <strong>{sealed.out_discounted_payback_years < NO_PAYBACK_YEARS ? sealed.out_discounted_payback_years.toFixed(1) + " yr" : "never"}</strong>.</p>
            </div>
          </div>

          <div className="nir-sec">
            <div className="nir-sec-h"><span className="nir-sec-n">1</span><span className="nir-sec-t">Annual cash flow schedule</span></div>
            <table>
              <thead><tr><th>Year</th><th style={{ textAlign: "right" }}>Nominal CF {repCur}</th><th style={{ textAlign: "right" }}>Discounted CF {repCur}</th><th style={{ textAlign: "right" }}>Cumulative discounted {repCur}</th></tr></thead>
              <tbody>
                <tr><td>0 (outlay)</td><td className="nir-n">−{fmt(rx.capex + rx.workingCapital)}</td><td className="nir-n">−{fmt(rx.capex + rx.workingCapital)}</td><td className="nir-n">−{fmt(rx.capex + rx.workingCapital)}</td></tr>
                {sch.rows.map((row) => {
                  const disc = row.total / Math.pow(1 + rx.discountRate, row.year);
                  cumDisc += disc;
                  return (
                    <tr key={row.year}>
                      <td>{row.year}</td>
                      <td className="nir-n">{fmt(row.total)}</td>
                      <td className="nir-n">{fmt(disc)}</td>
                      <td className="nir-n">{fmt(cumDisc)}</td>
                    </tr>
                  );
                })}
                <tr className="nir-total"><td>NPV (discounted)</td><td colSpan={2}></td><td className="nir-n">{fmt(sealed.out_npv)}</td></tr>
              </tbody>
            </table>
            <div className="nir-note">Cash flow grows at {(100 * rx.cashFlowGrowthRate).toFixed(1)}%/yr from year 1; year {sch.years} includes the residual value and recovered working capital.</div>
          </div>

          <div className="nir-sec">
            <div className="nir-sec-h"><span className="nir-sec-n">2</span><span className="nir-sec-t">NPV vs. discount rate — where IRR comes from</span></div>
            <div dangerouslySetInnerHTML={{ __html: chartNpvVsRate(rx, sealed, repCur) }} />
            <div className="nir-note">IRR is the discount rate where this curve crosses zero — not an assumed number. The dashed line marks your hurdle rate.</div>
          </div>

          <div className="nir-sec">
            <div className="nir-sec-h"><span className="nir-sec-n">3</span><span className="nir-sec-t">Payback — simple vs. discounted</span></div>
            <div dangerouslySetInnerHTML={{ __html: chartPayback(rx, repCur) }} />
            <div className="nir-note">Where each line crosses zero is the payback point. The discounted line (accounting for the time value of money) always crosses later.</div>
          </div>

          <div className="nir-sec">
            <div className="nir-sec-h"><span className="nir-sec-n">4</span><span className="nir-sec-t">Sensitivity — what moves the NPV</span></div>
            <div dangerouslySetInnerHTML={{ __html: chartTornado(rx, repCur) }} />
            <div className="nir-note">NPV swing at the hurdle rate when each input is stressed ±15%.</div>
          </div>

          <div className="nir-sec">
            <div className="nir-sec-h"><span className="nir-sec-n">5</span><span className="nir-sec-t">Engineering insights</span></div>
            {ins.map((i, k) => (
              <div className={`nir-ins nir-${i.sev}`} key={k}>
                <span className="nir-t">{i.t}</span>
                <span dangerouslySetInnerHTML={{ __html: i.msg }} />
              </div>
            ))}
          </div>

          <div className="nir-seal">
            SEAL · {serverResult.seal.hash_algorithm} {seal}<br />
            Sealed server-side at {serverResult.seal.executed_at ?? "—"}.
          </div>
          <button
            type="button"
            className="nir-print-btn"
            onClick={() => window.print()}
            aria-label="Download this report as a PDF"
          >
            Download PDF
          </button>
          <div className="nir-disc">
            Technical simulation only; not financial, legal, or engineering advice. Users must verify results before making business decisions.
          </div>
          <PremiumReportFeedback
            key={serverResult.seal.output_hash}
            schemaSlug={TOOL_KEY}
            sectorSlug="finance"
            reportSlug={serverResult.seal.output_hash}
            inputSnapshot={{ ...rx }}
            resultSnapshot={s}
            currency={repCur}
          />
        </div>
      </div>
    );
  };

  return (
    <div className="nir-shell">
      <div className="nir-mast">
        <div className="nir-kicker">SectorCalc PRO · Capital Investment · Accept/reject decision</div>
        <h1>Capital Equipment Investment Appraisal — NPV/IRR</h1>
        <p className="nir-lede">Standard capital budgeting appraisal: discounted NPV, Newton-Raphson IRR, simple and discounted payback, and a profitability index — all computed from a single cash-flow model, not assumed.</p>
        <div className="nir-meta">
          <span>Engine <b>v5.3.2-domain</b></span>
          <span>Method <b>discounted NPV + IRR</b></span>
          <span>Report <b>sealed · SHA-256</b></span>
        </div>
        <div className="nir-curbar">
          <label htmlFor="nir-curSel">Report currency</label>
          <select id="nir-curSel" value={curSym} onChange={(e) => setCurSym(e.target.value)}>
            {CURRENCIES.map((c) => <option key={c.code} value={c.sym}>{c.code} · {c.sym}</option>)}
          </select>
          <span className="nir-curnote">Symbol only — no exchange-rate conversion. Enter every figure in the same currency.</span>
        </div>
      </div>

      <div className="nir-bench">
        <div className="nir-form-col">
          {[1, 2, 3].map((g) => (
            <div className="nir-grp" key={g}>
              <div className="nir-grp-h"><span className="nir-grp-n">{GROUPS[g].n}</span><span className="nir-grp-t">{GROUPS[g].t}</span></div>
              <div className="nir-grp-d">{GROUPS[g].d}</div>
              {Object.keys(FIELDS).filter((id) => FIELDS[id].grp === g).map(renderField)}
            </div>
          ))}
        </div>
        <div className="nir-rail">
          <div className="nir-rail-in">
            <div className="nir-verdict">
              <div className={`nir-verdict-band ${r ? (r.out_decision === 1 ? "nir-pos" : "nir-neg") : "nir-warn"}`}>
                {r ? (r.out_decision === 1 ? "accept" : "reject") : "incomplete"}
              </div>
              <div className="nir-verdict-body">
                <div className="nir-big">{r ? <>{curSym}{fmt(r.out_npv)} <small>NPV</small></> : "—"}</div>
                <div className="nir-big-cap">
                  {r
                    ? `IRR ${irrValidLive ? (100 * r.out_irr).toFixed(1) + "%" : "undefined"} · PI ${r.out_profitability_index.toFixed(2)}`
                    : errorCount ? `${errorCount} input(s) need attention` : "enter investment data to begin"}
                </div>
              </div>
            </div>
            <div className="nir-stat"><span>Simple payback</span><b>{r ? (r.out_payback_years < NO_PAYBACK_YEARS ? `${r.out_payback_years.toFixed(1)} yr` : "never") : "—"}</b></div>
            <div className="nir-stat"><span>Discounted payback</span><b>{r ? (r.out_discounted_payback_years < NO_PAYBACK_YEARS ? `${r.out_discounted_payback_years.toFixed(1)} yr` : "never") : "—"}</b></div>
            <div className="nir-stat"><span>IRR margin over hurdle</span><b>{r && irrValidLive ? `${(100 * r.out_irr_minus_hurdle).toFixed(1)} pts` : "—"}</b></div>
            <div className="nir-stat"><span>Terminal value (PV)</span><b>{r ? curSym + fmt(r.out_terminal_pv) : "—"}</b></div>

            {!usageSessionId ? (
              <button className="nir-cta" disabled={sessionLoading || !canGenerate} onClick={requestSession}>
                {sessionLoading ? "Checking credits…" : "Unlock sealed report · 1 credit"}
              </button>
            ) : (
              <button className="nir-cta" disabled={!canGenerate || isExecuting} onClick={handleGenerate}>
                {isExecuting ? "Generating…" : "Generate sealed report"}
              </button>
            )}
            {remainingRuns != null && usageSessionId !== BYPASS_SESSION_ID && (
              <div className="nir-conf">{remainingRuns} run(s) remaining this session.</div>
            )}
            {sessionError && <div className="nir-conf" style={{ color: "var(--nir-neg)" }}>{sessionError}</div>}
            {executeError && <div className="nir-conf" style={{ color: "var(--nir-neg)" }}>{executeError}</div>}
            <div className="nir-conf">
              <span className="nir-d" style={{ background: r ? (r.out_decision === 1 ? "var(--nir-pos)" : "var(--nir-neg)") : "var(--nir-warn)" }} />
              <span>{r ? `Inputs consistent · profitability index ${r.out_profitability_index.toFixed(2)}` : errorCount ? "Fix highlighted inputs." : "Enter inputs to compute."}</span>
            </div>
          </div>
        </div>
      </div>

      {serverResult && renderReport()}
    </div>
  );
}
