import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "../..");
const P24_CACHE_PATH = path.join(ROOT, "scripts/.cache/p24-tool-quality-report.json");
const P24_VERDICTS_TS = path.join(ROOT, "src/lib/tools/runtime-readiness-p24-verdicts.ts");

function loadP24Maps(): { nonPass: Record<string, string>; explicitPass: string[] } {
  if (!fs.existsSync(P24_CACHE_PATH)) {
    return { nonPass: {}, explicitPass: [] };
  }
  const report = JSON.parse(fs.readFileSync(P24_CACHE_PATH, "utf8")) as {
    tools?: Array<{ slug: string; verdict: string }>;
    items?: Array<{ slug: string; verdict: string }>;
  };
  const verdictRank: Record<string, number> = {
    PASS: 0,
    WARN: 1,
    QUARANTINE: 2,
    FAIL: 3,
  };
  const mergedVerdicts: Record<string, string> = {};
  const rows = report.tools ?? report.items ?? [];
  for (const item of rows) {
    if (!item.verdict) {
      continue;
    }
    const current = mergedVerdicts[item.slug];
    if (!current || verdictRank[item.verdict] > verdictRank[current]) {
      mergedVerdicts[item.slug] = item.verdict;
    }
  }

  const nonPass: Record<string, string> = {};
  const explicitPass: string[] = [];
  for (const [slug, verdict] of Object.entries(mergedVerdicts)) {
    if (verdict === "PASS") {
      explicitPass.push(slug);
    } else {
      nonPass[slug] = verdict;
    }
  }
  return { nonPass, explicitPass: explicitPass.sort((a, b) => a.localeCompare(b)) };
}

function writeP24VerdictsFile(nonPass: Record<string, string>, explicitPass: string[]): void {
  const nonPassEntries = Object.entries(nonPass)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([slug, verdict]) => `  "${slug}": "${verdict}",`)
    .join("\n");

  const passEntries = explicitPass.map((slug) => `  "${slug}",`).join("\n");

  const content = `/**
 * P2.4 verdict cache for runtime readiness / trust gate.
 * Regenerated by: node scripts/tool-activation/audit-runtime-trust-engine.mjs
 * Non-PASS slugs block Formula Gate Approved badge.
 */

export type P24AuditVerdict = "PASS" | "WARN" | "FAIL" | "QUARANTINE";

/** Slugs with P2.4 verdict !== PASS (generated snapshot). */
export const P24_NON_PASS_VERDICTS: Readonly<Record<string, P24AuditVerdict>> = {
${nonPassEntries}
};

/** Slugs with explicit P2.4 PASS — required for Formula Gate trust eligibility. */
export const P24_EXPLICIT_PASS_SLUGS: ReadonlySet<string> = new Set([
${passEntries}
]);

export function getP24VerdictForSlug(slug: string): P24AuditVerdict | "PASS" {
  return P24_NON_PASS_VERDICTS[slug] ?? "PASS";
}

export function isP24PassForSlug(slug: string): boolean {
  return getP24VerdictForSlug(slug) === "PASS";
}

/** Stricter trust gate — unknown / unaudited slugs are not eligible. */
export function isP24TrustPassForSlug(slug: string): boolean {
  if (P24_NON_PASS_VERDICTS[slug]) {
    return false;
  }
  return P24_EXPLICIT_PASS_SLUGS.has(slug);
}
`;

  fs.writeFileSync(P24_VERDICTS_TS, content, "utf8");
}

function main(): void {
  const { nonPass, explicitPass } = loadP24Maps();
  writeP24VerdictsFile(nonPass, explicitPass);
  console.log("audit:runtime-trust-engine phase 1 PASS");
  console.log(`regenerated: ${path.relative(ROOT, P24_VERDICTS_TS)}`);
  console.log(`explicitPass: ${explicitPass.length}, nonPass: ${Object.keys(nonPass).length}`);
}

main();
