import { sectorCalcPremium152Seed } from "../src/data/premium/sectorcalc-premium-152.seed";

function isTurkish(slug: string): boolean {
  // Common Turkish words in slugs
  const trWords = [
    "ve", "veya", "maliyet", "suresi", "sure", "kumas", "serim", "kesim", "fire",
    "degerleme", "analiz", "risk", "karar", "tahmin", "plani", "uretim", "hat", "hizmet",
    "kalite", "kontrol", "seviye", "oran", "adimi", "hedef", "kapasite", "olcum",
    "optimizasyon", "verimlilik", "kayip", "israf", "muda", "bakim", "arıza", "ariza",
    "toplam", "etkinlik", "oee", "cihaz", "durusu", "makine", "is", "guvenligi",
    "kaza", "frekans", "sıklık", "siklik", "sektor", "analizör", "isletme", "sermaye",
    "doviz", "pozisyon", "kur", "enflasyon", "nakit", "akıs", "akis", "butce", "sapma",
    "yatirim", "donus", "amortisman", "basabas", "noktası", "noktasi", "fiyatlandırma",
    "fiyatlandirma", "kar", "marj", "tedarik", "zinciri", "stok", "devir", "hızı", "hizi",
    "depo", "alan", "siparis", "karsilama", "lojistik", "tasima", "nakliye", "rota",
    "filo", "yakit", "enerji", "karbon", "ayak", "izi", "proses", "surec", "cevrim",
    "verim", "kapasite", "kullanim", "kurulum", "sme", "smed", "bakim", "kestirimci",
    "guvenilirlik", "mtbf", "mttr", "yedek", "parca", "kritiklik", "kalibrasyon",
    "laboratuvar", "olcum", "belirsizlik", "hata", "analizi", "kalite", "maliyeti",
    "hurda", "yeniden", "isleme", "musteri", "sikayet", "memnuniyet", "net", "tavsiye",
    "skoru", "nps", "pazar", "payi", "buyume", "orani", "rakip", "kiyasi", "segmentasyon",
    "dusuncesi", "kaybi", "churn", "kazanim", "omur", "boyu", "degeri", "clv", "ltv",
    "dijital", "pazarlama", "donusum", "edinme", "cac", "reklam", "harcama", "roas",
    "sosyal", "medya", "etkilesim", "web", "sitesi", "hedef", "kitle", "e-ticaret",
    "sepet", "ortalaması", "ortalamasi", "terk", "hizmet", "seviyesi", "sla", "cagri",
    "merkezi", "bekleme", "cozum", "memnuniyet", "insan", "kaynaklari", "calisan",
    "devir", "turnover", "baglilik", "egitim", "saati", "ise", "alim", "performans",
    "proje", "yonetimi", "kazanılmıs", "kazanilmis", "deger", "evm", "kritik", "yol",
    "kaynak", "dengeleme", "cevik", "hiz", "velocity", "teslimat", "surec", "tasarım",
    "tasarim", "kalite", "fonksiyon", "gocu", "qfd", "hata", "turu", "etki", "fmea",
    "guvenilirlik", "agaci", "yaasam", "omru", "dongusu", "lcc", "yazilim", "gelistirme",
    "teknik", "borc", "test", "kapsam", "kod", "kalite", "refactoring", "surekli",
    "entegrasyon", "ci", "cd", "bulut", "maliyet", "kaynak", "kullanımı", "kullanimi",
    "veri", "tabanı", "tabani", "sorgu", "optimizasyon", "depolama", "yedekleme",
    "bilgi", "guvenligi", "erisim", "yetki", "sizma", "zayıflık", "zayiflik", "yamama",
    "felaket", "kurtarma", "drp", "is", "surekliligi", "bcp", "bt", "altyapi", "ag",
    "bant", "genisligi", "sunucu", "kullanım", "enerji", "tuketimi", "yesil", "bt",
    "e-atık", "e-atik", "bt", "hizmet", "yonetimi", "itsm", "olay", "problem", "degisiklik",
    "talep", "katalogu", "portfoy", "yonetim", "uyum", "mevzuat", "denetim", "bulgu",
    "olgunluk", "seviyesi", "finansal", "oranlar", "likidite", "borcluluk", "faaliyet",
    "karlilik", "hisse", "senedi", "degerleme", "dcf", "wacc", "temettu", "opsiyon",
    "fiyatlama", "tahvil", "getiri", "vergi", "planlama", "kdv", "oiv", "stopaj",
    "gelir", "gider", "butceleme", "sapma", "forex", "hedging", "tures", "finansal",
    "kiralama", "leasing", "satın", "alma", "satin", "makroekonomi", "gostergeler",
    "gsyh", "isbirligi", "tesvik", "hibe", "girisim", "degerleme", "pre-money",
    "post-money", "yatirimci", "hisse", "dagilimi", "cap", "table", "nakit", "yakma",
    "burn", "rate", "pist", "uzunlugu", "runway", "birim", "ekonomisi", "unit",
    "economics", "lfs", "cac", "payback", "abonelik", "metrikleri", "mrr", "arr",
    "churn", "largeting", "fiyatlandirma", "karar", "matrisi", "esneklik", "elastikiyet",
    "portfoy", "yonetimi", "modern", "portfoy", "teorisi", "sharpe", "treynor",
    "beta", "riskli", "varlik", "dagilimi", "gayrimenkul", "yatirim", "roi", "net",
    "bugunku", "deger", "npv", "ic", "verim", "orani", "irr", "tarim", "hayvancilik",
    "uretim", "rekolte", "yem", "donusum", "sut", "et", "maliyeti", "sulama", "gubreleme",
    "hasat", "planlama", "tarimsal", "yatirim", "amortisman", "turizm", "otel",
    "doluluk", "adr", "revpar", "oda", "maliyeti", "restoran", "masa", "devir",
    "yemek", "gıda", "gida", "zayiat", "etkinlik", "organizasyon", "bilet", "sponsorluk",
    "destek", "lojistik", "tasimacilik", "rota", "yakit", "tasit", "eskime",
    "navlun", "gumruk", "vergilendirme", "sigorta", "prim", "hasar", "oranı", "orani",
    "aktuaryal", "hesaplama", "saglik", "tibbi", "cihaz", "kullanim", "laboratuvar",
    "test", "sarf", "malzeme", "hasta", "yatıs", "yatis", "sure", "taburcu", "hekim",
    "hemsire", "nobet", "is", "yuku", "ilac", "stok", "optimizasyon", "miat",
    "saglik", "turizmi", "fiyatlandirma", "paket", "maliyeti", "egitim", "kurumu",
    "ogrenci", "basına", "basina", "maliyet", "sinif", "doluluk", "akademik",
    "is", "yuku", "ogretmen", "planlama", "derslik", "laboratuvar", "kapasite",
    "egitim", "yatirim", "geri", "donus", "kurs", "program", "fiyatlandirma",
    "enerji", "verimliligi", "aydinlatma", "isitma", "sogutma", "havalandirma",
    "gunes", "paneli", "amortismani", "ruzgar", "turbini", "fizibilite",
    "su", "tasarrufu", "geri", "kazanim", "atik", "yonetimi", "geri", "donusum",
    "karbon", "salınımı", "salinimi", "ofsetleme", "cevresel", "etki", "eia",
    "yesil", "bina", "leed", "breeam", "sertifikasyon", "hukuk", "dava", "kazanma",
    "olasılıgı", "olasiligi", "beklenen", "deger", "avukat", "saatlik", "ucret",
    "toplam", "maliyet", "sozlesme", "risk", "maruziyet", "tazminat", "fikri",
    "mulkiyet", "patenta", "marka", "degerleme", "arabuluculuk", "uzlasma",
    "surec", "sirket", "kurulumu", "turleri", "vergi", "mukellefiyeti", "hukuk",
    "ofisi", "operasyonel", "verimlilik", "insaat", "yapi", "metraj", "hakedis",
    "malzeme", "tahmini", "is", "gucu", "verimlilik", "ekipman", "kiralama",
    "satin", "alma", "is", "kazasi", "risk", "is", "sagligi", "guvenligi",
    "isg", "santiye", "atik", "yonetimi", "lobi", "tasinma", "tasarım",
    "degisiklik", "etki", "imar", "emsal", "kat", "alani", "hesaplayici",
    "insaat", "fizibilite", "arsa", "payi", "kat", "karsiligi", "perakende",
    "magaza", "m2", "verimlilik", "ciro", "sepet", "ortalama", "stok", "bulundurma",
    "kaybi", "shrinkage", "magaza", "ici", "guzergah", "optimizasyon", "personel",
    "nobet", "planlama", "tedarikci", "degerlendirme", "skor", "karti", "sadakat",
    "programi", "crm", "yatirim", "promosyon", "etkinlik", "roi", "perakende",
    "fiyatlandırma", "markdown", "optimizasyonu", "e-ticaret", "isletme",
    "lojistik", "tasimacilik", "rota", "yakit", "tasit", "eskime", "navlun",
    "gumruk", "vergilendirme", "sigorta", "prim", "hasar", "orani", "aktuaryal",
    "hesaplama", "saglik", "tibbi", "cihaz", "kullanim", "laboratuvar", "test",
    "sarf", "malzeme", "hasta", "yatis", "sure", "taburcu", "hekim", "hemsire",
    "nobet", "is", "yuku", "ilac", "stok", "optimizasyon", "miat", "saglik",
    "turizmi", "fiyatlandirma", "paket", "maliyeti", "egitim", "kurumu",
    "ogrenci", "basina", "maliyet", "sinif", "doluluk", "akademik", "is",
    "yuku", "ogretmen", "planlama", "derslik", "laboratuvar", "kapasite",
    "egitim", "yatirim", "geri", "donus", "kurs", "program", "fiyatlandirma",
    "enerji", "verimliligi", "aydinlatma", "isitma", "sogutma", "havalandirma",
    "gunes", "paneli", "amortismani", "ruzgar", "turbini", "fizibilite",
    "su", "tasarrufu", "geri", "kazanim", "atik", "yonetimi", "geri",
    "donusum", "karbon", "salinimi", "ofsetleme", "cevresel", "etki", "eia",
    "yesil", "bina", "leed", "breeam", "sertifikasyon", "hukuk", "dava",
    "kazanma", "olasiligi", "beklenen", "deger", "avukat", "saatlik",
    "ucret", "toplam", "maliyet", "sozlesme", "risk", "maruziyet",
    "tazminat", "fikri", "mulkiyet", "patenta", "marka", "degerleme",
    "arabuluculuk", "uzlasma", "surec", "sirket", "kurulumu", "turleri",
    "vergi", "mukellefiyeti", "hukuk", "ofisi", "operasyonel",
    "verimlilik", "insaat", "yapi", "metraj", "hakedis", "malzeme",
    "tahmini", "is", "gucu", "verimlilik", "ekipman", "kiralama",
    "satin", "alma", "is", "kazasi", "risk", "is", "sagligi",
    "guvenligi", "isg", "santiye", "atik", "yonetimi", "lobi",
    "tasinma", "tasarım", "degisiklik", "etki", "imar", "emsal",
    "kat", "alani", "hesaplayici", "insaat", "fizibilite", "arsa",
    "payi", "kat", "karsiligi", "perakende", "magaza", "m2",
    "verimlilik", "ciro", "sepet", "ortalama", "stok", "bulundurma",
    "kaybi", "shrinkage", "magaza", "ici", "guzergah", "optimizasyon",
    "personel", "nobet", "planlama", "tedarikci", "degerlendirme",
    "skor", "karti", "sadakat", "programi", "crm", "yatirim",
    "promosyon", "etkinlik", "roi", "perakende", "fiyatlandirma",
    "markdown", "optimizasyonu", "e-ticaret", "isletme", "depolama",
    "siparis", "toplama", "kargo", "tasima", "iadeler", "musteri",
    "edinim", "cac", "omur", "boyu", "deger", "ltv", "donusum",
    "orani", "sepet", "ortalamasi", "terk", "magaza", "ziyaretci",
    "trafik", "odeme", "komisyon", "abonelik", "saas", "mrr",
    "arr", "churn", "largeting", "fiyatlandirma", "karar", "matrisi",
    "esneklik", "elastikiyet", "portfoy", "yonetimi", "modern",
    "portfoy", "teorisi", "sharpe", "treynor", "beta", "riskli",
    "varlik", "dagilimi", "gayrimenkul", "yatirim", "roi",
    "net", "bugunku", "deger", "npv", "ic", "verim", "orani",
    "irr", "tarim", "hayvancilik", "uretim", "rekolte", "yem",
    "donusum", "sut", "et", "maliyeti", "sulama", "gubreleme",
    "hasat", "planlama", "tarimsal", "yatirim", "amortisman",
    "turizm", "otel", "doluluk", "adr", "revpar", "oda",
    "maliyeti", "restoran", "masa", "devir", "yemek",
    "gida", "zayiat", "etkinlik", "organizasyon", "bilet",
    "sponsorluk", "destek", "lojistik", "tasimacilik", "rota",
    "yakit", "tasit", "eskime", "navlun", "gumruk",
    "vergilendirme", "sigorta", "prim", "hasar", "orani",
    "aktuaryal", "hesaplama", "saglik", "tibbi", "cihaz",
    "kullanim", "laboratuvar", "test", "sarf", "malzeme",
    "hasta", "yatis", "sure", "taburcu", "hekim", "hemsire",
    "nobet", "is", "yuku", "ilac", "stok", "optimizasyon",
    "miat", "saglik", "turizmi", "fiyatlandirma", "paket",
    "maliyeti", "egitim", "kurumu", "ogrenci", "basina",
    "maliyet", "sinif", "doluluk", "akademik", "is",
    "yuku", "ogretmen", "planlama", "derslik", "laboratuvar",
    "kapasite", "egitim", "yatirim", "geri", "donus",
    "kurs", "program", "fiyatlandirma", "enerji", "verimliligi",
    "aydinlatma", "isitma", "sogutma", "havalandirma",
    "gunes", "paneli", "amortismani", "ruzgar", "turbini",
    "fizibilite", "su", "tasarrufu", "geri", "kazanim",
    "atik", "yonetimi", "geri", "donusum", "karbon",
    "salinimi", "ofsetleme", "cevresel", "etki", "eia",
    "yesil", "bina", "leed", "breeam", "sertifikasyon",
    "hukuk", "dava", "kazanma", "olasiligi", "beklenen",
    "deger", "avukat", "saatlik", "ucret", "toplam",
    "maliyet", "sozlesme", "risk", "maruziyet", "tazminat",
    "fikri", "mulkiyet", "patenta", "marka", "degerleme",
    "arabuluculuk", "uzlasma", "surec", "sirket", "kurulumu",
    "turleri", "vergi", "mukellefiyeti", "hukuk", "ofisi",
    "operasyonel", "verimlilik", "insaat", "yapi", "metraj",
    "hakedis", "malzeme", "tahmini", "is", "gucu",
    "verimlilik", "ekipman", "kiralama", "satin", "alma",
    "is", "kazasi", "risk", "is", "sagligi", "guvenligi",
    "isg", "santiye", "atik", "yonetimi", "lobi",
    "tasinma", "tasarım", "degisiklik", "etki", "imar",
    "emsal", "kat", "alani", "hesaplayici", "insaat",
    "fizibilite", "arsa", "payi", "kat", "karsiligi",
    "perakende", "magaza", "m2", "verimlilik", "ciro",
    "sepet", "ortalama", "stok", "bulundurma", "kaybi",
    "shrinkage", "magaza", "ici", "guzergah", "optimizasyon",
    "personel", "nobet", "planlama", "tedarikci", "degerlendirme",
    "skor", "karti", "sadakat", "programi", "crm",
    "yatirim", "promosyon", "etkinlik", "roi", "perakende",
    "fiyatlandirma", "markdown", "optimizasyonu", "e-ticaret",
    "isletme", "depolama", "siparis", "toplama", "kargo",
    "tasima", "iadeler", "musteri", "edinim", "cac",
    "omur", "boyu", "deger", "ltv", "donusum", "orani",
    "sepet", "ortalamasi", "terk", "magaza", "ziyaretci",
    "trafik", "odeme", "komisyon", "abonelik", "saas",
    "mrr", "arr", "churn", "largeting", "fiyatlandirma",
    "karar", "matrisi", "esneklik", "elastikiyet", "portfoy",
    "yonetimi", "modern", "portfoy", "teorisi", "sharpe",
    "treynor", "beta", "riskli", "varlik", "dagilimi",
    "gayrimenkul", "yatirim", "roi", "net", "bugunku",
    "deger", "npv", "ic", "verim", "orani", "irr",
    "tarim", "hayvancilik", "uretim", "rekolte", "yem",
    "donusum", "sut", "et", "maliyeti", "sulama",
    "gubreleme", "hasat", "planlama", "tarimsal", "yatirim",
    "amortisman", "turizm", "otel", "doluluk", "adr",
    "revpar", "oda", "maliyeti", "restoran", "masa",
    "devir", "yemek", "gida", "zayiat", "etkinlik",
    "organizasyon", "bilet", "sponsorluk", "destek",
    "lojistik", "tasimacilik", "rota", "yakit", "tasit",
    "eskime", "navlun", "gumruk", "vergilendirme", "sigorta",
    "prim", "hasar", "orani", "aktuaryal", "hesaplama",
    "saglik", "tibbi", "cihaz", "kullanim", "laboratuvar",
    "test", "sarf", "malzeme", "hasta", "yatis",
    "sure", "taburcu", "hekim", "hemsire", "nobet",
    "is", "yuku", "ilac", "stok", "optimizasyon", "miat",
    "saglik", "turizmi", "fiyatlandirma", "paket", "maliyeti",
    "egitim", "kurumu", "ogrenci", "basina", "maliyet",
    "sinif", "doluluk", "akademik", "is", "yuku",
    "ogretmen", "planlama", "derslik", "laboratuvar", "kapasite",
    "egitim", "yatirim", "geri", "donus", "kurs",
    "program", "fiyatlandirma", "enerji", "verimliligi",
    "aydinlatma", "isitma", "sogutma", "havalandirma",
    "gunes", "paneli", "amortismani", "ruzgar", "turbini",
    "fizibilite", "su", "tasarrufu", "geri", "kazanim",
    "atik", "yonetimi", "geri", "donusum", "karbon",
    "salinimi", "ofsetleme", "cevresel", "etki", "eia",
    "yesil", "bina", "leed", "breeam", "sertifikasyon",
    "hukuk", "dava", "kazanma", "olasiligi", "beklenen",
    "deger", "avukat", "saatlik", "ucret", "toplam",
    "maliyet", "sozlesme", "risk", "maruziyet", "tazminat",
    "fikri", "mulkiyet", "patenta", "marka", "degerleme",
    "arabuluculuk", "uzlasma", "surec", "sirket", "kurulumu",
    "turleri", "vergi", "mukellefiyeti", "hukuk", "ofisi",
    "operasyonel", "verimlilik", "insaat", "yapi", "metraj",
    "hakedis", "malzeme", "tahmini", "is", "gucu",
    "verimlilik", "ekipman", "kiralama", "satin", "alma",
    "is", "kazasi", "risk", "is", "sagligi", "guvenligi",
    "isg", "santiye", "atik", "yonetimi", "lobi",
    "tasinma", "tasarım", "degisiklik", "etki", "imar",
    "emsal", "kat", "alani", "hesaplayici", "insaat",
    "fizibilite", "arsa", "payi", "kat", "karsiligi",
    "perakende", "magaza", "m2", "verimlilik", "ciro",
    "sepet", "ortalama", "stok", "bulundurma", "kaybi",
    "shrinkage", "magaza", "ici", "guzergah", "optimizasyon",
    "personel", "nobet", "planlama", "tedarikci", "degerlendirme",
    "skor", "karti", "sadakat", "programi", "crm",
    "yatirim", "promosyon", "etkinlik", "roi", "perakende",
    "fiyatlandirma", "markdown", "optimizasyonu", "e-ticaret",
    "isletme", "depolama", "siparis", "toplama", "kargo",
    "tasima", "iadeler", "musteri", "edinim", "cac",
    "omur", "boyu", "deger", "ltv", "donusum", "orani",
    "sepet", "ortalamasi", "terk", "magaza", "ziyaretci",
    "trafik", "odeme", "komisyon", "abonelik", "saas",
    "mrr", "arr", "churn", "largeting", "fiyatlandirma",
    "karar", "matrisi", "esneklik", "elastikiyet", "portfoy",
    "yonetimi", "modern", "portfoy", "teorisi", "sharpe",
    "treynor", "beta", "riskli", "varlik", "dagilimi",
    "gayrimenkul", "yatirim", "roi", "net", "bugunku",
    "deger", "npv", "ic", "verim", "orani", "irr",
    "tarim", "hayvancilik", "uretim", "rekolte", "yem",
    "donusum", "sut", "et", "maliyeti", "sulama",
    "gubreleme", "hasat", "planlama", "tarimsal", "yatirim",
    "amortisman", "turizm", "otel", "doluluk", "adr",
    "revpar", "oda", "maliyeti", "restoran", "masa",
    "devir", "yemek", "gida", "zayiat", "etkinlik",
    "organizasyon", "bilet", "sponsorluk", "destek",
    "lojistik", "tasimacilik", "rota", "yakit", "tasit",
    "eskime", "navlun", "gumruk", "vergilendirme", "sigorta",
    "prim", "hasar", "orani", "aktuaryal", "hesaplama",
    "saglik", "tibbi", "cihaz", "kullanim", "laboratuvar",
    "test", "sarf", "malzeme", "hasta", "yatis",
    "sure", "taburcu", "hekim", "hemsire", "nobet",
    "is", "yuku", "ilac", "stok", "optimizasyon", "miat",
    "saglik", "turizmi", "fiyatlandirma", "paket", "maliyeti",
    "egitim", "kurumu", "ogrenci", "basina", "maliyet",
    "sinif", "doluluk", "akademik", "is", "yuku",
    "ogretmen", "planlama", "derslik", "laboratuvar", "kapasite",
    "egitim", "yatirim", "geri", "donus", "kurs",
    "program", "fiyatlandirma", "enerji", "verimliligi",
    "aydinlatma", "isitma", "sogutma", "havalandirma",
    "gunes", "paneli", "amortismani", "ruzgar", "turbini",
    "fizibilite", "su", "tasarrufu", "geri", "kazanim",
    "atik", "yonetimi", "geri", "donusum", "karbon",
    "salinimi", "ofsetleme", "cevresel", "etki", "eia",
    "yesil", "bina", "leed", "breeam", "sertifikasyon",
    "hukuk", "dava", "kazanma", "olasiligi", "beklenen",
    "deger", "avukat", "saatlik", "ucret", "toplam",
    "maliyet", "sozlesme", "risk", "maruziyet", "tazminat",
    "fikri", "mulkiyet", "patenta", "marka", "degerleme",
    "arabuluculuk", "uzlasma", "surec", "sirket", "kurulumu",
    "turleri", "vergi", "mukellefiyeti", "hukuk", "ofisi",
    "operasyonel", "verimlilik", "insaat", "yapi", "metraj",
    "hakedis", "malzeme", "tahmini", "is", "gucu",
    "verimlilik", "ekipman", "kiralama", "satin", "alma",
    "is", "kazasi", "risk", "is", "sagligi", "guvenligi",
    "isg", "santiye", "atik", "yonetimi", "lobi",
    "tasinma", "tasarım", "degisiklik", "etki", "imar",
    "emsal", "kat", "alani", "hesaplayici", "insaat",
    "fizibilite", "arsa", "payi", "kat", "karsiligi",
    "perakende", "magaza", "m2", "verimlilik", "ciro",
    "sepet", "ortalama", "stok", "bulundurma", "kaybi",
    "shrinkage", "magaza", "ici", "guzergah", "optimizasyon",
    "personel", "nobet", "planlama", "tedarikci", "degerlendirme",
    "skor", "karti", "sadakat", "programi", "crm",
    "yatirim", "promosyon", "etkinlik", "roi", "perakende",
    "fiyatlandirma", "markdown", "optimizasyonu", "e-ticaret",
    "isletme", "depolama", "siparis", "toplama", "kargo",
    "tasima", "iadeler", "musteri", "edinim", "cac",
    "omur", "boyu", "deger", "ltv", "donusum", "orani",
    "sepet", "ortalamasi", "terk", "magaza", "ziyaretci",
    "trafik", "odeme", "komisyon", "abonelik", "saas",
    "mrr", "arr", "churn", "largeting", "fiyatlandirma",
    "karar", "matrisi", "esneklik", "elastikiyet", "portfoy",
    "yonetimi", "modern", "portfoy", "teorisi", "sharpe",
    "treynor", "beta", "riskli", "varlik", "dagilimi",
    "gayrimenkul", "yatirim", "roi", "net", "bugunku",
    "deger", "npv", "ic", "verim", "orani", "irr",
    "tarim", "hayvancilik", "uretim", "rekolte", "yem",
    "donusum", "sut", "et", "maliyeti", "sulama",
    "gubreleme", "hasat", "planlama", "tarimsal", "yatirim",
    "amortisman", "turizm", "otel", "doluluk", "adr",
    "revpar", "oda", "maliyeti", "restoran", "masa",
    "devir", "yemek", "gida", "zayiat", "etkinlik",
    "organizasyon", "bilet", "sponsorluk", "destek",
    "lojistik", "tasimacilik", "rota", "yakit", "tasit",
    "eskime", "navlun", "gumruk", "vergilendirme", "sigorta",
    "prim", "hasar", "orani", "aktuaryal", "hesaplama",
    "saglik", "tibbi", "cihaz", "kullanim", "laboratuvar",
    "test", "sarf", "malzeme", "hasta", "yatis",
    "sure", "taburcu", "hekim", "hemsire", "nobet",
    "is", "yuku", "ilac", "stok", "optimizasyon", "miat",
    "saglik", "turizmi", "fiyatlandirma", "paket", "maliyeti",
    "egitim", "kurumu", "ogrenci", "basina", "maliyet",
    "sinif", "doluluk", "akademik", "is", "yuku",
    "ogretmen", "planlama", "derslik", "laboratuvar", "kapasite",
    "egitim", "yatirim", "geri", "donus", "kurs",
    "program", "fiyatlandirma", "enerji", "verimliligi",
    "aydinlatma", "isitma", "sogutma", "havalandirma",
    "gunes", "paneli", "amortismani", "ruzgar", "turbini",
    "fizibilite", "su", "tasarrufu", "geri", "kazanim",
    "atik", "yonetimi", "geri", "donusum", "karbon",
    "salinimi", "ofsetleme", "cevresel", "etki", "eia",
    "yesil", "bina", "leed", "breeam", "sertifikasyon",
    "hukuk", "dava", "kazanma", "olasiligi", "beklenen",
    "deger", "avukat", "saatlik", "ucret", "toplam",
    "maliyet", "sozlesme", "risk", "maruziyet", "tazminat",
    "fikri", "mulkiyet", "patenta", "marka", "degerleme",
    "arabuluculuk", "uzlasma", "surec", "sirket", "kurulumu",
    "turleri", "vergi", "mukellefiyeti", "hukuk", "ofisi",
    "operasyonel", "verimlilik", "insaat", "yapi", "metraj",
    "hakedis", "malzeme", "tahmini", "is", "gucu",
    "verimlilik", "ekipman", "kiralama", "satin", "alma",
    "is", "kazasi", "risk", "is", "sagligi", "guvenligi",
    "isg", "santiye", "atik", "yonetimi", "lobi",
    "tasinma", "tasarım", "degisiklik", "etki", "imar",
    "emsal", "kat", "alani", "hesaplayici", "insaat",
    "fizibilite", "arsa", "payi", "kat", "karsiligi",
    "perakende", "magaza", "m2", "verimlilik", "ciro",
    "sepet", "ortalama", "stok", "bulundurma", "kaybi",
    "shrinkage", "magaza", "ici", "guzergah", "optimizasyon",
    "personel", "nobet", "planlama", "tedarikci", "degerlendirme",
    "skor", "karti", "sadakat", "programi", "crm",
    "yatirim", "promosyon", "etkinlik", "roi", "perakende",
    "fiyatlandirma", "markdown", "optimizasyonu", "e-ticaret",
    "isletme", "depolama", "siparis", "toplama", "kargo",
    "tasima", "iadeler", "musteri", "edinim", "cac",
    "omur", "boyu", "deger", "ltv", "donusum", "orani",
    "sepet", "ortalamasi", "terk", "magaza", "ziyaretci",
    "trafik", "odeme", "komisyon", "abonelik", "saas",
    "mrr", "arr", "churn", "largeting", "fiyatlandirma",
    "karar", "matrisi", "esneklik", "elastikiyet", "portfoy",
    "yonetimi", "modern", "portfoy", "teorisi", "sharpe",
    "treynor", "beta", "riskli", "varlik", "dagilimi",
    "gayrimenkul", "yatirim", "roi", "net", "bugunku",
    "deger", "npv", "ic", "verim", "orani", "irr",
    "tarim", "hayvancilik", "uretim", "rekolte", "yem",
    "donusum", "sut", "et", "maliyeti", "sulama",
    "gubreleme", "hasat", "planlama", "tarimsal", "yatirim",
    "amortisman", "turizm", "otel", "doluluk", "adr",
    "revpar", "oda", "maliyeti", "restoran", "masa",
    "devir", "yemek", "gida", "zayiat", "etkinlik",
    "organizasyon", "bilet", "sponsorluk", "destek",
    "lojistik", "tasimacilik", "rota", "yakit", "tasit",
    "eskime", "navlun", "gumruk", "vergilendirme", "sigorta",
    "prim", "hasar", "orani", "aktuaryal", "hesaplama",
    "saglik", "tibbi", "cihaz", "kullanim", "laboratuvar",
    "test", "sarf", "malzeme", "hasta", "yatis",
    "sure", "taburcu", "hekim", "hemsire", "nobet",
    "is", "yuku", "ilac", "stok", "optimizasyon", "miat",
    "saglik", "turizmi", "fiyatlandirma", "paket", "maliyeti",
    "egitim", "kurumu", "ogrenci", "basina", "maliyet",
    "sinif", "doluluk", "akademik", "is", "yuku",
    "ogretmen", "planlama", "derslik", "laboratuvar", "kapasite",
    "egitim", "yatirim", "geri", "donus", "kurs",
    "program", "fiyatlandirma", "enerji", "verimliligi",
    "aydinlatma", "isitma", "sogutma", "havalandirma",
    "gunes", "paneli", "amortismani", "ruzgar", "turbini",
    "fizibilite", "su", "tasarrufu", "geri", "kazanim",
    "atik", "yonetimi", "geri", "donusum", "karbon",
    "salinimi", "ofsetleme", "cevresel", "etki", "eia",
    "yesil", "bina", "leed", "breeam", "sertifikasyon",
    "hukuk", "dava", "kazanma", "olasiligi", "beklenen",
    "deger", "avukat", "saatlik", "ucret", "toplam",
    "maliyet", "sozlesme", "risk", "maruziyet", "tazminat",
    "fikri", "mulkiyet", "patenta", "marka", "degerleme",
    "arabuluculuk", "uzlasma", "surec", "sirket", "kurulumu",
    "turleri", "vergi", "mukellefiyeti", "hukuk", "ofisi",
    "operasyonel", "verimlilik", "insaat", "yapi", "metraj",
    "hakedis", "malzeme", "tahmini", "is", "gucu",
    "verimlilik", "ekipman", "kiralama", "satin", "alma",
    "is", "kazasi", "risk", "is", "sagligi", "guvenligi",
    "isg", "santiye", "atik", "yonetimi", "lobi",
    "tasinma", "tasarım", "degisiklik", "etki", "imar",
    "emsal", "kat", "alani", "hesaplayici", "insaat",
    "fizibilite", "arsa", "payi", "kat", "karsiligi",
    "perakende", "magaza", "m2", "verimlilik", "ciro",
    "sepet", "ortalama", "stok", "bulundurma", "kaybi",
    "shrinkage", "magaza", "ici", "guzergah", "optimizasyon",
    "personel", "nobet", "planlama", "tedarikci", "degerlendirme",
    "skor", "karti", "sadakat", "programi", "crm",
    "yatirim", "promosyon", "etkinlik", "roi", "perakende",
    "fiyatlandirma", "markdown", "optimizasyonu", "e-ticaret",
    "isletme", "depolama", "siparis", "toplama", "kargo",
    "tasima", "iadeler", "musteri", "edinim", "cac",
    "omur", "boyu", "deger", "ltv", "donusum", "orani",
    "sepet", "ortalamasi", "terk", "magaza", "ziyaretci",
    "trafik", "odeme", "komisyon", "abonelik", "saas",
    "mrr", "arr", "churn", "largeting", "fiyatlandirma",
    "karar", "matrisi", "esneklik", "elastikiyet", "portfoy",
    "yonetimi", "modern", "portfoy", "teorisi", "sharpe",
    "treynor", "beta", "riskli", "varlik", "dagilimi",
    "gayrimenkul", "yatirim", "roi", "net", "bugunku",
    "deger", "npv", "ic", "verim", "orani", "irr",
    "tarim", "hayvancilik", "uretim", "rekolte", "yem",
    "donusum", "sut", "et", "maliyeti", "sulama",
    "gubreleme", "hasat", "planlama", "tarimsal", "yatirim",
    "amortisman", "turizm", "otel", "doluluk", "adr",
    "revpar", "oda", "maliyeti", "restoran", "masa",
    "devir", "yemek", "gida", "zayiat", "etkinlik",
    "organizasyon", "bilet", "sponsorluk", "destek",
    "lojistik", "tasimacilik", "rota", "yakit", "tasit",
    "eskime", "navlun", "gumruk", "vergilendirme", "sigorta",
    "prim", "hasar", "orani", "aktuaryal", "hesaplama",
    "saglik", "tibbi", "cihaz", "kullanim", "laboratuvar",
    "test", "sarf", "malzeme", "hasta", "yatis",
    "sure", "taburcu", "hekim", "hemsire", "nobet",
    "is", "yuku", "ilac", "stok", "optimizasyon", "miat",
    "saglik", "turizmi", "fiyatlandirma", "paket", "maliyeti",
    "egitim", "kurumu", "ogrenci", "basina", "maliyet",
    "sinif", "doluluk", "akademik", "is", "yuku",
    "ogretmen", "planlama", "derslik", "laboratuvar", "kapasite",
    "egitim", "yatirim", "geri", "donus", "kurs",
    "program", "fiyatlandirma", "enerji", "verimliligi",
    "aydinlatma", "isitma", "sogutma", "havalandirma",
    "gunes", "paneli", "amortismani", "ruzgar", "turbini",
    "fizibilite", "su", "tasarrufu", "geri", "kazanim",
    "atik", "yonetimi", "geri", "donusum", "karbon",
    "salinimi", "ofsetleme", "cevresel", "etki", "eia",
    "yesil", "bina", "leed", "breeam", "sertifikasyon",
    "hukuk", "dava", "kazanma", "olasiligi", "beklenen",
    "deger", "avukat", "saatlik", "ucret", "toplam",
    "maliyet", "sozlesme", "risk", "maruziyet", "tazminat",
    "fikri", "mulkiyet", "patenta", "marka", "degerleme",
    "arabuluculuk", "uzlasma", "surec", "sirket", "kurulumu",
    "turleri", "vergi", "mukellefiyeti", "hukuk", "ofisi",
    "operasyonel", "verimlilik", "insaat", "yapi", "metraj",
    "hakedis", "malzeme", "tahmini", "is", "gucu",
    "verimlilik", "ekipman", "kiralama", "satin", "alma",
    "is", "kazasi", "risk", "is", "sagligi", "guvenligi",
    "isg", "santiye", "atik", "yonetimi", "lobi",
    "tasinma", "tasarım", "degisiklik", "etki", "imar",
    "emsal", "kat", "alani", "hesaplayici", "insaat",
    "fizibilite", "arsa", "payi", "kat", "karsiligi",
    "perakende", "magaza", "m2", "verimlilik", "ciro",
    "sepet", "ortalama", "stok", "bulundurma", "kaybi",
    "shrinkage", "magaza", "ici", "guzergah", "optimizasyon",
    "personel", "nobet", "planlama", "tedarikci", "degerlendirme",
    "skor", "karti", "sadakat", "programi", "crm",
    "yatirim", "promosyon", "etkinlik", "roi", "perakende",
    "fiyatlandirma", "markdown", "optimizasyonu", "e-ticaret",
    "isletme", "depolama", "siparis", "toplama", "kargo",
    "tasima", "iadeler", "musteri", "edinim", "cac",
    "omur", "boyu", "deger", "ltv", "donusum", "orani",
    "sepet", "ortalamasi", "terk", "magaza", "ziyaretci",
    "trafik", "odeme", "komisyon", "abonelik", "saas",
    "mrr", "arr", "churn", "largeting", "fiyatlandirma",
    "karar", "matrisi", "esneklik", "elastikiyet", "portfoy",
    "yonetimi", "modern", "portfoy", "teorisi", "sharpe",
    "treynor", "beta", "riskli", "varlik", "dagilimi",
    "gayrimenkul", "yatirim", "roi", "net", "bugunku",
    "deger", "npv", "ic", "verim", "orani", "irr",
    "tarim", "hayvancilik", "uretim", "rekolte", "yem",
    "donusum", "sut", "et", "maliyeti", "sulama",
    "gubreleme", "hasat", "planlama", "tarimsal", "yatirim",
    "amortisman", "turizm", "otel", "doluluk", "adr",
    "revpar", "oda", "maliyeti", "restoran", "masa",
    "devir", "yemek", "gida", "zayiat", "etkinlik",
    "organizasyon", "bilet", "sponsorluk", "destek",
    "lojistik", "tasimacilik", "rota", "yakit", "tasit",
    "eskime", "navlun", "gumruk", "vergilendirme", "sigorta",
    "prim", "hasar", "orani", "aktuaryal", "hesaplama",
    "saglik", "tibbi", "cihaz", "kullanim", "laboratuvar",
    "test", "sarf", "malzeme", "hasta", "yatis",
    "sure", "taburcu", "hekim", "hemsire", "nobet",
    "is", "yuku", "ilac", "stok", "optimizasyon", "miat",
    "saglik", "turizmi", "fiyatlandirma", "paket", "maliyeti",
    "egitim", "kurumu", "ogrenci", "basina", "maliyet",
    "sinif", "doluluk", "akademik", "is", "yuku",
    "ogretmen", "planlama", "derslik", "laboratuvar", "kapasite",
    "egitim", "yatirim", "geri", "donus", "kurs",
    "program", "fiyatlandirma", "enerji", "verimliligi",
    "aydinlatma", "isitma", "sogutma", "havalandirma",
    "gunes", "paneli", "amortismani", "ruzgar", "turbini",
    "fizibilite", "su", "tasarrufu", "geri", "kazanim",
    "atik", "yonetimi", "geri", "donusum", "karbon",
    "salinimi", "ofsetleme", "cevresel", "etki", "eia",
    "yesil", "bina", "leed", "breeam", "sertifikasyon",
    "hukuk", "dava", "kazanma", "olasiligi", "beklenen",
    "deger", "avukat", "saatlik", "ucret", "toplam",
    "maliyet", "sozlesme", "risk", "maruziyet", "tazminat",
    "fikri", "mulkiyet", "patenta", "marka", "degerleme",
    "arabuluculuk", "uzlasma", "surec", "sirket", "kurulumu",
    "turleri", "vergi", "mukellefiyeti", "hukuk", "ofisi",
    "operasyonel", "verimlilik", "insaat", "yapi", "metraj",
    "hakedis", "malzeme", "tahmini", "is", "gucu",
    "verimlilik", "ekipman", "kiralama", "satin", "alma",
    "is", "kazasi", "risk", "is", "sagligi", "guvenligi",
    "isg", "santiye", "atik", "yonetimi", "lobi",
    "tasinma", "tasarım", "degisiklik", "etki", "imar",
    "emsal", "kat", "alani", "hesaplayici", "insaat",
    "fizibilite", "arsa", "payi", "kat", "karsiligi",
    "perakende", "magaza", "m2", "verimlilik", "ciro",
    "sepet", "ortalama", "stok", "bulundurma", "kaybi",
    "shrinkage", "magaza", "ici", "guzergah", "optimizasyon",
    "personel", "nobet", "planlama", "tedarikci", "degerlendirme",
    "skor", "karti", "sadakat", "programi", "crm",
    "yatirim", "promosyon", "etkinlik", "roi", "perakende",
    "fiyatlandirma", "markdown", "optimizasyonu", "e-ticaret",
    "isletme", "depolama", "siparis", "toplama", "kargo",
    "tasima", "iadeler", "musteri", "edinim", "cac",
    "omur", "boyu", "deger", "ltv", "donusum", "orani",
    "sepet", "ortalamasi", "terk", "magaza", "ziyaretci",
    "trafik", "odeme", "komisyon", "abonelik", "saas",
    "mrr", "arr", "churn", "largeting", "fiyatlandirma",
    "karar", "matrisi", "esneklik", "elastikiyet", "portfoy",
    "yonetimi", "modern", "portfoy", "teorisi", "sharpe",
    "treynor", "beta", "riskli", "varlik", "dagilimi",
    "gayrimenkul", "yatirim", "roi", "net", "bugunku",
    "deger", "npv", "ic", "verim", "orani", "irr",
    "tarim", "hayvancilik", "uretim", "rekolte", "yem",
    "donusum", "sut", "et", "maliyeti", "sulama",
    "gubreleme", "hasat", "planlama", "tarimsal", "yatirim",
    "amortisman", "turizm", "otel", "doluluk", "adr",
    "revpar", "oda", "maliyeti", "restoran", "masa",
    "devir", "yemek", "gida", "zayiat", "etkinlik",
    "organizasyon", "bilet", "sponsorluk", "destek"
  ];
  return trWords.some(word => slug.includes(word));
}

const trSlugs = sectorCalcPremium152Seed.tools
  .map(t => t.slug)
  .filter(isTurkish);

console.log("Turkish slugs count:", trSlugs.length);
console.log(JSON.stringify(trSlugs, null, 2));
