/**
 * scripts/generate-free-v531-static-registry.ts
 *
 * V5.4 Core — Generate bundle-safe static registry for Free V5.3.1 schemas.
 *
 * Bundles all 50 V5.3.1 schemas into a single JSON file and generates
 * a TypeScript registry that imports the bundled JSON.
 * Single JSON import prevents webpack tree-shaking of individual schemas.
 *
 * Run: npx tsx scripts/generate-free-v531-static-registry.ts
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.cwd();
const SCHEMA_DIR = join(ROOT, "src/sectorcalc/schemas/free-v531");
const BUNDLED_DIR = join(SCHEMA_DIR, "bundled");
const OUTPUT_FILE = join(SCHEMA_DIR, "registry.generated.ts");

// Known V5.3.1 slug set (50 tools)
const V531_SLUGS = new Set([
  "machining-cost-per-part",
  "cnc-shop-hourly-rate",
  "cutting-speed-feed-rpm",
  "tap-drill-size",
  "iso-286-tolerance-fit",
  "surface-roughness-converter",
  "material-removal-rate",
  "tool-life-tool-cost-per-part",
  "scrap-cost",
  "rework-vs-scrap-decision",
  "thread-dimensions-reference",
  "knurling-drill-point-depth",
  "weld-metal-weight-consumable",
  "fillet-weld-size-strength",
  "welding-cost-per-meter",
  "welding-heat-input",
  "bolt-torque",
  "bolt-preload-clamp-force",
  "steel-weight",
  "beam-load-deflection-quick-check",
  "sheet-metal-bend-allowance",
  "oee",
  "downtime-cost",
  "takt-time-cycle-time",
  "setup-time-cost",
  "line-balancing-efficiency",
  "compressed-air-leak-cost",
  "electric-motor-running-cost",
  "energy-cost-per-part",
  "cbam-cost-quick-estimator",
  "electricity-co2-emissions",
  "diesel-fuel-co2-emissions",
  "product-carbon-footprint-basic",
  "carbon-price-exposure",
  "true-employee-cost",
  "quote-margin-markup",
  "break-even-point",
  "payment-term-cost",
  "machine-investment-payback",
  "customer-profitability",
  "currency-adjusted-pricing",
  "eoq",
  "safety-stock-reorder-point",
  "inventory-carrying-cost",
  "pallet-container-load-cbm",
  "freight-cost-per-km-trip",
  "concrete-volume-order-quantity",
  "rebar-weight-count",
  "recipe-cost-menu-price",
  "fabric-consumption-gsm",
]);

function main(): void {
  if (!existsSync(SCHEMA_DIR)) {
    console.error("FATAL: schema directory not found:", SCHEMA_DIR);
    process.exit(1);
  }

  // Read all schema JSON files, build combined lookup
  const files = readdirSync(SCHEMA_DIR)
    .filter((f: string) => f.endsWith(".json"))
    .sort();

  const combined: Record<string, Record<string, unknown>> = {};
  let entryCount = 0;

  for (const fn of files) {
    const numStr = fn.split("-")[0];
    if (!numStr || isNaN(Number(numStr))) continue;
    const num = parseInt(numStr, 10);
    if (num < 295 || num > 344) continue;

    const raw = JSON.parse(readFileSync(join(SCHEMA_DIR, fn), "utf-8")) as Record<string, unknown>;
    const tk = raw?.tool_key as string | undefined;
    if (tk && V531_SLUGS.has(tk)) {
      combined[tk] = raw;
      entryCount++;
    }
  }

  if (entryCount === 0) {
    console.error("FATAL: no V5.3.1 schemas found in", SCHEMA_DIR);
    process.exit(1);
  }

  // Write bundled JSON
  if (!existsSync(BUNDLED_DIR)) {
    mkdirSync(BUNDLED_DIR, { recursive: true });
  }
  const bundledPath = join(BUNDLED_DIR, "all.json");
  writeFileSync(bundledPath, JSON.stringify(combined), "utf8");
  console.log(`  Bundled JSON: ${bundledPath} (${entryCount} schemas)`);

  // Generate TypeScript registry
  const sortedKeys = Object.keys(combined).sort();
  const slugLines = sortedKeys.map((s) => `  "${s}"`).join(",\n");

  const output = `// ⚡ AUTO-GENERATED — DO NOT EDIT
// Generated by: npx tsx scripts/generate-free-v531-static-registry.ts
// Imports a single bundled JSON to prevent webpack tree-shaking.
// Generated on: ${new Date().toISOString().split("T")[0]}

import type { SuperV4Schema } from "@/sectorcalc/pro-form/contract-types";
import ALL_SCHEMAS from "./bundled/all.json";

type SchemaType = SuperV4Schema;
type SchemaBundle = Record<string, SchemaType>;

const _BUNDLE = ALL_SCHEMAS as unknown as SchemaBundle;
const _L = Object.keys(_BUNDLE);

/** Sorted list of all Free V5.3.1 schema slugs. */
export const FREE_V531_SCHEMA_SLUGS: readonly string[] = ${JSON.stringify(sortedKeys)} as const;

/** Resolve a Free V5.3.1 schema by slug. */
export function getFreeV531SchemaBySlug(slug: string): SchemaType | undefined {
  return _BUNDLE[slug];
}

/** Check if a Free V5.3.1 schema exists for the given slug. */
export function hasFreeV531Schema(slug: string): boolean {
  return slug in _BUNDLE;
}
`;

  writeFileSync(OUTPUT_FILE, output, "utf8");
  console.log(`✅ Generated: ${OUTPUT_FILE}`);
  console.log(`   Entries: ${entryCount}`);
  for (const s of sortedKeys) {
    console.log(`     - ${s}`);
  }
}

main();
