#!/usr/bin/env npx tsx
/**
 * Thin wrapper — full loader registry is generated by deepseek script.
 * Trust Gate: only PASS and WARN slugs are included in calculator-registry.ts.
 */
import { spawnSync } from "node:child_process";
import path from "node:path";
import { getActiveSlugs } from "../src/lib/generated-tools/trust-gate-server";

const deepseekScript = path.join(process.cwd(), "scripts/deepseek/generate-calculator-registry.ts");
const result = spawnSync("npx", ["tsx", deepseekScript], {
  cwd: process.cwd(),
  stdio: "inherit",
  shell: process.platform === "win32",
});

if (result.status !== 0) {
  process.exit(result.status ?? 1);
}

const activeSlugs = getActiveSlugs();
console.log(`✅ Registry generated: ${activeSlugs.length} calculators (PASS + WARN)`);
