/**
 * scripts/generate-free-v531-static-registry.ts
 *
 * V5.4 Core — Generate inline-free-v531-registry.ts (NO separate module).
 * Schema data is embedded directly in a loader to prevent webpack tree-shaking.
 *
 * Run: npx tsx scripts/generate-free-v531-static-registry.ts
 */

import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.cwd();
const SCHEMA_DIR = join(ROOT, "src/sectorcalc/schemas/free-v531");
const OUTPUT_FILE = join(ROOT, "src/sectorcalc/runtime/inline-free-v531-registry.ts");

// Known V5.3.1 slug set (50 tools)
const V531_SLUGS = new Set([
  "machining-cost-per-part",
  "cnc-shop-hourly-rate",
  "cutting-speed-feed-rpm",
  "tap-drill-size",
  "iso-286-tolerance-fit",
  "surface-roughness-converter",
  "material-removal-rate",
  "tool-life-tool-cost-per-part",
  "scrap-cost",
  "rework-vs-scrap-decision",
  "thread-dimensions-reference",
  "knurling-drill-point-depth",
  "weld-metal-weight-consumable",
  "fillet-weld-size-strength",
  "welding-cost-per-meter",
  "welding-heat-input",
  "bolt-torque",
  "bolt-preload-clamp-force",
  "steel-weight",
  "beam-load-deflection-quick-check",
  "sheet-metal-bend-allowance",
  "oee",
  "downtime-cost",
  "takt-time-cycle-time",
  "setup-time-cost",
  "line-balancing-efficiency",
  "compressed-air-leak-cost",
  "electric-motor-running-cost",
  "energy-cost-per-part",
  "cbam-cost-quick-estimator",
  "electricity-co2-emissions",
  "diesel-fuel-co2-emissions",
  "product-carbon-footprint-basic",
  "carbon-price-exposure",
  "true-employee-cost",
  "quote-margin-markup",
  "break-even-point",
  "break-even-and-margin-of-safety-analysis",
  "payment-term-cost",
  "machine-investment-payback",
  "customer-profitability",
  "currency-adjusted-pricing",
  "eoq",
  "safety-stock-reorder-point",
  "inventory-carrying-cost",
  "pallet-container-load-cbm",
  "freight-cost-per-km-trip",
  "concrete-volume-order-quantity",
  "rebar-weight-count",
  "recipe-cost-menu-price",
  "fabric-consumption-gsm",
  "von-mises-stress-calculator",
  "net-present-value-calculator",
  "return-on-investment-calculator",
]);

function main(): void {
  if (!existsSync(SCHEMA_DIR)) {
    console.error("FATAL: schema directory not found:", SCHEMA_DIR);
    process.exit(1);
  }

  const files = readdirSync(SCHEMA_DIR)
    .filter((f: string) => f.endsWith(".json"))
    .sort();

  const combined: Record<string, Record<string, unknown>> = {};
  let entryCount = 0;

  for (const fn of files) {
    const numStr = fn.split("-")[0];
    if (!numStr || isNaN(Number(numStr))) continue;
    const num = parseInt(numStr, 10);
    // Active V5.4 Core batch is 295-344; the break-even pilot lives at file 030
    // and the von Mises stress calculator pilot lives at file 278.
    if ((num < 295 || num > 344) && num !== 30 && num !== 278 && num !== 400 && num !== 401) continue;

    const raw = JSON.parse(readFileSync(join(SCHEMA_DIR, fn), "utf-8")) as Record<string, unknown>;
    const tk = raw?.tool_key as string | undefined;
    if (tk && V531_SLUGS.has(tk)) {
      combined[tk] = raw;
      entryCount++;
    }
  }

  if (entryCount === 0) {
    console.error("FATAL: no V5.3.1 schemas found in", SCHEMA_DIR);
    process.exit(1);
  }

  const sortedKeys = Object.keys(combined).sort();

  // Build switch cases — one per slug, each returning raw JSON object
  const caseLines: string[] = [];
  for (const slug of sortedKeys) {
    const schemaJSON = JSON.stringify(combined[slug]);
    caseLines.push(`    case "${slug}": return ${schemaJSON};`);
  }

  const output = `// ⚡ AUTO-GENERATED — DO NOT EDIT
// Generated by: npx tsx scripts/generate-free-v531-static-registry.ts
// Purpose: Bundle-safe Free V5.3.1 schema registry.
// Embedded in the runtime directory (same module scope as schema-loader)
// to prevent webpack tree-shaking across module boundaries.
// Uses switch/case — every case is statically referenced.
// Generated on: ${new Date().toISOString().split("T")[0]}

/**
 * Resolve a Free V5.3.1 schema by slug.
 * Returns the raw schema object (Record<string, unknown>) that must be
 * normalized via normalizeFreeSchema before use.
 * Switch/case — guaranteed bundle-safe, no tree-shaking.
 */
export function getFreeV531SchemaRaw(slug: string): Record<string, unknown> | undefined {
  switch (slug) {
${caseLines.join("\n")}
    default: return undefined;
  }
}
`;

  writeFileSync(OUTPUT_FILE, output, "utf8");

  const kb = Math.round(Buffer.byteLength(output, "utf8") / 1024);
  console.log(`✅ Generated: ${OUTPUT_FILE}`);
  console.log(`   Entries: ${entryCount}`);
  console.log(`   Size: ${kb} KB (inline in runtime dir)`);
  for (const s of sortedKeys) {
    console.log(`     - ${s}`);
  }
}

main();
