#!/usr/bin/env node
/**
 * Prebuild Reference Registry Generator
 *
 * Reads all YAML files from the `references/` directory, validates each
 * against FormReferenceBindingContract, and generates
 * `src/generated/reference-registry.ts`.
 *
 * Usage:
 *   npx tsx scripts/prebuild-reference-registry.ts
 *
 * Exit codes:
 *   0 — Success (registry generated)
 *   1 — Validation error (Zod schema violation)
 */

import * as fs from "node:fs";
import * as path from "node:path";
import * as yaml from "js-yaml";

// We need to avoid circular dependency with Zod at build time.
// Instead, we inline the validation schema here using a light validation.

const ROOT = process.cwd();
const REFERENCES_DIR = path.join(ROOT, "references");
const OUTPUT_FILE = path.join(ROOT, "src/generated/reference-registry.ts");

const UNIT_WHITELIST = [
  "MPa",
  "GPa",
  "psi",
  "kg/m3",
  "lb/ft3",
  "g/cm3",
  "mm",
  "in",
  "m",
  "ft",
  "Pa·s",
] as const;

const ALLOWED_PROJECT_UNIT_SYSTEMS = [
  "METRIC_ONLY",
  "IMPERIAL_ONLY",
  "GLOBAL",
] as const;

interface ReferenceItem {
  label: string;
  value: number;
  unit: string;
  source: string;
  description?: string;
}

interface ReferenceBinding {
  toolId: string;
  inputKey: string;
  standard: string;
  projectUnitSystem: string;
  references: ReferenceItem[];
}

// ─── Validation (lightweight, no Zod dependency for prebuild) ───────────

function validateBinding(
  data: unknown,
  filePath: string,
): ReferenceBinding {
  const errors: string[] = [];

  if (!data || typeof data !== "object") {
    throw new Error(`${filePath}: Must be an object`);
  }

  const d = data as Record<string, unknown>;

  if (!d.toolId || typeof d.toolId !== "string") {
    errors.push("toolId: required string");
  }
  if (!d.inputKey || typeof d.inputKey !== "string") {
    errors.push("inputKey: required string");
  }
  if (!d.standard || typeof d.standard !== "string") {
    errors.push("standard: required string");
  }
  if (
    !d.projectUnitSystem ||
    !ALLOWED_PROJECT_UNIT_SYSTEMS.includes(
      d.projectUnitSystem as (typeof ALLOWED_PROJECT_UNIT_SYSTEMS)[number],
    )
  ) {
    errors.push(
      `projectUnitSystem: must be one of ${ALLOWED_PROJECT_UNIT_SYSTEMS.join(", ")}`,
    );
  }
  if (!Array.isArray(d.references) || d.references.length === 0) {
    errors.push("references: must be a non-empty array");
  } else {
    for (let i = 0; i < d.references.length; i++) {
      const r = d.references[i] as Record<string, unknown>;
      if (!r.label || typeof r.label !== "string") {
        errors.push(`references[${i}].label: required string`);
      }
      if (typeof r.value !== "number") {
        errors.push(`references[${i}].value: required number`);
      }
      if (!r.unit || !UNIT_WHITELIST.includes(r.unit as typeof UNIT_WHITELIST[number])) {
        errors.push(
          `references[${i}].unit: must be one of ${UNIT_WHITELIST.join(", ")} (got "${r.unit}")`,
        );
      }
      if (!r.source || typeof r.source !== "string") {
        errors.push(`references[${i}].source: required string`);
      }
    }
  }

  if (errors.length > 0) {
    throw new Error(
      `${filePath}: Validation failed:\n  ${errors.join("\n  ")}`,
    );
  }

  return {
    toolId: d.toolId as string,
    inputKey: d.inputKey as string,
    standard: d.standard as string,
    projectUnitSystem: d.projectUnitSystem as string,
    references: d.references as ReferenceItem[],
  };
}

// ─── File Discovery ─────────────────────────────────────────────────────

function findYamlFiles(dir: string): string[] {
  const results: string[] = [];
  if (!fs.existsSync(dir)) return results;

  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...findYamlFiles(fullPath));
    } else if (
      entry.isFile() &&
      (entry.name.endsWith(".yaml") || entry.name.endsWith(".yml"))
    ) {
      results.push(fullPath);
    }
  }
  return results;
}

// ─── Registry Generation ────────────────────────────────────────────────

function generateRegistryCode(
  registry: Record<string, Record<string, ReferenceBinding>>,
): string {
  const lines: string[] = [];
  lines.push("// Auto-generated by scripts/prebuild-reference-registry.ts");
  lines.push("// DO NOT EDIT — run `npm run prebuild` to regenerate.");
  lines.push("");
  lines.push(
    'import type { ReferenceRegistry } from "@/lib/reference-engine/FormReferenceBindingContract";',
  );
  lines.push("");

  // Sort tool IDs for deterministic output
  const toolIds = Object.keys(registry).sort();

  lines.push("export const registry: ReferenceRegistry = {");

  for (const toolId of toolIds) {
    const inputKeys = Object.keys(registry[toolId]).sort();
    lines.push(`  "${toolId}": {`);
    for (const inputKey of inputKeys) {
      const binding = registry[toolId][inputKey];
      const refsJson = JSON.stringify(binding.references, null, 2)
        .split("\n")
        .map((l) => `      ${l}`)
        .join("\n")
        .trim();
      lines.push(`    "${inputKey}": {
      toolId: ${JSON.stringify(binding.toolId)},
      inputKey: ${JSON.stringify(binding.inputKey)},
      standard: ${JSON.stringify(binding.standard)},
      projectUnitSystem: ${JSON.stringify(binding.projectUnitSystem)},
      references: ${refsJson},
    },`);
    }
    lines.push("  },");
  }

  lines.push("};");
  lines.push("");
  lines.push(
    "// ════════════════════════════════════════════════════════════════",
  );
  lines.push(
    "// Usage: import { registry } from '@/generated/reference-registry';",
  );
  lines.push(
    "// <GlobalReferenceInput binding={registry[toolId][inputKey]} ... />",
  );
  lines.push(
    "// ════════════════════════════════════════════════════════════════",
  );
  lines.push("");

  return lines.join("\n");
}

// ─── Main ───────────────────────────────────────────────────────────────

function main(): void {
  console.log("📦 Prebuild Reference Registry Generator");
  console.log(`   Scanning: ${REFERENCES_DIR}`);
  console.log(`   Output:   ${OUTPUT_FILE}\n`);

  const yamlFiles = findYamlFiles(REFERENCES_DIR);

  if (yamlFiles.length === 0) {
    console.log("   ⚠ No YAML files found in references/ directory.");
    console.log("   ✓ Empty registry generated.\n");
    // Ensure output directory exists
    const outDir = path.dirname(OUTPUT_FILE);
    if (!fs.existsSync(outDir)) {
      fs.mkdirSync(outDir, { recursive: true });
    }
    // Write empty registry
    const code = `// Auto-generated by scripts/prebuild-reference-registry.ts\n// DO NOT EDIT — run \`npm run prebuild\` to regenerate.\n\nimport type { ReferenceRegistry } from "@/lib/reference-engine/FormReferenceBindingContract";\n\nexport const registry: ReferenceRegistry = {};\n`;
    fs.writeFileSync(OUTPUT_FILE, code, "utf8");
    console.log("   ✓ Empty registry written.\n");
    process.exit(0);
  }

  const registry: Record<string, Record<string, ReferenceBinding>> = {};
  let validCount = 0;
  let errorCount = 0;

  for (const filePath of yamlFiles) {
    const relativePath = path.relative(ROOT, filePath);
    console.log(`   📄 ${relativePath}`);

    try {
      const raw = fs.readFileSync(filePath, "utf8");
      const parsed = yaml.load(raw) as unknown;
      const binding = validateBinding(parsed, relativePath);

      // Check for duplicate toolId+inputKey
      if (registry[binding.toolId]?.[binding.inputKey]) {
        console.error(
          `   ❌ Duplicate binding: ${binding.toolId}.${binding.inputKey} already defined.`,
        );
        errorCount++;
        continue;
      }

      if (!registry[binding.toolId]) {
        registry[binding.toolId] = {};
      }
      registry[binding.toolId][binding.inputKey] = binding;
      validCount++;
      console.log(
        `   ✓ ${binding.toolId}.${binding.inputKey} → ${binding.references.length} reference(s) (${binding.standard})`,
      );
    } catch (err) {
      errorCount++;
      console.error(`   ❌ ${(err as Error).message}`);
    }
  }

  console.log("\n   ──────────────────────────────────────");
  console.log(`   ✅ Valid:   ${validCount}`);
  console.log(`   ❌ Errors:  ${errorCount}`);
  console.log(`   📊 Total:   ${yamlFiles.length} file(s)`);

  if (errorCount > 0 && validCount === 0) {
    console.error("\n❌ No valid bindings found. Aborting registry generation.\n");
    process.exit(1);
  }

  // Ensure output directory exists
  const outDir = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }

  // Generate and write
  const code = generateRegistryCode(registry);
  fs.writeFileSync(OUTPUT_FILE, code, "utf8");
  console.log(`\n   📝 Written: ${path.relative(ROOT, OUTPUT_FILE)}`);
  console.log("   ✅ Registry generation complete.\n");

  process.exit(0);
}

main();
