import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage();
const requests = [];
page.on('response', (r) => { if (r.url().includes('sc-billing') || r.url().includes('sc-study') || r.url().includes('quote-pro.ts') || r.url().includes('labor-pro.ts') || r.url().includes('sc008-pro.ts')) requests.push(`${r.status()} ${r.url().split('?')[0].split('/').pop()}?${r.url().split('?')[1] || ''}`); });
await page.goto('https://sectorcalc.com/calculator/quote-pricing', { waitUntil: 'networkidle', timeout: 30000 });
await page.waitForTimeout(2000);
console.log('quote-pricing loaded assets:');
for (const r of [...new Set(requests)]) console.log(' ', r);
await page.close();
await browser.close();
