import type { PremiumCalculatorSchema } from "@/lib/premium-schema/premium-calculator-schema";

const WAITING_OPPORTUNITY_MODE_OPTIONS = [
  { value: "none", label: "Exclude opportunity cost" },
  { value: "manualHourly", label: "Manual hourly opportunity cost" },
  { value: "derivedThroughput", label: "Derive from planned throughput" },
] as const;

const CURRENCY_CODE_OPTIONS = [
  { value: "USD", label: "USD — US Dollar" },
  { value: "EUR", label: "EUR — Euro" },
  { value: "GBP", label: "GBP — British Pound" },
  { value: "TRY", label: "TRY — Turkish Lira" },
  { value: "CHF", label: "CHF — Swiss Franc" },
  { value: "JPY", label: "JPY — Japanese Yen" },
  { value: "CAD", label: "CAD — Canadian Dollar" },
  { value: "AUD", label: "AUD — Australian Dollar" },
] as const;

export const SEVEN_MUDA_WASTE_COST_CALCULATOR_SCHEMA: PremiumCalculatorSchema = {
  id: "7-israf-muda-avcisi-parasal-karsilik-calculator",
  legacyPaidSlug: "7-israf-muda-avcisi-parasal-karsilik-calculator",
  name: "7 Waste (Muda) Hunter Monetary Impact Calculator",
  sectorSlug: "manufacturing",
  category: "cost",
  painStatement:
    "Quantifies period-level monetary impact across overproduction, waiting, transport, inventory, motion, overprocessing, and defect waste drivers.",

  inputs: [
    {
      id: "analysisPeriodDays",
      label: "Analysis period length",
      type: "number",
      unit: "days",
      required: true,
      smartDefault: 30,
      validation: { min: 1 },
      helper: "Number of calendar or working days covered by this analysis window.",
      expertMeaning: "Annualization and inventory holding proration use this period length.",
    },
    {
      id: "workingDaysPerYear",
      label: "Working days per year",
      type: "number",
      unit: "days/year",
      required: true,
      smartDefault: 250,
      validation: { min: 1 },
      helper: "Operating days used to annualize period waste exposure.",
      expertMeaning: "annualizedWasteCost = totalWasteCost × (workingDaysPerYear / analysisPeriodDays).",
    },
    {
      id: "productionUnitsInPeriod",
      label: "Production units in period",
      type: "number",
      unit: "units",
      required: true,
      smartDefault: 1000,
      validation: { min: 1 },
      helper: "Good units produced inside the selected analysis period only — not annual volume.",
      expertMeaning: "Denominator for wasteCostPerUnit and throughput-based opportunity cost.",
    },
    {
      id: "currencyCode",
      label: "Currency code",
      type: "select",
      unit: "USD",
      required: true,
      smartDefault: "USD",
      helper: "All monetary inputs below must use this same currency for the analysis period.",
      expertMeaning: "ISO 4217 three-letter code; mixed-currency inputs invalidate comparison.",
      options: [...CURRENCY_CODE_OPTIONS],
    },
    {
      id: "unitVariableCost",
      label: "Unit variable cost",
      type: "number",
      unit: "currency/unit",
      required: true,
      smartDefault: 50,
      validation: { min: 0 },
      helper: "Fully loaded variable cost to produce one good unit.",
      expertMeaning: "Used for overproduction base cost and scrap material cost.",
    },
    {
      id: "unitSellingPrice",
      label: "Unit selling price",
      type: "number",
      unit: "currency/unit",
      required: true,
      smartDefault: 80,
      validation: { min: 0 },
      helper: "Average selling price per good unit in the analysis period.",
      expertMeaning: "Used for periodRevenue and gross-margin-based opportunity cost.",
    },
    {
      id: "grossMarginPct",
      label: "Gross margin percent",
      type: "number",
      unit: "%",
      required: true,
      smartDefault: 25,
      validation: { min: 0, max: 100 },
      helper: "Gross margin as a percent of selling price per unit.",
      expertMeaning: "Drives unit gross margin and waste-to-margin ratio outputs.",
    },
    {
      id: "excessUnits",
      label: "Excess production units",
      type: "number",
      unit: "units",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Units produced beyond confirmed demand inside the analysis period.",
      expertMeaning: "Overproduction volume before holding and write-down adjustments.",
    },
    {
      id: "excessInventoryHoldingDays",
      label: "Excess inventory holding days",
      type: "number",
      unit: "days",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Average days excess units remain in inventory before use or write-down.",
      expertMeaning: "Prorates overproduction holding cost across the year.",
    },
    {
      id: "excessWriteDownCostPerUnit",
      label: "Excess write-down per unit",
      type: "number",
      unit: "currency/unit",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Value loss per excess unit — enter per-unit amount, not a lump-sum total.",
      expertMeaning: "Separate from inventoryObsolescenceValue; scales only with excessUnits.",
    },
    {
      id: "waitingMinutes",
      label: "Waiting minutes",
      type: "number",
      unit: "minutes",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Queue, idle, or blocked minutes waiting for material, machine, or information.",
      expertMeaning: "Multiplied by affected operators and machines using hourly-to-minute conversion.",
    },
    {
      id: "affectedOperators",
      label: "Affected operators",
      type: "number",
      unit: "units",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Operators idled during waiting events in the period.",
      expertMeaning: "Scales waiting labor cost across concurrent idle operators.",
    },
    {
      id: "hourlyLaborCost",
      label: "Hourly labor cost",
      type: "number",
      unit: "currency/hour",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Loaded labor cost per hour for waiting operators.",
      expertMeaning: "Converted to laborMinuteCost = hourlyLaborCost / 60 inside the calculator.",
    },
    {
      id: "affectedMachines",
      label: "Affected machines",
      type: "number",
      unit: "units",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Machines or lines idled during waiting events.",
      expertMeaning: "Scales waiting machine cost across concurrent idle assets.",
    },
    {
      id: "hourlyMachineCost",
      label: "Hourly machine cost",
      type: "number",
      unit: "currency/hour",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Loaded machine or line cost per hour during waiting.",
      expertMeaning: "Converted to machineMinuteCost = hourlyMachineCost / 60 inside the calculator.",
    },
    {
      id: "waitingOpportunityMode",
      label: "Waiting opportunity mode",
      type: "select",
      unit: "ratio",
      required: true,
      smartDefault: "none",
      helper: "Choose how waiting opportunity cost is excluded, entered manually, or derived from throughput.",
      expertMeaning: "none = direct waiting only; manualHourly = hourlyOpportunityCost; derivedThroughput = plannedUnitsPerHour × unit gross margin.",
      options: [...WAITING_OPPORTUNITY_MODE_OPTIONS],
    },
    {
      id: "hourlyOpportunityCost",
      label: "Hourly opportunity cost",
      type: "number",
      unit: "currency/hour",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Manual opportunity cost rate used when waitingOpportunityMode is manualHourly.",
      expertMeaning: "Applied as waitingMinutes × (hourlyOpportunityCost / 60).",
    },
    {
      id: "plannedUnitsPerHour",
      label: "Planned units per hour",
      type: "number",
      unit: "units/hour",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Planned good-unit throughput used when opportunity cost is derived from throughput.",
      expertMeaning: "Required when waitingOpportunityMode is derivedThroughput; zero triggers a validation warning.",
    },
    {
      id: "transportDistanceKm",
      label: "Transport distance",
      type: "number",
      unit: "km/trip",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Average one-way distance per internal transport move.",
      expertMeaning: "Distance component multiplied by transportTrips and cost per km.",
    },
    {
      id: "transportTrips",
      label: "Transport trips",
      type: "number",
      unit: "units",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Count of non-value internal transport moves in the period.",
      expertMeaning: "Also scales handling time and transport damage exposure.",
    },
    {
      id: "transportCostPerKm",
      label: "Transport cost per km",
      type: "number",
      unit: "currency/km",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Loaded vehicle or forklift cost per kilometer moved.",
      expertMeaning: "Vehicle cost component of transport waste.",
    },
    {
      id: "handlingMinutesPerTrip",
      label: "Handling minutes per trip",
      type: "number",
      unit: "minutes/trip",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Non-value handling minutes per transport trip.",
      expertMeaning: "Multiplied by transportTrips and handling hourly labor converted to minutes.",
    },
    {
      id: "handlingHourlyLaborCost",
      label: "Handling hourly labor cost",
      type: "number",
      unit: "currency/hour",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Loaded labor cost for material handling during transport moves.",
      expertMeaning: "Converted to handlingMinuteCost = handlingHourlyLaborCost / 60.",
    },
    {
      id: "transportDamageRatePct",
      label: "Transport damage rate",
      type: "number",
      unit: "%",
      required: false,
      smartDefault: 0,
      validation: { min: 0, max: 100 },
      helper: "Expected value loss from in-transit damage as a percent of average load value.",
      expertMeaning: "Damage cost = averageLoadValue × rate × transportTrips.",
    },
    {
      id: "averageLoadValue",
      label: "Average load value",
      type: "number",
      unit: "USD",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Average monetary value moved per transport trip.",
      expertMeaning: "Base value for transport damage cost calculation.",
    },
    {
      id: "averageExcessInventoryValue",
      label: "Average excess inventory value",
      type: "number",
      unit: "USD",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Average value of inventory held above required buffer during the period.",
      expertMeaning: "Base for inventory holding, shrinkage, and obsolescence buckets.",
    },
    {
      id: "inventoryHoldingRatePct",
      label: "Inventory holding rate",
      type: "number",
      unit: "%/year",
      required: false,
      smartDefault: 0,
      validation: { min: 0, max: 100 },
      helper: "Annualized carrying cost as a percent of inventory value.",
      expertMeaning: "Prorated by analysisPeriodDays / 365 for period holding cost.",
    },
    {
      id: "inventoryObsolescenceValue",
      label: "Inventory obsolescence value",
      type: "number",
      unit: "USD",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Stock write-down from obsolescence — separate from excess production write-down per unit.",
      expertMeaning: "Not multiplied by excessUnits; models shelf-life or spec-change loss.",
    },
    {
      id: "inventoryShrinkageRatePct",
      label: "Inventory shrinkage rate",
      type: "number",
      unit: "%",
      required: false,
      smartDefault: 0,
      validation: { min: 0, max: 100 },
      helper: "Shrink or loss rate applied to average excess inventory value.",
      expertMeaning: "Shrinkage cost = averageExcessInventoryValue × shrinkage rate.",
    },
    {
      id: "unnecessaryMotionMinutes",
      label: "Unnecessary motion minutes",
      type: "number",
      unit: "minutes",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Operator motion minutes that do not add customer value.",
      expertMeaning: "Multiplied by motionAffectedOperators and motion hourly labor converted to minutes.",
    },
    {
      id: "motionAffectedOperators",
      label: "Motion affected operators",
      type: "number",
      unit: "units",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Operators performing unnecessary motion during the period.",
      expertMeaning: "Scales motion labor waste across concurrent operators.",
    },
    {
      id: "motionHourlyLaborCost",
      label: "Motion hourly labor cost",
      type: "number",
      unit: "currency/hour",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Loaded labor cost per hour for motion waste.",
      expertMeaning: "Converted to motionMinuteCost = motionHourlyLaborCost / 60.",
    },
    {
      id: "overprocessingMinutes",
      label: "Overprocessing minutes",
      type: "number",
      unit: "minutes",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Extra processing minutes beyond what the customer requires.",
      expertMeaning: "Multiplied by overprocessing hourly resource cost converted to minutes.",
    },
    {
      id: "overprocessingHourlyResourceCost",
      label: "Overprocessing hourly resource cost",
      type: "number",
      unit: "currency/hour",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Loaded machine or line cost per hour for overprocessing time.",
      expertMeaning: "Converted to overprocessingMinuteCost = overprocessingHourlyResourceCost / 60.",
    },
    {
      id: "extraMaterialCost",
      label: "Extra material cost",
      type: "number",
      unit: "USD",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Additional material consumed by overprocessing beyond standard BOM.",
      expertMeaning: "Direct material add-on inside overprocessing waste.",
    },
    {
      id: "extraEnergyCost",
      label: "Extra energy cost",
      type: "number",
      unit: "USD",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Additional energy consumed by overprocessing steps.",
      expertMeaning: "Direct utility add-on inside overprocessing waste.",
    },
    {
      id: "extraInspectionCost",
      label: "Extra inspection cost",
      type: "number",
      unit: "USD",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Additional inspection or appraisal cost caused by overprocessing.",
      expertMeaning: "Direct quality appraisal add-on inside overprocessing waste.",
    },
    {
      id: "scrapUnits",
      label: "Scrap units",
      type: "number",
      unit: "units",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Units scrapped inside the analysis period.",
      expertMeaning: "Scrap material cost = scrapUnits × unitVariableCost.",
    },
    {
      id: "scrapDisposalCostPerUnit",
      label: "Scrap disposal cost per unit",
      type: "number",
      unit: "currency/unit",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Disposal, sorting, or recycling cost per scrapped unit.",
      expertMeaning: "Added to scrap material cost inside defect waste.",
    },
    {
      id: "reworkMinutes",
      label: "Rework minutes",
      type: "number",
      unit: "minutes",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Labor and machine minutes spent on rework in the period.",
      expertMeaning: "Split across rework labor and machine minute costs.",
    },
    {
      id: "reworkHourlyLaborCost",
      label: "Rework hourly labor cost",
      type: "number",
      unit: "currency/hour",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Loaded labor cost per hour for rework activity.",
      expertMeaning: "Converted to reworkMinuteLaborCost = reworkHourlyLaborCost / 60.",
    },
    {
      id: "reworkHourlyMachineCost",
      label: "Rework hourly machine cost",
      type: "number",
      unit: "currency/hour",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Loaded machine cost per hour for rework activity.",
      expertMeaning: "Converted to reworkMinuteMachineCost = reworkHourlyMachineCost / 60.",
    },
    {
      id: "customerReturnCost",
      label: "Customer return cost",
      type: "number",
      unit: "USD",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Logistics, credit, or handling cost from customer returns linked to defects.",
      expertMeaning: "Direct defect bucket cost outside scrap and rework minutes.",
    },
    {
      id: "warrantyCost",
      label: "Warranty cost",
      type: "number",
      unit: "USD",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Warranty claims or service cost attributed to defect waste in the period.",
      expertMeaning: "Direct defect bucket cost outside scrap and rework minutes.",
    },
    {
      id: "expediteCost",
      label: "Expedite cost",
      type: "number",
      unit: "USD",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Premium freight, overtime, or rush fees triggered by defect fallout.",
      expertMeaning: "Direct defect bucket cost outside scrap and rework minutes.",
    },
    {
      id: "dataConfidencePct",
      label: "Data confidence",
      type: "number",
      unit: "%",
      required: true,
      smartDefault: 70,
      validation: { min: 0, max: 100 },
      helper: "Your confidence that the entered waste drivers reflect actual shop-floor data.",
      expertMeaning: "Feeds confidenceLevel and riskAdjustedPriorityScore in the decision output.",
    },
    {
      id: "implementationDifficultyScore",
      label: "Implementation difficulty",
      type: "number",
      unit: "ratio",
      required: true,
      smartDefault: 3,
      validation: { min: 1, max: 5, step: 1 },
      helper: "How hard it is to implement fixes: 1 = easy kaizen, 5 = major capital or layout change.",
      expertMeaning: "Higher difficulty reduces riskAdjustedPriorityScore for otherwise large savings.",
    },
  ],

  formulaPipeline: [
    {
      formulaId: "lean.muda_overproduction_cost",
      inputMap: {
        excessUnits: "excessUnits",
        unitProductionCost: "unitVariableCost",
        inventoryHoldingRatePct: "inventoryHoldingRatePct",
      },
      outputId: "overproductionCost",
    },
    {
      formulaId: "lean.muda_waiting_cost",
      inputMap: {
        waitingMinutes: "waitingMinutes",
        resourceMinuteCost: "hourlyMachineCost",
      },
      outputId: "waitingCost",
    },
    {
      formulaId: "lean.muda_transport_cost",
      inputMap: {
        transportDistanceKm: "transportDistanceKm",
        transportTrips: "transportTrips",
        transportCostPerKm: "transportCostPerKm",
      },
      outputId: "transportCost",
    },
    {
      formulaId: "lean.muda_inventory_cost",
      inputMap: {
        averageExcessInventoryValue: "averageExcessInventoryValue",
        inventoryHoldingRatePct: "inventoryHoldingRatePct",
      },
      outputId: "inventoryCost",
    },
    {
      formulaId: "lean.muda_motion_cost",
      inputMap: {
        unnecessaryMotionMinutes: "unnecessaryMotionMinutes",
        laborMinuteCost: "motionHourlyLaborCost",
      },
      outputId: "motionCost",
    },
    {
      formulaId: "lean.muda_overprocessing_cost",
      inputMap: {
        overprocessingMinutes: "overprocessingMinutes",
        resourceMinuteCost: "overprocessingHourlyResourceCost",
        extraMaterialCost: "extraMaterialCost",
      },
      outputId: "overprocessingCost",
    },
    {
      formulaId: "lean.muda_defect_cost",
      inputMap: {
        scrapUnits: "scrapUnits",
        unitProductionCost: "unitVariableCost",
        reworkMinutes: "reworkMinutes",
        laborMinuteCost: "reworkHourlyLaborCost",
      },
      outputId: "defectCost",
    },
    {
      formulaId: "lean.muda_total_waste_cost",
      inputMap: {
        overproductionCost: "overproductionCost",
        waitingCost: "waitingCost",
        transportCost: "transportCost",
        inventoryCost: "inventoryCost",
        motionCost: "motionCost",
        overprocessingCost: "overprocessingCost",
        defectCost: "defectCost",
      },
      outputId: "totalWasteCost",
    },
    {
      formulaId: "lean.muda_annualized_waste_cost",
      inputMap: {},
      outputId: "annualizedWasteCost",
    },
    {
      formulaId: "lean.muda_waste_cost_per_unit",
      inputMap: {},
      outputId: "wasteCostPerUnit",
    },
    {
      formulaId: "lean.muda_period_revenue",
      inputMap: {},
      outputId: "periodRevenue",
    },
    {
      formulaId: "lean.muda_period_gross_margin_value",
      inputMap: {},
      outputId: "periodGrossMarginValue",
    },
    {
      formulaId: "lean.muda_waste_to_revenue_ratio_pct",
      inputMap: {},
      outputId: "wasteToRevenueRatioPct",
    },
    {
      formulaId: "lean.muda_waste_to_gross_margin_ratio_pct",
      inputMap: {},
      outputId: "wasteToGrossMarginRatioPct",
    },
    {
      formulaId: "lean.muda_highest_waste_cost",
      inputMap: {},
      outputId: "highestWasteCost",
    },
    {
      formulaId: "lean.muda_risk_adjusted_priority_score",
      inputMap: {},
      outputId: "riskAdjustedPriorityScore",
    },
    {
      formulaId: "lean.muda_highest_waste_index",
      inputMap: {
        overproductionCost: "overproductionCost",
        waitingCost: "waitingCost",
        transportCost: "transportCost",
        inventoryCost: "inventoryCost",
        motionCost: "motionCost",
        overprocessingCost: "overprocessingCost",
        defectCost: "defectCost",
      },
      outputId: "highestWasteCategoryIndex",
    },
  ],

  outputs: [
    {
      id: "totalWasteCost",
      label: "Total waste cost",
      unit: "USD",
      format: "currency",
      isBigNumber: true,
    },
    {
      id: "annualizedWasteCost",
      label: "Annualized waste cost",
      unit: "USD",
      format: "currency",
    },
    {
      id: "wasteCostPerUnit",
      label: "Waste cost per unit",
      unit: "USD",
      format: "currency",
    },
    {
      id: "periodRevenue",
      label: "Period revenue",
      unit: "USD",
      format: "currency",
    },
    {
      id: "periodGrossMarginValue",
      label: "Period gross margin value",
      unit: "USD",
      format: "currency",
    },
    {
      id: "wasteToRevenueRatioPct",
      label: "Waste to revenue ratio",
      unit: "%",
      format: "percentage",
    },
    {
      id: "wasteToGrossMarginRatioPct",
      label: "Waste to gross margin ratio",
      unit: "%",
      format: "percentage",
    },
    {
      id: "highestWasteCost",
      label: "Highest waste category cost",
      unit: "USD",
      format: "currency",
    },
    {
      id: "riskAdjustedPriorityScore",
      label: "Risk-adjusted priority score",
      unit: "score",
      format: "score",
    },
    {
      id: "overproductionCost",
      label: "Overproduction cost",
      unit: "USD",
      format: "currency",
    },
    {
      id: "waitingCost",
      label: "Waiting cost",
      unit: "USD",
      format: "currency",
    },
    {
      id: "transportCost",
      label: "Transport cost",
      unit: "USD",
      format: "currency",
    },
    {
      id: "inventoryCost",
      label: "Inventory cost",
      unit: "USD",
      format: "currency",
    },
    {
      id: "motionCost",
      label: "Motion cost",
      unit: "USD",
      format: "currency",
    },
    {
      id: "overprocessingCost",
      label: "Overprocessing cost",
      unit: "USD",
      format: "currency",
    },
    {
      id: "defectCost",
      label: "Defect cost",
      unit: "USD",
      format: "currency",
    },
    {
      id: "highestWasteCategoryIndex",
      label: "Highest waste category rank",
      unit: "rank",
      format: "number",
    },
  ],

  thresholds: [
    {
      fieldId: "totalWasteCost",
      warning: 5000,
      critical: 15000,
      direction: "higher_is_bad",
      warningMessage: "Total muda exposure is material — review the highest waste category and recommended action order.",
      criticalMessage: "Total muda exposure is severe — launch focused kaizen on the dominant waste driver.",
    },
  ],

  reportTemplate: {
    title: "7 Muda Monetary Impact Decision Report",
    sections: ["executive_summary", "loss_breakdown", "thresholds", "action_plan", "assumptions"],
    exportFormats: ["pdf", "csv"],
  },

  assumptions: {
    hiddenLossMultiplier: 1,
    volatilityPercent: 8,
    targetMarginPercent: 0,
    assumptionNotes: [
      "All monetary inputs must use the selected currencyCode for the analysis period.",
      "productionUnitsInPeriod is the production volume inside the selected analysis period only.",
      "Hourly labor and machine rates are converted to minute costs inside the engineering calculator.",
      "excessWriteDownCostPerUnit is per excess unit, not a lump-sum write-down total.",
      "inventoryObsolescenceValue is stock write-down outside excess-production write-down.",
      "Waiting cost combines labor and machine minute costs plus optional opportunity modes.",
      "This tool produces operational loss estimates — not ERP reconciliation or audited financial statements.",
    ],
  },
};
