import type { PremiumCalculatorSchema } from "@/lib/premium-schema/premium-calculator-schema";

const WAITING_OPPORTUNITY_MODE_OPTIONS = [
  { value: "margin", label: "Derive from unit contribution margin" },
  { value: "manual", label: "Manual hourly opportunity cost" },
] as const;

const CURRENCY_CODE_OPTIONS = [
  { value: "USD", label: "USD — US Dollar" },
  { value: "EUR", label: "EUR — Euro" },
  { value: "GBP", label: "GBP — British Pound" },
  { value: "TRY", label: "TRY — Turkish Lira" },
  { value: "CHF", label: "CHF — Swiss Franc" },
  { value: "JPY", label: "JPY — Japanese Yen" },
  { value: "CAD", label: "CAD — Canadian Dollar" },
  { value: "AUD", label: "AUD — Australian Dollar" },
] as const;

export const SEVEN_MUDA_WASTE_COST_CALCULATOR_SCHEMA: PremiumCalculatorSchema = {
  id: "7-israf-muda-avcisi-parasal-karsilik-calculator",
  legacyPaidSlug: "7-israf-muda-avcisi-parasal-karsilik-calculator",
  name: "7 Waste (Muda) Hunter Monetary Impact Calculator",
  sectorSlug: "manufacturing",
  category: "cost",
  painStatement:
    "Quantifies period-level monetary impact across overproduction, waiting, transport, inventory, motion, overprocessing, and defect waste drivers.",

  inputs: [
    {
      id: "analysisPeriodDays",
      label: "Analysis period length",
      type: "number",
      unit: "days",
      required: true,
      smartDefault: 30,
      validation: { min: 1 },
      helper: "Number of calendar or working days covered by this analysis window.",
      expertMeaning: "Annualization and inventory holding proration use this period length.",
    },
    {
      id: "annualWorkingDays",
      label: "Annual working days",
      type: "number",
      unit: "days/year",
      required: true,
      smartDefault: 250,
      validation: { min: 1 },
      helper: "Operating days used to annualize period waste exposure.",
      expertMeaning: "annualizedWasteCost = totalWasteCost × (annualWorkingDays / analysisPeriodDays).",
    },
    {
      id: "productionUnits",
      label: "Production units in period",
      type: "number",
      unit: "units",
      required: true,
      smartDefault: 1000,
      validation: { min: 1 },
      helper: "Good units produced inside the selected analysis period only — not annual volume.",
      expertMeaning: "Denominator for wasteCostPerUnit and throughput context.",
    },
    {
      id: "currency",
      label: "Currency",
      type: "select",
      unit: "USD",
      required: true,
      smartDefault: "USD",
      helper: "All monetary inputs below must use this same currency for the analysis period.",
      expertMeaning: "ISO 4217 three-letter code; mixed-currency inputs invalidate comparison.",
      options: [...CURRENCY_CODE_OPTIONS],
    },
    {
      id: "unitVariableCost",
      label: "Unit variable cost",
      type: "number",
      unit: "currency/unit",
      required: true,
      smartDefault: 50,
      validation: { min: 0 },
      helper: "Fully loaded variable cost to produce one good unit.",
      expertMeaning: "Used for overproduction base cost and defect material cost.",
    },
    {
      id: "unitSellingPrice",
      label: "Unit selling price",
      type: "number",
      unit: "currency/unit",
      required: true,
      smartDefault: 80,
      validation: { min: 0 },
      helper: "Average selling price per good unit in the analysis period.",
      expertMeaning: "Used for periodRevenue and margin-based opportunity cost.",
    },
    {
      id: "grossMarginPercent",
      label: "Gross margin percent",
      type: "number",
      unit: "%",
      required: true,
      smartDefault: 25,
      validation: { min: 0, max: 100 },
      helper: "Gross margin as a percent of selling price per unit.",
      expertMeaning: "Drives unit contribution margin and waste-to-margin ratio outputs.",
    },
    {
      id: "overproductionUnits",
      label: "Excess production units",
      type: "number",
      unit: "units",
      required: true,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Units produced beyond confirmed demand or order plan inside the analysis period.",
      expertMeaning: "Overproduction volume before write-down adjustments.",
    },
    {
      id: "waitingHours",
      label: "Waiting / downtime hours",
      type: "number",
      unit: "hours",
      required: true,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Total hours people, machines, or processes waited idle in the period.",
      expertMeaning: "Multiplied by hourly opportunity cost per waitingOpportunityCostMode.",
    },
    {
      id: "waitingOpportunityCostMode",
      label: "Waiting opportunity cost mode",
      type: "select",
      unit: "mode",
      required: true,
      smartDefault: "margin",
      helper: "Choose manual hourly cost or derive opportunity cost from unit contribution margin.",
      expertMeaning: "manual = manualHourlyOpportunityCost; margin = unit contribution margin per hour basis.",
      options: [...WAITING_OPPORTUNITY_MODE_OPTIONS],
    },
    {
      id: "manualHourlyOpportunityCost",
      label: "Hourly opportunity cost",
      type: "number",
      unit: "currency/hour",
      required: true,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Hourly cost used to convert waiting hours into monetary loss when mode is manual.",
      expertMeaning: "Applied as waitingHours × manualHourlyOpportunityCost.",
    },
    {
      id: "unnecessaryTransportCost",
      label: "Unnecessary transport cost",
      type: "number",
      unit: "currency",
      required: true,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Unnecessary internal transport, handling, forklift, routing, or shipment cost in the period.",
      expertMeaning: "Direct transport waste bucket — no distance model required.",
    },
    {
      id: "excessInventoryValue",
      label: "Excess inventory value",
      type: "number",
      unit: "currency",
      required: true,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Average value of inventory held above required buffer during the period.",
      expertMeaning: "Base for inventory carrying cost proration.",
    },
    {
      id: "inventoryCarryingRatePercent",
      label: "Inventory carrying rate",
      type: "number",
      unit: "%",
      required: true,
      smartDefault: 20,
      validation: { min: 0, max: 100 },
      helper: "Annual carrying rate including finance, space, insurance, spoilage, and stock risk.",
      expertMeaning: "Prorated by analysisPeriodDays / annualWorkingDays for period holding cost.",
    },
    {
      id: "unnecessaryMotionHours",
      label: "Unnecessary motion hours",
      type: "number",
      unit: "hours",
      required: true,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Non-value operator, team, or field movement time in the period.",
      expertMeaning: "Multiplied by motionHourlyCost.",
    },
    {
      id: "motionHourlyCost",
      label: "Motion hourly cost",
      type: "number",
      unit: "currency/hour",
      required: true,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Hourly cost of unnecessary motion time.",
      expertMeaning: "Applied as unnecessaryMotionHours × motionHourlyCost.",
    },
    {
      id: "defectUnits",
      label: "Defect / scrap units",
      type: "number",
      unit: "units",
      required: true,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Scrap, waste, rework, or quality-defect units in the period.",
      expertMeaning: "Defect cost includes variable cost plus rework cost per defect.",
    },
    {
      id: "reworkCostPerDefect",
      label: "Rework cost per defect",
      type: "number",
      unit: "currency/unit",
      required: true,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Extra labor, material, or correction cost per defective unit.",
      expertMeaning: "Added to unitVariableCost inside defect waste.",
    },
    {
      id: "overprocessingHours",
      label: "Overprocessing hours",
      type: "number",
      unit: "hours",
      required: true,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Extra processing, inspection, approval, or unnecessary operation hours.",
      expertMeaning: "Multiplied by overprocessingHourlyCost.",
    },
    {
      id: "overprocessingHourlyCost",
      label: "Overprocessing hourly cost",
      type: "number",
      unit: "currency/hour",
      required: true,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Hourly cost of overprocessing time.",
      expertMeaning: "Applied as overprocessingHours × overprocessingHourlyCost.",
    },
    {
      id: "dataConfidencePercent",
      label: "Data confidence",
      type: "number",
      unit: "%",
      required: true,
      smartDefault: 70,
      validation: { min: 0, max: 100 },
      helper: "Your confidence that the entered waste drivers reflect actual shop-floor data.",
      expertMeaning: "Feeds confidenceLevel and riskAdjustedPriorityScore in the decision output.",
    },
    {
      id: "implementationDifficulty",
      label: "Implementation difficulty",
      type: "number",
      unit: "score",
      required: true,
      smartDefault: 3,
      validation: { min: 1, max: 5, step: 1 },
      helper: "How hard it is to implement fixes: 1 = easy kaizen, 5 = major capital or layout change.",
      expertMeaning: "Higher difficulty reduces riskAdjustedPriorityScore for otherwise large savings.",
    },
  ],

  formulaPipeline: [
    {
      formulaId: "lean.muda_overproduction_cost",
      inputMap: {
        excessUnits: "overproductionUnits",
        unitProductionCost: "unitVariableCost",
        inventoryHoldingRatePct: "inventoryCarryingRatePercent",
      },
      outputId: "overproductionCost",
    },
    {
      formulaId: "lean.muda_waiting_cost",
      inputMap: {
        waitingMinutes: "waitingHours",
        resourceMinuteCost: "manualHourlyOpportunityCost",
      },
      outputId: "waitingCost",
    },
    {
      formulaId: "lean.muda_transport_cost",
      inputMap: {
        transportDistanceKm: "unnecessaryTransportCost",
        transportTrips: "unnecessaryTransportCost",
        transportCostPerKm: "unnecessaryTransportCost",
      },
      outputId: "transportCost",
    },
    {
      formulaId: "lean.muda_inventory_cost",
      inputMap: {
        averageExcessInventoryValue: "excessInventoryValue",
        inventoryHoldingRatePct: "inventoryCarryingRatePercent",
      },
      outputId: "inventoryCost",
    },
    {
      formulaId: "lean.muda_motion_cost",
      inputMap: {
        unnecessaryMotionMinutes: "unnecessaryMotionHours",
        laborMinuteCost: "motionHourlyCost",
      },
      outputId: "motionCost",
    },
    {
      formulaId: "lean.muda_overprocessing_cost",
      inputMap: {
        overprocessingMinutes: "overprocessingHours",
        resourceMinuteCost: "overprocessingHourlyCost",
        extraMaterialCost: "overprocessingHourlyCost",
      },
      outputId: "overprocessingCost",
    },
    {
      formulaId: "lean.muda_defect_cost",
      inputMap: {
        scrapUnits: "defectUnits",
        unitProductionCost: "unitVariableCost",
        reworkMinutes: "reworkCostPerDefect",
        laborMinuteCost: "reworkCostPerDefect",
      },
      outputId: "defectCost",
    },
    {
      formulaId: "lean.muda_total_waste_cost",
      inputMap: {
        overproductionCost: "overproductionCost",
        waitingCost: "waitingCost",
        transportCost: "transportCost",
        inventoryCost: "inventoryCost",
        motionCost: "motionCost",
        overprocessingCost: "overprocessingCost",
        defectCost: "defectCost",
      },
      outputId: "totalWasteCost",
    },
    {
      formulaId: "lean.muda_annualized_waste_cost",
      inputMap: {},
      outputId: "annualizedWasteCost",
    },
    {
      formulaId: "lean.muda_waste_cost_per_unit",
      inputMap: {},
      outputId: "wasteCostPerUnit",
    },
    {
      formulaId: "lean.muda_period_revenue",
      inputMap: {},
      outputId: "periodRevenue",
    },
    {
      formulaId: "lean.muda_period_gross_margin_value",
      inputMap: {},
      outputId: "periodGrossMarginValue",
    },
    {
      formulaId: "lean.muda_waste_to_revenue_ratio_pct",
      inputMap: {},
      outputId: "wasteToRevenueRatioPct",
    },
    {
      formulaId: "lean.muda_waste_to_gross_margin_ratio_pct",
      inputMap: {},
      outputId: "wasteToGrossMarginRatioPct",
    },
    {
      formulaId: "lean.muda_highest_waste_cost",
      inputMap: {},
      outputId: "highestWasteCost",
    },
    {
      formulaId: "lean.muda_risk_adjusted_priority_score",
      inputMap: {},
      outputId: "riskAdjustedPriorityScore",
    },
    {
      formulaId: "lean.muda_highest_waste_index",
      inputMap: {
        overproductionCost: "overproductionCost",
        waitingCost: "waitingCost",
        transportCost: "transportCost",
        inventoryCost: "inventoryCost",
        motionCost: "motionCost",
        overprocessingCost: "overprocessingCost",
        defectCost: "defectCost",
      },
      outputId: "highestWasteCategoryIndex",
    },
  ],

  outputs: [
    {
      id: "totalWasteCost",
      label: "Total waste cost",
      unit: "USD",
      format: "currency",
      isBigNumber: true,
    },
    {
      id: "annualizedWasteCost",
      label: "Annualized waste cost",
      unit: "USD",
      format: "currency",
    },
    {
      id: "wasteCostPerUnit",
      label: "Waste cost per unit",
      unit: "USD",
      format: "currency",
    },
    {
      id: "periodRevenue",
      label: "Period revenue",
      unit: "USD",
      format: "currency",
    },
    {
      id: "periodGrossMarginValue",
      label: "Period gross margin value",
      unit: "USD",
      format: "currency",
    },
    {
      id: "wasteToRevenueRatioPct",
      label: "Waste to revenue ratio",
      unit: "%",
      format: "percentage",
    },
    {
      id: "wasteToGrossMarginRatioPct",
      label: "Waste to gross margin ratio",
      unit: "%",
      format: "percentage",
    },
    {
      id: "highestWasteCost",
      label: "Highest waste category cost",
      unit: "USD",
      format: "currency",
    },
    {
      id: "riskAdjustedPriorityScore",
      label: "Risk-adjusted priority score",
      unit: "score",
      format: "score",
    },
    {
      id: "overproductionCost",
      label: "Overproduction cost",
      unit: "USD",
      format: "currency",
    },
    {
      id: "waitingCost",
      label: "Waiting cost",
      unit: "USD",
      format: "currency",
    },
    {
      id: "transportCost",
      label: "Transport cost",
      unit: "USD",
      format: "currency",
    },
    {
      id: "inventoryCost",
      label: "Inventory cost",
      unit: "USD",
      format: "currency",
    },
    {
      id: "motionCost",
      label: "Motion cost",
      unit: "USD",
      format: "currency",
    },
    {
      id: "overprocessingCost",
      label: "Overprocessing cost",
      unit: "USD",
      format: "currency",
    },
    {
      id: "defectCost",
      label: "Defect cost",
      unit: "USD",
      format: "currency",
    },
    {
      id: "highestWasteCategoryIndex",
      label: "Highest waste category rank",
      unit: "rank",
      format: "number",
    },
  ],

  thresholds: [
    {
      fieldId: "totalWasteCost",
      warning: 5000,
      critical: 15000,
      direction: "higher_is_bad",
      warningMessage: "Total muda exposure is material — review the highest waste category and recommended action order.",
      criticalMessage: "Total muda exposure is severe — launch focused kaizen on the dominant waste driver.",
    },
  ],

  reportTemplate: {
    title: "7 Muda Monetary Impact Decision Report",
    sections: ["executive_summary", "loss_breakdown", "thresholds", "action_plan", "assumptions"],
    exportFormats: ["pdf", "csv"],
  },

  assumptions: {
    hiddenLossMultiplier: 1,
    volatilityPercent: 8,
    targetMarginPercent: 0,
    assumptionNotes: [
      "All monetary inputs must use the selected currency for the analysis period.",
      "productionUnits is the production volume inside the selected analysis period only.",
      "Waiting opportunity cost uses manual hourly rate or unit contribution margin per the selected mode.",
      "Inventory carrying cost prorates annual rate by analysisPeriodDays / annualWorkingDays.",
      "This tool produces operational loss estimates — not ERP reconciliation or audited financial statements.",
    ],
  },
};
