/**
 * Tool #8 — Auto Shop Marj Kaçak (Margin Leak)
 * EffectiveLaborRate → NetMargin → AnnualLeakage
 */
import type { PremiumCalculatorSchema } from "@/lib/premium-schema/premium-calculator-schema";
export const AUTO_SHOP_MARGIN_LEAK_SCHEMA: PremiumCalculatorSchema = {
  id: "auto-shop-margin-leak-analyzer", legacyPaidSlug: "auto-shop-margin-leak-analyzer",
  name: "Auto Shop Marj Kaçak Analizi", name_i18n: {"en":"Auto Shop Margin Leak Analysis","tr":"Auto Shop Marj Kaçak Analizi"}, sectorSlug: "auto-repair", category: "cost",
  painStatement: "Oto servislerde parça ve işçilik marjındaki küçük sapmalar yıllık yüz binlerce dolarlık kaçağa dönüşür. Bu araç marj yapısını analiz eder ve yıllık kaçağı hesaplar.", painStatement_i18n: {"en":"Oto servislerde parça ve işçilik marjındaki küçük sapmalar yıllık yüz binlerce dolarlık kaçağa dönüşür. Bu araç marj yapısını analiz eder ve yıllık kaçağı hesaplar.","tr":"Oto servislerde parça ve işçilik marjındaki küçük sapmalar yıllık yüz binlerce dolarlık kaçağa dönüşür. Bu araç marj yapısını analiz eder ve yıllık kaçağı hesaplar."},
  inputs: [
    { id: "monthlyPartsRevenue", label: "Aylık Parça Geliri", label_i18n: {"en":"Monthly Parts Revenue","tr":"Aylık Parça Geliri"}, type: "number", unit: "USD", required: true, smartDefault: 40000, validation: { min: 0 }, helper: "", expertMeaning: "Parts revenue per month", expertMeaning_i18n: {"en":"Parts revenue per month","tr":"Aylık parça geliri"} },
    { id: "monthlyLaborRevenue", label: "Aylık İşçilik Geliri", label_i18n: {"en":"Monthly Labor Revenue","tr":"Aylık İşçilik Geliri"}, type: "number", unit: "USD", required: true, smartDefault: 60000, validation: { min: 0 }, helper: "", expertMeaning: "Labor revenue per month", expertMeaning_i18n: {"en":"Labor revenue per month","tr":"Aylık işçilik geliri"} },
    { id: "partsCogs", label: "Parça COGS", label_i18n: {"en":"Parts COGS","tr":"Parça COGS"}, type: "number", unit: "USD", required: true, smartDefault: 28000, validation: { min: 0 }, helper: "", expertMeaning: "Parts cost of goods sold", expertMeaning_i18n: {"en":"Parts cost of goods sold","tr":"Parça satılan mal maliyeti"} },
    { id: "laborCost", label: "İşçilik Maliyeti", label_i18n: {"en":"Labor Cost","tr":"İşçilik Maliyeti"}, type: "number", unit: "USD", required: true, smartDefault: 36000, validation: { min: 0 }, helper: "", expertMeaning: "Direct labor cost", expertMeaning_i18n: {"en":"Direct labor cost","tr":"Direkt işçilik maliyeti"} },
    { id: "inventoryShrinkage", label: "Envanter Fire", label_i18n: {"en":"Inventory Shrinkage","tr":"Envanter Fire"}, type: "number", unit: "USD", required: false, smartDefault: 2000, validation: { min: 0 }, helper: "", expertMeaning: "Inventory shrinkage/loss", expertMeaning_i18n: {"en":"Inventory shrinkage/loss","tr":"Envanter fire/kaybı"} },
    { id: "totalFlagHours", label: "Flag Saatleri", label_i18n: {"en":"Flag Hours","tr":"Flag Saatleri"}, type: "number", unit: "saat", required: true, smartDefault: 800, validation: { min: 0 }, helper: "", expertMeaning: "Total billed hours", expertMeaning_i18n: {"en":"Total billed hours","tr":"Toplam faturalanan saat"} },
    { id: "totalAvailableHours", label: "Mevcut Saatler", label_i18n: {"en":"Available Hours","tr":"Mevcut Saatler"}, type: "number", unit: "saat", required: false, smartDefault: 1000, validation: { min: 0 }, helper: "", expertMeaning: "Total available technician hours", expertMeaning_i18n: {"en":"Total available technician hours","tr":"Toplam kullanılabilir teknisyen saati"} },
    { id: "totalOpEx", label: "Toplam OpEx", label_i18n: {"en":"Total OpEx","tr":"Toplam OpEx"}, type: "number", unit: "USD", required: false, smartDefault: 35000, validation: { min: 0 }, helper: "", expertMeaning: "Total operating expenses", expertMeaning_i18n: {"en":"Total operating expenses","tr":"Toplam işletme giderleri"} },
    { id: "industryBenchmarkMargin", label: "Sektör Benchmark Marjı", label_i18n: {"en":"Industry Benchmark Margin","tr":"Sektör Benchmark Marjı"}, type: "number", unit: "%", required: false, smartDefault: 15, validation: { min: 0, max: 100 }, helper: "", expertMeaning: "Industry average net margin", expertMeaning_i18n: {"en":"Industry average net margin","tr":"Sektör ortalama net marjı"} },
    { id: "monthlyDiscounts", label: "Aylık İskontolar", label_i18n: {"en":"Monthly Discounts","tr":"Aylık İskontolar"}, type: "number", unit: "USD", required: false, smartDefault: 3000, validation: { min: 0 }, helper: "", expertMeaning: "Total discounts given", expertMeaning_i18n: {"en":"Total discounts given","tr":"Verilen toplam indirimler"} },
    { id: "netMarginInput", label: "Net Marj (%)", label_i18n: {"en":"Net Margin (%)","tr":"Net Marj (%)"}, type: "number", unit: "%", required: true, smartDefault: 8, validation: { min: 0, max: 100 }, helper: "Mevcut net kâr marjınız.", helper_i18n: {"en":"Mevcut net kâr marjınız.","tr":"Mevcut net kâr marjınız."}, expertMeaning: "Current net profit margin percentage", expertMeaning_i18n: {"en":"Current net profit margin percentage","tr":"Güncel net kâr marjı yüzdesi"} },
  ],
  outputs: [
    { id: "grossMarginParts", label: "Parça Brüt Marjı", label_i18n: {"en":"Parça Brüt Marjı","tr":"Parça Brüt Marjı"}, unit: "%", format: "percentage" },
    { id: "effectiveLaborRate", label: "Efektif İşçilik Ücreti", label_i18n: {"en":"Efektif İşçilik Ücreti","tr":"Efektif İşçilik Ücreti"}, unit: "USD/saat", format: "currency" },
    { id: "netMargin", label: "Net Marj", label_i18n: {"en":"Net Marj","tr":"Net Marj"}, unit: "%", format: "percentage" },
    { id: "annualLeakage", label: "Yıllık Marj Kaçağı", label_i18n: {"en":"Yıllık Marj Kaçağı","tr":"Yıllık Marj Kaçağı"}, unit: "USD", format: "currency", isBigNumber: true },
  ],
  thresholds: [
    { fieldId: "annualLeakage", warning: 30000, critical: 100000, direction: "higher_is_bad", warningMessage: "Yıllık kaçak > $30K — fiyatlama gözden geçirilmeli.", warningMessage_i18n: {"en":"Yıllık kaçak > $30K — fiyatlama gözden geçirilmeli.","tr":"Yıllık kaçak > $30K — fiyatlama gözden geçirilmeli."}, criticalMessage: "Yıllık kaçak > $100K — acil marj iyileştirme programı başlatılmalı.", criticalMessage_i18n: {"en":"Yıllık kaçak > $100K — acil marj iyileştirme programı başlatılmalı.","tr":"Yıllık kaçak > $100K — acil marj iyileştirme programı başlatılmalı."} },
  ],
  formulaPipeline: [
    { formulaId: "cost.effective_labor_rate", inputMap: { laborRevenue: "monthlyLaborRevenue", flagHours: "totalFlagHours" }, outputId: "effectiveLaborRate" },
    { formulaId: "cost.annual_margin_leakage", inputMap: { totalRevenue: "monthlyLaborRevenue", targetMargin: "industryBenchmarkMargin", actualMargin: "netMarginInput" }, outputId: "annualLeakage" },
  ],
  reportTemplate: { title: "Auto Shop Margin Leak Report", title_i18n: {"en":"Auto Shop Margin Leak Report","tr":"Auto Shop Margin Leak Report"}, sections: ["executive_summary", "loss_breakdown", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.15, volatilityPercent: 10, targetMarginPercent: 20, assumptionNotes: ["Gross margin = (Revenue - COGS) / Revenue. Parts margin excludes labor.", "Effective labor rate = Labor revenue / Flag hours.", "Net margin = (Total Revenue - COGS - OpEx) / Total Revenue.", "Annual leakage = Monthly revenue × (Target margin - Net margin) × 12."],assumptionNotes_i18n:[{"en":"Gross margin = (Revenue - COGS) / Revenue. Parts margin excludes labor.","tr":"Gross margin = (Revenue - COGS) / Revenue. Parts margin excludes labor."},{"en":"Effective labor rate = Labor revenue / Flag hours.","tr":"Effective labor rate = Labor revenue / Flag hours."},{"en":"Net margin = (Total Revenue - COGS - OpEx) / Total Revenue.","tr":"Net margin = (Total Revenue - COGS - OpEx) / Total Revenue."},{"en":"Annual leakage = Monthly revenue × (Target margin - Net margin) × 12.","tr":"Annual leakage = Monthly revenue × (Target margin - Net margin) × 12."}]},
};
