/**
 * Tool #11 — Başabaş Noktası & Güvenlik Marjı
 * BEP_Units → CMR → BEP_Revenue → MoS → OperatingLeverage → TargetProfit
 */
import type { PremiumCalculatorSchema } from "@/lib/premium-schema/premium-calculator-schema";
export const BREAK_EVEN_SCHEMA: PremiumCalculatorSchema = {
  id: "break-even-margin-of-safety-analyzer", legacyPaidSlug: "break-even-margin-of-safety-analyzer",
  name: "Başabaş Noktası & Güvenlik Marjı Analizi", name_i18n: {"en":"Break-Even & Margin of Safety Analysis","tr":"Başabaş Noktası & Güvenlik Marjı Analizi", sectorSlug: "financial-planning", category: "finance",
  painStatement: "Başabaş noktası bilinmeden yapılan fiyatlama ya marj baskısı ya da satış kaybına yol açar. Bu araç CVP analizi ile başabaş noktası, güvenlik marjı ve faaliyet kaldıracını hesaplar.", painStatement_i18n: {"en":"Pricing without knowing the break-even point causes either margin pressure or lost sales. This tool calculates break-even, margin of safety, and operating leverage via CVP analysis.","tr":"Başabaş noktası bilinmeden yapılan fiyatlama ya marj baskısı ya da satış kaybına yol açar. Bu araç CVP analizi ile başabaş noktası, güvenlik marjı ve faaliyet kaldıracını hesaplar.",
  inputs: [
    { id: "fixedCosts", label: "Sabit Maliyetler", label_i18n: {"en":"Sabit Maliyetler","tr":"Sabit Maliyetler"}, type: "number", unit: "USD", required: true, smartDefault: 50000, validation: { min: 1 }, helper: "Kira, maaş, sigorta gibi sabit giderler toplamı.", helper_i18n: {"en":"Kira, maaş, sigorta gibi sabit giderler toplamı.","tr":"Kira, maaş, sigorta gibi sabit giderler toplamı."}, expertMeaning: "Total fixed costs", expertMeaning_i18n: {"en":"Total fixed costs","tr":"Total fixed costs" },
    { id: "unitVariableCost", label: "Birim Değişken Maliyet", label_i18n: {"en":"Unit Variable Cost","tr":"Birim Değişken Maliyet", type: "number", unit: "USD", required: true, smartDefault: 30, validation: { min: 0.01 }, helper: "Birim başına değişken maliyet (hammadde, işçilik).", helper_i18n: {"en":"Birim başına değişken maliyet (hammadde, işçilik).","tr":"Birim başına değişken maliyet (hammadde, işçilik)."}, expertMeaning: "Variable cost per unit", expertMeaning_i18n: {"en":"Variable cost per unit","tr":"Variable cost per unit" },
    { id: "unitPrice", label: "Birim Satış Fiyatı", label_i18n: {"en":"Unit Selling Price","tr":"Birim Satış Fiyatı", type: "number", unit: "USD", required: true, smartDefault: 50, validation: { min: 0.01 }, helper: "Ürün başına satış fiyatı.", helper_i18n: {"en":"Ürün başına satış fiyatı.","tr":"Ürün başına satış fiyatı."}, expertMeaning: "Selling price per unit", expertMeaning_i18n: {"en":"Selling price per unit","tr":"Selling price per unit" },
    { id: "actualSalesUnits", label: "Güncel Satış Hacmi", label_i18n: {"en":"Current Sales Volume","tr":"Güncel Satış Hacmi", type: "number", unit: "adet", required: true, smartDefault: 3000, validation: { min: 0 }, helper: "Mevcut satış adedi.", helper_i18n: {"en":"Mevcut satış adedi.","tr":"Mevcut satış adedi."}, expertMeaning: "Actual sales volume", expertMeaning_i18n: {"en":"Actual sales volume","tr":"Actual sales volume" },
    { id: "actualRevenue", label: "Güncel Gelir", label_i18n: {"en":"Güncel Gelir","tr":"Güncel Gelir"}, type: "number", unit: "USD", required: false, smartDefault: 150000, validation: { min: 0 }, helper: "Toplam ciro.", helper_i18n: {"en":"Total revenue.","tr":"Toplam ciro.", expertMeaning: "Actual revenue", expertMeaning_i18n: {"en":"Actual revenue","tr":"Actual revenue" },
    { id: "targetProfit", label: "Hedef Kâr", label_i18n: {"en":"Hedef Kâr","tr":"Hedef Kâr"}, type: "number", unit: "USD", required: false, smartDefault: 50000, validation: { min: 0 }, helper: "Ulaşılmak istenen kâr hedefi.", helper_i18n: {"en":"Ulaşılmak istenen kâr hedefi.","tr":"Ulaşılmak istenen kâr hedefi."}, expertMeaning: "Target profit amount", expertMeaning_i18n: {"en":"Target profit amount","tr":"Target profit amount" },
    { id: "contributionMarginTotal", label: "Toplam Katkı Marjı", label_i18n: {"en":"Toplam Katkı Marjı","tr":"Toplam Katkı Marjı"}, type: "number", unit: "USD", required: false, smartDefault: 60000, validation: { min: 0 }, helper: "(Birim fiyat - BM) × satış adedi.", helper_i18n: {"en":"(Birim fiyat - BM) × satış adedi.","tr":"(Birim fiyat - BM) × satış adedi."}, expertMeaning: "Total contribution margin", expertMeaning_i18n: {"en":"Total contribution margin","tr":"Total contribution margin" },
    { id: "netOpIncome", label: "Net Faaliyet Kârı", label_i18n: {"en":"Net Faaliyet Kârı","tr":"Net Faaliyet Kârı"}, type: "number", unit: "USD", required: false, smartDefault: 10000, validation: { min: 0 }, helper: "Katkı marjı - sabit giderler.", helper_i18n: {"en":"Katkı marjı - sabit giderler.","tr":"Katkı marjı - sabit giderler."}, expertMeaning: "Net operating income", expertMeaning_i18n: {"en":"Net operating income","tr":"Net operating income" },
    { id: "unitCm", label: "Birim Katkı Marjı", label_i18n: {"en":"Birim Katkı Marjı","tr":"Birim Katkı Marjı"}, type: "number", unit: "USD", required: false, smartDefault: 20, validation: { min: 0 }, helper: "Birim fiyat - birim değişken maliyet.", helper_i18n: {"en":"Birim fiyat - birim değişken maliyet.","tr":"Birim fiyat - birim değişken maliyet."}, expertMeaning: "Unit contribution margin", expertMeaning_i18n: {"en":"Unit contribution margin","tr":"Unit contribution margin" },
  ],
  outputs: [
    { id: "bepUnits", label: "Başabaş Noktası (Birim)", label_i18n: {"en":"Başabaş Noktası (Birim)","tr":"Başabaş Noktası (Birim)"}, unit: "adet", format: "number" },
    { id: "bepRevenue", label: "Başabaş Noktası (Gelir)", label_i18n: {"en":"Başabaş Noktası (Gelir)","tr":"Başabaş Noktası (Gelir)"}, unit: "USD", format: "currency" },
    { id: "cmr", label: "Katkı Marjı Oranı", label_i18n: {"en":"Katkı Marjı Oranı","tr":"Katkı Marjı Oranı"}, unit: "%", format: "percentage" },
    { id: "marginOfSafetyPct", label: "Güvenlik Marjı", label_i18n: {"en":"Güvenlik Marjı","tr":"Güvenlik Marjı"}, unit: "%", format: "percentage" },
    { id: "operatingLeverage", label: "Faaliyet Kaldıracı (DOL)", label_i18n: {"en":"Faaliyet Kaldıracı (DOL)","tr":"Faaliyet Kaldıracı (DOL)"}, unit: "", format: "number" },
    { id: "targetProfitUnits", label: "Hedef Kâr İçin Gerekli Satış", label_i18n: {"en":"Hedef Kâr İçin Gerekli Satış","tr":"Hedef Kâr İçin Gerekli Satış"}, unit: "adet", format: "number" },
    { id: "bepVerdict", label: "Kârlılık Durumu", label_i18n: {"en":"Kârlılık Durumu","tr":"Kârlılık Durumu"}, unit: "", format: "score", isBigNumber: true },
  ],
  thresholds: [
    { fieldId: "marginOfSafetyPct", warning: 20, critical: 10, direction: "lower_is_bad", warningMessage: "Güvenlik marjı < %20 — satış düşüşüne karşı kırılgan.", warningMessage_i18n: {"en":"Margin of safety < 20% — vulnerable to sales decline.","tr":"Güvenlik marjı < %20 — satış düşüşüne karşı kırılgan.", criticalMessage: "Güvenlik marjı < %10 — satışdaki küçük düşüş zarara sokar.", criticalMessage_i18n: {"en":"Margin of safety < 10% — small sales decline causes loss.","tr":"Güvenlik marjı < %10 — satışdaki küçük düşüş zarara sokar." },
  ],
  formulaPipeline: [
    { formulaId: "cost.bep_units", inputMap: { fixedCosts: "fixedCosts", unitPrice: "unitPrice", unitVariableCost: "unitVariableCost" }, outputId: "bepUnits" },
    { formulaId: "cost.cmr", inputMap: { unitPrice: "unitPrice", unitVariableCost: "unitVariableCost" }, outputId: "cmr" },
    { formulaId: "cost.bep_revenue", inputMap: { fixedCosts: "fixedCosts", cmr: "cmr" }, outputId: "bepRevenue" },
    { formulaId: "cost.margin_of_safety_pct", inputMap: { actualSales: "actualSalesUnits", bepUnits: "bepUnits" }, outputId: "marginOfSafetyPct" },
    { formulaId: "cost.operating_leverage", inputMap: { contributionMargin: "contributionMarginTotal", netOperatingIncome: "netOpIncome" }, outputId: "operatingLeverage" },
    { formulaId: "cost.target_profit_units", inputMap: { fixedCosts: "fixedCosts", targetProfit: "targetProfit", unitContributionMargin: "unitCm" }, outputId: "targetProfitUnits" },
  ],
  reportTemplate: { title: "Break-Even & Margin of Safety Report", title_i18n: {"en":"Break-Even & Margin of Safety Report","tr":"Break-Even & Margin of Safety Report"}, sections: ["executive_summary", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.1, volatilityPercent: 10, targetMarginPercent: 15, assumptionNotes: ["BEP Units = Fixed Costs / (Price - Variable Cost).", "CMR = (Price - Variable Cost) / Price.", "Margin of Safety = (Actual Sales - BEP) / Actual Sales * 100.", "DOL = Contribution Margin / Net Operating Income.", "Assumes linear cost behavior and single product."],assumptionNotes_i18n:[{"en":"BEP Units = Fixed Costs / (Price - Variable Cost).","tr":"BEP Units = Fixed Costs / (Price - Variable Cost)."},{"en":"CMR = (Price - Variable Cost) / Price.","tr":"CMR = (Price - Variable Cost) / Price."},{"en":"Margin of Safety = (Actual Sales - BEP) / Actual Sales * 100.","tr":"Margin of Safety = (Actual Sales - BEP) / Actual Sales * 100."},{"en":"DOL = Contribution Margin / Net Operating Income.","tr":"DOL = Contribution Margin / Net Operating Income."},{"en":"Assumes linear cost behavior and single product.","tr":"Assumes linear cost behavior and single product."}] },
};
