/**
 * Tool #16 — Chatter Yüzey Kalite Kaybı
 * V_c → f_z → SurfaceRoughness → QualityLossCost
 */
import type { PremiumCalculatorSchema } from "@/lib/premium-schema/premium-calculator-schema";
export const CHATTER_SCHEMA: PremiumCalculatorSchema = {
  id: "chatter-surface-quality-analyzer", legacyPaidSlug: "chatter-surface-quality-analyzer",
  name: "Chatter Yüzey Kalite Kaybı Analizi", name_i18n: {"en":"Chatter Surface Quality Loss Analysis","tr":"Chatter Yüzey Kalite Kaybı Analizi"}, sectorSlug: "cnc-manufacturing", category: "measurement",
  painStatement: "CNC işlemede chatter (titreşim) yüzey pürüzlülüğünü artırır, tolerans dışı parça ve hurda oranını yükseltir. Bu araç kesme parametrelerinden yola çıkarak yüzey kalitesi kaybını hesaplar.", painStatement_i18n: {"en":"In CNC machining, chatter (vibration) increases surface roughness, raising out-of-tolerance part and scrap rates. This tool calculates quality loss based on cutting parameters.","tr":"CNC işlemede chatter (titreşim) yüzey pürüzlülüğünü artırır, tolerans dışı parça ve hurda oranını yükseltir. Bu araç kesme parametrelerinden yola çıkarak yüzey kalitesi kaybını hesaplar."},
  inputs: [
    { id: "cuttingSpeed", label: "Kesme Hızı (V_c)", label_i18n: {"en":"Cutting Speed (V_c)","tr":"Kesme Hızı (V_c)"}, type: "number", unit: "m/dak", required: true, smartDefault: 150, validation: { min: 1 }, helper: "", expertMeaning: "Cutting speed", expertMeaning_i18n: {"en":"Cutting speed","tr":"Kesme hızı"} },
    { id: "spindleRpm", label: "Devir (n)", label_i18n: {"en":"Spindle Speed (n)","tr":"Devir (n)"}, type: "number", unit: "rpm", required: true, smartDefault: 3000, validation: { min: 1 }, helper: "", expertMeaning: "Spindle speed", expertMeaning_i18n: {"en":"Spindle speed","tr":"Devir hızı"} },
    { id: "feedRate", label: "İlerleme (V_f)", label_i18n: {"en":"Feed Rate (V_f)","tr":"İlerleme (V_f)"}, type: "number", unit: "mm/dak", required: true, smartDefault: 600, validation: { min: 0.1 }, helper: "", expertMeaning: "Feed rate", expertMeaning_i18n: {"en":"Feed rate","tr":"İlerleme hızı"} },
    { id: "toothCount", label: "Diş Sayısı (z)", label_i18n: {"en":"Number of Teeth (z)","tr":"Diş Sayısı (z)"}, type: "number", unit: "", required: true, smartDefault: 4, validation: { min: 1 }, helper: "", expertMeaning: "Number of cutting teeth", expertMeaning_i18n: {"en":"Number of cutting teeth","tr":"Kesici diş sayısı"} },
    { id: "toolNoseRadius", label: "Takım Ucu Radyusu (r_epsilon)", label_i18n: {"en":"Tool Nose Radius (r_epsilon)","tr":"Takım Ucu Radyusu (r_epsilon)"}, type: "number", unit: "mm", required: true, smartDefault: 0.8, validation: { min: 0.01 }, helper: "", expertMeaning: "Insert nose radius", expertMeaning_i18n: {"en":"Insert nose radius","tr":"Kesici uç radyusu"} },
    { id: "chatterAmplification", label: "Titreşim Genliği (chatter faktörü)", label_i18n: {"en":"Vibration Amplitude (chatter factor)","tr":"Titreşim Genliği (chatter faktörü)"}, type: "number", unit: "%", required: false, smartDefault: 30, validation: { min: 0, max: 500 }, helper: "", expertMeaning: "Chatter amplification over theoretical Ra", expertMeaning_i18n: {"en":"Chatter amplification over theoretical Ra","tr":"Teorik Ra üzerinde titreşim amplifikasyonu"} },
    { id: "surfaceRoughnessLimitRa", label: "Yüzey Pürüzlülüğü Limiti (Ra)", label_i18n: {"en":"Surface Roughness Limit (Ra)","tr":"Yüzey Pürüzlülüğü Limiti (Ra)"}, type: "number", unit: "µm", required: true, smartDefault: 1.6, validation: { min: 0.01 }, helper: "", expertMeaning: "Maximum allowed Ra per spec", expertMeaning_i18n: {"en":"Maximum allowed Ra per spec","tr":"Spesifikasyona göre izin verilen maksimum Ra"} },
    { id: "maxToleranceRa", label: "Maksimum Tolerans (Ra_max)", label_i18n: {"en":"Maximum Tolerance (Ra_max)","tr":"Maksimum Tolerans (Ra_max)"}, type: "number", unit: "µm", required: false, smartDefault: 3.2, validation: { min: 0.01 }, helper: "", expertMeaning: "Absolute max Ra — beyond = scrap", expertMeaning_i18n: {"en":"Absolute max Ra — beyond = scrap","tr":"Mutlak maksimum Ra — aşarsa hurda"} },
    { id: "batchSize", label: "Parti Büyüklüğü", label_i18n: {"en":"Batch Size","tr":"Parti Büyüklüğü"}, type: "number", unit: "adet", required: false, smartDefault: 500, validation: { min: 0 }, helper: "", expertMeaning: "Batch size for scrap calculation", expertMeaning_i18n: {"en":"Batch size for scrap calculation","tr":"Hurda hesaplaması için parti büyüklüğü"} },
    { id: "reworkCostPerMicron", label: "Yeniden İşleme Maliyeti", label_i18n: {"en":"Rework Cost","tr":"Yeniden İşleme Maliyeti"}, type: "number", unit: "USD/µm", required: false, smartDefault: 2, validation: { min: 0 }, helper: "", expertMeaning: "Rework cost per micron overshoot", expertMeaning_i18n: {"en":"Rework cost per micron overshoot","tr":"Mikron başına yeniden işleme maliyeti"} },
  ],
  outputs: [
    { id: "cuttingSpeedResult", label: "Kesme Hızı (V_c)", label_i18n: {"en":"Cutting Speed (V_c)","tr":"Kesme Hızı (V_c)"}, unit: "m/dak", format: "number" },
    { id: "chipLoad", label: "Talaş Kalınlığı (f_z)", label_i18n: {"en":"Chip Load (f_z)","tr":"Talaş Kalınlığı (f_z)"}, unit: "mm/diş", format: "number" },
    { id: "theoreticalRa", label: "Teorik Yüzey Pürüzlülüğü (Ra)", label_i18n: {"en":"Theoretical Surface Roughness (Ra)","tr":"Teorik Yüzey Pürüzlülüğü (Ra)"}, unit: "µm", format: "number" },
    { id: "actualRa", label: "Gerçek Yüzey Pürüzlülüğü (Ra)", label_i18n: {"en":"Actual Surface Roughness (Ra)","tr":"Gerçek Yüzey Pürüzlülüğü (Ra)"}, unit: "µm", format: "number" },
    { id: "qualityLossCost", label: "Kalite Kaybı Maliyeti", label_i18n: {"en":"Quality Loss Cost","tr":"Kalite Kaybı Maliyeti"}, unit: "USD", format: "currency", isBigNumber: true },
  ],
  thresholds: [
    { fieldId: "actualRa", warning: 1.6, critical: 3.2, direction: "higher_is_bad", warningMessage: "Ra > 1.6 µm — yeniden işleme riski var.", warningMessage_i18n: {"en":"Ra > 1.6 µm — rework risk exists.","tr":"Ra > 1.6 µm — yeniden işleme riski var."}, criticalMessage: "Ra > 3.2 µm — hurda riski yüksek, kesme parametreleri düzeltilmeli.", criticalMessage_i18n: {"en":"Ra > 3.2 µm — scrap risk high, cutting parameters should be corrected.","tr":"Ra > 3.2 µm — hurda riski yüksek, kesme parametreleri düzeltilmeli."} },
  ],
  formulaPipeline: [
    { formulaId: "measurement.cutting_speed", inputMap: { diameter: "cuttingSpeed", rpm: "spindleRpm" }, outputId: "cuttingSpeedResult" },
    { formulaId: "measurement.chip_load", inputMap: { feedRate: "feedRate", toothCount: "toothCount", rpm: "spindleRpm" }, outputId: "chipLoad" },
    { formulaId: "measurement.surface_roughness_theoretical", inputMap: { chipLoad: "chipLoad", noseRadius: "toolNoseRadius" }, outputId: "theoreticalRa" },
    { formulaId: "measurement.surface_roughness_actual", inputMap: { theoreticalRa: "theoreticalRa", chatterAmplification: "chatterAmplification" }, outputId: "actualRa" },
    { formulaId: "cost.chatter_quality_loss", inputMap: { actualRa: "actualRa", toleranceLimit: "surfaceRoughnessLimitRa", reworkCostPerMicron: "reworkCostPerMicron" }, outputId: "qualityLossCost" },
  ],
  reportTemplate: { title: "Chatter Surface Quality Report", title_i18n: {"en":"Chatter Surface Quality Report","tr":"Chatter Surface Quality Report"}, sections: ["executive_summary", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.15, volatilityPercent: 15, targetMarginPercent: 20, assumptionNotes: ["V_c = π × D × n / 1000 (m/min). f_z = V_f / (z × n) (mm/tooth).", "Ra_theoretical = f_z² / (8 × r_epsilon) (µm).", "Ra_actual = Ra_theoretical × (1 + chatter/100).", "Quality loss = (Ra_actual - Ra_limit) × rework cost per micron.", "Scrap if Ra_actual > Ra_max: batch × unit cost."],assumptionNotes_i18n:[{"en":"V_c = π × D × n / 1000 (m/min). f_z = V_f / (z × n) (mm/tooth).","tr":"V_c = π × D × n / 1000 (m/min). f_z = V_f / (z × n) (mm/tooth)."},{"en":"Ra_theoretical = f_z² / (8 × r_epsilon) (µm).","tr":"Ra_theoretical = f_z² / (8 × r_epsilon) (µm)."},{"en":"Ra_actual = Ra_theoretical × (1 + chatter/100).","tr":"Ra_actual = Ra_theoretical × (1 + chatter/100)."},{"en":"Quality loss = (Ra_actual - Ra_limit) × rework cost per micron.","tr":"Quality loss = (Ra_actual - Ra_limit) × rework cost per micron."},{"en":"Scrap if Ra_actual > Ra_max: batch × unit cost.","tr":"Scrap if Ra_actual > Ra_max: batch × unit cost."}] },
};
