/**
 * Tool #20 — Cloud Fire Elimination (Bulut İsraf Temizliği)
 * ZombieResource + OversizingSavings + SpotSavings + ReservedSavings + IdleHoursCost
 */
import type { PremiumCalculatorSchema } from "@/lib/premium-schema/premium-calculator-schema";
export const CLOUD_WASTE_ELIMINATION_SCHEMA: PremiumCalculatorSchema = {
  id: "cloud-waste-elimination-analyzer", legacyPaidSlug: "cloud-waste-elimination-analyzer",
  name: "Cloud İsraf Temizliği (Waste Elimination) Analizi", name_i18n: {"en":"Cloud İsraf Temizliği (Waste Elimination) Analizi","tr":"Cloud İsraf Temizliği (Waste Elimination) Analizi"}, sectorSlug: "it-cloud", category: "cost",
  painStatement: "Bulut harcamalarının %30-45'i gereksiz kaynaklardan oluşur: zombie kaynaklar, aşırı boyutlandırma ve boşta çalışan instance'lar. Bu araç toplam israfı hesaplar ve tasarruf potansiyelini gösterir.", painStatement_i18n: {"en":"Bulut harcamalarının %30-45'i gereksiz kaynaklardan oluşur: zombie kaynaklar, aşırı boyutlandırma ve boşta çalışan instance'lar. Bu araç toplam israfı hesaplar ve tasarruf potansiyelini gösterir.","tr":"Bulut harcamalarının %30-45'i gereksiz kaynaklardan oluşur: zombie kaynaklar, aşırı boyutlandırma ve boşta çalışan instance'lar. Bu araç toplam israfı hesaplar ve tasarruf potansiyelini gösterir."},
  inputs: [
    { id: "unattachedVolumes", label: "Bağımsız Disk Sayısı", label_i18n: {"en":"Bağımsız Disk Sayısı","tr":"Bağımsız Disk Sayısı"}, type: "number", unit: "adet", required: true, smartDefault: 10, validation: { min: 0 }, helper: "", expertMeaning: "Unattached EBS volumes", expertMeaning_i18n: {"en":"Unattached EBS volumes","tr":"Unattached EBS volumes"} },
    { id: "volumeRatePerMonth", label: "Disk Birim Fiyat", label_i18n: {"en":"Disk Birim Fiyat","tr":"Disk Birim Fiyat"}, type: "number", unit: "USD/ay", required: true, smartDefault: 10, validation: { min: 0 }, helper: "", expertMeaning: "Monthly cost per unattached volume", expertMeaning_i18n: {"en":"Monthly cost per unattached volume","tr":"Monthly cost per unattached volume"} },
    { id: "orphanSnapshotGb", label: "Atıl Snapshot Boyutu", label_i18n: {"en":"Atıl Snapshot Boyutu","tr":"Atıl Snapshot Boyutu"}, type: "number", unit: "GB", required: false, smartDefault: 500, validation: { min: 0 }, helper: "", expertMeaning: "Orphaned snapshots total GB", expertMeaning_i18n: {"en":"Orphaned snapshots total GB","tr":"Orphaned snapshots total GB"} },
    { id: "snapshotStorageRate", label: "Snapshot Depolama Ücreti", label_i18n: {"en":"Snapshot Depolama Ücreti","tr":"Snapshot Depolama Ücreti"}, type: "number", unit: "USD/GB/ay", required: false, smartDefault: 0.05, validation: { min: 0 }, helper: "", expertMeaning: "S3/EFS snapshot cost per GB", expertMeaning_i18n: {"en":"S3/EFS snapshot cost per GB","tr":"S3/EFS snapshot cost per GB"} },
    { id: "currentInstanceCost", label: "Mevcut Instance Maliyeti", label_i18n: {"en":"Mevcut Instance Maliyeti","tr":"Mevcut Instance Maliyeti"}, type: "number", unit: "USD/ay", required: true, smartDefault: 5000, validation: { min: 0 }, helper: "", expertMeaning: "Current monthly compute cost", expertMeaning_i18n: {"en":"Current monthly compute cost","tr":"Current monthly compute cost"} },
    { id: "rightSizedInstanceCost", label: "Right-Sized Instance Maliyeti", label_i18n: {"en":"Right-Sized Instance Maliyeti","tr":"Right-Sized Instance Maliyeti"}, type: "number", unit: "USD/ay", required: true, smartDefault: 3500, validation: { min: 0 }, helper: "", expertMeaning: "Optimized monthly compute cost", expertMeaning_i18n: {"en":"Optimized monthly compute cost","tr":"Optimized monthly compute cost"} },
    { id: "spotUsageRatio", label: "Spot Kullanım Oranı", label_i18n: {"en":"Spot Kullanım Oranı","tr":"Spot Kullanım Oranı"}, type: "number", unit: "%", required: false, smartDefault: 20, validation: { min: 0, max: 100 }, helper: "", expertMeaning: "Current spot adoption", expertMeaning_i18n: {"en":"Current spot adoption","tr":"Current spot adoption"} },
    { id: "targetSpotRatio", label: "Hedef Spot Oranı", label_i18n: {"en":"Hedef Spot Oranı","tr":"Hedef Spot Oranı"}, type: "number", unit: "%", required: false, smartDefault: 50, validation: { min: 0, max: 100 }, helper: "", expertMeaning: "Target spot adoption", expertMeaning_i18n: {"en":"Target spot adoption","tr":"Target spot adoption"} },
    { id: "onDemandCost", label: "On-Demand Aylık Maliyet", label_i18n: {"en":"On-Demand Aylık Maliyet","tr":"On-Demand Aylık Maliyet"}, type: "number", unit: "USD", required: false, smartDefault: 3000, validation: { min: 0 }, helper: "", expertMeaning: "On-demand spend eligible for RI", expertMeaning_i18n: {"en":"On-demand spend eligible for RI","tr":"On-demand spend eligible for RI"} },
    { id: "reservedCost", label: "Reserved Instance Aylık Maliyet", label_i18n: {"en":"Reserved Instance Aylık Maliyet","tr":"Reserved Instance Aylık Maliyet"}, type: "number", unit: "USD", required: false, smartDefault: 2000, validation: { min: 0 }, helper: "", expertMeaning: "Reserved instance cost", expertMeaning_i18n: {"en":"Reserved instance cost","tr":"Reserved instance cost"} },
    { id: "nonBizHoursInstances", label: "Mesai Dışı Çalışan Sunucu Sayısı", label_i18n: {"en":"Mesai Dışı Çalışan Sunucu Sayısı","tr":"Mesai Dışı Çalışan Sunucu Sayısı"}, type: "number", unit: "adet", required: false, smartDefault: 5, validation: { min: 0 }, helper: "", expertMeaning: "Instances running 24/7 unnecessarily", expertMeaning_i18n: {"en":"Instances running 24/7 unnecessarily","tr":"Instances running 24/7 unnecessarily"} },
    { id: "nonBizHoursPerMonth", label: "Mesai Dışı Saat/Ay", label_i18n: {"en":"Mesai Dışı Saat/Ay","tr":"Mesai Dışı Saat/Ay"}, type: "number", unit: "saat", required: false, smartDefault: 300, validation: { min: 0 }, helper: "", expertMeaning: "Non-business hours per month", expertMeaning_i18n: {"en":"Non-business hours per month","tr":"Non-business hours per month"} },
    { id: "instanceHourlyRate", label: "Instance Saatlik Maliyet", label_i18n: {"en":"Instance Saatlik Maliyet","tr":"Instance Saatlik Maliyet"}, type: "number", unit: "USD/saat", required: false, smartDefault: 0.50, validation: { min: 0 }, helper: "", expertMeaning: "Average hourly instance cost", expertMeaning_i18n: {"en":"Average hourly instance cost","tr":"Average hourly instance cost"} },
    { id: "zombieCostInput", label: "Zombie Kaynak Maliyeti (Tahmini)", label_i18n: {"en":"Zombie Kaynak Maliyeti (Tahmini)","tr":"Zombie Kaynak Maliyeti (Tahmini)"}, type: "number", unit: "USD/ay", required: false, smartDefault: 350, validation: { min: 0 }, helper: "Bağımsız diskler + atıl snapshotlar.", helper_i18n: {"en":"Bağımsız diskler + atıl snapshotlar.","tr":"Bağımsız diskler + atıl snapshotlar."}, expertMeaning: "Zombie resource cost per month", expertMeaning_i18n: {"en":"Zombie resource cost per month","tr":"Zombie resource cost per month"} },
    { id: "oversizingSavingsInput", label: "Aşırı Boyutlandırma Tasarrufu", label_i18n: {"en":"Aşırı Boyutlandırma Tasarrufu","tr":"Aşırı Boyutlandırma Tasarrufu"}, type: "number", unit: "USD/ay", required: false, smartDefault: 1500, validation: { min: 0 }, helper: "Mevcut - right-sized farkı.", helper_i18n: {"en":"Mevcut - right-sized farkı.","tr":"Mevcut - right-sized farkı."}, expertMeaning: "Monthly oversizing waste", expertMeaning_i18n: {"en":"Monthly oversizing waste","tr":"Monthly oversizing waste"} },
    { id: "spotSavingsInput", label: "Spot Instance Tasarruf Potansiyeli", label_i18n: {"en":"Spot Instance Tasarruf Potansiyeli","tr":"Spot Instance Tasarruf Potansiyeli"}, type: "number", unit: "USD/ay", required: false, smartDefault: 450, validation: { min: 0 }, helper: "Spot kullanım artışından tasarruf.", helper_i18n: {"en":"Spot kullanım artışından tasarruf.","tr":"Spot kullanım artışından tasarruf."}, expertMeaning: "Additional spot savings potential", expertMeaning_i18n: {"en":"Additional spot savings potential","tr":"Additional spot savings potential"} },
    { id: "reservedSavingsInput", label: "Reserved Instance Tasarrufu", label_i18n: {"en":"Reserved Instance Tasarrufu","tr":"Reserved Instance Tasarrufu"}, type: "number", unit: "USD/ay", required: false, smartDefault: 600, validation: { min: 0 }, helper: "Reserved vs on-demand farkı.", helper_i18n: {"en":"Reserved vs on-demand farkı.","tr":"Reserved vs on-demand farkı."}, expertMeaning: "RI savings per month", expertMeaning_i18n: {"en":"RI savings per month","tr":"RI savings per month"} },
    { id: "idleHoursCostInput", label: "Boşta Çalışan Instance Maliyeti", label_i18n: {"en":"Boşta Çalışan Instance Maliyeti","tr":"Boşta Çalışan Instance Maliyeti"}, type: "number", unit: "USD/ay", required: false, smartDefault: 750, validation: { min: 0 }, helper: "Mesai dışı çalışan instance'lar.", helper_i18n: {"en":"Mesai dışı çalışan instance'lar.","tr":"Mesai dışı çalışan instance'lar."}, expertMeaning: "Non-business hours instance cost", expertMeaning_i18n: {"en":"Non-business hours instance cost","tr":"Non-business hours instance cost"} },
  ],
  outputs: [
    { id: "zombieResourceCost", label: "Zombie Kaynak Maliyeti", label_i18n: {"en":"Zombie Kaynak Maliyeti","tr":"Zombie Kaynak Maliyeti"}, unit: "USD/ay", format: "currency" },
    { id: "oversizingSavings", label: "Aşırı Boyutlandırma Tasarrufu", label_i18n: {"en":"Aşırı Boyutlandırma Tasarrufu","tr":"Aşırı Boyutlandırma Tasarrufu"}, unit: "USD/ay", format: "currency" },
    { id: "idleHoursCost", label: "Boşta Çalışan Instance Maliyeti", label_i18n: {"en":"Boşta Çalışan Instance Maliyeti","tr":"Boşta Çalışan Instance Maliyeti"}, unit: "USD/ay", format: "currency" },
    { id: "totalWasteEliminated", label: "Toplam İsraf (Aylık)", label_i18n: {"en":"Toplam İsraf (Aylık)","tr":"Toplam İsraf (Aylık)"}, unit: "USD/ay", format: "currency", isBigNumber: true },
  ],
  thresholds: [
    { fieldId: "totalWasteEliminated", warning: 2000, critical: 10000, direction: "higher_is_bad", warningMessage: "Aylık israf > $2K — bulut maliyet optimizasyonu planı başlatılmalı.", warningMessage_i18n: {"en":"Aylık israf > $2K — bulut maliyet optimizasyonu planı başlatılmalı.","tr":"Aylık israf > $2K — bulut maliyet optimizasyonu planı başlatılmalı."}, criticalMessage: "Aylık israf > $10K — acil FinOps müdahalesi gerekiyor.", criticalMessage_i18n: {"en":"Aylık israf > $10K — acil FinOps müdahalesi gerekiyor.","tr":"Aylık israf > $10K — acil FinOps müdahalesi gerekiyor."} },
  ],
  formulaPipeline: [
    { formulaId: "cost.cloud_waste_total", inputMap: { zombieCost: "zombieCostInput", oversizingSavings: "oversizingSavingsInput", spotSavings: "spotSavingsInput", reservedSavings: "reservedSavingsInput", idleHoursCost: "idleHoursCostInput" }, outputId: "totalWasteEliminated" },
  ],
  reportTemplate: { title: "Cloud Waste Elimination Report", title_i18n: {"en":"Cloud Waste Elimination Report","tr":"Cloud Waste Elimination Report"}, sections: ["executive_summary", "loss_breakdown", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.15, volatilityPercent: 15, targetMarginPercent: 20, assumptionNotes: ["Zombie cost = Unattached volumes × Rate + Orphan snapshots × Storage rate.", "Oversizing savings = (Current - RightSized) per month.", "Spot savings = (OnDemand - Spot) × fault-tolerant workload ratio.", "Reserved instance savings = (OnDemand - Reserved) × utilization.", "Idle hours cost = Non-business hours × Running instances × Hourly rate.", "Average waste: 30% overprovisioned, 20% idle, 15% zombie resources."],assumptionNotes_i18n:[{"en":"Zombie cost = Unattached volumes × Rate + Orphan snapshots × Storage rate.","tr":"Zombie cost = Unattached volumes × Rate + Orphan snapshots × Storage rate."},{"en":"Oversizing savings = (Current - RightSized) per month.","tr":"Oversizing savings = (Current - RightSized) per month."},{"en":"Spot savings = (OnDemand - Spot) × fault-tolerant workload ratio.","tr":"Spot savings = (OnDemand - Spot) × fault-tolerant workload ratio."},{"en":"Reserved instance savings = (OnDemand - Reserved) × utilization.","tr":"Reserved instance savings = (OnDemand - Reserved) × utilization."},{"en":"Idle hours cost = Non-business hours × Running instances × Hourly rate.","tr":"Idle hours cost = Non-business hours × Running instances × Hourly rate."},{"en":"Average waste: 30% overprovisioned, 20% idle, 15% zombie resources.","tr":"Average waste: 30% overprovisioned, 20% idle, 15% zombie resources."}] },
};
