import type { PremiumCalculatorSchema } from "@/lib/premium-schema/premium-calculator-schema";

export const CNC_QUOTE_RISK_ANALYZER_SCHEMA: PremiumCalculatorSchema = {
  id: "cnc--502",
  name: "CNC Audit Engine",
  sectorSlug: "cnc-manufacturing",
  category: "oee",
  legacyPaidSlug: "cnc-quote-risk-analyzer",
  painStatement:
    "Estimate minimum safe price and quote risk verdict for CNC jobs using setup, cycle, tooling, material and machine rate inputs.",

  inputs: [
    {
      id: "machineRate",
      label: "Machine rate",
      type: "number",
      unit: "USD/hour",
      required: true,
      smartDefault: 90,
      validation: { min: 0, step: 1 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "plannedHours",
      label: "Planned run hours",
      type: "number",
      unit: "hours",
      required: true,
      smartDefault: 8,
      validation: { min: 0.1, step: 0.1 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "downtimeHours",
      label: "Expected downtime",
      type: "number",
      unit: "hours",
      required: true,
      smartDefault: 1.2,
      validation: { min: 0, step: 0.1 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "materialCost",
      label: "Material cost",
      type: "number",
      unit: "USD",
      required: true,
      smartDefault: 400,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "scrapRate",
      label: "Scrap rate",
      type: "number",
      unit: "%",
      required: true,
      smartDefault: 6,
      validation: { min: 0, max: 100, step: 0.1 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "availability",
      label: "Availability",
      type: "number",
      unit: "%",
      required: true,
      smartDefault: 82,
      validation: { min: 0, max: 100 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "performance",
      label: "Performance",
      type: "number",
      unit: "%",
      required: true,
      smartDefault: 88,
      validation: { min: 0, max: 100 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "quality",
      label: "Quality",
      type: "number",
      unit: "%",
      required: true,
      smartDefault: 95,
      validation: { min: 0, max: 100 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "quotedPrice",
      label: "Quoted price",
      type: "number",
      unit: "USD",
      required: false,
      smartDefault: 5000,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
  ],

  formulaPipeline: [
    {
      formulaId: "oee.availability_loss_cost",
      inputMap: {
        machineRate: "machineRate",
        plannedHours: "plannedHours",
        downtimeHours: "downtimeHours",
      },
      outputId: "availabilityLossCost",
    },
    {
      formulaId: "loss.scrap_cost",
      formulaFamily: "scrap",
      inputMap: { materialCost: "materialCost", scrapRate: "scrapRate" },
      outputId: "scrapCost",
    },
    {
      formulaId: "loss.time_cost",
      formulaFamily: "time",
      inputMap: { hourlyCost: "machineRate", lossHours: "downtimeHours" },
      outputId: "timeLossCost",
    },
    {
      formulaId: "oee.basic",
      inputMap: {
        availability: "availability",
        performance: "performance",
        quality: "quality",
      },
      outputId: "oeeScore",
    },
    {
      formulaId: "loss.combined_operating",
      formulaFamily: "scrap",
      inputMap: {
        laborCost: "availabilityLossCost",
        materialCost: "scrapCost",
        overheadCost: "timeLossCost",
      },
      outputId: "combinedOperatingCost",
    },
    {
      formulaId: "loss.total_exposure",
      formulaFamily: "scrap",
      inputMap: {
        baseCost: "combinedOperatingCost",
        hiddenMultiplier: "hiddenMultiplierConst",
      },
      outputId: "totalExposure",
    },
  ],

  outputs: [
    {
      id: "oeeScore",
      label: "OEE score",
      unit: "%",
      format: "percentage",
    },
    {
      id: "availabilityLossCost",
      label: "Availability loss",
      unit: "USD",
      format: "currency",
    },
    {
      id: "scrapCost",
      label: "Scrap cost",
      unit: "USD",
      format: "currency",
    },
    {
      id: "totalExposure",
      label: "Total loss exposure",
      unit: "USD",
      format: "currency",
      isBigNumber: true,
    },
  ],

  thresholds: [
    {
      fieldId: "oeeScore",
      warning: 65,
      critical: 50,
      direction: "lower_is_bad",
      warningMessage: "OEE is below typical job-shop band — schedule and scrap buffers are tight.",
      criticalMessage: "High risk — hidden cost may erase the margin. Reprice before accepting this job.",
    },
    {
      fieldId: "scrapCost",
      warning: 50,
      critical: 120,
      direction: "higher_is_bad",
      warningMessage: "Scrap exposure is elevated — verify material yield and first-off plan.",
      criticalMessage: "Material fire cost is critical — raise quote or reduce scrap allowance.",
    },
  ],

  reportTemplate: {
    title: "CNC OEE & Loss Decision Report",
    sections: [
      "executive_summary",
      "loss_breakdown",
      "thresholds",
      "sensitivity",
      "action_plan",
      "assumptions",
    ],
    exportFormats: ["pdf"],
  },

  assumptions: {
    hiddenLossMultiplier: 1.12,
    volatilityPercent: 22,
    targetMarginPercent: 15,
    assumptionNotes: [
      "Hidden buffers include setup overrun, tool wear and inspection load.",
      "P90 uses sector volatility 22% unless you override shop history.",
      "Outputs are estimates — verify before signing the job.",
    ],
  },
};
