/**
 * Tool #10 — Basınçlı Hava Sistemi Enerji Maliyeti
 * CompressorPower → AnnualEnergyCost → TotalAnnualCost
 */
import type { PremiumCalculatorSchema } from "@/lib/premium-schema/premium-calculator-schema";
export const COMPRESSED_AIR_SCHEMA: PremiumCalculatorSchema = {
  id: "compressed-air-energy-cost-analyzer", legacyPaidSlug: "compressed-air-energy-cost-analyzer",
  name: "Basınçlı Hava Sistemi Enerji Maliyet Analizi", name_i18n: {"en":"Compressed Air System Energy Cost Analysis","tr":"Basınçlı Hava Sistemi Enerji Maliyet Analizi"}, sectorSlug: "energy-consumption", category: "energy",
  painStatement: "Basınçlı hava sistemleri fabrika elektrik faturasının %30'una kadar çıkabilir. Kaçaklar ve düşük verim gizli maliyet oluşturur. Bu araç sistem enerji maliyetini ve ısı geri kazanım tasarrufunu hesaplar.", painStatement_i18n: {"en":"Compressed air systems can account for up to 30% of factory electricity bills. Leaks and low efficiency create hidden costs. This tool calculates system energy cost and heat recovery savings.","tr":"Basınçlı hava sistemleri fabrika elektrik faturasının %30'una kadar çıkabilir. Kaçaklar ve düşük verim gizli maliyet oluşturur. Bu araç sistem enerji maliyetini ve ısı geri kazanım tasarrufunu hesaplar."},
  inputs: [
    { id: "compressorPowerKw", label: "Kompresör Gücü", label_i18n: {"en":"Compressor Power","tr":"Kompresör Gücü"}, type: "number", unit: "kW", required: true, smartDefault: 75, validation: { min: 0 }, helper: "", expertMeaning: "Compressor motor power", expertMeaning_i18n: {"en":"Compressor motor power","tr":"Kompresör motor gücü"} },
    { id: "operatingHoursPerYear", label: "Çalışma Saati/Yıl", label_i18n: {"en":"Operating Hours/Year","tr":"Çalışma Saati/Yıl"}, type: "number", unit: "saat/yıl", required: true, smartDefault: 8000, validation: { min: 0 }, helper: "", expertMeaning: "Annual operating hours", expertMeaning_i18n: {"en":"Annual operating hours","tr":"Yıllık çalışma saati"} },
    { id: "loadFactor", label: "Yük Oranı", label_i18n: {"en":"Load Factor","tr":"Yük Oranı"}, type: "number", unit: "", required: true, smartDefault: 0.8, validation: { min: 0, max: 1 }, helper: "", expertMeaning: "Compressor load factor", expertMeaning_i18n: {"en":"Compressor load factor","tr":"Kompresör yük faktörü"} },
    { id: "efficiencyIsothermal", label: "İzotermal Verim", label_i18n: {"en":"Isothermal Efficiency","tr":"İzotermal Verim"}, type: "number", unit: "%", required: true, smartDefault: 70, validation: { min: 1, max: 100 }, helper: "", expertMeaning: "Isothermal efficiency", expertMeaning_i18n: {"en":"Isothermal efficiency","tr":"İzotermal verim"} },
    { id: "efficiencyMotor", label: "Motor Verimi", label_i18n: {"en":"Motor Efficiency","tr":"Motor Verimi"}, type: "number", unit: "%", required: true, smartDefault: 90, validation: { min: 1, max: 100 }, helper: "", expertMeaning: "Electric motor efficiency", expertMeaning_i18n: {"en":"Electric motor efficiency","tr":"Elektrik motor verimi"} },
    { id: "efficiencyDrive", label: "Tahrik Verimi", label_i18n: {"en":"Drive Efficiency","tr":"Tahrik Verimi"}, type: "number", unit: "%", required: false, smartDefault: 95, validation: { min: 1, max: 100 }, helper: "", expertMeaning: "Drive/belt efficiency", expertMeaning_i18n: {"en":"Drive/belt efficiency","tr":"Tahrik/kayış verimi"} },
    { id: "electricityRate", label: "Elektrik Tarifesi", label_i18n: {"en":"Electricity Rate","tr":"Elektrik Tarifesi"}, type: "number", unit: "USD/kWh", required: true, smartDefault: 0.12, validation: { min: 0 }, helper: "", expertMeaning: "Electricity unit cost", expertMeaning_i18n: {"en":"Electricity unit cost","tr":"Elektrik birim maliyeti"} },
    { id: "excessPressureDropKpa", label: "Aşırı Basınç Düşümü", label_i18n: {"en":"Excess Pressure Drop","tr":"Aşırı Basınç Düşümü"}, type: "number", unit: "kPa", required: false, smartDefault: 50, validation: { min: 0 }, helper: "", expertMeaning: "Excess ΔP above design", expertMeaning_i18n: {"en":"Excess ΔP above design","tr":"Tasarım üzeri aşırı basınç düşümü"} },
    { id: "heatRecoveryEfficiency", label: "Isı Geri Kazanım Verimi", label_i18n: {"en":"Heat Recovery Efficiency","tr":"Isı Geri Kazanım Verimi"}, type: "number", unit: "%", required: false, smartDefault: 50, validation: { min: 0, max: 100 }, helper: "", expertMeaning: "Heat recovery efficiency", expertMeaning_i18n: {"en":"Heat recovery efficiency","tr":"Isı geri kazanım verimi"} },
    { id: "alternativeEnergyCost", label: "Alternatif Enerji Maliyeti", label_i18n: {"en":"Alternative Energy Cost","tr":"Alternatif Enerji Maliyeti"}, type: "number", unit: "USD/kWh", required: false, smartDefault: 0.10, validation: { min: 0 }, helper: "", expertMeaning: "Cost of alternative heating", expertMeaning_i18n: {"en":"Cost of alternative heating","tr":"Alternatif ısıtma maliyeti"} },
    { id: "gridEmissionFactor", label: "Şebeke Emisyon Faktörü", label_i18n: {"en":"Grid Emission Factor","tr":"Şebeke Emisyon Faktörü"}, type: "number", unit: "kgCO₂/kWh", required: false, smartDefault: 0.45, validation: { min: 0 }, helper: "", expertMeaning: "Grid carbon intensity", expertMeaning_i18n: {"en":"Grid carbon intensity","tr":"Şebeke karbon yoğunluğu"} },
    { id: "annualEnergyCostInput", label: "Yıllık Enerji Maliyeti (Tahmini)", label_i18n: {"en":"Annual Energy Cost (Estimated)","tr":"Yıllık Enerji Maliyeti (Tahmini)"}, type: "number", unit: "USD/yıl", required: false, smartDefault: 40000, validation: { min: 0 }, helper: "Kompresörün yıllık elektrik maliyeti.", helper_i18n: {"en":"Annual electricity cost of compressor.","tr":"Kompresörün yıllık elektrik maliyeti."}, expertMeaning: "Annual electricity cost", expertMeaning_i18n: {"en":"Annual electricity cost","tr":"Yıllık elektrik maliyeti"} },
    { id: "leakageCostInput", label: "Kaçak Kaynaklı Yıllık Kayıp", label_i18n: {"en":"Leakage Annual Loss","tr":"Kaçak Kaynaklı Yıllık Kayıp"}, type: "number", unit: "USD/yıl", required: false, smartDefault: 8000, validation: { min: 0 }, helper: "Basınçlı hava kaçaklarının yıllık maliyeti.", helper_i18n: {"en":"Annual cost of compressed air leaks.","tr":"Basınçlı hava kaçaklarının yıllık maliyeti."}, expertMeaning: "Annual leakage cost", expertMeaning_i18n: {"en":"Annual leakage cost","tr":"Yıllık kaçak maliyeti"} },
    { id: "heatRecoverySavingsInput", label: "Isı Geri Kazanım Tasarrufu", label_i18n: {"en":"Heat Recovery Savings","tr":"Isı Geri Kazanım Tasarrufu"}, type: "number", unit: "USD/yıl", required: false, smartDefault: 3000, validation: { min: 0 }, helper: "Atık ısının geri kazanımından sağlanan tasarruf.", helper_i18n: {"en":"Savings from waste heat recovery.","tr":"Atık ısının geri kazanımından sağlanan tasarruf."}, expertMeaning: "Annual heat recovery savings", expertMeaning_i18n: {"en":"Annual heat recovery savings","tr":"Yıllık ısı geri kazanım tasarrufu"} },
  ],
  outputs: [
    { id: "annualEnergyCost", label: "Yıllık Enerji Maliyeti", label_i18n: {"en":"Annual Energy Cost","tr":"Yıllık Enerji Maliyeti"}, unit: "USD/yıl", format: "currency" },
    { id: "heatRecoverySavings", label: "Isı Geri Kazanım Tasarrufu", label_i18n: {"en":"Heat Recovery Savings","tr":"Isı Geri Kazanım Tasarrufu"}, unit: "USD/yıl", format: "currency" },
    { id: "totalAnnualCost", label: "Toplam Yıllık Maliyet", label_i18n: {"en":"Total Annual Cost","tr":"Toplam Yıllık Maliyet"}, unit: "USD/yıl", format: "currency", isBigNumber: true },
    { id: "carbonFootprint", label: "Yıllık Karbon Ayak İzi", label_i18n: {"en":"Annual Carbon Footprint","tr":"Yıllık Karbon Ayak İzi"}, unit: "kgCO₂/kWh", format: "number" },
  ],
  thresholds: [
    { fieldId: "totalAnnualCost", warning: 50000, critical: 150000, direction: "higher_is_bad", warningMessage: "Yıllık maliyet > $50K — kaçak taraması önerilir.", warningMessage_i18n: {"en":"Annual cost > $50K — leak scan recommended.","tr":"Yıllık maliyet > $50K — kaçak taraması önerilir."}, criticalMessage: "Yıllık maliyet > $150K — kompresör yenileme fizibilitesi yapılmalı.", criticalMessage_i18n: {"en":"Annual cost > $150K — compressor replacement feasibility study needed.","tr":"Yıllık maliyet > $150K — kompresör yenileme fizibilitesi yapılmalı."} },
  ],
  formulaPipeline: [
    { formulaId: "energy.compressed_air_annual_cost", inputMap: { annualEnergyCost: "annualEnergyCostInput", leakageCost: "leakageCostInput", pressureDropCost: "excessPressureDropKpa", heatRecoverySavings: "heatRecoverySavingsInput" }, outputId: "totalAnnualCost" },
  ],
  reportTemplate: { title: "Compressed Air Energy Cost Report", title_i18n: {"en":"Compressed Air Energy Cost Report","tr":"Compressed Air Energy Cost Report"}, sections: ["executive_summary", "loss_breakdown", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.15, volatilityPercent: 15, targetMarginPercent: 20, assumptionNotes: ["Annual energy cost = Power × Hours × Rate × Load factor.", "Heat recovery savings = Power × RecoveryEff × Hours × AltEnergyCost.", "Leakage cost estimated at 20-30% of total energy cost for typical systems.", "Carbon footprint = (Total cost / Electricity rate) × Grid emission factor.", "1 kW saved = 8,760 kWh/year at continuous operation."],assumptionNotes_i18n:[{"en":"Annual energy cost = Power × Hours × Rate × Load factor.","tr":"Annual energy cost = Power × Hours × Rate × Load factor."},{"en":"Heat recovery savings = Power × RecoveryEff × Hours × AltEnergyCost.","tr":"Heat recovery savings = Power × RecoveryEff × Hours × AltEnergyCost."},{"en":"Leakage cost estimated at 20-30% of total energy cost for typical systems.","tr":"Leakage cost estimated at 20-30% of total energy cost for typical systems."},{"en":"Carbon footprint = (Total cost / Electricity rate) × Grid emission factor.","tr":"Carbon footprint = (Total cost / Electricity rate) × Grid emission factor."},{"en":"1 kW saved = 8,760 kWh/year at continuous operation.","tr":"1 kW saved = 8,760 kWh/year at continuous operation."}] },
};
