import type { PremiumCalculatorSchema } from "@/lib/premium-schema/premium-calculator-schema";
export const CUTTING_TOOL_LIFE_SCHEMA: PremiumCalculatorSchema = {
  id: "cutting-tool-life-analyzer", legacyPaidSlug: "cutting-tool-life-analyzer",
  name: "Kesim Parametreleri ve Takım Ömrü", name_i18n: {"en":"Cutting Parameters & Tool Life","tr":"Kesim Parametreleri ve Takım Ömrü", sectorSlug: "cnc-manufacturing", category: "measurement",
  painStatement: "Taylor takım ömrü ve optimum kesme hızı hesaplanmazsa, takım maliyeti ve duruş süreleri kontrol edilemez.", painStatement_i18n: {"en":"Without calculating Taylor tool life and optimal cutting speed, tool costs and downtimes cannot be controlled.","tr":"Taylor takım ömrü ve optimum kesme hızı hesaplanmazsa, takım maliyeti ve duruş süreleri kontrol edilemez.",
  inputs: [
    { id: "cuttingSpeed", label: "Kesme Hızı Vc", label_i18n: {"en":"Cutting Speed Vc","tr":"Kesme Hızı Vc", type: "number", unit: "m/dk", required: true, smartDefault: 150, validation: { min: 1 }, helper: "", expertMeaning: "Cutting speed", expertMeaning_i18n: {"en":"Cutting speed","tr":"Cutting speed" },
    { id: "feed", label: "İlerleme f", label_i18n: {"en":"Feed f","tr":"İlerleme f", type: "number", unit: "mm/dev", required: true, smartDefault: 0.25, validation: { min: 0.01 }, helper: "", expertMeaning: "Feed per revolution", expertMeaning_i18n: {"en":"Feed per revolution","tr":"Feed per revolution" },
    { id: "depth", label: "Derinlik ap", label_i18n: {"en":"Derinlik ap","tr":"Derinlik ap"}, type: "number", unit: "mm", required: true, smartDefault: 2, validation: { min: 0.1 }, helper: "", expertMeaning: "Depth of cut", expertMeaning_i18n: {"en":"Depth of cut","tr":"Depth of cut" },
    { id: "taylorC", label: "Taylor Sabiti C", label_i18n: {"en":"Taylor Constant C","tr":"Taylor Sabiti C", type: "number", unit: "", required: true, smartDefault: 300, validation: { min: 1 }, helper: "", expertMeaning: "Taylor constant C", expertMeaning_i18n: {"en":"Taylor constant C","tr":"Taylor constant C" },
    { id: "taylorN", label: "Taylor Üssü n", label_i18n: {"en":"Taylor Exponent n","tr":"Taylor Üssü n", type: "number", unit: "", required: true, smartDefault: 0.25, validation: { min: 0.01, max: 1 }, helper: "", expertMeaning: "Taylor exponent n", expertMeaning_i18n: {"en":"Taylor exponent n","tr":"Taylor exponent n" },
    { id: "taylorM", label: "Taylor Üssü m", label_i18n: {"en":"Taylor Exponent m","tr":"Taylor Üssü m", type: "number", unit: "", required: false, smartDefault: 0.5, validation: { min: 0.01, max: 1 }, helper: "", expertMeaning: "Taylor exponent m", expertMeaning_i18n: {"en":"Taylor exponent m","tr":"Taylor exponent m" },
    { id: "taylorK", label: "Taylor Üssü k", label_i18n: {"en":"Taylor Exponent k","tr":"Taylor Üssü k", type: "number", unit: "", required: false, smartDefault: 0.1, validation: { min: 0.01, max: 1 }, helper: "", expertMeaning: "Taylor exponent k", expertMeaning_i18n: {"en":"Taylor exponent k","tr":"Taylor exponent k" },
    { id: "toolCost", label: "Takım Ucu Maliyeti", label_i18n: {"en":"Tool Tip Cost","tr":"Takım Ucu Maliyeti", type: "number", unit: "USD", required: true, smartDefault: 30, validation: { min: 0 }, helper: "", expertMeaning: "Tool insert cost", expertMeaning_i18n: {"en":"Tool insert cost","tr":"Tool insert cost" },
    { id: "edges", label: "Kenar Sayısı", label_i18n: {"en":"Number of Edges","tr":"Kenar Sayısı", type: "number", unit: "", required: false, smartDefault: 4, validation: { min: 1, max: 20 }, helper: "", expertMeaning: "Cutting edges per insert", expertMeaning_i18n: {"en":"Cutting edges per insert","tr":"Cutting edges per insert" },
    { id: "toolChangeTime", label: "Takım Değişim Süresi", label_i18n: {"en":"Tool Change Time","tr":"Takım Değişim Süresi", type: "number", unit: "dk", required: true, smartDefault: 3, validation: { min: 0.1 }, helper: "", expertMeaning: "Tool change time", expertMeaning_i18n: {"en":"Tool change time","tr":"Tool change time" },
    { id: "machineRate", label: "Makine Saat Ücreti", label_i18n: {"en":"Machine Hourly Rate","tr":"Makine Saat Ücreti", type: "number", unit: "USD/saat", required: true, smartDefault: 75, validation: { min: 0 }, helper: "", expertMeaning: "Machine hourly rate", expertMeaning_i18n: {"en":"Machine hourly rate","tr":"Machine hourly rate" },
    { id: "machiningTime", label: "İşleme Süresi", label_i18n: {"en":"Machining Time","tr":"İşleme Süresi", type: "number", unit: "dk", required: true, smartDefault: 10, validation: { min: 0.1 }, helper: "", expertMeaning: "Machining time per part", expertMeaning_i18n: {"en":"Machining time per part","tr":"Machining time per part" },
  ],
  outputs: [
    { id: "toolLife", label: "Takım Ömrü (Taylor)", label_i18n: {"en":"Takım Ömrü (Taylor)","tr":"Takım Ömrü (Taylor)"}, unit: "dk", format: "number" },
    { id: "costPerPartTool", label: "Parça Başı Takım Maliyeti", label_i18n: {"en":"Parça Başı Takım Maliyeti","tr":"Parça Başı Takım Maliyeti"}, unit: "USD", format: "currency" },
    { id: "optimalToolLife", label: "Optimum Takım Ömrü", label_i18n: {"en":"Optimum Takım Ömrü","tr":"Optimum Takım Ömrü"}, unit: "dk", format: "number" },
    { id: "optimalVc", label: "Optimum Kesme Hızı", label_i18n: {"en":"Optimum Kesme Hızı","tr":"Optimum Kesme Hızı"}, unit: "m/dk", format: "number" },
    { id: "productionRate", label: "Üretim Hızı", label_i18n: {"en":"Üretim Hızı","tr":"Üretim Hızı"}, unit: "parça/saat", format: "number" },
  ],
  thresholds: [{ fieldId: "toolLife", warning: 30, critical: 5, direction: "lower_is_bad", warningMessage: "Takım ömrü < 30dk — kesme parametreleri agresif.", warningMessage_i18n: {"en":"Tool life < 30 min — cutting parameters aggressive.","tr":"Takım ömrü < 30dk — kesme parametreleri agresif.", criticalMessage: "Takım ömrü < 5dk — acil parametre revizyonu.", criticalMessage_i18n: {"en":"Tool life < 5 min — urgent parameter revision.","tr":"Takım ömrü < 5dk — acil parametre revizyonu." }],
  formulaPipeline: [
    { formulaId: "measurement.machining_tool_life", inputMap: { cTaylor: "taylorC", vc: "cuttingSpeed", nTaylor: "taylorN", feed: "feed", mTaylor: "taylorM" }, outputId: "toolLife" },
    { formulaId: "cost.cnc_tooling", inputMap: { cutTime: "machiningTime", toolLife: "toolLife", toolCost: "toolCost" }, outputId: "costPerPartTool" },
  ],
  reportTemplate: { title: "Takım Ömrü Raporu", title_i18n: {"en":"Tool Life Report","tr":"Takım Ömrü Raporu", sections: ["executive_summary", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1, volatilityPercent: 10, targetMarginPercent: 15, assumptionNotes: ["Taylor T = C / (Vc^n × f^m × ap^k).", "Cost/part = (ToolCost/Edges) × (MachTime/ToolLife)."],assumptionNotes_i18n:[{"en":"Taylor T = C / (Vc^n × f^m × ap^k).","tr":"Taylor T = C / (Vc^n × f^m × ap^k)."},{"en":"Cost/part = (ToolCost/Edges) × (MachTime/ToolLife).","tr":"Cost/part = (ToolCost/Edges) × (MachTime/ToolLife)."}] },
};
