/**
 * Tool #33 — Dye Reçete Maliyet
 */
import type { PremiumCalculatorSchema } from "@/lib/premium-schema/premium-calculator-schema";
export const DYE_RECIPE_COST_SCHEMA: PremiumCalculatorSchema = {
  id: "dye-recipe-cost-analyzer", legacyPaidSlug: "dye-recipe-cost-analyzer",
  name: "Dye Reçete Maliyet Analizi", name_i18n: {"en":"Dye Recipe Cost Analysis","tr":"Dye Reçete Maliyet Analizi"}, sectorSlug: "textile", category: "cost",
  painStatement: "Boyarmadde reçetesinde fire ve kimyasal maliyeti kontrol edilmezse kg başına maliyet beklenenden yüksek çıkar.", painStatement_i18n: {"en":"If waste and chemical costs in dye recipes are not controlled, the cost per kg turns out higher than expected.","tr":"Boyarmadde reçetesinde fire ve kimyasal maliyeti kontrol edilmezse kg başına maliyet beklenenden yüksek çıkar."},
  inputs: [
    { id: "bathRatio", label: "Flotte Oranı", label_i18n: {"en":"Liquor Ratio","tr":"Flotte Oranı"}, type: "number", unit: "", required: true, smartDefault: 10, validation: { min: 1 }, helper: "", expertMeaning: "Liquor ratio (liquid:goods)", expertMeaning_i18n: {"en":"Liquor ratio (liquid:goods)","tr":"Flotte oranı (sıvı:malzeme)"} },
    { id: "fabricWeight", label: "Kumaş Ağırlığı", label_i18n: {"en":"Fabric Weight","tr":"Kumaş Ağırlığı"}, type: "number", unit: "kg", required: true, smartDefault: 100, validation: { min: 0.1 }, helper: "", expertMeaning: "Fabric weight per batch", expertMeaning_i18n: {"en":"Fabric weight per batch","tr":"Batch başına kumaş ağırlığı"} },
    { id: "dyeConcentrations", label: "Konsantrasyonlar (g/L, virgülle)", label_i18n: {"en":"Dye Concentrations (g/L, comma-separated)","tr":"Konsantrasyonlar (g/L, virgülle)"}, type: "number", unit: "g/L", array: true, required: true, validation: { min: 0 }, helper: "", expertMeaning: "Dye concentrations", expertMeaning_i18n: {"en":"Dye concentrations","tr":"Boyarmadde konsantrasyonları"} },
    { id: "dyePrices", label: "Boyarmadde Fiyatları (USD/kg, virgülle)", label_i18n: {"en":"Dye Prices (USD/kg, comma-separated)","tr":"Boyarmadde Fiyatları (USD/kg, virgülle)"}, type: "number", unit: "USD/kg", array: true, required: true, validation: { min: 0 }, helper: "", expertMeaning: "Dye price per kg", expertMeaning_i18n: {"en":"Dye price per kg","tr":"Kg başına boyarmadde fiyatı"} },
    { id: "dosages", label: "Kimyasal Dozajları (g/L, virgülle)", label_i18n: {"en":"Chemical Dosages (g/L, comma-separated)","tr":"Kimyasal Dozajları (g/L, virgülle)"}, type: "number", unit: "g/L", array: true, required: false, validation: { min: 0 }, helper: "", expertMeaning: "Chemical dosages", expertMeaning_i18n: {"en":"Chemical dosages","tr":"Kimyasal dozajları"} },
    { id: "chemPrices", label: "Kimyasal Fiyatları (USD/kg, virgülle)", label_i18n: {"en":"Chemical Prices (USD/kg, comma-separated)","tr":"Kimyasal Fiyatları (USD/kg, virgülle)"}, type: "number", unit: "USD/kg", array: true, required: false, validation: { min: 0 }, helper: "", expertMeaning: "Chemical prices", expertMeaning_i18n: {"en":"Chemical prices","tr":"Kimyasal fiyatları"} },
    { id: "waterTariff", label: "Su Tarifesi", label_i18n: {"en":"Water Tariff","tr":"Su Tarifesi"}, type: "number", unit: "USD/m³", required: false, smartDefault: 3, validation: { min: 0 }, helper: "", expertMeaning: "Water cost per m³", expertMeaning_i18n: {"en":"Water cost per m³","tr":"m³ başına su maliyeti"} },
    { id: "heatingCost", label: "Isıtma Maliyeti", label_i18n: {"en":"Heating Cost","tr":"Isıtma Maliyeti"}, type: "number", unit: "USD/batch", required: false, smartDefault: 25, validation: { min: 0 }, helper: "", expertMeaning: "Heating cost per batch", expertMeaning_i18n: {"en":"Heating cost per batch","tr":"Batch başına ısıtma maliyeti"} },
    { id: "wasteTreatmentCost", label: "Atık Su Arıtma Maliyeti", label_i18n: {"en":"Wastewater Treatment Cost","tr":"Atık Su Arıtma Maliyeti"}, type: "number", unit: "USD/m³", required: false, smartDefault: 2, validation: { min: 0 }, helper: "", expertMeaning: "Effluent treatment cost", expertMeaning_i18n: {"en":"Effluent treatment cost","tr":"Atık su arıtma maliyeti"} },
    { id: "rftPct", label: "RFT Oranı (İlk Seferde Doğru)", label_i18n: {"en":"RFT Rate (Right First Time)","tr":"RFT Oranı (İlk Seferde Doğru)"}, type: "number", unit: "%", required: false, smartDefault: 85, validation: { min: 0, max: 100 }, helper: "", expertMeaning: "Right First Time percentage", expertMeaning_i18n: {"en":"Right First Time percentage","tr":"İlk Seferde Doğru yüzdesi"} },
    { id: "reworkCost", label: "Rework Maliyeti/Batch", label_i18n: {"en":"Rework Cost/Batch","tr":"Rework Maliyeti/Batch"}, type: "number", unit: "USD", required: false, smartDefault: 75, validation: { min: 0 }, helper: "", expertMeaning: "Rework cost per batch", expertMeaning_i18n: {"en":"Rework cost per batch","tr":"Batch başına yeniden işleme maliyeti"} },
  ],
  outputs: [
    { id: "totalBatchCost", label: "Toplam Batch Maliyeti", label_i18n: {"en":"Total Batch Cost","tr":"Toplam Batch Maliyeti"}, unit: "USD/batch", format: "currency" },
    { id: "costPerKg", label: "Kg Başına Maliyet", label_i18n: {"en":"Cost Per Kg","tr":"Kg Başına Maliyet"}, unit: "USD/kg", format: "currency", isBigNumber: true },
  ],
  thresholds: [{ fieldId: "costPerKg", warning: 3, critical: 5, direction: "higher_is_bad", warningMessage: "Maliyet > $3/kg — optimizasyon potansiyeli var.", warningMessage_i18n: {"en":"Cost > $3/kg — optimization potential exists.","tr":"Maliyet > $3/kg — optimizasyon potansiyeli var."}, criticalMessage: "Maliyet > $5/kg — acil reçete optimizasyonu.", criticalMessage_i18n: {"en":"Cost > $5/kg — urgent recipe optimization needed.","tr":"Maliyet > $5/kg — acil reçete optimizasyonu."} }],
  formulaPipeline: [
    { formulaId: "cost.dye_batch", inputMap: { dyeCost: "dyeConcentrations", chemCost: "dosages", waterCost: "waterTariff", energyCost: "heatingCost", wasteCost: "wasteTreatmentCost" }, outputId: "totalBatchCost" },
    { formulaId: "cost.dye_rft_savings", inputMap: { reworkCost: "reworkCost", rftPct: "rftPct" }, outputId: "rftSavings" },
    { formulaId: "cost.dye_cost_per_kg", inputMap: { totalBatch: "totalBatchCost", rftSavings: "rftSavings", fabricWeight: "fabricWeight" }, outputId: "costPerKg" },
  ],
  reportTemplate: { title: "Dye Recipe Cost Report", title_i18n: {"en":"Dye Recipe Cost Report","tr":"Dye Recipe Cost Report"}, sections: ["executive_summary", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.15, volatilityPercent: 15, targetMarginPercent: 20, assumptionNotes: ["Dye cost = Σ(Conc×Price)/BathRatio×Weight/1000.", "Chem cost = Σ(Dosage×Price)×Volume/1000.", "Cost/kg = (TotalBatch+RFTSavings)/Weight."],assumptionNotes_i18n:[{"en":"Dye cost = Σ(Conc×Price)/BathRatio×Weight/1000.","tr":"Dye cost = Σ(Conc×Price)/BathRatio×Weight/1000."},{"en":"Chem cost = Σ(Dosage×Price)×Volume/1000.","tr":"Chem cost = Σ(Dosage×Price)×Volume/1000."},{"en":"Cost/kg = (TotalBatch+RFTSavings)/Weight.","tr":"Cost/kg = (TotalBatch+RFTSavings)/Weight."}] },
};
