/**
 * Tool #18 — Ciro Maliyeti (Employee Turnover Cost)
 * Separation → Vacancy → Replacement → Training → ProductivityLoss → Total
 */
import type { PremiumCalculatorSchema } from "@/lib/premium-schema/premium-calculator-schema";
export const TURNOVER_COST_SCHEMA: PremiumCalculatorSchema = {
  id: "employee-turnover-cost-analyzer", legacyPaidSlug: "employee-turnover-cost-analyzer",
  name: "Çalışan Ciro (Turnover) Maliyet Analizi", name_i18n: {"en":"Employee Turnover Cost Analysis","tr":"Çalışan Ciro (Turnover) Maliyet Analizi"}, sectorSlug: "legal-tax", category: "cost",
  painStatement: "Personel ayrılma maliyeti sadece tazminat değil; işe alım, eğitim ve verimlilik kaybını da içerir. Bu araç ayrılan çalışan başına gerçek maliyeti hesaplar.", painStatement_i18n: {"en":"Employee departure cost includes not only severance but also recruitment, training, and productivity loss. This tool calculates the true cost per departing employee.","tr":"Personel ayrılma maliyeti sadece tazminat değil; işe alım, eğitim ve verimlilik kaybını da içerir. Bu araç ayrılan çalışan başına gerçek maliyeti hesaplar."},
  inputs: [
    { id: "exitsCount", label: "Ayrılan Personel Sayısı", label_i18n: {"en":"Employee Exit Count","tr":"Ayrılan Personel Sayısı"}, type: "number", unit: "kişi", required: true, smartDefault: 10, validation: { min: 1 }, helper: "", expertMeaning: "Number of employee exits", expertMeaning_i18n: {"en":"Number of employee exits","tr":"Ayrılan çalışan sayısı"} },
    { id: "severancePay", label: "Kıdem Tazminatı (Toplam)", label_i18n: {"en":"Severance Pay (Total)","tr":"Kıdem Tazminatı (Toplam)"}, type: "number", unit: "USD", required: true, smartDefault: 25000, validation: { min: 0 }, helper: "", expertMeaning: "Total severance compensation", expertMeaning_i18n: {"en":"Total severance compensation","tr":"Toplam kıdem tazminatı"} },
    { id: "timeToFillDays", label: "İşe Alım Süresi", label_i18n: {"en":"Time to Fill","tr":"İşe Alım Süresi"}, type: "number", unit: "gün", required: true, smartDefault: 45, validation: { min: 1 }, helper: "", expertMeaning: "Average days to fill position", expertMeaning_i18n: {"en":"Average days to fill position","tr":"Pozisyonu doldurmak için ortalama gün"} },
    { id: "dailyRevenuePerEmployee", label: "Çalışan Başına Günlük Gelir", label_i18n: {"en":"Daily Revenue Per Employee","tr":"Çalışan Başına Günlük Gelir"}, type: "number", unit: "USD/gün", required: true, smartDefault: 400, validation: { min: 0 }, helper: "", expertMeaning: "Revenue per employee per day", expertMeaning_i18n: {"en":"Revenue per employee per day","tr":"Çalışan başına günlük gelir"} },
    { id: "advertisingAndAgencyFees", label: "İlan ve Ajans Ücretleri", label_i18n: {"en":"Advertising & Agency Fees","tr":"İlan ve Ajans Ücretleri"}, type: "number", unit: "USD", required: true, smartDefault: 3000, validation: { min: 0 }, helper: "", expertMeaning: "Total recruitment advertising", expertMeaning_i18n: {"en":"Total recruitment advertising","tr":"Toplam işe alım ilan maliyeti"} },
    { id: "interviewHours", label: "Mülakat Süresi (Toplam)", label_i18n: {"en":"Interview Hours (Total)","tr":"Mülakat Süresi (Toplam)"}, type: "number", unit: "saat", required: false, smartDefault: 10, validation: { min: 0 }, helper: "", expertMeaning: "Manager interview hours per hire", expertMeaning_i18n: {"en":"Manager interview hours per hire","tr":"Yönetici mülakat saati"} },
    { id: "interviewerRate", label: "Mülakatçı Saatlik Ücreti", label_i18n: {"en":"Interviewer Hourly Rate","tr":"Mülakatçı Saatlik Ücreti"}, type: "number", unit: "USD/saat", required: false, smartDefault: 60, validation: { min: 0 }, helper: "", expertMeaning: "Manager hourly rate", expertMeaning_i18n: {"en":"Manager hourly rate","tr":"Yönetici saatlik ücreti"} },
    { id: "trainingHours", label: "Eğitim Süresi", label_i18n: {"en":"Training Hours","tr":"Eğitim Süresi"}, type: "number", unit: "saat", required: false, smartDefault: 80, validation: { min: 0 }, helper: "", expertMeaning: "Total training hours per hire", expertMeaning_i18n: {"en":"Total training hours per hire","tr":"İşe alım başına toplam eğitim saati"} },
    { id: "trainerRate", label: "Eğitmen Saatlik Ücreti", label_i18n: {"en":"Trainer Hourly Rate","tr":"Eğitmen Saatlik Ücreti"}, type: "number", unit: "USD/saat", required: false, smartDefault: 50, validation: { min: 0 }, helper: "", expertMeaning: "Trainer hourly cost", expertMeaning_i18n: {"en":"Trainer hourly cost","tr":"Eğitmen saatlik maliyeti"} },
    { id: "onboardingHours", label: "Oryantasyon Süresi", label_i18n: {"en":"Onboarding Hours","tr":"Oryantasyon Süresi"}, type: "number", unit: "saat", required: false, smartDefault: 40, validation: { min: 0 }, helper: "", expertMeaning: "Onboarding hours per hire", expertMeaning_i18n: {"en":"Onboarding hours per hire","tr":"İşe alım başına oryantasyon saati"} },
    { id: "newHireRate", label: "Yeni Çalışan Saatlik Ücreti", label_i18n: {"en":"New Hire Hourly Rate","tr":"Yeni Çalışan Saatlik Ücreti"}, type: "number", unit: "USD/saat", required: false, smartDefault: 20, validation: { min: 0 }, helper: "", expertMeaning: "New hire hourly rate during training", expertMeaning_i18n: {"en":"New hire hourly rate during training","tr":"Eğitim sırasında yeni çalışan saatlik ücreti"} },
    { id: "timeToFullProductivityDays", label: "Tam Verimliliğe Ulaşma", label_i18n: {"en":"Time to Full Productivity","tr":"Tam Verimliliğe Ulaşma"}, type: "number", unit: "gün", required: false, smartDefault: 90, validation: { min: 0 }, helper: "", expertMeaning: "Days to reach full productivity", expertMeaning_i18n: {"en":"Days to reach full productivity","tr":"Tam verime ulaşma günü"} },
    { id: "avgDailyOutput", label: "Ortalama Günlük Çıktı", label_i18n: {"en":"Average Daily Output","tr":"Ortalama Günlük Çıktı"}, type: "number", unit: "birim/gün", required: false, smartDefault: 50, validation: { min: 0 }, helper: "", expertMeaning: "Average daily output per employee", expertMeaning_i18n: {"en":"Average daily output per employee","tr":"Çalışan başına ortalama günlük çıktı"} },
    { id: "unitMargin", label: "Birim Kâr Marjı", label_i18n: {"en":"Unit Profit Margin","tr":"Birim Kâr Marjı"}, type: "number", unit: "USD", required: false, smartDefault: 5, validation: { min: 0 }, helper: "", expertMeaning: "Profit margin per unit", expertMeaning_i18n: {"en":"Profit margin per unit","tr":"Birim başına kar marjı"} },
    { id: "separationCostInput", label: "Ayrılma Maliyeti (Tahmini)", label_i18n: {"en":"Separation Cost (Estimated)","tr":"Ayrılma Maliyeti (Tahmini)"}, type: "number", unit: "USD", required: false, smartDefault: 3000, validation: { min: 0 }, helper: "İşten çıkış maliyeti (tazminat + işlem).", helper_i18n: {"en":"Exit cost (severance + processing).","tr":"İşten çıkış maliyeti (tazminat + işlem)."}, expertMeaning: "Separation cost per employee", expertMeaning_i18n: {"en":"Separation cost per employee","tr":"Çalışan başına ayrılma maliyeti"} },
    { id: "vacancyCostInput", label: "Pozisyon Boşluk Maliyeti", label_i18n: {"en":"Vacancy Cost","tr":"Pozisyon Boşluk Maliyeti"}, type: "number", unit: "USD", required: false, smartDefault: 12000, validation: { min: 0 }, helper: "Boş pozisyonun günlük gelir kaybı.", helper_i18n: {"en":"Daily revenue loss of vacant position.","tr":"Boş pozisyonun günlük gelir kaybı."}, expertMeaning: "Vacancy cost per employee", expertMeaning_i18n: {"en":"Vacancy cost per employee","tr":"Çalışan başına pozisyon boşluk maliyeti"} },
    { id: "replacementCostInput", label: "Yenileme Maliyeti", label_i18n: {"en":"Replacement Cost","tr":"Yenileme Maliyeti"}, type: "number", unit: "USD", required: false, smartDefault: 5000, validation: { min: 0 }, helper: "İlan, mülakat, referans maliyeti.", helper_i18n: {"en":"Advertising, interview, reference cost.","tr":"İlan, mülakat, referans maliyeti."}, expertMeaning: "Replacement hiring cost", expertMeaning_i18n: {"en":"Replacement hiring cost","tr":"Yenileme işe alım maliyeti"} },
    { id: "trainingCostInput", label: "Eğitim Maliyeti", label_i18n: {"en":"Training Cost","tr":"Eğitim Maliyeti"}, type: "number", unit: "USD", required: false, smartDefault: 4000, validation: { min: 0 }, helper: "Eğitim + oryantasyon maliyeti.", helper_i18n: {"en":"Training + onboarding cost.","tr":"Eğitim + oryantasyon maliyeti."}, expertMeaning: "Training cost per new hire", expertMeaning_i18n: {"en":"Training cost per new hire","tr":"Yeni işe alım başına eğitim maliyeti"} },
    { id: "productivityLossInput", label: "Verimlilik Kaybı", label_i18n: {"en":"Productivity Loss","tr":"Verimlilik Kaybı"}, type: "number", unit: "USD", required: false, smartDefault: 8000, validation: { min: 0 }, helper: "Tam verime ulaşana kadar kayıp.", helper_i18n: {"en":"Loss until reaching full productivity.","tr":"Tam verime ulaşana kadar kayıp."}, expertMeaning: "Productivity loss per new hire", expertMeaning_i18n: {"en":"Productivity loss per new hire","tr":"Yeni işe alım başına verimlilik kaybı"} },
  ],
  outputs: [
    { id: "separationCost", label: "Ayrılma Maliyeti", label_i18n: {"en":"Separation Cost","tr":"Ayrılma Maliyeti"}, unit: "USD", format: "currency" },
    { id: "vacancyCost", label: "Pozisyon Boşluk Maliyeti", label_i18n: {"en":"Vacancy Cost","tr":"Pozisyon Boşluk Maliyeti"}, unit: "USD", format: "currency" },
    { id: "replacementCost", label: "Yenileme Maliyeti", label_i18n: {"en":"Replacement Cost","tr":"Yenileme Maliyeti"}, unit: "USD", format: "currency" },
    { id: "trainingCost", label: "Eğitim Maliyeti", label_i18n: {"en":"Training Cost","tr":"Eğitim Maliyeti"}, unit: "USD", format: "currency" },
    { id: "productivityLoss", label: "Verimlilik Kaybı", label_i18n: {"en":"Productivity Loss","tr":"Verimlilik Kaybı"}, unit: "USD", format: "currency" },
    { id: "totalTurnoverCost", label: "Toplam Ciro Maliyeti", label_i18n: {"en":"Total Turnover Cost","tr":"Toplam Ciro Maliyeti"}, unit: "USD", format: "currency", isBigNumber: true },
  ],
  thresholds: [
    { fieldId: "totalTurnoverCost", warning: 50000, critical: 150000, direction: "higher_is_bad", warningMessage: "Ciro maliyeti > $50K — çalışan bağlılığı programı değerlendirilmeli.", warningMessage_i18n: {"en":"Turnover cost > $50K — evaluate employee retention program.","tr":"Ciro maliyeti > $50K — çalışan bağlılığı programı değerlendirilmeli."}, criticalMessage: "Ciro maliyeti > $150K — acil elde tutma stratejisi gerekiyor.", criticalMessage_i18n: {"en":"Turnover cost > $150K — urgent retention strategy needed.","tr":"Ciro maliyeti > $150K — acil elde tutma stratejisi gerekiyor."} },
  ],
  formulaPipeline: [
    { formulaId: "cost.turnover_total", inputMap: { separationCost: "separationCostInput", vacancyCost: "vacancyCostInput", replacementCost: "replacementCostInput", trainingCost: "trainingCostInput", productivityLoss: "productivityLossInput" }, outputId: "totalTurnoverCost" },
  ],
  reportTemplate: { title: "Employee Turnover Cost Report", title_i18n: {"en":"Employee Turnover Cost Report","tr":"Employee Turnover Cost Report"}, sections: ["executive_summary", "loss_breakdown", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.15, volatilityPercent: 15, targetMarginPercent: 20, assumptionNotes: ["Separation cost = Exit interview + Severance + Admin.", "Vacancy cost = Time to fill × Daily revenue + Temp agency.", "Replacement cost = Ads + Agency + Interview time × Manager rate.", "Training cost = Training hours × Trainer rate + Onboarding × New hire rate.", "Productivity loss = Time to full prod × (1 - Ramp-up curve) × Output × Margin."],assumptionNotes_i18n:[{"en":"Separation cost = Exit interview + Severance + Admin.","tr":"Separation cost = Exit interview + Severance + Admin."},{"en":"Vacancy cost = Time to fill × Daily revenue + Temp agency.","tr":"Vacancy cost = Time to fill × Daily revenue + Temp agency."},{"en":"Replacement cost = Ads + Agency + Interview time × Manager rate.","tr":"Replacement cost = Ads + Agency + Interview time × Manager rate."},{"en":"Training cost = Training hours × Trainer rate + Onboarding × New hire rate.","tr":"Training cost = Training hours × Trainer rate + Onboarding × New hire rate."},{"en":"Productivity loss = Time to full prod × (1 - Ramp-up curve) × Output × Margin.","tr":"Productivity loss = Time to full prod × (1 - Ramp-up curve) × Output × Margin."}] },
};
