/**
 * Tool #36 — Environmental Fire
 */
import type { PremiumCalculatorSchema } from "@/lib/premium-schema/premium-calculator-schema";
export const ENVIRONMENTAL_WASTE_SCHEMA: PremiumCalculatorSchema = {
  id: "environmental-waste-cost-analyzer", legacyPaidSlug: "environmental-waste-cost-analyzer",
  name: "Çevre Atık Maliyet & Döngüsellik Analizi", name_i18n: {"en":"Environmental Waste Cost & Circularity Analysis","tr":"Çevre Atık Maliyet & Döngüsellik Analizi"}, sectorSlug: "legal-tax", category: "cost",
  painStatement: "Atık bertaraf, tehlikeli atık ve emisyon maliyetleri ayrıştırılmazsa çevre cezaları ve sürdürülebilirlik raporlaması hatalı olur.", painStatement_i18n: {"en":"If waste disposal, hazardous waste, and emission costs are not broken down, environmental fines and sustainability reporting will be inaccurate.","tr":"Atık bertaraf, tehlikeli atık ve emisyon maliyetleri ayrıştırılmazsa çevre cezaları ve sürdürülebilirlik raporlaması hatalı olur."},
  inputs: [
    { id: "nonHazWaste", label: "Tehlikesiz Atık Miktarı", label_i18n: {"en":"Non-Hazardous Waste Amount","tr":"Tehlikesiz Atık Miktarı"}, type: "number", unit: "ton", required: true, smartDefault: 50, validation: { min: 0 }, helper: "", expertMeaning: "Non-hazardous waste", expertMeaning_i18n: {"en":"Non-hazardous waste","tr":"Tehlikesiz atık"} },
    { id: "disposalFee", label: "Bertaraf Ücreti", label_i18n: {"en":"Disposal Fee","tr":"Bertaraf Ücreti"}, type: "number", unit: "USD/ton", required: true, smartDefault: 100, validation: { min: 0 }, helper: "", expertMeaning: "Disposal fee per ton", expertMeaning_i18n: {"en":"Disposal fee per ton","tr":"Ton başına bertaraf ücreti"} },
    { id: "hazMass", label: "Tehlikeli Atık Miktarı", label_i18n: {"en":"Hazardous Waste Amount","tr":"Tehlikeli Atık Miktarı"}, type: "number", unit: "ton", required: true, smartDefault: 10, validation: { min: 0 }, helper: "", expertMeaning: "Hazardous waste mass", expertMeaning_i18n: {"en":"Hazardous waste mass","tr":"Tehlikeli atık miktarı"} },
    { id: "hazFee", label: "Tehlikeli Atık Ücreti", label_i18n: {"en":"Hazardous Waste Fee","tr":"Tehlikeli Atık Ücreti"}, type: "number", unit: "USD/ton", required: true, smartDefault: 500, validation: { min: 0 }, helper: "", expertMeaning: "Hazardous waste fee", expertMeaning_i18n: {"en":"Hazardous waste fee","tr":"Tehlikeli atık ücreti"} },
    { id: "hazSurcharge", label: "Tehlikeli Ek Ücret", label_i18n: {"en":"Hazardous Surcharge","tr":"Tehlikeli Ek Ücret"}, type: "number", unit: "USD/ton", required: false, smartDefault: 100, validation: { min: 0 }, helper: "", expertMeaning: "Hazardous surcharge", expertMeaning_i18n: {"en":"Hazardous surcharge","tr":"Tehlikeli atık ek ücreti"} },
    { id: "recycMass", label: "Geri Dönüşüm Miktarı", label_i18n: {"en":"Recycling Amount","tr":"Geri Dönüşüm Miktarı"}, type: "number", unit: "ton", required: true, smartDefault: 20, validation: { min: 0 }, helper: "", expertMeaning: "Recycling mass", expertMeaning_i18n: {"en":"Recycling mass","tr":"Geri dönüşüm miktarı"} },
    { id: "sortCost", label: "Ayırma Maliyeti", label_i18n: {"en":"Sorting Cost","tr":"Ayırma Maliyeti"}, type: "number", unit: "USD/ton", required: false, smartDefault: 50, validation: { min: 0 }, helper: "", expertMeaning: "Sorting cost per ton", expertMeaning_i18n: {"en":"Sorting cost per ton","tr":"Ton başına ayırma maliyeti"} },
    { id: "scrapRevenue", label: "Hurda Geliri", label_i18n: {"en":"Scrap Revenue","tr":"Hurda Geliri"}, type: "number", unit: "USD/ton", required: false, smartDefault: 30, validation: { min: 0 }, helper: "", expertMeaning: "Scrap revenue per ton", expertMeaning_i18n: {"en":"Scrap revenue per ton","tr":"Ton başına hurda geliri"} },
    { id: "airEmissions", label: "Hava Emisyonu", label_i18n: {"en":"Air Emissions","tr":"Hava Emisyonu"}, type: "number", unit: "tonCO₂", required: false, smartDefault: 100, validation: { min: 0 }, helper: "", expertMeaning: "Air emissions in tons", expertMeaning_i18n: {"en":"Air emissions in tons","tr":"Ton cinsinden hava emisyonu"} },
    { id: "carbonPrice", label: "Karbon Fiyatı", label_i18n: {"en":"Carbon Price","tr":"Karbon Fiyatı"}, type: "number", unit: "USD/ton", required: false, smartDefault: 50, validation: { min: 0 }, helper: "", expertMeaning: "Carbon price", expertMeaning_i18n: {"en":"Carbon price","tr":"Karbon fiyatı"} },
    { id: "waterEffluent", label: "Atık Su Hacmi", label_i18n: {"en":"Wastewater Volume","tr":"Atık Su Hacmi"}, type: "number", unit: "m³", required: false, smartDefault: 1000, validation: { min: 0 }, helper: "", expertMeaning: "Wastewater volume", expertMeaning_i18n: {"en":"Wastewater volume","tr":"Atık su hacmi"} },
    { id: "treatCost", label: "Atık Su Arıtma", label_i18n: {"en":"Wastewater Treatment","tr":"Atık Su Arıtma"}, type: "number", unit: "USD/m³", required: false, smartDefault: 3, validation: { min: 0 }, helper: "", expertMeaning: "Treatment cost per m³", expertMeaning_i18n: {"en":"Treatment cost per m³","tr":"m³ başına arıtma maliyeti"} },
    { id: "probViolation", label: "İhlal Olasılığı", label_i18n: {"en":"Violation Probability","tr":"İhlal Olasılığı"}, type: "number", unit: "%", required: false, smartDefault: 5, validation: { min: 0, max: 100 }, helper: "", expertMeaning: "Violation probability", expertMeaning_i18n: {"en":"Violation probability","tr":"İhlal olasılığı"} },
    { id: "fineAmount", label: "Ceza Tutarı", label_i18n: {"en":"Fine Amount","tr":"Ceza Tutarı"}, type: "number", unit: "USD", required: false, smartDefault: 500000, validation: { min: 0 }, helper: "", expertMeaning: "Maximum fine amount", expertMeaning_i18n: {"en":"Maximum fine amount","tr":"Maksimum ceza tutarı"} },
  ],
  outputs: [
    { id: "totalEnvCost", label: "Toplam Çevre Maliyeti", label_i18n: {"en":"Total Environmental Cost","tr":"Toplam Çevre Maliyeti"}, unit: "USD", format: "currency", isBigNumber: true },
  ],
  thresholds: [{ fieldId: "totalEnvCost", warning: 50000, critical: 150000, direction: "higher_is_bad", warningMessage: "Çevre maliyeti > $50K — azaltım programı başlatılmalı.", warningMessage_i18n: {"en":"Environmental cost > $50K — start reduction program.","tr":"Çevre maliyeti > $50K — azaltım programı başlatılmalı."}, criticalMessage: "Maliyet > $150K — acil çevre yönetimi aksiyonu.", criticalMessage_i18n: {"en":"Cost > $150K — urgent environmental management action.","tr":"Maliyet > $150K — acil çevre yönetimi aksiyonu."} }],
  formulaPipeline: [
    { formulaId: "cost.env_fire_disposal", inputMap: { nonHazWaste: "nonHazWaste", disposalFee: "disposalFee" }, outputId: "disposalCost" },
    { formulaId: "cost.env_fire_haz", inputMap: { hazMass: "hazMass", hazFee: "hazFee", hazSurcharge: "hazSurcharge" }, outputId: "hazCost" },
    { formulaId: "cost.env_fire_recycling", inputMap: { recycMass: "recycMass", sortCost: "sortCost", scrapRevenue: "scrapRevenue" }, outputId: "recyclingCost" },
    { formulaId: "cost.env_fire_emissions", inputMap: { airEmissions: "airEmissions", carbonPrice: "carbonPrice", waterEffluent: "waterEffluent", treatCost: "treatCost" }, outputId: "emissionsCost" },
    { formulaId: "cost.env_fire_penalty_risk", inputMap: { probViolation: "probViolation", fineAmount: "fineAmount" }, outputId: "penaltyRisk" },
    { formulaId: "cost.env_fire_total", inputMap: { disposalCost: "disposalCost", hazCost: "hazCost", recyclingCost: "recyclingCost", emissionsCost: "emissionsCost", penaltyRisk: "penaltyRisk" }, outputId: "totalEnvCost" },
  ],
  reportTemplate: { title: "Environmental Waste Cost Report", title_i18n: {"en":"Environmental Waste Cost Report","tr":"Environmental Waste Cost Report"}, sections: ["executive_summary", "loss_breakdown", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.2, volatilityPercent: 20, targetMarginPercent: 25, assumptionNotes: ["Disposal = Waste×Fee. Haz = Mass×(Fee+Surcharge).", "Recycling = Mass×(SortCost-ScrapRev).", "Emissions = Air×CarbonPrice + Water×TreatCost."],assumptionNotes_i18n:[{"en":"Disposal = Waste×Fee. Haz = Mass×(Fee+Surcharge).","tr":"Disposal = Waste×Fee. Haz = Mass×(Fee+Surcharge)."},{"en":"Recycling = Mass×(SortCost-ScrapRev).","tr":"Recycling = Mass×(SortCost-ScrapRev)."},{"en":"Emissions = Air×CarbonPrice + Water×TreatCost.","tr":"Emissions = Air×CarbonPrice + Water×TreatCost."}] },
};
