/**
 * Tool #43 — Flexible Manufacturing ROI
 */
import type { PremiumCalculatorSchema } from "@/lib/premium-schema/premium-calculator-schema";
export const FLEXIBLE_MFG_ROI_SCHEMA: PremiumCalculatorSchema = {
  id: "flexible-manufacturing-roi-analyzer", legacyPaidSlug: "flexible-manufacturing-roi-analyzer",
  name: "Esnek İmalat (FMS) ROI Analizi", name_i18n: {"en":"Esnek İmalat (FMS) ROI Analizi","tr":"Esnek İmalat (FMS) ROI Analizi"}, sectorSlug: "cnc-manufacturing", category: "cost",
  painStatement: "Esnek imalat sistemine (FMS) yatırım kararı, dedicated sistemle karşılaştırmalı ROI analizi yapılmadan verilmemelidir.", painStatement_i18n: {"en":"Esnek imalat sistemine (FMS) yatırım kararı, dedicated sistemle karşılaştırmalı ROI analizi yapılmadan verilmemelidir.","tr":"Esnek imalat sistemine (FMS) yatırım kararı, dedicated sistemle karşılaştırmalı ROI analizi yapılmadan verilmemelidir."},
  inputs: [
    { id: "costDedicated", label: "Dedicated Sistem Maliyeti", label_i18n: {"en":"Dedicated Sistem Maliyeti","tr":"Dedicated Sistem Maliyeti"}, type: "number", unit: "USD", required: true, smartDefault: 300000, validation: { min: 0 }, helper: "", expertMeaning: "Dedicated system cost", expertMeaning_i18n: {"en":"Dedicated system cost","tr":"Dedicated system cost"} },
    { id: "costFlex", label: "FMS Sistem Maliyeti", label_i18n: {"en":"FMS Sistem Maliyeti","tr":"FMS Sistem Maliyeti"}, type: "number", unit: "USD", required: true, smartDefault: 500000, validation: { min: 0 }, helper: "", expertMeaning: "Flexible system cost", expertMeaning_i18n: {"en":"Flexible system cost","tr":"Flexible system cost"} },
    { id: "ttmReduction", label: "TTM Azaltma (gün)", label_i18n: {"en":"TTM Azaltma (gün)","tr":"TTM Azaltma (gün)"}, type: "number", unit: "gün", required: false, smartDefault: 20, validation: { min: 0 }, helper: "", expertMeaning: "Time-to-market reduction", expertMeaning_i18n: {"en":"Time-to-market reduction","tr":"Time-to-market reduction"} },
    { id: "totalTime", label: "Toplam Geliştirme Süresi", label_i18n: {"en":"Toplam Geliştirme Süresi","tr":"Toplam Geliştirme Süresi"}, type: "number", unit: "gün", required: false, smartDefault: 100, validation: { min: 0 }, helper: "", expertMeaning: "Total development time", expertMeaning_i18n: {"en":"Total development time","tr":"Total development time"} },
    { id: "revenueGain", label: "Erken Çıkış Gelir Kazancı", label_i18n: {"en":"Erken Çıkış Gelir Kazancı","tr":"Erken Çıkış Gelir Kazancı"}, type: "number", unit: "USD", required: false, smartDefault: 200000, validation: { min: 0 }, helper: "", expertMeaning: "Revenue gain from early launch", expertMeaning_i18n: {"en":"Revenue gain from early launch","tr":"Revenue gain from early launch"} },
    { id: "customerPremium", label: "Müşteri Prim Marjı", label_i18n: {"en":"Müşteri Prim Marjı","tr":"Müşteri Prim Marjı"}, type: "number", unit: "%", required: false, smartDefault: 5, validation: { min: 0, max: 100 }, helper: "", expertMeaning: "Customer premium from flexibility", expertMeaning_i18n: {"en":"Customer premium from flexibility","tr":"Customer premium from flexibility"} },
    { id: "productionVolume", label: "Yıllık Üretim Hacmi", label_i18n: {"en":"Yıllık Üretim Hacmi","tr":"Yıllık Üretim Hacmi"}, type: "number", unit: "adet", required: false, smartDefault: 50000, validation: { min: 0 }, helper: "", expertMeaning: "Annual production volume", expertMeaning_i18n: {"en":"Annual production volume","tr":"Annual production volume"} },
    { id: "unitPrice", label: "Birim Fiyat", label_i18n: {"en":"Birim Fiyat","tr":"Birim Fiyat"}, type: "number", unit: "USD", required: false, smartDefault: 100, validation: { min: 0 }, helper: "", expertMeaning: "Unit price", expertMeaning_i18n: {"en":"Unit price","tr":"Unit price"} },
    { id: "wipDedicated", label: "Dedicated WIP", label_i18n: {"en":"Dedicated WIP","tr":"Dedicated WIP"}, type: "number", unit: "USD", required: false, smartDefault: 80000, validation: { min: 0 }, helper: "", expertMeaning: "WIP for dedicated system", expertMeaning_i18n: {"en":"WIP for dedicated system","tr":"WIP for dedicated system"} },
    { id: "wipFlexible", label: "FMS WIP", label_i18n: {"en":"FMS WIP","tr":"FMS WIP"}, type: "number", unit: "USD", required: false, smartDefault: 40000, validation: { min: 0 }, helper: "", expertMeaning: "WIP for flexible system", expertMeaning_i18n: {"en":"WIP for flexible system","tr":"WIP for flexible system"} },
    { id: "carryCostPct", label: "Taşıma Maliyeti Oranı", label_i18n: {"en":"Taşıma Maliyeti Oranı","tr":"Taşıma Maliyeti Oranı"}, type: "number", unit: "%", required: false, smartDefault: 15, validation: { min: 0, max: 100 }, helper: "", expertMeaning: "Inventory carrying cost", expertMeaning_i18n: {"en":"Inventory carrying cost","tr":"Inventory carrying cost"} },
    { id: "scrapReduction", label: "Hurda Azaltma Tasarrufu", label_i18n: {"en":"Hurda Azaltma Tasarrufu","tr":"Hurda Azaltma Tasarrufu"}, type: "number", unit: "USD", required: false, smartDefault: 10000, validation: { min: 0 }, helper: "", expertMeaning: "Scrap reduction savings", expertMeaning_i18n: {"en":"Scrap reduction savings","tr":"Scrap reduction savings"} },
    { id: "capex", label: "FMS Yatırım Bedeli", label_i18n: {"en":"FMS Yatırım Bedeli","tr":"FMS Yatırım Bedeli"}, type: "number", unit: "USD", required: true, smartDefault: 500000, validation: { min: 1 }, helper: "", expertMeaning: "FMS capital expenditure", expertMeaning_i18n: {"en":"FMS capital expenditure","tr":"FMS capital expenditure"} },
  ],
  outputs: [
    { id: "roi", label: "FMS ROI", label_i18n: {"en":"FMS ROI","tr":"FMS ROI"}, unit: "%", format: "percentage", isBigNumber: true },
  ],
  thresholds: [{ fieldId: "roi", warning: 30, critical: 15, direction: "lower_is_bad", warningMessage: "ROI < %30 — yatırım fizibilitesi sorgulanmalı.", warningMessage_i18n: {"en":"ROI < %30 — yatırım fizibilitesi sorgulanmalı.","tr":"ROI < %30 — yatırım fizibilitesi sorgulanmalı."}, criticalMessage: "ROI < %15 — dedicated sistem daha avantajlı olabilir.", criticalMessage_i18n: {"en":"ROI < %15 — dedicated sistem daha avantajlı olabilir.","tr":"ROI < %15 — dedicated sistem daha avantajlı olabilir."} }],
  formulaPipeline: [
    { formulaId: "cost.flex_mfg_roi", inputMap: { costDedicated: "costDedicated", costFlex: "costFlex", capex: "capex" }, outputId: "roi" },
  ],
  reportTemplate: { title: "Flexible Manufacturing ROI Report", title_i18n: {"en":"Flexible Manufacturing ROI Report","tr":"Flexible Manufacturing ROI Report"}, sections: ["executive_summary", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.2, volatilityPercent: 20, targetMarginPercent: 25, assumptionNotes: ["Compares dedicated vs flexible manufacturing cost.", "Includes flex value (TTM + customer premium), WIP savings, scrap reduction.", "ROI = (CostGap+FlexVal+InvSav+ScrapRed)/Capex."],assumptionNotes_i18n:[{"en":"Compares dedicated vs flexible manufacturing cost.","tr":"Compares dedicated vs flexible manufacturing cost."},{"en":"Includes flex value (TTM + customer premium), WIP savings, scrap reduction.","tr":"Includes flex value (TTM + customer premium), WIP savings, scrap reduction."},{"en":"ROI = (CostGap+FlexVal+InvSav+ScrapRed)/Capex.","tr":"ROI = (CostGap+FlexVal+InvSav+ScrapRed)/Capex."}] },
};
