/**
 * Tool #47 — HACCP Deviation
 */
import type { PremiumCalculatorSchema } from "@/lib/premium-schema/premium-calculator-schema";
export const HACCP_DEVIATION_SCHEMA: PremiumCalculatorSchema = {
  id: "haccp-deviation-cost-analyzer", legacyPaidSlug: "haccp-deviation-cost-analyzer",
  name: "HACCP Sapma Maliyet & RPN Analizi", name_i18n: {"en":"HACCP Deviation Cost & RPN Analysis","tr":"HACCP Sapma Maliyet & RPN Analizi"}, sectorSlug: "food", category: "cost",
  painStatement: "HACCP sapmalarının maliyeti (bekletme, test, rework, geri çağırma) hesaplanmazsa gıda güvenliği yatırım öncelikleri yanlış belirlenir.", painStatement_i18n: {"en":"Without calculating HACCP deviation costs (hold, test, rework, recall), food safety investment priorities cannot be properly determined.","tr":"HACCP sapmalarının maliyeti (bekletme, test, rework, geri çağırma) hesaplanmazsa gıda güvenliği yatırım öncelikleri yanlış belirlenir."},
  inputs: [
    { id: "quarantineVolume", label: "Karantina Hacmi", label_i18n: {"en":"Quarantined product volume","tr":"Karantina Hacmi"}, type: "number", unit: "kg", required: true, smartDefault: 5000, validation: { min: 0 }, helper: "", expertMeaning: "Quarantined product volume", expertMeaning_i18n: {"en":"Quarantined product volume","tr":"Karantina Hacmi"} },
    { id: "holdCostPerUnit", label: "Bekletme Maliyeti", label_i18n: {"en":"Cost per unit per day","tr":"Bekletme Maliyeti"}, type: "number", unit: "USD/kg/gün", required: true, smartDefault: 0.1, validation: { min: 0 }, helper: "", expertMeaning: "Cost per unit per day", expertMeaning_i18n: {"en":"Cost per unit per day","tr":"Bekletme Maliyeti"} },
    { id: "holdDays", label: "Bekletme Günü", label_i18n: {"en":"Hold duration","tr":"Bekletme Günü"}, type: "number", unit: "gün", required: true, smartDefault: 3, validation: { min: 1 }, helper: "", expertMeaning: "Hold duration", expertMeaning_i18n: {"en":"Hold duration","tr":"Bekletme Günü"} },
    { id: "testSamples", label: "Test Örnek Sayısı", label_i18n: {"en":"Number of test samples","tr":"Test Örnek Sayısı"}, type: "number", unit: "adet", required: true, smartDefault: 20, validation: { min: 0 }, helper: "", expertMeaning: "Number of test samples", expertMeaning_i18n: {"en":"Number of test samples","tr":"Test Örnek Sayısı"} },
    { id: "labCost", label: "Laboratuvar Maliyeti", label_i18n: {"en":"Lab cost per sample","tr":"Laboratuvar Maliyeti"}, type: "number", unit: "USD/örnek", required: true, smartDefault: 50, validation: { min: 0 }, helper: "", expertMeaning: "Lab cost per sample", expertMeaning_i18n: {"en":"Lab cost per sample","tr":"Laboratuvar Maliyeti"} },
    { id: "deviationVolume", label: "Sapma Hacmi", label_i18n: {"en":"Volume requiring rework","tr":"Sapma Hacmi"}, type: "number", unit: "kg", required: false, smartDefault: 1000, validation: { min: 0 }, helper: "", expertMeaning: "Volume requiring rework", expertMeaning_i18n: {"en":"Volume requiring rework","tr":"Sapma Hacmi"} },
    { id: "reworkCost", label: "Rework Maliyeti", label_i18n: {"en":"Rework cost per kg","tr":"Rework Maliyeti"}, type: "number", unit: "USD/kg", required: false, smartDefault: 1.5, validation: { min: 0 }, helper: "", expertMeaning: "Rework cost per kg", expertMeaning_i18n: {"en":"Rework cost per kg","tr":"Rework Maliyeti"} },
    { id: "condemnedVolume", label: "İmha Hacmi", label_i18n: {"en":"Condemned volume","tr":"İmha Hacmi"}, type: "number", unit: "kg", required: false, smartDefault: 500, validation: { min: 0 }, helper: "", expertMeaning: "Condemned volume", expertMeaning_i18n: {"en":"Condemned volume","tr":"İmha Hacmi"} },
    { id: "disposalCost", label: "Bertaraf Maliyeti", label_i18n: {"en":"Disposal cost per kg","tr":"Bertaraf Maliyeti"}, type: "number", unit: "USD/kg", required: false, smartDefault: 0.5, validation: { min: 0 }, helper: "", expertMeaning: "Disposal cost per kg", expertMeaning_i18n: {"en":"Disposal cost per kg","tr":"Bertaraf Maliyeti"} },
    { id: "lostMaterial", label: "Malzeme Kaybı", label_i18n: {"en":"Lost material cost","tr":"Malzeme Kaybı"}, type: "number", unit: "USD", required: false, smartDefault: 2000, validation: { min: 0 }, helper: "", expertMeaning: "Lost material cost", expertMeaning_i18n: {"en":"Lost material cost","tr":"Malzeme Kaybı"} },
    { id: "notificationCost", label: "Bildirim Maliyeti", label_i18n: {"en":"Notification cost","tr":"Bildirim Maliyeti"}, type: "number", unit: "USD", required: false, smartDefault: 5000, validation: { min: 0 }, helper: "", expertMeaning: "Notification cost", expertMeaning_i18n: {"en":"Notification cost","tr":"Bildirim Maliyeti"} },
    { id: "logisticsRecall", label: "Geri Toplama Lojistiği", label_i18n: {"en":"Recall logistics cost","tr":"Geri Toplama Lojistiği"}, type: "number", unit: "USD", required: false, smartDefault: 15000, validation: { min: 0 }, helper: "", expertMeaning: "Recall logistics cost", expertMeaning_i18n: {"en":"Recall logistics cost","tr":"Geri Toplama Lojistiği"} },
    { id: "retailPenalty", label: "Perakende Cezası", label_i18n: {"en":"Retailer penalty","tr":"Perakende Cezası"}, type: "number", unit: "USD", required: false, smartDefault: 10000, validation: { min: 0 }, helper: "", expertMeaning: "Retailer penalty", expertMeaning_i18n: {"en":"Retailer penalty","tr":"Perakende Cezası"} },
    { id: "brandDamage", label: "Marka Hasarı", label_i18n: {"en":"Brand damage cost","tr":"Marka Hasarı"}, type: "number", unit: "USD", required: false, smartDefault: 50000, validation: { min: 0 }, helper: "", expertMeaning: "Brand damage cost", expertMeaning_i18n: {"en":"Brand damage cost","tr":"Marka Hasarı"} },
    { id: "probDetection", label: "Tespit Olasılığı", label_i18n: {"en":"Regulatory detection probability","tr":"Tespit Olasılığı"}, type: "number", unit: "%", required: false, smartDefault: 30, validation: { min: 0, max: 100 }, helper: "", expertMeaning: "Regulatory detection probability", expertMeaning_i18n: {"en":"Regulatory detection probability","tr":"Tespit Olasılığı"} },
    { id: "fineAmount", label: "Ceza Tutarı", label_i18n: {"en":"Maximum regulatory fine","tr":"Ceza Tutarı"}, type: "number", unit: "USD", required: false, smartDefault: 100000, validation: { min: 0 }, helper: "", expertMeaning: "Maximum regulatory fine", expertMeaning_i18n: {"en":"Maximum regulatory fine","tr":"Ceza Tutarı"} },
  ],
  outputs:  [
    { id: "totalHaccpCost", label: "Toplam HACCP Sapma Maliyeti", label_i18n: {"en":"Total HACCP Deviation Cost","tr":"Toplam HACCP Sapma Maliyeti"}, unit: "USD", format: "currency", isBigNumber: true },
  ],
  thresholds: [{ fieldId: "totalHaccpCost", warning: 50000, critical: 150000, direction: "higher_is_bad", warningMessage: "Maliyet > $50K — HACCP planı gözden geçirilmeli.", warningMessage_i18n: {"en":"Cost > $50K — HACCP plan should be reviewed.","tr":"Maliyet > $50K — HACCP planı gözden geçirilmeli."}, criticalMessage: "Maliyet > $150K — tesis denetimi ve düzeltici faaliyet acil.", criticalMessage_i18n: {"en":"Cost > $150K — facility audit and corrective action urgent.","tr":"Maliyet > $150K — tesis denetimi ve düzeltici faaliyet acil."} }],
  formulaPipeline: [
    { formulaId: "cost.haccp_hold", inputMap: { quarantineVolume: "quarantineVolume", holdCostPerUnit: "holdCostPerUnit", holdDays: "holdDays" }, outputId: "holdCost" },
    { formulaId: "cost.haccp_test", inputMap: { testSamples: "testSamples", labCost: "labCost" }, outputId: "testCost" },
    { formulaId: "cost.haccp_rework", inputMap: { deviationVolume: "deviationVolume", reworkCost: "reworkCost" }, outputId: "reworkCost" },
    { formulaId: "cost.haccp_disposal", inputMap: { condemnedVolume: "condemnedVolume", disposalCost: "disposalCost", lostMaterial: "lostMaterial" }, outputId: "disposalCost" },
    { formulaId: "cost.haccp_recall", inputMap: { notificationCost: "notificationCost", logisticsRecall: "logisticsRecall", retailPenalty: "retailPenalty", brandDamage: "brandDamage" }, outputId: "recallCost" },
    { formulaId: "cost.haccp_fine", inputMap: { probDetection: "probDetection", fineAmount: "fineAmount" }, outputId: "fine" },
    { formulaId: "cost.haccp_total", inputMap: { holdCost: "holdCost", testCost: "testCost", reworkCost: "reworkCost", disposalCost: "disposalCost", recallCost: "recallCost", fine: "fine" }, outputId: "totalHaccpCost" },
  ],
  reportTemplate: { title: "HACCP Deviation Cost Report", title_i18n: {"en":"HACCP Deviation Cost Report","tr":"HACCP Deviation Cost Report"}, sections: ["executive_summary", "loss_breakdown", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.2, volatilityPercent: 20, targetMarginPercent: 25, assumptionNotes: ["Hold = Vol×Cost×Days. Test = Samples×LabCost.", "Rework = Vol×ReworkCost. Disp = CondVol×DispCost+LostMat.", "Recall = Notif+Log+RetailPen+Brand. Fine = Prob×Fine."],assumptionNotes_i18n:[{"en":"Hold = Vol×Cost×Days. Test = Samples×LabCost.","tr":"Hold = Vol×Cost×Days. Test = Samples×LabCost."},{"en":"Rework = Vol×ReworkCost. Disp = CondVol×DispCost+LostMat.","tr":"Rework = Vol×ReworkCost. Disp = CondVol×DispCost+LostMat."},{"en":"Recall = Notif+Log+RetailPen+Brand. Fine = Prob×Fine.","tr":"Recall = Notif+Log+RetailPen+Brand. Fine = Prob×Fine."}] },
};
