/**
 * Tool #53 — Isı Exchanger Fouling
 */
import type { PremiumCalculatorSchema } from "@/lib/premium-schema/premium-calculator-schema";
export const HEAT_EXCHANGER_FOULING_SCHEMA: PremiumCalculatorSchema = {
  id: "heat-exchanger-fouling-analyzer", legacyPaidSlug: "heat-exchanger-fouling-analyzer",
  name: "Isı Değiştirici Fouling & Enerji Kaybı Analizi", name_i18n: {"en":"Isı Değiştirici Fouling & Enerji Kaybı Analizi","tr":"Isı Değiştirici Fouling & Enerji Kaybı Analizi"}, sectorSlug: "sheet-metal", category: "energy",
  painStatement: "Isı değiştiricide kirlenme (fouling) nedeniyle ısı transfer verimi düşer ve enerji maliyeti artar. Temizlik ROI'si hesaplanmalıdır.", painStatement_i18n: {"en":"Isı değiştiricide kirlenme (fouling) nedeniyle ısı transfer verimi düşer ve enerji maliyeti artar. Temizlik ROI'si hesaplanmalıdır.","tr":"Isı değiştiricide kirlenme (fouling) nedeniyle ısı transfer verimi düşer ve enerji maliyeti artar. Temizlik ROI'si hesaplanmalıdır."},
  inputs: [
    { id: "uClean", label: "U_clean (Temiz)", label_i18n: {"en":"U_clean (Temiz)","tr":"U_clean (Temiz)"}, type: "number", unit: "W/m²K", required: true, smartDefault: 500, validation: { min: 1 }, helper: "", expertMeaning: "Clean overall heat transfer coeff", expertMeaning_i18n: {"en":"Clean overall heat transfer coeff","tr":"Clean overall heat transfer coeff"} },
    { id: "uDirty", label: "U_dirty (Kirli)", label_i18n: {"en":"U_dirty (Kirli)","tr":"U_dirty (Kirli)"}, type: "number", unit: "W/m²K", required: true, smartDefault: 350, validation: { min: 1 }, helper: "", expertMeaning: "Dirty overall heat transfer coeff", expertMeaning_i18n: {"en":"Dirty overall heat transfer coeff","tr":"Dirty overall heat transfer coeff"} },
    { id: "area", label: "Isı Transfer Alanı", label_i18n: {"en":"Isı Transfer Alanı","tr":"Isı Transfer Alanı"}, type: "number", unit: "m²", required: true, smartDefault: 100, validation: { min: 0.1 }, helper: "", expertMeaning: "Heat exchanger area", expertMeaning_i18n: {"en":"Heat exchanger area","tr":"Heat exchanger area"} },
    { id: "lmtd", label: "LMTD", label_i18n: {"en":"LMTD","tr":"LMTD"}, type: "number", unit: "K", required: true, smartDefault: 30, validation: { min: 0.1 }, helper: "", expertMeaning: "Log mean temperature difference", expertMeaning_i18n: {"en":"Log mean temperature difference","tr":"Log mean temperature difference"} },
    { id: "operatingHours", label: "Yıllık Çalışma Saati", label_i18n: {"en":"Yıllık Çalışma Saati","tr":"Yıllık Çalışma Saati"}, type: "number", unit: "saat/yıl", required: false, smartDefault: 8000, validation: { min: 0 }, helper: "", expertMeaning: "Annual operating hours", expertMeaning_i18n: {"en":"Annual operating hours","tr":"Annual operating hours"} },
    { id: "boilerEff", label: "Kazan Verimi", label_i18n: {"en":"Kazan Verimi","tr":"Kazan Verimi"}, type: "number", unit: "%", required: false, smartDefault: 85, validation: { min: 1, max: 100 }, helper: "", expertMeaning: "Boiler/furnace efficiency", expertMeaning_i18n: {"en":"Boiler/furnace efficiency","tr":"Boiler/furnace efficiency"} },
    { id: "fuelCost", label: "Yakıt Birim Maliyeti", label_i18n: {"en":"Yakıt Birim Maliyeti","tr":"Yakıt Birim Maliyeti"}, type: "number", unit: "USD/kWh", required: false, smartDefault: 0.05, validation: { min: 0 }, helper: "", expertMeaning: "Fuel cost per kWh", expertMeaning_i18n: {"en":"Fuel cost per kWh","tr":"Fuel cost per kWh"} },
    { id: "deltaPIncrease", label: "Basınç Düşüşü Artışı", label_i18n: {"en":"Basınç Düşüşü Artışı","tr":"Basınç Düşüşü Artışı"}, type: "number", unit: "bar", required: false, smartDefault: 0.5, validation: { min: 0 }, helper: "", expertMeaning: "DP increase due to fouling", expertMeaning_i18n: {"en":"DP increase due to fouling","tr":"DP increase due to fouling"} },
    { id: "flowM3h", label: "Akış Debisi", label_i18n: {"en":"Akış Debisi","tr":"Akış Debisi"}, type: "number", unit: "m³/saat", required: false, smartDefault: 200, validation: { min: 0 }, helper: "", expertMeaning: "Flow rate", expertMeaning_i18n: {"en":"Flow rate","tr":"Flow rate"} },
    { id: "pumpEff", label: "Pompa Verimi", label_i18n: {"en":"Pompa Verimi","tr":"Pompa Verimi"}, type: "number", unit: "%", required: false, smartDefault: 75, validation: { min: 1, max: 100 }, helper: "", expertMeaning: "Pump efficiency", expertMeaning_i18n: {"en":"Pump efficiency","tr":"Pump efficiency"} },
    { id: "cleanCost", label: "Temizlik Maliyeti", label_i18n: {"en":"Temizlik Maliyeti","tr":"Temizlik Maliyeti"}, type: "number", unit: "USD", required: false, smartDefault: 5000, validation: { min: 0 }, helper: "", expertMeaning: "Cost of cleaning", expertMeaning_i18n: {"en":"Cost of cleaning","tr":"Cost of cleaning"} },
    { id: "heatLoss", label: "Isı Transfer Kaybı (kW)", label_i18n: {"en":"Isı Transfer Kaybı (kW)","tr":"Isı Transfer Kaybı (kW)"}, type: "number", unit: "kW", required: true, smartDefault: 150, validation: { min: 0 }, helper: "", expertMeaning: "Heat loss due to fouling", expertMeaning_i18n: {"en":"Heat loss due to fouling","tr":"Heat loss due to fouling"} },
  ],
  outputs: [
    { id: "rf", label: "Fouling Direnci (Rf)", label_i18n: {"en":"Fouling Direnci (Rf)","tr":"Fouling Direnci (Rf)"}, unit: "m²K/W", format: "number" },
    { id: "heatLoss", label: "Isı Transfer Kaybı", label_i18n: {"en":"Isı Transfer Kaybı","tr":"Isı Transfer Kaybı"}, unit: "kW", format: "number" },
    { id: "cost", label: "Yıllık Enerji Kaybı", label_i18n: {"en":"Yıllık Enerji Kaybı","tr":"Yıllık Enerji Kaybı"}, unit: "USD/yıl", format: "currency" },
    { id: "roi", label: "Temizlik ROI", label_i18n: {"en":"Temizlik ROI","tr":"Temizlik ROI"}, unit: "%", format: "percentage", isBigNumber: true },
  ],
  thresholds: [{ fieldId: "cost", warning: 10000, critical: 30000, direction: "higher_is_bad", warningMessage: "Enerji kaybı > $10K/yıl — temizlik planlanmalı.", warningMessage_i18n: {"en":"Enerji kaybı > $10K/yıl — temizlik planlanmalı.","tr":"Enerji kaybı > $10K/yıl — temizlik planlanmalı."}, criticalMessage: "Kayıp > $30K/yıl — acil temizlik gerekli.", criticalMessage_i18n: {"en":"Kayıp > $30K/yıl — acil temizlik gerekli.","tr":"Kayıp > $30K/yıl — acil temizlik gerekli."} }],
  formulaPipeline: [
    { formulaId: "energy.fouling_resistance", inputMap: { uClean: "uClean", uDirty: "uDirty" }, outputId: "rf" },
    { formulaId: "energy.fouling_cost", inputMap: { heatLoss: "heatLoss", fuelCost: "fuelCost", pumpIncrease: "deltaPIncrease" }, outputId: "cost" },
    { formulaId: "energy.fouling_roi", inputMap: { totalCost: "cost", cleanCost: "cleanCost" }, outputId: "roi" },
  ],
  reportTemplate: { title: "Heat Exchanger Fouling Report", title_i18n: {"en":"Heat Exchanger Fouling Report","tr":"Heat Exchanger Fouling Report"}, sections: ["executive_summary", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.15, volatilityPercent: 15, targetMarginPercent: 20, assumptionNotes: ["Rf = 1/U_dirty - 1/U_clean.", "Heat loss = Area×U_clean×LMTD - Area×U_dirty×LMTD.", "Cost = EnergyPenalty×FuelCost + PumpInc."],assumptionNotes_i18n:[{"en":"Rf = 1/U_dirty - 1/U_clean.","tr":"Rf = 1/U_dirty - 1/U_clean."},{"en":"Heat loss = Area×U_clean×LMTD - Area×U_dirty×LMTD.","tr":"Heat loss = Area×U_clean×LMTD - Area×U_dirty×LMTD."},{"en":"Cost = EnergyPenalty×FuelCost + PumpInc.","tr":"Cost = EnergyPenalty×FuelCost + PumpInc."}] },
};
