/**
 * Tool — Saatlik Ücret
 */
import type { PremiumCalculatorSchema } from "@/lib/premium-schema/premium-calculator-schema";
export const HOURLY_RATE_ANALYZER: PremiumCalculatorSchema = {
  id: "hourly-rate-analyzer", legacyPaidSlug: "hourly-rate-analyzer",
  name: "Saatlik Ücret Analizi", name_i18n: {"en":"Hourly Rate Analysis","tr":"Saatlik Ücret Analizi"}, sectorSlug: "financial-planning", category: "cost",
  painStatement: "Çalışanın gerçek saatlik maliyeti brüt maaşın çok üzerindedir; yan haklar, vergiler ve dolaylı giderler hesaba katılmazsa fiyatlama zarar eder.", painStatement_i18n: {"en":"The true hourly cost of an employee far exceeds gross salary; pricing will lose money if benefits, taxes, and indirect costs are not included.","tr":"Çalışanın gerçek saatlik maliyeti brüt maaşın çok üzerindedir; yan haklar, vergiler ve dolaylı giderler hesaba katılmazsa fiyatlama zarar eder."},
  inputs: [
    { id: "grossSalary", label: "Brüt Aylık Maaş", label_i18n: {"en":"Gross monthly salary","tr":"Brüt Aylık Maaş"}, type: "number", unit: "USD", required: true, smartDefault: 4000, validation: { min: 1 }, helper: "", expertMeaning: "Gross monthly salary", expertMeaning_i18n: {"en":"Gross monthly salary","tr":"Brüt Aylık Maaş"} },
    { id: "employerTaxRate", label: "İşveren Vergi Oranı", label_i18n: {"en":"Employer tax & social security rate","tr":"İşveren Vergi Oranı"}, type: "number", unit: "%", required: true, smartDefault: 22.5, validation: { min: 0, max: 100 }, helper: "", expertMeaning: "Employer tax & social security rate", expertMeaning_i18n: {"en":"Employer tax & social security rate","tr":"İşveren Vergi Oranı"} },
    { id: "benefitsCost", label: "Yan Hak Maliyeti", label_i18n: {"en":"Monthly benefits cost","tr":"Yan Hak Maliyeti"}, type: "number", unit: "USD/ay", required: false, smartDefault: 500, validation: { min: 0 }, helper: "", expertMeaning: "Monthly benefits cost", expertMeaning_i18n: {"en":"Monthly benefits cost","tr":"Yan Hak Maliyeti"} },
    { id: "overheadPct", label: "Genel Gider Oranı", label_i18n: {"en":"Indirect overhead allocation rate","tr":"Genel Gider Oranı"}, type: "number", unit: "%", required: false, smartDefault: 15, validation: { min: 0, max: 100 }, helper: "", expertMeaning: "Indirect overhead allocation rate", expertMeaning_i18n: {"en":"Indirect overhead allocation rate","tr":"Genel Gider Oranı"} },
    { id: "billableHoursPerMonth", label: "Aylık Faturalanabilir Saat", label_i18n: {"en":"Billable hours per month","tr":"Aylık Faturalanabilir Saat"}, type: "number", unit: "saat", required: true, smartDefault: 140, validation: { min: 1 }, helper: "", expertMeaning: "Billable hours per month", expertMeaning_i18n: {"en":"Billable hours per month","tr":"Aylık Faturalanabilir Saat"} },
    { id: "bonusPct", label: "Prim Oranı", label_i18n: {"en":"Annual bonus percentage","tr":"Prim Oranı"}, type: "number", unit: "%", required: false, smartDefault: 10, validation: { min: 0, max: 100 }, helper: "", expertMeaning: "Annual bonus percentage", expertMeaning_i18n: {"en":"Annual bonus percentage","tr":"Prim Oranı"} },
  ],
  outputs:  [
    { id: "burdenedHourlyRate", label: "Toplam Yüklü Saatlik Ücret", label_i18n: {"en":"Total Burdened Hourly Rate","tr":"Toplam Yüklü Saatlik Ücret"}, unit: "USD/saat", format: "currency", isBigNumber: true },
  ],
  thresholds: [{ fieldId: "burdenedHourlyRate", warning: 50, critical: 80, direction: "higher_is_bad", warningMessage: "Yüklü saatlik ücret >$50 — maliyet avantajı azalıyor.", warningMessage_i18n: {"en":"Burdened rate >$50 — cost advantage decreasing.","tr":"Yüklü saatlik ücret >$50 — maliyet avantajı azalıyor."}, criticalMessage: "Yüklü saatlik ücret >$80 — rekabetçi fiyatlama zorlaşır.", criticalMessage_i18n: {"en":"Burdened rate >$80 — competitive pricing becomes difficult.","tr":"Yüklü saatlik ücret >$80 — rekabetçi fiyatlama zorlaşır."} }],
  formulaPipeline: [
    { formulaId: "cost.burdened_hourly_rate", inputMap: { grossSalary: "grossSalary", employerTaxRate: "employerTaxRate", benefitsCost: "benefitsCost", overheadPct: "overheadPct", billableHoursPerMonth: "billableHoursPerMonth", bonusPct: "bonusPct" }, outputId: "burdenedHourlyRate" },
  ],
  reportTemplate: { title: "Saatlik Ücret Analiz Raporu", title_i18n: {"en":"Hourly Rate Analysis Report","tr":"Saatlik Ücret Analiz Raporu"}, sections: ["executive_summary", "loss_breakdown", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.1, volatilityPercent: 10, targetMarginPercent: 15, assumptionNotes: ["Yüklü saatlik ücret = (maaş + vergi + yan hak + genel gider + prim) / faturalanabilir saat.", "Vergi oranı işveren payı ve sosyal güvenlik primini içerir.", "Faturalanabilir saat aylık ortalama üzerinden hesaplanır."],assumptionNotes_i18n:[{"en":"Burdened hourly rate = (salary + tax + benefits + overhead + bonus) / billable hours.","tr":"Yüklü saatlik ücret = (maaş + vergi + yan hak + genel gider + prim) / faturalanabilir saat."},{"en":"Tax rate includes employer share and social security premium.","tr":"Vergi oranı işveren payı ve sosyal güvenlik primini içerir."},{"en":"Billable hours are calculated based on monthly average.","tr":"Faturalanabilir saat aylık ortalama üzerinden hesaplanır."}] },
};
