import type { PremiumCalculatorSchema } from "@/lib/premium-schema/premium-calculator-schema";

export const PROFIT_MARGIN_CALCULATOR_SCHEMA: PremiumCalculatorSchema = {
  id: "mfg-509",
  name: "Profit Margin Calculator",
  sectorSlug: "manufacturing",
  category: "cost",
  painStatement:
    "Compute selling margin percent and markup from unit price and cost.",

  inputs: [
    {
      id: "materialCost",
      label: "Material cost",
      type: "number",
      unit: "USD",
      required: true,
      smartDefault: 4200,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "laborCost",
      label: "Labor cost",
      type: "number",
      unit: "USD",
      required: true,
      smartDefault: 2800,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "machineCost",
      label: "Machine cost",
      type: "number",
      unit: "USD",
      required: true,
      smartDefault: 1900,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "energyCost",
      label: "Energy cost",
      type: "number",
      unit: "USD",
      required: true,
      smartDefault: 320,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "overheadCost",
      label: "Overhead cost",
      type: "number",
      unit: "USD",
      required: true,
      smartDefault: 650,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "wasteRate",
      label: "Waste rate",
      type: "number",
      unit: "%",
      required: true,
      smartDefault: 4,
      validation: { min: 0, max: 100 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "setupTimeCost",
      label: "Setup time cost",
      type: "number",
      unit: "USD",
      required: true,
      smartDefault: 480,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "shippingCost",
      label: "Shipping cost",
      type: "number",
      unit: "USD",
      required: true,
      smartDefault: 180,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "paymentTermCost",
      label: "Payment term cost",
      type: "number",
      unit: "USD",
      required: true,
      smartDefault: 210,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "targetMarginRate",
      label: "Target margin rate",
      type: "number",
      unit: "%",
      required: true,
      smartDefault: 18,
      validation: { min: 1, max: 95 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "discountRate",
      label: "Discount rate",
      type: "number",
      unit: "%",
      required: false,
      smartDefault: 0,
      validation: { min: 0, max: 100 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "taxIncluded",
      label: "Tax included in costs",
      type: "boolean",
      unit: "flag",
      required: false,
      smartDefault: false,
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "safetyMarginUplift",
      label: "Safety margin uplift",
      type: "number",
      unit: "%",
      required: false,
      smartDefault: 2,
      validation: { min: 0, max: 20 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
  ],

  formulaPipeline: [
    {
      formulaId: "cost.total_exposure",
      inputMap: { a: "materialCost", b: "laborCost", c: "machineCost" },
      outputId: "costStack1",
    },
    {
      formulaId: "cost.total_exposure",
      inputMap: { a: "costStack1", b: "energyCost", c: "overheadCost" },
      outputId: "costStack2",
    },
    {
      formulaId: "cost.total_exposure",
      inputMap: { a: "costStack2", b: "setupTimeCost", c: "shippingCost" },
      outputId: "costStack3",
    },
    {
      formulaId: "cost.sum2",
      inputMap: { a: "costStack3", b: "paymentTermCost" },
      outputId: "directSubtotal",
    },
    {
      formulaId: "cost.percent_of_amount",
      inputMap: { amount: "directSubtotal", percent: "wasteRate" },
      outputId: "wasteCost",
    },
    {
      formulaId: "cost.sum2",
      inputMap: { a: "directSubtotal", b: "wasteCost" },
      outputId: "totalCost",
    },
    {
      formulaId: "cost.value",
      inputMap: { value: "totalCost" },
      outputId: "totalExposure",
    },
    {
      formulaId: "cost.quote_target_price",
      inputMap: { totalCost: "totalCost", targetMarginPercent: "targetMarginRate" },
      outputId: "targetSalesPrice",
    },
    {
      formulaId: "cost.quote_safe_floor_price",
      inputMap: {
        totalCost: "totalCost",
        targetMarginPercent: "targetMarginRate",
        safetyMarginUplift: "safetyMarginUplift",
      },
      outputId: "minimumSafePrice",
    },
    {
      formulaId: "cost.difference",
      inputMap: { a: "targetSalesPrice", b: "totalCost" },
      outputId: "grossMarginAmount",
    },
    {
      formulaId: "cost.margin_rate_on_price",
      inputMap: { price: "targetSalesPrice", cost: "totalCost" },
      outputId: "grossMarginRate",
    },
    {
      formulaId: "cost.margin_rate_on_price",
      inputMap: { price: "targetSalesPrice", cost: "totalCost" },
      outputId: "decisionSummary",
    },
    {
      formulaId: "cost.percent_of_amount",
      inputMap: { amount: "targetSalesPrice", percent: "discountRate" },
      outputId: "discountImpact",
    },
  ],

  outputs: [
    {
      id: "targetSalesPrice",
      label: "Target sales price",
      unit: "USD",
      format: "currency",
      isBigNumber: true,
    },
    {
      id: "totalCost",
      label: "Total loaded cost",
      unit: "USD",
      format: "currency",
    },
    {
      id: "wasteCost",
      label: "Waste cost",
      unit: "USD",
      format: "currency",
    },
    {
      id: "minimumSafePrice",
      label: "Minimum safe price",
      unit: "USD",
      format: "currency",
    },
    {
      id: "grossMarginAmount",
      label: "Gross margin amount",
      unit: "USD",
      format: "currency",
    },
    {
      id: "grossMarginRate",
      label: "Gross margin rate",
      unit: "%",
      format: "percentage",
    },
    {
      id: "discountImpact",
      label: "Discount impact",
      unit: "USD",
      format: "currency",
    },
    {
      id: "decisionSummary",
      label: "Decision summary margin",
      unit: "%",
      format: "percentage",
    },
  ],

  thresholds: [
    {
      fieldId: "grossMarginRate",
      warning: 12,
      critical: 8,
      direction: "lower_is_bad",
      warningMessage:
        "Achieved margin is below a typical shop band — review waste, setup and payment-term lines before sending the quote.",
      criticalMessage:
        "Quoted margin is critically thin — reprice or remove discount before committing.",
    },
    {
      fieldId: "wasteRate",
      warning: 6,
      critical: 10,
      direction: "higher_is_bad",
      warningMessage: "Waste rate is elevated — confirm nesting, scrap and rework allowance.",
      criticalMessage: "Waste rate is very high — margin may be lost before production starts.",
    },
  ],

  reportTemplate: {
    title: "Quote Price and Margin Decision Report",
    sections: [
      "executive_summary",
      "loss_breakdown",
      "thresholds",
      "sensitivity",
      "action_plan",
      "assumptions",
    ],
    exportFormats: ["pdf", "csv"],
  },

  assumptions: {
    hiddenLossMultiplier: 1.05,
    volatilityPercent: 8,
    targetMarginPercent: 18,
    assumptionNotes: [
      "Direct subtotal sums material, labor, machine, energy, overhead, setup, shipping and payment-term cost.",
      "Waste cost = direct subtotal × waste rate.",
      "Target sales price = total cost ÷ (1 − target margin rate).",
      "Minimum safe price adds the safety margin uplift to the target margin rate.",
      "Tax-included flag is informational only in this release.",
    ],
  },
};
