import type { PremiumCalculatorSchema } from "@/lib/premium-schema/premium-calculator-schema";

const WAITING_OPPORTUNITY_MODE_OPTIONS = [
  { value: "none", label: "Exclude opportunity cost" },
  { value: "manualHourly", label: "Manual hourly opportunity cost" },
  { value: "derivedThroughput", label: "Derive from planned throughput" },
] as const;

const CURRENCY_CODE_OPTIONS = [
  { value: "USD", label: "USD — US Dollar" },
  { value: "EUR", label: "EUR — Euro" },
  { value: "GBP", label: "GBP — British Pound" },
  { value: "TRY", label: "TRY — Turkish Lira" },
  { value: "CHF", label: "CHF — Swiss Franc" },
  { value: "JPY", label: "JPY — Japanese Yen" },
  { value: "CAD", label: "CAD — Canadian Dollar" },
  { value: "AUD", label: "AUD — Australian Dollar" },
] as const;

export const SEVEN_MUDA_WASTE_COST_CALCULATOR_SCHEMA: PremiumCalculatorSchema = {
  id: "mfg-501",
  name: "7 Waste (Muda) Hunter Monetary Impact Calculator",
  sectorSlug: "manufacturing",
  category: "cost",
  painStatement:
    "Lean teams see waste categories qualitatively but cannot express each muda type in comparable monetary terms with period context and action priority.",

  inputs: [
    {
      id: "analysisPeriodDays",
      label: "Analysis period length",
      type: "number",
      unit: "days",
      required: true,
      smartDefault: 30,
      validation: { min: 1 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "workingDaysPerYear",
      label: "Working days per year",
      type: "number",
      unit: "days/year",
      required: true,
      smartDefault: 250,
      validation: { min: 1 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "productionUnitsInPeriod",
      label: "Production units in period",
      type: "number",
      unit: "units",
      required: true,
      smartDefault: 1000,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "currencyCode",
      label: "Currency code",
      type: "select",
      unit: "ISO 4217",
      required: true,
      smartDefault: "USD",
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
      options: [...CURRENCY_CODE_OPTIONS],
    },
    {
      id: "unitVariableCost",
      label: "Unit variable cost",
      type: "number",
      unit: "currency/unit",
      required: true,
      smartDefault: 50,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "unitSellingPrice",
      label: "Unit selling price",
      type: "number",
      unit: "currency/unit",
      required: true,
      smartDefault: 80,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "grossMarginPct",
      label: "Gross margin percent",
      type: "number",
      unit: "%",
      required: true,
      smartDefault: 25,
      validation: { min: 0, max: 100 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "excessUnits",
      label: "Excess production units",
      type: "number",
      unit: "units",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "excessInventoryHoldingDays",
      label: "Excess inventory holding days",
      type: "number",
      unit: "days",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "excessWriteDownCostPerUnit",
      label: "Excess write-down per unit",
      type: "number",
      unit: "currency/unit",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "waitingMinutes",
      label: "Waiting minutes",
      type: "number",
      unit: "minutes",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "affectedOperators",
      label: "Affected operators",
      type: "number",
      unit: "people",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "hourlyLaborCost",
      label: "Hourly labor cost",
      type: "number",
      unit: "currency/hour",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "affectedMachines",
      label: "Affected machines",
      type: "number",
      unit: "machines",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "hourlyMachineCost",
      label: "Hourly machine cost",
      type: "number",
      unit: "currency/hour",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "waitingOpportunityMode",
      label: "Waiting opportunity mode",
      type: "select",
      unit: "mode",
      required: true,
      smartDefault: "none",
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
      options: [...WAITING_OPPORTUNITY_MODE_OPTIONS],
    },
    {
      id: "hourlyOpportunityCost",
      label: "Hourly opportunity cost",
      type: "number",
      unit: "currency/hour",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "plannedUnitsPerHour",
      label: "Planned units per hour",
      type: "number",
      unit: "units/hour",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "transportDistanceKm",
      label: "Transport distance",
      type: "number",
      unit: "km",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "transportTrips",
      label: "Transport trips",
      type: "number",
      unit: "trips",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "transportCostPerKm",
      label: "Transport cost per km",
      type: "number",
      unit: "currency/km",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "handlingMinutesPerTrip",
      label: "Handling minutes per trip",
      type: "number",
      unit: "minutes/trip",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "handlingHourlyLaborCost",
      label: "Handling hourly labor cost",
      type: "number",
      unit: "currency/hour",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "transportDamageRatePct",
      label: "Transport damage rate",
      type: "number",
      unit: "%",
      required: false,
      smartDefault: 0,
      validation: { min: 0, max: 100 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "averageLoadValue",
      label: "Average load value",
      type: "number",
      unit: "currency",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "averageExcessInventoryValue",
      label: "Average excess inventory value",
      type: "number",
      unit: "currency",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "inventoryHoldingRatePct",
      label: "Inventory holding rate",
      type: "number",
      unit: "%/year",
      required: false,
      smartDefault: 0,
      validation: { min: 0, max: 100 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "inventoryObsolescenceValue",
      label: "Inventory obsolescence value",
      type: "number",
      unit: "currency",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "inventoryShrinkageRatePct",
      label: "Inventory shrinkage rate",
      type: "number",
      unit: "%",
      required: false,
      smartDefault: 0,
      validation: { min: 0, max: 100 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "unnecessaryMotionMinutes",
      label: "Unnecessary motion minutes",
      type: "number",
      unit: "minutes",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "motionAffectedOperators",
      label: "Motion affected operators",
      type: "number",
      unit: "people",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "motionHourlyLaborCost",
      label: "Motion hourly labor cost",
      type: "number",
      unit: "currency/hour",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "overprocessingMinutes",
      label: "Overprocessing minutes",
      type: "number",
      unit: "minutes",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "overprocessingHourlyResourceCost",
      label: "Overprocessing hourly resource cost",
      type: "number",
      unit: "currency/hour",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "extraMaterialCost",
      label: "Extra material cost",
      type: "number",
      unit: "currency",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "extraEnergyCost",
      label: "Extra energy cost",
      type: "number",
      unit: "currency",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "extraInspectionCost",
      label: "Extra inspection cost",
      type: "number",
      unit: "currency",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "scrapUnits",
      label: "Scrap units",
      type: "number",
      unit: "units",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "scrapDisposalCostPerUnit",
      label: "Scrap disposal cost per unit",
      type: "number",
      unit: "currency/unit",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "reworkMinutes",
      label: "Rework minutes",
      type: "number",
      unit: "minutes",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "reworkHourlyLaborCost",
      label: "Rework hourly labor cost",
      type: "number",
      unit: "currency/hour",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "reworkHourlyMachineCost",
      label: "Rework hourly machine cost",
      type: "number",
      unit: "currency/hour",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "customerReturnCost",
      label: "Customer return cost",
      type: "number",
      unit: "currency",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "warrantyCost",
      label: "Warranty cost",
      type: "number",
      unit: "currency",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "expediteCost",
      label: "Expedite cost",
      type: "number",
      unit: "currency",
      required: false,
      smartDefault: 0,
      validation: { min: 0 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "dataConfidencePct",
      label: "Data confidence",
      type: "number",
      unit: "%",
      required: true,
      smartDefault: 70,
      validation: { min: 0, max: 100 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
    {
      id: "implementationDifficultyScore",
      label: "Implementation difficulty",
      type: "number",
      unit: "1-5",
      required: true,
      smartDefault: 3,
      validation: { min: 1, max: 5, step: 1 },
      helper: "Please enter a valid value.",
      expertMeaning: "Parameter value complies with industrial calculation standards.",
    },
  ],

  formulaPipeline: [
    {
      formulaId: "lean.muda_overproduction_cost",
      inputMap: {
        excessUnits: "excessUnits",
        unitProductionCost: "unitVariableCost",
        inventoryHoldingRatePct: "inventoryHoldingRatePct",
      },
      outputId: "overproductionCost",
    },
    {
      formulaId: "lean.muda_waiting_cost",
      inputMap: {
        waitingMinutes: "waitingMinutes",
        resourceMinuteCost: "hourlyMachineCost",
      },
      outputId: "waitingCost",
    },
    {
      formulaId: "lean.muda_transport_cost",
      inputMap: {
        transportDistanceKm: "transportDistanceKm",
        transportTrips: "transportTrips",
        transportCostPerKm: "transportCostPerKm",
      },
      outputId: "transportCost",
    },
    {
      formulaId: "lean.muda_inventory_cost",
      inputMap: {
        averageExcessInventoryValue: "averageExcessInventoryValue",
        inventoryHoldingRatePct: "inventoryHoldingRatePct",
      },
      outputId: "inventoryCost",
    },
    {
      formulaId: "lean.muda_motion_cost",
      inputMap: {
        unnecessaryMotionMinutes: "unnecessaryMotionMinutes",
        laborMinuteCost: "motionHourlyLaborCost",
      },
      outputId: "motionCost",
    },
    {
      formulaId: "lean.muda_overprocessing_cost",
      inputMap: {
        overprocessingMinutes: "overprocessingMinutes",
        resourceMinuteCost: "overprocessingHourlyResourceCost",
        extraMaterialCost: "extraMaterialCost",
      },
      outputId: "overprocessingCost",
    },
    {
      formulaId: "lean.muda_defect_cost",
      inputMap: {
        scrapUnits: "scrapUnits",
        unitProductionCost: "unitVariableCost",
        reworkMinutes: "reworkMinutes",
        laborMinuteCost: "reworkHourlyLaborCost",
      },
      outputId: "defectCost",
    },
    {
      formulaId: "lean.muda_total_waste_cost",
      inputMap: {
        overproductionCost: "overproductionCost",
        waitingCost: "waitingCost",
        transportCost: "transportCost",
        inventoryCost: "inventoryCost",
        motionCost: "motionCost",
        overprocessingCost: "overprocessingCost",
        defectCost: "defectCost",
      },
      outputId: "totalWasteCost",
    },
    {
      formulaId: "lean.muda_annualized_waste_cost",
      inputMap: {},
      outputId: "annualizedWasteCost",
    },
    {
      formulaId: "lean.muda_waste_cost_per_unit",
      inputMap: {},
      outputId: "wasteCostPerUnit",
    },
    {
      formulaId: "lean.muda_period_revenue",
      inputMap: {},
      outputId: "periodRevenue",
    },
    {
      formulaId: "lean.muda_period_gross_margin_value",
      inputMap: {},
      outputId: "periodGrossMarginValue",
    },
    {
      formulaId: "lean.muda_waste_to_revenue_ratio_pct",
      inputMap: {},
      outputId: "wasteToRevenueRatioPct",
    },
    {
      formulaId: "lean.muda_waste_to_gross_margin_ratio_pct",
      inputMap: {},
      outputId: "wasteToGrossMarginRatioPct",
    },
    {
      formulaId: "lean.muda_highest_waste_cost",
      inputMap: {},
      outputId: "highestWasteCost",
    },
    {
      formulaId: "lean.muda_risk_adjusted_priority_score",
      inputMap: {},
      outputId: "riskAdjustedPriorityScore",
    },
    {
      formulaId: "lean.muda_highest_waste_index",
      inputMap: {
        overproductionCost: "overproductionCost",
        waitingCost: "waitingCost",
        transportCost: "transportCost",
        inventoryCost: "inventoryCost",
        motionCost: "motionCost",
        overprocessingCost: "overprocessingCost",
        defectCost: "defectCost",
      },
      outputId: "highestWasteCategoryIndex",
    },
  ],

  outputs: [
    {
      id: "totalWasteCost",
      label: "Total waste cost",
      unit: "currency",
      format: "currency",
      isBigNumber: true,
    },
    {
      id: "annualizedWasteCost",
      label: "Annualized waste cost",
      unit: "currency",
      format: "currency",
    },
    {
      id: "wasteCostPerUnit",
      label: "Waste cost per unit",
      unit: "currency",
      format: "currency",
    },
    {
      id: "periodRevenue",
      label: "Period revenue",
      unit: "currency",
      format: "currency",
    },
    {
      id: "periodGrossMarginValue",
      label: "Period gross margin value",
      unit: "currency",
      format: "currency",
    },
    {
      id: "wasteToRevenueRatioPct",
      label: "Waste to revenue ratio",
      unit: "%",
      format: "percentage",
    },
    {
      id: "wasteToGrossMarginRatioPct",
      label: "Waste to gross margin ratio",
      unit: "%",
      format: "percentage",
    },
    {
      id: "highestWasteCost",
      label: "Highest waste category cost",
      unit: "currency",
      format: "currency",
    },
    {
      id: "riskAdjustedPriorityScore",
      label: "Risk-adjusted priority score",
      unit: "score",
      format: "score",
    },
    {
      id: "overproductionCost",
      label: "Overproduction cost",
      unit: "currency",
      format: "currency",
    },
    {
      id: "waitingCost",
      label: "Waiting cost",
      unit: "currency",
      format: "currency",
    },
    {
      id: "transportCost",
      label: "Transport cost",
      unit: "currency",
      format: "currency",
    },
    {
      id: "inventoryCost",
      label: "Inventory cost",
      unit: "currency",
      format: "currency",
    },
    {
      id: "motionCost",
      label: "Motion cost",
      unit: "currency",
      format: "currency",
    },
    {
      id: "overprocessingCost",
      label: "Overprocessing cost",
      unit: "currency",
      format: "currency",
    },
    {
      id: "defectCost",
      label: "Defect cost",
      unit: "currency",
      format: "currency",
    },
    {
      id: "highestWasteCategoryIndex",
      label: "Highest waste category rank",
      unit: "rank",
      format: "number",
    },
  ],

  thresholds: [
    {
      fieldId: "totalWasteCost",
      warning: 5000,
      critical: 15000,
      direction: "higher_is_bad",
      warningMessage: "Total muda exposure is material — review the highest waste category and recommended action order.",
      criticalMessage: "Total muda exposure is severe — launch focused kaizen on the dominant waste driver.",
    },
  ],

  reportTemplate: {
    title: "7 Muda Monetary Impact Decision Report",
    sections: ["executive_summary", "loss_breakdown", "thresholds", "action_plan", "assumptions"],
    exportFormats: ["pdf", "csv"],
  },

  assumptions: {
    hiddenLossMultiplier: 1,
    volatilityPercent: 8,
    targetMarginPercent: 0,
    assumptionNotes: [
      "All monetary inputs must use the selected currencyCode for the analysis period.",
      "productionUnitsInPeriod is the production volume inside the selected analysis period only.",
      "excessWriteDownCostPerUnit is per excess unit, not a lump-sum write-down total.",
      "inventoryObsolescenceValue is stock write-down outside excess-production write-down.",
      "Hourly labor and machine rates are converted to minute costs inside the engineering calculator.",
      "waitingOpportunityMode controls whether opportunity cost is excluded, manual, or throughput-derived.",
      "Invalid inputs fail validation explicitly; schema smartDefault values must be present in submitted input values.",
    ],
  },
};
