import type { PremiumCalculatorSchema } from "@/lib/premium-schema/premium-calculator-schema";
export const QUALITY_COST_PAF_SCHEMA: PremiumCalculatorSchema = {
  id: "quality-cost-paf-analyzer", legacyPaidSlug: "quality-cost-paf-analyzer",
  name: "Kalite Maliyeti PAF Analizi", sectorSlug: "quality", category: "cost",
  painStatement: "PAF modeli olmadan kalite maliyetleri görünmez; önleme, değerlendirme, iç ve dış başarısızlık maliyetleri kontrol edilemez.",
  inputs: [
    { id: "training", label: "Eğitim Bütçesi", type: "number", unit: "USD", required: false, smartDefault: 10000, validation: { min: 0 }, helper: "", expertMeaning: "Quality training cost" },
    { id: "qualityPlanning", label: "Kalite Planlama", type: "number", unit: "USD", required: false, smartDefault: 15000, validation: { min: 0 }, helper: "", expertMeaning: "Quality planning cost" },
    { id: "supplierScore", label: "Tedarikçi Değerlendirme", type: "number", unit: "USD", required: false, smartDefault: 8000, validation: { min: 0 }, helper: "", expertMeaning: "Supplier evaluation cost" },
    { id: "designReview", label: "Tasarım Gözden Geçirme", type: "number", unit: "USD", required: false, smartDefault: 12000, validation: { min: 0 }, helper: "", expertMeaning: "Design review cost" },
    { id: "inspection", label: "Muayene Maliyeti", type: "number", unit: "USD", required: false, smartDefault: 20000, validation: { min: 0 }, helper: "", expertMeaning: "Inspection cost" },
    { id: "testing", label: "Test Maliyeti", type: "number", unit: "USD", required: false, smartDefault: 15000, validation: { min: 0 }, helper: "", expertMeaning: "Testing cost" },
    { id: "calibration", label: "Kalibrasyon", type: "number", unit: "USD", required: false, smartDefault: 5000, validation: { min: 0 }, helper: "", expertMeaning: "Calibration cost" },
    { id: "audit", label: "Denetim", type: "number", unit: "USD", required: false, smartDefault: 7000, validation: { min: 0 }, helper: "", expertMeaning: "Audit cost" },
    { id: "scrap", label: "Hurda Maliyeti", type: "number", unit: "USD", required: false, smartDefault: 30000, validation: { min: 0 }, helper: "", expertMeaning: "Scrap cost" },
    { id: "rework", label: "Yeniden İşleme", type: "number", unit: "USD", required: false, smartDefault: 25000, validation: { min: 0 }, helper: "", expertMeaning: "Rework cost" },
    { id: "reinspection", label: "Yeniden Muayene", type: "number", unit: "USD", required: false, smartDefault: 8000, validation: { min: 0 }, helper: "", expertMeaning: "Reinspection cost" },
    { id: "downtime", label: "Duruş Maliyeti", type: "number", unit: "USD", required: false, smartDefault: 12000, validation: { min: 0 }, helper: "", expertMeaning: "Downtime cost from quality" },
    { id: "warranty", label: "Garanti Maliyeti", type: "number", unit: "USD", required: false, smartDefault: 40000, validation: { min: 0 }, helper: "", expertMeaning: "Warranty cost" },
    { id: "returns", label: "İade Maliyeti", type: "number", unit: "USD", required: false, smartDefault: 15000, validation: { min: 0 }, helper: "", expertMeaning: "Returns cost" },
    { id: "recall", label: "Geri Çağırma", type: "number", unit: "USD", required: false, smartDefault: 50000, validation: { min: 0 }, helper: "", expertMeaning: "Recall cost" },
    { id: "liability", label: "Sorumluluk", type: "number", unit: "USD", required: false, smartDefault: 20000, validation: { min: 0 }, helper: "", expertMeaning: "Liability cost" },
    { id: "lostSales", label: "Kayıp Satış Tahmini", type: "number", unit: "USD", required: false, smartDefault: 60000, validation: { min: 0 }, helper: "", expertMeaning: "Lost sales estimate" },
    { id: "totalRevenue", label: "Toplam Gelir", type: "number", unit: "USD", required: true, smartDefault: 2000000, validation: { min: 1 }, helper: "", expertMeaning: "Total revenue for COQ ratio" },
  ],
  outputs: [
    { id: "prevention", label: "Önleme Maliyeti", unit: "USD", format: "currency" },
    { id: "appraisal", label: "Değerlendirme Maliyeti", unit: "USD", format: "currency" },
    { id: "internalFailure", label: "İç Başarısızlık", unit: "USD", format: "currency" },
    { id: "externalFailure", label: "Dış Başarısızlık", unit: "USD", format: "currency" },
    { id: "totalCoq", label: "Toplam Kalite Maliyeti (COQ)", unit: "USD", format: "currency", isBigNumber: true },
    { id: "coqRatio", label: "COQ / Gelir Oranı", unit: "%", format: "percentage" },
    { id: "pafRatio", label: "Önleme / COQ Oranı", unit: "%", format: "percentage" },
  ],
  thresholds: [{ fieldId: "coqRatio", warning: 0.05, critical: 0.15, direction: "higher_is_bad", warningMessage: "COQ > %5 — kalite yönetimi gözden geçirilmeli.", criticalMessage: "COQ > %15 — acil kalite iyileştirme programı başlatılmalı." }],
  formulaPipeline: [
    { formulaId: "cost.paf_prevention", inputMap: { training: "training", qualityPlanning: "qualityPlanning", supplierScoreRef: "supplierScore", designReview: "designReview" }, outputId: "prevention" },
    { formulaId: "cost.paf_appraisal", inputMap: { inspection: "inspection", testing: "testing", calibration: "calibration", audit: "audit" }, outputId: "appraisal" },
    { formulaId: "cost.paf_internal_failure", inputMap: { scrap: "scrap", rework: "rework", reinspection: "reinspection", downtime: "downtime" }, outputId: "internalFailure" },
    { formulaId: "cost.paf_external_failure", inputMap: { warranty: "warranty", returns: "returns", recall: "recall", liability: "liability", lostSales: "lostSales" }, outputId: "externalFailure" },
    { formulaId: "cost.paf_total", inputMap: { prevention: "prevention", appraisal: "appraisal", internalFailure: "internalFailure", externalFailure: "externalFailure" }, outputId: "totalCoq" },
    { formulaId: "cost.paf_ratio", inputMap: { totalCoq: "totalCoq", totalRevenue: "totalRevenue" }, outputId: "coqRatio" },
    { formulaId: "cost.paf_p_ratio", inputMap: { prevention: "prevention", totalCoq: "totalCoq" }, outputId: "pafRatio" },
  ],
  reportTemplate: { title: "Kalite Maliyeti PAF Raporu", sections: ["executive_summary", "loss_breakdown", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.15, volatilityPercent: 10, targetMarginPercent: 20, assumptionNotes: ["PAF = Prevention + Appraisal + Internal + External.", "COQ oranı > %15 kritik eşik.", "Önleme maliyeti arttıkça toplam COQ düşer (1:10 kuralı)."] },
};
