/**
 * Tool #50 — Hurda Oranı Optimize
 */
import type { PremiumCalculatorSchema } from "@/lib/premium-schema/premium-calculator-schema";
export const SCRAP_OPTIMIZE_SCHEMA: PremiumCalculatorSchema = {
  id: "scrap-rate-optimize-analyzer", legacyPaidSlug: "scrap-rate-optimize-analyzer",
  name: "Hurda Oranı Optimizasyon & Pareto Analizi", name_i18n: {"en":"Scrap Rate Optimization & Pareto Analysis","tr":"Hurda Oranı Optimizasyon & Pareto Analizi", sectorSlug: "sheet-metal", category: "cost",
  painStatement: "Hurda maliyeti sadece malzeme kaybı değildir; işçilik, makine ve fırsat maliyetini de içerir. Kaynak bazlı Pareto analizi gerekir.", painStatement_i18n: {"en":"Scrap cost is not just material loss; it includes labor, machine, and opportunity costs. Source-based Pareto analysis is needed.","tr":"Hurda maliyeti sadece malzeme kaybı değildir; işçilik, makine ve fırsat maliyetini de içerir. Kaynak bazlı Pareto analizi gerekir.",
  inputs: [
    { id: "scrapQty", label: "Hurda Miktarı", label_i18n: {"en":"Scrap Quantity","tr":"Hurda Miktarı", type: "number", unit: "adet/yıl", required: true, smartDefault: 5000, validation: { min: 0 }, helper: "", expertMeaning: "Annual scrap quantity", expertMeaning_i18n: {"en":"Annual scrap quantity","tr":"Annual scrap quantity" },
    { id: "totalInput", label: "Toplam Üretim Girdisi", label_i18n: {"en":"Total Production Input","tr":"Toplam Üretim Girdisi", type: "number", unit: "adet/yıl", required: true, smartDefault: 100000, validation: { min: 1 }, helper: "", expertMeaning: "Total input quantity", expertMeaning_i18n: {"en":"Total input quantity","tr":"Total input quantity" },
    { id: "matCost", label: "Hammadde Maliyeti/Adet", label_i18n: {"en":"Material Cost/Unit","tr":"Hammadde Maliyeti/Adet", type: "number", unit: "USD", required: true, smartDefault: 2, validation: { min: 0 }, helper: "", expertMeaning: "Material cost per unit", expertMeaning_i18n: {"en":"Material cost per unit","tr":"Material cost per unit" },
    { id: "cycleTime", label: "Çevrim Süresi", label_i18n: {"en":"Cycle Time","tr":"Çevrim Süresi", type: "number", unit: "dak", required: false, smartDefault: 2, validation: { min: 0 }, helper: "", expertMeaning: "Cycle time per part", expertMeaning_i18n: {"en":"Cycle time per part","tr":"Cycle time per part" },
    { id: "labRate", label: "İşçilik Saat Ücreti", label_i18n: {"en":"Labor Hourly Rate","tr":"İşçilik Saat Ücreti", type: "number", unit: "USD/saat", required: false, smartDefault: 25, validation: { min: 0 }, helper: "", expertMeaning: "Labor hourly rate", expertMeaning_i18n: {"en":"Labor hourly rate","tr":"Labor hourly rate" },
    { id: "machRate", label: "Makine Saat Ücreti", label_i18n: {"en":"Machine Hourly Rate","tr":"Makine Saat Ücreti", type: "number", unit: "USD/saat", required: false, smartDefault: 75, validation: { min: 0 }, helper: "", expertMeaning: "Machine hourly rate", expertMeaning_i18n: {"en":"Machine hourly rate","tr":"Machine hourly rate" },
    { id: "unitMargin", label: "Birim Kâr Marjı", label_i18n: {"en":"Unit Profit Margin","tr":"Birim Kâr Marjı", type: "number", unit: "USD", required: false, smartDefault: 5, validation: { min: 0 }, helper: "", expertMeaning: "Profit margin per unit", expertMeaning_i18n: {"en":"Profit margin per unit","tr":"Profit margin per unit" },
    { id: "salvage", label: "Kurtarma Geliri/Adet", label_i18n: {"en":"Salvage Value/Unit","tr":"Kurtarma Geliri/Adet", type: "number", unit: "USD", required: false, smartDefault: 0.5, validation: { min: 0 }, helper: "", expertMeaning: "Salvage value per scrap", expertMeaning_i18n: {"en":"Salvage value per scrap","tr":"Salvage value per scrap" },
    { id: "benchmarkRate", label: "Hedef (Benchmark) Hurda Oranı", label_i18n: {"en":"Target (Benchmark) Scrap Rate","tr":"Hedef (Benchmark) Hurda Oranı", type: "number", unit: "%", required: false, smartDefault: 3, validation: { min: 0, max: 100 }, helper: "", expertMeaning: "Target scrap rate", expertMeaning_i18n: {"en":"Target scrap rate","tr":"Target scrap rate" },
    { id: "impFactor", label: "İyileştirme Faktörü", label_i18n: {"en":"Improvement Factor","tr":"İyileştirme Faktörü", type: "number", unit: "%", required: false, smartDefault: 20, validation: { min: 0, max: 100 }, helper: "", expertMeaning: "Expected improvement", expertMeaning_i18n: {"en":"Expected improvement","tr":"Expected improvement" },
  ],
  outputs: [
    { id: "currentScrapRate", label: "Mevcut Hurda Oranı", label_i18n: {"en":"Mevcut Hurda Oranı","tr":"Mevcut Hurda Oranı"}, unit: "%", format: "percentage" },
    { id: "totalScrapCost", label: "Toplam Hurda Maliyeti", label_i18n: {"en":"Toplam Hurda Maliyeti","tr":"Toplam Hurda Maliyeti"}, unit: "USD/yıl", format: "currency", isBigNumber: true },
  ],
  thresholds: [{ fieldId: "currentScrapRate", warning: 5, critical: 10, direction: "higher_is_bad", warningMessage: "Hurda oranı > %5 — iyileştirme programı başlatılmalı.", warningMessage_i18n: {"en":"Scrap rate > 5% — initiate improvement program.","tr":"Hurda oranı > %5 — iyileştirme programı başlatılmalı.", criticalMessage: "Hurda oranı > %10 — acil proses iyileştirme.", criticalMessage_i18n: {"en":"Scrap rate > 10% — urgent process improvement.","tr":"Hurda oranı > %10 — acil proses iyileştirme." }],
  formulaPipeline: [
    { formulaId: "cost.scrap_optimize_total", inputMap: { scrapMaterialCost: "matCost", scrapLaborCost: "cycleTime", scrapOverhead: "machRate", scrapOpportunity: "unitMargin", scrapSalvage: "salvage" }, outputId: "totalScrapCost" },
  ],
  reportTemplate: { title: "Scrap Rate Optimization Report", title_i18n: {"en":"Scrap Rate Optimization Report","tr":"Scrap Rate Optimization Report"}, sections: ["executive_summary", "loss_breakdown", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.15, volatilityPercent: 15, targetMarginPercent: 20, assumptionNotes: ["ScrapRate = ScrapQty/TotalInput.", "Total = Scrap×(MatCost+Labor+OH+Margin)-Salvage.", "Target = Benchmark×(1-ImpFactor)."],assumptionNotes_i18n:[{"en":"ScrapRate = ScrapQty/TotalInput.","tr":"ScrapRate = ScrapQty/TotalInput."},{"en":"Total = Scrap×(MatCost+Labor+OH+Margin)-Salvage.","tr":"Total = Scrap×(MatCost+Labor+OH+Margin)-Salvage."},{"en":"Target = Benchmark×(1-ImpFactor).","tr":"Target = Benchmark×(1-ImpFactor)."}] },
};
