import type { PremiumCalculatorSchema } from "@/lib/premium-schema/premium-calculator-schema";
export const SHOP_HOURLY_RATE_SCHEMA: PremiumCalculatorSchema = {
  id: "shop-hourly-rate-analyzer", legacyPaidSlug: "shop-hourly-rate-analyzer",
  name: "Mağaza Saatlik Ücret", sectorSlug: "financial-planning", category: "cost",
  painStatement: "Atölye saatlik ücreti doğru hesaplanmazsa, faturalama zararı ve marj kaybı oluşur.",
  inputs: [
    { id: "technicianWages", label: "Teknisyen Ücretleri", type: "number", unit: "USD/ay", required: true, smartDefault: 15000, validation: { min: 0 }, helper: "", expertMeaning: "Total technician wages" },
    { id: "managerWages", label: "Yönetici Ücretleri", type: "number", unit: "USD/ay", required: false, smartDefault: 8000, validation: { min: 0 }, helper: "", expertMeaning: "Manager wages" },
    { id: "adminWages", label: "İdari Ücretler", type: "number", unit: "USD/ay", required: false, smartDefault: 5000, validation: { min: 0 }, helper: "", expertMeaning: "Admin wages" },
    { id: "rent", label: "Kira", type: "number", unit: "USD/ay", required: true, smartDefault: 5000, validation: { min: 0 }, helper: "", expertMeaning: "Monthly rent" },
    { id: "utilities", label: "Fatura", type: "number", unit: "USD/ay", required: false, smartDefault: 2000, validation: { min: 0 }, helper: "", expertMeaning: "Utilities" },
    { id: "insurance", label: "Sigorta", type: "number", unit: "USD/ay", required: false, smartDefault: 1000, validation: { min: 0 }, helper: "", expertMeaning: "Insurance" },
    { id: "tools", label: "Alet/Ekipman", type: "number", unit: "USD/ay", required: false, smartDefault: 1500, validation: { min: 0 }, helper: "", expertMeaning: "Tools & equipment" },
    { id: "depreciation", label: "Amortisman", type: "number", unit: "USD/ay", required: false, smartDefault: 2000, validation: { min: 0 }, helper: "", expertMeaning: "Monthly depreciation" },
    { id: "totalAvailableHours", label: "Toplam Faturalanabilir Saat", type: "number", unit: "saat/ay", required: true, smartDefault: 500, validation: { min: 1 }, helper: "", expertMeaning: "Total billable hours" },
    { id: "utilizationRate", label: "Kullanım Oranı", type: "number", unit: "", required: false, smartDefault: 0.75, validation: { min: 0, max: 1 }, helper: "", expertMeaning: "Utilization rate" },
    { id: "targetMargin", label: "Hedef Kâr Marjı", type: "number", unit: "%", required: false, smartDefault: 30, validation: { min: 0, max: 100 }, helper: "", expertMeaning: "Target profit margin" },
    { id: "actualBillingRate", label: "Gerçek Faturalama Ücreti", type: "number", unit: "USD/saat", required: true, smartDefault: 95, validation: { min: 0 }, helper: "", expertMeaning: "Actual billing rate" },
  ],
  outputs: [
    { id: "directLabor", label: "Direkt İşçilik", unit: "USD/ay", format: "currency" },
    { id: "indirectLabor", label: "Endirekt İşçilik", unit: "USD/ay", format: "currency" },
    { id: "overhead", label: "Genel Gider", unit: "USD/ay", format: "currency" },
    { id: "totalShopCost", label: "Toplam Atölye Maliyeti", unit: "USD/ay", format: "currency", isBigNumber: true },
    { id: "billableHours", label: "Faturalanabilir Saat", unit: "saat/ay", format: "number" },
    { id: "shopHourlyRate", label: "Atölye Saatlik Ücreti", unit: "USD/saat", format: "currency" },
    { id: "effectiveMargin", label: "Gerçek Marj", unit: "%", format: "percentage" },
  ],
  thresholds: [{ fieldId: "effectiveMargin", warning: 20, critical: 10, direction: "lower_is_bad", warningMessage: "Marj < %20 — maliyet yapısı gözden geçirilmeli.", criticalMessage: "Marj < %10 — acil fiyatlandırma revizyonu." }],
  formulaPipeline: [
    { formulaId: "cost.shop_direct_labor", inputMap: { technicianWages: "technicianWages" }, outputId: "directLabor" },
    { formulaId: "cost.shop_indirect_labor", inputMap: { managerWages: "managerWages", adminWages: "adminWages" }, outputId: "indirectLabor" },
    { formulaId: "cost.shop_overhead", inputMap: { rent: "rent", utilities: "utilities", insurance: "insurance", tools: "tools", depreciation: "depreciation" }, outputId: "overhead" },
    { formulaId: "cost.shop_total_cost", inputMap: { directLabor: "directLabor", indirectLabor: "indirectLabor", overhead: "overhead" }, outputId: "totalShopCost" },
    { formulaId: "cost.shop_billable_hours", inputMap: { totalAvailableHours: "totalAvailableHours", utilizationRate: "utilizationRate" }, outputId: "billableHours" },
    { formulaId: "cost.shop_hourly_rate", inputMap: { totalShopCost: "totalShopCost", billableHours: "billableHours" }, outputId: "shopHourlyRate" },
    { formulaId: "cost.shop_effective_margin", inputMap: { actualBillingRate: "actualBillingRate", shopHourlyRate: "shopHourlyRate" }, outputId: "effectiveMargin" },
  ],
  reportTemplate: { title: "Atölye Saatlik Ücret Raporu", sections: ["executive_summary", "loss_breakdown", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.1, volatilityPercent: 10, targetMarginPercent: 20, assumptionNotes: ["Saatlik ücret = Toplam maliyet / Faturalanabilir saat.", "Marj = (Faturalama - Maliyet) / Faturalama.", "Kullanım oranı fiili doluluğu yansıtır."] },
};
