/**
 * Tool — Takım Aşınma
 */
import type { PremiumCalculatorSchema } from "@/lib/premium-schema/premium-calculator-schema";
export const TOOL_WEAR_COST_ANALYZER: PremiumCalculatorSchema = {
  id: "tool-wear-cost-analyzer", legacyPaidSlug: "tool-wear-cost-analyzer",
  name: "Takım Aşınma Maliyet Analizi", name_i18n: {"en":"Takım Aşınma Maliyet Analizi","tr":"Takım Aşınma Maliyet Analizi"}, sectorSlug: "cnc-manufacturing", category: "cost",
  painStatement: "Kesici takım aşınması takip edilmezse parça başı takım maliyeti artar, erken kırılmalar plansız duruşlara ve yüksek hurda oranına yol açar.", painStatement_i18n: {"en":"Kesici takım aşınması takip edilmezse parça başı takım maliyeti artar, erken kırılmalar plansız duruşlara ve yüksek hurda oranına yol açar.","tr":"Kesici takım aşınması takip edilmezse parça başı takım maliyeti artar, erken kırılmalar plansız duruşlara ve yüksek hurda oranına yol açar."},
  inputs: [
    { id: "toolCost", label: "Takım Birim Maliyeti", label_i18n: {"en":"Takım Birim Maliyeti","tr":"Takım Birim Maliyeti"}, type: "number", unit: "USD/takım", required: true, smartDefault: 50, validation: { min: 0.01 }, helper: "", expertMeaning: "Cost per tool", expertMeaning_i18n: {"en":"Cost per tool","tr":"Cost per tool"} },
    { id: "toolLifeParts", label: "Takım Ömrü", label_i18n: {"en":"Takım Ömrü","tr":"Takım Ömrü"}, type: "number", unit: "parça", required: true, smartDefault: 500, validation: { min: 1 }, helper: "", expertMeaning: "Parts produced per tool life", expertMeaning_i18n: {"en":"Parts produced per tool life","tr":"Parts produced per tool life"} },
    { id: "annualPartVolume", label: "Yıllık Parça Hacmi", label_i18n: {"en":"Yıllık Parça Hacmi","tr":"Yıllık Parça Hacmi"}, type: "number", unit: "adet", required: true, smartDefault: 50000, validation: { min: 1 }, helper: "", expertMeaning: "Annual part production volume", expertMeaning_i18n: {"en":"Annual part production volume","tr":"Annual part production volume"} },
    { id: "toolChangeTime", label: "Takım Değişim Süresi", label_i18n: {"en":"Takım Değişim Süresi","tr":"Takım Değişim Süresi"}, type: "number", unit: "dakika", required: false, smartDefault: 5, validation: { min: 0 }, helper: "", expertMeaning: "Tool change time in minutes", expertMeaning_i18n: {"en":"Tool change time in minutes","tr":"Tool change time in minutes"} },
    { id: "machineRate", label: "Makine Saatlik Maliyeti", label_i18n: {"en":"Makine Saatlik Maliyeti","tr":"Makine Saatlik Maliyeti"}, type: "number", unit: "USD/saat", required: false, smartDefault: 85, validation: { min: 1 }, helper: "", expertMeaning: "Machine hourly cost", expertMeaning_i18n: {"en":"Machine hourly cost","tr":"Machine hourly cost"} },
    { id: "prematureFailureRate", label: "Erken Kırılma Oranı", label_i18n: {"en":"Erken Kırılma Oranı","tr":"Erken Kırılma Oranı"}, type: "number", unit: "%", required: false, smartDefault: 5, validation: { min: 0, max: 100 }, helper: "", expertMeaning: "Premature tool failure rate", expertMeaning_i18n: {"en":"Premature tool failure rate","tr":"Premature tool failure rate"} },
    { id: "scrapCostPerFail", label: "Kırılma Başına Hurda Maliyeti", label_i18n: {"en":"Kırılma Başına Hurda Maliyeti","tr":"Kırılma Başına Hurda Maliyeti"}, type: "number", unit: "USD", required: false, smartDefault: 20, validation: { min: 0 }, helper: "", expertMeaning: "Scrap cost per tool failure", expertMeaning_i18n: {"en":"Scrap cost per tool failure","tr":"Scrap cost per tool failure"} },
    { id: "numToolsPerYear", label: "Yıllık Kullanılan Takım Sayısı", label_i18n: {"en":"Yıllık Kullanılan Takım Sayısı","tr":"Yıllık Kullanılan Takım Sayısı"}, type: "number", unit: "adet/yıl", required: false, smartDefault: 100, validation: { min: 1 }, helper: "", expertMeaning: "Number of tools used per year", expertMeaning_i18n: {"en":"Number of tools used per year","tr":"Number of tools used per year"} },
  ],
  outputs: [
    { id: "toolingCostPerPart", label: "Parça Başı Takım Maliyeti", label_i18n: {"en":"Parça Başı Takım Maliyeti","tr":"Parça Başı Takım Maliyeti"}, unit: "USD/parça", format: "currency" },
    { id: "toolingTotal", label: "Toplam Takım Maliyeti", label_i18n: {"en":"Toplam Takım Maliyeti","tr":"Toplam Takım Maliyeti"}, unit: "USD/yıl", format: "currency", isBigNumber: true },
    { id: "prematureFailureCost", label: "Erken Kırılma Maliyeti", label_i18n: {"en":"Erken Kırılma Maliyeti","tr":"Erken Kırılma Maliyeti"}, unit: "USD/yıl", format: "currency" },
  ],
  thresholds: [{ fieldId: "toolingCostPerPart", warning: 0.15, critical: 0.3, direction: "higher_is_bad", warningMessage: "Parça başı takım maliyeti >$0.15 — takım ömrü iyileştirilmeli.", warningMessage_i18n: {"en":"Parça başı takım maliyeti >$0.15 — takım ömrü iyileştirilmeli.","tr":"Parça başı takım maliyeti >$0.15 — takım ömrü iyileştirilmeli."}, criticalMessage: "Parça başı takım maliyeti >$0.30 — takım seçimi veya kesme parametreleri gözden geçirilmeli.", criticalMessage_i18n: {"en":"Parça başı takım maliyeti >$0.30 — takım seçimi veya kesme parametreleri gözden geçirilmeli.","tr":"Parça başı takım maliyeti >$0.30 — takım seçimi veya kesme parametreleri gözden geçirilmeli."} }],
  formulaPipeline: [
    { formulaId: "cost.tooling_cost_per_part", inputMap: { toolCost: "toolCost", toolLifeParts: "toolLifeParts" }, outputId: "toolingCostPerPart" },
    { formulaId: "cost.tooling_total", inputMap: { toolingCostPerPart: "toolingCostPerPart", annualPartVolume: "annualPartVolume", toolChangeTime: "toolChangeTime", machineRate: "machineRate" }, outputId: "toolingTotal" },
    { formulaId: "cost.premature_failure_cost", inputMap: { prematureFailureRate: "prematureFailureRate", numToolsPerYear: "numToolsPerYear", toolCost: "toolCost", scrapCostPerFail: "scrapCostPerFail" }, outputId: "prematureFailureCost" },
  ],
  reportTemplate: { title: "Takım Aşınma Maliyet Raporu", title_i18n: {"en":"Takım Aşınma Maliyet Raporu","tr":"Takım Aşınma Maliyet Raporu"}, sections: ["executive_summary", "loss_breakdown", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.1, volatilityPercent: 10, targetMarginPercent: 15, assumptionNotes: ["Parça başı takım maliyeti = takım fiyatı / takım ömrü.", "Toplam maliyet = parça başı × yıllık hacim + değişim maliyeti.", "Erken kırılma maliyeti = kırılma oranı × (takım + hurda) × yıllık takım.", "Takız ömrü Taylor takım ömrü denklemine göre belirlenir."],assumptionNotes_i18n:[{"en":"Parça başı takım maliyeti = takım fiyatı / takım ömrü.","tr":"Parça başı takım maliyeti = takım fiyatı / takım ömrü."},{"en":"Toplam maliyet = parça başı × yıllık hacim + değişim maliyeti.","tr":"Toplam maliyet = parça başı × yıllık hacim + değişim maliyeti."},{"en":"Erken kırılma maliyeti = kırılma oranı × (takım + hurda) × yıllık takım.","tr":"Erken kırılma maliyeti = kırılma oranı × (takım + hurda) × yıllık takım."},{"en":"Takız ömrü Taylor takım ömrü denklemine göre belirlenir.","tr":"Takız ömrü Taylor takım ömrü denklemine göre belirlenir."}] },
};
