/**
 * Tool #29 — Depo Yerleşimi
 */
import type { PremiumCalculatorSchema } from "@/lib/premium-schema/premium-calculator-schema";
export const WAREHOUSE_LAYOUT_SCHEMA: PremiumCalculatorSchema = {
  id: "warehouse-layout-analyzer", legacyPaidSlug: "warehouse-layout-analyzer",
  name: "Depo Yerleşimi & Verimlilik Analizi", name_i18n: {"en":"Depo Yerleşimi & Verimlilik Analizi","tr":"Depo Yerleşimi & Verimlilik Analizi"}, sectorSlug: "logistics-transport", category: "measurement",
  painStatement: "Depo yerleşimi optimize edilmezse palet pozisyonu, throughput ve toplama verimliliği düşer, işletme maliyeti artar.", painStatement_i18n: {"en":"Depo yerleşimi optimize edilmezse palet pozisyonu, throughput ve toplama verimliliği düşer, işletme maliyeti artar.","tr":"Depo yerleşimi optimize edilmezse palet pozisyonu, throughput ve toplama verimliliği düşer, işletme maliyeti artar."},
  inputs: [
    { id: "warehouseFootprint", label: "Depo Taban Alanı", label_i18n: {"en":"Depo Taban Alanı","tr":"Depo Taban Alanı"}, type: "number", unit: "m²", required: true, smartDefault: 2000, validation: { min: 1 }, helper: "", expertMeaning: "Warehouse footprint", expertMeaning_i18n: {"en":"Warehouse footprint","tr":"Warehouse footprint"} },
    { id: "utilRate", label: "Depolama Kullanım Oranı", label_i18n: {"en":"Depolama Kullanım Oranı","tr":"Depolama Kullanım Oranı"}, type: "number", unit: "%", required: true, smartDefault: 70, validation: { min: 1, max: 100 }, helper: "", expertMeaning: "Storage utilization rate", expertMeaning_i18n: {"en":"Storage utilization rate","tr":"Storage utilization rate"} },
    { id: "palletFootprint", label: "Palet Alanı", label_i18n: {"en":"Palet Alanı","tr":"Palet Alanı"}, type: "number", unit: "m²", required: true, smartDefault: 1.0, validation: { min: 0.1 }, helper: "", expertMeaning: "Pallet footprint (L×W)", expertMeaning_i18n: {"en":"Pallet footprint (L×W)","tr":"Pallet footprint (L×W)"} },
    { id: "aisleFactor", label: "Koridor Katsayısı", label_i18n: {"en":"Koridor Katsayısı","tr":"Koridor Katsayısı"}, type: "number", unit: "", required: true, smartDefault: 1.5, validation: { min: 1 }, helper: "", expertMeaning: "Aisle space multiplier", expertMeaning_i18n: {"en":"Aisle space multiplier","tr":"Aisle space multiplier"} },
    { id: "rackLevels", label: "Raf Seviye Sayısı", label_i18n: {"en":"Raf Seviye Sayısı","tr":"Raf Seviye Sayısı"}, type: "number", unit: "", required: true, smartDefault: 4, validation: { min: 1 }, helper: "", expertMeaning: "Number of rack levels", expertMeaning_i18n: {"en":"Number of rack levels","tr":"Number of rack levels"} },
    { id: "doorCount", label: "Yükleme Kapısı Sayısı", label_i18n: {"en":"Yükleme Kapısı Sayısı","tr":"Yükleme Kapısı Sayısı"}, type: "number", unit: "", required: false, smartDefault: 4, validation: { min: 1 }, helper: "", expertMeaning: "Number of loading doors", expertMeaning_i18n: {"en":"Number of loading doors","tr":"Number of loading doors"} },
    { id: "turnaroundLoad", label: "Yükleme Süresi", label_i18n: {"en":"Yükleme Süresi","tr":"Yükleme Süresi"}, type: "number", unit: "saat", required: false, smartDefault: 0.5, validation: { min: 0 }, helper: "", expertMeaning: "Loading turnaround hours", expertMeaning_i18n: {"en":"Loading turnaround hours","tr":"Loading turnaround hours"} },
    { id: "turnaroundUnload", label: "Boşaltma Süresi", label_i18n: {"en":"Boşaltma Süresi","tr":"Boşaltma Süresi"}, type: "number", unit: "saat", required: false, smartDefault: 0.5, validation: { min: 0 }, helper: "", expertMeaning: "Unloading turnaround hours", expertMeaning_i18n: {"en":"Unloading turnaround hours","tr":"Unloading turnaround hours"} },
    { id: "pickLines", label: "Toplama Kalemi Sayısı", label_i18n: {"en":"Toplama Kalemi Sayısı","tr":"Toplama Kalemi Sayısı"}, type: "number", unit: "adet/gün", required: false, smartDefault: 500, validation: { min: 0 }, helper: "", expertMeaning: "Daily pick lines", expertMeaning_i18n: {"en":"Daily pick lines","tr":"Daily pick lines"} },
    { id: "travelTime", label: "Toplam Seyahat Süresi", label_i18n: {"en":"Toplam Seyahat Süresi","tr":"Toplam Seyahat Süresi"}, type: "number", unit: "saat/gün", required: false, smartDefault: 40, validation: { min: 0 }, helper: "", expertMeaning: "Daily travel time for picking", expertMeaning_i18n: {"en":"Daily travel time for picking","tr":"Daily travel time for picking"} },
    { id: "facilityCost", label: "Tesis Yıllık Maliyeti", label_i18n: {"en":"Tesis Yıllık Maliyeti","tr":"Tesis Yıllık Maliyeti"}, type: "number", unit: "USD/yıl", required: false, smartDefault: 120000, validation: { min: 0 }, helper: "", expertMeaning: "Total facility cost", expertMeaning_i18n: {"en":"Total facility cost","tr":"Total facility cost"} },
  ],
  outputs: [
    { id: "palletPositions", label: "Palet Pozisyonu (Tek Kat)", label_i18n: {"en":"Palet Pozisyonu (Tek Kat)","tr":"Palet Pozisyonu (Tek Kat)"}, unit: "adet", format: "number" },
    { id: "verticalCap", label: "Dikey Kapasite", label_i18n: {"en":"Dikey Kapasite","tr":"Dikey Kapasite"}, unit: "adet", format: "number" },
    { id: "throughputCap", label: "Throughput Kapasitesi", label_i18n: {"en":"Throughput Kapasitesi","tr":"Throughput Kapasitesi"}, unit: "araç/gün", format: "number" },
    { id: "pickEfficiency", label: "Toplama Verimliliği", label_i18n: {"en":"Toplama Verimliliği","tr":"Toplama Verimliliği"}, unit: "kalem/saat", format: "number" },
    { id: "costPerPosition", label: "Pozisyon Başına Maliyet", label_i18n: {"en":"Pozisyon Başına Maliyet","tr":"Pozisyon Başına Maliyet"}, unit: "USD/yıl", format: "currency", isBigNumber: true },
  ],
  thresholds: [{ fieldId: "costPerPosition", warning: 150, critical: 250, direction: "higher_is_bad", warningMessage: "Pozisyon maliyeti > $150 — optimizasyon fırsatı var.", warningMessage_i18n: {"en":"Pozisyon maliyeti > $150 — optimizasyon fırsatı var.","tr":"Pozisyon maliyeti > $150 — optimizasyon fırsatı var."}, criticalMessage: "Pozisyon maliyeti > $250 — depo verimliliği düşük.", criticalMessage_i18n: {"en":"Pozisyon maliyeti > $250 — depo verimliliği düşük.","tr":"Pozisyon maliyeti > $250 — depo verimliliği düşük."} }],
  formulaPipeline: [
    { formulaId: "measurement.warehouse_pallet_positions", inputMap: { warehouseFootprint: "warehouseFootprint", utilRate: "utilRate", palletFootprint: "palletFootprint", aisleFactor: "aisleFactor" }, outputId: "palletPositions" },
    { formulaId: "measurement.warehouse_vertical_cap", inputMap: { palletPositions: "palletPositions", rackLevels: "rackLevels" }, outputId: "verticalCap" },
    { formulaId: "measurement.warehouse_throughput_cap", inputMap: { doorCount: "doorCount", turnaroundLoad: "turnaroundLoad", turnaroundUnload: "turnaroundUnload" }, outputId: "throughputCap" },
    { formulaId: "measurement.warehouse_pick_efficiency", inputMap: { pickLines: "pickLines", travelTime: "travelTime" }, outputId: "pickEfficiency" },
    { formulaId: "cost.warehouse_cost_per_pos", inputMap: { facilityCost: "facilityCost", palletPositions: "palletPositions" }, outputId: "costPerPosition" },
  ],
  reportTemplate: { title: "Warehouse Layout Report", title_i18n: {"en":"Warehouse Layout Report","tr":"Warehouse Layout Report"}, sections: ["executive_summary", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.1, volatilityPercent: 10, targetMarginPercent: 15, assumptionNotes: ["Positions = (Area×UtilRate)/(PalletFP×AisleFactor).", "Throughput = Doors/(TurnLoad+TurnUnload).", "PickEfficiency = Lines/TravelTime."],assumptionNotes_i18n:[{"en":"Positions = (Area×UtilRate)/(PalletFP×AisleFactor).","tr":"Positions = (Area×UtilRate)/(PalletFP×AisleFactor)."},{"en":"Throughput = Doors/(TurnLoad+TurnUnload).","tr":"Throughput = Doors/(TurnLoad+TurnUnload)."},{"en":"PickEfficiency = Lines/TravelTime.","tr":"PickEfficiency = Lines/TravelTime."}] },
};
