import type { PremiumCalculatorSchema } from "@/lib/premium-schema/premium-calculator-schema";
export const WELD_VOLUME_COST_SCHEMA: PremiumCalculatorSchema = {
  id: "weld-volume-cost-analyzer", legacyPaidSlug: "weld-volume-cost-analyzer",
  name: "Kaynak Hacmi ve Maliyeti", sectorSlug: "cnc-manufacturing", category: "cost",
  painStatement: "Kaynak hacmi ve dolgu maliyeti hesaplanmazsa, tahminlerin üzerinde malzeme ve işçilik gideri oluşur.",
  inputs: [
    { id: "leg", label: "Kaynak Ağız Boyu (Leg)", type: "number", unit: "mm", required: true, smartDefault: 6, validation: { min: 1 }, helper: "", expertMeaning: "Fillet weld leg size" },
    { id: "weldLength", label: "Kaynak Uzunluğu", type: "number", unit: "m", required: true, smartDefault: 10, validation: { min: 0.1 }, helper: "", expertMeaning: "Total weld length" },
    { id: "density", label: "Malzeme Yoğunluğu", type: "number", unit: "kg/m³", required: false, smartDefault: 7850, validation: { min: 0 }, helper: "", expertMeaning: "Weld metal density" },
    { id: "depEff", label: "Biriktirme Verimi", type: "number", unit: "", required: false, smartDefault: 0.8, validation: { min: 0, max: 1 }, helper: "", expertMeaning: "Deposition efficiency" },
    { id: "pricePerKg", label: "Dolgu Teli Fiyatı", type: "number", unit: "USD/kg", required: true, smartDefault: 5, validation: { min: 0 }, helper: "", expertMeaning: "Filler wire price" },
    { id: "gasFlowRate", label: "Gaz Debisi", type: "number", unit: "L/dk", required: false, smartDefault: 15, validation: { min: 0 }, helper: "", expertMeaning: "Shielding gas flow rate" },
    { id: "arcTime", label: "Ark Süresi", type: "number", unit: "saat", required: true, smartDefault: 2, validation: { min: 0.1 }, helper: "", expertMeaning: "Total arc-on time" },
    { id: "gasPrice", label: "Gaz Fiyatı", type: "number", unit: "USD/L", required: false, smartDefault: 0.05, validation: { min: 0 }, helper: "", expertMeaning: "Gas price per liter" },
    { id: "voltage", label: "Voltaj", type: "number", unit: "V", required: false, smartDefault: 26, validation: { min: 0 }, helper: "", expertMeaning: "Welding voltage" },
    { id: "current", label: "Akım", type: "number", unit: "A", required: false, smartDefault: 280, validation: { min: 0 }, helper: "", expertMeaning: "Welding current" },
    { id: "machineEff", label: "Makine Verimi", type: "number", unit: "", required: false, smartDefault: 0.85, validation: { min: 0, max: 1 }, helper: "", expertMeaning: "Machine efficiency" },
    { id: "elecRate", label: "Elektrik Tarifesi", type: "number", unit: "USD/kWh", required: false, smartDefault: 0.12, validation: { min: 0 }, helper: "", expertMeaning: "Electricity rate" },
    { id: "depRate", label: "Biriktirme Hızı", type: "number", unit: "kg/saat", required: false, smartDefault: 2.5, validation: { min: 0 }, helper: "", expertMeaning: "Deposition rate" },
    { id: "laborRate", label: "İşçilik Saat Ücreti", type: "number", unit: "USD/saat", required: true, smartDefault: 35, validation: { min: 0 }, helper: "", expertMeaning: "Labor cost per hour" },
  ],
  outputs: [
    { id: "weldArea", label: "Kesit Alanı", unit: "mm²", format: "number" },
    { id: "weldVolume", label: "Kaynak Hacmi", unit: "mm³", format: "number" },
    { id: "depositedWeight", label: "Biriktirilen Ağırlık", unit: "kg", format: "number" },
    { id: "electrodeWeight", label: "Elektrod Ağırlığı", unit: "kg", format: "number" },
    { id: "fillerCost", label: "Dolgu Maliyeti", unit: "USD", format: "currency" },
    { id: "gasCost", label: "Gaz Maliyeti", unit: "USD", format: "currency" },
    { id: "powerCost", label: "Enerji Maliyeti", unit: "USD", format: "currency" },
    { id: "totalWeldCost", label: "Toplam Kaynak Maliyeti", unit: "USD", format: "currency", isBigNumber: true },
  ],
  thresholds: [{ fieldId: "totalWeldCost", warning: 5000, critical: 15000, direction: "higher_is_bad", warningMessage: "Kaynak maliyeti > $5K — proses optimizasyonu değerlendirilmeli.", criticalMessage: "Kaynak maliyeti > $15K — yöntem değişikliği gerekebilir." }],
  formulaPipeline: [
    { formulaId: "measurement.weld_area", inputMap: { leg: "leg" }, outputId: "weldArea" },
    { formulaId: "measurement.weld_volume", inputMap: { weldArea: "weldArea", weldLength: "weldLength" }, outputId: "weldVolume" },
    { formulaId: "measurement.weld_deposited_weight", inputMap: { weldVolume: "weldVolume", density: "density" }, outputId: "depositedWeight" },
    { formulaId: "measurement.weld_electrode_weight", inputMap: { depositedWeight: "depositedWeight", depEff: "depEff" }, outputId: "electrodeWeight" },
    { formulaId: "cost.weld_filler_cost", inputMap: { electrodeWeight: "electrodeWeight", pricePerKg: "pricePerKg" }, outputId: "fillerCost" },
    { formulaId: "cost.weld_gas_cost", inputMap: { gasFlowRate: "gasFlowRate", arcTime: "arcTime", gasPrice: "gasPrice" }, outputId: "gasCost" },
    { formulaId: "cost.weld_power_cost", inputMap: { voltage: "voltage", current: "current", arcTime: "arcTime", machineEff: "machineEff", elecRate: "elecRate" }, outputId: "powerCost" },
    { formulaId: "cost.weld_total_cost", inputMap: { fillerCost: "fillerCost", gasCost: "gasCost", powerCost: "powerCost", arcTime: "arcTime", depRate: "depRate", laborRate: "laborRate" }, outputId: "totalWeldCost" },
  ],
  reportTemplate: { title: "Kaynak Hacim ve Maliyet Raporu", sections: ["executive_summary", "loss_breakdown", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.1, volatilityPercent: 10, targetMarginPercent: 15, assumptionNotes: ["Kesit = Leg²/2. Hacim = Alan × Uzunluk.", "Biriktirme = Hacim × Yoğunluk.", "Enerji maliyeti = V×I×t / (1000×Verim) × Tarife."] },
};
