import type { PremiumCalculatorSchema } from "@/lib/premium-schema/premium-calculator-schema";
export const WELD_COST_ANALYSIS_SCHEMA: PremiumCalculatorSchema = {
  id: "weld-cost-analysis-analyzer", legacyPaidSlug: "weld-cost-analysis-analyzer",
  name: "Kaynak Maliyeti Detay Analizi", name_i18n: {"en":"Kaynak Maliyeti Detay Analizi","tr":"Kaynak Maliyeti Detay Analizi"}, sectorSlug: "cnc-manufacturing", category: "cost",
  painStatement: "Kaynak maliyetinin metraj bazlı analizi yapılmazsa, birim fiyat ve proses verimliliği izlenemez.", painStatement_i18n: {"en":"Kaynak maliyetinin metraj bazlı analizi yapılmazsa, birim fiyat ve proses verimliliği izlenemez.","tr":"Kaynak maliyetinin metraj bazlı analizi yapılmazsa, birim fiyat ve proses verimliliği izlenemez."},
  inputs: [
    { id: "weldLength", label: "Toplam Kaynak Metresi", label_i18n: {"en":"Toplam Kaynak Metresi","tr":"Toplam Kaynak Metresi"}, type: "number", unit: "m", required: true, smartDefault: 100, validation: { min: 1 }, helper: "", expertMeaning: "Total weld meters", expertMeaning_i18n: {"en":"Total weld meters","tr":"Total weld meters"} },
    { id: "totalShiftTime", label: "Vardiya Süresi", label_i18n: {"en":"Vardiya Süresi","tr":"Vardiya Süresi"}, type: "number", unit: "saat", required: false, smartDefault: 8, validation: { min: 1 }, helper: "", expertMeaning: "Shift duration", expertMeaning_i18n: {"en":"Shift duration","tr":"Shift duration"} },
    { id: "travelSpeed", label: "İlerleme Hızı", label_i18n: {"en":"İlerleme Hızı","tr":"İlerleme Hızı"}, type: "number", unit: "cm/dk", required: true, smartDefault: 30, validation: { min: 0.1 }, helper: "", expertMeaning: "Travel speed", expertMeaning_i18n: {"en":"Travel speed","tr":"Travel speed"} },
    { id: "arcTime", label: "Ark Süresi", label_i18n: {"en":"Ark Süresi","tr":"Ark Süresi"}, type: "number", unit: "saat", required: true, smartDefault: 6, validation: { min: 0.1 }, helper: "", expertMeaning: "Arc-on time", expertMeaning_i18n: {"en":"Arc-on time","tr":"Arc-on time"} },
    { id: "laborRate", label: "İşçilik Saat Ücreti", label_i18n: {"en":"İşçilik Saat Ücreti","tr":"İşçilik Saat Ücreti"}, type: "number", unit: "USD/saat", required: true, smartDefault: 35, validation: { min: 0 }, helper: "", expertMeaning: "Labor rate", expertMeaning_i18n: {"en":"Labor rate","tr":"Labor rate"} },
    { id: "overheadRate", label: "Genel Gider", label_i18n: {"en":"Genel Gider","tr":"Genel Gider"}, type: "number", unit: "USD/saat", required: false, smartDefault: 15, validation: { min: 0 }, helper: "", expertMeaning: "Overhead rate", expertMeaning_i18n: {"en":"Overhead rate","tr":"Overhead rate"} },
    { id: "fillerCost", label: "Dolgu Maliyeti", label_i18n: {"en":"Dolgu Maliyeti","tr":"Dolgu Maliyeti"}, type: "number", unit: "USD", required: true, smartDefault: 200, validation: { min: 0 }, helper: "", expertMeaning: "Total filler cost", expertMeaning_i18n: {"en":"Total filler cost","tr":"Total filler cost"} },
    { id: "gasCost", label: "Gaz Maliyeti", label_i18n: {"en":"Gaz Maliyeti","tr":"Gaz Maliyeti"}, type: "number", unit: "USD", required: false, smartDefault: 80, validation: { min: 0 }, helper: "", expertMeaning: "Gas cost", expertMeaning_i18n: {"en":"Gas cost","tr":"Gas cost"} },
    { id: "powerCost", label: "Enerji Maliyeti", label_i18n: {"en":"Enerji Maliyeti","tr":"Enerji Maliyeti"}, type: "number", unit: "USD", required: false, smartDefault: 50, validation: { min: 0 }, helper: "", expertMeaning: "Power cost", expertMeaning_i18n: {"en":"Power cost","tr":"Power cost"} },
    { id: "depositedWeight", label: "Biriktirilen Ağırlık", label_i18n: {"en":"Biriktirilen Ağırlık","tr":"Biriktirilen Ağırlık"}, type: "number", unit: "kg", required: false, smartDefault: 15, validation: { min: 0 }, helper: "", expertMeaning: "Deposited weld metal", expertMeaning_i18n: {"en":"Deposited weld metal","tr":"Deposited weld metal"} },
  ],
  outputs: [
    { id: "opFactor", label: "Çalışma Faktörü", label_i18n: {"en":"Çalışma Faktörü","tr":"Çalışma Faktörü"}, unit: "", format: "percentage" },
    { id: "depositionRate", label: "Biriktirme Hızı", label_i18n: {"en":"Biriktirme Hızı","tr":"Biriktirme Hızı"}, unit: "kg/saat", format: "number" },
    { id: "jointCost", label: "Toplam Birleştirme Maliyeti", label_i18n: {"en":"Toplam Birleştirme Maliyeti","tr":"Toplam Birleştirme Maliyeti"}, unit: "USD", format: "currency", isBigNumber: true },
    { id: "costPerMeter", label: "Metre Başına Maliyet", label_i18n: {"en":"Metre Başına Maliyet","tr":"Metre Başına Maliyet"}, unit: "USD/m", format: "currency" },
    { id: "consumablePct", label: "Sarf Malzeme Oranı", label_i18n: {"en":"Sarf Malzeme Oranı","tr":"Sarf Malzeme Oranı"}, unit: "%", format: "percentage" },
  ],
  thresholds: [{ fieldId: "costPerMeter", warning: 50, critical: 100, direction: "higher_is_bad", warningMessage: "m² maliyet > $50 — proses verimliliği düşük.", warningMessage_i18n: {"en":"m² maliyet > $50 — proses verimliliği düşük.","tr":"m² maliyet > $50 — proses verimliliği düşük."}, criticalMessage: "m² maliyet > $100 — kaynak yöntemi değişmeli.", criticalMessage_i18n: {"en":"m² maliyet > $100 — kaynak yöntemi değişmeli.","tr":"m² maliyet > $100 — kaynak yöntemi değişmeli."} }],
  formulaPipeline: [
    { formulaId: "measurement.weld_op_factor", inputMap: { arcTime: "arcTime", totalShiftTime: "totalShiftTime" }, outputId: "opFactor" },
    { formulaId: "measurement.weld_deposition_rate", inputMap: { depositedWeight: "depositedWeight", arcTime: "arcTime" }, outputId: "depositionRate" },
    { formulaId: "cost.weld_joint_cost", inputMap: { weldLength: "weldLength", travelSpeed: "travelSpeed", laborRate: "laborRate", overheadRate: "overheadRate", opFactor: "opFactor", fillerCost: "fillerCost", gasCost: "gasCost", powerCost: "powerCost" }, outputId: "jointCost" },
    { formulaId: "cost.weld_cost_per_meter", inputMap: { jointCost: "jointCost", weldLength: "weldLength" }, outputId: "costPerMeter" },
    { formulaId: "cost.weld_consumable_pct", inputMap: { fillerCost: "fillerCost", jointCost: "jointCost" }, outputId: "consumablePct" },
  ],
  reportTemplate: { title: "Kaynak Maliyet Analizi", title_i18n: {"en":"Kaynak Maliyet Analizi","tr":"Kaynak Maliyet Analizi"}, sections: ["executive_summary", "loss_breakdown", "thresholds", "action_plan", "assumptions"], exportFormats: ["pdf", "excel"] },
  assumptions: { hiddenLossMultiplier: 1.1, volatilityPercent: 10, targetMarginPercent: 15, assumptionNotes: ["Çalışma faktörü = Ark süresi / Vardiya süresi.", "Toplam maliyet = (Uzunluk/Hız)×(İşçilik+Overhead)/Faktör + Sarf.", "Sarf oranı = Dolgu / Toplam."],assumptionNotes_i18n:[{"en":"Çalışma faktörü = Ark süresi / Vardiya süresi.","tr":"Çalışma faktörü = Ark süresi / Vardiya süresi."},{"en":"Toplam maliyet = (Uzunluk/Hız)×(İşçilik+Overhead)/Faktör + Sarf.","tr":"Toplam maliyet = (Uzunluk/Hız)×(İşçilik+Overhead)/Faktör + Sarf."},{"en":"Sarf oranı = Dolgu / Toplam.","tr":"Sarf oranı = Dolgu / Toplam."}] },
};
