import type { ToolDef } from "./359-types";
const c = "technology-ai-cloud-cyber"; const s = "Bilişim, Biyomedikal ve Maden";
const ld: string[] = ["Low SLA indicates service reliability issue.", "High latency degrades user experience."];
const sa: string[] = ["Monitor system performance regularly.", "Implement redundancy for critical infrastructure."];

export const section21: ToolDef[] = [
  { slug: "veri-yedekleme-sure-hesaplama", dt: "Sıkıştırma ve ağ hızına göre veri yedekleme için gereken süreyi hesaplar.", de: "Calculate backup time based on data size, compression, and network speed.", cat: c, st: s, ld, sa,
    inputs: [{ id: "veriBoyutu", lt: "Veri Boyutu (TB)", le: "Data Size (TB)", u: "TB", d: 5, ct: "Yedeklenecek ham veri boyutu.", ce: "Raw backup data size." },{ id: "sikistirmaOrani", lt: "Sıkıştırma Oranı", le: "Compression Ratio", u: "", d: 3, ct: "Sıkıştırma faktörü (2:1=2).", ce: "Compression factor." },{ id: "agHizi", lt: "Ağ Hızı (Gbps)", le: "Network Speed (Gbps)", u: "Gbps", d: 1, ct: "Veri aktarım hızı.", ce: "Data transfer speed." }],
    f: { hedefBoyut: "veriBoyutu / Math.max(0.0001, sikistirmaOrani)", sonuc: "((veriBoyutu / Math.max(0.0001, sikistirmaOrani)) * 8192) / Math.max(0.0001, agHizi)" }, op: "sonuc", ou: "s", ok: ["hedefBoyut", "sonuc"], ol: { hedefBoyut: "Sıkıştırılmış Boyut (TB)", sonuc: "Aktarım Süresi (s)" } },
  { slug: "rsa-sifreleme-guvenlik-hesaplama", dt: "RSA anahtar uzunluğunun sağladığı teorik simetrik şifreleme eşdeğerini hesaplar.", de: "Estimate symmetric key equivalent strength for RSA key size.", cat: c, st: s, ld, sa,
    inputs: [{ id: "rsaAnahtarUzunlugu", lt: "RSA Anahtar Uzunluğu (bit)", le: "RSA Key Length (bits)", u: "bits", d: 2048, ct: "RSA anahtar boyu.", ce: "RSA key size." }],
    f: { sonuc: "rsaAnahtarUzunlugu >= 15360 ? 256 : rsaAnahtarUzunlugu >= 7680 ? 192 : rsaAnahtarUzunlugu >= 3072 ? 128 : rsaAnahtarUzunlugu >= 2048 ? 112 : rsaAnahtarUzunlugu >= 1024 ? 80 : 56" }, op: "sonuc", ou: "bits", ok: ["sonuc"], ol: { sonuc: "Simetrik Eşdeğer" } },
  { slug: "api-gecikme-sla-hesaplama", dt: "API servisinin yanıt hızını (ortalama gecikme) ve başarıyla karşılama yüzdesini (SLA) hesaplar.", de: "Calculate API average latency and SLA success rate.", cat: c, st: s, ld, sa,
    inputs: [{ id: "toplamIstek", lt: "Toplam İstek Sayısı", le: "Total Requests", u: "requests", d: 10000, ct: "Toplam API çağrısı.", ce: "Total API calls." },{ id: "hataliIstek", lt: "Hatalı İstek Sayısı", le: "Failed Requests", u: "requests", d: 50, ct: "Başarısız istek adedi.", ce: "Number of failed requests." },{ id: "toplamGecikme", lt: "Toplam Gecikme (ms)", le: "Total Latency (ms)", u: "ms", d: 250000, ct: "Tüm isteklerin süre toplamı.", ce: "Sum of all request durations." }],
    f: { sonuc: "toplamGecikme / Math.max(1, toplamIstek)", sla: "((toplamIstek - hataliIstek) / Math.max(1, toplamIstek)) * 100" }, op: "sonuc", ou: "ms", ok: ["sonuc", "sla"], ol: { sonuc: "Ortalama Gecikme", sla: "SLA (%)" } },
  { slug: "ilac-yarilanma-omru-hesaplama", dt: "Kararlı durumda ilacın vücutta birikim faktörünü yarılanma ömrüne göre hesaplar.", de: "Calculate drug accumulation factor based on half-life and dosing interval.", cat: c, st: s, ld, sa,
    inputs: [{ id: "yarilanmaOmru", lt: "Yarılanma Ömrü (Saat)", le: "Half-Life (Hours)", u: "h", d: 12, ct: "İlacın vücuttan yarılanma süresi.", ce: "Drug elimination half-life." },{ id: "dozAraligi", lt: "Doz Aralığı (Saat)", le: "Dosing Interval (Hours)", u: "h", d: 8, ct: "İlaç alma sıklığı.", ce: "Time between doses." }],
    f: { k: "0.693 / Math.max(0.0001, yarilanmaOmru)", sonuc: "1 / Math.max(0.0001, (1 - Math.exp(-(0.693 / Math.max(0.0001, yarilanmaOmru)) * dozAraligi)))" }, op: "sonuc", ou: "factor", ok: ["sonuc"], ol: { sonuc: "Birikim Faktörü" } },
  { slug: "radyasyon-dozu-etkin-hesaplama", dt: "Biyolojik hasar riskini yansıtan toplam eşdeğer radyasyon dozunu (mSv) hesaplar.", de: "Calculate effective radiation dose in mSv considering tissue and radiation weighting.", cat: c, st: s, ld, sa,
    inputs: [{ id: "sozurulenDoz", lt: "Soğurulan Doz (mGy)", le: "Absorbed Dose (mGy)", u: "mGy", d: 10, ct: "Doku tarafından emilen enerji.", ce: "Energy absorbed by tissue." },{ id: "dokuAgirlikFaktoru", lt: "Doku Ağırlık Faktörü", le: "Tissue Weighting Factor", u: "", d: 0.12, ct: "Dokunun radyasyon hassasiyeti.", ce: "Tissue radiation sensitivity." },{ id: "radyasyonTuruFaktoru", lt: "Radyasyon Türü Faktörü", le: "Radiation Type Factor", u: "", d: 1, ct: "Radyasyon türünün biyolojik etkinliği.", ce: "Radiation type effectiveness." }],
    f: { sonuc: "sozurulenDoz * dokuAgirlikFaktoru * radyasyonTuruFaktoru" }, op: "sonuc", ou: "mSv", ok: ["sonuc"], ol: { sonuc: "Etkin Doz (mSv)" } },
  { slug: "biyolojik-sinyal-ornekleme-hesaplama", dt: "Sinyalde örtüşmeyi (aliasing) önleyen minimum ADC örnekleme hızını Nyquist teoremi ile hesaplar.", de: "Calculate minimum sampling rate for biological signals (Nyquist theorem).", cat: c, st: s, ld, sa,
    inputs: [{ id: "maksSinyalFrekansi", lt: "Maks. Sinyal Frekansı (Hz)", le: "Max Signal Frequency (Hz)", u: "Hz", d: 100, ct: "Sinyaldeki en yüksek frekans bileşeni.", ce: "Highest frequency component." }],
    f: { sonuc: "2 * maksSinyalFrekansi" }, op: "sonuc", ou: "Hz", ok: ["sonuc"], ol: { sonuc: "Min. Örnekleme Hızı" } },
  { slug: "maden-rezerv-hacim-hesaplama", dt: "Sahadaki net cevher ve saf metal ağırlığını (rezerv hacim) hesaplar.", de: "Calculate ore tonnage and metal content in a mining block.", cat: c, st: s, ld, sa,
    inputs: [{ id: "blokHacim", lt: "Cevher Blok Hacmi (m³)", le: "Ore Block Volume (m³)", u: "m3", d: 50000, ct: "Cevher kütlesinin hacmi.", ce: "Ore body volume." },{ id: "cevherYogunlugu", lt: "Cevher Yoğunluğu (ton/m³)", le: "Ore Density (ton/m³)", u: "ton/m3", d: 2.7, ct: "Cevherin yoğunluğu.", ce: "Ore density." },{ id: "tenor", lt: "Tenör (%)", le: "Grade (%)", u: "%", d: 1.5, ct: "Cevherin metal içeriği.", ce: "Metal grade in ore." }],
    f: { tonaj: "blokHacim * cevherYogunlugu", sonuc: "(blokHacim * cevherYogunlugu) * (tenor / 100)" }, op: "sonuc", ou: "tons", ok: ["tonaj", "sonuc"], ol: { tonaj: "Toplam Cevher (ton)", sonuc: "Metal Miktarı (ton)" } },
  { slug: "sondaj-kuyusu-basinc-hesaplama", dt: "Kuyu tabanındaki çamur sütununun oluşturduğu hidrostatik basıncı hesaplar.", de: "Calculate hydrostatic pressure of mud column at well depth.", cat: c, st: s, ld, sa,
    inputs: [{ id: "dikeyDerinlik", lt: "Dikey Derinlik (m)", le: "Vertical Depth (m)", u: "m", d: 3000, ct: "Kuyunun dikey boyu.", ce: "True vertical depth." },{ id: "camurYogunlugu", lt: "Sondaj Çamuru Yoğunluğu (kg/m³)", le: "Mud Density (kg/m³)", u: "kg/m3", d: 1500, ct: "Çamur yoğunluğu.", ce: "Mud weight." }],
    f: { sonuc: "(camurYogunlugu * 9.81 * dikeyDerinlik) / 1000000" }, op: "sonuc", ou: "MPa", ok: ["sonuc"], ol: { sonuc: "Hidrostatik Basınç" } },
  { slug: "deprem-buyuklugu-pga-hesaplama", dt: "Belirli bir deprem büyüklüğü ve mesafe için yüzeyde beklenen maksimum yer ivmesini (PGA) hesaplar.", de: "Estimate peak ground acceleration (PGA) from earthquake magnitude and distance.", cat: c, st: s, ld, sa,
    inputs: [{ id: "momentMagnitudu", lt: "Deprem Büyüklüğü (Mw)", le: "Moment Magnitude (Mw)", u: "Mw", d: 7, mn: 0, mx: 10, ct: "Depremin moment magnitüdü.", ce: "Earthquake moment magnitude." },{ id: "mesafe", lt: "Deprem Merkezine Uzaklık (km)", le: "Distance from Epicenter (km)", u: "km", d: 50, ct: "Gözlem noktasının deprem merkezine uzaklığı.", ce: "Distance from epicenter." },{ id: "zeminKatsayisi", lt: "Zemin Katsayısı", le: "Site Coefficient", u: "", d: 1, ct: "Zemin türü katsayısı (sert=0.8, yumuşak=1.5).", ce: "Soil amplification factor." }],
    f: { sonuc: "1 * Math.exp(0.5 * 7 - 2.0 * Math.log(Math.max(1, 50 + 10)))" }, op: "sonuc", ou: "g", ok: ["sonuc"], ol: { sonuc: "PGA (g)" } },
];
