import type { ToolDef } from "./359-types";
const c = "mathematics-statistics"; const s = "Veri ve İstatistik";
const ld: string[] = []; const sa: string[] = ["Verify statistical assumptions before making decisions.", "Use larger sample sizes for better accuracy."];

export const section9: ToolDef[] = [
  { slug: "mean-median-mode-calculator", dt: "Veri setinin merkezi eğilim ölçülerini (ortalama, medyan, mod) hesaplar.", de: "Calculate mean, median, and mode of a data set.", cat: c, st: s, ld, sa,
    inputs: [{ id: "deger1", lt: "Değer 1", le: "Value 1", u: "", d: 10, ct: "Veri setinin birinci elemanı.", ce: "First data value." },{ id: "deger2", lt: "Değer 2", le: "Value 2", u: "", d: 20, ct: "İkinci eleman.", ce: "Second value." },{ id: "deger3", lt: "Değer 3", le: "Value 3", u: "", d: 30, ct: "Üçüncü eleman.", ce: "Third value." },{ id: "deger4", lt: "Değer 4", le: "Value 4", u: "", d: 40, ct: "Dördüncü eleman.", ce: "Fourth value." },{ id: "deger5", lt: "Değer 5", le: "Value 5", u: "", d: 50, ct: "Beşinci eleman.", ce: "Fifth value." }],
    f: { ortalama: "(deger1 + deger2 + deger3 + deger4 + deger5) / 5", sonuc: "(deger1 + deger2 + deger3 + deger4 + deger5) / 5" }, op: "sonuc", ou: "number", ok: ["sonuc"], ol: { sonuc: "Ortalama" } },
  { slug: "standard-deviation-variance-calculator", dt: "Verilerin ortalamaya göre yayılım derecesini (standart sapma ve varyans) hesaplar.", de: "Calculate standard deviation and variance of a data set.", cat: c, st: s, ld, sa,
    inputs: [{ id: "deger1", lt: "Değer 1", le: "Value 1", u: "", d: 10, ct: "Veri seti elemanı.", ce: "Data value." },{ id: "deger2", lt: "Değer 2", le: "Value 2", u: "", d: 20, ct: "Veri seti elemanı.", ce: "Data value." },{ id: "deger3", lt: "Değer 3", le: "Value 3", u: "", d: 30, ct: "Veri seti elemanı.", ce: "Data value." },{ id: "deger4", lt: "Değer 4", le: "Value 4", u: "", d: 40, ct: "Veri seti elemanı.", ce: "Data value." },{ id: "deger5", lt: "Değer 5", le: "Value 5", u: "", d: 50, ct: "Veri seti elemanı.", ce: "Data value." }],
    f: { ort: "(deger1 + deger2 + deger3 + deger4 + deger5) / 5", sonuc: "Math.sqrt((Math.pow(deger1 - (deger1+deger2+deger3+deger4+deger5)/5, 2) + Math.pow(deger2 - (deger1+deger2+deger3+deger4+deger5)/5, 2) + Math.pow(deger3 - (deger1+deger2+deger3+deger4+deger5)/5, 2) + Math.pow(deger4 - (deger1+deger2+deger3+deger4+deger5)/5, 2) + Math.pow(deger5 - (deger1+deger2+deger3+deger4+deger5)/5, 2)) / 4)" }, op: "sonuc", ou: "number", ok: ["sonuc"], ol: { sonuc: "Standart Sapma" } },
  { slug: "confidence-interval-calculator", dt: "Popülasyon parametresinin bulunma olasılığı yüksek aralığı (güven aralığı) hesaplar.", de: "Calculate confidence interval for population parameter.", cat: c, st: s, ld, sa,
    inputs: [{ id: "ortalama", lt: "Örneklem Ortalaması", le: "Sample Mean", u: "", d: 100, ct: "Örneklemin ortalaması.", ce: "Sample average." },{ id: "stdHata", lt: "Standart Hata", le: "Standard Error", u: "", d: 5, ct: "Ortalamanın standart hatası.", ce: "Standard error of the mean." },{ id: "guvenSeviyesi", lt: "Güven Seviyesi (%)", le: "Confidence Level (%)", u: "%", d: 95, mn: 1, mx: 99.9, ct: "İstatistiksel güven düzeyi.", ce: "Statistical confidence level." }],
    f: { Z: "guvenSeviyesi >= 99 ? 2.576 : guvenSeviyesi >= 95 ? 1.96 : 1.645", alt: "ortalama - (guvenSeviyesi >= 99 ? 2.576 : guvenSeviyesi >= 95 ? 1.96 : 1.645) * stdHata", sonuc: "ortalama + (guvenSeviyesi >= 99 ? 2.576 : guvenSeviyesi >= 95 ? 1.96 : 1.645) * stdHata" },
    op: "sonuc", ou: "number", ok: ["alt", "sonuc"], ol: { alt: "Alt Sınır", sonuc: "Üst Sınır" } },
  { slug: "minimum-sample-size-calculator", dt: "İstatistiksel anlamlılık için gereken minimum örneklem sayısını hesaplar.", de: "Calculate minimum sample size for statistical significance.", cat: c, st: s, ld, sa,
    inputs: [{ id: "Z", lt: "Z Değeri", le: "Z Value", u: "", d: 1.96, ct: "Güven seviyesine karşılık Z (1.96=%95).", ce: "Z-score for confidence level." },{ id: "stdSapma", lt: "Tahmini Standart Sapma", le: "Estimated Std Dev", u: "", d: 10, ct: "Popülasyon standart sapması.", ce: "Population standard deviation." },{ id: "hataPayi", lt: "Kabul Edilebilir Hata Payı", le: "Margin of Error", u: "", d: 2, ct: "İzin verilen maksimum hata.", ce: "Maximum allowable error." }],
    f: { sonuc: "Math.ceil(Math.pow((Z * stdSapma / Math.max(0.0001, hataPayi)), 2))" }, op: "sonuc", ou: "samples", ok: ["sonuc"], ol: { sonuc: "Gereken Minimum Örneklem" } },
  { slug: "correlation-regression-calculator", dt: "İki değişken arası ilişki gücünü (korelasyon) ve doğrusal regresyon eğimini hesaplar.", de: "Calculate correlation coefficient and linear regression slope.", cat: c, st: s, ld, sa,
    inputs: [{ id: "x1", lt: "X1", le: "X1", u: "", d: 1, ct: "X değişkeni.", ce: "X variable." },{ id: "y1", lt: "Y1", le: "Y1", u: "", d: 2, ct: "Y değişkeni.", ce: "Y variable." },{ id: "x2", lt: "X2", le: "X2", u: "", d: 2, ct: "X değişkeni.", ce: "X variable." },{ id: "y2", lt: "Y2", le: "Y2", u: "", d: 4, ct: "Y değişkeni.", ce: "Y variable." },{ id: "x3", lt: "X3", le: "X3", u: "", d: 3, ct: "X değişkeni.", ce: "X variable." },{ id: "y3", lt: "Y3", le: "Y3", u: "", d: 6, ct: "Y değişkeni.", ce: "Y variable." }],
    f: { n: "3", sx: "x1+x2+x3", sy: "y1+y2+y3", sxy: "x1*y1+x2*y2+x3*y3", sxx: "x1*x1+x2*x2+x3*x3", syy: "y1*y1+y2*y2+y3*y3", sonuc: "(3*(x1*y1+x2*y2+x3*y3)-(x1+x2+x3)*(y1+y2+y3))/Math.sqrt(Math.max(0.0001,(3*(x1*x1+x2*x2+x3*x3)-(x1+x2+x3)*(x1+x2+x3))*(3*(y1*y1+y2*y2+y3*y3)-(y1+y2+y3)*(y1+y2+y3))))" },
    op: "sonuc", ou: "r-value", ok: ["sonuc"], ol: { sonuc: "Korelasyon (r)" } },
  { slug: "anova-f-statistic-calculator", dt: "Grup ortalamaları arası farkın istatistiksel anlamlılığını (ANOVA) hesaplar.", de: "Calculate ANOVA F-statistic for comparing group means.", cat: c, st: s, ld, sa,
    inputs: [{ id: "grup1", lt: "Grup 1 Ortalaması", le: "Group 1 Mean", u: "", d: 100, ct: "Birinci grubun ortalaması.", ce: "Mean of first group." },{ id: "grup2", lt: "Grup 2 Ortalaması", le: "Group 2 Mean", u: "", d: 110, ct: "İkinci grubun ortalaması.", ce: "Mean of second group." },{ id: "grup1N", lt: "Grup 1 Örneklem", le: "Group 1 N", u: "", d: 30, mn: 2, ct: "Birinci grubun örneklem sayısı.", ce: "First group sample size." },{ id: "grup2N", lt: "Grup 2 Örneklem", le: "Group 2 N", u: "", d: 30, mn: 2, ct: "İkinci grubun örneklem sayısı.", ce: "Second group sample size." },{ id: "grup1Varyans", lt: "Grup 1 Varyans", le: "Group 1 Variance", u: "", d: 225, ct: "Birinci grubun varyansı.", ce: "First group variance." },{ id: "grup2Varyans", lt: "Grup 2 Varyans", le: "Group 2 Variance", u: "", d: 225, ct: "İkinci grubun varyansı.", ce: "Second group variance." }],
    f: { grandMean: "(grup1*grup1N+grup2*grup2N)/(grup1N+grup2N)", ssBetween: "grup1N*(grup1-grandMean)^2+grup2N*(grup2-grandMean)^2", ssWithin: "(grup1N-1)*grup1Varyans+(grup2N-1)*grup2Varyans", msBetween: "(grup1N*(grup1-grandMean)^2+grup2N*(grup2-grandMean)^2)/(2-1)", msWithin: "((grup1N-1)*grup1Varyans+(grup2N-1)*grup2Varyans)/(grup1N+grup2N-2)", sonuc: "msBetween/msWithin" },
    op: "sonuc", ou: "F-value", ok: ["sonuc"], ol: { sonuc: "F-İstatistiği" } },
];
