import type { ToolDef } from "./359-types";
const c = "sustainability-resource-esg"; const s = "Çevre ve Sürdürülebilirlik";
const ld: string[] = ["High environmental score may reduce operational costs.", "Low ESG score may increase capital costs."];
const sa: string[] = ["Set improvement targets for each ESG pillar.", "Consider carbon offset programs for residual emissions."];

export const section14: ToolDef[] = [
  { slug: "breeam-leed-puan-hesaplama", dt: "Binanın sürdürülebilirlik sertifikası (BREEAM/LEED) tahmini puanını hesaplar.", de: "Estimate BREEAM/LEED sustainability certification score.", cat: c, st: s, ld, sa,
    inputs: [{ id: "enerji", lt: "Enerji Kriter Puanı (0-100)", le: "Energy Score (0-100)", u: "", d: 70, mn: 0, mx: 100, ct: "Enerji verimliliği puanı.", ce: "Energy efficiency score." },{ id: "su", lt: "Su Kriter Puanı (0-100)", le: "Water Score (0-100)", u: "", d: 60, mn: 0, mx: 100, ct: "Su yönetimi puanı.", ce: "Water management score." },{ id: "malzeme", lt: "Malzeme Kriter Puanı (0-100)", le: "Materials Score (0-100)", u: "", d: 65, mn: 0, mx: 100, ct: "Malzeme seçimi puanı.", ce: "Materials selection score." }],
    f: { sonuc: "(enerji * 0.4) + (su * 0.3) + (malzeme * 0.3)" }, op: "sonuc", ou: "score", ok: ["sonuc"], ol: { sonuc: "Tahmini Sertifika Puanı" } },
  { slug: "karbon-ayak-izi-hesaplama", dt: "Kurumun toplam sera gazı emisyonunu (karbon ayak izi) hesaplar.", de: "Calculate total corporate greenhouse gas emissions (carbon footprint).", cat: c, st: s, ld, sa,
    inputs: [{ id: "yakit", lt: "Yakıt Tüketimi (L)", le: "Fuel Consumption (L)", u: "L", d: 10000, ct: "Yıllık yakıt tüketimi (motorin).", ce: "Annual diesel consumption." },{ id: "elektrik", lt: "Elektrik Tüketimi (kWh)", le: "Electricity (kWh)", u: "kWh", d: 50000, ct: "Yıllık elektrik tüketimi.", ce: "Annual electricity consumption." },{ id: "tedarik", lt: "Tedarik Emisyonu (kgCO₂)", le: "Supply Chain (kgCO₂)", u: "kgCO2", d: 20000, ct: "Satın alınan mal/hizmet kaynaklı emisyon.", ce: "Purchased goods emissions." }],
    f: { scope1: "yakit * 2.31", scope2: "elektrik * 0.45", sonuc: "(yakit * 2.31) + (elektrik * 0.45) + tedarik" }, op: "sonuc", ou: "kgCO2", ok: ["sonuc"], ol: { sonuc: "Toplam Karbon Ayak İzi" } },
  { slug: "esg-skoru-hesaplama", dt: "Kurumun finansal olmayan sürdürülebilirlik notunu (ESG skoru) hesaplar.", de: "Calculate corporate ESG sustainability score (0-100).", cat: c, st: s, ld, sa,
    inputs: [{ id: "cevre", lt: "Çevre Puanı (0-100)", le: "Environmental (0-100)", u: "", d: 75, mn: 0, mx: 100, ct: "Çevresel performans.", ce: "Environmental performance." },{ id: "sosyal", lt: "Sosyal Puan (0-100)", le: "Social (0-100)", u: "", d: 80, mn: 0, mx: 100, ct: "Sosyal sorumluluk.", ce: "Social responsibility." },{ id: "yonetisim", lt: "Yönetişim Puanı (0-100)", le: "Governance (0-100)", u: "", d: 70, mn: 0, mx: 100, ct: "Kurumsal yönetim.", ce: "Corporate governance." }],
    f: { sonuc: "(cevre * 0.4) + (sosyal * 0.3) + (yonetisim * 0.3)" }, op: "sonuc", ou: "score", ok: ["sonuc"], ol: { sonuc: "ESG Skoru" } },
  { slug: "dongusel-ekonomi-hesaplama", dt: "Üretimde kullanılan ikincil hammadde oranını (döngüsel ekonomi oranı) hesaplar.", de: "Calculate circular economy material reuse ratio.", cat: c, st: s, ld, sa,
    inputs: [{ id: "geriKazanilan", lt: "Geri Kazanılan Malzeme (ton)", le: "Recovered Material (tons)", u: "tons", d: 500, ct: "İkincil hammadde miktarı.", ce: "Secondary raw material." },{ id: "toplamGirdi", lt: "Toplam Hammadde Girdisi (ton)", le: "Total Material Input (tons)", u: "tons", d: 2000, ct: "Üretimde kullanılan tüm malzeme.", ce: "All production material input." }],
    f: { sonuc: "(geriKazanilan / Math.max(0.0001, toplamGirdi)) * 100" }, op: "sonuc", ou: "%", ok: ["sonuc"], ol: { sonuc: "Döngüsel Ekonomi Oranı" } },
  { slug: "su-ayak-izi-hesaplama", dt: "Birim ürün başına harcanan tatlı su miktarını (su ayak izi) hesaplar.", de: "Calculate water footprint per unit of production.", cat: c, st: s, ld, sa,
    inputs: [{ id: "uretimHacmi", lt: "Üretim Hacmi (Ton)", le: "Production Volume (Tons)", u: "tons", d: 5000, ct: "Toplam üretim miktarı.", ce: "Total production quantity." },{ id: "tuketilenSu", lt: "Tüketilen Su (m³)", le: "Water Consumed (m³)", u: "m3", d: 15000, ct: "Üretimde kullanılan toplam su.", ce: "Total water used in production." }],
    f: { sonuc: "tuketilenSu / Math.max(0.0001, uretimHacmi)" }, op: "sonuc", ou: "m3/ton", ok: ["sonuc"], ol: { sonuc: "Su Ayak İzi" } },
  { slug: "atik-depolama-saha-hesaplama", dt: "Atığı depolamak için gereken minimum deponi sahası yüzey alanını hesaplar.", de: "Calculate minimum landfill area required for waste storage.", cat: c, st: s, ld, sa,
    inputs: [{ id: "atikHacmi", lt: "Atık Hacmi (m³)", le: "Waste Volume (m³)", u: "m3", d: 50000, ct: "Depolanacak atık hacmi.", ce: "Waste volume to store." },{ id: "sikistirma", lt: "Sıkıştırma Oranı (%)", le: "Compaction Ratio (%)", u: "%", d: 20, ct: "Sıkıştırmayla hacim azalma oranı.", ce: "Volume reduction by compaction." },{ id: "derinlik", lt: "Deponi Derinliği (m)", le: "Landfill Depth (m)", u: "m", d: 10, ct: "Deponi ortalama derinliği.", ce: "Average landfill depth." }],
    f: { sonuc: "(atikHacmi * (1 - sikistirma / 100)) / Math.max(0.0001, derinlik)" }, op: "sonuc", ou: "m2", ok: ["sonuc"], ol: { sonuc: "Gerekli Deponi Alanı" } },
  { slug: "geri-donusum-orani-hesaplama", dt: "Atık yönetimindeki başarı ve kazanım yüzdesini (geri dönüşüm oranı) hesaplar.", de: "Calculate recycling rate as percentage of waste recovered.", cat: c, st: s, ld, sa,
    inputs: [{ id: "geriDonusen", lt: "Geri Dönüştürülen (ton)", le: "Recycled (tons)", u: "tons", d: 300, ct: "Geri kazanılan atık miktarı.", ce: "Amount of waste recovered." },{ id: "toplamAtik", lt: "Toplam Atık (ton)", le: "Total Waste (tons)", u: "tons", d: 1000, ct: "Oluşan toplam atık.", ce: "Total waste generated." }],
    f: { sonuc: "(geriDonusen / Math.max(0.0001, toplamAtik)) * 100" }, op: "sonuc", ou: "%", ok: ["sonuc"], ol: { sonuc: "Geri Dönüşüm Oranı" } },
  { slug: "havza-yonetimi-akis-hesaplama", dt: "Yağış sonrası havzadan çıkacak yüzey akış suyu miktarını hesaplar.", de: "Calculate surface runoff volume from a watershed after rainfall.", cat: c, st: s, ld, sa,
    inputs: [{ id: "havzaAlani", lt: "Havza Alanı (km²)", le: "Watershed Area (km²)", u: "km2", d: 100, ct: "Toplama havzası alanı.", ce: "Catchment area." },{ id: "yagis", lt: "Yağış Miktarı (mm)", le: "Rainfall (mm)", u: "mm", d: 50, ct: "Birim yağış yüksekliği.", ce: "Single rainfall depth." },{ id: "akisKatsayisi", lt: "Akış Katsayısı (0-1)", le: "Runoff Coefficient (0-1)", u: "", d: 0.3, ct: "Zeminin geçirgenliğine bağlı katsayı.", ce: "Surface permeability coefficient." }],
    f: { sonuc: "havzaAlani * 1000000 * (yagis / 1000) * akisKatsayisi" }, op: "sonuc", ou: "m3", ok: ["sonuc"], ol: { sonuc: "Toplam Yüzey Akış Hacmi" } },
  { slug: "gri-su-geri-kazanim-hesaplama", dt: "Gri su sisteminin yıllık net finansal kazancını hesaplar.", de: "Calculate annual net financial savings from greywater system.", cat: c, st: s, ld, sa,
    inputs: [{ id: "griSuHacmi", lt: "Günlük Gri Su Hacmi (m³/gün)", le: "Daily Greywater (m³/day)", u: "m3/day", d: 5, ct: "Günlük oluşan gri su.", ce: "Daily greywater volume." },{ id: "aritmaMaliyet", lt: "Arıtma Maliyeti (TL/m³)", le: "Treatment Cost (TL/m³)", u: "TL/m3", d: 3, ct: "Gri su arıtma birim maliyeti.", ce: "Greywater treatment unit cost." },{ id: "sebekeFiyat", lt: "Şebeke Su Fiyatı (TL/m³)", le: "Mains Water Price (TL/m³)", u: "TL/m3", d: 15, ct: "Şebekeden alınan su birim fiyatı.", ce: "Municipal water unit price." }],
    f: { sonuc: "griSuHacmi * (sebekeFiyat - aritmaMaliyet) * 365" }, op: "sonuc", ou: "TL/year", ok: ["sonuc"], ol: { sonuc: "Yıllık Net Tasarruf" } },
];
