import type { ToolDef } from "./359-types";
const c = "health-fitness-daily-life"; const s = "Sağlık ve Fitness";
const ld: string[] = []; const sa: string[] = ["Consult a healthcare professional before starting any diet or exercise program.", "Individual results may vary."];

export const section10: ToolDef[] = [
  { slug: "bmi-obesity-risk-calculator", dt: "Vücut kitle endeksini (BMI) ve obezite risk sınıflandırmasını hesaplar.", de: "Calculate body mass index (BMI) and obesity risk classification.", cat: c, st: s, ld, sa,
    inputs: [{ id: "agirlik", lt: "Ağırlık (kg)", le: "Weight (kg)", u: "kg", d: 75, mn: 20, mx: 300, ct: "Vücut ağırlığı.", ce: "Body weight." },{ id: "boy", lt: "Boy (m)", le: "Height (m)", u: "m", d: 1.75, mn: 0.5, mx: 2.5, ct: "Boy uzunluğu.", ce: "Body height." }],
    f: { sonuc: "agirlik / Math.max(0.0001, (boy * boy))" }, op: "sonuc", ou: "kg/m2", ok: ["sonuc"], ol: { sonuc: "VKİ (BMI)" } },
  { slug: "body-fat-percentage-navy-method-calculator", dt: "Vücuttaki yağ kütlesinin toplam ağırlığa oranını (vücut yağ yüzdesi) hesaplar.", de: "Calculate body fat percentage using the Navy method.", cat: c, st: s, ld, sa,
    inputs: [{ id: "boy", lt: "Boy (cm)", le: "Height (cm)", u: "cm", d: 175, ct: "Boy uzunluğu.", ce: "Height." },{ id: "bel", lt: "Bel Çevresi (cm)", le: "Waist (cm)", u: "cm", d: 85, ct: "En dar bel çevresi.", ce: "Narrowest waist circumference." },{ id: "boyun", lt: "Boyun Çevresi (cm)", le: "Neck (cm)", u: "cm", d: 38, ct: "Boyun çevresi.", ce: "Neck circumference." }],
    f: { sonuc: "495 / Math.max(0.0001, (1.0324 - 0.19077 * Math.log(Math.max(1, bel - boyun)) / Math.log(10) + 0.15456 * Math.log(Math.max(1, boy)) / Math.log(10))) - 450" }, op: "sonuc", ou: "%", ok: ["sonuc"], ol: { sonuc: "Vücut Yağ Yüzdesi" } },
  { slug: "basal-metabolic-rate-mifflin-st-jeor-calculator", dt: "Vücudun dinlenme halindeyken yaktığı minimum günlük enerjiyi (BMR) hesaplar.", de: "Calculate basal metabolic rate (BMR) using Mifflin-St Jeor formula.", cat: c, st: s, ld, sa,
    inputs: [{ id: "agirlik", lt: "Ağırlık (kg)", le: "Weight (kg)", u: "kg", d: 75, ct: "Vücut ağırlığı.", ce: "Body weight." },{ id: "boy", lt: "Boy (cm)", le: "Height (cm)", u: "cm", d: 175, ct: "Boy uzunluğu.", ce: "Height." },{ id: "yas", lt: "Yaş", le: "Age", u: "years", d: 30, mn: 10, mx: 100, ct: "Kişinin yaşı.", ce: "Person's age." },{ id: "cinsiyet", lt: "Cinsiyet (1=Erkek, 0=Kadın)", le: "Sex (1=Male, 0=Female)", u: "", d: 1, ct: "Cinsiyet.", ce: "Gender." }],
    f: { sonuc: "cinsiyet === 1 ? (10 * agirlik + 6.25 * boy - 5 * yas + 5) : (10 * agirlik + 6.25 * boy - 5 * yas - 161)" }, op: "sonuc", ou: "kcal", ok: ["sonuc"], ol: { sonuc: "BMR (Bazal Metabolizma Hızı)" } },
  { slug: "total-daily-energy-expenditure-calculator", dt: "Mevcut kiloyu korumak için günlük alınması gereken toplam kaloriyi (TDEE) hesaplar.", de: "Calculate total daily energy expenditure (TDEE) to maintain weight.", cat: c, st: s, ld, sa,
    inputs: [{ id: "bmr", lt: "BMR (kcal)", le: "BMR (kcal)", u: "kcal", d: 1650, ct: "Bazal metabolizma hızı.", ce: "Basal metabolic rate." },{ id: "aktiviteSeviyesi", lt: "Aktivite Seviyesi (1.2-2.0)", le: "Activity Level (1.2-2.0)", u: "", d: 1.55, mn: 1.2, mx: 2.0, ct: "Fiziksel aktivite çarpanı (1.2=hareketsiz, 2.0=çok aktif).", ce: "Physical activity multiplier." }],
    f: { sonuc: "bmr * aktiviteSeviyesi" }, op: "sonuc", ou: "kcal", ok: ["sonuc"], ol: { sonuc: "TDEE (Günlük Kalori İhtiyacı)" } },
  { slug: "target-heart-rate-karvonen-calculator", dt: "Karvonen formülüne göre ideal antrenman nabız aralığını hesaplar.", de: "Calculate target heart rate zone using the Karvonen formula.", cat: c, st: s, ld, sa,
    inputs: [{ id: "yas", lt: "Yaş", le: "Age", u: "years", d: 30, mn: 10, mx: 100, ct: "Kişinin yaşı.", ce: "Age." },{ id: "dinlenmeNabzi", lt: "Dinlenme Nabzı (BPM)", le: "Resting Heart Rate (BPM)", u: "bpm", d: 70, mn: 30, mx: 120, ct: "Dinlenme halindeki kalp atış hızı.", ce: "Resting heart rate." },{ id: "yogunluk", lt: "Hedef Yoğunluk (%)", le: "Target Intensity (%)", u: "%", d: 75, mn: 40, mx: 100, ct: "Antrenman yoğunluğu.", ce: "Workout intensity." }],
    f: { maxNabiz: "220 - yas", sonuc: "((220 - yas - dinlenmeNabzi) * yogunluk / 100) + dinlenmeNabzi" }, op: "sonuc", ou: "bpm", ok: ["sonuc"], ol: { sonuc: "Hedef Kalp Atış Hızı" } },
  { slug: "vo2-max-cooper-test-calculator", dt: "Cooper testine göre maksimum oksijen tüketim kapasitesini (VO2 Max) hesaplar.", de: "Estimate VO2 max using the Cooper test formula.", cat: c, st: s, ld, sa,
    inputs: [{ id: "kosuMesafesi", lt: "12 Dk Koşu Mesafesi (m)", le: "12min Run Distance (m)", u: "m", d: 2400, mn: 500, ct: "12 dakikada koşulan toplam mesafe.", ce: "Total distance covered in 12 minutes." }],
    f: { sonuc: "(kosuMesafesi - 504.9) / 44.73" }, op: "sonuc", ou: "ml/kg/min", ok: ["sonuc"], ol: { sonuc: "VO2 Max" } },
  { slug: "daily-macronutrient-targets-calculator", dt: "Günlük kalori hedefinin gramaj bazlı besin dağılımını (protein, yağ, karbonhidrat) hesaplar.", de: "Calculate daily macronutrient targets in grams based on calorie goals.", cat: c, st: s, ld, sa,
    inputs: [{ id: "tdee", lt: "Günlük Kalori (kcal)", le: "Daily Calories (kcal)", u: "kcal", d: 2500, ct: "Toplam günlük enerji hedefi.", ce: "Total daily energy target." },{ id: "protein", lt: "Protein Oranı (%)", le: "Protein Ratio (%)", u: "%", d: 30, mn: 5, mx: 50, ct: "Kalorinin protein yüzdesi.", ce: "Percentage of calories from protein." },{ id: "yag", lt: "Yağ Oranı (%)", le: "Fat Ratio (%)", u: "%", d: 25, mn: 5, mx: 50, ct: "Kalorinin yağ yüzdesi.", ce: "Percentage from fat." },{ id: "karb", lt: "Karbonhidrat Oranı (%)", le: "Carbs Ratio (%)", u: "%", d: 45, mn: 5, mx: 80, ct: "Kalorinin karbonhidrat yüzdesi.", ce: "Percentage from carbs." }],
    f: { protein_g: "(tdee * protein / 100) / 4", yag_g: "(tdee * yag / 100) / 9", sonuc: "(tdee * karb / 100) / 4" },
    op: "sonuc", ou: "g", ok: ["protein_g", "yag_g", "sonuc"], ol: { protein_g: "Protein (g)", yag_g: "Yağ (g)", sonuc: "Karbohidrat (g)" } },
  { slug: "daily-water-intake-calculator", dt: "Günlük baz ve aktivite kaynaklı su kaybını telafi eden minimum su miktarını hesaplar.", de: "Calculate daily water intake needs based on weight and activity.", cat: c, st: s, ld, sa,
    inputs: [{ id: "agirlik", lt: "Ağırlık (kg)", le: "Weight (kg)", u: "kg", d: 75, ct: "Vücut ağırlığı.", ce: "Body weight." },{ id: "aktiviteSure", lt: "Günlük Egzersiz Süresi (Dk)", le: "Daily Exercise (Min)", u: "min", d: 30, ct: "Günlük fiziksel aktivite.", ce: "Daily physical activity." }],
    f: { sonuc: "(agirlik * 0.033) + (aktiviteSure / 30 * 0.35)" }, op: "sonuc", ou: "liters", ok: ["sonuc"], ol: { sonuc: "Günlük Su İhtiyacı" } },
];
