import type { ToolDef } from "./359-types";
const c = "automotive-transport"; const s = "Mekanik, Otomotiv ve Havacılık";
const ld: string[] = ["High fuel/energy consumption indicates efficiency losses."];
const sa: string[] = ["Regular maintenance improves overall equipment efficiency.", "Simulate real-world driving conditions for accurate range estimates."];

export const section19: ToolDef[] = [
  { slug: "0-100-kmh-acceleration-calculator", dt: "Aracın durgun halden 100 km/h hıza ulaşma süresini hesaplar.", de: "Calculate vehicle 0-100 km/h acceleration time.", cat: c, st: s, ld, sa,
    inputs: [{ id: "kutle", lt: "Araç Kütlesi (kg)", le: "Vehicle Mass (kg)", u: "kg", d: 1500, ct: "Araç ağırlığı.", ce: "Vehicle weight." },{ id: "tork", lt: "Motor Torku (N.m)", le: "Engine Torque (N.m)", u: "N.m", d: 300, ct: "Motorun ürettiği tork.", ce: "Engine torque." },{ id: "cekişKatsayisi", lt: "Çekiş Katsayısı", le: "Traction Coefficient", u: "", d: 0.8, ct: "Lastik-yol tutunma katsayısı.", ce: "Tire-road friction." },{ id: "havaDirenci", lt: "Hava Direnci (N)", le: "Aerodynamic Drag (N)", u: "N", d: 500, ct: "100 km/h'deki hava direnci.", ce: "Aerodynamic drag at 100 km/h." }],
    f: { ivme: "((tork * cekişKatsayisi) - havaDirenci) / Math.max(0.0001, kutle)", sonuc: "(100 / 3.6) / Math.max(0.0001, ivme)" }, op: "sonuc", ou: "s", ok: ["sonuc"], ol: { sonuc: "0-100 km/h Süresi" } },
  { slug: "chain-drive-calculator", dt: "Zincir tahrik mekanizmasının toplam zincir boyunu ve dişli oranını hesaplar.", de: "Calculate chain drive length and sprocket ratio.", cat: c, st: s, ld, sa,
    inputs: [{ id: "Z1", lt: "Küçük Dişli Diş Sayısı (Z1)", le: "Small Sprocket Teeth (Z1)", u: "teeth", d: 17, mn: 6, ct: "Motor dişlisi.", ce: "Drive sprocket." },{ id: "Z2", lt: "Büyük Dişli Diş Sayısı (Z2)", le: "Large Sprocket Teeth (Z2)", u: "teeth", d: 45, mn: 6, ct: "Tekerlek dişlisi.", ce: "Wheel sprocket." },{ id: "adim", lt: "Zincir Adımı (mm)", le: "Chain Pitch (mm)", u: "mm", d: 12.7, ct: "Zincir bakla arası mesafe.", ce: "Chain link pitch." },{ id: "merkezC", lt: "Merkezler Arası Mesafe (mm)", le: "Center Distance (mm)", u: "mm", d: 500, ct: "Dişliler arası mesafe.", ce: "Distance between sprockets." }],
    f: { oran: "Z2 / Math.max(1, Z1)", sonuc: "2*merkezC + (Z1+Z2)*adim/2 + Math.pow(((Z2-Z1)*adim)/(2*Math.PI), 2)/Math.max(0.0001, merkezC)" }, op: "sonuc", ou: "mm", ok: ["sonuc"], ol: { sonuc: "Zincir Boyu" } },
  { slug: "ev-charging-time-calculator", dt: "Elektrikli araç bataryasının %0'dan %100'e dolum süresini hesaplar.", de: "Calculate EV battery charging time from 0 to 100%.", cat: c, st: s, ld, sa,
    inputs: [{ id: "bataryaKapasite", lt: "Batarya Kapasitesi (kWh)", le: "Battery Capacity (kWh)", u: "kWh", d: 60, ct: "Toplam batarya enerjisi.", ce: "Total battery energy." },{ id: "sarjGuc", lt: "Şarj Gücü (kW)", le: "Charging Power (kW)", u: "kW", d: 7.4, ct: "Şarj istasyonu gücü.", ce: "Charger power." },{ id: "verim", lt: "Şarj Verimi (%)", le: "Charging Efficiency (%)", u: "%", d: 90, ct: "Şarj kayıpları.", ce: "Charging losses." }],
    f: { sonuc: "bataryaKapasite / Math.max(0.0001, (sarjGuc * (verim / 100)))" }, op: "sonuc", ou: "hours", ok: ["sonuc"], ol: { sonuc: "Şarj Süresi" } },
  { slug: "ev-range-calculator", dt: "Elektrikli aracın tam şarjla gidebileceği teorik maksimum menzili hesaplar.", de: "Calculate EV range on a full charge.", cat: c, st: s, ld, sa,
    inputs: [{ id: "bataryaEnerji", lt: "Batarya Enerjisi (kWh)", le: "Battery Energy (kWh)", u: "kWh", d: 60, ct: "Kullanılabilir batarya kapasitesi.", ce: "Usable battery capacity." },{ id: "tuketim", lt: "Enerji Tüketimi (Wh/km)", le: "Energy Consumption (Wh/km)", u: "Wh/km", d: 180, ct: "km başı enerji tüketimi.", ce: "Energy consumption per km." },{ id: "verim", lt: "Aktarma Verimi (%)", le: "Drivetrain Efficiency (%)", u: "%", d: 90, ct: "Motordan tekerleğe verim.", ce: "Motor-to-wheel efficiency." }],
    f: { sonuc: "(bataryaEnerji * 1000 * (verim / 100)) / Math.max(0.0001, tuketim)" }, op: "sonuc", ou: "km", ok: ["sonuc"], ol: { sonuc: "Tahmini Menzil" } },
  { slug: "horsepower-converter-calculator", dt: "Farklı birimlerdeki güç değerini standart kW birimine dönüştürür.", de: "Convert horsepower (HP/PS) to kilowatts (kW).", cat: c, st: s, ld, sa,
    inputs: [{ id: "deger", lt: "Güç Değeri", le: "Power Value", u: "", d: 100, ct: "Dönüştürülecek güç.", ce: "Power to convert." },{ id: "kaynak", lt: "Kaynak Birim (0=HP, 1=kW, 2=PS)", le: "Source Unit (0=HP, 1=kW, 2=PS)", u: "", d: 0, ct: "Girilen birim.", ce: "Input unit." }],
    f: { sonuc: "kaynak === 0 ? deger * 0.7457 : kaynak === 2 ? deger * 0.7355 : deger" }, op: "sonuc", ou: "kW", ok: ["sonuc"], ol: { sonuc: "kW Karşılığı" } },
  { slug: "indicated-horsepower-calculator", dt: "Motor silindirleri içinde üretilen brüt teorik gücü (IHP) hesaplar.", de: "Calculate indicated horsepower (IHP) from cylinder parameters.", cat: c, st: s, ld, sa,
    inputs: [{ id: "basinc", lt: "Ortalama İndike Basınc (Pa)", le: "Mean Indicated Pressure (Pa)", u: "Pa", d: 1e6, ct: "Silindir içi ortalama basınç.", ce: "Average cylinder pressure." },{ id: "strok", lt: "Strok (m)", le: "Stroke (m)", u: "m", d: 0.1, ct: "Pistonun alt-üst ölü nokta mesafesi.", ce: "Piston stroke length." },{ id: "alan", lt: "Piston Alanı (m²)", le: "Piston Area (m²)", u: "m2", d: 0.01, ct: "Piston yüzey alanı.", ce: "Piston cross-section area." },{ id: "devir", lt: "Motor Devri (devir/dk)", le: "Engine Speed (RPM)", u: "rpm", d: 3000, ct: "Krank mili dönüş hızı.", ce: "Crankshaft speed." }],
    f: { sonuc: "(basinc * strok * alan * devir) / 60000" }, op: "sonuc", ou: "kW", ok: ["sonuc"], ol: { sonuc: "İndike Beygir Gücü (IHP)" } },
  { slug: "engine-torque-calculator", dt: "Motorun belirli bir devirde ürettiği döndürme momentini (tork) hesaplar.", de: "Calculate engine torque at a given power and RPM.", cat: c, st: s, ld, sa,
    inputs: [{ id: "guc", lt: "Motor Gücü (kW)", le: "Engine Power (kW)", u: "kW", d: 100, ct: "Motorun ürettiği güç.", ce: "Engine output power." },{ id: "devir", lt: "Motor Devri (devir/dk)", le: "Engine Speed (RPM)", u: "rpm", d: 3000, ct: "Krank mili devri.", ce: "Crankshaft speed." }],
    f: { sonuc: "(guc * 9550) / Math.max(0.0001, devir)" }, op: "sonuc", ou: "N.m", ok: ["sonuc"], ol: { sonuc: "Motor Torku" } },
  { slug: "motor-efficiency-calculator", dt: "Elektrik enerjisinin mekanik enerjiye dönüşüm başarısını (motor verimi) hesaplar.", de: "Calculate electric motor efficiency.", cat: c, st: s, ld, sa,
    inputs: [{ id: "cikisGuc", lt: "Çıkış Gücü (W)", le: "Output Power (W)", u: "W", d: 750, ct: "Milin ürettiği mekanik güç.", ce: "Shaft mechanical power." },{ id: "girisGuc", lt: "Giriş Gücü (W)", le: "Input Power (W)", u: "W", d: 1000, ct: "Motorun çektiği elektrik gücü.", ce: "Motor electrical power." }],
    f: { sonuc: "(cikisGuc / Math.max(0.0001, girisGuc)) * 100" }, op: "sonuc", ou: "%", ok: ["sonuc"], ol: { sonuc: "Motor Verimi" } },
  { slug: "vehicle-top-speed-calculator", dt: "Motor gücünün direnç kuvvetlerini yendiği denge hızını (maksimum hız) hesaplar.", de: "Calculate vehicle top speed where engine power equals total drag.", cat: c, st: s, ld, sa,
    inputs: [{ id: "guc", lt: "Motor Gücü (W)", le: "Engine Power (W)", u: "W", d: 100000, ct: "Maksimum motor gücü.", ce: "Maximum engine power." },{ id: "kutle", lt: "Araç Kütlesi (kg)", le: "Vehicle Mass (kg)", u: "kg", d: 1500, ct: "Araç ağırlığı.", ce: "Vehicle weight." },{ id: "suratmeKatsayi", lt: "Yuvarlanma Sürtünme Katsayısı", le: "Rolling Friction Coefficient", u: "", d: 0.015, ct: "Lastik-yol sürtünme katsayısı.", ce: "Tire rolling resistance." }],
    f: { sonuc: "Math.pow((guc / suratmeKatsayi), 1/3)" }, op: "sonuc", ou: "m/s", ok: ["sonuc"], ol: { sonuc: "Maksimum Hız" } },
  { slug: "runway-length-calculator", dt: "Uçağın havalanması için gereken minimum pist mesafesini hesaplar.", de: "Calculate minimum runway length required for takeoff.", cat: c, st: s, ld, sa,
    inputs: [{ id: "kalkisHiz", lt: "Kalkış Hızı (m/s)", le: "Takeoff Speed (m/s)", u: "m/s", d: 80, ct: "Uçağın yerden kesilme hızı.", ce: "Aircraft rotation speed." },{ id: "ivme", lt: "Ortalama İvme (m/s²)", le: "Average Acceleration (m/s²)", u: "m/s2", d: 3, ct: "Motor itki gücüyle hızlanma.", ce: "Engine thrust acceleration." },{ id: "ruzgarHiz", lt: "Karşı Rüzgar Hızı (m/s)", le: "Headwind Speed (m/s)", u: "m/s", d: 5, ct: "Pist başı rüzgar.", ce: "Runway headwind component." }],
    f: { etkiliHiz: "kalkisHiz - ruzgarHiz", sonuc: "(etkiliHiz * etkiliHiz) / Math.max(0.0001, (2 * ivme))" }, op: "sonuc", ou: "m", ok: ["sonuc"], ol: { sonuc: "Gerekli Pist Uzunluğu" } },
];
