import type { ToolDef } from "./359-types";
const c = "other"; const s = "İleri Fizik ve Kuantum";
const ld: string[] = []; const sa: string[] = ["Quantum effects are only observable at microscopic scales.", "These are idealized models."];

export const section15: ToolDef[] = [
  { slug: "quantum-tunneling-probability-calculator", dt: "Parçacığın klasik fizikte aşamayacağı engeli geçme olasılığını (kuantum tünelleme) hesaplar.", de: "Calculate quantum tunneling probability through a potential barrier.", cat: c, st: s, ld, sa,
    inputs: [{ id: "engelGenisligi", lt: "Engel Genişliği (m)", le: "Barrier Width (m)", u: "m", d: 1e-10, ct: "Potansiyel engelin kalınlığı.", ce: "Potential barrier thickness." },{ id: "engelYuksekligi", lt: "Engel Yüksekliği (J)", le: "Barrier Height (J)", u: "J", d: 1.6e-19, ct: "Potansiyel engelin yüksekliği.", ce: "Potential barrier height." },{ id: "enerji", lt: "Parçacık Enerjisi (J)", le: "Particle Energy (J)", u: "J", d: 8e-20, ct: "Gelen parçacığın kinetik enerjisi.", ce: "Incident particle kinetic energy." },{ id: "kutle", lt: "Parçacık Kütlesi (kg)", le: "Particle Mass (kg)", u: "kg", d: 9.11e-31, ct: "Parçacığın kütlesi.", ce: "Particle mass." }],
    f: { hbar: "1.054e-34", sonuc: "Math.exp(-2 * Math.sqrt(Math.max(0, 2 * kutle * (engelYuksekligi - enerji))) / 1.054e-34 * engelGenisligi) * 100" }, op: "sonuc", ou: "%", ok: ["sonuc"], ol: { sonuc: "Tünelleme Olasılığı" } },
  { slug: "infinite-well-energy-calculator", dt: "Sonsuz potansiyel kuyusundaki parçacığın izin verilen enerji seviyesini hesaplar.", de: "Calculate allowed energy level in an infinite potential well (1D).", cat: c, st: s, ld, sa,
    inputs: [{ id: "kuyuGenisligi", lt: "Kuyu Genişliği (m)", le: "Well Width (m)", u: "m", d: 1e-10, ct: "Sonsuz kuyunun genişliği.", ce: "Infinite well width." },{ id: "kutle", lt: "Parçacık Kütlesi (kg)", le: "Particle Mass (kg)", u: "kg", d: 9.11e-31, ct: "Parçacığın kütlesi.", ce: "Particle mass." },{ id: "kuantumSayisi", lt: "Kuantum Sayısı (n)", le: "Quantum Number (n)", u: "", d: 1, mn: 1, ct: "Enerji seviye numarası.", ce: "Energy level quantum number." }],
    f: { sonuc: "(Math.pow(kuantumSayisi, 2) * Math.pow(Math.PI, 2) * Math.pow(1.054e-34, 2)) / Math.max(0.0001, (2 * kutle * Math.pow(kuyuGenisligi, 2)))" }, op: "sonuc", ou: "J", ok: ["sonuc"], ol: { sonuc: "Enerji (Eₙ)" } },
  { slug: "compton-shift-calculator", dt: "Fotonun saçılma sonrası dalga boyundaki değişimi (Compton kayması) hesaplar.", de: "Calculate Compton shift in photon wavelength after scattering.", cat: c, st: s, ld, sa,
    inputs: [{ id: "sacilmaAcisi", lt: "Saçılma Açısı (Derece)", le: "Scattering Angle (Deg)", u: "degrees", d: 90, mn: 0, mx: 180, ct: "Fotonun saçılma açısı.", ce: "Photon scattering angle." }],
    f: { sonuc: "2.426e-12 * (1 - Math.cos(sacilmaAcisi * Math.PI / 180))" }, op: "sonuc", ou: "m", ok: ["sonuc"], ol: { sonuc: "Compton Kayması" } },
  { slug: "chandrasekhar-limit-calculator", dt: "Beyaz cücenin çökmeden önceki maksimum kütle sınırını (Chandrasekhar limiti) hesaplar.", de: "Calculate the Chandrasekhar limit for white dwarf maximum mass.", cat: c, st: s, ld, sa,
    inputs: [{ id: "gunesKutlesi", lt: "Yıldız Kütlesi (Güneş Kütlesi)", le: "Star Mass (Solar Mass)", u: "M☉", d: 1.4, ct: "Yıldızın Güneş kütlesi cinsinden ağırlığı.", ce: "Star mass in solar masses." }],
    f: { sonuc: "gunesKutlesi > 1.44 ? 1.44 : gunesKutlesi" }, op: "sonuc", ou: "M☉", ok: ["sonuc"], ol: { sonuc: "Chandrasekhar Limiti" } },
  { slug: "load-factor-calculator", dt: "Tüketicinin enerjiyi ne kadar dengeli kullandığının göstergesini (yük faktörü) hesaplar.", de: "Calculate electrical load factor — average vs peak power usage ratio.", cat: c, st: s, ld, sa,
    inputs: [{ id: "ortalamaGuc", lt: "Ortalama Güç (kW)", le: "Average Power (kW)", u: "kW", d: 80, ct: "Dönem boyunca ortalama çekilen güç.", ce: "Average power drawn." },{ id: "pikGuc", lt: "Pik Güç (kW)", le: "Peak Power (kW)", u: "kW", d: 200, ct: "Dönemdeki en yüksek güç talebi.", ce: "Peak power demand." }],
    f: { sonuc: "(ortalamaGuc / Math.max(0.0001, pikGuc)) * 100" }, op: "sonuc", ou: "%", ok: ["sonuc"], ol: { sonuc: "Yük Faktörü" } },
  { slug: "fiber-optic-loss-calculator", dt: "Işık sinyalinin hat sonundaki toplam güç kaybını (fiber optik zayıflama) hesaplar.", de: "Calculate total optical power loss in fiber optic link.", cat: c, st: s, ld, sa,
    inputs: [{ id: "uzunluk", lt: "Fiber Uzunluğu (km)", le: "Fiber Length (km)", u: "km", d: 50, ct: "Fiber kablo boyu.", ce: "Fiber cable length." },{ id: "birimKayip", lt: "Birim Kayıp (dB/km)", le: "Attenuation (dB/km)", u: "dB/km", d: 0.2, ct: "Fiberin km başına zayıflaması.", ce: "Loss per km." },{ id: "ekKayip", lt: "Ek Kayıplar (dB)", le: "Splice Losses (dB)", u: "dB", d: 1.5, ct: "Konnektör ve ek kayıpları.", ce: "Connector and splice losses." }],
    f: { sonuc: "(uzunluk * birimKayip) + ekKayip" }, op: "sonuc", ou: "dB", ok: ["sonuc"], ol: { sonuc: "Toplam Zayıflama" } },
  { slug: "antenna-length-calculator", dt: "Rezonans için gereken fiziksel anten eleman boyunu hesaplar.", de: "Calculate physical antenna element length for resonance at given frequency.", cat: c, st: s, ld, sa,
    inputs: [{ id: "frekans", lt: "Frekans (MHz)", le: "Frequency (MHz)", u: "MHz", d: 100, ct: "Çalışma frekansı.", ce: "Operating frequency." },{ id: "tip", lt: "Anten Tipi (1=Dipole, 2=Yagi)", le: "Antenna Type (1=Dipole, 2=Yagi)", u: "", d: 1, ct: "Anten türü.", ce: "Antenna type." }],
    f: { dalgaBoyu: "300 / Math.max(0.0001, frekans)", sonuc: "tip === 1 ? 300 / Math.max(0.0001, frekans) / 2 : 300 / Math.max(0.0001, frekans) * 0.45" }, op: "sonuc", ou: "m", ok: ["sonuc"], ol: { sonuc: "Anten Uzunluğu" } },
  { slug: "beam-reaction-calculator", dt: "Basit kiriş mesnetlerindeki düşey tepki kuvvetlerini hesaplar.", de: "Calculate vertical reaction forces at simple beam supports.", cat: c, st: s, ld, sa,
    inputs: [{ id: "yuk", lt: "Tekil Yük (N)", le: "Point Load (N)", u: "N", d: 10000, ct: "Kirişe uygulanan tekil kuvvet.", ce: "Point force on beam." },{ id: "uzunluk", lt: "Kiriş Boyu (m)", le: "Beam Length (m)", u: "m", d: 6, ct: "Mesnetler arası mesafe.", ce: "Span between supports." },{ id: "yukKonum", lt: "Yükün A Konumuna Uzaklığı (m)", le: "Load Distance from A (m)", u: "m", d: 2, ct: "Yükün sol mesnete uzaklığı.", ce: "Distance from left support to load." }],
    f: { RA: "yuk * Math.max(0, (uzunluk - yukKonum)) / Math.max(0.0001, uzunluk)", sonuc: "yuk - yuk * Math.max(0, (uzunluk - yukKonum)) / Math.max(0.0001, uzunluk)" }, op: "sonuc", ou: "N", ok: ["RA", "sonuc"], ol: { RA: "Tepki A (Rₐ)", sonuc: "Tepki B (Rᵦ)" } },
];
