import Big from "big.js"; import fc from "fast-check"; import {describe,expect,it} from "vitest";
import {FX_COMMODITY_FORMULA_VERSION,FX_COMMODITY_MODEL_ID,FX_COMMODITY_SCHEMA_VERSION,evaluateFxCommodity} from "@/sectorcalc/formulas/pro-v531/fx-commodity-core";
import {calculate,sampleInputs} from "@/sectorcalc/formulas/pro-v531/fx-commodity-pass-through-pricer.formula"; import {resolveApprovedToolSchema} from "@/sectorcalc/runtime/resolve-approved-tool-schema";
const D=Big();D.DP=50;D.RM=2;D.STRICT=true;const close=(a:Big,b:Big)=>a.minus(b).abs().div(a.abs().plus(b.abs()).plus("1")).lte("1e-44");
function evaluate(o:Record<string,string>={}){const r=evaluateFxCommodity({basePrice:"100",currentFxRate:"1.1",budgetFxRate:"1.05",currentCommodityIndex:"180",budgetCommodityIndex:"160",materialCostShareRatio:"0.4",fxHedgeRatio:"0.6",commodityHedgeRatio:"0.5",annualVolume:"10000",sourceConfidenceRatio:"0.9",...o});expect(r.ok).toBe(true);if(!r.ok)throw Error(r.error.message);return r.value;}
describe("FX commodity pass-through Decimal properties",()=>{
it("proves factor, component, decomposition, price, and annual identities",()=>{fc.assert(fc.property(fc.integer({min:1,max:1000000}),fc.integer({min:1,max:1000000}),(priceCents,volume)=>{const p=D(String(priceCents)).div("100");const r=evaluate({basePrice:p.toString(),annualVolume:String(volume)});expect(r.combinedMaterialFactor.eq(r.hedgeAdjustedFxFactor.times(r.hedgeAdjustedCommodityFactor))).toBe(true);expect(r.nonMaterialPriceComponent.plus(r.materialPriceComponent).eq(p)).toBe(true);expect(r.totalPriceAdjustment.eq(r.fxPriceImpact.plus(r.commodityAndInteractionPriceImpact))).toBe(true);expect(r.adjustedPrice.eq(p.plus(r.totalPriceAdjustment))).toBe(true);expect(close(r.passThroughRatio.times(p),r.totalPriceAdjustment)).toBe(true);expect(r.annualPriceAdjustment.eq(r.totalPriceAdjustment.times(String(volume)))).toBe(true);}),{numRuns:500,seed:539001});});
it("is homogeneous in base price without changing factors or decisions",()=>{fc.assert(fc.property(fc.integer({min:1,max:10000}),f=>{const s=D(String(f));const a=evaluate();const b=evaluate({basePrice:D("100").times(s).toString()});expect(close(b.adjustedPrice,a.adjustedPrice.times(s))).toBe(true);expect(close(b.annualMoneyAtRisk,a.annualMoneyAtRisk.times(s))).toBe(true);expect(b.passThroughRatio.eq(a.passThroughRatio)).toBe(true);expect(b.decisionState).toBe(a.decisionState);}),{numRuns:500,seed:539002});});
it("is monotone in unhedged markets and eliminates a fully hedged market movement",()=>{fc.assert(fc.property(fc.integer({min:1,max:999}),bp=>{const x=D(String(bp)).div("1000");const fxLow=evaluate({currentFxRate:x.plus("1").toString()});const fxHigh=evaluate({currentFxRate:x.plus("1.001").toString()});expect(fxHigh.adjustedPrice.gt(fxLow.adjustedPrice)).toBe(true);const fxHedged=evaluate({fxHedgeRatio:"1"});expect(fxHedged.hedgeAdjustedFxFactor.eq("1")).toBe(true);expect(fxHedged.fxPriceImpact.eq("0")).toBe(true);const commodityHedged=evaluate({commodityHedgeRatio:"1"});expect(commodityHedged.hedgeAdjustedCommodityFactor.eq("1")).toBe(true);expect(commodityHedged.commodityAndInteractionPriceImpact.eq("0")).toBe(true);}),{numRuns:500,seed:539003});});
it("encloses adjusted price and narrows with confidence",()=>{fc.assert(fc.property(fc.integer({min:0,max:999}),bp=>{const c=D(String(bp)).div("1000");const a=evaluate({sourceConfidenceRatio:c.toString()});const b=evaluate({sourceConfidenceRatio:c.plus("0.001").toString()});expect(a.adjustedPriceLowerBound.lte(a.adjustedPrice)).toBe(true);expect(a.adjustedPriceUpperBound.gte(a.adjustedPrice)).toBe(true);expect(b.priceAdjustmentUncertainty.lte(a.priceAdjustmentUncertainty)).toBe(true);expect(b.adjustedPriceLowerBound.gte(a.adjustedPriceLowerBound)).toBe(true);}),{numRuns:500,seed:539004});});
it("fails closed for zero references/price/volume, invalid ratios/counts, NaN, and infinity",()=>{const b={basePrice:"100",currentFxRate:"1.1",budgetFxRate:"1.05",currentCommodityIndex:"180",budgetCommodityIndex:"160",materialCostShareRatio:"0.4",fxHedgeRatio:"0.6",commodityHedgeRatio:"0.5",annualVolume:"10000",sourceConfidenceRatio:"0.9"};expect(evaluateFxCommodity({...b,basePrice:"0"}).ok).toBe(false);expect(evaluateFxCommodity({...b,budgetFxRate:"0"}).ok).toBe(false);expect(evaluateFxCommodity({...b,budgetCommodityIndex:"0"}).ok).toBe(false);expect(evaluateFxCommodity({...b,annualVolume:"1.5"}).ok).toBe(false);expect(evaluateFxCommodity({...b,fxHedgeRatio:"1.1"}).ok).toBe(false);expect(evaluateFxCommodity({...b,currentFxRate:Number.NaN}).ok).toBe(false);expect(evaluateFxCommodity({...b,currentCommodityIndex:Number.POSITIVE_INFINITY}).ok).toBe(false);});
it("binds canonical ratios, annual counts, multiplicative policy, and exact outputs",()=>{const s=resolveApprovedToolSchema("fx-commodity-pass-through-pricer");if(!s.ok)throw Error(`${s.reason}:${s.errors.join("|")}`);expect(s.schema.metadata.formula_version).toBe(FX_COMMODITY_FORMULA_VERSION);expect(s.schema.metadata.schema_version).toBe(FX_COMMODITY_SCHEMA_VERSION);expect(s.schema.calculation_basis.model_id).toBe(FX_COMMODITY_MODEL_ID);expect(s.schema.calculation_basis.material_factor_policy).toContain("TIMES");expect(s.schema.inputs.find(i=>i.id==="annual_volume")).toMatchObject({type:"integer",base_unit:"count/year"});const f=calculate(sampleInputs);expect(f.status).not.toBe("BLOCKED");expect(Object.keys(f.outputs).sort()).toEqual(s.schema.outputs.map(i=>i.id).sort());for(const[id,x]of Object.entries(f.decimalOutputs??{}))expect(Number(x)).toBe(f.outputs[id]);});
});
