import type { GlobalToolCategorySlug } from "@/lib/catalog/global-tool-category-taxonomy";

export const FREE_TO_PREMIUM_TITLE_LIST_TR = [
  "Kira mı Satın Alma mı Karşılaştırması",
  "İç Verim Oranı (IRR) Hesaplama",
  "OEE Hesaplayıcı",
  "İstatistiksel Proses Kontrol (SPC) Limit Hesabı",
  "Altı Sigma – DPMO – Sigma Seviyesi Çevirici",
  "Doğrusal Regresyon Hesaplayıcı",
  "Örneklem Büyüklüğü Hesaplayıcı",
  "Lazer Kesim Süresi Kontrolü",
  "3B Baskı Maliyet Kontrolü",
  "Rüzgar Türbini Yaklaşık Üretim Hesabı",
  "CBAM Maruziyet Hızlı Kontrol",
  "İşveren Maaş Maliyeti Hesaplayıcı",
  "Gelir Vergisi Dilimleri Hesaplama",
  "SGK Prim Hesaplama (İşçi + İşveren)",
  "Stopaj Hesaplama (Kira, Serbest Meslek)",
  "KDV Tevkifatı Hesaplama",
  "İş Kazası Maliyeti (Gün Kaybı) Hesaplama",
  "Personel Devamsızlık Maliyeti Hesaplama",
  "Çek – Senet Vade Kırma Maliyeti Hesabı",
  "Kredi Erken Kapama Cezası Hesaplama",
  "Leasing – Kiralama Maliyet Karşılaştırma",
  "Makine Ekonomik Ömrü – Hurda Değer Hesabı",
  "Nakit Akışı (Basit Günlük/Haftalık) Panosu",
  "Geri Dönüşüm Gelir – Maliyet Hesabı",
  "Yangın Merdiveni – Kaçış Yolu Genişliği Hesabı",
  "İş Sağlığı ve Güvenliği Ceza Hesaplama",
  "Çevre – Atık Beyanı Maliyet Hesaplama",
  "Basınçlı Kap Cidar Kalınlığı Hesabı",
  "Kaynak Prosedürü (WPS) Ön Isıtma Sıcaklığı Hesabı",
  "Yay (Helisel) Kuvvet – Uzama Hesabı",
  "Mil – Aks Çapı Hesabı (Eğilme – Burulma)",
  "Kaynaklı Bağlantı (Köşe – Küt) Mukavemet Hesabı",
  "Bulonlu Bağlantı (Kesme – Ezilme) Hesabı",
  "Rulman Ömür Hesabı (L10)",
  "Hidrolik Pompa Gücü Hesaplama",
  "Pnömatik Silindir Kuvvet Hesabı",
  "Kompresör Debisi – Tank Hacmi Hesabı",
  "Gerilim Düşümü Hesaplama",
  "Kablo Kesiti (mm²) Seçim Hesaplama",
  "Jeneratör Kapasitesi Seçim Hesaplama",
  "Klima BTU Seçim Hesaplama",
  "Karbon Ayak İzi Hızlı Kontrol",
  "Yakıt Emisyon Hesaplayıcı",
  "Konteyner Yükleme Kapasitesi (TEU) Hesabı",
  "Tır – Kamyon Yük Kapasitesi Hesaplama",
  "Depo Raf – Palet Yerleşim Optimizasyonu",
  "Araç Kira – Satın Alma Karşılaştırma",
  "Forklift – Transpalet Kullanım Maliyeti",
  "Paketleme Malzemesi (Streç, Koli) Sarfiyatı",
  "İrsaliye – Fatura Adedi Başına Sevkiyat Maliyeti",
  "Navlun Maliyeti Hesaplayıcı",
] as const;

export type FreeToPremiumMigrationTitle = (typeof FREE_TO_PREMIUM_TITLE_LIST_TR)[number];

/** Legacy slug aliases from migration spec → canonical seed category slugs. */
export const FREE_TO_PREMIUM_CATEGORY_SLUG_ALIASES: Readonly<
  Record<string, GlobalToolCategorySlug>
> = {
  "project-construction-site": "project-construction-management",
  "sheet-metal-forming": "metal-plastics-forming",
  "workforce-shift-hr": "workforce-hr",
  "safety-ergonomics-risk": "hse-ergonomics",
  "electrical-panel-power": "electrical-power-systems",
  "supply-logistics-procurement": "procurement-supply-chain",
};

export type FreeToPremiumWave2Item = {
  readonly titleTr: string;
  readonly slugCandidates: readonly string[];
  readonly categorySlug: GlobalToolCategorySlug;
  readonly reason: string;
};

/** Wave 2 — business-value free calculators moved to premium categories. */
export const FREE_TO_PREMIUM_WAVE_2 = [
  {
    titleTr: "Concrete Bag Calculator",
    slugCandidates: ["concrete-bag-calculator"],
    categorySlug: "project-construction-management",
    reason: "fire + torba verimi + maliyet optimizasyonu",
  },
  {
    titleTr: "Paint Coverage Calculator",
    slugCandidates: ["paint-coverage-calculator"],
    categorySlug: "project-construction-management",
    reason: "litre tahmini + kat sayısı + sarfiyat kontrolü",
  },
  {
    titleTr: "Home Renovation Cost per m²",
    slugCandidates: ["home-renovation-m2-calculator"],
    categorySlug: "project-construction-management",
    reason: "bütçe + contingency + parasal karar",
  },
  {
    titleTr: "İstinat Duvarı Yaklaşık Beton Hesabı",
    slugCandidates: ["istinat-duvari-yaklasik-beton-hesabi"],
    categorySlug: "project-construction-management",
    reason: "mühendislik maliyeti",
  },
  {
    titleTr: "Loan Payment Calculator",
    slugCandidates: ["loan-payment-calculator"],
    categorySlug: "finance-sales-working-capital",
    reason: "kredi maliyeti",
  },
  {
    titleTr: "Mortgage Calculator",
    slugCandidates: ["mortgage-calculator"],
    categorySlug: "finance-sales-working-capital",
    reason: "konut kredisi faiz toplamı",
  },
  {
    titleTr: "Compound Interest Calculator",
    slugCandidates: ["compound-interest-calculator"],
    categorySlug: "finance-sales-working-capital",
    reason: "yatırım getirisi",
  },
  {
    titleTr: "Profit Margin Calculator",
    slugCandidates: ["profit-margin-calculator"],
    categorySlug: "finance-sales-working-capital",
    reason: "kar marjı",
  },
  {
    titleTr: "Break-Even Calculator",
    slugCandidates: ["break-even-calculator"],
    categorySlug: "finance-sales-working-capital",
    reason: "başabaş noktası",
  },
  {
    titleTr: "ROI Calculator",
    slugCandidates: ["roi-calculator"],
    categorySlug: "finance-sales-working-capital",
    reason: "yatırım getirisi",
  },
  {
    titleTr: "Cash Flow Gap Calculator",
    slugCandidates: ["cash-flow-gap-calculator"],
    categorySlug: "finance-sales-working-capital",
    reason: "işletme sermayesi açığı",
  },
  {
    titleTr: "Enflasyon — Fiyat Eskalasyonu",
    slugCandidates: ["enflasyon-fiyat-eskalasyonu-hesaplama"],
    categorySlug: "finance-sales-working-capital",
    reason: "fiyatlama kararı",
  },
  {
    titleTr: "Döviz Pozisyonu — Kur Farkı Riski",
    slugCandidates: ["doviz-pozisyonu-kur-farki-riski-hesabi"],
    categorySlug: "finance-sales-working-capital",
    reason: "finansal risk",
  },
  {
    titleTr: "Fazla Mesai Ücreti",
    slugCandidates: ["fazla-mesai-ucreti-hesaplama"],
    categorySlug: "workforce-hr",
    reason: "işçilik maliyeti",
  },
  {
    titleTr: "İşe Giriş-Çıkış Bildirgesi Süreleri",
    slugCandidates: ["ise-giris-cikis-bildirgesi-sureleri"],
    categorySlug: "workforce-hr",
    reason: "ceza ve uyum maliyeti",
  },
  {
    titleTr: "Hourly Rate Calculator",
    slugCandidates: ["hourly-rate-calculator"],
    categorySlug: "finance-sales-working-capital",
    reason: "fiyatlama stratejisi",
  },
  {
    titleTr: "Machine Time Calculator",
    slugCandidates: ["machine-time-calculator"],
    categorySlug: "lean-production",
    reason: "makine maliyeti",
  },
  {
    titleTr: "CNC Cycle Time Calculator",
    slugCandidates: ["cnc-cycle-time-calculator"],
    categorySlug: "cnc-additive-manufacturing",
    reason: "parti maliyeti",
  },
  {
    titleTr: "Welding Cost Estimator",
    slugCandidates: ["welding-cost-estimator"],
    categorySlug: "metal-plastics-forming",
    reason: "işçilik + sarf malzeme",
  },
  {
    titleTr: "Sheet Metal Weight Calculator",
    slugCandidates: ["sheet-metal-weight-calculator"],
    categorySlug: "metal-plastics-forming",
    reason: "malzeme maliyeti",
  },
  {
    titleTr: "Material Waste Calculator",
    slugCandidates: ["material-waste-calculator"],
    categorySlug: "lean-production",
    reason: "fire kaybı",
  },
  {
    titleTr: "Scrap Rate Calculator",
    slugCandidates: ["scrap-rate-calculator"],
    categorySlug: "lean-production",
    reason: "hurda maliyeti",
  },
  {
    titleTr: "Machine Hour Rate Calculator",
    slugCandidates: ["machine-hour-rate-calculator"],
    categorySlug: "lean-production",
    reason: "tam yüklü makine saat ücreti",
  },
  {
    titleTr: "Tool Life Cost Calculator",
    slugCandidates: ["tool-life-calculator"],
    categorySlug: "cnc-additive-manufacturing",
    reason: "takım maliyeti / parça",
  },
  {
    titleTr: "Civata Sıkma Torku",
    slugCandidates: ["civata-sikma-torku-hesaplama"],
    categorySlug: "mechanical-hvac-energy-loss",
    reason: "güvenlik + montaj hatası maliyeti",
  },
  {
    titleTr: "Kaynak Dikiş Hacmi — Maliyeti",
    slugCandidates: ["kaynak-dikis-hacmi-maliyeti-hesabi"],
    categorySlug: "metal-plastics-forming",
    reason: "doğrudan kaynak maliyeti",
  },
  {
    titleTr: "Kesme Bükme Abkant Tonaj Hesabı",
    slugCandidates: ["kesme-bukme-abkant-tonaj-hesabi"],
    categorySlug: "metal-plastics-forming",
    reason: "operasyon maliyeti",
  },
  {
    titleTr: "Civata Ön Germe Kuvveti",
    slugCandidates: ["civata-on-germe-kuvveti-hesabi"],
    categorySlug: "mechanical-hvac-energy-loss",
    reason: "güvenlik / bağlantı hatası",
  },
  {
    titleTr: "Plastik Enjeksiyon Çevrim Süresi Tahmini",
    slugCandidates: ["plastik-enjeksiyon-cevrim-suresi-tahmini"],
    categorySlug: "metal-plastics-forming",
    reason: "üretim maliyeti",
  },
  {
    titleTr: "Enjeksiyon — Döküm Çekme Payı",
    slugCandidates: ["enjeksiyon-dokum-cekme-payi-hesabi"],
    categorySlug: "metal-plastics-forming",
    reason: "kalıp maliyeti",
  },
  {
    titleTr: "kWh Cost Calculator",
    slugCandidates: ["kwh-cost-calculator"],
    categorySlug: "mechanical-hvac-energy-loss",
    reason: "elektrik maliyeti",
  },
  {
    titleTr: "Electricity Bill Calculator",
    slugCandidates: ["electricity-bill-calculator"],
    categorySlug: "electrical-power-systems",
    reason: "fatura optimizasyonu",
  },
  {
    titleTr: "Compressor Energy Cost",
    slugCandidates: ["compressor-energy-cost-calculator"],
    categorySlug: "mechanical-hvac-energy-loss",
    reason: "basınçlı hava maliyeti",
  },
  {
    titleTr: "Heat Loss Calculator",
    slugCandidates: ["heat-loss-calculator"],
    categorySlug: "mechanical-hvac-energy-loss",
    reason: "ısı kaybı maliyeti",
  },
  {
    titleTr: "Boiler Efficiency Calculator",
    slugCandidates: ["boiler-efficiency-calculator"],
    categorySlug: "mechanical-hvac-energy-loss",
    reason: "yakıt tasarrufu",
  },
  {
    titleTr: "Motor Gücü KW-HP Çevirici",
    slugCandidates: ["motor-gucu-kw-hp-cevirici"],
    categorySlug: "electrical-power-systems",
    reason: "enerji bazlı karar",
  },
  {
    titleTr: "UPS Seçimi",
    slugCandidates: ["ups-kesintisiz-guc-kaynagi-secimi"],
    categorySlug: "electrical-power-systems",
    reason: "yatırım maliyeti",
  },
  {
    titleTr: "Akü Kapasitesi – Çalışma Süresi",
    slugCandidates: ["aku-kapasitesi-calisma-suresi-hesabi"],
    categorySlug: "electrical-power-systems",
    reason: "operasyonel süre ve maliyet",
  },
  {
    titleTr: "Route Cost Calculator",
    slugCandidates: ["route-cost-calculator"],
    categorySlug: "procurement-supply-chain",
    reason: "sürücü + süre + yakıt + yol maliyeti",
  },
  {
    titleTr: "Warehouse Storage Cost",
    slugCandidates: ["warehouse-storage-cost-calculator"],
    categorySlug: "procurement-supply-chain",
    reason: "stok maliyeti",
  },
  {
    titleTr: "Vehicle Depreciation Calculator",
    slugCandidates: ["vehicle-depreciation-calculator"],
    categorySlug: "procurement-supply-chain",
    reason: "amortisman",
  },
  {
    titleTr: "Araç Kira – Satın Alma Karşılaştırma",
    slugCandidates: ["arac-kira-satin-alma-karsilastirma"],
    categorySlug: "procurement-supply-chain",
    reason: "yatırım / kiralama kararı",
  },
  {
    titleTr: "Kasko – Sigorta Prim Karşılaştırma",
    slugCandidates: ["kasko-sigorta-prim-karsilastirma"],
    categorySlug: "procurement-supply-chain",
    reason: "risk maliyeti",
  },
  {
    titleTr: "Şoför – Operatör Günlük Yevmiye Maliyeti",
    slugCandidates: ["sofor-operator-gunluk-yevmiye-maliyeti"],
    categorySlug: "procurement-supply-chain",
    reason: "işçilik maliyeti",
  },
  {
    titleTr: "Trafik Cezası – Gecikme Faizi",
    slugCandidates: ["trafik-cezasi-gecikme-faizi-hesaplama"],
    categorySlug: "procurement-supply-chain",
    reason: "uyum maliyeti",
  },
  {
    titleTr: "Fertilizer Dosage Calculator",
    slugCandidates: ["fertilizer-dosage-calculator"],
    categorySlug: "food-cold-chain-hygiene",
    reason: "gübre maliyeti",
  },
  {
    titleTr: "Seed Rate Calculator",
    slugCandidates: ["seed-rate-calculator"],
    categorySlug: "food-cold-chain-hygiene",
    reason: "tohum maliyeti",
  },
  {
    titleTr: "Irrigation Cost Check",
    slugCandidates: ["irrigation-cost-check"],
    categorySlug: "food-cold-chain-hygiene",
    reason: "sulama enerji + su maliyeti",
  },
  {
    titleTr: "Feed Cost Estimator",
    slugCandidates: ["feed-cost-estimator"],
    categorySlug: "food-cold-chain-hygiene",
    reason: "yem maliyeti",
  },
  {
    titleTr: "Milk Yield Check",
    slugCandidates: ["milk-yield-check"],
    categorySlug: "food-cold-chain-hygiene",
    reason: "gelir tahmini",
  },
  {
    titleTr: "Crop Yield Calculator",
    slugCandidates: ["crop-yield-calculator"],
    categorySlug: "food-cold-chain-hygiene",
    reason: "hasat geliri",
  },
  {
    titleTr: "Food Cost Percentage",
    slugCandidates: ["food-cost-calculator", "food-cost-percentage-calculator"],
    categorySlug: "food-cold-chain-hygiene",
    reason: "restoran kar marjı",
  },
  {
    titleTr: "Portion Cost Calculator",
    slugCandidates: ["portion-cost-calculator"],
    categorySlug: "food-cold-chain-hygiene",
    reason: "porsiyon maliyeti",
  },
  {
    titleTr: "Toplantı Saati Maliyeti",
    slugCandidates: ["toplanti-saati-maliyeti-hesaplama"],
    categorySlug: "workforce-hr",
    reason: "şirket içi zaman maliyeti",
  },
  {
    titleTr: "Abonelik Yazılım Cloud Yıllık Maliyet",
    slugCandidates: ["abonelik-yazilim-cloud-yillik-maliyet-hesabi"],
    categorySlug: "technology-ai-cloud-cyber",
    reason: "TCO / yıllık teknoloji gideri",
  },
  {
    titleTr: "Şirket Telefon Faturası",
    slugCandidates: ["sirket-telefon-faturasi-hesaplama"],
    categorySlug: "packaging-local-business",
    reason: "gider optimizasyonu",
  },
  {
    titleTr: "Çelik Raf – Depo Rafı Yük Kapasitesi",
    slugCandidates: ["celik-raf-depo-rafi-yuk-kapasitesi"],
    categorySlug: "procurement-supply-chain",
    reason: "yatırım / güvenlik kararı",
  },
  {
    titleTr: "Z-Score Calculator",
    slugCandidates: ["z-score-calculator"],
    categorySlug: "quality-six-sigma",
    reason: "kalite kontrol / finansal sapma analizi",
  },
  {
    titleTr: "Standard Deviation Calculator",
    slugCandidates: ["standard-deviation-calculator"],
    categorySlug: "quality-six-sigma",
    reason: "süreç varyasyonu / maliyet sapması",
  },
] as const satisfies readonly FreeToPremiumWave2Item[];

export const FORCE_FREE_SIMPLE_FINANCE_SLUGS = [
  "vat-calculator",
  "discount-calculator",
  "percentage-calculator",
  "interest-calculator",
] as const;

/** Title → category slug (canonical seed slugs only). */
export const FREE_TO_PREMIUM_CATEGORY_OVERRIDES: Readonly<
  Record<FreeToPremiumMigrationTitle, GlobalToolCategorySlug>
> = {
  "Kira mı Satın Alma mı Karşılaştırması": "finance-sales-working-capital",
  "İç Verim Oranı (IRR) Hesaplama": "finance-sales-working-capital",
  "OEE Hesaplayıcı": "lean-production",
  "İstatistiksel Proses Kontrol (SPC) Limit Hesabı": "quality-six-sigma",
  "Altı Sigma – DPMO – Sigma Seviyesi Çevirici": "quality-six-sigma",
  "Doğrusal Regresyon Hesaplayıcı": "quality-six-sigma",
  "Örneklem Büyüklüğü Hesaplayıcı": "quality-six-sigma",
  "Lazer Kesim Süresi Kontrolü": "metal-plastics-forming",
  "3B Baskı Maliyet Kontrolü": "cnc-additive-manufacturing",
  "Rüzgar Türbini Yaklaşık Üretim Hesabı": "sustainability-resource-esg",
  "CBAM Maruziyet Hızlı Kontrol": "sustainability-resource-esg",
  "İşveren Maaş Maliyeti Hesaplayıcı": "workforce-hr",
  "Gelir Vergisi Dilimleri Hesaplama": "finance-sales-working-capital",
  "SGK Prim Hesaplama (İşçi + İşveren)": "workforce-hr",
  "Stopaj Hesaplama (Kira, Serbest Meslek)": "finance-sales-working-capital",
  "KDV Tevkifatı Hesaplama": "finance-sales-working-capital",
  "İş Kazası Maliyeti (Gün Kaybı) Hesaplama": "hse-ergonomics",
  "Personel Devamsızlık Maliyeti Hesaplama": "workforce-hr",
  "Çek – Senet Vade Kırma Maliyeti Hesabı": "finance-sales-working-capital",
  "Kredi Erken Kapama Cezası Hesaplama": "finance-sales-working-capital",
  "Leasing – Kiralama Maliyet Karşılaştırma": "finance-sales-working-capital",
  "Makine Ekonomik Ömrü – Hurda Değer Hesabı": "maintenance-reliability",
  "Nakit Akışı (Basit Günlük/Haftalık) Panosu": "finance-sales-working-capital",
  "Geri Dönüşüm Gelir – Maliyet Hesabı": "sustainability-resource-esg",
  "Yangın Merdiveni – Kaçış Yolu Genişliği Hesabı": "hse-ergonomics",
  "İş Sağlığı ve Güvenliği Ceza Hesaplama": "hse-ergonomics",
  "Çevre – Atık Beyanı Maliyet Hesaplama": "sustainability-resource-esg",
  "Basınçlı Kap Cidar Kalınlığı Hesabı": "mechanical-hvac-energy-loss",
  "Kaynak Prosedürü (WPS) Ön Isıtma Sıcaklığı Hesabı": "mechanical-hvac-energy-loss",
  "Yay (Helisel) Kuvvet – Uzama Hesabı": "mechanical-hvac-energy-loss",
  "Mil – Aks Çapı Hesabı (Eğilme – Burulma)": "mechanical-hvac-energy-loss",
  "Kaynaklı Bağlantı (Köşe – Küt) Mukavemet Hesabı": "mechanical-hvac-energy-loss",
  "Bulonlu Bağlantı (Kesme – Ezilme) Hesabı": "mechanical-hvac-energy-loss",
  "Rulman Ömür Hesabı (L10)": "maintenance-reliability",
  "Hidrolik Pompa Gücü Hesaplama": "mechanical-hvac-energy-loss",
  "Pnömatik Silindir Kuvvet Hesabı": "mechanical-hvac-energy-loss",
  "Kompresör Debisi – Tank Hacmi Hesabı": "mechanical-hvac-energy-loss",
  "Gerilim Düşümü Hesaplama": "electrical-power-systems",
  "Kablo Kesiti (mm²) Seçim Hesaplama": "electrical-power-systems",
  "Jeneratör Kapasitesi Seçim Hesaplama": "electrical-power-systems",
  "Klima BTU Seçim Hesaplama": "mechanical-hvac-energy-loss",
  "Karbon Ayak İzi Hızlı Kontrol": "sustainability-resource-esg",
  "Yakıt Emisyon Hesaplayıcı": "sustainability-resource-esg",
  "Konteyner Yükleme Kapasitesi (TEU) Hesabı": "procurement-supply-chain",
  "Tır – Kamyon Yük Kapasitesi Hesaplama": "procurement-supply-chain",
  "Depo Raf – Palet Yerleşim Optimizasyonu": "procurement-supply-chain",
  "Araç Kira – Satın Alma Karşılaştırma": "procurement-supply-chain",
  "Forklift – Transpalet Kullanım Maliyeti": "procurement-supply-chain",
  "Paketleme Malzemesi (Streç, Koli) Sarfiyatı": "packaging-local-business",
  "İrsaliye – Fatura Adedi Başına Sevkiyat Maliyeti": "procurement-supply-chain",
  "Navlun Maliyeti Hesaplayıcı": "procurement-supply-chain",
};

export const FREE_TO_PREMIUM_KNOWN_SLUG_ALIASES: Readonly<Record<string, string>> = {
  "oee-calculator": "oee-calculator",
  "rent-vs-buy-calculator": "rent-vs-buy-calculator",
  "carbon-footprint-quick": "carbon-footprint-quick",
  "fuel-emission-calculator": "fuel-emission-calculator",
  "freight-cost-calculator": "freight-cost-calculator",
  "cbam-exposure-quick-check": "cbam-exposure-quick-check",
};
