import type { GlobalToolCategorySlug } from "@/lib/catalog/global-tool-category-taxonomy";

export const FREE_TO_PREMIUM_TITLE_LIST_TR = [
  "Kira mı Satın Alma mı Karşılaştırması",
  "İç Verim Oranı (IRR) Hesaplama",
  "OEE Hesaplayıcı",
  "İstatistiksel Proses Kontrol (SPC) Limit Hesabı",
  "Altı Sigma – DPMO – Sigma Seviyesi Çevirici",
  "Doğrusal Regresyon Hesaplayıcı",
  "Örneklem Büyüklüğü Hesaplayıcı",
  "Lazer Kesim Süresi Kontrolü",
  "3B Baskı Maliyet Kontrolü",
  "Rüzgar Türbini Yaklaşık Üretim Hesabı",
  "CBAM Maruziyet Hızlı Kontrol",
  "İşveren Maaş Maliyeti Hesaplayıcı",
  "Gelir Vergisi Dilimleri Hesaplama",
  "SGK Prim Hesaplama (İşçi + İşveren)",
  "Stopaj Hesaplama (Kira, Serbest Meslek)",
  "KDV Tevkifatı Hesaplama",
  "İş Kazası Maliyeti (Gün Kaybı) Hesaplama",
  "Personel Devamsızlık Maliyeti Hesaplama",
  "Çek – Senet Vade Kırma Maliyeti Hesabı",
  "Kredi Erken Kapama Cezası Hesaplama",
  "Leasing – Kiralama Maliyet Karşılaştırma",
  "Makine Ekonomik Ömrü – Hurda Değer Hesabı",
  "Nakit Akışı (Basit Günlük/Haftalık) Panosu",
  "Geri Dönüşüm Gelir – Maliyet Hesabı",
  "Yangın Merdiveni – Kaçış Yolu Genişliği Hesabı",
  "İş Sağlığı ve Güvenliği Ceza Hesaplama",
  "Çevre – Atık Beyanı Maliyet Hesaplama",
  "Basınçlı Kap Cidar Kalınlığı Hesabı",
  "Kaynak Prosedürü (WPS) Ön Isıtma Sıcaklığı Hesabı",
  "Yay (Helisel) Kuvvet – Uzama Hesabı",
  "Mil – Aks Çapı Hesabı (Eğilme – Burulma)",
  "Kaynaklı Bağlantı (Köşe – Küt) Mukavemet Hesabı",
  "Bulonlu Bağlantı (Kesme – Ezilme) Hesabı",
  "Rulman Ömür Hesabı (L10)",
  "Hidrolik Pompa Gücü Hesaplama",
  "Pnömatik Silindir Kuvvet Hesabı",
  "Kompresör Debisi – Tank Hacmi Hesabı",
  "Gerilim Düşümü Hesaplama",
  "Kablo Kesiti (mm²) Seçim Hesaplama",
  "Jeneratör Kapasitesi Seçim Hesaplama",
  "Klima BTU Seçim Hesaplama",
  "Karbon Ayak İzi Hızlı Kontrol",
  "Yakıt Emisyon Hesaplayıcı",
  "Konteyner Yükleme Kapasitesi (TEU) Hesabı",
  "Tır – Kamyon Yük Kapasitesi Hesaplama",
  "Depo Raf – Palet Yerleşim Optimizasyonu",
  "Araç Kira – Satın Alma Karşılaştırma",
  "Forklift – Transpalet Kullanım Maliyeti",
  "Paketleme Malzemesi (Streç, Koli) Sarfiyatı",
  "İrsaliye – Fatura Adedi Başına Sevkiyat Maliyeti",
  "Navlun Maliyeti Hesaplayıcı",
] as const;

export type FreeToPremiumMigrationTitle = (typeof FREE_TO_PREMIUM_TITLE_LIST_TR)[number];

/** Legacy slug aliases from migration spec → canonical seed category slugs. */
export const FREE_TO_PREMIUM_CATEGORY_SLUG_ALIASES: Readonly<
  Record<string, GlobalToolCategorySlug>
> = {
  "sheet-metal-forming": "metal-plastics-forming",
  "workforce-shift-hr": "workforce-hr",
  "safety-ergonomics-risk": "hse-ergonomics",
  "electrical-panel-power": "electrical-power-systems",
  "supply-logistics-procurement": "procurement-supply-chain",
};

/** Title → category slug (canonical seed slugs only). */
export const FREE_TO_PREMIUM_CATEGORY_OVERRIDES: Readonly<
  Record<FreeToPremiumMigrationTitle, GlobalToolCategorySlug>
> = {
  "Kira mı Satın Alma mı Karşılaştırması": "finance-sales-working-capital",
  "İç Verim Oranı (IRR) Hesaplama": "finance-sales-working-capital",
  "OEE Hesaplayıcı": "lean-production",
  "İstatistiksel Proses Kontrol (SPC) Limit Hesabı": "quality-six-sigma",
  "Altı Sigma – DPMO – Sigma Seviyesi Çevirici": "quality-six-sigma",
  "Doğrusal Regresyon Hesaplayıcı": "quality-six-sigma",
  "Örneklem Büyüklüğü Hesaplayıcı": "quality-six-sigma",
  "Lazer Kesim Süresi Kontrolü": "metal-plastics-forming",
  "3B Baskı Maliyet Kontrolü": "cnc-additive-manufacturing",
  "Rüzgar Türbini Yaklaşık Üretim Hesabı": "sustainability-resource-esg",
  "CBAM Maruziyet Hızlı Kontrol": "sustainability-resource-esg",
  "İşveren Maaş Maliyeti Hesaplayıcı": "workforce-hr",
  "Gelir Vergisi Dilimleri Hesaplama": "finance-sales-working-capital",
  "SGK Prim Hesaplama (İşçi + İşveren)": "workforce-hr",
  "Stopaj Hesaplama (Kira, Serbest Meslek)": "finance-sales-working-capital",
  "KDV Tevkifatı Hesaplama": "finance-sales-working-capital",
  "İş Kazası Maliyeti (Gün Kaybı) Hesaplama": "hse-ergonomics",
  "Personel Devamsızlık Maliyeti Hesaplama": "workforce-hr",
  "Çek – Senet Vade Kırma Maliyeti Hesabı": "finance-sales-working-capital",
  "Kredi Erken Kapama Cezası Hesaplama": "finance-sales-working-capital",
  "Leasing – Kiralama Maliyet Karşılaştırma": "finance-sales-working-capital",
  "Makine Ekonomik Ömrü – Hurda Değer Hesabı": "maintenance-reliability",
  "Nakit Akışı (Basit Günlük/Haftalık) Panosu": "finance-sales-working-capital",
  "Geri Dönüşüm Gelir – Maliyet Hesabı": "sustainability-resource-esg",
  "Yangın Merdiveni – Kaçış Yolu Genişliği Hesabı": "hse-ergonomics",
  "İş Sağlığı ve Güvenliği Ceza Hesaplama": "hse-ergonomics",
  "Çevre – Atık Beyanı Maliyet Hesaplama": "sustainability-resource-esg",
  "Basınçlı Kap Cidar Kalınlığı Hesabı": "mechanical-hvac-energy-loss",
  "Kaynak Prosedürü (WPS) Ön Isıtma Sıcaklığı Hesabı": "mechanical-hvac-energy-loss",
  "Yay (Helisel) Kuvvet – Uzama Hesabı": "mechanical-hvac-energy-loss",
  "Mil – Aks Çapı Hesabı (Eğilme – Burulma)": "mechanical-hvac-energy-loss",
  "Kaynaklı Bağlantı (Köşe – Küt) Mukavemet Hesabı": "mechanical-hvac-energy-loss",
  "Bulonlu Bağlantı (Kesme – Ezilme) Hesabı": "mechanical-hvac-energy-loss",
  "Rulman Ömür Hesabı (L10)": "maintenance-reliability",
  "Hidrolik Pompa Gücü Hesaplama": "mechanical-hvac-energy-loss",
  "Pnömatik Silindir Kuvvet Hesabı": "mechanical-hvac-energy-loss",
  "Kompresör Debisi – Tank Hacmi Hesabı": "mechanical-hvac-energy-loss",
  "Gerilim Düşümü Hesaplama": "electrical-power-systems",
  "Kablo Kesiti (mm²) Seçim Hesaplama": "electrical-power-systems",
  "Jeneratör Kapasitesi Seçim Hesaplama": "electrical-power-systems",
  "Klima BTU Seçim Hesaplama": "mechanical-hvac-energy-loss",
  "Karbon Ayak İzi Hızlı Kontrol": "sustainability-resource-esg",
  "Yakıt Emisyon Hesaplayıcı": "sustainability-resource-esg",
  "Konteyner Yükleme Kapasitesi (TEU) Hesabı": "procurement-supply-chain",
  "Tır – Kamyon Yük Kapasitesi Hesaplama": "procurement-supply-chain",
  "Depo Raf – Palet Yerleşim Optimizasyonu": "procurement-supply-chain",
  "Araç Kira – Satın Alma Karşılaştırma": "procurement-supply-chain",
  "Forklift – Transpalet Kullanım Maliyeti": "procurement-supply-chain",
  "Paketleme Malzemesi (Streç, Koli) Sarfiyatı": "packaging-local-business",
  "İrsaliye – Fatura Adedi Başına Sevkiyat Maliyeti": "procurement-supply-chain",
  "Navlun Maliyeti Hesaplayıcı": "procurement-supply-chain",
};

export const FREE_TO_PREMIUM_KNOWN_SLUG_ALIASES: Readonly<Record<string, string>> = {
  "oee-calculator": "oee-calculator",
  "rent-vs-buy-calculator": "rent-vs-buy-calculator",
  "carbon-footprint-quick": "carbon-footprint-quick",
  "fuel-emission-calculator": "fuel-emission-calculator",
  "freight-cost-calculator": "freight-cost-calculator",
  "cbam-exposure-quick-check": "cbam-exposure-quick-check",
};
