/* eslint-disable */
// Auto-generated TypeScript wrapper for JSON bundle (Vercel webpack compat).
// Generated by: run `node scripts/regenerate-ts-json-wrappers.mjs` after updating the .json source.
import raw from "./generated-tool-titles-i18n.generated.json";
export default raw;
