/**
 * Strategic roadmap data - generated by scripts/generate-strategic-roadmap-data.mjs
 * Do not edit manually; regenerate from scripts/data/strategic-roadmap-source.json
 */

export type Locale = "en" | "tr" | "de" | "fr" | "es" | "ar";

export type RoadmapStatus = "live" | "beta" | "planned";

export type StrategicPremiumCalculator = {
  id: string;
  slug: string;
  phase: 1 | 2 | 3 | 4;
  score: number;
  status: RoadmapStatus;
  categoryId: string;
  title: Record<Locale, string>;
  shortDescription: Record<Locale, string>;
  pain: Record<Locale, string>;
  publicPromise: Record<Locale, string>;
  internalSourceNote: string;
  mappedLiveSlug?: string;
};

export const STRATEGIC_PREMIUM_CALCULATORS: readonly StrategicPremiumCalculator[] = [];
