/**
 * Strategic roadmap data — generated by scripts/generate-strategic-roadmap-data.mjs
 * Do not edit manually; regenerate from scripts/data/strategic-roadmap-source.json
 */

export type Locale = "en" | "tr" | "de" | "fr" | "es" | "ar";

export type RoadmapStatus = "live" | "beta" | "planned";

export type StrategicPremiumCalculator = {
  id: string;
  slug: string;
  phase: 1 | 2 | 3 | 4;
  score: number;
  status: RoadmapStatus;
  categoryId: string;
  title: Record<Locale, string>;
  shortDescription: Record<Locale, string>;
  pain: Record<Locale, string>;
  publicPromise: Record<Locale, string>;
  internalSourceNote: string;
  mappedLiveSlug?: string;
};

export const STRATEGIC_PREMIUM_CALCULATORS: readonly StrategicPremiumCalculator[] = [
  {
    "id": "sp-001",
    "slug": "quote-price-profit-margin-calculator",
    "phase": 1,
    "score": 9.7,
    "status": "live",
    "categoryId": "cost-margin",
    "title": {
      "en": "Quote Price and Profit Margin Calculator",
      "tr": "Teklif Fiyatı ve Kâr Marjı Hesaplayıcı",
      "de": "Angebotspreis- und Gewinnmargen-Rechner",
      "fr": "Calculateur de prix de devis et marge bénéficiaire",
      "es": "Calculadora de precio de cotización y margen de beneficio",
      "ar": "حاسبة سعر العرض وهامش الربح"
    },
    "shortDescription": {
      "en": "Calculate quote price, margin, scrap, setup, payment terms and energy in one screen.",
      "tr": "Tekliflerde maliyet, fire, vade, enerji ve marj kalemlerini aynı ekranda hesaplayın.",
      "de": "Berechnen Sie Angebotspreis, Marge, Ausschuss, Rüstzeit, Zahlungsziel und Energie auf einem Bildschirm.",
      "fr": "Calculez prix, marge, rebuts, réglage, délais de paiement et énergie sur un seul écran.",
      "es": "Calcule precio, margen, merma, setup, plazo de pago y energía en una sola pantalla.",
      "ar": "احسب سعر العرض والهامش والهدر والإعداد وشروط الدفع والطاقة في شاشة واحدة."
    },
    "pain": {
      "en": "Quotes often omit scrap, setup time, payment-term cost and utility load before margin is set.",
      "tr": "Tekliflerde fire, kurulum süresi, vade maliyeti ve enerji yükü sıkça atlanır; marj buna göre incelir.",
      "de": "Angebote lassen oft Ausschuss, Rüstzeit, Zahlungszielkosten und Energie außer Acht.",
      "fr": "Les devis omettent souvent rebuts, temps de réglage, coût de délai et charge énergétique.",
      "es": "Las cotizaciones suelen omitir merma, setup, coste de plazo y carga energética.",
      "ar": "غالبًا ما تُهمَل الهدر ووقت الإعداد وتكلفة آجال الدفع والحمل الطاقي في العروض."
    },
    "publicPromise": {
      "en": "Structure every quote with the cost lines teams forget before margin is locked.",
      "tr": "Marj kilitlenmeden önce ekiplerin unuttuğu maliyet kalemlerini teklife ekleyin.",
      "de": "Strukturieren Sie jedes Angebot mit vergessenen Kostenpositionen vor der Margenfixierung.",
      "fr": "Structurez chaque devis avec les postes de coût oubliés avant de figer la marge.",
      "es": "Estructure cada cotización con las partidas olvidadas antes de fijar el margen.",
      "ar": "نظّم كل عرض بالبنود التي تُنسى قبل تثبيت الهامش."
    },
    "internalSourceNote": "Strategic report tool 1 — quote margin; safe copy replaces aggressive margin guarantee.",
    "mappedLiveSlug": "quote-price-profit-margin-calculator"
  },
  {
    "id": "sp-002",
    "slug": "shop-rate-hourly-cost-calculator",
    "phase": 1,
    "score": 9.2,
    "status": "live",
    "categoryId": "operations-oee",
    "title": {
      "en": "Machine Hour Rate Calculator",
      "tr": "Makine Saat Ücreti Hesaplayıcı",
      "de": "Maschinenstundensatz-Rechner",
      "fr": "Calculateur de taux horaire machine",
      "es": "Calculadora de tarifa horaria de máquina",
      "ar": "حاسبة أجر الساعة للآلة"
    },
    "shortDescription": {
      "en": "See true machine hourly cost with depreciation, energy, maintenance and floor-space share.",
      "tr": "Makinenin saatlik maliyetini amortisman, enerji, bakım ve alan payı ile birlikte görün.",
      "de": "Sehen Sie den echten Maschinenstundensatz inkl. Abschreibung, Energie, Wartung und Flächenanteil.",
      "fr": "Voyez le coût horaire réel avec amortissement, énergie, maintenance et part de surface.",
      "es": "Vea el coste horario real con amortización, energía, mantenimiento y espacio.",
      "ar": "اعرض التكلفة الساعية الحقيقية مع الإهلاك والطاقة والصيانة وحصة المساحة."
    },
    "pain": {
      "en": "Most shops estimate shop rate from labor and power only, understating true hourly burden.",
      "tr": "Atölyelerin çoğu shop rate'i yalnızca işçilik ve elektrikle hesaplar; gerçek yük eksik kalır.",
      "de": "Die meisten Werkstätten schätzen den Stundensatz nur aus Arbeit und Strom.",
      "fr": "La plupart des ateliers estiment le taux horaire avec main-d'œuvre et électricité seulement.",
      "es": "La mayoría estima la tarifa horaria solo con mano de obra y electricidad.",
      "ar": "تقدّر معظم الورش التكلفة الساعية من العمالة والكهرباء فقط."
    },
    "publicPromise": {
      "en": "Build a defensible shop-rate profile in minutes instead of guessing from power bills alone.",
      "tr": "Shop rate profilini dakikalar içinde, yalnızca elektrik faturasından tahmin etmek yerine oluşturun.",
      "de": "Erstellen Sie in Minuten ein belastbares Shop-Rate-Profil statt zu schätzen.",
      "fr": "Construisez un profil de taux horaire défendable en quelques minutes.",
      "es": "Construya un perfil de tarifa horaria defendible en minutos.",
      "ar": "أنشئ ملف تكلفة ساعية موثوقًا في دقائق بدل التخمين."
    },
    "internalSourceNote": "Strategic report tool 2 — shop rate.",
    "mappedLiveSlug": "machine-hour-rate-calculator"
  },
  {
    "id": "sp-003",
    "slug": "break-even-safety-margin-calculator",
    "phase": 1,
    "score": 9.1,
    "status": "live",
    "categoryId": "finance-hr",
    "title": {
      "en": "Break-Even and Safety Margin Calculator",
      "tr": "Başabaş Noktası ve Güvenlik Marjı Hesaplayıcı",
      "de": "Break-even- und Sicherheitsmargen-Rechner",
      "fr": "Calculateur de seuil de rentabilité et marge de sécurité",
      "es": "Calculadora de punto de equilibrio y margen de seguridad",
      "ar": "حاسبة نقطة التعادل وهامش الأمان"
    },
    "shortDescription": {
      "en": "Calculate break-even point and safety margin on one screen.",
      "tr": "Başabaş noktası ve güvenlik marjını tek ekranda hesaplayın.",
      "de": "Berechnen Sie Break-even und Sicherheitsmarge auf einem Bildschirm.",
      "fr": "Calculez seuil de rentabilité et marge de sécurité sur un écran.",
      "es": "Calcule punto de equilibrio y margen de seguridad en una pantalla.",
      "ar": "احسب نقطة التعادل وهامش الأمان في شاشة واحدة."
    },
    "pain": {
      "en": "Owners often learn profit or loss only after month-end statements arrive.",
      "tr": "İşletmeler kâr/zararı çoğu zaman ay sonu tabloları gelince öğrenir.",
      "de": "Unternehmer erfahren Gewinn oder Verlust oft erst nach Monatsabschluss.",
      "fr": "Les dirigeants découvrent profit ou perte seulement en fin de mois.",
      "es": "Los dueños conocen ganancia o pérdida solo al cierre mensual.",
      "ar": "يتعرّف أصحاب الأعمال الربح أو الخسارة غالبًا بعد إغلاق الشهر."
    },
    "publicPromise": {
      "en": "Track fixed and variable costs against revenue before the month closes.",
      "tr": "Ay kapanmadan sabit ve değişken maliyetleri ciroya göre takip edin.",
      "de": "Verfolgen Sie Fix- und variable Kosten zum Umsatz vor Monatsende.",
      "fr": "Suivez coûts fixes et variables face au chiffre d'affaires avant la clôture.",
      "es": "Siga costes fijos y variables frente a ingresos antes del cierre.",
      "ar": "تتبّع التكاليف الثابتة والمتغيرة مقابل الإيراد قبل إغلاق الشهر."
    },
    "internalSourceNote": "Strategic report tool 3 — break-even dashboard.",
    "mappedLiveSlug": "break-even-calculator"
  },
  {
    "id": "sp-004",
    "slug": "auto-repair-parts-labor-quote-calculator",
    "phase": 1,
    "score": 9,
    "status": "live",
    "categoryId": "cost-margin",
    "title": {
      "en": "Auto Repair Parts and Labor Quote Calculator",
      "tr": "Tamirhane Parça ve İşçilik Teklif Hesaplayıcı",
      "de": "Kfz-Teile- und Arbeitsangebots-Rechner",
      "fr": "Calculateur de devis pièces et main-d'œuvre garage",
      "es": "Calculadora de cotización de piezas y mano de obra de taller",
      "ar": "حاسبة عرض قطع الغيار والعمالة للإصلاح"
    },
    "shortDescription": {
      "en": "Standardize parts and labor lines for repair-shop quotes on mobile.",
      "tr": "Tamirhane tekliflerinde parça ve işçilik satırlarını mobilde standartlaştırın.",
      "de": "Standardisieren Sie Teile- und Arbeitszeilen für Werkstattangebote mobil.",
      "fr": "Standardisez pièces et main-d'œuvre pour devis d'atelier sur mobile.",
      "es": "Estandarice piezas y mano de obra en cotizaciones de taller móvil.",
      "ar": "وحّد بنود القطع والعمالة لعروض الورش على الجوال."
    },
    "pain": {
      "en": "Repair quotes vary by technician and format, making price consistency hard.",
      "tr": "Tamir teklifleri ustaya göre değişir; fiyat tutarlılığı zorlaşır.",
      "de": "Reparaturangebote variieren je Techniker und Format.",
      "fr": "Les devis de réparation varient selon le technicien.",
      "es": "Las cotizaciones de reparación varían por técnico.",
      "ar": "تختلف عروض الإصلاح حسب الفني والنموذج."
    },
    "publicPromise": {
      "en": "Issue repeatable repair quotes with shared labor-time and parts structure.",
      "tr": "Ortak işçilik süresi ve parça yapısıyla tekrarlanabilir tamir teklifleri verin.",
      "de": "Erstellen Sie wiederholbare Reparaturangebote mit gemeinsamer Struktur.",
      "fr": "Émettez des devis répétables avec structure commune.",
      "es": "Emite cotizaciones repetibles con estructura común.",
      "ar": "قدّم عروض إصلاح مت repeatable ببنية مشتركة."
    },
    "internalSourceNote": "Strategic report tool 4 — auto repair quote; planned premium build.",
    "mappedLiveSlug": "auto-repair-parts-labor-quote-calculator"
  },
  {
    "id": "sp-005",
    "slug": "cbam-unit-product-carbon-footprint-calculator",
    "phase": 1,
    "score": 8.8,
    "status": "live",
    "categoryId": "energy-carbon",
    "title": {
      "en": "CBAM Unit Product Carbon Footprint Calculator",
      "tr": "SKDM Birim Ürün Karbon Ayak İzi Hesaplayıcı",
      "de": "CBAM-Produkt-CO₂-Fußabdruck-Rechner",
      "fr": "Calculateur d'empreinte carbone unitaire CBAM",
      "es": "Calculadora de huella de carbono unitaria CBAM",
      "ar": "حاسبة البصمة الكarbonية للوحدة CBAM"
    },
    "shortDescription": {
      "en": "Estimate embedded carbon per product unit for export compliance workflows.",
      "tr": "İhracat uyum süreçleri için birim ürün gömülü karbonunu hesaplayın.",
      "de": "Schätzen Sie eingebetteten Kohlenstoff pro Produkteinheit für Export-Compliance.",
      "fr": "Estimez le carbone incorporé par unité pour la conformité export.",
      "es": "Estime carbono incorporado por unidad para cumplimiento exportador.",
      "ar": "قدّر الكربون المدمج لكل وحدة منتج للامتثال التصديري."
    },
    "pain": {
      "en": "Exporters need product-level carbon evidence but lack affordable tooling.",
      "tr": "İhracatçılar ürün bazlı karbon kanıtına ihtiyaç duyar; uygun araç azdır.",
      "de": "Exporteure brauchen Produkt-Kohlenstoffnachweise ohne teure Berater.",
      "fr": "Les exportateurs manquent d'outils abordables pour le carbone produit.",
      "es": "Exportadores carecen de herramientas asequibles de carbono por producto.",
      "ar": "يحتاج المصدرون أدوات ميسورة لكربون المنتج."
    },
    "publicPromise": {
      "en": "Document unit product carbon with traceable factors before customs review.",
      "tr": "Gümrük incelemesinden önce izlenebilir faktörlerle birim ürün karbonunu belgeleyin.",
      "de": "Dokumentieren Sie Produkt-Kohlenstoff mit nachvollziehbaren Faktoren vor Zollprüfung.",
      "fr": "Documentez le carbone produit avec facteurs traçables avant douane.",
      "es": "Documente carbono por unidad con factores trazables antes de aduana.",
      "ar": "وثّق كربون المنتج بعوامل قابلة للتتبع قبل الجمارك."
    },
    "internalSourceNote": "Strategic report tool 5 — CBAM unit carbon; mapped to free CBAM quick check.",
    "mappedLiveSlug": "cbam-exposure-quick-check"
  },
  {
    "id": "sp-006",
    "slug": "oee-equipment-effectiveness-calculator",
    "phase": 1,
    "score": 8.8,
    "status": "live",
    "categoryId": "operations-oee",
    "title": {
      "en": "OEE Calculator",
      "tr": "OEE Hesaplayıcı",
      "de": "OEE-Rechner",
      "fr": "Calculateur OEE",
      "es": "Calculadora OEE",
      "ar": "حاسبة OEE"
    },
    "shortDescription": {
      "en": "Calculate OEE from availability, performance and quality inputs.",
      "tr": "Uygunluk, performans ve kalite girdileriyle OEE hesaplayın.",
      "de": "Berechnen Sie OEE aus Verfügbarkeit, Leistung und Qualität.",
      "fr": "Calculez l'OEE à partir de disponibilité, performance et qualité.",
      "es": "Calcule OEE con disponibilidad, rendimiento y calidad.",
      "ar": "احسب OEE من التوفر والأداء والجودة."
    },
    "pain": {
      "en": "Without OEE tracking, chronic downtime and quality loss stay invisible.",
      "tr": "OEE takibi olmadan kronik duruş ve kalite kaybı görünmez kalır.",
      "de": "Ohne OEE bleiben Stillstände und Qualitätsverlust unsichtbar.",
      "fr": "Sans OEE, arrêts chroniques et pertes qualité restent invisibles.",
      "es": "Sin OEE, paradas crónicas y pérdida de calidad permanecen ocultas.",
      "ar": "بدون OEE تبقى التوقفات المزمنة وخسائر الجودة مخفية."
    },
    "publicPromise": {
      "en": "Enter three shift numbers and see equipment effectiveness and loss split.",
      "tr": "Üç vardiya değeri girin; ekipman etkinliği ve kayıp dağılımını görün.",
      "de": "Geben Sie drei Schichtwerte ein und sehen Sie Effektivität und Verluste.",
      "fr": "Saisissez trois valeurs de poste et voyez efficacité et répartition des pertes.",
      "es": "Introduce tres valores de turno y ve eficacia y pérdidas.",
      "ar": "أدخل ثلاث قيم نوبة واعرض الفعالية وتوزيع الخسائر."
    },
    "internalSourceNote": "Strategic report tool 6 — OEE; live free calculator mapped.",
    "mappedLiveSlug": "oee-calculator"
  },
  {
    "id": "sp-007",
    "slug": "compressor-leak-cost-calculator",
    "phase": 1,
    "score": 8.7,
    "status": "live",
    "categoryId": "energy-carbon",
    "title": {
      "en": "Compressor Leak Cost Calculator",
      "tr": "Kompresör Kaçağı Maliyet Hesaplayıcı",
      "de": "Kompressor-Leckkosten-Rechner",
      "fr": "Calculateur de coût de fuite compresseur",
      "es": "Calculadora de coste de fuga de compresor",
      "ar": "حاسبة تكلفة تسرب الضاغط"
    },
    "shortDescription": {
      "en": "Estimate annual cost of compressed-air leaks from orifice, pressure and runtime.",
      "tr": "Delik çapı, basınç ve çalışma süresinden basınçlı hava kaçağı yıllık maliyetini tahmin edin.",
      "de": "Schätzen Sie jährliche Druckluftleckagekosten aus Öffnung, Druck und Laufzeit.",
      "fr": "Estimez le coût annuel des fuites d'air comprimé.",
      "es": "Estime el coste anual de fugas de aire comprimido.",
      "ar": "قدّر التكلفة السنوية لتسربات الهواء المضغوط."
    },
    "pain": {
      "en": "Compressed-air leaks are rarely quantified even though they inflate utility bills.",
      "tr": "Basınçlı hava kaçakları faturayı şişirir ama nadiren sayısallaştırılır.",
      "de": "Druckluftlecks werden selten beziffert, obwohl sie Kosten erhöhen.",
      "fr": "Les fuites d'air comprimé sont rarement chiffrées.",
      "es": "Las fugas de aire comprimido rara vez se cuantifican.",
      "ar": "نادرًا ما تُ quantified تسربات الهواء المضغوط."
    },
    "publicPromise": {
      "en": "Turn leak size and pressure into a yearly cost figure maintenance can act on.",
      "tr": "Kaçak boyutu ve basıncı bakımın aksiyon alabileceği yıllık maliyete çevirin.",
      "de": "Wandeln Sie Leckgröße und Druck in jährliche Kosten für die Wartung um.",
      "fr": "Transformez taille de fuite et pression en coût annuel actionnable.",
      "es": "Convierta tamaño de fuga y presión en coste anual accionable.",
      "ar": "حوّل حجم التسرب والضغط إلى تكلفة سنوية قابلة للتنفيذ."
    },
    "internalSourceNote": "Strategic report tool 7 — compressor leak cost.",
    "mappedLiveSlug": "compressor-energy-cost-calculator"
  },
  {
    "id": "sp-008",
    "slug": "employee-total-cost-calculator",
    "phase": 2,
    "score": 8.5,
    "status": "live",
    "categoryId": "finance-hr",
    "title": {
      "en": "Employee Total Cost Calculator",
      "tr": "Personel Tam Maliyet Hesaplayıcı",
      "de": "Personalkosten-Gesamtrechner",
      "fr": "Calculateur de coût total employé",
      "es": "Calculadora de coste total del empleado",
      "ar": "حاسبة التكلفة الكاملة للموظف"
    },
    "shortDescription": {
      "en": "Calculate full employer cost beyond net salary including SGK and benefits.",
      "tr": "Net maaşın ötesinde SGK ve yan haklarla işverenin tam personel maliyetini hesaplayın.",
      "de": "Berechnen Sie volle Arbeitgeberkosten über Nettogehalt inkl. Sozialabgaben.",
      "fr": "Calculez le coût employeur total au-delà du salaire net.",
      "es": "Calcule el coste total del empleador más allá del salario neto.",
      "ar": "احسب التكلفة الكاملة للEmployer beyond net salary."
    },
    "pain": {
      "en": "Hiring and pricing decisions often use net pay instead of loaded employer cost.",
      "tr": "İşe alım ve fiyatlama kararlarında net maaş kullanılır; tam maliyet eksik kalır.",
      "de": "Einstellungsentscheidungen nutzen oft Netto statt voller Arbeitgeberkosten.",
      "fr": "Les décisions d'embauche utilisent souvent le net au lieu du coût chargé.",
      "es": "Las decisiones de contratación usan a menudo el neto en lugar del coste total.",
      "ar": "قرارات التوظيف تستخدم غالبًا الصافي بدل التكلفة الكاملة."
    },
    "publicPromise": {
      "en": "See loaded headcount cost before hiring or quoting labor-heavy jobs.",
      "tr": "İş gücü yoğun iş teklif etmeden önce yüklenmiş personel maliyetini görün.",
      "de": "Sehen Sie belastete Personalkosten vor Einstellung oder Angebot.",
      "fr": "Voyez le coût personnel chargé avant embauche ou devis.",
      "es": "Vea el coste laboral cargado antes de contratar o cotizar.",
      "ar": "اعرض تكلفة الموظف المحمّلة قبل التوظيف أو العرض."
    },
    "internalSourceNote": "Strategic report tool 8 — total employee cost.",
    "mappedLiveSlug": "salary-cost-calculator"
  },
  {
    "id": "sp-009",
    "slug": "downtime-minute-cost-calculator",
    "phase": 2,
    "score": 8.4,
    "status": "live",
    "categoryId": "operations-oee",
    "title": {
      "en": "Downtime Minute Cost Calculator",
      "tr": "Duruş Dakika Maliyeti Hesaplayıcı",
      "de": "Stillstandsminutenkosten-Rechner",
      "fr": "Calculateur de coût minute d'arrêt",
      "es": "Calculadora de coste por minuto de parada",
      "ar": "حاسبة تكلفة دقيقة التوقف"
    },
    "shortDescription": {
      "en": "Convert downtime minutes into lost output value using shop rate.",
      "tr": "Shop rate ile duruş dakikalarını kayıp çıktı değerine çevirin.",
      "de": "Rechnen Sie Stillstandsminuten mit Shop-Rate in entgangenen Output um.",
      "fr": "Convertissez minutes d'arrêt en valeur perdue via taux horaire.",
      "es": "Convierta minutos de parada en valor perdido con tarifa horaria.",
      "ar": "حوّل دقائق التوقف إلى قيمة مفقودة باستخدام التكلفة الساعية."
    },
    "pain": {
      "en": "Maintenance budgets ignore opportunity cost of machines not producing.",
      "tr": "Bakım bütçeleri makinenin üretmediği fırsat maliyetini yok sayar.",
      "de": "Wartungsbudgets ignorieren entgangene Produktion.",
      "fr": "Les budgets maintenance ignorent le coût d'opportunité.",
      "es": "Los presupuestos de mantenimiento ignoran el coste de oportunidad.",
      "ar": "تتجاهل ميزانيات الصيانة تكلفة الفرصة."
    },
    "publicPromise": {
      "en": "Quantify downtime in currency to justify preventive maintenance spend.",
      "tr": "Önleyici bakım harcamasını gerekçelendirmek için duruşu para biriminde ölçün.",
      "de": "Quantifizieren Sie Stillstand in Währung für präventive Wartung.",
      "fr": "Quantifiez les arrêts en devise pour justifier la maintenance préventive.",
      "es": "Cuantifique paradas en moneda para justificar mantenimiento preventivo.",
      "ar": "قِس التوقف بالعملة لتبرير الصيانة الوقائية."
    },
    "internalSourceNote": "Strategic report tool 9 — downtime minute cost; planned.",
    "mappedLiveSlug": "downtime-minute-cost-calculator"
  },
  {
    "id": "sp-010",
    "slug": "product-customer-profitability-calculator",
    "phase": 2,
    "score": 8.3,
    "status": "live",
    "categoryId": "cost-margin",
    "title": {
      "en": "Product and Customer Profitability Calculator",
      "tr": "Ürün ve Müşteri Kârlılığı Hesaplayıcı",
      "de": "Produkt- und Kundenrentabilitäts-Rechner",
      "fr": "Calculateur de rentabilité produit et client",
      "es": "Calculadora de rentabilidad de producto y cliente",
      "ar": "حاسبة ربحية المنتج والعميل"
    },
    "shortDescription": {
      "en": "Compare product and customer contribution after hidden service costs.",
      "tr": "Gizli hizmet maliyetleri sonrası ürün ve müşteri katkısını karşılaştırın.",
      "de": "Vergleichen Sie Produkt- und Kundenbeitrag nach versteckten Servicekosten.",
      "fr": "Comparez contribution produit et client après coûts de service cachés.",
      "es": "Compare contribución de producto y cliente tras costes ocultos.",
      "ar": "قارن مساهمة المنتج والعميل بعد التكاليف الخفية."
    },
    "pain": {
      "en": "High-revenue customers can destroy margin through returns, delays and rework.",
      "tr": "Yüksek cirolu müşteriler iade, gecikme ve rework ile marjı eritebilir.",
      "de": "Umsatzstarke Kunden können Marge durch Retouren und Verzug zerstören.",
      "fr": "Les gros clients peuvent détruire la marge via retours et retards.",
      "es": "Clientes de alto ingreso pueden destruir margen con devoluciones.",
      "ar": "عملاء الإيرادات العالية قد يمحون الهامش بالمرتجعات."
    },
    "publicPromise": {
      "en": "Rank customers and SKUs by contribution instead of invoice total alone.",
      "tr": "Yalnızca fatura toplamı yerine müşteri ve SKU katkısına göre sıralayın.",
      "de": "Sortieren Sie nach Beitrag statt nur Rechnungssumme.",
      "fr": "Classez par contribution plutôt que total de facture seul.",
      "es": "Ordene por contribución en lugar de solo factura total.",
      "ar": "رتّب حسب المساهمة بدل إجمالي الفاتورة فقط."
    },
    "internalSourceNote": "Strategic report tool 10 — customer profitability.",
    "mappedLiveSlug": "profit-margin-calculator"
  },
  {
    "id": "sp-011",
    "slug": "inventory-carrying-cost-eoq-calculator",
    "phase": 2,
    "score": 7.9,
    "status": "live",
    "categoryId": "manufacturing-engineering",
    "title": {
      "en": "Inventory Carrying Cost and EOQ Calculator",
      "tr": "Stok Taşıma Maliyeti ve EOQ Hesaplayıcı",
      "de": "Lagerhaltungs- und EOQ-Rechner",
      "fr": "Calculateur de coût de stockage et EOQ",
      "es": "Calculadora de coste de inventario y EOQ",
      "ar": "حاسبة تكلفة حمل المخzón وEOQ"
    },
    "shortDescription": {
      "en": "Model inventory carrying cost and economic order quantity with sector scrap factors.",
      "tr": "Sektör fire katsayılarıyla stok taşıma maliyeti ve EOQ modelleyin.",
      "de": "Modellieren Sie Lagerhaltungskosten und EOQ mit Branchen-Ausschussfaktoren.",
      "fr": "Modélisez coût de stockage et EOQ avec facteurs de rebut sectoriels.",
      "es": "Modele coste de inventario y EOQ con factores de merma sectoriales.",
      "ar": "نمذج تكلفة حمل المخزون وEOQ بمعاملات الهدر القطاعية."
    },
    "pain": {
      "en": "Inventory cost is underestimated when only warehouse rent is counted.",
      "tr": "Stok maliyeti yalnızca depo kirası sayıldığında eksik kalır.",
      "de": "Lagerkosten werden unterschätzt wenn nur Miete gezählt wird.",
      "fr": "Le coût stock est sous-estimé si seul le loyer est compté.",
      "es": "El coste de inventario se subestima contando solo alquiler.",
      "ar": "يُUnderestimated تكلفة المخزون عند احتساب الإيجار فقط."
    },
    "publicPromise": {
      "en": "Expose holding cost and order size trade-offs before stock decisions.",
      "tr": "Stok kararlarından önce taşıma maliyeti ve sipariş büyüklüğü dengesini görün.",
      "de": "Zeigen Sie Haltungskosten vor Bestellentscheidungen.",
      "fr": "Exposez coût de détention avant décisions de stock.",
      "es": "Exponga coste de mantener stock antes de decidir.",
      "ar": "اعرض تكلفة الاحتفاظ قبل قرارات المخزون."
    },
    "internalSourceNote": "Strategic report tool 11 — inventory EOQ.",
    "mappedLiveSlug": "unit-cost-calculator"
  },
  {
    "id": "sp-012",
    "slug": "welded-bolted-connection-calculator",
    "phase": 2,
    "score": 7.7,
    "status": "live",
    "categoryId": "manufacturing-engineering",
    "title": {
      "en": "Welded and Bolted Connection Calculator",
      "tr": "Kaynaklı ve Bulonlu Bağlantı Hesaplayıcı",
      "de": "Schweiß- und Bolzenverbindungs-Rechner",
      "fr": "Calculateur de connexion soudée et boulonnée",
      "es": "Calculadora de conexión soldada y atornillada",
      "ar": "حاسبة الوصلات الملحومة والم bolted"
    },
    "shortDescription": {
      "en": "Check common welded and bolted connection capacity with workshop-friendly inputs.",
      "tr": "Atölye dostu girdilerle yaygın kaynaklı ve bulonlu bağlantı kapasitesini kontrol edin.",
      "de": "Prüfen Sie gängige Schweiß- und Bolzenverbindungen mit Werkstatt-Eingaben.",
      "fr": "Vérifiez connexions soudées et boulonnées avec entrées atelier.",
      "es": "Verifique conexiones soldadas y atornilladas con entradas de taller.",
      "ar": "تحقق من وصلات اللحام والبراغي بمدخلات الورشة."
    },
    "pain": {
      "en": "Connection sizing relies on guesswork without quick structural checks.",
      "tr": "Bağlantı boyutlandırması hızlı kontrol olmadan sezgiye kalır.",
      "de": "Verbindungsdimensionierung erfolgt ohne schnelle Prüfung per Bauchgefühl.",
      "fr": "Le dimensionnement repose sur l'intuition sans contrôle rapide.",
      "es": "El dimensionamiento depende de intuición sin chequeo rápido.",
      "ar": "يعتمد تحديد حجم الوصلات على الحدس."
    },
    "publicPromise": {
      "en": "Screen weld and bolt capacity for common shop connections in minutes.",
      "tr": "Yaygın atölye bağlantıları için kaynak ve bulon kapasitesini dakikalar içinde tarayın.",
      "de": "Prüfen Sie Schweiß- und Bolzenkapazität in Minuten.",
      "fr": "Filtrez capacité soudure et boulons en minutes.",
      "es": "Evalúe capacidad de soldadura y pernos en minutos.",
      "ar": "افحص سعة اللحام والبراغي في دقائق."
    },
    "internalSourceNote": "Strategic report tool 12 — weld/bolt; planned.",
    "mappedLiveSlug": "welded-bolted-connection-calculator"
  },
  {
    "id": "sp-013",
    "slug": "tolerance-stack-up-calculator",
    "phase": 2,
    "score": 7.7,
    "status": "live",
    "categoryId": "manufacturing-engineering",
    "title": {
      "en": "Tolerance Stack-Up Calculator",
      "tr": "Tolerans Yığılma Hesaplayıcı",
      "de": "Toleranzstack-up-Rechner",
      "fr": "Calculateur d'empilement de tolérances",
      "es": "Calculadora de acumulación de tolerancias",
      "ar": "حاسبة تراكم التسامح"
    },
    "shortDescription": {
      "en": "Run worst-case and RSS tolerance stack-up for assembly chains.",
      "tr": "Montaj zincirleri için en kötü durum ve RSS tolerans yığılmasını çalıştırın.",
      "de": "Führen Sie WC- und RSS-Toleranzstack-up für Montageketten aus.",
      "fr": "Exécutez empilement de tolérances WC et RSS pour assemblages.",
      "es": "Ejecute acumulación de tolerancias WC y RSS en ensamblajes.",
      "ar": "نفّذ تراكم التسامح WC وRSS لسلاسل التجميع."
    },
    "pain": {
      "en": "Fit issues often come from stacked tolerances without a documented chain check.",
      "tr": "Uyumsuzluklar çoğu zaman belgelenmiş zincir kontrolü olmadan birikir.",
      "de": "Passungsprobleme entstehen durch gestapelte Toleranzen ohne Dokumentation.",
      "fr": "Les problèmes d'ajustement viennent de tolérances empilées non documentées.",
      "es": "Problemas de ajuste vienen de tolerancias apiladas sin registro.",
      "ar": "مشاكل الملاءمة من tolerances متراكمة دون توثيق."
    },
    "publicPromise": {
      "en": "Identify which part drives assembly risk before scrap accumulates.",
      "tr": "Hurda birikmeden montaj riskini hangi parçanın taşıdığını görün.",
      "de": "Identifizieren Sie das risikoträchtige Teil vor Ausschuss.",
      "fr": "Identifiez la pièce à risque avant rebuts.",
      "es": "Identifique la pieza de riesgo antes de merma.",
      "ar": "حدّد القطعة المسببة للمخاطر قبل الهدر."
    },
    "internalSourceNote": "Strategic report tool 13 — tolerance stack-up.",
    "mappedLiveSlug": "tolerance-stack-up-calculator"
  },
  {
    "id": "sp-014",
    "slug": "bolt-tightening-torque-calculator",
    "phase": 3,
    "score": 7.4,
    "status": "live",
    "categoryId": "manufacturing-engineering",
    "title": {
      "en": "Bolt Tightening Torque Calculator",
      "tr": "Civata Sıkma Torku Hesaplayıcı",
      "de": "Anzugsdrehmoment-Rechner",
      "fr": "Calculateur de couple de serrage",
      "es": "Calculadora de par de apriete",
      "ar": "حاسبة عزم شد البرغي"
    },
    "shortDescription": {
      "en": "Calculate bolt tightening torque with friction and grade libraries.",
      "tr": "Sürtünme ve sınıf kütüphaneleriyle civata sıkma torkunu hesaplayın.",
      "de": "Berechnen Sie Anzugsdrehmoment mit Reibungs- und Gütebibliotheken.",
      "fr": "Calculez couple de serrage avec bibliothèques de frottement et classe.",
      "es": "Calcule par de apriete con bibliotecas de fricción y clase.",
      "ar": "احسب عزم شد البرغي بمكتبات الاحتكاك والدرجة."
    },
    "pain": {
      "en": "Critical fasteners are often tightened by feel instead of specified torque.",
      "tr": "Kritik bağlantılar çoğu zaman tork yerine hisle sıkılır.",
      "de": "Kritische Verbindungen werden oft nach Gefühl statt Drehmoment angezogen.",
      "fr": "Les fixations critiques sont souvent serrées au feeling.",
      "es": "Fijaciones críticas se aprietan a menudo a ojo.",
      "ar": "تُشد الوصلات الحرجة غالبًا بالحدس."
    },
    "publicPromise": {
      "en": "Set torque targets on mobile with grade and lubrication context.",
      "tr": "Sınıf ve yağlama bağlamıyla tork hedefini mobilde ayarlayın.",
      "de": "Setzen Sie Drehmomentziele mobil mit Güte und Schmierung.",
      "fr": "Définissez le couple cible sur mobile avec classe et lubrification.",
      "es": "Ajuste par de apriete en móvil con clase y lubricación.",
      "ar": "اضبط عزم الهدف على الجوال مع الدرجة والتزييت."
    },
    "internalSourceNote": "Strategic report tool 14 — bolt torque; planned.",
    "mappedLiveSlug": "bolt-tightening-torque-calculator"
  },
  {
    "id": "sp-015",
    "slug": "energy-savings-package-calculator",
    "phase": 3,
    "score": 7.4,
    "status": "live",
    "categoryId": "energy-carbon",
    "title": {
      "en": "Energy Savings Calculator",
      "tr": "Enerji Tasarruf Hesaplayıcı",
      "de": "Energiespar-Rechner",
      "fr": "Calculateur d'économies d'énergie",
      "es": "Calculadora de ahorro energético",
      "ar": "حاسبة توفير الطاقة"
    },
    "shortDescription": {
      "en": "Compare LED, motor and compressor upgrade payback in local currency.",
      "tr": "LED, motor ve kompresör yatırımlarının geri dönüşünü yerel para biriminde karşılaştırın.",
      "de": "Vergleichen Sie Amortisation von LED-, Motor- und Kompressor-Upgrades.",
      "fr": "Comparez retour sur investissement LED, moteur et compresseur.",
      "es": "Compare retorno de LED, motor y compresor.",
      "ar": "قارن استرداد ترقيات LED والمحرك والضاغط."
    },
    "pain": {
      "en": "Energy upgrades stall when payback is unclear in monthly bill terms.",
      "tr": "Geri dönüş net değilse enerji yatırımları ertelenir.",
      "de": "Energie-Upgrades stocken ohne klare Amortisation.",
      "fr": "Les upgrades énergie stagnent sans retour clair.",
      "es": "Mejoras energéticas se posponen sin retorno claro.",
      "ar": "تتوقف ترقيات الطاقة بدون استرداد واضح."
    },
    "publicPromise": {
      "en": "See monthly savings and payback months before capex approval.",
      "tr": "Yatırım onayından önce aylık tasarruf ve geri dönüş ayını görün.",
      "de": "Sehen Sie monatliche Einsparung und Amortisationsmonate vor Capex.",
      "fr": "Voyez économies mensuelles et mois de retour avant capex.",
      "es": "Vea ahorro mensual y meses de retorno antes del capex.",
      "ar": "اعرض التوفير الشهري وأشهر الاسترداد قبل الاستثمار."
    },
    "internalSourceNote": "Strategic report tool 15 — energy savings package.",
    "mappedLiveSlug": "energy-savings-package-calculator"
  },
  {
    "id": "sp-016",
    "slug": "investment-payback-npv-calculator",
    "phase": 3,
    "score": 7.1,
    "status": "live",
    "categoryId": "finance-hr",
    "title": {
      "en": "Investment Payback and NPV Calculator",
      "tr": "Yatırım Geri Dönüş ve NPV Hesaplayıcı",
      "de": "Investitions-Amortisations- und NPV-Rechner",
      "fr": "Calculateur de retour sur investissement et VAN",
      "es": "Calculadora de retorno de inversión y VAN",
      "ar": "حاسبة استرداد الاستثمار وNPV"
    },
    "shortDescription": {
      "en": "Run payback period and NPV with sector discount guidance.",
      "tr": "Sektör iskonto rehberiyle geri dönüş süresi ve NPV hesaplayın.",
      "de": "Berechnen Sie Payback und NPV mit Branchen-Diskontierung.",
      "fr": "Calculez payback et VAN avec guide sectoriel d'actualisation.",
      "es": "Calcule payback y VAN con guía de descuento sectorial.",
      "ar": "احسب فترة الاسترداد وNPV مع إرشاد خصم قطاعي."
    },
    "pain": {
      "en": "Capex decisions skip discounted cash-flow checks in small businesses.",
      "tr": "KOBİ'ler yatırım kararında iskontolu nakit akışını atlar.",
      "de": "KMU überspringen bei Investitionen DCF-Prüfungen.",
      "fr": "Les PME ignorent les flux actualisés pour le capex.",
      "es": "Las pymes omiten flujos descontados en capex.",
      "ar": "تتجاهل الشركات الصغيرة التدفقات المخصومة."
    },
    "publicPromise": {
      "en": "Compare investment options with payback and NPV on one decision summary.",
      "tr": "Yatırım seçeneklerini tek karar özetinde payback ve NPV ile karşılaştırın.",
      "de": "Vergleichen Sie Investitionen mit Payback und NPV in einer Übersicht.",
      "fr": "Comparez investissements avec payback et VAN en un résumé.",
      "es": "Compare inversiones con payback y VAN en un resumen.",
      "ar": "قارن الخيارات الاستثمارية بملخص قرار واحد."
    },
    "internalSourceNote": "Strategic report tool 16 — payback NPV.",
    "mappedLiveSlug": "investment-payback-npv-calculator"
  },
  {
    "id": "sp-017",
    "slug": "fire-system-flow-hydrant-calculator",
    "phase": 3,
    "score": 6.7,
    "status": "live",
    "categoryId": "engineering-technical",
    "title": {
      "en": "Fire System Flow and Hydrant Calculator",
      "tr": "Yangın Tesisatı Debi ve Hidrant Hesaplayıcı",
      "de": "Brandanlagen-Durchfluss- und Hydranten-Rechner",
      "fr": "Calculateur de débit incendie et hydrants",
      "es": "Calculadora de caudal contra incendios e hidrantes",
      "ar": "حاسبة تدفق نظام الإطفاء والhydrants"
    },
    "shortDescription": {
      "en": "Estimate fire-system flow and hydrant capacity for permit documentation.",
      "tr": "Ruhsat dokümantasyonu için yangın tesisatı debisi ve hidrant kapasitesini tahmin edin.",
      "de": "Schätzen Sie Brandfluss und Hydrantkapazität für Genehmigungsunterlagen.",
      "fr": "Estimez débit incendie et capacité hydrants pour permis.",
      "es": "Estime caudal contra incendios e hidrantes para permisos.",
      "ar": "قدّر تدفق نظام الإطفاء وسعة الحنفيات للتصاريح."
    },
    "pain": {
      "en": "Small facilities outsource basic fire hydraulic checks they could scope first.",
      "tr": "Küçük tesisler önce kapsamlandırılabilecek yangın hidroliğini dışarı verir.",
      "de": "Kleine Betriebe outsourcen Brandhydraulik die vorab scoping braucht.",
      "fr": "Les petits sites externalisent l'hydraulique incendie évitable.",
      "es": "Instalaciones pequeñas externalizan hidráulica evitable.",
      "ar": "تexternalize المنشآت الصغيرة فحوصات الحريق."
    },
    "publicPromise": {
      "en": "Produce first-pass fire flow numbers aligned with local checklist inputs.",
      "tr": "Yerel kontrol listesi girdilerine uygun ilk yangın debi rakamlarını üretin.",
      "de": "Erzeugen Sie Erstberechnung Brandfluss passend zur lokalen Checkliste.",
      "fr": "Produisez un premier débit incendie aligné sur la checklist locale.",
      "es": "Produzca primer caudal incendio alineado con checklist local.",
      "ar": "أنتج أرقام تدفق أولية متوافقة مع قائمة التحقق."
    },
    "internalSourceNote": "Strategic report tool 17 — fire system; planned.",
    "mappedLiveSlug": "fire-system-flow-hydrant-calculator"
  },
  {
    "id": "sp-018",
    "slug": "annual-leave-severance-notice-calculator",
    "phase": 3,
    "score": 6.6,
    "status": "live",
    "categoryId": "finance-hr",
    "title": {
      "en": "Annual Leave, Severance and Notice Calculator",
      "tr": "Yıllık İzin, Kıdem ve İhbar Tazminatı Hesaplayıcı",
      "de": "Urlaubs-, Abfindungs- und Kündigungsfrist-Rechner",
      "fr": "Calculateur congés, indemnités et préavis",
      "es": "Calculadora de vacaciones, indemnización y preaviso",
      "ar": "حاسبة الإجازة والمكافأة والإشعار"
    },
    "shortDescription": {
      "en": "Calculate annual leave, severance and notice amounts under current rules.",
      "tr": "Güncel kurallara göre yıllık izin, kıdem ve ihbar tutarlarını hesaplayın.",
      "de": "Berechnen Sie Urlaub, Abfindung und Kündigungsfrist nach aktuellen Regeln.",
      "fr": "Calculez congés, indemnités et préavis selon règles actuelles.",
      "es": "Calcule vacaciones, indemnización y preaviso según reglas actuales.",
      "ar": "احسب الإجازة والمكافأة والإشعار وفق القواعد الحالية."
    },
    "pain": {
      "en": "HR teams rework exit-cost math whenever regulations or ceilings change.",
      "tr": "Mevzuat değişince çıkış maliyeti yeniden hesaplanır; hata riski artar.",
      "de": "HR muss Austrittskosten bei Regeländerungen neu rechnen.",
      "fr": "Les RH recalculent les coûts de sortie à chaque changement réglementaire.",
      "es": "RR. HH. recalcula costes de salida con cada cambio normativo.",
      "ar": "تعيد الموارد البشرية حساب تكلفة المغادرة عند تغيّر القواعد."
    },
    "publicPromise": {
      "en": "Model exit packages with gross and net views before signatures.",
      "tr": "İmza öncesi brüt ve net görünümle çıkış paketini modelleyin.",
      "de": "Modellieren Sie Austrittspakete mit Brutto- und Nettosicht vor Unterschrift.",
      "fr": "Modélisez packages de sortie brut/net avant signature.",
      "es": "Modele paquetes de salida bruto/neto antes de firmar.",
      "ar": "نمذج حزم المغادرة brut/net قبل التوقيع."
    },
    "internalSourceNote": "Strategic report tool 18 — leave severance notice.",
    "mappedLiveSlug": "annual-leave-severance-notice-calculator"
  },
  {
    "id": "sp-019",
    "slug": "hydraulic-pneumatic-cylinder-force-calculator",
    "phase": 4,
    "score": 6.4,
    "status": "live",
    "categoryId": "engineering-technical",
    "title": {
      "en": "Hydraulic and Pneumatic Cylinder Force Calculator",
      "tr": "Hidrolik ve Pnömatik Silindir Kuvvet Hesaplayıcı",
      "de": "Hydraulik-/Pneumatikzylinder-Kraft-Rechner",
      "fr": "Calculateur de force vérin hydraulique/pneumatique",
      "es": "Calculadora de fuerza de cilindro hidráulico/neumático",
      "ar": "حاسبة قوة الأسطوانة الهيدraulique/ال neumática"
    },
    "shortDescription": {
      "en": "Calculate push and pull force for hydraulic and pneumatic cylinders.",
      "tr": "Hidrolik ve pnömatik silindirler için itme ve çekme kuvvetini hesaplayın.",
      "de": "Berechnen Sie Druck- und Zugkraft für Hydraulik- und Pneumatikzylinder.",
      "fr": "Calculez force poussée/traction pour vérins hydrauliques et pneumatiques.",
      "es": "Calcule fuerza empuje/tracción en cilindros hidráulicos y neumáticos.",
      "ar": "احسب قوة الدفع والسحب للأسطوانات."
    },
    "pain": {
      "en": "Wrong bore or pressure leads to undersized actuators and rework.",
      "tr": "Yanlış çap veya basınç yetersiz aktüatör ve rework doğurur.",
      "de": "Falscher Bohrung/Druck führt zu unterdimensionierten Aktoren.",
      "fr": "Alésage ou pression erronés mènent à actionneurs sous-dimensionnés.",
      "es": "Diámetro o presión incorrectos causan actuadores pequeños.",
      "ar": "القطر أو الضغط الخاطئ يؤدي لمح actuators صغيرة."
    },
    "publicPromise": {
      "en": "Validate cylinder selection with standard bore library and safety factor.",
      "tr": "Standart çap kütüphanesi ve emniyet katsayısıyla silindir seçimini doğrulayın.",
      "de": "Validieren Sie Zylinderwahl mit Standardbohrungen und Sicherheitsfaktor.",
      "fr": "Validez le vérin avec bibliothèque d'alésages et facteur de sécurité.",
      "es": "Valide cilindro con biblioteca de diámetros y factor de seguridad.",
      "ar": "تحقق من اختيار الأسطوانة بمكتبة الأقطار وعامل الأمان."
    },
    "internalSourceNote": "Strategic report tool 19 — cylinder force; planned.",
    "mappedLiveSlug": "hydraulic-pneumatic-cylinder-force-calculator"
  },
  {
    "id": "sp-020",
    "slug": "belt-pulley-speed-length-calculator",
    "phase": 4,
    "score": 6.2,
    "status": "live",
    "categoryId": "engineering-technical",
    "title": {
      "en": "Belt Pulley Speed and Length Calculator",
      "tr": "Kayış Kasnak Devir ve Uzunluk Hesaplayıcı",
      "de": "Riemenscheiben-Drehzahl- und Längen-Rechner",
      "fr": "Calculateur vitesse et longueur courroie/poulie",
      "es": "Calculadora de velocidad y longitud de correa/polea",
      "ar": "حاسبة سرعة وطول الحزام/البكرة"
    },
    "shortDescription": {
      "en": "Calculate belt-pulley speed ratio and belt length for V and timing belts.",
      "tr": "V ve triger kayışlar için kasnak devir oranı ve kayış uzunluğunu hesaplayın.",
      "de": "Berechnen Sie Übersetzung und Riemenlänge für Keil- und Zahnriemen.",
      "fr": "Calculez rapport de vitesse et longueur de courroie.",
      "es": "Calcule relación de velocidad y longitud de correa.",
      "ar": "احسب نسبة السرعة وطول الحزام."
    },
    "pain": {
      "en": "Drive changes fail when speed ratio or belt length is mis-specified.",
      "tr": "Devir oranı veya kayış uzunluğu hatalıysa tahrik değişimi başarısız olur.",
      "de": "Antriebswechsel scheitern bei falscher Übersetzung oder Riemenlänge.",
      "fr": "Les changements d'entraînement échouent si ratio ou longueur est faux.",
      "es": "Cambios de transmisión fallan con ratio o longitud incorrectos.",
      "ar": "تفشل تغييرات النقل عند خطأ النسبة أو الطول."
    },
    "publicPromise": {
      "en": "Size belt drives with pulley diameters and center distance in minutes.",
      "tr": "Kasnak çapları ve merkez mesafesiyle kayış tahrikini dakikalar içinde boyutlandırın.",
      "de": "Dimensionieren Sie Riemenantriebe in Minuten.",
      "fr": "Dimensionnez courroies en minutes avec poulies et entraxe.",
      "es": "Dimensiona correas en minutos con poleas y distancia.",
      "ar": "حدّد أحزمة النقل في دقائق."
    },
    "internalSourceNote": "Strategic report tool 20 — belt pulley; partial live mapping.",
    "mappedLiveSlug": "belt-pulley-speed-length-calculator"
  },
  {
    "id": "sp-021",
    "slug": "quality-cost-paf-calculator",
    "phase": 4,
    "score": 6.1,
    "status": "live",
    "categoryId": "quality-lean",
    "title": {
      "en": "Quality Cost PAF Calculator",
      "tr": "Kalite Maliyeti PAF Hesaplayıcı",
      "de": "Qualitätskosten-PAF-Rechner",
      "fr": "Calculateur coûts qualité PAF",
      "es": "Calculadora de coste de calidad PAF",
      "ar": "حاسبة تكلفة الجودة PAF"
    },
    "shortDescription": {
      "en": "Split quality cost into prevention, appraisal and failure categories (PAF).",
      "tr": "Kalite maliyetini önleme, değerlendirme ve hata (PAF) kalemlerine ayırın.",
      "de": "Teilen Sie Qualitätskosten in Prävention, Bewertung und Fehler (PAF).",
      "fr": "Répartissez coûts qualité en prévention, évaluation et échec (PAF).",
      "es": "Separe costes de calidad en prevención, evaluación y fallo (PAF).",
      "ar": "قسّم تكلفة الجودة إلى PAF."
    },
    "pain": {
      "en": "External failure cost is rarely tracked even though it dominates quality spend.",
      "tr": "Dış hata maliyeti nadiren izlenir oysa kalite harcamasını domine eder.",
      "de": "Externe Fehlerkosten werden selten erfasst obwohl dominant.",
      "fr": "Le coût d'échec externe est rarement suivi.",
      "es": "El coste de fallo externo rara vez se rastrea.",
      "ar": "نادرًا ما تُ tracked تكاليف الفشل الخارجي."
    },
    "publicPromise": {
      "en": "Visualize PAF mix to prioritize prevention budget with evidence.",
      "tr": "PAF dağılımını görerek önleme bütçesini kanıtla önceliklendirin.",
      "de": "Visualisieren Sie PAF-Mix für Präventionsbudget mit Beleg.",
      "fr": "Visualisez le mix PAF pour prioriser prévention.",
      "es": "Visualice mix PAF para priorizar prevención.",
      "ar": "اعرض mix PAF ل prioritize الميزانية."
    },
    "internalSourceNote": "Strategic report tool 21 — quality PAF; planned.",
    "mappedLiveSlug": "quality-cost-paf-calculator"
  },
  {
    "id": "sp-022",
    "slug": "pressure-vessel-wall-thickness-calculator",
    "phase": 4,
    "score": 5.9,
    "status": "live",
    "categoryId": "engineering-technical",
    "title": {
      "en": "Pressure Vessel Wall Thickness Calculator",
      "tr": "Basınçlı Kap Cidar Kalınlığı Hesaplayıcı",
      "de": "Druckbehälter-Wanddicken-Rechner",
      "fr": "Calculateur d'épaisseur paroi récipient pression",
      "es": "Calculadora de espesor de pared de recipiente a presión",
      "ar": "حاسبة سمك جدار الوعاء المضغوط"
    },
    "shortDescription": {
      "en": "Estimate minimum wall thickness for common pressure vessel geometries.",
      "tr": "Yaygın basınçlı kap geometrileri için minimum cidar kalınlığını tahmin edin.",
      "de": "Schätzen Sie Mindestwanddicke für gängige Druckbehältergeometrien.",
      "fr": "Estimez épaisseur paroi minimale pour géométries courantes.",
      "es": "Estime espesor mínimo de pared para geometrías comunes.",
      "ar": "قدّر最小 سمك الجدار للأشكال الشائعة."
    },
    "pain": {
      "en": "Fabricators risk unsafe tanks when thickness rules are applied from memory.",
      "tr": "Cidar kalınlığı hafızadan uygulanırsa güvensiz tank riski artar.",
      "de": "Falscher Wanddicken-Gedächtniswert riskiert unsichere Behälter.",
      "fr": "L'épaisseur de mémoire risque des cuves dangereuses.",
      "es": "Espesor de memoria arriesga tanques inseguros.",
      "ar": "تطبيق السمك من الذاكرة يخاطر بالسلامة."
    },
    "publicPromise": {
      "en": "Screen cylindrical and spherical vessels with material and safety inputs.",
      "tr": "Malzeme ve emniyet girdileriyle silindirik ve küresel kapları tarayın.",
      "de": "Prüfen Sie Zylinder- und Kugelbehälter mit Material und Sicherheit.",
      "fr": "Filtrez cuves cylindriques et sphériques avec matériau et sécurité.",
      "es": "Evalúe vasijas cilíndricas y esféricas con material y seguridad.",
      "ar": "افحص الأوعية الأسطوانية والكروية."
    },
    "internalSourceNote": "Strategic report tool 22 — pressure vessel; planned.",
    "mappedLiveSlug": "pressure-vessel-wall-thickness-calculator"
  },
  {
    "id": "sp-023",
    "slug": "value-stream-map-vsm-calculator",
    "phase": 4,
    "score": 5.7,
    "status": "live",
    "categoryId": "quality-lean",
    "title": {
      "en": "Value Stream Map VSM Calculator",
      "tr": "Değer Akış Haritası VSM Hesaplayıcı",
      "de": "Value-Stream-Map-VSM-Rechner",
      "fr": "Calculateur VSM carte de flux de valeur",
      "es": "Calculadora VSM mapa de flujo de valor",
      "ar": "حاسبة VSM خريطة تدفق القيمة"
    },
    "shortDescription": {
      "en": "Build current-state value-stream map metrics for lean workshops.",
      "tr": "Yalın atölyeler için mevcut durum değer akış haritası metriklerini oluşturun.",
      "de": "Erstellen Sie Ist-Zustand-VSM-Metriken für Lean-Workshops.",
      "fr": "Construisez métriques VSM état actuel pour ateliers lean.",
      "es": "Construya métricas VSM estado actual para talleres lean.",
      "ar": "أنشئ مقاييس VSM للحالة الحالية."
    },
    "pain": {
      "en": "VSM work stays on whiteboards and cannot be compared week to week.",
      "tr": "VSM çalışması tahtada kalır; haftalık karşılaştırılamaz.",
      "de": "VSM bleibt am Whiteboard ohne Wochenvergleich.",
      "fr": "Le VSM reste au tableau sans comparaison hebdomadaire.",
      "es": "VSM permanece en pizarra sin comparación semanal.",
      "ar": "VSM يبقى على السبورة دون مقارنة."
    },
    "publicPromise": {
      "en": "Capture value-added ratio and lead time in a repeatable digital template.",
      "tr": "Katma değer oranı ve lead time'ı tekrarlanabilir dijital şablonda kaydedin.",
      "de": "Erfassen Sie VA-Ratio und Durchlaufzeit in digitaler Vorlage.",
      "fr": "Capturez ratio VA et lead time dans modèle digital.",
      "es": "Capture ratio VA y lead time en plantilla digital.",
      "ar": "سجّل نسبة القيمة المضافة وlead time."
    },
    "internalSourceNote": "Strategic report tool 23 — VSM; planned.",
    "mappedLiveSlug": "value-stream-map-vsm-calculator"
  }
] as const;
