import {
  CASE_STUDY_DISCLAIMER,
  CASE_STUDY_REPRESENTATIVE_LABEL,
  type CaseStudyEntry,
} from "@/lib/case-studies/case-study-types";

export const CASE_STUDY_REGISTRY: readonly CaseStudyEntry[] = [
  {
    slug: "representative-welding-shop",
    sector: "welding",
    sectorLabel: "Welding",
    title: "Representative welding shop scenario",
    scenarioKind: "representative_scenario",
    problem:
      "A fab shop quotes labor and material but under-loads fit-up, rework, and gas consumables — visible margin erodes after callbacks.",
    toolSlug: "welding-bid-risk-analyzer",
    toolTitle: "Welding Bid Risk Analyzer",
    inputSummary: [
      "Material cost, labor hours, labor rate",
      "Gas/consumables, fit-up hours, rework risk %",
      "Target margin",
    ],
    calculationLogic:
      "Base weld cost loaded with hidden multipliers for fit-up, rework buffer, and volatility band; minimum safe price at target margin.",
    lossType: "labor_rework",
    lossTypeLabel: "Rework & fit-up buffer",
    suggestedAction: "Compare quoted price to minimum safe floor before accepting the job.",
    expectedImpact: "Modeled monthly waste exposure if quoted below P90 cost band — illustrative range only.",
    assumptions: [
      "Flat labor rate; consumables as entered",
      "Rework risk percent drives tolerance multiplier",
      CASE_STUDY_REPRESENTATIVE_LABEL,
    ],
    disclaimer: CASE_STUDY_DISCLAIMER,
  },
  {
    slug: "representative-cnc-job-shop",
    sector: "cnc",
    sectorLabel: "CNC Manufacturing",
    title: "Representative CNC quote scenario",
    scenarioKind: "representative_scenario",
    problem:
      "Programming and setup time are omitted from quick quotes; machine time alone understates true job cost.",
    toolSlug: "cnc-quote-risk-analyzer",
    toolTitle: "CNC Audit Engine",
    inputSummary: ["Machine time, setup time, material cost", "Tooling wear, target margin"],
    calculationLogic:
      "Loaded direct cost with programming/setup buffers and margin floor via governed premium decision engine.",
    lossType: "schedule_delay",
    lossTypeLabel: "Setup & programming leak",
    suggestedAction: "Reprice if customer offer sits below minimum safe price.",
    expectedImpact: "Estimated impact range on per-job margin — not verified savings.",
    assumptions: ["User-provided machine and setup hours", CASE_STUDY_REPRESENTATIVE_LABEL],
    disclaimer: CASE_STUDY_DISCLAIMER,
  },
  {
    slug: "representative-hvac-install",
    sector: "hvac",
    sectorLabel: "HVAC",
    title: "Representative HVAC project scenario",
    scenarioKind: "representative_scenario",
    problem:
      "Equipment and duct costs are visible; callback risk and commissioning buffers often missing from bids.",
    toolSlug: "hvac-project-margin-guard",
    toolTitle: "HVAC Project Margin Guard",
    inputSummary: [
      "Equipment, ductwork, labor hours/rate",
      "Commissioning cost, callback risk %",
    ],
    calculationLogic: "Equipment + labor + callback reserve; P90 floor and safe price at target margin.",
    lossType: "margin_leak",
    lossTypeLabel: "Callback & commissioning exposure",
    suggestedAction: "Hold margin band before signing install contract.",
    expectedImpact: "Modeled waste exposure if bid ignores callback buffer.",
    assumptions: [CASE_STUDY_REPRESENTATIVE_LABEL],
    disclaimer: CASE_STUDY_DISCLAIMER,
  },
  {
    slug: "representative-plumbing-panel",
    sector: "plumbing-electrical",
    sectorLabel: "Plumbing / Electrical",
    title: "Representative panel & plumbing job scenario",
    scenarioKind: "representative_scenario",
    problem:
      "Parts and labor quoted separately; inspection risk and callback trips compress net margin.",
    toolSlug: "plumbing-job-margin-verdict",
    toolTitle: "Plumbing Job Margin Verdict",
    inputSummary: ["Parts cost, labor hours, fixture count", "Callback risk %, target margin"],
    calculationLogic: "Direct cost stack with inspection/callback multipliers and safe price floor.",
    lossType: "labor_rework",
    lossTypeLabel: "Callback & inspection risk",
    suggestedAction: "Reprice or reduce scope if quote below safe floor.",
    expectedImpact: "Illustrative per-job margin pressure range.",
    assumptions: [CASE_STUDY_REPRESENTATIVE_LABEL],
    disclaimer: CASE_STUDY_DISCLAIMER,
  },
  {
    slug: "representative-sheet-metal-fab",
    sector: "sheet-metal",
    sectorLabel: "Sheet Metal",
    title: "Representative sheet metal quote scenario",
    scenarioKind: "representative_scenario",
    problem: "Scrap rate and programming time excluded from laser-cut quotes.",
    toolSlug: "sheet-metal-quote-risk-tool",
    toolTitle: "Sheet Metal Quote Risk Tool",
    inputSummary: [
      "Programming, setup, cut time, bends",
      "Material, scrap %, finishing, target margin",
    ],
    calculationLogic: "Labor minutes + scrap-adjusted material + finishing; margin floor via governance oracle path.",
    lossType: "material_scrap",
    lossTypeLabel: "Scrap & programming leak",
    suggestedAction: "Use safe quote floor before releasing fab package.",
    expectedImpact: "Modeled scrap-driven margin erosion — representative only.",
    assumptions: [CASE_STUDY_REPRESENTATIVE_LABEL],
    disclaimer: CASE_STUDY_DISCLAIMER,
  },
  {
    slug: "representative-cleaning-contract",
    sector: "cleaning",
    sectorLabel: "Commercial Cleaning",
    title: "Representative cleaning contract scenario",
    scenarioKind: "representative_scenario",
    problem: "Area and frequency quoted; supplies, travel, and overhead under-modeled.",
    toolSlug: "office-cleaning-bid-optimizer",
    toolTitle: "Office Cleaning Bid Optimizer",
    inputSummary: ["Area, frequency, hourly rate", "Supplies, travel, target margin"],
    calculationLogic: "Monthly labor + supplies + travel; minimum safe monthly bid at margin target.",
    lossType: "margin_leak",
    lossTypeLabel: "Overhead & supply leak",
    suggestedAction: "Adjust bid if client budget sits below safe monthly floor.",
    expectedImpact: "Estimated monthly margin pressure — not a client case study.",
    assumptions: [CASE_STUDY_REPRESENTATIVE_LABEL],
    disclaimer: CASE_STUDY_DISCLAIMER,
  },
  {
    slug: "representative-restaurant-menu",
    sector: "restaurant",
    sectorLabel: "Restaurant",
    title: "Representative menu margin scenario",
    scenarioKind: "representative_scenario",
    problem: "Menu price set from ingredient list alone; waste and prep variance ignored.",
    toolSlug: "menu-profit-leak-detector",
    toolTitle: "Menu Profit Leak Detector",
    inputSummary: ["Selling price, food cost, waste rate", "Target margin"],
    calculationLogic: "Loaded food cost with waste buffer; actual vs target margin verdict.",
    lossType: "food_waste",
    lossTypeLabel: "Food waste & prep leak",
    suggestedAction: "Reprice item or adjust portion if margin below target band.",
    expectedImpact: "Modeled weekly margin leak range — illustrative.",
    assumptions: [CASE_STUDY_REPRESENTATIVE_LABEL],
    disclaimer: CASE_STUDY_DISCLAIMER,
  },
  {
    slug: "representative-ecommerce-returns",
    sector: "ecommerce",
    sectorLabel: "E-commerce",
    title: "Representative return erosion scenario",
    scenarioKind: "representative_scenario",
    problem: "Product margin looks healthy until return rate and handling erode net profit.",
    toolSlug: "return-profit-erosion-tool",
    toolTitle: "Return Profit Erosion Tool",
    inputSummary: ["Product price, cost, return rate %", "Expected revenue, target margin"],
    calculationLogic: "Return-adjusted net profit and margin vs target; erosion drivers surfaced.",
    lossType: "return_erosion",
    lossTypeLabel: "Return & handling erosion",
    suggestedAction: "Adjust pricing or return policy if net margin below threshold.",
    expectedImpact: "Estimated monthly profit erosion range — synthetic scenario.",
    assumptions: [CASE_STUDY_REPRESENTATIVE_LABEL],
    disclaimer: CASE_STUDY_DISCLAIMER,
  },
];

export function listCaseStudies(): readonly CaseStudyEntry[] {
  return CASE_STUDY_REGISTRY;
}

export function getCaseStudyBySlug(slug: string): CaseStudyEntry | undefined {
  return CASE_STUDY_REGISTRY.find((entry) => entry.slug === slug);
}

export function listCaseStudySlugs(): readonly string[] {
  return CASE_STUDY_REGISTRY.map((entry) => entry.slug);
}
